name: Beginning Backup and Restore for SQL Server
name_cn: SQL Server 的备份与恢复入门指南
slug: beginning-backup-and-restore-for-sql-server
toc:
- - '###'
  - 修复思路
- - '###'
  - 修复后的目录
- - '#'
  - SQL Server 备份与恢复指南
- - '##'
  - 第一部分：备份
- - '###'
  - 第 1 章：完整备份
- - '####'
  - 什么是完整备份？
- - '#####'
  - 恢复模式
- - '#####'
  - 备份类型
- - '#####'
  - 恢复模型如何影响备份类型？
- - '####'
  - 准备进行完全备份
- - '#####'
  - 备份数据库：“常规”选项卡
- - '######'
  - 事务日志检查
- - '######'
  - 手动备份数据库
- - '####'
  - 总结
- - '###'
  - 第 2 章：差异备份
- - '####'
  - 什么是差异备份？
- - '#####'
  - 差异备份的依赖关系
- - '####'
  - 为何使用差异备份？
- - '#####'
  - 无差异备份的场景
- - '#####'
  - 运行差异备份的场景
- - '####'
  - 为备份解决方案添加差异备份
- - '####'
  - 为差异备份做准备
- - '####'
  - 执行差异备份
- - '#####'
  - 通过 SSMS 的 GUI 进行备份
- - '#####'
  - 通过 SSMS 的图形界面验证备份
- - '#####'
  - 通过 T-SQL 执行差异备份
- - '####'
  - 小结
- - '###'
  - 第 3 章：事务日志备份
- - '####'
  - 什么是事务日志？
- - '####'
  - 查看事务日志状态
- - '####'
  - 备份事务日志
- - '#####'
  - 通过脚本进行事务日志备份
- - '#####'
  - 通过 SSMS 进行事务日志备份
- - '######'
  - 备份数据库—常规
- - '######'
  - 备份数据库—介质选项
- - '######'
  - 备份数据库 — 备份选项
- - '####'
  - 总结
- - '###'
  - 第 4 章：备份解决方案示例
- - '####'
  - 设置维护计划
- - '#####'
  - 完整备份配置
- - '#####'
  - 定义备份数据库（差异）任务
- - '#####'
  - 差异备份配置
- - '#####'
  - 事务日志备份配置
- - '####'
  - 配置作业
- - '####'
  - 总结
- - '##'
  - 第二部分：还原
- - '###'
  - 第 5 章：完整还原
- - '####'
  - 什么是完全恢复？
- - '####'
  - 恢复 Master 数据库
- - '#####'
  - 以单用户模式启动 SQL Server
- - '#####'
  - 还原主数据库
- - '#####'
  - 将 SQL Server 恢复为多用户模式
- - '####'
  - 从完整备份还原
- - '#####'
  - 使用 SSMS 执行完整还原
- - '######'
  - 时间点恢复
- - '#####'
  - 紧急全量恢复示例
- - '####'
  - 总结
- - '###'
  - 第 6 章：差异备份恢复
- - '####'
  - 什么是差异还原？
- - '####'
  - 使用 SSMS 进行还原
- - '####'
  - 使用 T-SQL 进行还原
- - '####'
  - 小结
- - '###'
  - 第 7 章：事务日志还原
- - '####'
  - 事务日志恢复基础
- - '####'
  - 使用 SSMS 进行恢复
- - '#####'
  - 还原文件和文件组 — 常规
- - '#####'
  - 还原文件和文件组—选项
- - '######'
  - 界面概览
- - '######'
  - 还原选项
- - '######'
  - 恢复状态
- - '######'
  - 恢复策略
- - '######'
  - 完成还原
- - '#####'
  - 时间点还原/恢复
- - '####'
  - 使用 Transact-SQL 还原
- - '#####'
  - 还原文件和文件组模板
- - '####'
  - 总结
- - '###'
  - 第 8 章：还原解决方案示例
- - '####'
  - 页面还原
- - '#####'
  - 查询 msdb..suspect_pages
- - '####'
  - 使用 T-SQL 完成数据库完整恢复
- - '#####'
  - 清单 8-1. 数据库恢复操作步骤
- - '#####'
  - 清单 8-2. 恢复脚本
- - '#####'
  - 清单 8-3. 数据库状态验证
- - '####'
  - 使用 SSMS 完成数据库完整恢复
- - '#####'
  - 恢复序列
- - '#####'
  - 连接到 master 数据库
- - '#####'
  - 还原数据库
- - '####'
  - 数据库快照
- - '#####'
  - 数据库快照如何工作？
- - '#####'
  - 创建数据库快照
- - '#####'
  - 查询数据库快照
- - '#####'
  - 恢复数据库快照
- - '####'
  - 查看备份和还原历史记录
- - '####'
  - 总结
- - '##'
  - 第三部分：完整解决方案
- - '###'
  - 第 9 章：完整备份与还原解决方案
- - '####'
  - SSMS 中的完整备份计划
- - '#####'
  - 定义备份数据库任务选项
- - '#####'
  - 目标配签设置
- - '#####'
  - 选项选项卡
- - '######'
  - 理解 SQL Server 备份中的块大小与最大传输大小
- - '####'
  - 计划完整备份
- - '####'
  - 更新 SQL Server 代理作业
- - '#####'
  - 常规选项卡
- - '#####'
  - 步骤选项卡
- - '######'
  - 作业步骤属性 - Subplan_1 (常规选项卡)
- - '######'
  - 作业步骤属性 - Subplan_1（高级选项卡）
- - '#####'
  - 计划选项卡
- - '#####'
  - 警报选项卡
- - '#####'
  - 通知选项卡
- - '######'
  - 设置操作员
- - '####'
  - 测试完整备份计划
- - '####'
  - SSMS 中的完整恢复计划
- - '#####'
  - T-SQL 恢复命令
- - '#####'
  - SQL Server 代理恢复作业
- - '#####'
  - 复制并重命名当前备份文件
- - '#####'
  - 还原数据
- - '####'
  - 总结
- - '###'
  - 第 10 章：差异备份和还原解决方案
- - '####'
  - 在 SSMS 中添加差异备份
- - '####'
  - 计划差异备份
- - '####'
  - 更新 SQL Server Agent 作业
- - '#####'
  - 常规选项卡
- - '#####'
  - 步骤选项卡
- - '#####'
  - 计划选项卡
- - '#####'
  - 警报选项卡
- - '#####'
  - 通知选项卡
- - '####'
  - 测试差异备份计划
- - '####'
  - 在 SSMS 中创建差异还原计划
- - '#####'
  - T-SQL 还原命令
- - '#####'
  - SQL Server 代理恢复作业
- - '#####'
  - 复制并重命名当前备份
- - '#####'
  - 恢复数据
- - '####'
  - 摘要
- - '###'
  - 第 11 章：事务日志备份和还原解决方案
- - '####'
  - 在 SSMS 中添加事务日志备份
- - '####'
  - 计划事务日志备份
- - '####'
  - 更新 SQL Server Agent 作业
- - '#####'
  - 常规选项卡
- - '#####'
  - 步骤选项卡
- - '#####'
  - 通知选项卡
- - '####'
  - 测试事务日志备份计划
- - '####'
  - 在 SSMS 中进行事务日志恢复
- - '#####'
  - 创建测试数据
- - '#####'
  - 备份事务日志
- - '####'
  - 复制和重命名备份文件
- - '####'
  - T-SQL 恢复命令
- - '#####'
  - 场景 1：完整恢复
- - '#####'
  - 场景 2：完整和差异恢复
- - '#####'
  - 场景 3：完整、差异和事务日志恢复
- - '####'
  - 总结
- - '##'
  - 索引
- - '##'
  - 关于作者和技术评审者
- - '###'
  - 关于作者
- - '###'
  - 关于技术评审者
- - '###'
  - 主要修复说明
