name: Expert SQL server 2008 development
name_cn: SQL Server 2008 高级开发指南
slug: expert-sql-server-2008-development
toc:
- - '#'
  - 精通 SQL Server 2008 开发
- - '##'
  - 致读者
- - '##'
  - 作者信息
- - '##'
  - Apress 出版社路线图
- - '##'
  - 源代码
- - '##'
  - 书籍详情
- - '##'
  - 印制详情
- - '##'
  - 版权信息
- - '##'
  - 内容概览
- - '##'
  - 前言材料
- - '##'
  - 本书章节
- - '##'
  - 目录
- - '##'
  - 索引
- - '#'
  - 第 1 章：面向数据库世界的软件开发方法论
- - '##'
  - 架构再探
- - '###'
  - 耦合性
- - '###'
  - 内聚性
- - '###'
  - 封装
- - '###'
  - 接口
- - '###'
  - 接口即契约
- - '###'
  - 接口设计
- - '##'
  - 集成数据库与面向对象系统
- - '###'
  - 数据逻辑
- - '####'
  - 数据规则到底属于哪里？
- - '###'
  - 业务逻辑
- - '###'
  - 应用逻辑
- - '###'
  - “对象-关系阻抗不匹配”
- - '###'
  - 表是伪装的类吗？
- - '###'
  - 建模继承
- - '###'
  - ORM：一个制造诸多问题的解决方案
- - '##'
  - 引入“数据库即 API”的思维方式
- - '##'
  - 伟大的平衡之道
- - '###'
  - 性能
- - '###'
  - 可测试性
- - '###'
  - 可维护性
- - '###'
  - 安全性
- - '###'
  - 考虑未来需求
- - '##'
  - 总结
- - '#'
  - 第 2 章：数据库编程最佳实践
- - '##'
  - 防御性编程
- - '###'
  - 防御性编程的态度
- - '###'
  - 为何对数据库开发采用防御性方法？
- - '##'
  - SQL 编程最佳实践技巧
- - '###'
  - 识别代码中的隐藏假设
- - '###'
  - 不要走捷径
- - '###'
  - 测试
- - '###'
  - 代码审查
- - '###'
  - 验证所有输入
- - '###'
  - 确保代码面向未来
- - '###'
  - 限制暴露范围
- - '###'
  - 遵循良好的编码规范
- - '####'
  - 注释
- - '####'
  - 缩进与语句块
- - '####'
  - 如果一切都失败了...
- - '###'
  - 创建健康的开发环境
- - '##'
  - 总结
- - '#'
  - 第 3 章：测试数据库例程
- - '##'
  - 测试方法
- - '###'
  - 单元测试与功能测试
- - '###'
  - 单元测试框架
- - '###'
  - 回归测试
- - '###'
  - 实施数据库测试流程与规程的指南
- - '####'
  - 为什么测试很重要？
- - '####'
  - 哪种测试是重要的？
- - '####'
  - 需要多少测试？
- - '####'
  - 管理层会认同吗？
- - '##'
  - 性能监控工具
- - '###'
  - 实时客户端监控
- - '###'
  - 服务器端跟踪
- - '###'
  - 系统监控
- - '###'
  - 动态管理视图 (DMVs)
- - '###'
  - 扩展事件
- - '###'
  - 数据收集器
- - '##'
  - 分析性能数据
- - '###'
  - 捕获基准指标
- - '###'
  - 宏观分析
- - '###'
  - 精细分析
- - '###'
  - 解决问题：只关注明显问题足够吗？
- - '##'
  - 总结
- - '#'
  - 第 4 章：错误与异常
- - '##'
  - SQL Server 中异常如何工作
- - '###'
  - 语句级异常
- - '###'
  - 批处理级异常
- - '###'
  - 连接和服务器级异常
- - '##'
  - '`XACT_ABORT` 设置'
- - '##'
  - 剖析错误消息
- - '###'
  - 错误编号
- - '###'
  - 错误级别
- - '###'
  - 错误状态
- - '###'
  - 附加信息
- - '##'
  - SQL Server 的 `RAISERROR` 函数
- - '###'
  - 格式化错误消息
- - '###'
  - 创建持久化的自定义错误消息
- - '###'
  - 记录用户抛出的异常
- - '###'
  - 使用跟踪监控异常事件
- - '##'
  - 异常处理
- - '###'
  - 为什么要在 T-SQL 中处理异常？
- - '###'
  - 使用 `@@ERROR` 进行异常“处理”
- - '###'
  - SQL Server 的 `TRY/CATCH` 语法
- - '###'
  - 在 Catch 块中获取扩展的错误信息
- - '####'
  - 重新抛出异常
- - '####'
  - 何时应使用 `TRY/CATCH`？
- - '####'
  - 使用 `TRY/CATCH` 构建重试逻辑
- - '###'
  - 异常处理与 SQLCLR
- - '##'
  - 事务与异常
- - '###'
  - 关于事务中止的误解
- - '###'
  - XACT_ABORT：将神话变为（半）现实
- - '###'
  - TRY/CATCH 与注定失败的事务
- - '##'
  - 总结
- - '#'
  - 第 5 章：权限与授权
- - '##'
  - 最小权限原则
- - '##'
  - 在 SQL Server 中创建代理
- - '###'
  - 服务器级别代理
- - '###'
  - 数据库级别代理
- - '##'
  - 分层数据安全：洋葱模型
- - '##'
  - 使用架构组织数据
- - '##'
  - 使用 `EXECUTE AS` 进行基本模拟
- - '##'
  - 所有权链
- - '##'
  - 无所有权链的权限提升
- - '###'
  - 存储过程与 `EXECUTE AS`
- - '###'
  - 使用证书对存储过程签名
- - '###'
  - 分配服务器级别权限
- - '##'
  - 总结
- - '#'
  - 第 6 章：加密
- - '##'
  - 你真的需要加密吗？
- - '###'
  - 应该保护什么？
- - '###'
  - 你在防范什么？
- - '##'
  - SQL Server 2008 加密密钥层次结构
- - '###'
  - 自动密钥管理层次结构
- - '####'
  - 对称密钥、非对称密钥与证书
- - '####'
  - 数据库主密钥
- - '####'
  - 服务主密钥
- - '###'
  - 替代加密管理结构
- - '###'
  - 对称密钥分层与轮换
- - '###'
  - 从自动加密层次结构中移除密钥
- - '###'
  - 可扩展密钥管理
- - '##'
  - 数据保护与加密方法
- - '###'
  - 哈希
- - '###'
  - 对称密钥加密
- - '###'
  - 非对称密钥加密
- - '###'
  - 透明数据加密
- - '##'
  - 平衡性能与安全
- - '##'
  - 加密对查询设计的影响
- - '###'
  - 使用哈希消息认证码进行等值匹配
- - '###'
  - 使用 HMAC 子串进行通配符搜索
- - '###'
  - 范围搜索
- - '##'
  - 总结
- - '#'
  - 第 7 章：SQLCLR：架构与设计考量
- - '##'
  - 弥合 SQL/CLR 鸿沟：`SqlTypes` 库
- - '##'
  - 封装代码以促进跨层重用
- - '###'
  - 问题
- - '###'
  - 一个合理的解决方案
- - '###'
  - 简单示例：电子邮件地址格式验证
- - '##'
  - SQLCLR 安全性与可靠性特性
- - '###'
  - 安全例外
- - '###'
  - 主机保护例外
- - '###'
  - 对代码安全性的追求
- - '###'
  - 通过程序集引用进行选择性权限提升
- - '###'
  - 处理主机保护权限
- - '###'
  - 处理代码访问安全权限
- - '###'
  - 授予跨程序集权限
- - '##'
  - 数据库可信赖性
- - '###'
  - 强命名
- - '##'
  - 性能对比：SQLCLR vs. TSQL
- - '###'
  - 为质数创建一个“简单筛法”
- - '###'
  - 计算运行聚合
- - '###'
  - 字符串操作
- - '##'
  - 利用 SQLCLR 增强 Service Broker 的横向扩展能力
- - '###'
  - XML 序列化
- - '###'
  - XML 反序列化
- - '###'
  - 使用 SQLCLR 进行二进制序列化
- - '###'
  - 二进制反序列化
- - '##'
  - 总结
- - '#'
  - 第 8 章：动态 T-SQL
- - '##'
  - 动态 T-SQL 与即席 T-SQL
- - '##'
  - 存储过程与即席 SQL 的争论
- - '##'
  - 为何选择动态方式？
- - '##'
  - 编译与参数化
- - '##'
  - 自动参数化
- - '##'
  - 应用层参数化
- - '##'
  - 参数化与缓存对性能的影响
- - '##'
  - 支持可选参数
- - '###'
  - 通过静态 T-SQL 实现可选参数
- - '###'
  - 转向动态：使用 EXECUTE
- - '##'
  - SQL 注入
- - '##'
  - sp_executesql：一个更好的 EXECUTE
- - '##'
  - 性能对比
- - '##'
  - 动态 SQL 的安全考量
- - '###'
  - 对引用对象的权限
- - '###'
  - 接口规则
- - '##'
  - 总结
- - '#'
  - 第 9 章：为应用并发设计系统
- - '##'
  - 业务层面：当进程冲突时应该发生什么？
- - '##'
  - 隔离级别与事务行为
- - '###'
  - 阻塞型隔离级别
- - '####'
  - READ COMMITTED 隔离
- - '####'
  - REPEATABLE READ 隔离
- - '####'
  - SERIALIZABLE 隔离
- - '###'
  - 非阻塞型隔离级别
- - '####'
  - READ UNCOMMITTED 隔离
- - '####'
  - 快照隔离
- - '##'
  - 为最坏情况做准备：悲观并发控制
- - '##'
  - 逐步构建解决方案
- - '##'
  - 在写入时强制实施悲观锁
- - '##'
  - 应用程序锁：推广悲观并发控制
- - '##'
  - 寄望于最好情况：乐观并发控制
- - '##'
  - 拥抱冲突：多值并发控制
- - '##'
  - 在并发用户间共享资源
- - '###'
  - 控制资源分配
- - '###'
  - 计算有效和共享的最大资源分配
- - '###'
  - 控制并发请求处理
- - '##'
  - 总结
- - '#'
  - 第 10 章：处理空间数据
- - '##'
  - 空间参考系统
- - '###'
  - 地理坐标系
- - '###'
  - 基准
- - '##'
  - 标准符合性
- - '##'
  - 精度
- - '##'
  - 技术限制与性能
- - '##'
  - 创建空间数据
- - '###'
  - 众所周知的文本
- - '###'
  - 众所周知的二进制
- - '###'
  - 地理标记语言
- - '##'
  - 导入数据
- - '##'
  - 查询空间数据
- - '###'
  - 最近邻查询
- - '###'
  - 查找给定边界框内的位置
- - '##'
  - 空间索引
- - '###'
  - 空间索引如何工作？
- - '###'
  - 优化网格
- - '##'
  - 总结
- - '#'
  - 第 11 章：处理时态数据
- - '##'
  - SQL Server 的日期/时间数据类型
- - '##'
  - 输入日期格式
- - '##'
  - 输出日期格式
- - '##'
  - 高效查询日期/时间列
- - '##'
  - 日期/时间计算
- - '###'
  - 截断 datetime 值的时间部分
- - '###'
  - 查找相对日期
- - '###'
  - 生日蛋糕上有多少根蜡烛？
- - '###'
  - 使用日历表定义周期
- - '##'
  - 处理时区
- - '###'
  - 存储 UTC 时间
- - '###'
  - 使用 datetimeoffset 类型
- - '##'
  - 使用时间间隔
- - '###'
  - 建模和查询连续区间
- - '###'
  - 建模和查询独立区间
- - '###'
  - 重叠区间
- - '###'
  - 时间切片
- - '###'
  - 建模持续时间
- - '##'
  - 管理双时态数据
- - '##'
  - 总结
- - '#'
  - 第 12 章：树、层次结构与图
- - '##'
  - 术语：一切都是图
- - '##'
  - 基础：邻接表与图
- - '###'
  - 约束边
- - '###'
  - 基本图查询：我与谁相连？
- - '###'
  - 遍历图
- - '##'
  - 邻接表层次结构
- - '###'
  - 查找直接后代
- - '###'
  - 向下遍历层次结构
- - '###'
  - 排序输出
- - '###'
  - CTE 是最佳选择吗？
- - '###'
  - 向上遍历层次结构
- - '###'
  - 插入新节点和重新定位子树
- - '###'
  - 删除现有节点
- - '###'
  - 约束层次结构
- - '##'
  - 持久化物化路径
- - '###'
  - 查找下属
- - '###'
  - 向上导航层次结构
- - '###'
  - 插入节点
- - '###'
  - 重新定位子树
- - '###'
  - 删除节点
- - '###'
  - 约束层次结构
- - '##'
  - hierarchyid 数据类型
- - '###'
  - 查找下属
- - '###'
  - 向上导航层次结构
- - '###'
  - 插入节点
- - '###'
  - 重新定位子树
- - '###'
  - 删除节点
- - '###'
  - 约束层次结构
- - '##'
  - 总结
- - '#'
  - 关于作者
- - '#'
  - 技术审稿人
- - '#'
  - 致谢
- - '#'
  - 前言
