name: Oracle Database 11g Performance Tuning Recipes
name_cn: Oracle 数据库 11g 性能调优秘籍
slug: oracle-database-11g-performance-tuning-recipes
toc:
- - '#'
  - Oracle Database 11g 性能调优方案：问题-解决方案方法
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '##'
  - 第 1 章：优化表性能
- - '###'
  - 1-1. 构建性能最大化的数据库
- - '###'
  - 1-2. 创建表空间以最大化性能
- - '###'
  - 1-3. 匹配表类型与业务需求
- - '###'
  - 1-4. 为性能选择表特性
- - '###'
  - 1-5. 避免创建表时的区分配延迟
- - '###'
  - 1-6. 最大化数据加载速度
- - '###'
  - 1-7. 高效地移除表数据
- - '###'
  - 1-8. 显示自动段指导建议
- - '###'
  - 1-9. 手动生成段指导建议
- - '###'
  - 1-10. 自动通过电子邮件发送段指导输出
- - '###'
  - 1-11. 重建跨越多个块的行
- - '###'
  - 1-12. 释放未使用的表空间
- - '###'
  - 1-13. 为直接路径加载压缩数据
- - '###'
  - 1-14. 为所有 DML 压缩数据
- - '###'
  - 1-15. 在列级别压缩数据
- - '###'
  - 1-16. 监控表使用情况
- - '##'
  - 第 2 章：选择和优化索引
- - '###'
  - 2-1. 理解 B-tree 索引
- - '###'
  - 2-2. 决定为哪些列创建索引
- - '###'
  - 2-3. 创建主键索引
- - '###'
  - 2-4. 创建唯一索引
- - '###'
  - 2-5. 为外键列创建索引
- - '###'
  - 2-6. 决定何时使用组合索引
- - '###'
  - 2-7. 通过压缩减小索引大小
- - '###'
  - 2-8. 实现基于函数的索引
- - '###'
  - 2-9. 为虚拟列创建索引
- - '###'
  - 2-10. 避免索引的集中 I/O
- - '###'
  - 2-11. 添加索引而不影响现有应用程序
- - '###'
  - 2-12. 创建位图索引以支持星型模式
- - '###'
  - 2-13. 创建位图连接索引
- - '###'
  - 2-14. 创建索引组织表
- - '###'
  - 2-15. 监控索引使用情况
- - '###'
  - 2-16. 最大化索引创建速度
- - '###'
  - 2-17. 回收未使用的索引空间
- - '##'
  - 第 3 章：优化实例内存
- - '###'
  - 3-1. 自动化内存管理
- - '###'
  - 3-2. 管理多个缓冲池
- - '###'
  - 3-3. 为内存设置最小值
- - '##'
  - 第 4 章：监控系统性能
- - '###'
  - 4-1. 实施自动工作负载库（AWR）
- - '###'
  - 4-2. 修改统计信息收集间隔和保留周期
- - '###'
  - 4-3. 手动生成 AWR 报告
- - '###'
  - 4-4. 通过 Enterprise Manager 生成 AWR 报告
- - '###'
  - 4-5. 为单个 SQL 语句生成 AWR 报告
- - '###'
  - 4-6. 为您的数据库创建统计基线
- - '###'
  - 4-7. 通过 Enterprise Manager 管理 AWR 基线
- - '###'
  - 4-8. 管理 AWR 统计信息库
- - '###'
  - 4-9. 自动创建 AWR 基线
- - '###'
  - 4-10. 快速分析 AWR 输出
- - '###'
  - 4-11. 手动获取活动会话信息
- - '###'
  - 4-12. 从 Enterprise Manager 获取 ASH 信息
- - '###'
  - 4-13. 从数据字典获取 ASH 信息
- - '##'
  - 第 5 章：最小化系统竞争
- - '###'
  - 5-1. 理解响应时间
- - '###'
  - 5-2. 识别等待最多的 SQL 语句
- - '###'
  - 5-3. 分析等待事件
- - '###'
  - 5-4. 理解等待类别事件
- - '###'
  - 5-5. 检查会话等待
- - '###'
  - 5-6. 按类别检查等待事件
- - '###'
  - 5-7. 解决缓冲区忙等待
- - '###'
  - 5-8. 解决日志文件同步等待
- - '###'
  - 5-9. 最小化由其他会话引起的等待事件
- - '###'
  - 5-10. 减少直接路径读等待事件
- - '###'
  - 5-11. 最小化恢复写入器等待
- - '###'
  - 5-12. 查找谁持有阻塞锁
- - '###'
  - 5-13. 识别被阻塞和阻塞的会话
- - '###'
  - 5-14. 处理阻塞锁
- - '###'
  - 5-15. 识别被锁定的对象
- - '###'
  - '5-16. 解决 `enq: TM` 锁争用'
- - '###'
  - 5-17. 识别最近被锁定的会话
- - '###'
  - 5-18. 分析数据库中最近的等待事件
- - '###'
  - 5-19. 识别因锁定而导致的等待时间
- - '###'
  - 5-20. 最小化锁存争用
- - '###'
  - 5-21. 通过 Oracle 企业管理器管理锁
- - '###'
  - 5-22. 通过 Oracle 企业管理器分析等待
- - '##'
  - 第 6 章：分析操作系统性能
- - '###'
  - 6-1. 检测磁盘空间问题
- - '###'
  - 6-2. 识别系统瓶颈 (`vmstat`)
- - '###'
  - 6-3. 识别系统瓶颈 (Solaris)
- - '###'
  - 6-4. 识别消耗服务器资源最多的进程 (`top`)
- - '###'
  - 6-5. 识别 CPU 和内存瓶颈 (`ps`)
- - '###'
  - 6-6. 识别 I/O 瓶颈
- - '###'
  - 6-7. 识别网络密集型进程
- - '###'
  - 6-8. 排查数据库网络连接问题
- - '###'
  - 6-9. 将资源密集型进程映射到数据库进程
- - '###'
  - 6-10. 终止资源密集型进程
- - '##'
  - 第 7 章：排查数据库故障
- - '###'
  - 7-1. 确定最佳的 Undo 保留期
- - '###'
  - 7-2. 查找消耗 Undo 最多的操作
- - '###'
  - 7-3. 解决 ORA-01555 错误
- - '###'
  - 7-4. 监控临时表空间使用情况
- - '###'
  - 7-5. 识别谁在使用临时表空间
- - '###'
  - 7-6. 解决 “Unable to Extend Temp Segment” 错误
- - '###'
  - 7-7. 解决打开游标错误
- - '###'
  - 7-8. 解决数据库挂起问题
- - '###'
  - 7-9. 调用自动诊断存储库命令解释器
- - '###'
  - 7-10. 通过 `ADRCI` 查看告警日志
- - '###'
  - 7-11. 使用 `ADRCI` 查看事件
- - '###'
  - 7-12. 为 Oracle 支持服务打包事件信息
- - '###'
  - 7-13. 运行数据库健康检查
- - '###'
  - 7-14. 创建 SQL 测试用例
- - '###'
  - 7-15. 生成 AWR 报告
- - '###'
  - 7-16. 比较两个时间段之间的数据库性能
- - '###'
  - 7-17. 分析 AWR 报告
- - '##'
  - 第 8 章：创建高效的 SQL
- - '###'
  - 8-1. 从表中检索所有行
- - '###'
  - 8-2. 从表中检索行的子集
- - '###'
  - 8-3. 连接具有对应行的表
- - '###'
  - 8-4. 当对应行可能缺失时连接表
- - '###'
  - 8-5. 构建简单子查询
- - '###'
  - 8-6. 构建相关子查询
- - '###'
  - 8-7. 比较两个表以找出缺失的行
- - '###'
  - 8-8. 比较两个表以找出匹配的行
- - '###'
  - 8-9. 合并相似 `SELECT` 语句的结果
- - '###'
  - 8-10. 搜索值范围
- - '###'
  - 8-11. 处理空值
- - '###'
  - 8-12. 搜索部分列值
- - '###'
  - 8-13. 在共享池内重用 SQL 语句
- - '###'
  - 8-14. 避免意外的全表扫描
- - '###'
  - 8-15. 创建高效的临时视图
- - '###'
  - 8-16. 避免使用 `NOT` 子句
- - '###'
  - 8-17. 控制事务大小
- - '##'
  - 第 9 章：手动调整 SQL
- - '###'
  - 9-1. 显示查询的执行计划
- - '###'
  - 9-2. 自定义执行计划输出
- - '###'
  - 9-3. 图形化显示执行计划
- - '###'
  - 9-4. 阅读执行计划
- - '###'
  - 9-5. 监控长时间运行的 SQL 语句
- - '###'
  - 9-6. 识别当前正在执行的消耗资源的 SQL 语句
- - '###'
  - 9-7. 查看当前运行 SQL 的执行统计信息
- - '###'
  - 9-8. 监控 SQL 执行计划的进度
- - '###'
  - 9-9. 识别过去执行过的消耗资源的 SQL 语句
- - '###'
  - 9-10. 系统变更后比较 SQL 性能
- - '##'
  - 第 10 章：跟踪 SQL 执行
- - '###'
  - 10-1. 准备环境
- - '###'
  - 10-2. 跟踪特定 SQL 语句
- - '###'
  - 10-3. 在自己的会话中启用跟踪
- - '###'
  - 10-4. 查找跟踪文件
- - '###'
  - 10-5. 检查原始 SQL 跟踪文件
- - '###'
  - 10-6. 分析 Oracle 跟踪文件
- - '###'
  - 10-7. 使用 `TKPROF` 格式化跟踪文件
- - '###'
  - 10-8. 分析 `TKPROF` 输出
- - '###'
  - 10-9. 使用 Oracle Trace Analyzer 分析跟踪文件
- - '###'
  - 10-10. 跟踪并行查询
- - '###'
  - 10-11. 跟踪特定的并行查询进程
- - '###'
  - 10-12. 在 RAC 系统中跟踪并行查询
- - '###'
  - 10-13. 合并多个跟踪文件
- - '###'
  - 10-14. 查找用于跟踪的正确会话
- - '###'
  - 10-15. 跟踪 SQL 会话
- - '###'
  - 10-16. 按进程 ID 跟踪会话
- - '###'
  - 10-17. 跟踪多个会话
- - '###'
  - 10-18. 跟踪实例或数据库
- - '###'
  - 10-19. 为会话生成事件 10046 跟踪
- - '###'
  - 10-20. 为实例生成事件 10046 跟踪
- - '###'
  - 10-21. 在运行中的会话里设置跟踪
- - '###'
  - 10-22. 登录后在会话中启用跟踪
- - '###'
  - 10-23. 跟踪优化器的执行路径
- - '###'
  - 10-24. 生成自动的 Oracle 错误跟踪
- - '###'
  - 10-25. 跟踪后台进程
- - '###'
  - 10-26. 启用 Oracle 监听器跟踪
- - '###'
  - 10-27. 为 Data Guard 设置归档跟踪
- - '##'
  - 第 11 章：自动 SQL 调优
- - '###'
  - 11-1. 显示自动 SQL 调优作业详情
- - '###'
  - 11-2. 显示自动 SQL 调优建议
- - '###'
  - 11-3. 生成用于实施自动调优建议的 SQL 脚本
- - '###'
  - 11-4. 修改自动 SQL 调优功能
- - '###'
  - 11-5. 禁用和启用自动 SQL 调优
- - '###'
  - 11-6. 修改维护窗口属性
- - '###'
  - 11-7. 创建 SQL 调优集对象
- - '###'
  - 11-8. 在 AWR 中查看资源密集型 SQL
- - '###'
  - 11-9. 在内存中查看资源密集型 SQL
- - '###'
  - 11-10. 从 AWR 中的高资源消耗 SQL 填充 SQL 调优集
- - '###'
  - 11-11. 从内存中的资源消耗型 SQL 填充 SQL 调优集
- - '###'
  - 11-12. 用内存中的所有 SQL 填充 SQL 调优集
- - '###'
  - 11-13. 显示 SQL 调优集的内容
- - '###'
  - 11-14. 从 SQL 调优集中选择性删除语句
- - '###'
  - 11-15. 传输 SQL 调优集
- - '###'
  - 11-16. 创建调优任务
- - '###'
  - 11-17. 手动运行 SQL 调优顾问
- - '###'
  - 11-18. 从自动数据库诊断监视器获取 SQL 调优建议
- - '##'
  - 第 12 章：执行计划优化与一致性
- - '###'
  - 12-1. 创建并接受 SQL 配置文件
- - '###'
  - 12-2. 自动接受 SQL 配置文件
- - '###'
  - 12-3. 显示 SQL 配置文件信息
- - '###'
  - 12-4. 禁用 SQL 配置文件
- - '###'
  - 12-5. 删除 SQL 配置文件
- - '###'
  - 12-6. 迁移 SQL 配置文件
- - '###'
  - 12-7. 自动添加计划基线
- - '###'
  - 12-8. 为单个 SQL 语句创建计划基线
- - '###'
  - 12-9. 为 SQL 调优集中包含的 SQL 创建计划基线
- - '###'
  - 12-10. 修改计划基线
- - '###'
  - 12-11. 确定是否存在计划基线
- - '###'
  - 12-12. 显示计划基线执行计划
- - '###'
  - 12-13. 向计划基线添加新计划（演进）
- - '###'
  - 12-14. 禁用计划基线
- - '###'
  - 12-15. 移除计划基线信息
- - '###'
  - 12-16. 传输计划基线
- - '##'
  - 关于作者
- - '##'
  - 关于技术审阅者
- - '##'
  - 索引
