name: Beginning Oracle Application Express 5
name_cn: Oracle Application Express 5 入门指南
slug: beginning-oracle-application-express-5
toc:
- - '#'
  - 《Oracle Application Express 5 入门》
- - '##'
  - 版权信息
- - '##'
  - 谨以此书献给所有寻求知识和更深入理解的人们。希望随着你们技能的增长，你们也能继续分享这份财富。
- - '#'
  - 目录
- - '##'
  - 第 1 章：APEX 5.0 简介
- - '###'
  - 1. 什么是 APEX？
- - '###'
  - 2. APEX 简史
- - '####'
  - 2.1 早期历史
- - '####'
  - 2.2 较近期的历史
- - '###'
  - 3. APEX 5.0 及未来展望
- - '###'
  - 4. 开始前的准备
- - '####'
  - 4.1 访问一个 APEX 实例
- - '####'
  - 4.2 网页浏览器
- - '####'
  - 4.3 SQL Developer
- - '###'
  - 5. 总结
- - '##'
  - 第 2 章：开发者概览
- - '###'
  - 6. 工作区的剖析
- - '###'
  - 7. APEX 用户
- - '###'
  - 8. 应用程序、页面、区域和项目
- - '###'
  - 9. 工作区、应用程序和模式
- - '###'
  - 10. 关于工作区的最后说明
- - '###'
  - 11. APEX 模块概览
- - '###'
  - 12. 主页
- - '###'
  - 13. 应用程序构建器
- - '###'
  - 14. SQL 工作坊
- - '###'
  - 15. 打包的应用程序
- - '###'
  - 16. 管理与团队开发
- - '###'
  - 17. 总结
- - '##'
  - 第 3 章：识别问题与设计解决方案
- - '###'
  - 18. 识别系统需求
- - '####'
  - 18.1 从未是白纸一张
- - '###'
  - 19. 一个破损的系统
- - '####'
  - 19.1 如何修复？
- - '###'
  - 20. 考虑 APEX 的系统设计
- - '####'
  - 20.1 表定义与用户界面默认值
- - '####'
  - 21. APEX 与主键
- - '####'
  - 21.1 业务逻辑 vs. 用户界面逻辑
- - '####'
  - 22. 数据库对象的放置
- - '###'
  - 22. 从理论到实践
- - '###'
  - 23. 总结
- - '##'
  - 第 4 章：SQL 工作坊
- - '###'
  - 24. 使用对象浏览器创建对象
- - '###'
  - 25. 使用数据工作台工具加载数据
- - '###'
  - 26. 创建一个查找表
- - '###'
  - 27. 加载并运行 SQL 脚本
- - '###'
  - 28. 用户界面默认值
- - '####'
  - 28.1 理解用户界面默认值
- - '####'
  - 28.2 为表定义 UI 默认值
- - '###'
  - 29. 总结
- - '##'
  - 第 5 章：应用程序与导航
- - '###'
  - 30. 创建应用程序向导
- - '###'
  - 31. 示例和打包的应用程序
- - '###'
  - 32. 网页表格应用程序
- - '###'
  - 33. 从电子表格创建数据库应用程序
- - '###'
  - 34. 从零开始创建应用程序
- - '###'
  - 35. 静态内容区域
- - '###'
  - 36. 公共页面
- - '###'
  - 37. 导航栏条目
- - '###'
  - 38. 全局页面
- - '###'
  - 39. 面包屑区域
- - '###'
  - 40. 面包屑条目
- - '###'
  - 41. 列表
- - '###'
  - 42. 值列表
- - '####'
  - 43. 静态值列表
- - '####'
  - 44. 动态值列表
- - '###'
  - 45. 总结
- - '##'
  - 第 6 章：表单和报表：基础篇
- - '###'
  - 46. APEX 表单
- - '###'
  - 47. 基于表的表单
- - '####'
  - 47.1 创建基于表的表单
- - '####'
  - 48. 修改基于表的表单
- - '####'
  - 49. 探究幕后原理
- - '###'
  - 50. 基于过程的表单
- - '####'
  - 50.1 创建基于过程的表单
- - '####'
  - 51. 修改基于过程的表单
- - '####'
  - 52. 探究幕后原理
- - '###'
  - 53. 主从报表和表单
- - '####'
  - 53.1 创建主从报表和表单
- - '####'
  - 54. 修改主从报表
- - '###'
  - 55. 会话状态
- - '####'
  - 55.1 理解会话状态
- - '####'
  - 56. 共享数据库连接
- - '####'
  - 57. 设置和检索会话状态
- - '####'
  - 58. 查看会话状态
- - '###'
  - 59. APEX 项目
- - '####'
  - 60. 页面项目 vs. 应用程序项目
- - '###'
  - 60. 绑定变量的重要性
- - '###'
  - 61. 内置项目
- - '###'
  - 62. APEX URL 语法
- - '###'
  - 63. 可搜索的 APEX 报表
- - '####'
  - 63.1 创建可搜索的 APEX 报表
- - '####'
  - 64. 添加重置分页
- - '####'
  - 65. 探究幕后原理——APEX 报表
- - '####'
  - 66. 探究幕后原理——APEX 主从表单
- - '###'
  - 67. 关于 APEX 表单的更多内容
- - '####'
  - 67.1 项目布局
- - '####'
  - 68. 在同一行放置多个项目
- - '####'
  - 69. 实现值列表
- - '###'
  - 70. 主从关系清理
- - '###'
  - 71. APEX 帮助
- - '####'
  - 72. 添加帮助文本区域
- - '####'
  - 73. 填充帮助文本
- - '###'
  - 74. 声明式 BLOB
- - '###'
  - 75. 总结
- - '##'
  - 第 7 章：表单和报表：高级篇
- - '###'
  - 76. 表格式表单
- - '####'
  - 76.1 创建表格式表单
- - '####'
  - 77. 修改表格式表单
- - '####'
  - 78. 探究幕后原理
- - '###'
  - 79. 交互式报表
- - '####'
  - 79.1 创建交互式报表
- - '####'
  - 80. 运行交互式报表
- - '####'
  - 81. 按报表限制功能
- - '####'
  - 82. 按列限制功能
- - '####'
  - 82. 使用列标题菜单
- - '####'
  - 83. 按列搜索
- - '####'
  - 84. 选择列
- - '####'
  - 84. 筛选
- - '####'
  - 85. 排序
- - '####'
  - 85. 添加分组中断
- - '####'
  - 86. 高亮显示
- - '####'
  - 87. 计算列
- - '####'
  - 88. 添加聚合
- - '####'
  - 88. 向交互式报表添加图表
- - '####'
  - 89. 分组
- - '####'
  - 90. 数据透视
- - '####'
  - 91. 使用闪回
- - '####'
  - 91. 保存交互式报表
- - '####'
  - 92. 重置交互式报表
- - '####'
  - 92. 获取帮助
- - '####'
  - 93. 添加订阅
- - '####'
  - 94. 下载
- - '####'
  - 95. 修改交互式报表
- - '####'
  - 96. 探究幕后原理
- - '###'
  - 97. 日历
- - '####'
  - 98. 理解日历类型
- - '####'
  - 98. 创建日历
- - '####'
  - 99. 探究幕后原理
- - '###'
  - 99. 图表
- - '####'
  - 100. 为图表编写查询
- - '####'
  - 101. 创建图表
- - '####'
  - 102. 为图表筛选数据
- - '####'
  - 103. 探究幕后原理
- - '###'
  - 104. 总结
- - '##'
  - 第 8 章：编程元素
- - '###'
  - 105. 条件
- - '###'
  - 106. 必填值
- - '###'
  - 107. 验证
- - '####'
  - 107.1 项目级验证
- - '####'
  - 108. 页面级验证
- - '####'
  - 109. 表格式表单验证
- - '###'
  - 110. 计算
- - '####'
  - 110.1 执行
- - '####'
  - 111. 类型
- - '####'
  - 111. 创建计算
- - '###'
  - 112. 过程
- - '####'
  - 113. 执行点
- - '####'
  - 113. 过程类型
- - '####'
  - 114. 帮助台应用程序中的过程
- - '###'
  - 115. PL/SQL 区域
- - '###'
  - 116. 动态 SQL
- - '###'
  - 117. 总结
- - '##'
  - 第 9 章：安全
- - '###'
  - 118. 用户维护导航
- - '###'
  - 119. 用户维护数据录入
- - '###'
  - 120. 身份验证
- - '###'
  - 121. 自定义身份验证方案
- - '###'
  - 122. 条件安全
- - '###'
  - 123. 访问控制
- - '###'
  - 124. 授权
- - '###'
  - 125. 只读项目
- - '###'
  - 126. 数据安全
- - '###'
  - 127. 会话状态保护
- - '###'
  - 128. 总结
- - '##'
  - 第 10 章：应用程序打包与部署
- - '###'
  - 129. 识别应用程序组件
- - '####'
  - 130. 外部文件
- - '####'
  - 130. 数据库对象
- - '####'
  - 131. 基于 APEX 的文件
- - '###'
  - 132. APEX 应用程序导出
- - '###'
  - 133. 支持对象
- - '###'
  - 134. 先决条件
- - '###'
  - 135. 替换
- - '###'
  - 135. 构建选项
- - '###'
  - 136. 验证
- - '###'
  - 136. 安装
- - '###'
  - 137. 升级
- - '###'
  - 137. 卸载
- - '###'
  - 137. 导出
- - '###'
  - 137. 消息
- - '###'
  - 138. 导入
- - '###'
  - 139. 总结
- - '##'
  - 第 11 章：理解网页表格
- - '###'
  - 140. 网页表格结构
- - '###'
  - 141. 导航
- - '####'
  - 141.1 内容导航
- - '####'
  - 142. 结构导航
- - '###'
  - 142. 帮助
- - '###'
  - 143. 标记语法
- - '###'
  - 144. 用户身份验证
- - '###'
  - 145. 用户授权
- - '###'
  - 146. 区段
- - '####'
  - 146.1 文本区段
- - '####'
  - 147. 导航区段
- - '####'
  - 148. 数据区段
- - '####'
  - 149. 图表区段
- - '###'
  - 149. 批注
- - '###'
  - 150. 管理
- - '###'
  - 151. 总结
- - '##'
  - 第 12 章：网页表格示例
- - '###'
  - 152. 设置
- - '###'
  - 153. 创建并配置网页表格应用程序
- - '###'
  - 154. 向网页表格添加内容
- - '###'
  - 155. 创建数据网格
- - '####'
  - 156. 应用约束
- - '###'
  - 157. 添加球员
- - '###'
  - 158. 创建替代默认报表
- - '###'
  - 159. 创建页面区段
- - '###'
  - 160. SQL 标签
- - '###'
  - 161. 访问控制
- - '###'
  - 162. 总结
- - '##'
  - 第 13 章：扩展开发者工具
- - '###'
  - 163. 页面锁
- - '####'
  - 164. APEX 冲突
- - '####'
  - 164. 锁定 APEX 页面
- - '####'
  - 165. 解锁页面
- - '####'
  - 165. 管理页面锁
- - '###'
  - 166. 应用程序和页面组
- - '####'
  - 166.1 应用程序组
- - '####'
  - 167. 页面组
- - '###'
  - 167. APEX 视图和 APEX 字典
- - '####'
  - 168. APEX 模式
- - '####'
  - 168. APEX 视图
- - '####'
  - 169. APEX 字典
- - '###'
  - 169. 在 APEX 中搜索
- - '####'
  - 169.1 APEX 查找器
- - '####'
  - 170. 搜索应用程序
- - '###'
  - 171. 监控您的 APEX 应用程序
- - '####'
  - 171.1 启用日志记录
- - '####'
  - 172. 使用活动日志
- - '####'
  - 173. 登录尝试
- - '###'
  - 173. APEX 顾问
- - '###'
  - 174. 构建选项
- - '####'
  - 174.1 理解需求
- - '####'
  - 175. 创建构建选项
- - '####'
  - 176. 配置构建选项
- - '####'
  - 176. 提示构建选项状态
- - '####'
  - 177. 应用构建选项
- - '####'
  - 178. 报告构建选项使用情况
- - '###'
  - 178. 页面特定工具
- - '###'
  - 179. APEX 与 Oracle SQL Developer
- - '####'
  - 179.1 集成
- - '####'
  - 180. 重构支持
- - '###'
  - 181. 总结
- - '##'
  - 第 14 章：管理工作区
- - '###'
  - 182. 了解您的环境
- - '####'
  - 183. 查看实例信息
- - '####'
  - 184. 检查 APEX 版本
- - '###'
  - 184. 管理服务
- - '###'
  - 185. 工作区首选项
- - '###'
  - 186. 消息
- - '###'
  - 187. 管理元数据
- - '###'
  - 188. 开发者活动和点击计数日志
- - '###'
  - 189. 会话状态
- - '###'
  - 190. 应用程序缓存
- - '###'
  - 191. 网页表格数据库对象
- - '###'
  - 192. 应用程序构建状态
- - '###'
  - 193. 文件使用情况
- - '###'
  - 194. 交互式报表设置
- - '###'
  - 195. 管理用户和组
- - '####'
  - 195.1 创建一个用户
- - '####'
  - 196. 创建多个用户
- - '####'
  - 197. 将用户组织到组中
- - '###'
  - 198. 查看使用情况报告和仪表板
- - '###'
  - 199. 总结
- - '##'
  - 第 15 章：团队开发
- - '###'
  - 200. 团队开发概览
- - '###'
  - 201. 团队开发界面
- - '####'
  - 201.1 APEX 主页
- - '####'
  - 202. 团队开发主页
- - '###'
  - 203. 通用设计元素
- - '####'
  - 204. 下钻功能
- - '####'
  - 205. 标签
- - '###'
  - 206. 里程碑
- - '####'
  - 206.1 里程碑报告选项卡
- - '####'
  - 207. 按负责人选项卡
- - '####'
  - 207. 按里程碑的功能选项卡
- - '###'
  - 208. 功能
- - '####'
  - 208.1 功能报告选项卡
- - '####'
  - 209. 历史记录选项卡
- - '####'
  - 209. 进度日志选项卡
- - '###'
  - 210. 待办事项
- - '###'
  - 211. 缺陷
- - '###'
  - 212. 反馈
- - '####'
  - 212.1 配置反馈
- - '####'
  - 213. 完善反馈页面
- - '####'
  - 214. 查看反馈
- - '####'
  - 214. 对反馈的响应
- - '###'
  - 215. 工作区之间的通信
- - '###'
  - 216. 团队开发工具
- - '###'
  - 217. 团队开发设置
- - '###'
  - 218. 发布摘要
- - '###'
  - 219. 启用文件
- - '###'
  - 220. 功能工具
- - '####'
  - 221. 管理关注领域
- - '####'
  - 221. 更新负责人
- - '####'
  - 222. 查看文件
- - '####'
  - 222. 清除数据
- - '####'
  - 223. 管理新闻
- - '####'
  - 223. 管理链接
- - '###'
  - 224. 团队开发的用户角色
- - '###'
  - 225. 总结
- - '##'
  - 第 16 章：动态操作
- - '###'
  - 226. 动态操作的优势
- - '###'
  - 227. 剖析动态操作
- - '###'
  - 228. 帮助台应用程序中的动态操作
- - '###'
  - 229. 从简单开始
- - '###'
  - 230. 使用页面级事件
- - '###'
  - 231. 具有多个触发元素的动态操作
- - '###'
  - 232. 使用 PL/SQL 的动态操作
- - '###'
  - 233. 使用 JavaScript 的动态操作
- - '###'
  - 234. 总结
- - '##'
  - 附录 A：页面设计器演练与参考
- - '###'
  - 235. 页面设计器概览
- - '###'
  - 236. 页面设计器工具栏
- - '###'
  - 237. 树状窗格
- - '###'
  - 238. 中央窗格
- - '###'
  - 239. 网格布局
- - '###'
  - 240. 消息
- - '###'
  - 241. 页面搜索
- - '###'
  - 242. 帮助
- - '###'
  - 243. 属性编辑器
- - '###'
  - 244. 资源库
- - '###'
  - 245. 键盘快捷键
- - '###'
  - 246. 总结
- - '##'
  - 索引
- - '##'
  - 快速目录
- - '##'
  - 第 1 章：APEX 5.0 简介
- - '##'
  - 第 2 章：开发者概览
- - '##'
  - 第 3 章：识别问题与设计解决方案
- - '##'
  - 第 4 章：SQL 工作坊
- - '##'
  - 第 5 章：应用程序与导航
- - '##'
  - 第 6 章：表单和报表：基础篇
- - '##'
  - 第 7 章：表单和报表：高级篇
- - '##'
  - 第 8 章：编程元素
- - '##'
  - 第 9 章：安全
- - '##'
  - 第 10 章：应用程序打包与部署
- - '##'
  - 第 11 章：理解网页表格
- - '##'
  - 第 12 章：网页表格示例
- - '##'
  - 第 13 章：扩展开发者工具
- - '##'
  - 第 14 章：管理工作区
- - '##'
  - 第 15 章：团队开发
- - '##'
  - 第 16 章：动态操作
- - '##'
  - 附录 A：页面设计器演练与参考
