name: Next Generation Databases
name_cn: 下一代数据库
slug: next-generation-databases
toc:
- - '#'
  - 盖伊·哈里森 下一代数据库 NoSQL、NewSQL 与大数据
- - '##'
  - 下一代数据库
- - '##'
  - 致谢
- - '#'
  - 第一部分：下一代数据库
- - '##'
  - 第一章：三次数据库革命
- - '##'
  - 第二章：谷歌、大数据与 Hadoop
- - '##'
  - 第三章：分片、亚马逊与 NoSQL 的诞生
- - '##'
  - 第四章：文档数据库
- - '##'
  - 第五章：表并非你的朋友：图数据库
- - '##'
  - 第六章：列式数据库
- - '##'
  - 第七章：磁盘的终结？固态硬盘与内存数据库
- - '#'
  - 第二部分：技术细节
- - '##'
  - 第八章：分布式数据库模式
- - '##'
  - 第九章：一致性模型
- - '##'
  - 第十章：数据模型与存储
- - '##'
  - 第十一章：语言与编程接口
- - '##'
  - 第十二章：未来的数据库
- - '#'
  - 附录 A：数据库概览
- - '#'
  - 第一部分：下一代数据库
- - '###'
  - 1. 三次数据库革命
- - '####'
  - 早期数据库系统
- - '####'
  - 第一次数据库革命
- - '####'
  - 第二次数据库革命
- - '#####'
  - 关系理论
- - '#####'
  - 事务模型
- - '#####'
  - 最早的关系数据库
- - '#####'
  - 数据库之战！
- - '#####'
  - 客户端-服务器计算
- - '#####'
  - 面向对象编程与面向对象数据库管理系统
- - '#####'
  - 关系型平台期
- - '####'
  - 第三次数据库革命
- - '####'
  - 谷歌与 Hadoop
- - '####'
  - 其他互联网公司
- - '####'
  - 云计算
- - '####'
  - 文档数据库
- - '#####'
  - “NewSQL”
- - '#####'
  - 非关系型数据库的爆发
- - '####'
  - 结论：并非万能
- - '####'
  - 注释
- - '###'
  - 2. 谷歌、大数据与 Hadoop
- - '####'
  - 大数据革命
- - '#####'
  - 云、移动、社交与大数据
- - '####'
  - 谷歌：大数据的先驱
- - '####'
  - Google 硬件基础设施
- - '#####'
  - Google 软件栈
- - '#####'
  - 更多关于 MapReduce
- - '####'
  - Hadoop：开源的 Google 技术栈
- - '####'
  - Hadoop 的起源
- - '####'
  - Hadoop 的力量
- - '####'
  - Hadoop 的架构
- - '#####'
  - HBase
- - '#####'
  - Hive
- - '#####'
  - Pig
- - '#####'
  - Hadoop 生态系统
- - '####'
  - 结论
- - '####'
  - 注释
- - '###'
  - 3. 分片、亚马逊与 NoSQL 的诞生
- - '####'
  - 扩展 Web 2.0
- - '#####'
  - Web 2.0 如何取胜
- - '#####'
  - 开源解决方案
- - '#####'
  - 分片
- - '######'
  - 千刀万剐的分片
- - '######'
  - CAP 定理
- - '######'
  - 最终一致性
- - '####'
  - 亚马逊的 Dynamo
- - '#####'
  - 一致性哈希
- - '#####'
  - 可调节的一致性
- - '####'
  - Dynamo 与键值存储家族
- - '####'
  - 结论
- - '####'
  - 注
- - '###'
  - 4. 文档数据库
- - '####'
  - XML 与 XML 数据库
- - '#####'
  - XML 工具与标准
- - '#####'
  - XML 数据库
- - '#####'
  - 关系型系统中的 XML 支持
- - '####'
  - JSON 文档数据库
- - '#####'
  - JSON 与 AJAX
- - '#####'
  - JSON 数据库
- - '######'
  - 概述
- - '######'
  - 存储层级
- - '######'
  - 数据建模
- - '####'
  - 文档数据库中的数据模型
- - '####'
  - 早期的 JSON 数据库
- - '####'
  - MemBase 与 CouchBase
- - '####'
  - MongoDB
- - '#####'
  - JSON, JSON, 无处不在
- - '####'
  - 结论
- - '###'
  - 5. 表并非友好之选：图数据库
- - '####'
  - 什么是图？
- - '####'
  - 图的 RDBMS 模式
- - '#####'
  - RDF 与 SPARQL
- - '#####'
  - 属性图与 Neo4j
- - '#####'
  - Gremlin
- - '####'
  - 图数据库内部原理
- - '####'
  - 图计算引擎
- - '####'
  - 总结
- - '###'
  - 6. 列式数据库
- - '#####'
  - 数据仓库模式
- - '#####'
  - 列式替代方案
- - '####'
  - 列式压缩
- - '####'
  - 列式写入惩罚
- - '####'
  - Sybase IQ、C-Store 与 Vertica
- - '####'
  - 列式数据库架构
- - '#####'
  - 投影
- - '#####'
  - 其他数据库中的列式技术
- - '####'
  - 结论
- - '####'
  - 注释
- - '###'
  - 7. 磁盘的终结？固态硬盘与内存数据库
- - '####'
  - 磁盘的终结？
- - '#####'
  - 固态硬盘
- - '#####'
  - 磁盘经济学
- - '#####'
  - 支持固态硬盘的数据库
- - '####'
  - 内存数据库
- - '#####'
  - TimesTen
- - '######'
  - 核心特点
- - '######'
  - 持久化与事务
- - '######'
  - 架构图示
- - '######'
  - 当前意义
- - '#####'
  - Redis
- - '######'
  - 起源与发展
- - '######'
  - 架构与特性
- - '######'
  - 持久化机制
- - '######'
  - 复制功能
- - '######'
  - 架构图示
- - '######'
  - 性能考量
- - '######'
  - 总结
- - '#####'
  - SAP HANA
- - '#####'
  - VoltDB
- - '#####'
  - Oracle 12c “内存数据库”
- - '####'
  - Berkeley Analytics Data Stack 与 Spark
- - '#####'
  - Spark 架构
- - '####'
  - 结论
- - '####'
  - 注释
- - '#'
  - 第二部分：技术细节
- - '###'
  - 8. 分布式数据库模式
- - '####'
  - 分布式关系数据库
- - '#####'
  - 复制
- - '#####'
  - 共享无共享与共享磁盘
- - '####'
  - 非关系型分布式数据库
- - '####'
  - MongoDB 分片与复制
- - '#####'
  - 分片
- - '######'
  - 分片机制
- - '######'
  - 集群平衡
- - '#####'
  - 复制
- - '#####'
  - 写入关注与读取偏好
- - '####'
  - HBase
- - '#####'
  - 表、区域与区域服务器
- - '#####'
  - 缓存与数据本地性
- - '#####'
  - 行键排序
- - '#####'
  - RegionServer 的分割、负载均衡与故障处理
- - '#####'
  - 区域副本
- - '####'
  - Cassandra
- - '#####'
  - Gossip 协议
- - '#####'
  - 一致性哈希
- - '######'
  - 保留顺序的分区器
- - '#####'
  - 副本
- - '#####'
  - 探测器
- - '####'
  - 本章小结
- - '###'
  - 9. 一致性模型
- - '####'
  - 一致性的类型
- - '#####'
  - ACID 与 MVCC
- - '#####'
  - 全局事务序列号
- - '#####'
  - 两阶段提交
- - '#####'
  - 其他一致性级别
- - '####'
  - MongoDB 中的一致性
- - '#####'
  - MongoDB 锁定
- - '#####'
  - 副本集与最终一致性
- - '####'
  - HBase 一致性
- - '#####'
  - 最终一致的区域副本
- - '####'
  - Cassandra 一致性
- - '#####'
  - 副本因子
- - '#####'
  - 写入一致性
- - '#####'
  - 读一致性
- - '####'
  - 一致性级别间的相互作用
- - '####'
  - 暗示切换与读修复
- - '####'
  - 时间戳与粒度
- - '#####'
  - 向量时钟
- - '#####'
  - 轻量级事务
- - '####'
  - 结论
- - '###'
  - 10. 数据模型与存储
- - '####'
  - 数据模型
- - '#####'
  - 数据关系模型回顾
- - '#####'
  - 键值存储
- - '######'
  - 收敛复制数据类型
- - '#####'
  - BigTable 与 HBase 中的数据模型
- - '######'
  - 列族结构
- - '######'
  - 版本
- - '#####'
  - Cassandra
- - '######'
  - Cassandra 集合
- - '#####'
  - JSON 数据模型
- - '######'
  - 二进制 JSON
- - '####'
  - 存储
- - '#####'
  - 典型的关系型存储模型
- - '#####'
  - 日志结构合并树
- - '######'
  - SSTable 与布隆过滤器
- - '######'
  - 更新与墓碑标记
- - '######'
  - 合并
- - '#####'
  - 二级索引
- - '######'
  - 自建二级索引
- - '######'
  - 全局索引与本地索引
- - '####'
  - NoSQL 数据库中的二级索引实现
- - '####'
  - 结论
- - '###'
  - 11. 语言与编程接口
- - '####'
  - SQL
- - '####'
  - NoSQL API
- - '#####'
  - Riak
- - '######'
  - 定义更新值
- - '######'
  - 调用更新器
- - '####'
  - HBase
- - '#####'
  - 使用 Shell 命令
- - '#####'
  - 连接 HBase 服务器
- - '#####'
  - 获取数据
- - '#####'
  - 写入数据
- - '#####'
  - 其他功能
- - '####'
  - MongoDB
- - '####'
  - Cassandra 查询语言 (CQL)
- - '#####'
  - CQL 作为抽象层与接口
- - '#####'
  - CQL 中的宽列结构
- - '#####'
  - 局限性与设计原理
- - '#####'
  - 在 Java (JDBC 类) 应用程序中使用 CQL
- - '####'
  - MapReduce
- - '####'
  - Pig
- - '####'
  - 有向无环图
- - '####'
  - Cascading
- - '####'
  - Spark
- - '####'
  - SQL 的回归
- - '#####'
  - SQL-on-Hadoop 工具对比
- - '#####'
  - Hive
- - '#####'
  - Impala
- - '#####'
  - Spark SQL
- - '######'
  - Couchbase N1QL
- - '######'
  - 基本查询
- - '######'
  - 访问嵌套文档
- - '######'
  - 使用 WHERE ANY 查询子文档
- - '######'
  - 使用 UNNEST 连接嵌套文档
- - '######'
  - 总结
- - '#####'
  - Apache Drill
- - '#####'
  - 其他用于 NoSQL 的 SQL 方案
- - '####'
  - 结论
- - '####'
  - 注意
- - '###'
  - 12. 未来的数据库
- - '####'
  - 回顾革命
- - '####'
  - 反革命者
- - '#####'
  - 对非关系型数据库的反思与未来
- - '#####'
  - 我们是否绕回了起点？
- - '#####'
  - 选择过剩的尴尬
- - '#####'
  - 我们能否兼得？
- - '#####'
  - 一致性模型
- - '#####'
  - 类似 Cassandra 的数据库
- - '#####'
  - 模式
- - '#####'
  - 数据库语言
- - '#####'
  - 存储
- - '####'
  - 融合数据库的愿景
- - '####'
  - 与此同时，在 Oracle 总部……
- - '#####'
  - Oracle JSON 支持
- - '######'
  - Oracle JSON 与 REST 访问功能
- - '######'
  - 通过 Oracle REST 访问 JSON
- - '######'
  - 对 Oracle 表的 REST 访问
- - '#####'
  - Oracle Graph
- - '#####'
  - Oracle Sharding
- - '######'
  - Oracle 分片
- - '#####'
  - Oracle 作为混合数据库
- - '####'
  - 其他融合数据库
- - '#####'
  - 数据库技术的未来：统一与颠覆
- - '######'
  - 颠覆性的数据库技术
- - '######'
  - 存储技术
- - '######'
  - 区块链
- - '#####'
  - 量子计算
- - '####'
  - 结论
- - '####'
  - 注释
- - '###'
  - 13. 数据库概览
- - '####'
  - Aerospike
- - '####'
  - Cassandra
- - '#####'
  - CQL
- - '####'
  - CouchBase
- - '####'
  - DynamoDB
- - '####'
  - HBase
- - '####'
  - MarkLogic
- - '####'
  - MongoDB
- - '####'
  - Neo4J
- - '####'
  - NuoDB
- - '####'
  - Oracle RDBMS
- - '#####'
  - 数据模型
- - '#####'
  - 事务模型
- - '#####'
  - 集群
- - '#####'
  - API
- - '####'
  - Redis
- - '#####'
  - 数据模型
- - '#####'
  - 事务模型
- - '#####'
  - 集群
- - '#####'
  - API
- - '####'
  - Riak
- - '#####'
  - 数据模型
- - '#####'
  - 事务模型
- - '#####'
  - 集群
- - '#####'
  - API
- - '####'
  - SAP HANA
- - '#####'
  - 数据模型
- - '#####'
  - 事务模型
- - '#####'
  - 集群
- - '#####'
  - API
- - '####'
  - TimesTen
- - '#####'
  - 数据模型
- - '#####'
  - 事务模型
- - '#####'
  - 集群
- - '#####'
  - API
- - '####'
  - Vertica
- - '#####'
  - 数据模型
- - '#####'
  - 事务模型
- - '#####'
  - 集群
- - '#####'
  - API
- - '####'
  - VoltDB
- - '#####'
  - 数据模型
- - '#####'
  - 事务模型
- - '#####'
  - 集群
- - '#####'
  - API
- - '####'
  - A
- - '####'
  - B
- - '####'
  - C
- - '####'
  - D
- - '####'
  - E
- - '####'
  - G
- - '####'
  - H
- - '####'
  - I
- - '####'
  - J, K
- - '####'
  - L
- - '####'
  - M
- - '####'
  - N
- - '####'
  - O
- - '####'
  - P
- - '####'
  - Q
- - '####'
  - R
- - '####'
  - T, U
- - '####'
  - W
- - '####'
  - X
- - '####'
  - Y, Z
