name: SQL Server on Kubernetes
name_cn: Kubernetes上的SQL Server
slug: sql-server-on-kubernetes
toc:
- - '#'
  - 前言
- - '#'
  - 致谢
- - '#'
  - 关于作者 关于技术审阅者
- - '##'
  - 开始使用
- - '###'
  - 安装 Docker
- - '###'
  - 基于虚拟机的 Kubernetes 集群要求
- - '####'
  - 在 Azure 中运行虚拟机
- - '##'
  - 使用 Azure 和 Azure Kubernetes Service 搭建实验室环境
- - '###'
  - PowerShell 脚本：创建 Azure 实验室环境
- - '#'
  - 根据需要修改这些变量
- - '#'
  - 定义机器
- - '#'
  - 创建资源组
- - '#'
  - 创建虚拟网络和网络安全组
- - '#'
  - 创建虚拟机
- - '###'
  - 虚拟机网络配置
- - '###'
  - Azure Kubernetes Service
- - '###'
  - 安装工具
- - '####'
  - 使用 Linux 机器作为管理工作站
- - '####'
  - 使用 Windows 机器作为管理工作站
- - '###'
  - Windows 用户的小助手：Chocolatey
- - '###'
  - Windows 上的工具
- - '###'
  - NFS
- - '###'
  - 系统交换空间设置
- - '###'
  - 总结
- - '##'
  - 2. 容器基础
- - '###'
  - 基于容器的应用部署
- - '###'
  - 虚拟机有何难点？
- - '###'
  - 容器
- - '####'
  - 容器领域
- - '####'
  - 获取和运行容器
- - '####'
  - 容器生命周期
- - '####'
  - 操作容器镜像
- - '####'
  - 启动容器
- - '####'
  - 如果出现问题怎么办？
- - '####'
  - 访问基于容器的应用程序
- - '####'
  - 启动 SQL Server 的第二个实例
- - '####'
  - 将数据库恢复到容器中运行的 SQL Server
- - '####'
  - 停止容器
- - '####'
  - 在本地系统上查找容器
- - '##'
  - 启动和管理容器
- - '###'
  - 启动一个现有容器
- - '###'
  - 移除容器
- - '##'
  - 容器内部原理
- - '###'
  - 命名空间
- - '###'
  - 联合文件系统
- - '###'
  - 容器中的数据持久化
- - '####'
  - Docker 卷
- - '####'
  - 创建带有卷的容器
- - '####'
  - 深入了解卷
- - '####'
  - 停止和移除容器与卷
- - '###'
  - 现代应用程序部署
- - '###'
  - 容器编排器的需求
- - '###'
  - 更多资源
- - '###'
  - 总结
- - '##'
  - 3. Kubernetes 架构
- - '###'
  - Kubernetes 简介
- - '###'
  - Kubernetes API
- - '####'
  - API 对象
- - '####'
  - API Server
- - '####'
  - 核心 Kubernetes API 原语
- - '#####'
  - Pods
- - '#####'
  - Controllers
- - '##'
  - Kubernetes 中的控制器、服务与存储
- - '###'
  - StatefulSet 示例
- - '###'
  - 服务
- - '###'
  - 存储
- - '###'
  - 配置映射
- - '##'
  - Kubernetes 集群组件
- - '###'
  - Secrets
- - '###'
  - 探索 Kubernetes 集群架构
- - '####'
  - 控制平面节点
- - '##'
  - 工作节点
- - '###'
  - 网络基础
- - '####'
  - Kubernetes 网络模型规则
- - '####'
  - 通信模式
- - '###'
  - 总结
- - '###'
  - 4. 安装 Kubernetes
- - '###'
  - 安装考虑因素与方法
- - '####'
  - 部署位置？
- - '####'
  - 进一步考虑因素
- - '####'
  - 安装方法
- - '####'
  - 其他选项
- - '###'
  - 安装要求
- - '####'
  - 网络要求
- - '####'
  - '[获取 Kubernetes](https://app.pluralsight.com/course-player%253FclipId%253Db0f4845d-f2a5-4a1a-a790-a39ccf314435)'
- - '###'
  - 构建自管理集群
- - '####'
  - 准备虚拟机
- - '#####'
  - 安装和配置 containerd
- - '####'
  - 安装与配置 Kubernetes 软件包
- - '####'
  - 创建控制平面
- - '#####'
  - Pod 网络
- - '#####'
  - 存储
- - '####'
  - 将节点添加到集群
- - '###'
  - 在 Azure Kubernetes 服务中构建云集群
- - '###'
  - 总结
- - '##'
  - 5. 与 Kubernetes 集群交互
- - '###'
  - 使用 kubectl 与集群交互
- - '####'
  - 操作
- - '####'
  - 资源
- - '###'
  - 输出
- - '###'
  - Kubectl 上下文
- - '###'
  - 在 Kubernetes 中部署应用
- - '####'
  - 命令式部署
- - '###'
  - 声明式部署
- - '###'
  - 修改部署
- - '###'
  - 在集群中暴露和服务访问
- - '####'
  - 暴露类型为 ClusterIP 的服务
- - '####'
  - 暴露类型为 NodePort 的服务
- - '####'
  - 暴露类型为 LoadBalancer 的服务
- - '###'
  - 总结
- - '##'
  - 6. 在 Kubernetes 中存储持久数据
- - '###'
  - 基于容器的应用程序中数据持久性的必要性
- - '###'
  - Kubernetes 中的存储
- - '###'
  - 卷
- - '###'
  - 持久卷与持久卷声明
- - '####'
  - 持久卷
- - '####'
  - 访问模式
- - '####'
  - 持久卷的类型
- - '####'
  - 定义持久卷
- - '##'
  - 持久卷与持久卷声明的静态配置
- - '###'
  - 持久卷声明
- - '###'
  - 定义持久卷声明
- - '###'
  - 为应用静态配置存储
- - '####'
  - 使用持久化存储部署应用
- - '###'
  - 存储类和动态配置
- - '####'
  - 存储类
- - '####'
  - 动态配置
- - '###'
  - 回收策略
- - '###'
  - 使用动态配置来创建持久卷和持久卷声明
- - '####'
  - 使用 NFS 动态配置磁盘
- - '####'
  - NFS 动态配置
- - '####'
  - 在 Azure 中动态配置磁盘
- - '###'
  - 总结
- - '##'
  - 7. 在 Kubernetes 上部署 SQL Server
- - '###'
  - 在 Pod 中运行 SQL Server
- - '###'
  - 在 Kubernetes 上部署 SQL Server
- - '####'
  - 准备工作
- - '#####'
  - 存储
- - '#####'
  - Secret
- - '####'
  - 在 YAML 中定义 SQL Server 部署
- - '####'
  - 额外配置选项
- - '####'
  - Pod 生命周期与数据持久性
- - '####'
  - 在部署中升级 SQL Server
- - '####'
  - 在生产环境中于 Kubernetes 上运行 SQL Server
- - '##'
  - 高级磁盘拓扑
- - '##'
  - 资源管理（限制与请求）
- - '##'
  - 备份（与还原）
- - '##'
  - 总结
- - '##'
  - 8. 监控 Kubernetes 上的 SQL Server
- - '##'
  - 用于性能监控的 Grafana
- - '###'
  - 系统指标
- - '###'
  - SQL Server 指标
- - '###'
  - 如何安装和配置 Grafana
- - '###'
  - Kibana 用于日志聚合与管理
- - '####'
  - 如何安装和配置 Kibana
- - '##'
  - 在 Kubernetes 上部署日志聚合系统
- - '###'
  - 部署 Elasticsearch StatefulSet
- - '###'
  - 部署 Kibana
- - '###'
  - 安装 Fluent-bit
- - '###'
  - 访问 Kibana
- - '###'
  - 配置数据源
- - '####'
  - 在 Kibana 中查看 SQL Server 日志
- - '###'
  - 清理
- - '###'
  - 总结
- - '##'
  - 9. Azure Arc 启用的数据服务与 Kubernetes 上 SQL Server 的高可用性
- - '###'
  - 什么是 Azure Arc？
- - '###'
  - Azure Arc 启用的数据服务简介
- - '####'
  - Azure Arc 数据控制器
- - '###'
  - 监控（Grafana 和 Kibana）
- - '###'
  - 连接到 Azure 门户的模式
- - '###'
  - 数据服务
- - '####'
  - Azure Arc SQL Managed Instance
- - '####'
  - Azure Database for PostgreSQL
- - '###'
  - Azure Arc–Enabled Data Services 中的 Kubernetes 构造
- - '###'
  - 部署 Azure Arc–Enabled Data Services
- - '####'
  - 先决条件
- - '###'
  - Kubernetes 集群
- - '###'
  - 工具
- - '####'
  - 部署数据控制器
- - '####'
  - 部署 Azure Arc 托管 SQL 实例
- - '###'
  - Azure Arc SQL 托管实例的高可用性
- - '###'
  - 本章小结
- - '##'
  - 10. 大数据群集
- - '###'
  - 大数据集群简介
- - '####'
  - 数据虚拟化
- - '####'
  - 托管数据平台
- - '####'
  - AI 和应用程序平台
- - '###'
  - BDC 架构
- - '####'
  - 大数据集群组件
- - '#####'
  - BDC 控制平面
- - '#####'
  - SQL Server 主实例
- - '#####'
  - 计算池
- - '####'
  - 存储池
- - '####'
  - 数据池
- - '####'
  - 应用池
- - '####'
  - BDC 中的 Kubernetes 构造
- - '###'
  - 部署
- - '###'
  - 监控和管理
- - '###'
  - 升级大数据集群
- - '###'
  - 总结
- - '#'
  - 索引
