name: MariaDB and MySQL Common Table Expressions and Window Functions Revealed
name_cn: MariaDB 和 MySQL 公用表表达式与窗口函数揭秘
slug: mariadb-and-mysql-common-table-expressions-and-window-functi
toc:
- - '#'
  - Daniel Bartholomew：MariaDB 与 MySQL 中的公用表表达式与窗口函数揭秘
- - '##'
  - 引言
- - '##'
  - 语法
- - '##'
  - 致谢
- - '##'
  - 目录
- - '#'
  - 第一部分：公用表表达式
- - '##'
  - 1. 公用表表达式基础
- - '###'
  - 开始之前
- - '###'
  - 什么是公用表表达式？
- - '###'
  - 基本 CTE 语法
- - '###'
  - CTE 的动机
- - '####'
  - 临时性
- - '####'
  - 可读性
- - '###'
  - 在单处或多处使用
- - '###'
  - 权限
- - '###'
  - 嵌套
- - '###'
  - 多路复用
- - '###'
  - 递归
- - '###'
  - 总结
- - '##'
  - 2. 非递归公用表表达式
- - '###'
  - 开始之前
- - '###'
  - 使用 CTE 进行年度同比比较
- - '####'
  - 传统 SQL 查询方法
- - '####'
  - 使用 CTE 进行改进
- - '####'
  - 通过 JOIN 添加员工信息
- - '####'
  - 分析结果与进一步筛选
- - '####'
  - 个体与群体对比
- - '####'
  - 将子查询转换为 CTE
- - '###'
  - 总结
- - '##'
  - 3. 递归公用表表达式
- - '###'
  - 开始之前
- - '###'
  - 递归 CTE 语法
- - '###'
  - 数字累加
- - '###'
  - 计算斐波那契数列
- - '###'
  - 在树中查找祖先
- - '###'
  - SQL 递归 CTE 详解与示例
- - '####'
  - 查找所有可能的目的地
- - '####'
  - 查找所有可能路径
- - '###'
  - 总结
- - '#'
  - 第二部分：窗口函数
- - '##'
  - 4. 窗口函数基础
- - '###'
  - 什么是窗口函数？
- - '###'
  - 窗口函数语法
- - '####'
  - 分区定义语法
- - '####'
  - 排序定义语法
- - '####'
  - 帧定义语法
- - '###'
  - WINDOW 子句语法
- - '###'
  - 窗口函数参考
- - '####'
  - AVG()
- - '####'
  - BIT_AND()
- - '####'
  - BIT_OR()
- - '####'
  - BIT_XOR()
- - '####'
  - COUNT()
- - '####'
  - CUME_DIST()
- - '####'
  - DENSE_RANK()
- - '####'
  - FIRST_VALUE()
- - '####'
  - LAG()
- - '####'
  - LAST_VALUE()
- - '####'
  - LEAD()
- - '####'
  - NTH_VALUE()
- - '####'
  - NTILE()
- - '####'
  - PERCENT_RANK()
- - '####'
  - RANK()
- - '####'
  - ROW_NUMBER()
- - '####'
  - SUM()
- - '###'
  - 小结
- - '##'
  - 5. 识别窗口函数的应用场景
- - '###'
  - 分区和排序结果
- - '###'
  - 维护运行总计
- - '###'
  - 对结果集中的行进行排名
- - '##'
  - 6. 窗口函数实战
- - '###'
  - 任务与问题
- - '###'
  - 准备工作
- - '###'
  - 处理时间序列数据
- - '####'
  - 同时使用多个窗口函数
- - '###'
  - 绘制时间序列结果
- - '###'
  - 使用 gnuplot 绘图
- - '###'
  - 平滑数据线
- - '###'
  - 分析水果销售
- - '####'
  - 单店内的水果销售
- - '####'
  - 比较所有门店间的水果销售
- - '###'
  - 总结
- - '##'
  - 7. 结合使用窗口函数和 CTEs
- - '###'
  - 开始之前
- - '###'
  - 计算降水日之间的平均间隔时间
- - '###'
  - 添加主键列
- - '###'
  - 寻找数据缺口与连续段
- - '####'
  - 间隙
- - '####'
  - 岛屿
- - '###'
  - 总结
- - '###'
  - 索引
