name: The SQL Server DBA’s Guide to Docker Containers
name_cn: SQL Server DBA 的 Docker 容器指南
slug: the-sql-server-dbas-guide-to-docker-containers
toc:
- - '#'
  - 第 8 章：在 Linux 上操作 SQL Server
- - '##'
  - SQL Server on Linux 架构
- - '###'
  - 项目吊桥
- - '###'
  - SQLOS 和 SQLPAL
- - '##'
  - SQL Server 在 Windows 与 Linux 上的差异
- - '##'
  - 在 Linux 上安装 SQL Server
- - '###'
  - 手动安装
- - '####'
  - 无人参与安装
- - '##'
  - 配置防火墙
- - '##'
  - Linux 防火墙与 Docker 注意事项
- - '##'
  - 在 Linux 上配置 SQL Server
- - '###'
  - 启用 SQL Server Agent
- - '###'
  - 配置默认数据库数据和日志目录
- - '####'
  - 配置默认数据库备份目录
- - '####'
  - 启用跟踪标志
- - '####'
  - 查看所有实例级配置设置
- - '###'
  - 处理文件系统
- - '####'
  - Linux 文件系统中的重要目录
- - '####'
  - 文件权限
- - '##'
  - 为文件和目录分配权限
- - '###'
  - 更改所有者和所属组
- - '###'
  - 分配执行权限
- - '###'
  - 使用八进制模式
- - '##'
  - 编写简单的 Linux Bash 脚本
- - '###'
  - 什么是 Bash 脚本？
- - '###'
  - 创建脚本文件
- - '###'
  - 脚本示例
- - '###'
  - 设置执行权限
- - '###'
  - 运行脚本
- - '###'
  - 向脚本传递参数
- - '###'
  - 在 Bash 脚本中添加条件逻辑
- - '###'
  - VARIABLES
- - '##'
  - 总结
- - '#'
  - 通过配置双向 TLS 加密来保护 Docker 守护进程套接字
- - '##'
  - 更新 daemon.json 以包含双向 TLS 加密设置
- - '##'
  - 启用防火墙端口以允许到 Docker 守护进程的流量
- - '#'
  - Docker CLI 客户端配置与管理
- - '##'
  - 测试远程客户端连接
- - '##'
  - 清理
- - '##'
  - 配置 Docker CLI Bash 自动补全
- - '##'
  - 启动和停止容器
- - '##'
  - 删除容器和镜像
- - '##'
  - 与运行中的容器交互
- - '##'
  - 在主机和容器之间共享文件
- - '##'
  - 配置容器资源
- - '#'
  - 探索容器日志
- - '##'
  - 使用`docker logs`查看容器日志
- - '##'
  - 关于 Windows 行为的重要说明
- - '##'
  - 实时查看日志
- - '#'
  - 检查 Docker 守护进程的状态
- - '#'
  - 总结
