name: Practical Azure SQL Database for Modern Developers
name_cn: 现代开发者的实用 Azure SQL 数据库指南
slug: practical-azure-sql-database-for-modern-developers
toc:
- - '#'
  - 由 Rohan Kumar 撰写的前言
- - '#'
  - 由 Mark Souza 撰写的前言
- - '#'
  - 引言
- - '#'
  - 第 1 章
- - '#'
  - 第 2 章
- - '#'
  - 第 4 章
- - '#'
  - 第 5 章
- - '#'
  - 第 6 章
- - '#'
  - 第 7 章
- - '#'
  - 第 8 章
- - '#'
  - 第 9 章
- - '#'
  - 致谢
- - '##'
  - 达维德·毛里（Davide Mauri）
- - '##'
  - 西尔瓦诺·科里亚尼（Silvano Coriani）
- - '##'
  - 安娜·霍夫曼（Anna Hoffman）
- - '##'
  - 桑杰·米什拉（Sanjay Mishra）
- - '#'
  - 1. 面向现代开发者的数据库
- - '##'
  - 我们为何撰写本书？
- - '##'
  - 成长型思维
- - '###'
  - 重新审视旧观念
- - '###'
  - 持续学习
- - '###'
  - 更优秀的开发者
- - '###'
  - 不仅仅是被动的数据容器
- - '###'
  - 数据的守护者
- - '#'
  - 业务规则应置于何处？
- - '#'
  - 谈谈多语言持久性
- - '#'
  - 电池已备
- - '#'
  - Azure SQL 是开发工具吗？
- - '###'
  - 保持超级简单
- - '###'
  - 成为通才专家
- - '###'
  - 如果想了解更多
- - '#'
  - 2. Azure SQL 入门指南
- - '##'
  - Azure SQL 选项概览与创建指南
- - '###'
  - 创建 Azure SQL Database
- - '###'
  - 登录到您的 Azure 帐户
- - '###'
  - 查看您可用的订阅
- - '###'
  - 复制您要使用的订阅的 "id" 并将其设置为默认值
- - '###'
  - 查看您的帐户可用的区域，记下您要使用的区域的 "name"（例如 "westus"）
- - '###'
  - 创建一个资源组（指定区域和名称）
- - '###'
  - 创建一个逻辑服务器
- - '###'
  - 使用默认配置创建一个 Azure SQL Database
- - '###'
  - 使用默认配置和 AdventureWorksLT 示例数据库创建一个 Azure SQL Database
- - '###'
  - 使用默认参数创建 Azure SQL 托管实例
- - '###'
  - 在现有的 Azure SQL 托管实例内创建新的托管数据库
- - '##'
  - 用于使用和管理 Azure SQL 数据库的工具
- - '##'
  - 选择，选择，还是选择
- - '###'
  - 快速回顾
- - '###'
  - DTU 或 vCore
- - '###'
  - 服务层
- - '#'
  - 服务层级与配置
- - '##'
  - 硬件代次
- - '##'
  - 网络
- - '##'
  - 连接方法
- - '###'
  - 排序规则
- - '###'
  - 时区
- - '###'
  - 高级数据安全
- - '##'
  - 使用示例数据库
- - '#'
  - Azure SQL 数据库样本获取与连接查询
- - '##'
  - 获取样本数据库
- - '##'
  - 延伸阅读
- - '#'
  - 3. 连接和查询 Azure SQL
- - '##'
  - 驱动程序和库
- - '#'
  - 哪种 Azure SQL 驱动最适合我
- - '##'
  - 入门指南
- - '##'
  - 清单 3-1 .NET Core 应用程序中的数据访问方法
- - '##'
  - 清单 3-2 Java 应用程序中的数据访问方法
- - '###'
  - 清单 3-3：创建一个简单的 Python 应用程序
- - '###'
  - 清单 3-4：从数据库返回 JSON 数组的 Node.JS 函数
- - '###'
  - 连接性方面
- - '###'
  - 弹性连接和查询执行
- - '###'
  - 重试逻辑
- - '###'
  - 瞬时错误与持久错误
- - '###'
  - 自定义代码或可重用库
- - '###'
  - 连接最佳实践
- - '##'
  - 异常处理
- - '##'
  - 框架、ORM 和 MicroORM
- - '###'
  - 数据访问框架
- - '##'
  - ORM
- - '###'
  - 微 ORM
- - '##'
  - 使用只读副本
- - '##'
  - 延伸阅读
- - '#'
  - 4. 使用 Azure SQL 进行开发 – 基础篇
- - '##'
  - 将计算推送到数据端
- - '#'
  - 声明式与命令式
- - '#'
  - 查询与数据操作
- - '##'
  - 检索数据
- - '#'
  - SQL 查询基础概念与语法
- - '##'
  - 表名称与 Schema
- - '##'
  - 别名
- - '##'
  - 引号标识符
- - '##'
  - 连接
- - '####'
  - 筛选
- - '####'
  - 子查询
- - '####'
  - 公用表表达式
- - '####'
  - 联合
- - '####'
  - 分号
- - '####'
  - Unicode 字符串
- - '###'
  - 添加数据
- - '###'
  - 修改数据
- - '###'
  - 删除数据
- - '###'
  - 合并数据
- - '###'
  - 其他有用功能
- - '##'
  - 输出子句：插入和删除的虚拟表
- - '##'
  - 标识和序列
- - '###'
  - SEQUENCE 对象
- - '##'
  - TOP 和 OFFSET/FETCH
- - '##'
  - 聚合
- - '###'
  - 分组数据
- - '###'
  - 多重分组
- - '###'
  - 窗口函数
- - '##'
  - 批量操作
- - '##'
  - 如果你想了解更多
- - '#'
  - 5. 使用 Azure SQL 进行开发 – 高级篇
- - '##'
  - 可编程性
- - '##'
  - 变量
- - '##'
  - 临时表
- - '###'
  - 视图
- - '####'
  - 代码重用与性能
- - '####'
  - 安全性
- - '####'
  - 抽象与兼容性
- - '##'
  - 函数
- - '##'
  - 存储过程
- - '##'
  - 存储过程
- - '###'
  - 触发器
- - '###'
  - 非标量参数
- - '####'
  - 表值参数
- - '####'
  - JSON
- - '####'
  - CSV
- - '####'
  - 监控数据变更
- - '###'
  - 变更跟踪
- - '###'
  - 变更数据捕获
- - '##'
  - 保护数据资产
- - '###'
  - 权限
- - '###'
  - 行级安全
- - '###'
  - 动态数据屏蔽
- - '###'
  - 始终加密
- - '##'
  - 如果您想了解更多
- - '##'
  - 6. 表和索引的实际应用
- - '##'
  - 设计优秀的表格：最佳实践
- - '##'
  - 将领域模型映射到数据库表
- - '##'
  - 数据规范化的价值与复杂性
- - '##'
  - 规范化过程的核心优势
- - '##'
  - 规范化：起点与延伸阅读
- - '##'
  - 考虑表格设计的其他方面
- - '###'
  - 创建表
- - '###'
  - 确定合适的列类型
- - '####'
  - 定义你的列类型
- - '##'
  - 排序规则
- - '##'
  - 计算列
- - '##'
  - 复杂类型列
- - '###'
  - 声明式约束
- - '###'
  - 保障表的安全性
- - '##'
  - 使用索引提升性能
- - '###'
  - B 树索引
- - '###'
  - 何时使用 B 树索引？
- - '###'
  - 何时创建索引？
- - '###'
  - 维护索引
- - '###'
  - 退役索引
- - '##'
  - 如果你想了解更多
- - '#'
  - 7. 可扩展性、一致性与性能
- - '##'
  - 事务
- - '###'
  - 理解事务与 ACID 属性
- - '###'
  - 事务在任何应用中的重要性
- - '###'
  - 如何实现 ACID 属性：预写式日志 (WAL)
- - '###'
  - Azure SQL 中的事务：用例与机制
- - '###'
  - 管理事务：控制与范围
- - '###'
  - 显式模式与自动提交模式
- - '#'
  - 事务模式
- - '###'
  - 本地事务
- - '#'
  - Connecting to Azure SQL Database with autocommit=True
- - '##'
  - 清单 7-2
- - '###'
  - 在 T-SQL 脚本中使用事务的示例
- - '##'
  - 清单 7-3
- - '###'
  - 在 .NET Core 应用中使用事务的示例
- - '##'
  - 跨云数据库的分布式事务
- - '##'
  - 锁定与非锁定选项
- - '#'
  - Azure SQL 事务隔离级别与并发控制
- - '##'
  - 标准隔离级别
- - '##'
  - 行版本控制隔离级别
- - '##'
  - 术语澄清：锁
- - '##'
  - 锁管理机制
- - '##'
  - 多粒度锁
- - '##'
  - 开发者控制与参考
- - '##'
  - 原生编译存储过程
- - '##'
  - 优化数据库往返次数
- - '###'
  - 利用事务
- - '###'
  - 表值参数
- - '###'
  - 批量复制
- - '###'
  - 多行参数化 INSERT 语句
- - '###'
  - 建议与最佳实践
- - '###'
  - 如果你想了解更多
- - '#'
  - 8. 多模型能力
- - '##'
  - 在数据库设计中利用多模型能力
- - '###'
  - 领域模型的分类
- - '###'
  - 根据数据实体的结构，你的模型可以分类为：
- - '##'
  - 为何要为非关系型模型选择 Azure SQL？
- - '###'
  - JSON 支持
- - '##'
  - 将查询结果格式化为 JSON 文档
- - '##'
  - 存储 JSON 文档
- - '##'
  - 查询 JSON 数据
- - '###'
  - JSON 路径
- - '###'
  - 排序规则意识
- - '###'
  - 确保 JSON 文档的数据完整性
- - '###'
  - 为 JSON 值建立索引
- - '###'
  - 导入 JSON 文档
- - '##'
  - 图结构
- - '##'
  - 加载图数据
- - '##'
  - 查询图数据
- - '##'
  - 空间数据
- - '###'
  - 查询空间数据
- - '###'
  - 空间索引
- - '###'
  - 几何 vs. 地理
- - '##'
  - XML 数据
- - '#'
  - 查询 XML 数据
- - '#'
  - XPath 和 XQuery 语言
- - '##'
  - XML 索引
- - '##'
  - 键值对
- - '##'
  - 如何处理非结构化文本？
- - '###'
  - 索引非结构化文本
- - '###'
  - 查询非结构化文本
- - '###'
  - 如何在半结构化数据上利用非结构化索引？
- - '#'
  - Azure SQL 中的多模型：为何以及何时使用
- - '##'
  - 想了解更多
- - '#'
  - 9. 不仅仅是表格
- - '#'
  - 列存储格式
- - '###'
  - Azure SQL 中的列存储
- - '###'
  - 在列存储中更新值
- - '###'
  - 查询列存储结构
- - '###'
  - 聚集列存储索引
- - '###'
  - 非聚集列存储索引
- - '##'
  - 内存优化表
- - '###'
  - 一个关于乐观并发的故事
- - '###'
  - 我们应该成为悲观主义者吗？
- - '##'
  - 内存优化表
- - '###'
  - 访问内存优化表
- - '###'
  - 本机编译代码
- - '##'
  - 时态表
- - '###'
  - 查询时态数据
- - '###'
  - 配置时态表
- - '##'
  - 如果你想了解更多
- - '#'
  - 10. 监控与调试
- - '##'
  - 动态管理视图 (DMV)
- - '#'
  - 使用动态管理视图监控 Azure SQL 查询性能
- - '##'
  - 执行计划
- - '##'
  - 查询优化与执行计划分析
- - '##'
  - 查询存储
- - '#'
  - Azure SQL 中的查询存储功能
- - '##'
  - 概述
- - '##'
  - 查询存储视图
- - '##'
  - 查询示例
- - '#'
  - 工作中的查询存储
- - '##'
  - 比较与强制执行计划
- - '##'
  - 使用可视化工具
- - '##'
  - 分析等待统计
- - '##'
  - 云平台集成：查询性能见解
- - '##'
  - 在 SQL 中引发和捕获异常
- - '###'
  - 保持简单！
- - '##'
  - 与 Application Insights 集成
- - '#'
  - 指定你的 Application Insights 资源的检测键。
- - '#'
  - 指定你的 Spring Boot 应用程序名称。这可以是你希望给你的应用程序取的任何逻辑名称。
- - '###'
  - .NET/.NET Core 集成
- - '##'
  - 如果您想了解更多
- - '#'
  - 11. 与 Azure SQL 实现 DevOps
- - '##'
  - CI/CD：定义与概念
- - '##'
  - CI/CD 与 Azure SQL
- - '###'
  - GitHub Actions
- - '###'
  - Azure DevOps
- - '##'
  - 数据库迁移
- - '###'
  - 合成环境
- - '###'
  - 集成环境
- - '##'
  - 数据库迁移工具
- - '###'
  - 代码优先
- - '###'
  - 数据库优先
- - '####'
  - DACPAC
- - '##'
  - 比较工具
- - '##'
  - DbUp
- - '##'
  - 数据库测试
- - '##'
  - 整合所有内容
- - '##'
  - 如果你想了解更多
- - '#'
  - 索引
- - '##'
  - 添加数据
- - '##'
  - 数据监控
- - '##'
  - 数据行
- - '##'
  - JSON
- - '##'
  - 合并数据
- - '##'
  - Python/R
- - '##'
  - 表设计
- - '#'
  - B
- - '#'
  - C
- - '##'
  - 连接与查询
- - '##'
  - 持续集成 (CI)/持续部署 (CD)
- - '#'
  - D
- - '#'
  - E
- - '#'
  - F
- - '#'
  - G
- - '#'
  - H
- - '#'
  - I
- - '#'
  - J
- - '#'
  - K
- - '#'
  - L
- - '#'
  - M
- - '#'
  - N
- - '#'
  - O
- - '#'
  - P
- - '#'
  - Q
- - '#'
  - R
- - '#'
  - S
- - '#'
  - T
- - '##'
  - 表设计
- - '#'
  - U
- - '#'
  - V
- - '#'
  - W
- - '#'
  - X, Y, Z
