name: Expert Performance Indexing in SQL Server 2019
name_cn: SQL Server 2019 专家性能索引指南
slug: expert-performance-indexing-in-sql-server-2019
toc:
- - '#'
  - 版权信息
- - '#'
  - 引言
- - '##'
  - 本书内容是什么？
- - '##'
  - 本版有何新内容？
- - '##'
  - 总结
- - '###'
  - 关于作者和技术审阅者
- - '####'
  - 关于作者
- - '####'
  - 关于技术审阅者
- - '#'
  - 第1章 索引基础
- - '##'
  - 1.1 为何要构建索引？
- - '##'
  - 1.2 主要索引类型
- - '###'
  - 1.2.1 堆表
- - '###'
  - 1.2.2 注意
- - '###'
  - 1.2.3 聚簇索引
- - '###'
  - 1.2.4 非聚簇索引
- - '###'
  - 1.2.5 列存储索引
- - '###'
  - 1.2.6 其他索引类型
- - '##'
  - 1.3 索引类型
- - '###'
  - 1.3.1 空间索引
- - '###'
  - 1.3.2 哈希和范围索引
- - '###'
  - 1.3.3 全文搜索
- - '##'
  - 1.4 索引变体
- - '###'
  - 1.4.1 主键
- - '###'
  - 1.4.2 唯一索引
- - '###'
  - 1.4.3 包含列
- - '###'
  - 1.4.4 分区索引
- - '###'
  - 1.4.5 筛选索引
- - '###'
  - 1.4.6 压缩与索引
- - '###'
  - 1.4.7 索引数据定义语言
- - '####'
  - 创建索引
- - '##'
  - 1.5 SQL Server 索引操作指南
- - '###'
  - 1.5.1 修改索引
- - '###'
  - 1.5.2 ALTER INDEX 与 DROP INDEX 操作详解
- - '####'
  - ALTER INDEX 语法
- - '####'
  - 删除索引
- - '####'
  - 索引元数据
- - '#####'
  - sys.indexes
- - '#####'
  - sys.index_columns
- - '#####'
  - sys.index_resumable_operations
- - '#####'
  - sys.xml_indexes
- - '#####'
  - sys.selective_xml_index_paths
- - '#####'
  - sys.selective_xml_index_namespaces
- - '#####'
  - sys.spatial_indexes
- - '#####'
  - sys.spatial_index_tessellations
- - '#####'
  - sys.column_store_dictionaries
- - '#####'
  - sys.column_store_segments
- - '#####'
  - sys.column_store_row_groups
- - '#####'
  - sys.hash_indexes
- - '#####'
  - sys.fulltext_catalogs
- - '#####'
  - sys.fulltext_indexes
- - '#####'
  - sys.fulltext_index_columns
- - '###'
  - 1.5.3 本章小结
- - '#'
  - 第2章 索引存储基础
- - '##'
  - 2.1 存储基础
- - '###'
  - 2.1.1 页面
- - '###'
  - 2.1.2 区
- - '###'
  - 2.1.3 页面类型
- - '####'
  - 注意
- - '####'
  - 文件头页
- - '####'
  - 引导页
- - '####'
  - 页自由空间页面
- - '####'
  - 注意
- - '####'
  - 全局分配映射页面
- - '####'
  - 共享全局分配映射页面
- - '####'
  - 差异更改映射页面
- - '####'
  - 最小日志记录页面
- - '####'
  - 索引分配映射页面
- - '####'
  - 数据页
- - '####'
  - 索引页
- - '####'
  - 大对象页
- - '###'
  - 2.1.4 组织页面
- - '####'
  - 注意
- - '####'
  - 堆结构
- - '##'
  - 2.2 B 树结构
- - '##'
  - 2.3 列存储结构
- - '###'
  - 警告
- - '##'
  - 2.4 检查页面
- - '###'
  - 2.4.1 动态管理函数
- - '####'
  - sys.dm_db_database_page_allocations
- - '###'
  - 2.4.2 DMF 列描述与使用示例
- - '####'
  - DMF 列描述
- - '####'
  - sys.dm_db_database_page_allocations 的用例
- - '###'
  - 2.4.3 sys.dm_db_page_info
- - '####'
  - DBCC 命令
- - '####'
  - DBCC EXTENTINFO
- - '###'
  - 2.4.4 针对 dbo.IndexInternalsThree 的 DBCC IND 命令
- - '###'
  - 2.4.5 DBCC PAGE
- - '####'
  - 注意
- - '#####'
  - 页面头——仅打印选项
- - '#####'
  - 十六进制行打印选项
- - '#####'
  - 十六进制行打印选项
- - '#####'
  - 十六进制数据打印选项
- - '#####'
  - 行数据打印选项
- - '####'
  - 注意
- - '###'
  - 2.4.6 页面碎片
- - '####'
  - 注意
- - '####'
  - 转发记录
- - '###'
  - 2.4.7 页面拆分
- - '###'
  - 2.4.8 索引特性
- - '####'
  - 堆
- - '####'
  - 聚集索引
- - '####'
  - 非聚集索引
- - '####'
  - 列存储索引
- - '###'
  - 2.4.9 本章小结
- - '#'
  - 第3章 索引元数据与统计信息
- - '##'
  - 3.1 列级统计信息
- - '###'
  - 3.1.1 注意
- - '###'
  - 3.1.2 DBCC SHOW_STATISTICS
- - '###'
  - 3.1.3 统计信息头
- - '###'
  - 3.1.4 密度向量
- - '####'
  - 直方图
- - '####'
  - 目录视图
- - '#####'
  - sys.stats
- - '#####'
  - sys.stats_columns
- - '#####'
  - STATS_DATE
- - '#####'
  - sys.dm_db_stats_properties
- - '#####'
  - sys.dm_db_stats_histogram
- - '#####'
  - sys.dm_db_incremental_stats_properties
- - '#####'
  - 统计信息 DDL
- - '#####'
  - 列级统计信息总结
- - '##'
  - 3.2 索引使用统计信息
- - '###'
  - 3.2.1 注意
- - '###'
  - 3.2.2 标题列
- - '###'
  - 3.2.3 用户列
- - '###'
  - 3.2.4 索引操作与 `user_updates`
- - '####'
  - 系统列
- - '####'
  - 索引使用统计摘要
- - '##'
  - 3.3 索引操作统计
- - '###'
  - 3.3.1 注意
- - '###'
  - 3.3.2 头列
- - '###'
  - 3.3.3 DML 活动
- - '###'
  - 3.3.4 SELECT 活动
- - '####'
  - 范围扫描
- - '####'
  - 单例查找
- - '#####'
  - 转发获取
- - '###'
  - 3.3.5 锁争用
- - '####'
  - 行锁
- - '####'
  - 页锁
- - '####'
  - 锁升级
- - '####'
  - 锁存竞争
- - '#####'
  - 页面 I/O 锁存
- - '#####'
  - 页面锁存
- - '####'
  - 注意
- - '###'
  - 3.3.6 页面分配周期
- - '####'
  - 注意
- - '###'
  - 3.3.7 压缩
- - '###'
  - 3.3.8 LOB 访问
- - '###'
  - 3.3.9 行版本
- - '###'
  - 3.3.10 索引操作统计摘要
- - '##'
  - 3.4 索引物理统计
- - '###'
  - 3.4.1 注意
- - '###'
  - 3.4.2 头部列
- - '###'
  - 3.4.3 行统计信息
- - '###'
  - 3.4.4 碎片统计信息
- - '###'
  - 3.4.5 索引物理统计信息摘要
- - '##'
  - 3.5 列存储统计信息
- - '###'
  - 3.5.1 列存储物理统计信息
- - '####'
  - 头列
- - '####'
  - 统计信息列
- - '###'
  - 3.5.2 列存储操作统计信息
- - '####'
  - 头列
- - '####'
  - 统计信息列
- - '###'
  - 3.5.3 本章小结
- - '#'
  - 第4章 XML 索引
- - '##'
  - 4.1 XML 数据
- - '###'
  - 4.1.1 优势
- - '###'
  - 4.1.2 注意事项
- - '##'
  - 4.2 XML 索引
- - '###'
  - 4.2.1 主/次 XML 索引
- - '####'
  - 注意
- - '####'
  - 主 XML 索引
- - '####'
  - 警告
- - '###'
  - 4.2.2 辅助 XML 索引
- - '####'
  - 创建辅助 XML 索引
- - '###'
  - 4.2.3 执行计划对比
- - '###'
  - 4.2.4 索引大小与结构
- - '###'
  - 4.2.5 维护 XML 索引
- - '###'
  - 4.2.6 存储与性能考量
- - '##'
  - 4.3 选择性 XML 索引
- - '###'
  - 4.3.1 创建选择性 XML 索引
- - '###'
  - 4.3.2 扩展选择性 XML 索引
- - '##'
  - 4.4 总结
- - '#'
  - 第5章 空间索引
- - '##'
  - 5.1 空间数据如何被索引
- - '##'
  - 5.2 创建空间索引
- - '###'
  - 覆盖规则
- - '###'
  - 每对象单元格规则
- - '###'
  - 最深单元格规则
- - '###'
  - 注意事项
- - '##'
  - 5.3 使用索引支持的方法
- - '##'
  - 5.4 理解统计信息、属性与信息
- - '###'
  - 视图
- - '##'
  - 5.5 操作流程
- - '##'
  - 5.6 调整空间索引
- - '##'
  - 5.7 空间索引的限制
- - '##'
  - 5.8 总结
- - '#'
  - 第6章 索引内存优化表
- - '###'
  - 注意
- - '##'
  - 6.1 内存优化表概述
- - '##'
  - 6.2 哈希索引
- - '###'
  - 警告
- - '###'
  - 注意
- - '##'
  - 6.3 范围索引
- - '###'
  - 注意
- - '##'
  - 6.4 总结
- - '#'
  - 第7章 全文索引
- - '##'
  - 7.1 全文索引
- - '##'
  - 7.2 语法
- - '##'
  - 7.3 关键索引
- - '##'
  - 7.4 填充
- - '##'
  - 7.5 停用词列表
- - '##'
  - 7.6 全文搜索索引目录视图与属性
- - '##'
  - 7.7 总结
- - '#'
  - 第8章 索引的误区与最佳实践
- - '##'
  - 8.1 索引误区
- - '###'
  - 误区 1：数据库不需要索引
- - '###'
  - 误区 2：主键总是聚集的
- - '###'
  - 误区 3：在线索引操作不会阻塞
- - '####'
  - 注意
- - '###'
  - 误区 4：多列索引中的任何列都可以用于过滤
- - '###'
  - 误区 5：聚集索引按物理顺序存储记录
- - '###'
  - 误区 6：索引总是以相同的顺序输出
- - '###'
  - 误区 7：填充因子在插入时应用于索引
- - '###'
  - 误区 8：从堆中删除数据会导致不可恢复的空间
- - '###'
  - 误区 9：每个表都应该使用堆/聚集索引
- - '##'
  - 8.2 索引最佳实践
- - '###'
  - 当前工作负载的索引指南
- - '###'
  - 默认情况下在主键上使用聚集索引
- - '###'
  - 指定填充因子
- - '####'
  - 数据库级别的填充因子
- - '####'
  - 索引级别的填充因子
- - '###'
  - 为外键列创建索引
- - '###'
  - 平衡索引数量
- - '##'
  - 8.3 总结
- - '#'
  - 第9章 索引维护
- - '##'
  - 9.1 索引碎片化
- - '###'
  - 9.1.1 碎片化操作
- - '####'
  - 插入操作
- - '#####'
  - INSERT 操作
- - '#####'
  - UPDATE 操作
- - '#####'
  - Delete 操作
- - '#####'
  - 收缩操作
- - '###'
  - 9.1.2 碎片变体
- - '####'
  - 堆膨胀与转发
- - '##'
  - 9.2 列存储碎片化
- - '###'
  - 注意
- - '###'
  - 碎片化问题
- - '##'
  - 9.3 索引 I/O
- - '##'
  - 9.4 连续读取
- - '##'
  - 9.5 碎片整理选项
- - '##'
  - 9.6 索引重建
- - '###'
  - 注意
- - '####'
  - 索引重组
- - '####'
  - 删除和创建
- - '###'
  - 碎片整理策略
- - '###'
  - 维护计划
- - '####'
  - 重新组织索引任务
- - '####'
  - 重建索引任务
- - '####'
  - 维护计划摘要
- - '###'
  - T-SQL 脚本
- - '###'
  - 注意
- - '##'
  - 9.7 使用 T-SQL 脚本进行索引碎片整理
- - '###'
  - 注意事项
- - '###'
  - 注意事项
- - '##'
  - 9.8 预防碎片
- - '###'
  - 填充因子
- - '###'
  - 数据类型
- - '###'
  - 默认值
- - '##'
  - 9.9 索引统计信息维护
- - '###'
  - 9.9.1 自动维护统计信息
- - '####'
  - 自动创建
- - '####'
  - 自动更新
- - '####'
  - 防止自动更新
- - '####'
  - 内存中统计信息
- - '###'
  - 9.9.2 手动维护统计信息
- - '###'
  - 9.9.3 维护计划
- - '###'
  - 9.9.4 T-SQL 脚本
- - '####'
  - 存储过程
- - '###'
  - DDL 命令
- - '##'
  - 9.10 总结
- - '#'
  - 第10章 索引工具
- - '##'
  - 10.1 缺失索引
- - '###'
  - 注意
- - '###'
  - 解释动态管理对象
- - '####'
  - sys.dm_db_missing_index_details
- - '####'
  - sys.dm_db_missing_index_columns
- - '####'
  - sys.dm_db_missing_index_groups
- - '####'
  - sys.dm_db_missing_index_group_stats
- - '###'
  - 使用 DMO
- - '###'
  - 注意
- - '##'
  - 10.2 数据库引擎调优顾问
- - '###'
  - 注意
- - '###'
  - 解释 DTA
- - '###'
  - 注意
- - '###'
  - 使用 DTA GUI
- - '###'
  - 保存建议
- - '###'
  - 使用 DTA 实用工具
- - '###'
  - DTA 命令行参数参考
- - '###'
  - 注意
- - '##'
  - 10.3 总结
- - '#'
  - 第11章 索引策略
- - '##'
  - 11.1 堆表
- - '###'
  - 临时对象
- - '###'
  - 注意
- - '###'
  - 其他堆场景
- - '##'
  - 11.2 聚簇索引
- - '###'
  - 标识序列
- - '###'
  - 注意事项
- - '###'
  - 自然键
- - '###'
  - 外键模式
- - '###'
  - 实施外键模式
- - '###'
  - 性能比较
- - '####'
  - 用例 1：返回单行主数据
- - '####'
  - 用例 2：返回多行主数据
- - '###'
  - 多列模式
- - '###'
  - 索引模式对比测试与分析
- - '####'
  - 第一个测试：基于 `RoleName` 的查询
- - '####'
  - 第二个测试：基于 `EmployeeName` 的查询
- - '####'
  - 多列模式的实现与属性
- - '####'
  - 注意事项
- - '#####'
  - 全局唯一标识符
- - '#####'
  - 注意
- - '##'
  - 11.3 非聚集索引
- - '###'
  - Search Columns
- - '###'
  - Index Intersection
- - '###'
  - 索引交叉模式 vs. 多列模式
- - '####'
  - 索引交叉模式
- - '####'
  - 多列模式
- - '###'
  - 覆盖索引
- - '####'
  - 注意
- - '###'
  - 包含列
- - '###'
  - 包含列模式
- - '##'
  - 11.4 过滤索引
- - '###'
  - 筛选索引模式
- - '###'
  - 外键模式
- - '###'
  - 外键模式与列存储索引
- - '##'
  - 11.5 列存储索引
- - '###'
  - 注意
- - '###'
  - 在 `dbo.FactSales` 上测试非聚集列存储索引的性能
- - '###'
  - 使用聚集列存储索引
- - '###'
  - 注意
- - '##'
  - 11.6 JSON 索引
- - '##'
  - 11.7 索引存储策略
- - '###'
  - 注意
- - '###'
  - 行压缩
- - '####'
  - 工作原理
- - '####'
  - 示例设置
- - '####'
  - 实施与性能影响
- - '####'
  - 实施考虑因素
- - '###'
  - 页面压缩
- - '###'
  - 注意
- - '##'
  - 11.8 索引视图
- - '##'
  - 11.9 本章小结
- - '#'
  - 第12章 查询策略
- - '##'
  - 12.1 LIKE 比较
- - '##'
  - 12.2 连接
- - '##'
  - 12.3 计算列
- - '###'
  - 注意
- - '##'
  - 12.4 标量函数
- - '##'
  - 12.5 数据类型转换
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - 12.6 总结
- - '#'
  - 第13章 监控索引
- - '###'
  - 注意
- - '##'
  - 13.1 性能计数器
- - '###'
  - 表 13-1
- - '###'
  - 注意
- - '##'
  - 13.2 监控 SQL Server 索引性能
- - '##'
  - 13.3 动态管理对象
- - '###'
  - 警告
- - '###'
  - 索引使用情况统计
- - '###'
  - 索引操作统计
- - '###'
  - 注意
- - '###'
  - 清单 13-8：索引操作统计信息快照表
- - '###'
  - 清单 13-9：填充索引操作统计信息快照
- - '###'
  - 清单 13-10：索引操作统计快照填充
- - '###'
  - 索引物理统计
- - '###'
  - 提示
- - '###'
  - 等待统计信息
- - '###'
  - 注意
- - '###'
  - 数据清理
- - '##'
  - 13.4 事件追踪
- - '###'
  - SQL Trace
- - '###'
  - 注意
- - '###'
  - 添加事件和列到 SQL Trace 会话
- - '###'
  - 向 SQL Trace 会话添加筛选器
- - '###'
  - 启动 SQL Trace 会话
- - '###'
  - 停止 SQL Trace 会话
- - '##'
  - 13.5 扩展事件
- - '##'
  - 13.6 查询存储
- - '##'
  - 13.7 总结
- - '#'
  - 第14章 索引分析
- - '###'
  - 注意
- - '##'
  - 14.1 审查服务器状态
- - '###'
  - 性能计数器
- - '###'
  - 注意
- - '##'
  - 14.2 每秒转发记录数
- - '##'
  - 14.3 转发行缓解
- - '###'
  - 每秒空闲空间扫描和页面获取次数
- - '####'
  - 识别高插入速率的堆表
- - '####'
  - 缓解策略
- - '###'
  - 每秒全表扫描次数
- - '###'
  - 每秒索引搜索次数
- - '###'
  - 每秒页面拆分数
- - '###'
  - 每秒页面查找次数
- - '##'
  - 14.4 锁等待时间
- - '###'
  - 每秒锁等待数
- - '###'
  - 每秒死锁数量
- - '##'
  - 14.5 等待统计信息
- - '###'
  - 注意
- - '####'
  - CXPACKET
- - '###'
  - SQL Server 中的 CXPACKET 等待与索引优化
- - '####'
  - 关于并行等待
- - '###'
  - 检查执行计划缓存
- - '###'
  - 警告
- - '###'
  - 查询查询存储
- - '###'
  - 检查当前执行的计划
- - '####'
  - IO_COMPLETION
- - '###'
  - SQL Server 中与索引相关的等待类型
- - '####'
  - LCK_M_∗
- - '####'
  - PAGEIOLATCH_∗
- - '###'
  - 缓冲区分配
- - '##'
  - 14.6 Schema 发现
- - '###'
  - 识别堆表
- - '###'
  - 重复索引
- - '###'
  - 重叠索引
- - '###'
  - 未索引的外键
- - '###'
  - 未压缩索引
- - '###'
  - 注意
- - '##'
  - 14.7 数据库引擎调优顾问
- - '###'
  - 注意
- - '##'
  - 14.8 未使用的索引
- - '##'
  - 14.9 索引计划用法
- - '##'
  - 14.10 本章小结
- - '#'
  - 第15章 索引方法论
- - '##'
  - 15.1 索引方法
- - '##'
  - 15.2 实施
- - '###'
  - 沟通
- - '####'
  - 影响分析
- - '###'
  - 注意
- - '###'
  - 状态报告
- - '###'
  - 部署脚本
- - '####'
  - 准备数据库架构的部署和回滚方案
- - '####'
  - 将索引变更保存到源代码仓库
- - '####'
  - 包含影响分析的同行评审
- - '###'
  - 注意
- - '##'
  - 15.3 执行
- - '##'
  - 15.4 重复
- - '##'
  - 15.5 总结
- - '#'
  - 附录
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J, K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U, V
- - '###'
  - W
- - '###'
  - X, Y, Z
