name: Applied Mathematics for Database Professionals
name_cn: 数据库从业者的应用数学
slug: applied-mathematics-for-database-professionals
toc:
- - '#'
  - 目录
- - '##'
  - 数据库专业人员的应用数学
- - '###'
  - Lex de Haan
- - '###'
  - 1954–2006
- - '##'
  - 内容概览
- - '###'
  - 第一部分 理论 数学基础
- - '####'
  - 第 1 章
- - '####'
  - 第 2 章
- - '####'
  - 第 3 章
- - '####'
  - 第 4 章
- - '###'
  - 第二部分 实践 应用
- - '####'
  - 第 5 章
- - '####'
  - 第 6 章
- - '####'
  - 第 7 章
- - '####'
  - 第 8 章
- - '####'
  - 第 9 章
- - '####'
  - 第 10 章
- - '###'
  - 第三部分 实现
- - '####'
  - 第 11 章
- - '####'
  - 第 12 章
- - '###'
  - 第四部分 附录
- - '####'
  - 附录 A
- - '####'
  - 附录 B
- - '####'
  - 附录 C
- - '####'
  - 附录 D
- - '####'
  - 附录 E
- - '####'
  - 索引
- - '##'
  - 前言
- - '###'
  - 第十一章：理论与实践
- - '##'
  - 关于作者
- - '###'
  - Lex de Haan
- - '###'
  - Toon Koppelaars
- - '##'
  - 关于技术评审员
- - '###'
  - Chris Date
- - '##'
  - 致谢
- - '##'
  - 引言
- - '###'
  - 数学家
- - '###'
  - 书籍高层概述
- - '##'
  - 第一部分 数学基础
- - '###'
  - 第 1 章 逻辑：导论
- - '####'
  - 逻辑的历史
- - '#####'
  - 罗素悖论
- - '####'
  - 值、变量和类型
- - '####'
  - 命题和谓词
- - '#####'
  - 谓词与命题
- - '#####'
  - 逻辑连接词
- - '#####'
  - 简单谓词与复合谓词
- - '####'
  - 使用括号和运算符优先级规则
- - '####'
  - 真值表
- - '#####'
  - 表 1-5. 与（合取）的真值表
- - '#####'
  - 表 1-6. 或（析取）的真值表
- - '#####'
  - 表 1-7. 如果…那么（蕴涵）的真值表
- - '#####'
  - 表 1-8. 当且仅当（等价）的真值表
- - '####'
  - 蕴涵
- - '####'
  - 谓词强度
- - '####'
  - 再深入一点
- - '####'
  - 函数完备性
- - '####'
  - 特殊的谓词类别
- - '#####'
  - 重言式与矛盾式
- - '#####'
  - 假言推理与拒取式
- - '#####'
  - 逻辑等价与重写规则
- - '#####'
  - 重写规则
- - '####'
  - 章节小结
- - '#####'
  - 练习题
- - '###'
  - 第 2 章 集合论：导论
- - '####'
  - 集合与元素
- - '#####'
  - 定义 2-1：集合
- - '####'
  - 指定集合的方法
- - '#####'
  - 枚举法
- - '#####'
  - 谓词法
- - '#####'
  - 替换法
- - '#####'
  - 混合法
- - '####'
  - 韦恩图
- - '####'
  - 基数与单元素集
- - '#####'
  - 单元素集
- - '####'
  - 选择运算符
- - '####'
  - 子集
- - '#####'
  - 定义 2-5：真子集 / 真超集
- - '#####'
  - 代码清单 2-6：为真的子集命题示例
- - '####'
  - 并集、交集与差集
- - '#####'
  - 表 2-2：常见集合算子
- - '#####'
  - 图 2-2：并集、交集和差集的韦恩图
- - '#####'
  - 图 2-3：A (集合 {1,3,5}) 和 B (集合 {3,4,5,6}) 的韦恩图
- - '####'
  - 集合算子的性质
- - '#####'
  - 表 2-3：集合算子的性质
- - '######'
  - 结合律 (Associativity)
- - '######'
  - 分配律 (Distributivity)
- - '#####'
  - 集合运算符与不相交集合
- - '######'
  - 定义 2-6：不相交集合
- - '#####'
  - 集合运算符与空集
- - '#####'
  - 幂集与划分
- - '######'
  - 定义 2-7：幂集
- - '#####'
  - 注意
- - '####'
  - 清单 2-8. 幂集特性
- - '####'
  - 集合的并集
- - '#####'
  - '定义 2-8: 一元并集运算符'
- - '####'
  - 划分
- - '#####'
  - '定义 2-9: 划分'
- - '####'
  - 有序对与笛卡尔积
- - '#####'
  - 有序对
- - '#####'
  - 笛卡尔积
- - '####'
  - 求和运算符
- - '####'
  - 一些方便的集合简写表示法
- - '####'
  - 章节小结
- - '#####'
  - 练习
- - '###'
  - 第 3 章 更多逻辑内容
- - '####'
  - 代数属性
- - '#####'
  - 同一律
- - '####'
  - 逻辑恒等式与性质
- - '#####'
  - 交换律
- - '#####'
  - 结合律
- - '#####'
  - 分配律
- - '#####'
  - 自反性
- - '#####'
  - 传递性
- - '#####'
  - 德·摩根定律
- - '#####'
  - 幂等性
- - '#####'
  - 双重否定（或对合律）
- - '#####'
  - 吸收律
- - '####'
  - 量词
- - '#####'
  - 一般量词语法
- - '#####'
  - 量词与有限集
- - '#####'
  - 空集上的量化
- - '#####'
  - 嵌套量词
- - '######'
  - 交换嵌套量词
- - '#####'
  - 连续嵌套量词的缩写
- - '#####'
  - 量词的分配律
- - '#####'
  - 量词的否定
- - '####'
  - 带量词的重写规则
- - '####'
  - 范式
- - '#####'
  - 合取范式
- - '#####'
  - 析取范式
- - '#####'
  - 求给定谓词的范式
- - '######'
  - 求给定谓词的析取范式
- - '######'
  - 功能完备性再探
- - '######'
  - 求给定谓词的合取范式
- - '####'
  - 章节摘要
- - '#####'
  - 练习
- - '###'
  - 第 4 章 关系与函数
- - '####'
  - 二元关系
- - '####'
  - 有序对与笛卡尔积回顾
- - '####'
  - 二元关系
- - '####'
  - 函数
- - '####'
  - 函数的定义域与值域
- - '#####'
  - 示例函数的定义域与值域
- - '#####'
  - 从图示确定定义域与值域
- - '#####'
  - 函数的定义
- - '#####'
  - 函数应用
- - '####'
  - 恒等函数
- - '####'
  - 函数的子集
- - '####'
  - 小结
- - '####'
  - 函数上的操作
- - '#####'
  - 并集、交集与差集
- - '######'
  - 函数的并集与兼容性
- - '######'
  - 函数的交集与差集
- - '#####'
  - 函数的限制
- - '#####'
  - 集合函数
- - '#####'
  - 特征化
- - '#####'
  - 外部谓词
- - '#####'
  - 集合函数的泛化乘积
- - '######'
  - 定义 4-7：集合函数的泛化乘积
- - '######'
  - 清单 4-7. *泛化乘积的应用示例*
- - '#####'
  - 封闭世界假设
- - '#####'
  - 约束规范预览
- - '####'
  - 函数复合
- - '####'
  - 章节摘要
- - '#####'
  - 练习题
- - '##'
  - 第二部分 应用
- - '###'
  - 第 5 章 表与数据库状态
- - '####'
  - 术语
- - '#####'
  - 数据库设计
- - '#####'
  - 注意
- - '####'
  - 数据库变量
- - '#####'
  - 注意
- - '####'
  - 数据库宇宙
- - '####'
  - 数据库状态
- - '####'
  - 数据库
- - '####'
  - 数据库管理系统 (DBMS)
- - '####'
  - 表设计
- - '####'
  - 表结构
- - '####'
  - 表
- - '####'
  - 表集
- - '#####'
  - 表的形式化规范
- - '####'
  - 注意
- - '####'
  - 定义 5-1：表
- - '####'
  - 注意
- - '#####'
  - 简写记法
- - '#####'
  - 表的构造
- - '######'
  - 图 5-1. 表 `T1` 的简写记法
- - '######'
  - 注意
- - '######'
  - 定义 5-2：表的标题
- - '#####'
  - 表的构造
- - '######'
  - 代码清单 5-2. 集合函数 `F1`
- - '######'
  - 代码清单 5-3. 集合函数 `F1` 的广义积
- - '######'
  - 代码清单 5-4. 零件的特征描述
- - '####'
  - 数据库状态
- - '#####'
  - 数据库状态的形式化表示
- - '######'
  - 图 5-2. 示例员工表`EMP1`
- - '######'
  - 图 5-3. 示例部门表`DEP1`
- - '######'
  - 清单 5-5. 持有表`EMP1`和`DEP1`的数据库状态`DBS1`
- - '#####'
  - 数据库骨架
- - '######'
  - 清单 5-6. 数据库骨架 `SK1`
- - '#####'
  - 表上的操作
- - '######'
  - 并集、交集和差集
- - '######'
  - 图 5-4. 示例表 `E1`、`E2` 和 `E3`
- - '######'
  - 并集
- - '######'
  - 交集
- - '######'
  - 差集
- - '######'
  - 投影
- - '######'
  - 定义 5-3：表的投影
- - '######'
  - 清单 5-7. 表 T3
- - '######'
  - 限制
- - '######'
  - 连接（Join）
- - '######'
  - 属性重命名（Attribute Renaming）
- - '######'
  - 定义 5-5：属性重命名操作符
- - '######'
  - 扩展
- - '######'
  - 图 5-8. 用新属性扩展示例
- - '######'
  - 图 5-9. 另一个用新属性扩展表的例子
- - '######'
  - 聚合
- - '######'
  - 图 5-10. `T6` 按部门的工资总和
- - '######'
  - 定义 5-6：平均值运算符 (AVG)
- - '######'
  - 定义 5-7：最大值 (MAX) 和最小值 (MIN) 运算符
- - '#####'
  - 清单 5-8. 涉及 AVG、MAX 和 MIN 的示例表达式
- - '####'
  - 章节小结
- - '#####'
  - 练习
- - '###'
  - 第 6 章 元组、表与数据库谓词
- - '####'
  - 元组谓词
- - '####'
  - 表谓词
- - '####'
  - 数据库谓词
- - '#####'
  - 关于数据完整性谓词的一些说明
- - '#####'
  - 表和数据库谓词的常见模式
- - '######'
  - 唯一标识谓词
- - '######'
  - 定义 6-1：唯一标识谓词
- - '######'
  - 列表 6-9：唯一标识谓词的其他表现形式
- - '######'
  - 子集要求谓词
- - '######'
  - 定义 6-2：子集要求谓词
- - '######'
  - 图 6-5：示例表 DEP2
- - '######'
  - 图 6-6. *从 EMP1 到 DEP2 的子集需求可视化*
- - '######'
  - 特殊化谓词
- - '######'
  - 图 6-7. *表 TRN1*
- - '######'
  - 清单 6-10. *关于表 EMP1 和 TRN1 的命题*
- - '######'
  - 图 6-8. *表 MAN1*
- - '######'
  - 泛化
- - '######'
  - 图 6-9. 表 `CLK1`
- - '######'
  - 连接中的元组谓词
- - '######'
  - 图 6-10. 表 `EMPDEP1`，表 `EMP1` 和 `DEP1` 的连接
- - '######'
  - 列表 6-11. 更多关于表 `EMP1` 和 `DEP1` 的连接中的元组谓词
- - '####'
  - 章节摘要
- - '#####'
  - 练习
- - '###'
  - 第 7 章 规范数据库设计
- - '####'
  - 记录数据库与约束
- - '####'
  - 数据库设计的内部层次
- - '#####'
  - 数据库的自顶向下视图
- - '####'
  - 约束分类模式
- - '####'
  - 指定示例数据库设计
- - '#####'
  - 数据库骨架
- - '#####'
  - 薪资等级
- - '#####'
  - SREP -- 销售代表
- - '#####'
  - MEMP -- 被管理员工
- - '#####'
  - TERM -- 已离职员工
- - '#####'
  - DEPT -- 部门
- - '#####'
  - GRD -- 薪资等级
- - '#####'
  - CRS -- 课程
- - '#####'
  - OFFR -- 课程开设
- - '#####'
  - REG -- 课程注册
- - '#####'
  - HIST -- 员工历史记录
- - '######'
  - 表 7-1. 外谓词
- - '#####'
  - 表
- - '######'
  - 外部谓词
- - '#####'
  - 特征描述
- - '######'
  - 代码清单 7-2. 特征化 chr_EMP
- - '######'
  - 代码清单 7-3. 特征化 chr_SREP
- - '######'
  - 代码清单 7-4. 特征化 chr_MEMP
- - '######'
  - 代码清单 7-5. 特征化 chr_TERM
- - '######'
  - 代码清单 7-6. 特征化 chr_DEPT
- - '######'
  - 代码清单 7-7. 特征化 chr_GRD
- - '######'
  - 代码清单 7-8. 特征化 chr_CRS
- - '######'
  - 代码清单 7-9. 特征化 chr_OFFR
- - '######'
  - 代码清单 7-10. 特征化 chr_REG
- - '######'
  - 代码清单 7-11. 特征化 chr_HIST
- - '#####'
  - 元组全域
- - '######'
  - 代码清单 7-12. 表征 `chr_RESULT`
- - '#####'
  - 指定数据库设计
- - '######'
  - 清单 7-13. 元组宇宙 `tup_EMP`
- - '######'
  - 清单 7-14. 元组宇宙 `tup_SREP`
- - '######'
  - 清单 7-15. 元组宇宙 `tup_MEMP`
- - '######'
  - 清单 7-16. 元组宇宙 `tup_TERM`
- - '######'
  - 清单 7-17. 元组宇宙 `tup_DEPT`
- - '######'
  - 清单 7-18. 元组宇宙 `tup_GRD`
- - '######'
  - 清单 7-19. 元组宇宙 `tup_CRS`
- - '######'
  - 清单 7-20. 元组宇宙 `tup_OFFR`
- - '######'
  - 清单 7-21. 元组宇宙 `tup_REG`
- - '######'
  - 清单 7-22. 元组宇宙 `tup_HIST`
- - '#####'
  - 表宇宙
- - '######'
  - 图 7-2. 一个可能的名为 R1 的 RESULT 表
- - '######'
  - 代码清单 7-23. 表谓词 P1, P2, P3 和 P4
- - '######'
  - 代码清单 7-24. 表宇宙 `tab_RESULT` 的规范
- - '######'
  - 代码清单 7-25. 表宇宙 `tab_RESULT` 的枚举规范
- - '######'
  - 代码清单 7-26. *表全域 `tab_EMP`*
- - '######'
  - 代码清单 7-27. *表全域 `tab_SREP`*
- - '######'
  - 代码清单 7-28. *表全域 `tab_MEMP`*
- - '######'
  - 代码清单 7-29. *表全域 `tab_TERM`*
- - '######'
  - 代码清单 7-30. *表全域 `tab_DEPT`*
- - '#####'
  - 数据库设计的形式化规范（续）
- - '######'
  - 数据库宇宙
- - '######'
  - 代码清单 7-39. 数据库宇宙 `DB_UEX`
- - '######'
  - 代码清单 7-40. `DB_UEX`的子集需求
- - '######'
  - 清单 7-42. DB_UEX 中的元组-连接约束
- - '######'
  - 代码清单 7-43. DB_UEX 的“其他”数据库约束
- - '####'
  - 章节摘要
- - '#####'
  - 练习
- - '###'
  - 第 8 章 规范状态转移约束
- - '####'
  - 更多数据完整性谓词
- - '####'
  - 一个简单例子
- - '####'
  - 状态转换谓词
- - '####'
  - 状态转换约束
- - '#####'
  - 状态转换全域
- - '####'
  - 完成示例数据库设计
- - '#####'
  - 状态转换约束规范
- - '######'
  - 1. 约束 STC1：薪资不能降低
- - '######'
  - 2. 约束 STC2 与 STC3：`STATUS` 属性的转换
- - '######'
  - STC2 的工作方式
- - '######'
  - STC3 的工作方式
- - '######'
  - 3. 约束 STC4：`HIST` 表的历史记录
- - '######'
  - 4. 约束 STC5：`HIST` 表的语义
- - '######'
  - 5. `REG` 表的 `EVAL` 属性
- - '######'
  - 约束 STC6：新注册的初始评估值
- - '######'
  - 约束 STC7：评估值的转换
- - '######'
  - 6. 约束规范方式总结
- - '#####'
  - 结论
- - '####'
  - 章节总结
- - '#####'
  - 练习题
- - '###'
  - 第 9 章 数据检索
- - '####'
  - 形式化指定查询
- - '####'
  - 基于 DB_UEX 的示例查询
- - '####'
  - 代码清单 9-2. 查询 EXQ2(dbs)
- - '####'
  - 代码清单 9-3. 查询 EXQ3(dbs)
- - '####'
  - 代码清单 9-4. 查询 EXQ4(dbs)
- - '####'
  - 代码清单 9-5. 查询 EXQ5(dbs)
- - '####'
  - 注意
- - '####'
  - 列表 9-7. 查询 `EXQ7(dbs)`
- - '####'
  - 清单 9-8. 查询 `EXQ8(dbs)`
- - '####'
  - 图 9-1. 部门和员工表示例
- - '####'
  - 代码清单 9-9. 查询 EXQ9(dbs)
- - '####'
  - 代码清单 9-10. 查询 EXQ10(dbs)
- - '####'
  - 查询示例：EXQ9
- - '####'
  - 查询示例：EXQ11
- - '####'
  - 关于否定的说明
- - '####'
  - 章节总结
- - '#####'
  - 练习
- - '###'
  - 第 10 章 数据操作
- - '####'
  - 形式化指定查询
- - '####'
  - 在 `DB_UEX` 上的查询示例
- - '####'
  - 关于否定的评注
- - '####'
  - 章节总结
- - '#####'
  - 练习
- - '####'
  - 插入操作的形式化规范
- - '####'
  - 事务定义与约束讨论
- - '#####'
  - 问题分析
- - '#####'
  - 改进的事务定义
- - '#####'
  - 约束的考量
- - '#####'
  - 状态转换约束
- - '####'
  - DB_UEX 上的示例事务
- - '####'
  - 代码清单 10-2. 事务 ETX1(dbs)
- - '####'
  - 代码清单 10-3. 事务 ETX2(dbs)
- - '####'
  - 规范概述
- - '#####'
  - 注意
- - '####'
  - 事务规范示例
- - '#####'
  - 注意
- - '####'
  - 更新事务示例
- - '####'
  - 章节总结
- - '#####'
  - 练习
- - '##'
  - 第三部分 实现
- - '###'
  - 第 11 章 在 Oracle 中实现数据库设计
- - '####'
  - 引言
- - '####'
  - 窗口-on-数据应用程序
- - '#####'
  - 窗口-on-数据应用程序代码分类
- - '####'
  - 实现数据完整性代码
- - '#####'
  - 替代实现策略
- - '#####'
  - 偏好顺序
- - '####'
  - 实现表结构
- - '####'
  - 实现属性约束
- - '####'
  - 实现元组约束
- - '#####'
  - 表约束实现问题
- - '######'
  - DI 代码执行模型
- - '######'
  - DI 代码序列化
- - '####'
  - 实现表约束
- - '####'
  - 实现数据库约束
- - '####'
  - 实现转移约束
- - '#####'
  - 引入延迟检查
- - '######'
  - 为何需要延迟检查？
- - '######'
  - 延迟检查的执行模型概述
- - '####'
  - '`RuleGen` 框架'
- - '####'
  - 章节总结
- - '###'
  - 第 12 章 摘要与结论
- - '##'
  - 第四部分 附录
- - '###'
  - 附录 A 示例数据库的正式定义
- - '###'
  - 附录 B 符号
- - '###'
  - 附录 C 参考文献
- - '###'
  - 附录 D 空值与三（或多）值逻辑
- - '###'
  - 附录 E 选定习题的答案
- - '###'
  - 索引
