name: Introducing SQLite for mobile developers
name_cn: 移动开发者的 SQLite 入门指南
slug: introducing-sqlite-for-mobile-developers
toc:
- - '#'
  - 面向移动开发者的 SQLite 入门指南
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '#'
  - 第1章：快速掌握数据库与 SQLite
- - '##'
  - 超越“庞大”的概念
- - '##'
  - 数据库是结构化和有组织的
- - '##'
  - 数据库是智能的
- - '##'
  - 关系型数据库和 SQL 来救场
- - '##'
  - 深入了解关系型表与查询
- - '###'
  - 基本查询结构
- - '####'
  - SQL 操作：`SELECT`
- - '####'
  - 要选择的 SQL 数据：列名列表
- - '####'
  - SQL 数据源：表名
- - '####'
  - SQL 条件：`WHERE`
- - '###'
  - 审视其他查询选择
- - '##'
  - 本章小结
- - '#'
  - 第2章：理解 SQLite 是什么
- - '##'
  - 全面认识数据库
- - '##'
  - 定义 SQLite
- - '###'
  - 正确看待数据库
- - '###'
  - SQLite 是 DBMS 吗？
- - '###'
  - SQLite 为单用户设计
- - '####'
  - 单用户不意味着单线程
- - '####'
  - 在多用户环境中使用 SQLite
- - '###'
  - SQLite 是自包含的
- - '####'
  - 自包含代码
- - '####'
  - 自包含数据
- - '###'
  - SQLite 支持事务并符合 ACID 原则
- - '####'
  - ACID
- - '####'
  - 移动设备上的并发和 ACID 事务
- - '##'
  - 本章小结
- - '#'
  - 第3章：使用 SQLite 基础：存储和检索数据
- - '##'
  - 术语和定义
- - '##'
  - 使用`sqlite3`
- - '###'
  - 运行`sqlite3`并让其创建新数据库
- - '###'
  - 创建并命名一个新的`sqlite3`数据库
- - '###'
  - 删除数据库
- - '###'
  - 运行`sqlite3`并打开现有数据库
- - '##'
  - 实验 SQLite 语法
- - '##'
  - 关于主键
- - '##'
  - 使用图形化 SQLite 编辑器探索你的`sqlite3`数据库
- - '##'
  - 创建表
- - '###'
  - 使用图形化 SQLite 编辑器
- - '###'
  - 创建表列
- - '###'
  - 使用 SQLite3
- - '##'
  - 向表中插入数据
- - '###'
  - 使用图形用户界面
- - '###'
  - 使用 SQLite3
- - '##'
  - 检索数据
- - '###'
  - 使用图形用户界面
- - '###'
  - 使用`sqlite3`
- - '##'
  - 删除数据
- - '##'
  - 本章小结
- - '#'
  - 第4章：使用关系模型和 SQLite
- - '##'
  - 构建用户表
- - '##'
  - 构建分数表
- - '##'
  - 关联表
- - '###'
  - 在`SELECT`语句中使用别名来标识多表
- - '###'
  - 使用`rowid`主键
- - '###'
  - 在一个表中更改名称
- - '###'
  - 使用外键
- - '####'
  - 表 4-3. Users 表
- - '####'
  - 表 4-4. Scores 表
- - '##'
  - 连接表
- - '##'
  - 本章小结
- - '#'
  - 第5章：使用 SQLite 特性——你能用`SELECT`语句做什么
- - '##'
  - 概述：采用声明式思维
- - '##'
  - 查看测试数据
- - '##'
  - 对数据排序使其更易用
- - '##'
  - 数据分组可以整合信息
- - '##'
  - 在查询中使用变量
- - '##'
  - 本章小结
- - '#'
  - 第6章：在 PHP 中使用 SQLite
- - '##'
  - 将 PHP 和 SQLite 结合：基础
- - '###'
  - 验证你环境中的 PHP
- - '###'
  - 准备 SQLite 数据库
- - '###'
  - 为 PHP 定义“单用户”
- - '###'
  - PDO 与旧版 PHP/SQLite 数据库连接
- - '##'
  - 连接到你的 SQLite 数据库
- - '###'
  - 1. 创建新的 PDO 对象
- - '####'
  - 正确处理错误
- - '###'
  - 2. 创建并准备查询
- - '###'
  - 3. 执行查询
- - '###'
  - 4. 获取结果
- - '###'
  - 5. 使用结果
- - '##'
  - 本章小结
- - '#'
  - 第7章：在 Android/Java 中使用 SQLite
- - '##'
  - 将 SQLite 与任何操作系统、框架或语言集成
- - '##'
  - 在 Android 中使用 SQLite
- - '###'
  - 关键的数据库设计步骤
- - '###'
  - 使用静态值
- - '####'
  - 静态值可能在 API 中
- - '####'
  - 静态值可能在导入的文件中
- - '####'
  - 静态值可能在主文件中
- - '###'
  - 扩展 `SQLiteOpenHelper`
- - '##'
  - 本章小结
- - '#'
  - 第8章：在 iOS 和 OS X 中使用 SQLite 与 Core Data
- - '##'
  - 介绍 Core Data 框架
- - '###'
  - Core Data 的起源
- - '##'
  - 使用 Core Data 模型编辑器
- - '###'
  - 使用实体
- - '###'
  - 处理属性
- - '####'
  - 命名 Core Data 模型对象
- - '###'
  - 管理关系
- - '##'
  - 本章小结
- - '#'
  - 第9章：在 iOS 和 OS X 中使用 SQLite/Core Data 与 Swift
- - '##'
  - 查看 Core Data 栈
- - '##'
  - 向 Core Data 栈获取数据
- - '##'
  - 构建 Core Data 应用结构
- - '###'
  - 在 iOS 中将托管对象上下文传递给视图控制器
- - '###'
  - 在 iOS 的 `AppDelegate` 中设置 Core Data 栈
- - '####'
  - 在 iOS 中创建 `applicationDocumentsDirectory`
- - '####'
  - 在 iOS 中创建 `managedObjectModel`
- - '####'
  - 在 iOS 中创建 `persistentStoreCoordinator`
- - '####'
  - 在 iOS 中创建 `managedObjectContext`
- - '###'
  - 在 OS X 的 `AppDelegate` 中设置 Core Data 栈
- - '####'
  - 在 OS X 中创建 `applicationDocumentsDirectory`
- - '####'
  - 在 OS X 中创建 `managedObjectModel`
- - '####'
  - 在 OS X 中创建 `persistentStoreCoordinator`
- - '####'
  - 在 OS X 中创建 `managedObjectContext`
- - '##'
  - 在 iOS 中创建获取请求
- - '##'
  - 保存托管对象上下文
- - '###'
  - 在 iOS 中保存
- - '###'
  - 在 OS X 中保存
- - '##'
  - 使用 `NSManagedObject`
- - '###'
  - 创建新的 `NSManagedObject` 实例
- - '##'
  - 使用 `NSManagedObject` 的子类
- - '###'
  - 选择你的数据模型
- - '###'
  - 选择要生成子类的实体
- - '###'
  - 保存子类文件
- - '###'
  - 关于标量属性的选项
- - '###'
  - 桥接头文件
- - '###'
  - 生成的 Swift 文件
- - '##'
  - 本章小结
- - '#'
  - 第10章：在 Objective-C 中使用 SQLite/Core Data
- - '##'
  - 理解核心数据栈
- - '##'
  - 从核心数据栈获取数据
- - '##'
  - Objective-C 语言亮点
- - '###'
  - 使用引号字符串
- - '###'
  - Objective-C 是一门消息传递语言
- - '###'
  - 在 Objective-C 中使用方括号
- - '###'
  - 链式消息
- - '###'
  - 用分号结束语句
- - '###'
  - 在 Objective-C 中分离头文件与实现
- - '###'
  - 理解方法声明
- - '###'
  - 在 Objective-C 中处理 `nil`
- - '##'
  - 使用 Objective-C 构建核心数据应用结构
- - '###'
  - 在 iOS 中传递托管对象上下文给视图控制器
- - '###'
  - 在 iOS 的 `AppDelegate` 中设置核心数据栈
- - '####'
  - 创建应用委托头文件
- - '####'
  - 在 `AppDelegate.m` 中合成属性
- - '####'
  - 在 iOS 中创建 `applicationDocumentsDirectory`
- - '####'
  - 在 iOS 和 OS X 中创建 `managedObjectModel`
- - '####'
  - 在 iOS 中创建 `persistentStoreCoordinator`
- - '####'
  - 在 iOS 中创建 `managedObjectContext`
- - '###'
  - 在 OS X 的 `AppDelegate` 中设置核心数据栈
- - '####'
  - 在 OS X 中创建 `applicationDocumentsDirectory`
- - '####'
  - 在 OS X 中创建 `managedObjectModel`
- - '####'
  - 在 OS X 中创建 `persistentStoreCoordinator`
- - '####'
  - 在 OS X 中创建 `managedObjectContext`
- - '##'
  - 在 iOS 中创建获取请求
- - '##'
  - 保存托管对象上下文
- - '###'
  - 在 iOS 中保存
- - '###'
  - 在 OS X 中保存
- - '##'
  - 使用 NSManagedObject
- - '###'
  - 创建新的 NSManagedObject 实例
- - '##'
  - 使用 NSManagedObject 的子类
- - '##'
  - 本章小结
- - '#'
  - 第11章：使用简单数据库与 PHP 网站
- - '##'
  - 回顾数据库
- - '###'
  - 关于命名约定的说明
- - '####'
  - User 表
- - '####'
  - Score 表
- - '##'
  - 预览网站
- - '##'
  - 实现 PHP 网站
- - '###'
  - 了解基础的 PHP/SQLite 结构
- - '###'
  - 构建下拉选择列表 (`phpsql1.php`)
- - '###'
  - 显示选中的数据 (`phpsql2.php`)
- - '###'
  - 添加新数据 (`phpsql3.php`)
- - '###'
  - 在 PHP 和 PDO 中使用 try/catch 块
- - '##'
  - 本章小结
- - '#'
  - 第12章：在 Core Data/iOS 应用中使用简单数据库
- - '##'
  - 故事仍在继续…
- - '##'
  - 为 Core Data 调整数据模型和模板
- - '###'
  - 摆脱键并修订数据模型
- - '###'
  - 将 `timeStamp` 更改为 `name`
- - '###'
  - 在你的设备或模拟器上创建新数据库
- - '###'
  - 向应用添加 Score 表和界面
- - '####'
  - 确保你可以在 Master View Controller 中用 `+` 添加新用户
- - '####'
  - 使用详细视图
- - '####'
  - 为 Score 使用详细视图
- - '##'
  - 使用 NSManagedObject 子类
- - '###'
  - 为 DetailViewController 使用表视图控制器
- - '###'
  - 修改 DetailViewController 的代码
- - '####'
  - 使用子类
- - '####'
  - 将 `detail` 更改为 `detailUser`
- - '####'
  - 修改 `configureCell` 以使用子类
- - '###'
  - 修改 MasterViewController 以将用户传递给 DetailViewController
- - '##'
  - 本章小结
- - '##'
  - 索引
- - '###'
  - A, B
- - '####'
  - AppDelegate
- - '#####'
  - iOS
- - '#####'
  - NSManagedObject 子类
- - '#####'
  - OS X
- - '###'
  - C, D, E
- - '####'
  - Core Data
- - '###'
  - F, G, H
- - '###'
  - I, J, K, L, M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P, Q, R
- - '###'
  - S, T, U, V, W
- - '###'
  - X, Y, Z
