name: Expert PL SQL Practices
name_cn: PL SQL 高级实践指南
slug: expert-pl-sql-practices
toc:
- - '#'
  - Oracle 开发人员与 DBA 的专家级 PL/SQL 实践
- - '##'
  - 版权信息
- - '##'
  - 出版团队
- - '##'
  - 目录
- - '##'
  - 第 1 章：禁止使用的模式
- - '###'
  - 逐行处理
- - '###'
  - 嵌套逐行处理
- - '###'
  - 查询查找
- - '###'
  - 过度访问 `DUAL`
- - '###'
  - 日期的算术运算
- - '###'
  - 访问序列
- - '###'
  - 填充主从行
- - '###'
  - 过度调用函数
- - '###'
  - 不必要的函数执行
- - '###'
  - 代价高昂的函数调用
- - '###'
  - 数据库链接调用
- - '###'
  - 过度使用触发器
- - '###'
  - 过度提交
- - '###'
  - 过度解析
- - '###'
  - 总结
- - '##'
  - 第 2 章：动态 SQL：处理未知
- - '###'
  - 英雄登场
- - '###'
  - 原生动态 SQL
- - '###'
  - 动态游标
- - '###'
  - '`DBMS_SQL`'
- - '###'
  - 动态思维的示例
- - '###'
  - 安全问题
- - '###'
  - 性能与资源利用
- - '###'
  - 反模式
- - '###'
  - 动态 SQL 实现的比较
- - '###'
  - 对象依赖
- - '###'
  - 负面影响
- - '###'
  - 积极影响
- - '###'
  - 总结
- - '##'
  - 第 3 章：PL/SQL 与并行处理
- - '###'
  - 为何需要并行处理？
- - '###'
  - 影响并行处理的定律
- - '###'
  - 大数据的兴起
- - '###'
  - 并行处理 vs. 分布式处理
- - '###'
  - 并行硬件架构
- - '###'
  - 明确你的目标
- - '###'
  - 加速比
- - '###'
  - 向上扩展
- - '###'
  - 并行度
- - '###'
  - 适合并行处理的工作负载
- - '###'
  - 并行性与 OLTP
- - '###'
  - 并行性与非 OLTP 工作负载
- - '###'
  - MapReduce 编程模型
- - '###'
  - 在转向 PL/SQL 之前
- - '###'
  - 可用于并行活动的进程
- - '###'
  - 为 MapReduce 使用并行执行服务器
- - '###'
  - 流水线表函数
- - '###'
  - 指导原则
- - '###'
  - 并行流水线表函数总结
- - '###'
  - 总结
- - '##'
  - 第 4 章：警告与条件编译
- - '###'
  - PL/SQL 警告
- - '###'
  - 基础知识
- - '###'
  - 使用警告
- - '###'
  - 将警告提升为错误
- - '###'
  - 忽略警告
- - '###'
  - 条件编译
- - '###'
  - 总结
- - '##'
  - 第 6 章：单元测试
- - '###'
  - 为什么要测试你的代码？
- - '###'
  - 什么是单元测试？
- - '###'
  - 构建单元测试的工具
- - '###'
  - 准备和维护单元测试环境
- - '###'
  - 构建单元测试
- - '###'
  - 扩展测试范围
- - '###'
  - 支持的单元测试功能
- - '###'
  - 运行报告
- - '###'
  - 创建组件库
- - '###'
  - 总结
- - '##'
  - 第 7 章：了解你的代码
- - '###'
  - 本章将涵盖的内容
- - '###'
  - 总体目标
- - '###'
  - 自动化代码分析
- - '###'
  - 执行静态分析
- - '###'
  - 执行动态分析
- - '###'
  - 代码覆盖测试与性能指标
- - '###'
  - 总结
- - '##'
  - 第 8 章：面向契约编程
- - '###'
  - 契约式设计
- - '###'
  - 实施 PL/SQL 契约
- - '###'
  - 本地还是全局断言？
- - '###'
  - 使用 ASSERT 实现契约
- - '###'
  - 一项额外的改进
- - '###'
  - 面向契约的函数原型
- - '###'
  - 有用的契约模式
- - '###'
  - 无缺陷代码的原则
- - '###'
  - 总结
- - '##'
  - 第 9 章：从 SQL 调用 PL/SQL
- - '###'
  - 在 SQL 中使用 PL/SQL 函数的成本
- - '###'
  - 执行
- - '###'
  - 查询重写与 CBO
- - '###'
  - 优化器的难题
- - '###'
  - 谓词顺序
- - '###'
  - 其他问题
- - '###'
  - 降低 PL/SQL 函数的成本
- - '###'
  - 性能对比与列消除
- - '###'
  - 通过缓存减少函数调用
- - '###'
  - 协助基于成本的优化器
- - '###'
  - 可扩展优化器
- - '###'
  - 调优 PL/SQL
- - '###'
  - 总结
- - '##'
  - 第 10 章：游标
- - '###'
  - 选择正确的游标
- - '###'
  - 显式游标
- - '###'
  - 隐式游标
- - '###'
  - 静态 REF 游标
- - '###'
  - 动态 REF 游标
- - '###'
  - 总结
- - '##'
  - 第 11 章：大型 PL/SQL 编程
- - '###'
  - 作为基于 PL/SQL 的应用服务器的数据库
- - '###'
  - 大规模编程的要求
- - '###'
  - 通过约定实现统一性
- - '###'
  - 代码与数据的模块化
- - '###'
  - PL/SQL 中的面向对象编程
- - '###'
  - 内存管理
- - '###'
  - 总结
- - '##'
  - 第 12 章：演进式数据建模
- - '###'
  - 从二十年的系统开发中学到的教训
- - '###'
  - 数据库与敏捷开发
- - '###'
  - 演化式数据建模
- - '###'
  - 重构数据库
- - '###'
  - 通过 PL/SQL 创建访问层
- - '###'
  - 测试确认与功能更新
- - '###'
  - 敏捷宣言
- - '###'
  - 在进化数据建模中使用 PL/SQL
- - '###'
  - 总结
- - '##'
  - 第 13 章：性能剖析
- - '###'
  - 什么是性能？
- - '###'
  - 什么是性能剖析？
- - '###'
  - 插桩
- - '###'
  - 问题诊断
- - '###'
  - 方法 R
- - '###'
  - 性能分析示例
- - '###'
  - 总结
- - '##'
  - 第 14 章：编码规范与错误处理
- - '###'
  - 为何需要编码规范？
- - '###'
  - 格式化
- - '###'
  - 错误处理
- - '###'
  - 总结
- - '##'
  - 第 15 章：依赖关系与失效
- - '###'
  - 依赖链
- - '###'
  - 缩短依赖链
- - '###'
  - 资源锁定
- - '###'
  - 在触发器中强制依赖关系
- - '###'
  - 创建触发器时初始禁用
- - '###'
  - 总结
- - '##'
  - 附录 A：索引
- - '##'
  - 附录 B：关于作者
- - '##'
  - 附录 C：技术审稿人介绍
- - '##'
  - 附录 D：引言
