name: Pro SQL Server on Linux
name_cn: Linux 上的 SQL Server 高级指南
slug: pro-sql-server-on-linux
toc:
- - '#'
  - 精通 Linux 上的 SQL Server
- - '##'
  - 目录
- - '###'
  - 第 1 章：为什么选择在 Linux 上运行 SQL Server？
- - '####'
  - 平台选择
- - '####'
  - 我们是如何构建的
- - '#####'
  - Drawbridge
- - '#####'
  - SQLOS、SQLPAL 和 Helsinki
- - '#####'
  - Linux 上的 SQL Server 架构
- - '####'
  - Windows 版 SQL Server 与 Linux 版。它们是相同的吗？
- - '#####'
  - Linux 版 SQL Server 的功能
- - '#####'
  - 哪些特性不可用
- - '#####'
  - 我应该使用 Windows 还是 Linux？
- - '####'
  - 容器是新的虚拟机
- - '#####'
  - 数据库容器
- - '#####'
  - 平台独立性、可移植性与一致性
- - '#####'
  - 持续集成/持续部署
- - '#####'
  - Kubernetes
- - '####'
  - 本章小结
- - '###'
  - 第 2 章：安装与配置
- - '####'
  - 安装准备
- - '#####'
  - Linux 发行版
- - '#####'
  - 系统要求
- - '#####'
  - SQL Server 测试
- - '######'
  - WideWorldImporters 示例
- - '######'
  - 对 SQL Server 进行压力测试
- - '#####'
  - Linux 技巧
- - '######'
  - 常用命令
- - '######'
  - '`sudo`'
- - '######'
  - 查看和编辑文件及脚本
- - '######'
  - 系统日志记录
- - '####'
  - 开始安装！
- - '#####'
  - 60 秒内部署
- - '#####'
  - 下载仓库配置文件
- - '#####'
  - 安装 SQL Server 引擎
- - '#####'
  - 完成 SQL Server 的设置
- - '####'
  - 完整的安装体验
- - '#####'
  - 安装其他版本
- - '#####'
  - 验证安装
- - '######'
  - 检查 `mssql-server` 服务是否正在运行
- - '######'
  - 本地连接并运行查询
- - '######'
  - 远程连接
- - '######'
  - 验证 SQL Server 功能的更多方法
- - '#####'
  - 静默安装
- - '#####'
  - 离线安装
- - '#####'
  - 安装其他软件包
- - '#####'
  - 在 Azure 中安装
- - '#####'
  - 安装故障排除
- - '######'
  - 网络连接差或无连接
- - '######'
  - 安装未通过 `mssql-conf` 完成
- - '######'
  - '`Yum` 锁'
- - '######'
  - 更改 SQL Server 目录的权限或所有权
- - '######'
  - 安装调试
- - '####'
  - 探索 Linux 上的 SQL Server
- - '#####'
  - 已安装内容
- - '######'
  - '`/opt/mssql`'
- - '######'
  - '`/var/opt/mssql`'
- - '#####'
  - 其他文件
- - '#####'
  - 使用日志文件
- - '####'
  - 安装后配置
- - '#####'
  - 使用 `mssql-conf`
- - '#####'
  - SQL Server 实例配置
- - '######'
  - '`sp_configure`'
- - '######'
  - '`ALTER SERVER CONFIGURATION`'
- - '#####'
  - Linux 上的 Windows 配置选项
- - '######'
  - 锁定内存页
- - '######'
  - 即时文件初始化
- - '######'
  - 大页面
- - '######'
  - Windows Server 故障转移群集
- - '####'
  - 更新与卸载
- - '#####'
  - 更新 SQL Server
- - '#####'
  - 回滚到之前的更新
- - '#####'
  - 移除 SQL Server
- - '####'
  - 本章小结
- - '###'
  - 第 3 章：构建数据库与 T-SQL 基础
- - '####'
  - 设置环境
- - '####'
  - 创建数据库
- - '#####'
  - 系统数据库
- - '#####'
  - 创建登录名和用户
- - '#####'
  - 创建用户数据库
- - '####'
  - 创建表
- - '#####'
  - 创建架构
- - '#####'
  - 创建序列
- - '#####'
  - 最终创建表
- - '####'
  - 创建完整的数据库
- - '####'
  - 构建并运行查询
- - '#####'
  - 插入与读取数据
- - '#####'
  - 更新与删除数据
- - '#####'
  - 创建视图与存储过程
- - '####'
  - 本章小结
- - '###'
  - 第 4 章：构建应用程序与高级 T-SQL
- - '####'
  - 设置环境
- - '####'
  - 为 SQL Server 构建并运行数据应用程序
- - '#####'
  - 将 `node.js` 与 SQL Server 配合使用
- - '#####'
  - 使用 `node.js` 连接到 SQL Server
- - '#####'
  - 插入与读取数据
- - '#####'
  - 执行存储过程
- - '#####'
  - 增强你的应用程序
- - '####'
  - 深入 T-SQL
- - '#####'
  - 创建和使用临时对象
- - '######'
  - 临时表与表变量
- - '######'
  - 其他临时对象
- - '######'
  - '`tempdb` 的内部使用'
- - '#####'
  - 触发器
- - '#####'
  - 分析查询
- - '#####'
  - 复杂数据类型
- - '#####'
  - 字符串函数
- - '#####'
  - 其他 T-SQL 命令
- - '####'
  - 探索新的 SQL Server 功能
- - '#####'
  - JSON
- - '#####'
  - 时态表
- - '#####'
  - 图数据库
- - '#####'
  - 原生评分
- - '####'
  - 本章小结
- - '###'
  - 第 5 章：SQL Server 工具
- - '####'
  - 命令行工具
- - '#####'
  - '`sqlcmd`'
- - '#####'
  - '`bcp`'
- - '#####'
  - '`mssql-cli`'
- - '#####'
  - '`mssql-scripter`'
- - '#####'
  - '`sqlservr` 命令行选项'
- - '####'
  - SQL Operations Studio
- - '#####'
  - 安装
- - '#####'
  - 配置
- - '#####'
  - 对象资源管理器
- - '#####'
  - 仪表板、见解和扩展
- - '#####'
  - T-SQL 查询编辑器
- - '#####'
  - 其他功能
- - '####'
  - SQL Server Management Studio
- - '#####'
  - 对象资源管理器
- - '#####'
  - T-SQL 查询编辑器
- - '#####'
  - 报告
- - '####'
  - 引擎内置工具
- - '#####'
  - 系统表和目录视图
- - '#####'
  - 系统存储过程
- - '#####'
  - 动态管理视图
- - '######'
  - 视图
- - '######'
  - DBFS 工具
- - '#####'
  - 扩展事件
- - '######'
  - 扩展事件对象
- - '######'
  - 用法和场景
- - '######'
  - 工具
- - '#####'
  - T-SQL 性能特性
- - '######'
  - SHOWPLAN
- - '######'
  - SET STATISTICS
- - '######'
  - 轻量级查询分析
- - '#####'
  - 查询存储
- - '#####'
  - DBCC 命令
- - '#####'
  - 跟踪标志
- - '####'
  - 用于 ETL 的 SSIS
- - '#####'
  - 创建包
- - '######'
  - SQL Server Data Tools
- - '######'
  - 构建包
- - '#####'
  - 执行包
- - '#####'
  - 进一步使用 SSIS
- - '####'
  - 总结
- - '###'
  - 第 6 章：性能能力
- - '####'
  - 内置性能
- - '#####'
  - SQL Server 内置可扩展性
- - '#####'
  - 动态内存和缓存管理
- - '#####'
  - 高效的 I/O 处理
- - '######'
  - 预读
- - '######'
  - 预写日志
- - '######'
  - 检查点、延迟写入和急切写入
- - '######'
  - 数据压缩
- - '#####'
  - 并行处理
- - '####'
  - 最大性能配置
- - '#####'
  - SQL Server 实例配置
- - '#####'
  - 数据库选项
- - '#####'
  - Linux 内核配置
- - '####'
  - 调优以获成功
- - '#####'
  - 文件和文件组
- - '######'
  - 分离数据和事务日志文件
- - '######'
  - 使用多个数据库文件和文件组
- - '#####'
  - 索引
- - '######'
  - 聚集索引
- - '######'
  - 非聚集索引
- - '######'
  - 查看 WideWorldImporters
- - '######'
  - 使用工具
- - '######'
  - 索引类型和其他注意事项
- - '#####'
  - 统计信息
- - '######'
  - 索引和列上的统计信息
- - '######'
  - 自动化与统计信息
- - '######'
  - 基数估算
- - '#####'
  - 开发者技巧
- - '######'
  - 利用 T-SQL 的威力
- - '######'
  - 连接、事务和死锁
- - '######'
  - 处理你的结果！
- - '######'
  - 设置你的应用程序名称
- - '####'
  - 加速性能
- - '#####'
  - 分区表和索引
- - '#####'
  - 列存储索引
- - '######'
  - 工作原理
- - '######'
  - 何时以及应选择哪种？
- - '######'
  - 实战中的列存储
- - '######'
  - 技巧
- - '######'
  - 客户故事和资源
- - '#####'
  - 内存 OLTP
- - '######'
  - 基础知识
- - '######'
  - Hekaton 引擎
- - '######'
  - 内存优化文件组
- - '######'
  - 内存优化表
- - '######'
  - 索引
- - '######'
  - 本机编译存储过程
- - '######'
  - 使用场景
- - '####'
  - 智能 SQL Server 引擎
- - '#####'
  - 自适应查询处理
- - '#####'
  - 自动调优
- - '####'
  - 总结
- - '###'
  - 第 7 章：SQL Server 安全性
- - '####'
  - 登录名和用户
- - '####'
  - Active Directory 身份验证
- - '#####'
  - 工作原理
- - '#####'
  - 设置
- - '#####'
  - 使用 AD 身份验证
- - '####'
  - 权限和访问
- - '#####'
  - 授予和撤销访问权限
- - '#####'
  - 角色和权限
- - '######'
  - 服务器角色
- - '######'
  - 数据库角色
- - '######'
  - 应用程序角色
- - '######'
  - 其他权限
- - '#####'
  - 行级安全
- - '#####'
  - 动态数据屏蔽
- - '####'
  - SQL Server 与加密
- - '#####'
  - SQL Server 密钥和证书
- - '#####'
  - 透明数据加密
- - '#####'
  - 加密数据库备份
- - '#####'
  - 加密连接
- - '#####'
  - 始终加密
- - '#####'
  - 加密总结
- - '####'
  - 数据分类和审核
- - '#####'
  - 数据分类
- - '#####'
  - 漏洞评估
- - '#####'
  - SQL Server 审核
- - '####'
  - 总结
- - '###'
  - 第 8 章：SQL Server 的高可用性与灾难恢复
- - '####'
  - 备份和还原
- - '#####'
  - 数据库备份
- - '######'
  - 完整数据库备份
- - '######'
  - 恢复模型
- - '####'
  - 事务日志备份
- - '####'
  - Always On 故障转移群集实例
- - '####'
  - Always On 可用性组
- - '####'
  - 小结
- - '###'
  - 第 9 章：管理与监控 SQL Server
- - '####'
  - 管理 SQL Server 实例
- - '####'
  - 管理数据库
- - '####'
  - 管理对象
- - '####'
  - 监控 SQL Server
- - '####'
  - SQL Server 故障排除
- - '####'
  - 小结
- - '###'
  - 第 10 章：迁移到 Linux 上的 SQL Server
- - '####'
  - 从 SQL Server 迁移
- - '####'
  - 从 Oracle 迁移
- - '####'
  - 从 PostgreSQL 迁移
- - '####'
  - 迁移后注意事项
- - '####'
  - 总结
- - '###'
  - 第 11 章：SQL Server 与容器
- - '####'
  - 容器简介
- - '####'
  - 如何在容器中使用 SQL Server
- - '#####'
  - 部署并运行 SQL Server 镜像
- - '######'
  - Docker 容器 SQL Server 基础
- - '######'
  - 使用容器更新 SQL Server
- - '#####'
  - 使用 Dockerfile 构建你自己的容器
- - '#####'
  - 组合多容器应用
- - '####'
  - SQL Mac 挑战
- - '####'
  - SQL Server 与 Kubernetes
- - '#####'
  - 基础知识
- - '#####'
  - SQL Server HADR 与 Kubernetes
- - '######'
  - HADR 如何与 k8s 协同工作
- - '######'
  - 在 Azure Kubernetes 服务中使用 SQL Server
- - '####'
  - 总结
- - '###'
  - 第 12 章：结语
- - '###'
  - 索引
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '###'
  - 致谢
- - '###'
  - 前言
- - '###'
  - 引言
