name: Practical Oracle database appliance
name_cn: Oracle 数据库设备实用指南
slug: practical-oracle-database-appliance
toc:
- - '#'
  - Oracle 数据库一体机（ODA）是如何诞生的？
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '#'
  - 引言
- - '##'
  - 什么是 Oracle Database Appliance？
- - '##'
  - 本书的由来
- - '##'
  - 为何购买本书
- - '#'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 第 1 章 Oracle 数据库设备
- - '##'
  - 快速目录
- - '##'
  - 1.1 Oracle 数据库一体机
- - '###'
  - 为何需要一体机？
- - '###'
  - 一体机硬件
- - '###'
  - Oracle Database Appliance V1
- - '####'
  - 硬件规格
- - '####'
  - 存储配置
- - '####'
  - 操作系统与软件
- - '####'
  - 连接与设置
- - '###'
  - Oracle Database Appliance X3-2
- - '###'
  - ODA 服务器节点后部的标注说明
- - '##'
  - 本章小结
- - '#'
  - 第 2 章 集成式远程管理
- - '##'
  - 2.1 ILOM 简介
- - '##'
  - 2.2 ILOM 功能
- - '###'
  - 远程 KVMS 服务
- - '###'
  - Integrated Lights Out Manager (ILOM) 管理
- - '###'
  - 集成 Shell
- - '###'
  - ipmitool sunoem cli
- - '##'
  - 2.3 安全管理
- - '###'
  - 本地账户管理
- - '###'
  - Oracle 数据库设备与 ILOM
- - '###'
  - 告警与系统日志设置
- - '###'
  - 通过串行连接设置 Oracle 数据库设备
- - '###'
  - start /SYS
- - '###'
  - 裸机 Oracle 数据库设备
- - '##'
  - 摘要
- - '#'
  - 第 3 章 安装
- - '##'
  - 3.1 网络和电源连接
- - '###'
  - 原始 ODA
- - '###'
  - ODA X3-2
- - '###'
  - 电源线
- - '##'
  - 3.2 Oracle 数据库一体机初始部署
- - '###'
  - ILOM 网络
- - '###'
  - 网络信息
- - '###'
  - 真应用集群（RAC）网络
- - '###'
  - 网络配置
- - '###'
  - 网络时间协议配置
- - '###'
  - Grid Infrastructure 和数据库安装
- - '##'
  - 3.3 数据库安装
- - '###'
  - VNC 配置与连接
- - '###'
  - Oracle 设备管理器与部署
- - '###'
  - 网络信息屏幕
- - '###'
  - 数据库信息屏幕
- - '###'
  - 摘要屏幕
- - '###'
  - 部署过程
- - '###'
  - 完成屏幕
- - '###'
  - Oracle 数据库设备重新部署
- - '###'
  - 清单 3-11. cleanupDeploy.pl 脚本
- - '###'
  - 清单 3-12. 执行 cleanupDeploy.pl 及相关输出（部分）
- - '###'
  - 准备将 ZFS 阵列用作外部存储
- - '##'
  - 总结
- - '#'
  - 第 4 章 数据库配置
- - '##'
  - 4.1 `oakcli`命令
- - '###'
  - 命令选项
- - '###'
  - 执行命令
- - '###'
  - 企业版
- - '##'
  - 4.2 数据库配置类型
- - '###'
  - 真应用集群
- - '###'
  - 真正应用集群（RAC）
- - '###'
  - 单实例 (EE 选项)
- - '##'
  - 4.3 数据库删除
- - '##'
  - 4.4 数据库配置助手
- - '###'
  - 创建数据库
- - '###'
  - 启用/禁用自动维护任务
- - '###'
  - 删除数据库
- - '##'
  - 4.5 自动存储管理 (ASM)
- - '###'
  - 自动存储管理配置助手
- - '###'
  - 自动存储管理命令行
- - '##'
  - 本章小结
- - '#'
  - 第 5 章 网络
- - '##'
  - 5.1 ODA 型号
- - '###'
  - Oracle Database Appliance V1 网络配置详解
- - '###'
  - 硬件概述
- - '###'
  - 网络配置
- - '###'
  - 参考与注意事项
- - '###'
  - Oracle Database Appliance X3-2
- - '##'
  - 5.2 ODA 网络部署流程
- - '###'
  - 规划将要部署的 ODA 网络
- - '###'
  - 定义网络安全考虑因素
- - '###'
  - 在 ODA 到达前可完成的工作
- - '###'
  - 规格说明与订购 ODA 网络电缆
- - '###'
  - 申请 IP 地址
- - '##'
  - 5.3 构建离线配置文件
- - '##'
  - 5.4 将 ODA 安装到机架中
- - '##'
  - 5.5 为 ODA 布线
- - '###'
  - /opt/oracle/oak/bin/oakcli validate -c storagetopology
- - '###'
  - 应用 ILOM IP 地址并配置 ODA 公共网络
- - '###'
  - /opt/oracle/oak/bin/oakcli validate -c storagetopology
- - '###'
  - /opt/oracle/oak/bin/oakcli configure firstnet
- - '##'
  - 5.6 配置剩余网络
- - '###'
  - ./oakcli copy -conf /path/file_name.param
- - '###'
  - ./oakcli deploy -conf /path/file_name.param
- - '###'
  - ./oakcli deploy
- - '##'
  - 5.7 部署后进行网络更改的选项
- - '##'
  - 5.8 虚拟化注意事项
- - '##'
  - 总结
- - '#'
  - 第 6 章 监控 Oracle 数据库设备
- - '##'
  - 6.1 配置 Database Control
- - '###'
  - 使用企业管理器配置助手（EMCA）
- - '###'
  - 使用参数文件
- - '###'
  - 控制数据库控制
- - '###'
  - 数据库控制的状态
- - '###'
  - 停止数据库控制
- - '##'
  - 6.2 取消配置数据库控制
- - '###'
  - 启动数据库控制
- - '###'
  - 清单 6-12. 启动数据库控制
- - '###'
  - 清单 6-13. 启动与状态检查示例
- - '##'
  - 6.3 重新配置数据库控制台
- - '###'
  - 清单 6-14. recreate 命令
- - '###'
  - 清单 6-15. emca 重新配置数据库控制的输出
- - '##'
  - 6.4 反配置数据库控制
- - '##'
  - 6.5 支持 Oracle Enterprise Manager
- - '#'
  - 第 7 章 诊断 Oracle 数据库设备
- - '##'
  - 摘要
- - '##'
  - 7.1 主动诊断
- - '###'
  - 验证
- - '###'
  - 系统组件检查
- - '###'
  - 通过验证发现问题
- - '###'
  - 执行 ODA X3-2 系统组件检查 (X3-2)
- - '###'
  - 验证 ODA X3-2 存储拓扑
- - '###'
  - 操作系统磁盘存储
- - '###'
  - 共享存储
- - '###'
  - 网络组件
- - '###'
  - 磁盘校准
- - '###'
  - 自动服务请求
- - '###'
  - ODA 配置审计工具
- - '###'
  - 跟踪文件分析器
- - '###'
  - ./tfactl print config
- - '###'
  - Oracle TFA 目录管理与诊断收集
- - '###'
  - 目录管理
- - '###'
  - tfactl add directory /opt/oracle/oak/log
- - '###'
  - 诊断收集
- - '###'
  - tfactl diagcollect –all
- - '###'
  - tfactl diagcollect -crs node1,node2 -since 9h
- - '###'
  - tfactl diagcollect -for "Jun/29/2013 21:00:10"
- - '###'
  - 事件触发器
- - '###'
  - 总结
- - '###'
  - 其他工具
- - '###'
  - 响应式检查
- - '###'
  - 诊断信息收集
- - '###'
  - 磁盘故障
- - '###'
  - /root/Extras/odasundiag.sh
- - '###'
  - ./oakcli locate disk e0_pd_00 on
- - '##'
  - 摘要
- - '#'
  - 第 8 章 修补 Oracle 数据库设备
- - '##'
  - 8.1 补丁管理简介
- - '###'
  - 传统系统的局限性
- - '###'
  - Oracle 数据库一体机的优势
- - '##'
  - 8.2 补丁流程
- - '###'
  - 一般补丁流程
- - '###'
  - 特定 ODA 步骤
- - '##'
  - 8.3 时间安排
- - '###'
  - 多久打一次补丁
- - '###'
  - 补丁需要多长时间
- - '##'
  - 8.4 ODA 补丁选项
- - '###'
  - 新设备
- - '###'
  - 默认更新选项
- - '###'
  - 分时执行步骤
- - '###'
  - 延迟更新 RDBMS
- - '###'
  - 在 2.6 版本上
- - '###'
  - 显示所有当前 Oracle 主目录
- - '###'
  - 创建一个新的 Oracle 主目录
- - '###'
  - 重新配置一个数据库，使其从新的 Oracle 主目录运行
- - '###'
  - 重启数据库
- - '###'
  - 使用 Data Guard 最小化停机时间
- - '##'
  - 8.5 虚拟 Oracle 数据库设备
- - '##'
  - 8.6 准备工作
- - '###'
  - 验证发布级别
- - '###'
  - 审阅补丁说明
- - '###'
  - 下载补丁包集
- - '##'
  - 8.7 解压补丁包集合
- - '##'
  - 8.8 浏览更新仓库
- - '##'
  - 8.9 验证目标版本
- - '##'
  - 8.10 补丁执行
- - '###'
  - 升级日志文件
- - '###'
  - 升级系统基础设施
- - '###'
  - 升级 Grid 基础设施
- - '###'
  - 数据库升级
- - '###'
  - 升级所有数据库
- - '###'
  - 逐个升级
- - '###'
  - Show all current Oracle Homes
- - '###'
  - Update dbhome_1 that executes CAT database
- - '###'
  - At this stage the CAT database is updated to the latest version. The DOG database
    is still on the previous version.
- - '###'
  - Update dbhome_2 that executes DOG database
- - '##'
  - 总结
- - '#'
  - 第 9 章 ODA 的商业价值
- - '##'
  - 9.1 业务挑战
- - '##'
  - 9.2 ODA 登场
- - '##'
  - 9.3 快速、简单的数据库基础设施部署
- - '##'
  - 9.4 轻松搞定 RAC
- - '###'
  - 轻松实现高可用性
- - '###'
  - 成本与价值主张
- - '###'
  - Oracle ODA 平台概述
- - '###'
  - Oracle 硬件
- - '###'
  - 安全与合规性
- - '###'
  - 虚拟化技术
- - '###'
  - ODA 技术解决方案
- - '#'
  - 第 10 章 虚拟化与 ODA
- - '##'
  - 摘要
- - '##'
  - 10.1 ODA 性能
- - '##'
  - 总结
- - '##'
  - 10.2 Oracle VM (`OVM`)
- - '###'
  - OVM 与数据库一体机
- - '###'
  - 安装虚拟化 ODA
- - '##'
  - 10.3 虚拟化准备
- - '##'
  - 10.4 虚拟化部署考虑因素
- - '###'
  - 虚拟化 ODA 的部署
- - '###'
  - 虚拟部署的配置
- - '###'
  - 网络接口映射
- - '###'
  - 重镜像后配置
- - '###'
  - 为 `Dom0` 配置网络
- - '###'
  - ODA_BASE 的部署
- - '###'
  - /opt/oracle/oak/bin/oakcli deploy oda_base
- - '###'
  - xm list
- - '###'
  - /opt/oracle/oak/bin/oakcli show oda_base
- - '###'
  - /opt/oracle/oak/bin/oakcli deploy -conf /tmp/offlineconfig.param
- - '###'
  - 用户虚拟机的部署
- - '###'
  - 虚拟镜像仓库
- - '###'
  - oakcli create repo repo1 -dg data -size 20
- - '###'
  - oakcli show repo
- - '###'
  - oakcli stop repo repo1 -node 1
- - '##'
  - 10.5 用户虚拟机的创建
- - '##'
  - 10.6 高级虚拟机配置与补丁
- - '##'
  - 10.7 CPU 池
- - '###'
  - /opt/oracle/oak/bin/oakcli configure oda_base
- - '##'
  - 10.8 虚拟局域网
- - '###'
  - oakcli modify vm ol6test -addnetwork oda90
- - '##'
  - 10.9 为虚拟化 ODA 打补丁
- - '##'
  - 总结
- - '#'
  - 第 11 章 电子商务套件与 ODA
- - '##'
  - 11.1 ODA 是否适用？
- - '##'
  - 11.2 ODA 上的 e-Business Suite 系统架构
- - '##'
  - 11.3 为 e-Business Suite 配置 ODA
- - '###'
  - 在 ODA 上部署电子商务套件
- - '###'
  - 为您的独特环境做规划
- - '##'
  - 11.4 存储规划的重要性
- - '##'
  - 11.5 应用层安装的限制
- - '###'
  - 配置数据库服务器上的本地文件系统
- - '###'
  - 磁盘分区与格式化
- - '###'
  - 为应用层创建虚拟机
- - '##'
  - 11.6 为应用层文件使用 ACFS
- - '##'
  - 11.7 为应用层配置虚拟 IP
- - '##'
  - 11.8 安装 e-Business Suite
- - '###'
  - 数据库层安装
- - '###'
  - 应用层安装
- - '##'
  - 11.9 完成配置
- - '###'
  - 创建新的 11.2 Oracle 主目录
- - '###'
  - 创建新的数据库主目录
- - '###'
  - 修复 Oracle 二进制文件权限
- - '###'
  - 安装示例光盘
- - '###'
  - 创建 NLS 目录
- - '###'
  - 安装数据库补丁
- - '###'
  - 配置新的 Oracle 主目录
- - '###'
  - 运行 adpreclone.pl 实用程序以捕获配置详细信息
- - '###'
  - 复制 appsutil 目录并重命名上下文文件
- - '###'
  - 使用 adclonectx.pl 创建新的上下文文件
- - '###'
  - 在“实例化阶段”运行 AutoConfig 以准备配置文件
- - '###'
  - 创建并调整数据库初始化文件
- - '###'
  - 启动数据库并运行 AutoConfig 以完成配置
- - '###'
  - 完成补丁的安装后任务
- - '##'
  - 11.10 迁移至 ASM 和 RAC
- - '###'
  - 迁移至 ASM 和 RAC
- - '###'
  - 使用 RCONFIG 进行迁移
- - '###'
  - 转换与 ASM 迁移步骤
- - '###'
  - 迁移后针对 E-Business Suite 的 RAC 配置
- - '###'
  - 步骤 1：在应用服务器上创建新的 appsutil.zip
- - '###'
  - 步骤 2：在数据库节点上准备环境
- - '###'
  - 步骤 3：创建网络服务配置文件
- - '###'
  - 步骤 4：解压 appsutil.zip 并复制 JRE
- - '###'
  - 步骤 5：创建新的数据库监听器
- - '###'
  - 步骤 6：调整 local_listener 参数
- - '###'
  - 步骤 7：清理数据库配置
- - '###'
  - 步骤 8：生成新的数据库上下文文件
- - '###'
  - 数据库配置：修改参数与测试
- - '###'
  - 在第 1 个节点上
- - '###'
  - 在第 2 个节点上
- - '###'
  - 克隆应用层虚拟机
- - '###'
  - 停止电子商务套件服务
- - '###'
  - 将虚拟机打包成 tar 归档文件
- - '###'
  - 将 tar 归档文件复制到第二个 Dom0
- - '###'
  - 将 tar 归档文件导入为模板
- - '###'
  - 通过克隆模板创建并启动新的虚拟机
- - '###'
  - 更改主机名和 IP 地址
- - '###'
  - 从另一个虚拟 IP 挂载 `/cloudfs`
- - '###'
  - 验证设置并测试 keepalived
- - '###'
  - 配置第二个应用层节点
- - '###'
  - 回滚临时配置
- - '###'
  - no rows retrieved#
- - '##'
  - 11.11 安装后任务
- - '###'
  - 附加配置
- - '###'
  - 备份与监控
- - '##'
  - 概要
- - '#'
  - 第 12 章 Oracle Enterprise Manager 与 ODA
- - '##'
  - 摘要
- - '##'
  - 12.1 架构概览
- - '###'
  - Cloud Control 控制台
- - '###'
  - Oracle Management Agents
- - '###'
  - Oracle Management Service
- - '###'
  - Oracle Management Repository
- - '###'
  - Plug-ins
- - '###'
  - Agent Installation
- - '##'
  - 12.2 Adding the Hosts
- - '##'
  - 12.3 运行 `root.sh` 脚本
- - '##'
  - 12.4 发现目标
- - '##'
  - 概述
- - '#'
  - 实用甲骨文数据库一体机
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E, F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J, K, L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V, W
- - '##'
  - X, Y, Z
