name: SQL SERVER 2019 ALWAYS ON
name_cn: SQL SERVER 2019 ALWAYS ON 实战
slug: sql-server-2019-always-on
toc:
- - '##'
  - 1. 高可用性与灾难恢复概念
- - '##'
  - 2. 理解高可用性和灾难恢复技术
- - '##'
  - AlwaysOn 故障转移群集
- - '###'
  - 主动/被动配置
- - '##'
  - 三节点及以上的配置
- - '##'
  - 仲裁
- - '##'
  - AlwaysOn 可用性组
- - '##'
  - 日志传送
- - '##'
  - 技术整合
- - '##'
  - 总结
- - '#'
  - 第 3 章 集群实施
- - '#'
  - 4. 实现 AlwaysOn 故障转移群集实例
- - '#'
  - 5. 在 Windows 上实现 AlwaysOn 可用性组
- - '##'
  - 创建数据库
- - '##'
  - 配置 SQL Server
- - '##'
  - 使用新建可用性组向导
- - '###'
  - 可用性组概述
- - '###'
  - 备份首选项选项卡
- - '###'
  - 扩展自动备份的考虑因素
- - '###'
  - 监听器选项卡
- - '###'
  - 选择初始数据同步页面
- - '###'
  - 验证与配置过程
- - '##'
  - 使用新建可用性组对话框
- - '###'
  - 设置副本属性
- - '##'
  - 使用 T-SQL
- - '##'
  - 使用 PowerShell 实现可用性组
- - '#'
  - 6. 在 Linux 上实现 AlwaysOn 可用性组
- - '##'
  - 准备实施 AlwaysOn 可用性组
- - '##'
  - 配置集群
- - '##'
  - 配置防火墙
- - '##'
  - 安装 Pacemaker 组件
- - '##'
  - 启用集群服务
- - '##'
  - 构建集群
- - '##'
  - 安装资源代理
- - '##'
  - 保存凭据并创建资源
- - '#'
  - 7. 非典型可用性组实现
- - '##'
  - 基础可用性组
- - '##'
  - 总结
- - '##'
  - Azure IaaS 上的可用性组
- - '##'
  - 无集群可用性组
- - '###'
  - 准备实例
- - '###'
  - 域独立可用性组
- - '##'
  - 分布式可用性组
- - '##'
  - 摘要
- - '#'
  - 8. 管理 AlwaysOn
- - '##'
  - 管理集群
- - '##'
  - 从集群中移除节点
- - '##'
  - 管理 AlwaysOn 可用性组
- - '##'
  - 小结
- - '#'
  - 9. 监控 AlwaysOn 可用性组
- - '##'
  - AlwaysOn 仪表板
- - '##'
  - AlwaysOn 运行状况跟踪
- - '##'
  - 使用扩展事件监控 AlwaysOn
- - '###'
  - 扩展事件概念
- - '###'
  - 始终启用事件列表
- - '###'
  - 创建事件会话以监控可用性组
- - '##'
  - 概述
- - '#'
  - 10. 故障排除 AlwaysOn
- - '##'
  - AlwaysOn 故障转移群集实例元数据
- - '##'
  - AlwaysOn 可用性组元数据
- - '##'
  - 总结
- - '##'
  - 提示
- - '#'
  - 索引与术语
- - '#'
  - AlwaysOn 可用性组核心概念
- - '#'
  - 故障转移集群
- - '#'
  - Linux 上的 AlwaysOn 可用性组
- - '#'
  - 灾难恢复与高可用性
