name: Database Design and Relational Theory
name_cn: 数据库设计与关系理论
slug: database-design-and-relational-theory
toc:
- - '#'
  - 第一部分：第一版前言
- - '##'
  - 前置知识
- - '##'
  - 逻辑设计与物理设计
- - '###'
  - 关于作者
- - '#'
  - 第二部分：背景介绍
- - '##'
  - 1. 前言
- - '###'
  - 文献中的一些引述
- - '###'
  - 关于术语的说明
- - '###'
  - 贯穿全书的示例
- - '###'
  - 键
- - '###'
  - 设计理论的地位
- - '###'
  - 对常识与设计的反思
- - '###'
  - 本书的目标
- - '###'
  - 结语
- - '###'
  - 练习题
- - '###'
  - 答案
- - '##'
  - 2. 先决条件
- - '###'
  - 概述
- - '###'
  - 关系与关系变量
- - '###'
  - 谓词与命题
- - '###'
  - 关于供应商与零件的更多内容
- - '###'
  - 练习
- - '###'
  - 答案
- - '###'
  - 关于关系变量的定义
- - '###'
  - 答案
- - '###'
  - 封闭世界假设与开放世界假设
- - '###'
  - 精确定义
- - '###'
  - 值的相等性
- - '###'
  - 元组上的运算
- - '###'
  - 空元组
- - '###'
  - 空键
- - '###'
  - 谓词与命题
- - '###'
  - 投影与连接的定义
- - '#'
  - 第三部分：函数依赖、Boyce/Codd 范式及相关事项
- - '##'
  - 3. 规范化：一些通则
- - '###'
  - 规范化服务于两个目的
- - '####'
  - 通过谓词来理解
- - '####'
  - 一种完整性约束视角
- - '####'
  - 规范化的两个目的
- - '###'
  - 更新异常
- - '###'
  - 范式层次结构
- - '###'
  - 规范化与约束
- - '###'
  - 相等依赖
- - '####'
  - 定义（相等依赖）
- - '####'
  - 定义（包含依赖）
- - '###'
  - 结语
- - '###'
  - 练习题
- - '###'
  - 答案
- - '##'
  - 4. 函数依赖与 BCNF（非正式讨论）
- - '###'
  - 第一范式
- - '###'
  - 违反第一范式
- - '###'
  - 函数依赖
- - '###'
  - 键的再探讨
- - '###'
  - 数据库范式基础与核心概念
- - '###'
  - 第二范式
- - '###'
  - 第三范式
- - '###'
  - 博伊斯-科德范式
- - '###'
  - 练习
- - '##'
  - 17. 以下是技术文献中对 1NF 的一些定义。鉴于本章正文中对这些问题的讨论，您对此有何评论？
- - '###'
  - 第一范式的定义
- - '###'
  - 答案
- - '##'
  - 5. 函数依赖与 BCNF 范式（形式化）
- - '###'
  - 预备定义
- - '###'
  - 函数依赖再探讨
- - '####'
  - 定义（函数依赖）
- - '####'
  - 定义（满足或违反函数依赖）
- - '####'
  - 定义（函数依赖成立）
- - '###'
  - 重新审视鲍伊斯-科德范式
- - '####'
  - 定义（平凡函数依赖）
- - '####'
  - 定理
- - '####'
  - 定义（超键）
- - '####'
  - 定义（不可约函数依赖）
- - '####'
  - 定义（键）
- - '####'
  - 定义（由键所蕴含的函数依赖）
- - '####'
  - 定理
- - '####'
  - 定义（鲍伊斯-科德范式）
- - '####'
  - 定义（鲍伊斯-科德范式）
- - '###'
  - 希斯定理
- - '###'
  - 希思定理与非损耗分解
- - '####'
  - 希思定理（针对关系变量）
- - '####'
  - 练习
- - '#####'
  - 练习 1
- - '#####'
  - 练习 2
- - '#####'
  - 练习 3
- - '#####'
  - 练习 4
- - '#####'
  - 练习 5
- - '#####'
  - 练习 6
- - '#####'
  - 练习 7
- - '#####'
  - 练习 8
- - '####'
  - 答案
- - '#####'
  - 答案 1
- - '#####'
  - 答案 2
- - '#####'
  - 答案 3
- - '#####'
  - 答案 4
- - '##'
  - 6. 保持函数依赖
- - '###'
  - Heath 定理的证明与讨论
- - '###'
  - 结论
- - '###'
  - 引理
- - '###'
  - Heath 定理的逆命题
- - '###'
  - 练习
- - '##'
  - 7. FD 公理化
- - '###'
  - 阿姆斯特朗公理
- - '###'
  - 基本概念与规则
- - '###'
  - 附加规则
- - '###'
  - 证明附加规则
- - '###'
  - 另一种闭包
- - '####'
  - 定义（属性集的闭包）
- - '###'
  - 练习
- - '###'
  - 答案
- - '##'
  - 8. 反规范化
- - '###'
  - “为性能而反规范化”（？）
- - '###'
  - 反规范化意味着什么？
- - '###'
  - 反规范化不是什么（第一部分）
- - '####'
  - 第一范式：
- - '####'
  - 示例：
- - '###'
  - 反规范化不是什么（II）
- - '###'
  - 反规范化被认为是有害的 (I)
- - '###'
  - 反规范化被认为是有害的 (II)
- - '###'
  - 本章总结
- - '####'
  - 结束语
- - '###'
  - 练习题
- - '###'
  - 解答
- - '#'
  - 第四部分：连接依赖、第五范式及相关事项
- - '##'
  - 9. 连接依赖与第五范式（非正式）
- - '###'
  - 连接依赖——基本概念
- - '###'
  - 处于 BCNF 但非 5NF 的关系变量
- - '###'
  - 循环规则
- - '###'
  - 结束语
- - '###'
  - 练习
- - '###'
  - 答案
- - '##'
  - 10. JD 与 5NF（形式化）
- - '###'
  - 连接依赖再探
- - '####'
  - 定义（连接依赖）
- - '####'
  - 定义（满足或违反 JD）
- - '####'
  - 定义（JD 成立）
- - '###'
  - 第五范式
- - '###'
  - 由键所蕴含的连接依赖
- - '###'
  - 一个有用的定理
- - '###'
  - FD 不是 JD
- - '###'
  - 更新异常再探讨
- - '###'
  - 练习
- - '###'
  - 答案
- - '##'
  - 11. 隐式依赖
- - '###'
  - 无关分量
- - '###'
  - 组合分量
- - '####'
  - 定理
- - '####'
  - 练习
- - '###'
  - 不可约 JD
- - '####'
  - 定理
- - '####'
  - 定义（不可约 JD）
- - '###'
  - 迄今总结
- - '###'
  - 追踪算法
- - '###'
  - 结束语
- - '####'
  - 练习
- - '####'
  - 答案
- - '##'
  - 12. 多值依赖与第四范式 (4NF)
- - '###'
  - 引入性示例
- - '###'
  - 多值依赖（非正式）
- - '###'
  - 多值依赖（形式化）
- - '###'
  - 第四范式
- - '###'
  - 多值依赖公理化
- - '###'
  - 嵌入依赖
- - '###'
  - 练习
- - '###'
  - 答案
- - '####'
  - '1.'
- - '####'
  - '2.'
- - '####'
  - '3.'
- - '####'
  - '4.'
- - '####'
  - '5.'
- - '####'
  - '6.'
- - '####'
  - '7.'
- - '####'
  - '8.'
- - '#'
  - 第五部分：进一步的范式
- - '##'
  - 13. ETNF, RFNF, SKNF
- - '###'
  - 5NF 过于严格
- - '####'
  - 第一个例子：5NF 的作用
- - '####'
  - 第二个例子：为什么 5NF 做得太多了
- - '###'
  - 基本元组范式
- - '####'
  - 定义与定理
- - '####'
  - 一个处于 ETNF 但不处于 5NF 的关系变量
- - '####'
  - 一个处于 4NF 但不处于 ETNF 的关系变量
- - '####'
  - 我们的选择
- - '###'
  - 无冗余范式
- - '####'
  - 一个属于 RFNF 但不属于 5NF 的关系变量
- - '####'
  - 一个属于 ETNF 但不属于 RFNF 的关系变量
- - '###'
  - 超键范式
- - '####'
  - 一个属于 SKNF 但不属于 5NF 的关系变量
- - '####'
  - 一个属于 RFNF 但不属于 SKNF 的关系变量
- - '###'
  - 结束语
- - '###'
  - 练习题
- - '###'
  - 答案
- - '###'
  - 脚注
- - '##'
  - 14. 6NF
- - '###'
  - 常规数据的第六范式
- - '###'
  - 时态数据的第六范式
- - '####'
  - 引言
- - '####'
  - 定义（U_join）
- - '####'
  - 定义（U_equality）
- - '####'
  - 定义（U_join 依赖）
- - '####'
  - 定义（第六范式）
- - '###'
  - 练习题
- - '###'
  - 答案
- - '##'
  - 15. 这还不是结束
- - '###'
  - 域键范式
- - '###'
  - 初等键范式
- - '###'
  - 过强的 PJ/NF
- - '###'
  - “限制-并”范式
- - '###'
  - 练习
- - '###'
  - 答案
- - '#'
  - 第六部分：正交性
- - '##'
  - 16. 正交设计原则
- - '###'
  - 为规范化欢呼两声
- - '###'
  - 一个激励性示例
- - '###'
  - 一个更简单的例子
- - '###'
  - 元组与命题
- - '####'
  - 源自这第二次尝试的要点：
- - '###'
  - 重访第一个示例
- - '###'
  - 再探第二个例子
- - '###'
  - 最终版本（？）
- - '###'
  - 澄清说明
- - '####'
  - 示例 1：ON_VACATION 与 NEEDS_PHONE
- - '####'
  - 示例 2：EARNS、SALARY_UNK 与 UNSALARIED
- - '###'
  - 结束语
- - '###'
  - 练习题
- - '###'
  - 答案
- - '#'
  - 第七部分：冗余
- - '##'
  - 17. 我们需要更多科学
- - '###'
  - 历史小记
- - '###'
  - 谓词与约束
- - '###'
  - 示例 1
- - '###'
  - 示例 2
- - '###'
  - 示例 3
- - '###'
  - 示例 4
- - '###'
  - 示例 5
- - '###'
  - 示例 6
- - '####'
  - 图 17-4
- - '###'
  - 示例 7
- - '####'
  - 图 17-5
- - '###'
  - 示例 8
- - '####'
  - 图 17-6
- - '###'
  - 示例 9
- - '###'
  - 示例 10
- - '###'
  - 示例 11
- - '###'
  - 示例 12
- - '###'
  - 管理冗余
- - '####'
  - 1. 仅采用原始设计
- - '####'
  - 2. 声明约束
- - '####'
  - 3. 使用视图
- - '####'
  - 4. 使用快照
- - '###'
  - 精炼定义
- - '####'
  - Relvar S 中的元组与冗余
- - '####'
  - 示例 1 和 2
- - '####'
  - 示例 3
- - '####'
  - 示例 4
- - '####'
  - 示例 5
- - '####'
  - 示例 6
- - '####'
  - 示例 7
- - '####'
  - 示例 8
- - '###'
  - 示例 9 和 10
- - '###'
  - 示例 11
- - '###'
  - 示例 12
- - '###'
  - 结束语
- - '###'
  - 练习
- - '###'
  - 答案
- - '#'
  - 第八部分：附录
- - '##'
  - 究竟什么是数据库设计？
- - '##'
  - 关于“表和视图”常见误解的讨论
- - '###'
  - 对“存储对象”观点的批评
- - '###'
  - 对“逻辑对象和关系”以及“链接”观点的批评
- - '###'
  - 对“物理设计包含数据类型”观点的批评
- - '##'
  - 逻辑设计与物理设计
- - '##'
  - 理论的作用
- - '##'
  - 谓词
- - '##'
  - 规则
- - '##'
  - 冗余
- - '##'
  - “最终一致性”
- - '##'
  - 关于一致性的更多论述
- - '###'
  - 数据库是一个逻辑系统
- - '###'
  - 证明 1 = 0
- - '###'
  - 错误答案
- - '###'
  - 推广论证
- - '###'
  - 为什么完整性检查必须是即时的
- - '##'
  - 主键虽好，但非必需
- - '###'
  - 为 PK:AK 区分辩护的论点
- - '####'
  - 主要论点
- - '####'
  - 后续反思
- - '####'
  - Codd 的观点
- - '###'
  - 具有两个或更多键的关系变量
- - '###'
  - 发票与发货单示例
- - '###'
  - 每个实体类型只有一个主键？
- - '###'
  - 申请人和雇员的例子
- - '###'
  - 结语
- - '##'
  - 历史注释
- - '##'
  - 索引
- - '###'
  - 关于
- - '###'
  - 符号
- - '###'
  - 数字
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Y
- - '###'
  - Z
