name: Pro Oracle Identity and Access Management Suite
name_cn: Oracle Identity and Access Management Suite 高级指南
slug: pro-oracle-identity-and-access-management-suite
toc:
- - '#'
  - Oracle 身份与访问管理套件
- - '##'
  - 目录
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 第 1 章：Oracle 身份与访问管理套件概述
- - '###'
  - WebLogic Server
- - '###'
  - Oracle 目录服务
- - '###'
  - Oracle 互联网目录
- - '###'
  - Oracle 统一目录
- - '###'
  - Oracle 虚拟目录
- - '###'
  - Oracle 身份与访问管理
- - '###'
  - Oracle 访问管理器
- - '###'
  - Oracle 自适应访问管理
- - '###'
  - 身份联合
- - '####'
  - 联合身份认证
- - '####'
  - 移动和社交访问
- - '####'
  - API 和 Web 服务安全
- - '####'
  - 云访问门户
- - '###'
  - Oracle 身份管理器
- - '####'
  - 自助服务
- - '####'
  - 工作流
- - '####'
  - 委派管理
- - '####'
  - 审计
- - '###'
  - 小结
- - '##'
  - 第 2 章：安装前注意事项与先决条件
- - '###'
  - 容量规划
- - '####'
  - Fusion Middleware
- - '#####'
  - 评估容量要求
- - '#####'
  - 硬件
- - '#####'
  - 内存
- - '#####'
  - 存储
- - '#####'
  - 网络
- - '#####'
  - 集群
- - '###'
  - 企业部署拓扑
- - '####'
  - 单节点
- - '####'
  - 本地高可用性
- - '####'
  - 灾难恢复与最大可用性
- - '####'
  - 拓扑实现
- - '###'
  - 先决条件
- - '####'
  - 操作系统
- - '####'
  - Fusion Middleware 硬件要求
- - '#####'
  - WebLogic Server
- - '#####'
  - Oracle 目录服务
- - '#####'
  - Oracle 身份与访问管理器
- - '####'
  - 集群考虑事项
- - '#####'
  - 主机配置
- - '####'
  - 网络规划
- - '###'
  - 小结
- - '##'
  - 第 3 章：用户与策略存储
- - '###'
  - 用户与策略存储概述
- - '####'
  - 组织和管理用于用户身份的目录
- - '####'
  - 对象类和属性定义
- - '####'
  - 应用程序权限和组管理
- - '####'
  - 多目录的挑战
- - '###'
  - Oracle 互联网目录
- - '####'
  - 安全与数据隐私
- - '#####'
  - Oracle 透明数据加密 (TDE)
- - '####'
  - 易用性与管理
- - '#####'
  - ODSM 界面
- - '#####'
  - Fusion Middleware Control 界面
- - '####'
  - 目录同步
- - '###'
  - Oracle 统一目录
- - '####'
  - 架构
- - '####'
  - 可扩展性
- - '####'
  - 复制
- - '####'
  - 易用性与可管理性
- - '###'
  - Oracle 虚拟目录
- - '####'
  - 架构
- - '###'
  - 聚合
- - '###'
  - 访问管理
- - '###'
  - 小结
- - '##'
  - 第 4 章：Oracle 目录服务安装与配置
- - '###'
  - 安装前任务
- - '####'
  - 操作系统用户
- - '####'
  - 操作系统配置
- - '####'
  - 操作系统软件包
- - '####'
  - 数据库准备
- - '###'
  - Fusion Middleware WebLogic Server
- - '###'
  - Oracle 互联网目录安装
- - '###'
  - Oracle 互联网目录配置
- - '####'
  - 配置类型
- - '#####'
  - 开始配置
- - '#####'
  - 欢迎屏幕
- - '#####'
  - 选择域类型
- - '#####'
  - 输入管理员信息
- - '#####'
  - 配置新域详情
- - '#####'
  - 选择组件
- - '#####'
  - 配置端口
- - '#####'
  - 配置 OVD（如果选择）
- - '#####'
  - 配置 Oracle 虚拟目录领域和管理员密码
- - '###'
  - 验证安装
- - '###'
  - 小结
- - '##'
  - 第 5 章：目录同步与虚拟化
- - '###'
  - 目录集成平台
- - '###'
  - 创建同步配置文件
- - '###'
  - 小结
- - '##'
  - 第 6 章：Oracle 访问管理器安装
- - '###'
  - 安装前任务
- - '####'
  - 操作系统用户
- - '####'
  - 操作系统配置
- - '####'
  - 操作系统软件包
- - '####'
  - 数据库准备
- - '###'
  - 访问管理器软件安装
- - '###'
  - 创建访问管理器域
- - '####'
  - 配置管理服务器、被管理服务器、集群和计算机
- - '###'
  - 小结
- - '##'
  - 第 7 章：身份管理器安装
- - '###'
  - 安装前任务
- - '####'
  - 操作系统用户
- - '####'
  - 操作系统配置
- - '####'
  - 操作系统软件包
- - '####'
  - 数据库准备
- - '###'
  - 身份管理器软件安装
- - '###'
  - 面向服务的架构安装
- - '###'
  - 身份管理器安装
- - '###'
  - 配置身份管理器域
- - '###'
  - 小结
- - '##'
  - 第 8 章：Oracle HTTP 服务器与 WebGate 安装配置
- - '###'
  - 安装前任务
- - '####'
  - 操作系统用户
- - '####'
  - 操作系统配置
- - '####'
  - 操作系统软件包
- - '###'
  - Oracle HTTP 服务器软件安装与配置
- - '###'
  - Oracle 访问管理器 WebGate 安装与配置
- - '###'
  - 配置与部署 Oracle WebGate
- - '###'
  - 小结
- - '##'
  - 第 9 章：配置 Oracle 访问管理器
- - '###'
  - 准备访问管理器以使用 Oracle 互联网目录
- - '###'
  - 为 Oracle 访问管理器预配置 OID
- - '###'
  - 配置 Oracle 访问管理器身份存储
- - '###'
  - 小结
- - '##'
  - 第 10 章：Oracle 身份管理配置
- - '###'
  - 预配置步骤
- - '###'
  - 配置数据库安全存储
- - '###'
  - 为 OIM 预配置 OID 身份存储
- - '###'
  - 配置 Oracle 身份管理器服务器
- - '###'
  - 完成 LDAP 安装后配置
- - '###'
  - 小结
- - '##'
  - 第 11 章：Oracle 身份与访问管理器集成
- - '###'
  - IdmConfigTool
- - '###'
  - 配置 Oracle 访问管理器
- - '###'
  - 配置 Oracle 身份管理器
- - '###'
  - 集成 OIM 与 OAM
- - '###'
  - 配置 Oracle HTTP 服务器 WebGate
- - '###'
  - 小结
- - '##'
  - 第 12 章：Oracle 身份管理与身份存储
- - '###'
  - 用例
- - '###'
  - 拓扑
- - '###'
  - 分割配置文件
- - '###'
  - 独立的用户与组群体
- - '###'
  - 身份存储与 Oracle 访问管理器
- - '###'
  - 小结
- - '##'
  - 第 13 章：身份管理器策略管理
- - '###'
  - 访问策略
- - '###'
  - 访问策略配置示例
- - '###'
  - 密码策略
- - '###'
  - 小结
- - '##'
  - 第 14 章：Oracle 身份管理器表单与定制
- - '###'
  - 基础定制
- - '###'
  - 用户界面定制
- - '###'
  - 小结
- - '##'
  - 第 15 章：集成访问管理器与电子商务套件
- - '###'
  - 架构
- - '###'
  - 准备 EBS AccessGate 文件
- - '###'
  - 创建 EBS AccessGate 安装目录
- - '###'
  - 准备 EBS 和 OID
- - '###'
  - 将 EBS Home 注册到 OAM
- - '###'
  - 将 EBS 注册到 OID
- - '###'
  - 创建 EBS 连接用户
- - '###'
  - 配置 EBS AccessGate
- - '###'
  - 为 AccessGate 创建受管服务器
- - '###'
  - 复制构件文件
- - '###'
  - 在 EBS 中生成 DBC 文件
- - '###'
  - 将 EBS AccessGate 主机添加到外部表列表
- - '###'
  - 使用 txkEBSAuth.xml 部署 AccessGate
- - '###'
  - 验证 AccessGate 应用程序部署
- - '###'
  - 在 Oracle 访问管理器中配置资源
- - '###'
  - 将 HTTP 服务器重定向到 WebLogic Server 以支持 EBS AccessGate
- - '###'
  - 配置集中注销
- - '###'
  - 配置注销清理文件
- - '###'
  - 配置额外注销回调
- - '###'
  - EBS 配置文件配置
- - '###'
  - 测试电子商务套件单点登录
- - '###'
  - 小结
- - '##'
  - 第 16 章：故障排除与常见问题
- - '###'
  - 安装问题
- - '###'
  - 常见配置问题
- - '####'
  - Oracle 互联网目录
- - '####'
  - Oracle 访问管理器
- - '####'
  - Oracle 身份管理器
- - '###'
  - 小结
- - '##'
  - 索引
- - '###'
  - A, B, C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F, G, H
- - '###'
  - I, J
- - '###'
  - K
- - '###'
  - L, M, N
- - '###'
  - O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U, V
- - '###'
  - W, X, Y, Z
