name: Beginning Oracle SQL for Oracle Database 18c
name_cn: Oracle Database 18c 的 Oracle SQL 入门指南
slug: beginning-oracle-sql-for-oracle-database-18c
toc:
- - '#'
  - Oracle Database 18c SQL 入门
- - '##'
  - 前言
- - '##'
  - 您将学到什么
- - '#'
  - 第一部分：设置环境
- - '##'
  - 1. 什么是数据库？
- - '###'
  - 数据库的替代方案
- - '###'
  - 表
- - '###'
  - 行
- - '###'
  - 列
- - '###'
  - 查询
- - '###'
  - SQL
- - '###'
  - 索引
- - '###'
  - 供应商
- - '###'
  - 总结
- - '##'
  - 2. 设置环境
- - '###'
  - 我们需要什么工具？
- - '###'
  - 版本
- - '###'
  - 下载 Oracle 快捷版
- - '####'
  - 注意
- - '###'
  - Windows、Linux 以及 Mac 呢？
- - '###'
  - 安装 Oracle Express
- - '####'
  - 注意
- - '###'
  - 下载 Oracle SQL Developer
- - '###'
  - 运行 Oracle SQL Developer
- - '###'
  - 下载 JDK
- - '###'
  - 创建连接
- - '###'
  - 创建新用户
- - '###'
  - 使用新用户创建连接
- - '###'
  - 创建表
- - '###'
  - 插入数据
- - '###'
  - LiveSQL
- - '###'
  - 总结
- - '#'
  - 第二部分：查看数据
- - '##'
  - 3. 检索数据
- - '###'
  - 如何查看数据？
- - '###'
  - 什么是 SELECT 语句？
- - '###'
  - 需注意的几点
- - '###'
  - 我们的第一个 SELECT 语句
- - '###'
  - 在 SQL Developer 中运行语句
- - '###'
  - 结果
- - '###'
  - 运行脚本
- - '###'
  - SQL 中的错误
- - '####'
  - 缺少关键字
- - '####'
  - 表不存在
- - '###'
  - 总结
- - '##'
  - 4. 选择特定列
- - '###'
  - 选择单列
- - '###'
  - 选择多列
- - '###'
  - 选择所有列
- - '###'
  - 选择特定列还是选择所有列？
- - '###'
  - 总结
- - '##'
  - 5. 限制结果
- - '###'
  - 为什么要限制数据？
- - '###'
  - 什么是 WHERE 子句？
- - '###'
  - 使用文本值的示例
- - '###'
  - 注意
- - '###'
  - 数值示例
- - '###'
  - 查找不等于某个值的行
- - '###'
  - 大于
- - '###'
  - 大于等于
- - '###'
  - 小于
- - '###'
  - 小于等于
- - '###'
  - 最佳实践
- - '####'
  - 将列名放在左侧
- - '####'
  - 只选择你需要的
- - '###'
  - 总结
- - '##'
  - 6. 比较数据
- - '###'
  - 什么是部分匹配？
- - '###'
  - LIKE 的语法
- - '###'
  - 百分号通配符
- - '###'
  - 下划线通配符
- - '###'
  - 搜索通配符字符
- - '###'
  - 性能
- - '###'
  - 总结
- - '##'
  - 7. 应用多个过滤器
- - '###'
  - 为什么使用多个过滤器？
- - '###'
  - AND 关键字
- - '####'
  - 查找匹配姓氏和薪资的记录
- - '####'
  - 使用 AND 关键词对两列进行大于和小于查询以查找记录
- - '###'
  - OR 关键词
- - '####'
  - 使用 OR 关键词按姓氏或工资查找记录
- - '####'
  - 使用 OR 关键词对两列进行大于或小于查询以查找记录
- - '###'
  - 超过两个条件
- - '####'
  - 多个 AND 条件
- - '####'
  - 多个 OR 条件
- - '####'
  - 组合多个 AND 和 OR 条件
- - '###'
  - 使用多个条件指定顺序
- - '###'
  - 总结
- - '##'
  - 8. 处理 Null 值
- - '###'
  - 缺失数据
- - '###'
  - 什么是 NULL？
- - '###'
  - 应该如何处理 NULL？
- - '###'
  - 处理 NULL 的示例
- - '###'
  - 添加更多数据
- - '###'
  - 选择记录
- - '###'
  - 限制 NULL 值
- - '###'
  - 隐藏空值
- - '###'
  - 在一个 SQL 窗口中运行多个查询
- - '###'
  - 总结
- - '##'
  - 9. 移除重复结果
- - '###'
  - 添加新记录
- - '###'
  - 选择数据
- - '###'
  - 什么是 DISTINCT？
- - '####'
  - 注意
- - '###'
  - 查找唯一的 Last Name 值
- - '###'
  - 查找唯一的薪资值
- - '###'
  - 查找唯一的值组合
- - '###'
  - 总结
- - '##'
  - 10. 对值列表和范围应用过滤器
- - '###'
  - 连词过多
- - '###'
  - IN 关键字
- - '####'
  - 使用 IN 的示例
- - '####'
  - 更长的值列表
- - '###'
  - 使用 `IN` 处理文本值
- - '###'
  - 将 `IN` 与其他子句结合使用
- - '###'
  - '`IN` 与 `AND`？'
- - '###'
  - '`IN` 与 `LIKE`？'
- - '###'
  - 过滤值的范围
- - '###'
  - '`BETWEEN` 运算符'
- - '####'
  - 使用 Between 处理两个薪资值
- - '####'
  - 当值不完全匹配时使用 BETWEEN
- - '####'
  - 对文本值使用 BETWEEN
- - '####'
  - 包含性与排他性检查示例
- - '####'
  - 是否应该使用 BETWEEN？
- - '###'
  - 总结
- - '##'
  - 11. 数据排序
- - '###'
  - 结果无序
- - '####'
  - 警告！
- - '###'
  - 使用 ORDER BY 对结果排序
- - '###'
  - ORDER BY 示例
- - '####'
  - 按文本值排序
- - '####'
  - 按数字值排序
- - '####'
  - 按不在 SELECT 子句中的列排序
- - '####'
  - 按数字排序
- - '####'
  - ORDER BY 与 NULL 值
- - '####'
  - 按多列排序
- - '###'
  - 你真的需要对数据进行排序吗？
- - '###'
  - 小结
- - '##'
  - 12. 应用表与列别名
- - '###'
  - 什么是表别名？
- - '###'
  - 表别名示例
- - '###'
  - 智能感知或自动完成
- - '###'
  - 更长的表别名
- - '###'
  - 如果我不使用表别名会怎样？
- - '###'
  - 什么是列别名？
- - '###'
  - 列别名示例
- - '###'
  - AS 关键字
- - '###'
  - 数学运算与列别名
- - '####'
  - 加法
- - '####'
  - 减法
- - '####'
  - 乘法
- - '####'
  - 除法
- - '###'
  - 列别名与表别名
- - '###'
  - 总结
- - '#'
  - 第三部分：添加、更新、删除数据
- - '##'
  - 13. 理解数据类型
- - '###'
  - 什么是数据类型？
- - '###'
  - 我们为什么需要不同的数据类型？
- - '###'
  - 有哪些不同的数据类型？
- - '####'
  - 文本数据类型
- - '#####'
  - CHAR
- - '#####'
  - VARCHAR2
- - '#####'
  - NCHAR
- - '#####'
  - NVARCHAR2
- - '#####'
  - LONG
- - '#####'
  - RAW
- - '#####'
  - LONG RAW
- - '####'
  - 数字数据类型
- - '#####'
  - NUMBER
- - '#####'
  - INTEGER
- - '#####'
  - FLOAT
- - '#####'
  - DECIMAL
- - '#####'
  - BINARY_FLOAT
- - '#####'
  - BINARY_DOUBLE
- - '####'
  - 日期数据类型
- - '#####'
  - DATE
- - '#####'
  - TIMESTAMP
- - '#####'
  - 带时区的时间戳 (TIMESTAMP WITH TIME ZONE)
- - '#####'
  - 带本地时区的时间戳 (TIMESTAMP WITH LOCAL TIME ZONE)
- - '#####'
  - 年月间隔 (INTERVAL YEAR TO MONTH)
- - '#####'
  - 日秒间隔 (INTERVAL DAY TO SECOND)
- - '####'
  - 其他数据类型
- - '#####'
  - 二进制大对象 (BLOB)
- - '#####'
  - 字符大对象 (CLOB)
- - '###'
  - 数据类型建议
- - '###'
  - 总结
- - '##'
  - 14. 创建表
- - '###'
  - 使用 SQL 代码创建表
- - '###'
  - CREATE TABLE 语句
- - '###'
  - 我们的员工表
- - '###'
  - 存储办公室详细信息
- - '###'
  - 办公室表
- - '###'
  - 销售会议表
- - '###'
  - 主键
- - '###'
  - 再次记录员工信息
- - '###'
  - 外键
- - '###'
  - 总结
- - '##'
  - 15. 向表中添加数据
- - '###'
  - INSERT 语句
- - '###'
  - 运行 INSERT 语句
- - '###'
  - 插入更多数据
- - '###'
  - 插入日期值
- - '####'
  - 注意
- - '###'
  - 保存和撤销更改
- - '###'
  - 插入数据的最佳实践
- - '###'
  - 小结
- - '##'
  - 16. 更新和删除数据
- - '###'
  - UPDATE 语句
- - '####'
  - 注意
- - '###'
  - 更新为新值
- - '###'
  - 在运行前检查更新语句
- - '###'
  - 更新 NULL 值
- - '###'
  - 基于现有值更新
- - '###'
  - 更新日期值
- - '###'
  - 查看和更新日期格式
- - '###'
  - 更新两个列
- - '###'
  - 没有 WHERE 子句的更新
- - '##'
  - 17. 更新或删除表结构
- - '###'
  - 为什么要更新表的结构？
- - '###'
  - ALTER TABLE 语句
- - '###'
  - 示例：添加列
- - '###'
  - 示例：更改数据类型
- - '###'
  - 示例：添加主键
- - '###'
  - 示例：添加外键
- - '###'
  - 示例：重命名列
- - '###'
  - 示例：删除列
- - '###'
  - 示例：重命名表
- - '###'
  - 从表中删除数据
- - '####'
  - 删除记录
- - '####'
  - 检查哪些记录将被删除
- - '####'
  - 删除表中的所有记录
- - '###'
  - 使用 DROP TABLE 删除表
- - '####'
  - 注意
- - '###'
  - 摘要
- - '#'
  - 第四部分：连接表
- - '##'
  - 18. 内连接
- - '###'
  - 多表
- - '###'
  - 什么是连接？
- - '###'
  - 连接示例
- - '###'
  - 连接、格式化与表别名
- - '###'
  - 内连接 (INNER JOIN)
- - '###'
  - 总结
- - '##'
  - 19. 外连接
- - '###'
  - 什么是外连接？
- - '###'
  - 编写左外连接
- - '###'
  - 使用左外连接显示所有员工
- - '###'
  - 编写右外连接
- - '###'
  - 何时会使用右外连接？
- - '###'
  - 编写全外连接
- - '###'
  - 在我们的表上使用全外连接
- - '###'
  - 总结
- - '##'
  - 20. 其他连接类型
- - '###'
  - USING 关键字
- - '###'
  - 更新 Office 表
- - '###'
  - 使用 USING 关键字编写查询
- - '####'
  - 注意
- - '###'
  - 什么是自然连接？
- - '####'
  - 注意
- - '###'
  - 使用自然连接编写查询
- - '###'
  - 什么是交叉连接？
- - '###'
  - 使用交叉连接
- - '###'
  - 替代连接语法
- - '####'
  - 内连接
- - '####'
  - 外连接
- - '####'
  - 为什么不应使用替代连接语法
- - '###'
  - 总结
- - '##'
  - 21. 连接多个表
- - '###'
  - 连接三个表
- - '###'
  - 连接我们的表
- - '####'
  - 注意
- - '###'
  - 使用外连接类型
- - '###'
  - 混合连接类型
- - '###'
  - 连接四个或更多表
- - '###'
  - 总结
- - '#'
  - 第五部分：函数
- - '##'
  - 22. 在 SQL 中使用函数
- - '###'
  - 什么是函数？
- - '###'
  - 可以在哪些地方使用函数？
- - '###'
  - 简单的数值计算
- - '###'
  - DUAL 表
- - '###'
  - 数字函数
- - '###'
  - ROUND 函数
- - '###'
  - CEILING 和 FLOOR 函数
- - '###'
  - 对表数据使用数字函数
- - '###'
  - 字符串的连接
- - '###'
  - 字符串函数
- - '####'
  - 更改大小写
- - '####'
  - 检查相同大小写的匹配
- - '####'
  - 注意
- - '####'
  - 获取字符串的一部分
- - '###'
  - 日期计算
- - '###'
  - 日期函数
- - '####'
  - 当前日期和时间
- - '####'
  - 添加月份
- - '###'
  - 总结
- - '##'
  - 23. 编写条件逻辑
- - '###'
  - CASE 语句
- - '###'
  - 简单 CASE 语句
- - '###'
  - 基本示例
- - '###'
  - 使用函数处理大小写
- - '###'
  - 多条件简单 CASE
- - '###'
  - 搜索式 CASE 语句
- - '###'
  - DECODE 函数
- - '###'
  - CASE 还是 DECODE？
- - '###'
  - 总结
- - '##'
  - 24. 理解聚合函数
- - '###'
  - 聚合函数
- - '###'
  - SUM 函数
- - '###'
  - SUM 与 WHERE 子句
- - '###'
  - SUM 与表达式
- - '###'
  - SUM 与 DISTINCT
- - '###'
  - COUNT 函数
- - '####'
  - 统计所有记录
- - '####'
  - 统计特定列
- - '####'
  - COUNT 与 DISTINCT
- - '####'
  - 注意
- - '####'
  - 结合 WHERE 进行计数
- - '###'
  - AVG 函数
- - '####'
  - 所有值的平均值
- - '####'
  - 使用 DISTINCT 计算平均值
- - '####'
  - 结合 WHERE 计算平均值
- - '###'
  - MIN 函数
- - '####'
  - 所有记录的最小值
- - '####'
  - 结合 WHERE 计算最小值
- - '###'
  - MAX 函数
- - '####'
  - 所有记录的最大值
- - '####'
  - 结合 WHERE 计算最大值
- - '###'
  - 概要
- - '##'
  - 25. 对结果进行分组
- - '###'
  - 分组数据
- - '###'
  - GROUP BY 关键字
- - '###'
  - 与连接（JOIN）一起使用的 GROUP BY
- - '###'
  - GROUP BY 与 SUM
- - '###'
  - 使用 WHERE 子句的 GROUP BY
- - '###'
  - 分组后限制结果
- - '###'
  - HAVING 子句
- - '###'
  - GROUP BY、HAVING 和 SUM
- - '###'
  - 查找重复记录
- - '###'
  - 总结
- - '##'
  - 26. 什么是索引？
- - '###'
  - 什么是索引？
- - '###'
  - 如何创建索引
- - '###'
  - 创建索引示例
- - '###'
  - 为什么性能很重要？
- - '####'
  - Web 应用程序
- - '####'
  - 夜间批处理作业
- - '####'
  - 报告系统
- - '###'
  - 使用连接（Join）的索引
- - '####'
  - 创建索引
- - '####'
  - 注意
- - '###'
  - 索引的缺点
- - '###'
  - 创建索引的最佳实践
- - '###'
  - 总结
- - '#'
  - 第六部分：命令行
- - '##'
  - 27. 使用命令行
- - '###'
  - 什么是 `SQL*Plus` 以及为何要使用它？
- - '###'
  - 如何启动 `SQL*Plus`
- - '###'
  - 其他登录语法
- - '###'
  - 一步登录
- - '###'
  - 在 SQL*Plus 中运行查询
- - '###'
  - 在 SQL*Plus 中格式化输出
- - '###'
  - 复制并粘贴到 SQL*Plus 中
- - '###'
  - 斜杠字符
- - '###'
  - 退出 SQL*Plus
- - '###'
  - SQLcl 怎么样？
- - '###'
  - 如何下载与运行 SQLcl
- - '###'
  - 总结
- - '#'
  - 第七部分：附录
- - '##'
  - 附录：如何查找和使用 Oracle SQL 参考手册
- - '###'
  - 查找 Oracle SQL 参考手册
- - '###'
  - Oracle SQL 参考手册概览
- - '###'
  - 使用目录查找所需内容
- - '###'
  - 使用搜索功能查找所需内容
- - '###'
  - 索引
- - '####'
  - B
- - '####'
  - C
- - '####'
  - D
- - '####'
  - E
- - '####'
  - F
- - '####'
  - G
- - '####'
  - H
- - '####'
  - I
- - '####'
  - J, K
- - '####'
  - L
- - '####'
  - M
- - '####'
  - N
- - '####'
  - O
- - '####'
  - P, Q
- - '####'
  - R
- - '####'
  - S
- - '####'
  - T
- - '####'
  - U, V
- - '####'
  - W, X, Y, Z
- - '##'
  - 关于作者和关于技术审校者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '##'
  - 致谢
