name: Pro SQL Server 2012 Integration Services
name_cn: SQL Server 2012 Integration Services 高级指南
slug: pro-sql-server-2012-integration-services
toc:
- - '#'
  - 内容概览
- - '##'
  - 第1章 Integration Services 简介
- - '###'
  - Microsoft ETL 简史
- - '###'
  - SSIS 能为您做什么？
- - '###'
  - 什么是企业级 ETL？
- - '###'
  - SSIS 架构
- - '###'
  - 告别数据转换服务
- - '###'
  - SSIS 新特性
- - '###'
  - 我们喜爱的人物与资源
- - '###'
  - 小结
- - '##'
  - 第2章 BIDS 与 SSMS
- - '###'
  - SQL Server 商业智能开发工作室
- - '####'
  - Analysis Services 项目
- - '####'
  - Integration Services 项目
- - '####'
  - 报表服务器项目向导
- - '####'
  - 报表服务器项目
- - '####'
  - 导入 Analysis Services 数据库
- - '####'
  - Integration Services 项目向导
- - '####'
  - 报表模型项目
- - '####'
  - Integration Services
- - '###'
  - 服务器数据库引擎
- - '###'
  - Integration Services 项目
- - '###'
  - 撤销还是重做，这是个问题
- - '###'
  - 报表服务器项目向导
- - '###'
  - 报表服务器项目
- - '###'
  - 导入 Analysis Services 数据库
- - '###'
  - BIDS 和 SSMS 工具详解
- - '###'
  - 导入 Analysis Services 数据库项目
- - '###'
  - 集成服务项目向导
- - '###'
  - 报表模型项目
- - '###'
  - 集成服务
- - '###'
  - 项目与 SSIS 包
- - '####'
  - 项目文件
- - '####'
  - 工具窗口
- - '####'
  - 设计器窗口
- - '####'
  - 解析引用
- - '#####'
  - 图 2-10. 解析引用实用工具
- - '####'
  - SSIS 工具箱
- - '#####'
  - 图 2-11. 目标助手
- - '####'
  - 包代码视图
- - '####'
  - 清单 2-2. 数据流任务组件
- - '####'
  - 数据流输出定义
- - '####'
  - XML 可读性改进
- - '####'
  - 数据行 ID 跟踪方式变更
- - '####'
  - CDATA 部分
- - '###'
  - SQL Server Management Studio 简介
- - '###'
  - Management Studio 与 SQL 查询开发
- - '####'
  - 工具窗口
- - '###'
  - SQL Server Management Studio 项目
- - '###'
  - 模板
- - '###'
  - 代码片段
- - '###'
  - 代码片段示例
- - '###'
  - 代码片段关键组件
- - '###'
  - 用于 SSIS 的查询
- - '###'
  - 总结
- - '##'
  - 第3章 Hello World——你的第一个 SSIS 2012 包
- - '###'
  - Integration Services 项目
- - '###'
  - 关键包属性
- - '###'
  - 包注释
- - '###'
  - 包属性类别
- - '###'
  - Hello World
- - '###'
  - 平面文件源连接
- - '###'
  - 平面文件连接管理器编辑器
- - '####'
  - 常规页面
- - '####'
  - 列页面
- - '####'
  - 高级页面
- - '####'
  - 预览页面
- - '###'
  - OLE DB 目标连接
- - '###'
  - 数据连接属性
- - '###'
  - 配置连接
- - '###'
  - 数据流任务
- - '###'
  - 源组件
- - '###'
  - Types 窗格与连接管理器
- - '###'
  - 添加目标组件
- - '###'
  - 创建数据流路径
- - '###'
  - 映射
- - '####'
  - 图 3-16. 数据流任务——映射错误 OLE DB 目标
- - '####'
  - 图 3-17. 使用 OLE DB 目标编辑器修复错误
- - '####'
  - 清单 3-1. 人口密度数据的创建表脚本
- - '####'
  - 图 3-18. OLE DB 目标编辑器映射页
- - '####'
  - 图 3-19. HelloWorld.dtsx — 包资源管理器
- - '###'
  - 执行
- - '###'
  - 现实世界
- - '####'
  - 控制流
- - '####'
  - 执行 SQL 任务
- - '####'
  - 数据流任务
- - '####'
  - 数据流组件配置与操作
- - '####'
  - 图 3-29. DER_SplitYearAndStatistics
- - '####'
  - 清单 3-3. 人口普查数据的建表脚本
- - '####'
  - 图 3-30. RealWorld.dtsx 执行结果
- - '####'
  - 清单 3-4. 反规范化数据的查询
- - '###'
  - 总结
- - '##'
  - 第4章 连接管理器
- - '###'
  - 常用连接管理器
- - '###'
  - OLE DB 连接管理器
- - '####'
  - OLE DB 与 ODBC
- - '###'
  - 文件连接管理器
- - '###'
  - SSIS 中的连接管理器
- - '###'
  - SSIS 支持的文件类型
- - '####'
  - 平面文件 (FLATFILE)
- - '####'
  - 文件 (FILE)
- - '####'
  - EXCEL
- - '####'
  - 多文件 (MULTIFILE)
- - '####'
  - 多平面文件 (MULTIFLATFILE)
- - '###'
  - 文件连接管理器的通用信息
- - '###'
  - ADO.NET 连接管理器
- - '###'
  - 缓存连接管理器
- - '###'
  - 其他连接管理器
- - '####'
  - FTP 连接管理器
- - '####'
  - HTTP 连接管理器
- - '####'
  - MSOLAP100 连接管理器
- - '####'
  - DQS 连接管理器
- - '####'
  - MSMQ 连接管理器
- - '####'
  - SMO 连接管理器
- - '####'
  - SMTP 连接管理器
- - '####'
  - SQLMOBILE 连接管理器
- - '####'
  - WMI 连接管理器
- - '###'
  - 小结
- - '##'
  - 第5章 控制流基础
- - '###'
  - 什么是控制流？
- - '###'
  - 用于控制流的 SSIS 工具箱
- - '###'
  - 收藏夹任务
- - '####'
  - 数据流任务
- - '####'
  - 执行 SQL 任务
- - '###'
  - 执行 SQL 任务编辑器—常规页
- - '####'
  - 通用页面
- - '####'
  - 参数映射页面
- - '####'
  - 执行 SQL 任务编辑器—结果集页面
- - '####'
  - 执行 SQL 任务编辑器—表达式页面
- - '###'
  - 常用任务
- - '####'
  - Analysis Services 处理任务
- - '####'
  - Analysis Services 处理任务编辑器—常规页面
- - '####'
  - Analysis Services 处理任务编辑器—处理设置页
- - '####'
  - 维度键错误选项卡
- - '####'
  - 大容量插入任务
- - '#####'
  - 使用大容量插入任务前的注意事项
- - '#####'
  - 大容量插入任务编辑器 - 连接页
- - '#####'
  - 大容量插入任务编辑器 - 选项页
- - '####'
  - 数据剖析任务
- - '#####'
  - 数据剖析任务编辑器—常规页
- - '#####'
  - 数据配置文件任务编辑器 — 配置文件请求页面
- - '####'
  - 执行包任务
- - '#####'
  - 执行包任务编辑器 — 包页面
- - '#####'
  - 执行包任务编辑器 — 参数绑定页面
- - '####'
  - 执行进程任务
- - '####'
  - 文件系统任务
- - '####'
  - FTP 任务
- - '#####'
  - 图 5-27. FTP 任务
- - '#####'
  - FTP 任务编辑器—常规页
- - '#####'
  - 图 5-28. FTP 任务编辑器—常规页
- - '#####'
  - FTP 任务编辑器—文件传输页
- - '#####'
  - 图 5-29. FTP 任务编辑器—文件传输页
- - '####'
  - IsTransferAscii 与远程路径属性
- - '####'
  - 脚本任务
- - '####'
  - 发送邮件任务
- - '####'
  - Web 服务任务
- - '#####'
  - Web 服务任务编辑器 — 常规页
- - '#####'
  - Web 服务任务编辑器 — 输入页
- - '####'
  - XML 任务
- - '####'
  - XML 任务常规页面
- - '####'
  - 优先级约束
- - '####'
  - 多重约束
- - '###'
  - 基本容器
- - '###'
  - 容器
- - '###'
  - 分组
- - '###'
  - 断点
- - '###'
  - 小结
- - '##'
  - 第6章 高级控制流任务
- - '###'
  - 高级任务
- - '####'
  - Analysis Services 执行 DDL 任务
- - '####'
  - 数据挖掘查询任务
- - '#####'
  - 数据挖掘查询任务编辑器——挖掘模型选项卡
- - '#####'
  - 数据挖掘查询任务编辑器——查询选项卡
- - '#####'
  - 数据挖掘查询任务编辑器 - 输出选项卡
- - '####'
  - 消息队列任务
- - '#####'
  - 消息队列任务编辑器 - 常规页
- - '#####'
  - 消息队列任务编辑器 — 发送页面
- - '#####'
  - 消息队列任务编辑器 — 接收页面
- - '####'
  - 传输数据库任务
- - '####'
  - 传输错误消息任务
- - '####'
  - 传输作业任务
- - '####'
  - 传输登录名任务
- - '####'
  - 传输 Master 存储过程任务
- - '####'
  - 传输 SQL Server 对象任务
- - '#####'
  - 属性参考
- - '#####'
  - 控制复制行为的属性
- - '#####'
  - 对象复制范围的属性
- - '#####'
  - 具体对象类型的列表属性
- - '####'
  - WMI 数据读取器任务
- - '####'
  - WMI 事件监视器任务
- - '###'
  - 高级容器
- - '####'
  - For Loop 容器
- - '####'
  - Foreach Loop 容器
- - '####'
  - “Foreach 循环编辑器”—“集合”页面
- - '#####'
  - Foreach 文件枚举器
- - '#####'
  - Foreach 项枚举器
- - '#####'
  - Foreach ADO 枚举器
- - '####'
  - Foreach 循环编辑器—变量映射页面
- - '####'
  - 任务主机控制器
- - '###'
  - 本章小结
- - '##'
  - 第7章 源和目标适配器
- - '###'
  - 数据流
- - '###'
  - 源和目标
- - '###'
  - 源向导
- - '###'
  - 精度和小数位数
- - '###'
  - 编辑数据流组件
- - '###'
  - 目标助手
- - '###'
  - 数据库源和目标
- - '####'
  - OLE DB
- - '#####'
  - OLE DB 连接管理器下拉列表
- - '#####'
  - 数据访问模式下拉列表
- - '#####'
  - 选项描述
- - '#####'
  - SQL 命令文本框
- - '#####'
  - 参数按钮
- - '#####'
  - 构建查询按钮
- - '#####'
  - 浏览按钮
- - '#####'
  - 解析查询按钮
- - '#####'
  - 预览按钮
- - '####'
  - ADO.NET
- - '####'
  - SQL Server 目标
- - '####'
  - SQL Server Compact
- - '####'
  - 文件
- - '#####'
  - 平面文件
- - '#####'
  - 平展文件
- - '####'
  - Excel 文件
- - '#####'
  - 图 7-28. 在编辑器中配置 Excel 源
- - '#####'
  - 图 7-29. 查看 Excel 源编辑器的列页面
- - '#####'
  - 表 7-4. Excel 到 SSIS 再到 SQL Server 的数据类型转换
- - '#####'
  - JET 驱动程序与 64 位
- - '#####'
  - 图 7-30. 将 SSIS 项目设置为以 32 位模式运行
- - '#####'
  - 图 7-31. Excel 电子表格成功导入到 SQL Server 表
- - '#####'
  - 图 7-32. 新的 SSIS 目标工作簿，除列标题外为空
- - '#####'
  - 图 7-33. 在 Excel 目标编辑器中配置 Excel 目标配适器
- - '####'
  - 原始文件
- - '####'
  - XML 文件
- - '###'
  - 专用适配器
- - '####'
  - Analysis Services
- - '###'
  - 小结
- - '##'
  - 第8章 数据流转换
- - '###'
  - 高层次数据流
- - '###'
  - 转换类型
- - '###'
  - 同步转换
- - '###'
  - 异步转换
- - '###'
  - 阻塞转换
- - '###'
  - 行转换
- - '####'
  - 数据转换
- - '#####'
  - 数据类型映射
- - '#####'
  - 表 8-2. SSIS 数据类型到 SQL 数据类型的映射
- - '####'
  - 字符映射
- - '#####'
  - 图 8-6. 数据流中的字符映射转换
- - '####'
  - 复制列转换
- - '####'
  - 派生列转换
- - '####'
  - 导入列转换
- - '#####'
  - 配置导入列
- - '####'
  - OLE DB 命令
- - '#####'
  - 参数化 SQL 语句
- - '####'
  - 导出列
- - '####'
  - 脚本组件
- - '###'
  - 行集转换
- - '####'
  - 聚合
- - '#####'
  - 图 8-32. 在高级模式下编辑聚合转换
- - '####'
  - 排序
- - '#####'
  - 图 8-33. 数据流中的排序转换
- - '#####'
  - ISSORTED 属性
- - '####'
  - 透视转换
- - '####'
  - 百分比采样转换
- - '#####'
  - 图 8-40. 数据流中的百分比采样转换
- - '#####'
  - 图 8-41. 编辑百分比采样转换
- - '####'
  - 行采样
- - '#####'
  - 图 8-42. 数据流中的行采样转换
- - '#####'
  - 图 8-43. 行采样转换编辑器
- - '####'
  - 逆透视
- - '#####'
  - 图 8-44. 对非规范化数据集进行逆透视
- - '#####'
  - 图 8-45. 示例数据流中的逆透视转换
- - '#####'
  - 图 8-46. 逆透视转换编辑器
- - '###'
  - 拆分与联接
- - '####'
  - 查找
- - '#####'
  - 图 8-47. 示例数据流中的查找转换
- - '#####'
  - 常规页面
- - '#####'
  - 连接页面
- - '#####'
  - 列页面
- - '#####'
  - 高级页面
- - '####'
  - 缓存转换
- - '####'
  - 条件拆分
- - '####'
  - 多播
- - '####'
  - Union All
- - '####'
  - 合并
- - '####'
  - 合并连接
- - '####'
  - 审核
- - '#####'
  - 行数
- - '#####'
  - 审核
- - '###'
  - 商业智能转换
- - '###'
  - 总结
- - '##'
  - 第9章 变量、参数与表达式
- - '###'
  - 什么是变量与表达式？
- - '###'
  - 什么是参数？
- - '###'
  - SSIS 数据类型
- - '###'
  - 数据类型参考
- - '####'
  - DT_DBTIMESTAMP
- - '####'
  - DT_DBTIMESTAMP2 (DT_DBTIMESTAMP2, «scale»)
- - '####'
  - DT_DBTIMESTAMPOFFSET (DT_DBTIMESTAMPOFFSET, «scale»)
- - '####'
  - DT_DECIMAL (DT_DECIMAL, «scale»)
- - '####'
  - DT_FILETIME (DT_FILETIME)
- - '####'
  - DT_GUID (DT_GUID)
- - '####'
  - DT_I1 (DT_I1)
- - '####'
  - DT_I2 (DT_I2)
- - '####'
  - DT_I4 (DT_I4)
- - '####'
  - DT_I8 (DT_I8)
- - '####'
  - DT_NUMERIC (DT_NUMERIC, «precision», «scale»)
- - '####'
  - DT_R4 (DT_R4)
- - '####'
  - DT_R8 (DT_R8)
- - '####'
  - DT_STR (DT_STR, «length», «code_page»)
- - '####'
  - DT_UI1 (DT_UI1)
- - '####'
  - DT_UI2 (DT_UI2)
- - '####'
  - DT_UI4 (DT_UI4)
- - '####'
  - DT_UI8 (DT_UI8)
- - '####'
  - DT_WSTR (DT_WSTR, «length»)
- - '####'
  - DT_IMAGE (DT_IMAGE)
- - '####'
  - DT_NTEXT (DT_NTEXT)
- - '####'
  - DT_TEXT (DT_TEXT, «code_page»)
- - '###'
  - 变量作用域、默认值和命名空间
- - '####'
  - 作用域
- - '####'
  - 默认值
- - '####'
  - 命名空间
- - '###'
  - 系统变量
- - '####'
  - 包系统变量
- - '####'
  - 容器系统变量
- - '####'
  - 任务系统变量
- - '####'
  - 事件处理程序系统变量
- - '###'
  - 访问变量
- - '###'
  - 参数化查询
- - '###'
  - 派生列转换
- - '###'
  - 条件性拆分
- - '###'
  - 记录集目标
- - '###'
  - Foreach 循环容器
- - '###'
  - 脚本任务
- - '###'
  - 执行 SQL 任务结果集
- - '###'
  - 源类型
- - '###'
  - 动态 SQL
- - '####'
  - 代码清单 9-4. StateQuery 赋值
- - '###'
  - 传递变量
- - '###'
  - SSIS 表达式语言
- - '####'
  - 函数
- - '####'
  - 字符函数
- - '####'
  - 日期函数
- - '####'
  - NULL 函数
- - '####'
  - 运算符
- - '###'
  - 总结
- - '##'
  - 第10章 脚本编写
- - '###'
  - 脚本任务
- - '###'
  - 高级功能
- - '###'
  - 脚本任务概述
- - '###'
  - Foreach 循环容器的限制
- - '###'
  - 创建示例包
- - '###'
  - 代码示例
- - '###'
  - 脚本任务事件
- - '###'
  - 示例：使用脚本任务获取文件信息
- - '###'
  - 使用文件元数据
- - '###'
  - 脚本组件源
- - '###'
  - 脚本组件事件
- - '###'
  - 同步脚本组件转换
- - '###'
  - 同步还是异步？
- - '###'
  - 输入列页面
- - '###'
  - 脚本组件同步转换
- - '###'
  - 示例脚本分析
- - '###'
  - 异步脚本组件转换
- - '###'
  - 列定义
- - '###'
  - 脚本组件方法
- - '###'
  - 脚本组件目的地
- - '###'
  - 总结
- - '##'
  - 第11章 事件与错误处理
- - '###'
  - SSIS 事件
- - '###'
  - 表 11-1. 常见 SSIS 事件
- - '###'
  - 日志事件
- - '####'
  - 表 11-2. 数据流任务日志事件
- - '####'
  - 表 11-3. 数据准备任务日志事件
- - '####'
  - 表 11-4. 工作流任务日志事件
- - '####'
  - 表 11-5. SQL Server 任务日志事件
- - '###'
  - 脚本任务与日志提供程序
- - '###'
  - 脚本任务组
- - '###'
  - 日志提供程序
- - '###'
  - 选择要记录的事件
- - '###'
  - 脚本事件
- - '####'
  - 脚本任务事件
- - '#####'
  - 图 11-8：演示脚本任务事件的示例包
- - '#####'
  - 图 11-9：示例包出错
- - '#####'
  - 图 11-10：包失败后查看日志
- - '####'
  - 脚本组件事件
- - '#####'
  - 表 11-9：脚本组件事件触发方法
- - '#####'
  - FIREERROR() 与 MAXIMUMERRORCOUNT
- - '#####'
  - 图 11-11：在脚本组件中引发事件
- - '#####'
  - 图 11-12：脚本组件日志条目的结果
- - '###'
  - 事件处理程序
- - '####'
  - 图 11-13：向任务添加事件处理程序
- - '####'
  - 图 11-14：完成的 OnError 事件处理程序
- - '###'
  - 本章小结
- - '##'
  - 第12章 数据剖析与清洗
- - '###'
  - 数据剖析
- - '###'
  - 数据剖析任务
- - '###'
  - 数据剖析任务编辑器
- - '####'
  - 表 12-1. 数据分析请求类型
- - '###'
  - 数据分析概况查看器
- - '####'
  - 列长度分布分析
- - '####'
  - 列空值比率分析
- - '####'
  - 列模式配置文件
- - '####'
  - 列统计配置文件
- - '####'
  - 列值分布配置文件
- - '####'
  - 候选键配置文件
- - '###'
  - 连接管理器与关键列选择
- - '###'
  - 候选键配置文件输出
- - '###'
  - 函数依赖配置文件
- - '###'
  - 模糊查找
- - '###'
  - 模糊分组
- - '####'
  - 代码清单 12-5. 模糊分组结果
- - '###'
  - 数据预览
- - '####'
  - 数据查看器
- - '####'
  - 数据采样
- - '#####'
  - 行采样
- - '#####'
  - 百分比采样
- - '###'
  - 总结
- - '##'
  - 第13章 日志记录与审计
- - '###'
  - 日志记录
- - '####'
  - 启用日志记录
- - '####'
  - 选择日志事件
- - '####'
  - 关于 SQL 日志记录
- - '###'
  - 摘要审计
- - '####'
  - 批次级别审计
- - '####'
  - 包级别审计
- - '####'
  - 向包添加审计
- - '###'
  - 带有审计调用的示例包
- - '###'
  - 简单的数据血缘
- - '###'
  - 总结
- - '##'
  - 第14章 异构源和目标
- - '###'
  - SQL Server 源和目标
- - '###'
  - 高级属性编辑器
- - '###'
  - 将数据加载到 SQL Server
- - '###'
  - 其他 RDBMS 源和目标
- - '###'
  - 平面文件源和目标
- - '###'
  - Excel 源与目标
- - '###'
  - XML 源
- - '####'
  - 图 14-14. XML 源编辑器的列页面
- - '###'
  - 原始文件源和目标
- - '###'
  - SQL Server Analysis Services 源
- - '###'
  - 记录集目标
- - '###'
  - 小结
- - '##'
  - 第15章 数据流调优与优化
- - '###'
  - 在数据库端限制行数
- - '###'
  - 在数据库中执行连接
- - '###'
  - 在数据库中排序
- - '###'
  - 在数据库中执行复杂的预处理
- - '###'
  - 确保安全性和“读取审计”
- - '###'
  - 拉取过多列
- - '###'
  - 使用执行树
- - '####'
  - 在 BIDS 中高亮显示执行树
- - '###'
  - 实现并行性
- - '###'
  - 适可而止
- - '###'
  - 小结
- - '##'
  - 第16章 父-子设计模式
- - '###'
  - 理解父-子设计模式
- - '####'
  - 代码清单 16-1. 子包脚本任务
- - '####'
  - 代码清单 16-2. 被禁用子包脚本任务
- - '###'
  - 使用参数传递值
- - '###'
  - 处理共享配置信息
- - '###'
  - 覆盖属性
- - '###'
  - 日志记录
- - '###'
  - 实现数据驱动的 ETL
- - '####'
  - 清单 16-3. 表 CH16_Apress_PackageExecution
- - '###'
  - 填充 dbo.CH16_Apress_PackageExecution
- - '###'
  - 图 16-4. CH16_DynamicParentPackage 变量
- - '###'
  - 图 16-5. CH16_Apress_DynamicParentPackage
- - '###'
  - SQL_GetPackageList 查询
- - '###'
  - 总结
- - '##'
  - 第17章 维度数据 ETL
- - '###'
  - 介绍维度数据
- - '###'
  - 数据仓库、操作数据存储及其他流行术语
- - '###'
  - 快速见效
- - '####'
  - 以优化模式运行
- - '####'
  - 移除“死端”组件
- - '####'
  - 保持包体积小巧
- - '####'
  - 优化查找
- - '####'
  - 保持数据持续流动
- - '####'
  - 最小化日志记录
- - '###'
  - 使用快速加载选项
- - '###'
  - 理解缓慢变化维度
- - '####'
  - 类型 0 维度
- - '####'
  - 类型 1 维度
- - '####'
  - 哈希码
- - '###'
  - 类型 1 SCD 更新
- - '###'
  - 类型 2 维度
- - '###'
  - 类型 3 维度
- - '###'
  - 小结
- - '##'
  - 第18章 构建健壮的解决方案
- - '###'
  - 什么构成健壮的解决方案
- - '###'
  - 关键因素
- - '###'
  - 弹性
- - '###'
  - 数据流任务
- - '###'
  - 事件处理程序
- - '###'
  - 动态性
- - '###'
  - 可追溯性
- - '####'
  - 日志提供程序
- - '####'
  - 自定义日志记录
- - '###'
  - 小结
- - '##'
  - 第19章 部署模型
- - '###'
  - 生成过程
- - '###'
  - 部署过程
- - '####'
  - 清单 19-1. 启用 CLR 集成
- - '###'
  - 环境
- - '###'
  - 执行
- - '###'
  - 导入过程
- - '###'
  - 迁移过程
- - '###'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '###'
  - ADO.NET
- - '###'
  - Analysis Services 执行 DDL 任务编辑器
- - '##'
  - B
- - '###'
  - 批次级别审核
- - '###'
  - Analysis Services 处理任务编辑器
- - '##'
  - C
- - '##'
  - D
- - '##'
  - F, G
- - '##'
  - H
- - '##'
  - I, J, K
- - '##'
  - L
- - '##'
  - M, N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U, V
- - '##'
  - W
- - '##'
  - X, Y, Z
