name: Expert Oracle Exadata
name_cn: Oracle Exadata 高级指南
slug: expert-oracle-exadata
toc:
- - '#'
  - 引言
- - '##'
  - 目标读者
- - '##'
  - 一个不断变化的目标
- - '##'
  - 向所有提供帮助的人致以万分感谢！
- - '##'
  - 各章节作者
- - '#'
  - 乐趣无穷！
- - '#'
  - 致谢
- - '#'
  - 目录
- - '##'
  - 第1章：什么是Exadata？
- - '###'
  - Exadata概述
- - '###'
  - Exadata历史
- - '###'
  - 关于Exadata的其他观点
- - '####'
  - 数据仓库一体机
- - '####'
  - OLTP机器
- - '####'
  - 整合平台
- - '###'
  - 配置选项
- - '####'
  - Exadata数据库机X5-2
- - '####'
  - Exadata数据库机X4-8
- - '####'
  - Exadata存储扩展机柜X5-2
- - '###'
  - 硬件组件
- - '####'
  - 操作系统
- - '####'
  - 数据库服务器
- - '####'
  - 存储服务器
- - '####'
  - InfiniBand
- - '####'
  - 闪存缓存
- - '####'
  - 磁盘
- - '####'
  - 零散组件
- - '###'
  - 软件组件
- - '####'
  - 数据库服务器软件
- - '####'
  - 存储服务器软件
- - '####'
  - 软件架构
- - '###'
  - 小结
- - '##'
  - 第2章：下推卸载/智能扫描
- - '###'
  - 为什么下推卸载很重要
- - '###'
  - 下推卸载包含什么
- - '####'
  - 列投影
- - '####'
  - 谓词过滤
- - '####'
  - 存储索引和区域映射
- - '####'
  - 简单连接（布隆过滤器）
- - '####'
  - 函数下推卸载
- - '####'
  - 压缩/解压缩
- - '####'
  - 加密/解密
- - '####'
  - 虚拟列
- - '####'
  - 支持LOB下推卸载
- - '####'
  - JSON支持与下推卸载
- - '####'
  - 数据挖掘模型评分
- - '####'
  - 非智能扫描的下推卸载
- - '###'
  - 智能扫描前提条件
- - '####'
  - 全表扫描
- - '####'
  - 直接路径读取
- - '####'
  - Exadata存储
- - '###'
  - 禁用智能扫描的情况
- - '####'
  - 根本不可用
- - '####'
  - 回退到块传输
- - '####'
  - 跳过某些下推卸载
- - '####'
  - 静默跳过下推卸载
- - '###'
  - 如何验证智能扫描是否发生
- - '####'
  - '`10046`跟踪'
- - '####'
  - 会话性能统计信息
- - '####'
  - 可下推卸载字节数
- - '####'
  - '`SQL监控`'
- - '###'
  - 参数
- - '###'
  - 小结
- - '##'
  - 第3章：混合列压缩
- - '###'
  - Oracle存储回顾
- - '###'
  - 解析Oracle块
- - '###'
  - 压缩机制
- - '####'
  - '`基本`压缩'
- - '####'
  - '`OLTP`压缩'
- - '####'
  - 混合列压缩
- - '###'
  - '`HCC`内部机制'
- - '####'
  - 当你创建`HCC`压缩表时会发生什么？
- - '###'
  - '`HCC`性能'
- - '####'
  - 加载性能
- - '####'
  - 查询性能
- - '####'
  - DML性能
- - '###'
  - 预期压缩率
- - '###'
  - 压缩顾问
- - '###'
  - 实际案例
- - '###'
  - 限制/挑战
- - '####'
  - 将数据移动到非Exadata平台
- - '####'
  - 禁用串行直接路径读取
- - '####'
  - 锁问题
- - '####'
  - 单行访问
- - '###'
  - 常见使用场景
- - '###'
  - 自动数据优化
- - '####'
  - '`ADO`示例用例'
- - '###'
  - 小结
- - '##'
  - 第4章：存储索引
- - '###'
  - 结构
- - '###'
  - 监控存储索引
- - '####'
  - 数据库统计信息
- - '####'
  - 跟踪
- - '####'
  - 监控总结
- - '###'
  - 控制存储索引
- - '####'
  - '`_kcfis_storageidx_disabled`'
- - '####'
  - '`_kcfis_storageidx_diag_mode`'
- - '####'
  - '`_cell_storidx_mode`'
- - '####'
  - '`_cell_storidx_minmax_enabled`'
- - '####'
  - 存储软件参数
- - '###'
  - 行为
- - '###'
  - 性能
- - '###'
  - 针对空值的特殊优化
- - '###'
  - 值的物理分布
- - '###'
  - 潜在问题
- - '####'
  - 结果不正确
- - '####'
  - 移动目标
- - '####'
  - 分区大小
- - '####'
  - 不兼容的编码技术
- - '###'
  - 小结
- - '##'
  - 第5章：Exadata智能闪存缓存
- - '###'
  - 硬件
- - '####'
  - Exadata X4-2存储服务器中的闪存
- - '####'
  - Exadata X5-2存储服务器中的闪存
- - '####'
  - 闪存缓存vs.闪存磁盘
- - '###'
  - 将闪存用作缓存
- - '###'
  - 混合工作负载与OLTP优化
- - '###'
  - 使用闪存进行数据库日志记录
- - '###'
  - 使用闪存加速写入
- - '###'
  - 其他与`WBFC`相关的优化
- - '###'
  - '`ESFC`和`ESFL`如何创建'
- - '###'
  - 启用写回闪存缓存
- - '###'
  - 闪存缓存压缩
- - '###'
  - 控制`ESFC`使用
- - '###'
  - 监控
- - '####'
  - 在存储层
- - '####'
  - 在数据库层
- - '###'
  - 小结
- - '##'
  - 第6章：Exadata并行操作
- - '###'
  - 参数
- - '###'
  - 存储层的并行化
- - '###'
  - '`自动DOP`'
- - '####'
  - 操作与配置
- - '####'
  - I/O校准
- - '####'
  - '`自动DOP`总结'
- - '###'
  - 并行语句排队
- - '####'
  - 旧方法
- - '####'
  - 新方法
- - '####'
  - 控制并行排队
- - '####'
  - 并行语句排队总结
- - '###'
  - 内存中并行执行
- - '###'
  - 并行执行故障排除
- - '###'
  - 小结
- - '##'
  - 第7章：资源管理
- - '###'
  - 整合
- - '####'
  - 数据库整合的类型
- - '###'
  - 实例笼
- - '####'
  - 配置实例笼
- - '####'
  - 设置`CPU_COUNT`
- - '####'
  - 实例笼的使用和结果
- - '####'
  - 实例笼与多租户
- - '###'
  - 超额分配
- - '###'
  - 使用Cgroups将实例绑定到特定CPU
- - '####'
  - Cgroups的安装与配置
- - '###'
  - '`Oracle 12c线程执行`'
- - '###'
  - 管理PGA内存
- - '###'
  - 数据库资源管理器
- - '####'
  - 创建`CDB`资源计划
- - '####'
  - 创建（可插拔）数据库资源计划
- - '####'
  - 使用调度程序更改资源计划
- - '###'
  - '等待事件：`resmgr: cpu quantum`'
- - '###'
  - 从这里开始
- - '###'
  - 资源映射优先级
- - '###'
  - 资源限制
- - '###'
  - 其他限制参数
- - '###'
  - 使用`ORACLE_FUNCTION`的消费者组映射
- - '###'
  - 监控资源管理器
- - '####'
  - 资源管理器视图
- - '###'
  - I/O资源管理器
- - '####'
  - '`IORM`方法'
- - '####'
  - '`IORM`工作原理'
- - '####'
  - '`IORM`架构'
- - '####'
  - '`IORM`目标'
- - '####'
  - 配置数据库间`IORM`
- - '####'
  - 类别`IORM`
- - '###'
  - I/O资源管理器与可插拔数据库
- - '###'
  - I/O资源管理器配置文件
- - '###'
  - 资源管理指令矩阵
- - '###'
  - '`IORM`监控与指标'
- - '###'
  - 小结
- - '##'
  - 第8章：配置Exadata
- - '###'
  - Exadata网络组件
- - '####'
  - 管理网络
- - '####'
  - 客户端访问网络
- - '####'
  - 私有网络
- - '###'
  - 关于配置过程
- - '###'
  - 配置Exadata
- - '####'
  - 步骤1：收集安装要求
- - '####'
  - 步骤2：运行Oracle Exadata部署助手
- - '####'
  - 步骤3：创建网络VLAN和主机名的DNS条目
- - '####'
  - 步骤4：运行`CheckIP`以验证网络就绪情况
- - '####'
  - 步骤5：为Exadata机柜布线和供电
- - '####'
  - 步骤6：执行硬件安装
- - '####'
  - 步骤7：暂存`OneCommand`文件和Oracle软件
- - '####'
  - 步骤8：配置操作系统
- - '####'
  - 步骤9：运行`OneCommand`
- - '###'
  - 升级Exadata
- - '####'
  - 创建新的`RAC`集群
- - '####'
  - 升级现有集群
- - '###'
  - 小结
- - '##'
  - 第9章：恢复Exadata
- - '###'
  - Exadata诊断工具
- - '####'
  - Sun诊断：`sundiag.sh`
- - '####'
  - 单元警报
- - '###'
  - 备份Exadata
- - '####'
  - 备份数据库服务器
- - '####'
  - 备份存储单元
- - '####'
  - 备份数据库
- - '####'
  - 基于磁盘的备份
- - '####'
  - 基于磁带的备份
- - '####'
  - 从备用数据库备份
- - '####'
  - 针对`RMAN`的Exadata优化
- - '###'
  - 恢复Exadata
- - '####'
  - 还原数据库服务器
- - '####'
  - 恢复存储单元
- - '###'
  - 小结
- - '##'
  - 第10章：Exadata等待事件
- - '###'
  - Exadata特定的事件
- - '####'
  - “`cell`”事件
- - '####'
  - 触发事件的执行计划步骤
- - '###'
  - 用户`I/O`类中的Exadata等待事件
- - '####'
  - '`cell smart table scan`'
- - '####'
  - '`cell smart index scan`'
- - '####'
  - '`cell single block physical read`'
- - '####'
  - '`cell multiblock physical read`'
- - '####'
  - '`cell list of blocks physical read`'
- - '####'
  - '`cell smart file creation`'
- - '####'
  - '`cell statistics gather`'
- - '###'
  - 用户/IO类中的次要事件
- - '###'
  - 系统`I/O`类中的Exadata等待事件
- - '####'
  - '`cell smart incremental backup`'
- - '####'
  - '`cell smart restore from backup`'
- - '###'
  - 其他和空闲类中的Exadata等待事件
- - '####'
  - '`cell smart flash unkeep`'
- - '###'
  - 事件含义
- - '###'
  - 非Exadata特定事件
- - '####'
  - '`direct path read`'
- - '####'
  - '`Enq: KO—fast object checkpoint`'
- - '####'
  - '`reliable message`'
- - '###'
  - 资源管理器事件
- - '####'
  - '`resmgr:become active`'
- - '####'
  - '`resmgr:cpu quantum`'
- - '####'
  - '`resmgr:pq queued`'
- - '###'
  - 小结
- - '##'
  - 第11章：Exadata性能指标
- - '###'
  - 衡量Exadata的性能指标
- - '###'
  - 重温Exadata智能扫描的前提条件
- - '###'
  - Exadata智能扫描性能
- - '###'
  - 理解Exadata智能扫描指标和性能计数器
- - '###'
  - Exadata动态性能计数器
- - '###'
  - 何时以及如何使用性能计数器
- - '###'
  - Exadata性能计数器的含义与解释
- - '###'
  - 选定子集的性能计数器参考
- - '###'
  - 理解SQL语句性能
- - '###'
  - 查询`cellsrv`内部处理统计信息
- - '###'
  - '`V$CELL`系列视图'
- - '###'
  - '`cellsrvstat`实用程序'
- - '###'
  - 小结
- - '##'
  - 第12章：监控Exadata性能
- - '###'
  - 系统化方法
- - '###'
  - 监控SQL语句响应时间
- - '###'
  - 使用实时`SQL监控`报告监控SQL语句
- - '###'
  - 使用`V$SQL`和`V$SQLSTATS`监控SQL语句
- - '###'
  - 监控存储单元层
- - '####'
  - 使用`CellCLI`访问单元层中的单元指标
- - '####'
  - 使用Enterprise Manager Exadata存储服务器插件访问单元指标
- - '####'
  - 应使用哪些单元指标？
- - '###'
  - 监控Exadata存储单元OS级指标
- - '###'
  - 小结
- - '##'
  - 第13章：迁移到Exadata
- - '###'
  - 迁移策略
- - '###'
  - 逻辑迁移
- - '####'
  - 抽取和加载
- - '####'
  - 通过数据库链接复制数据
- - '####'
  - 基于复制的迁移
- - '####'
  - 逻辑迁移总结
- - '###'
  - 物理迁移
- - '####'
  - 备份与还原
- - '####'
  - 完整备份与还原
- - '####'
  - 增量备份
- - '####'
  - 可传输表空间
- - '####'
  - 带增量备份的跨平台`TTS`
- - '####'
  - 物理备用数据库
- - '####'
  - 物理迁移部分总结
- - '###'
  - 小结
- - '##'
  - 第14章：存储布局
- - '###'
  - Exadata磁盘架构
- - '###'
  - 故障组
- - '###'
  - 网格磁盘
- - '###'
  - 存储分配
- - '###'
  - 创建网格磁盘
- - '####'
  - 创建网格磁盘
- - '####'
  - 网格磁盘大小调整
- - '####'
  - 创建基于`FlashDisk`的网格磁盘
- - '###'
  - 存储策略
- - '###'
  - 配置选项
- - '###'
  - 隔离存储单元访问
- - '###'
  - 单元安全
- - '####'
  - 单元安全术语
- - '####'
  - 单元安全最佳实践
- - '###'
  - 配置`ASM`范围的安全
- - '###'
  - 配置数据库范围的安全
- - '###'
  - 移除单元安全
- - '###'
  - 小结
- - '##'
  - 第15章：计算节点布局
- - '###'
  - 配置考量
- - '###'
  - 非`RAC`配置
- - '###'
  - 拆分机架集群
- - '###'
  - 典型Exadata配置
- - '###'
  - 多机柜集群
- - '###'
  - 小结
- - '##'
  - 第16章：为Exadata打补丁
- - '###'
  - Exadata补丁类型
- - '###'
  - Exadata季度数据库补丁
- - '####'
  - 就地应用`QDPE`
- - '####'
  - 通过克隆主目录应用`QDPE`
- - '###'
  - Exadata存储服务器补丁
- - '####'
  - 应用Exadata存储服务器补丁
- - '###'
  - 升级计算节点
- - '###'
  - 升级InfiniBand交换机
- - '###'
  - 向备用系统应用补丁
- - '###'
  - 小结
- - '##'
  - 第17章：重新认识一些我们以为知道的事情
- - '###'
  - 两个系统的故事
- - '###'
  - '`OLTP`导向的工作负载'
- - '####'
  - Exadata智能闪存缓存(`ESFC`)
- - '####'
  - 可扩展性
- - '####'
  - 写密集型`OLTP`工作负载
- - '###'
  - '`DW`导向的工作负载'
- - '####'
  - 启用智能扫描
- - '###'
  - 可能破坏智能扫描的情况
- - '###'
  - 其他需要牢记的事项
- - '###'
  - 混合工作负载
- - '###'
  - 是否使用索引？
- - '###'
  - 优化器不知道
- - '###'
  - 使用资源管理器
- - '###'
  - 小结
- - '##'
  - 附录A：`CELLCLI`和`DCLI`
- - '###'
  - '`CellCLI`简介'
- - '###'
  - 调用`cellcli`
- - '###'
  - 熟悉`cellcli`
- - '###'
  - 从操作系统发送命令
- - '###'
  - 在数据库中使用`cellcli``XML`输出
- - '###'
  - 配置和管理存储单元
- - '###'
  - '`dcli`简介'
- - '###'
  - 小结
- - '##'
  - 附录B：在线Exadata资源
- - '###'
  - My Oracle Support注释
- - '###'
  - 作者的博客
- - '##'
  - 附录C：诊断脚本
- - '##'
  - 附录D：`exachk`
- - '###'
  - '`exachk`简介'
- - '###'
  - 运行`exachk`
- - '###'
  - 为`exachk`保存密码
- - '###'
  - 自动化`exachk`执行
- - '###'
  - 小结
- - '##'
  - 关于作者
