name: SQL Server Data Automation Through Frameworks
name_cn: SQL Server 数据自动化框架指南
slug: sql-server-data-automation-through-frameworks
toc:
- - '##'
  - 第一部分：基于存储过程的数据库框架
- - '###'
  - 第 1 章：存储过程 101
- - '###'
  - 第 2 章：使用存储过程实现自动化
- - '###'
  - 第 3 章：存储过程协调器
- - '###'
  - 第 4 章：一个基于存储过程的元数据驱动框架
- - '##'
  - 第二部分：SSIS 框架
- - '###'
  - 第 5 章：一个简单的、自定义、基于文件的 SSIS 框架
- - '###'
  - 第 6 章：框架执行引擎
- - '###'
  - 第 7 章：框架日志记录
- - '###'
  - 第 8 章：Azure-SSIS 集成运行时
- - '###'
  - 第 9 章：部署一个简单的、自定义、基于文件的 Azure-SSIS 框架
- - '###'
  - 第 10 章：ADF 中的框架日志记录
- - '###'
  - 第 11 章：ADF 框架中的容错
- - '##'
  - 1. 存储过程基础
- - '##'
  - 2. 使用存储过程实现自动化
- - '##'
  - 3. 存储过程协调器
- - '###'
  - 协调器
- - '###'
  - 流程快速概览
- - '###'
  - 问题排查初探
- - '###'
  - 总结
- - '##'
  - 4. 基于存储过程的元数据驱动框架
- - '###'
  - 构建元数据
- - '####'
  - 简介
- - '####'
  - 创建元数据表
- - '####'
  - 加载元数据
- - '####'
  - 关联存储过程与应用程序
- - '###'
  - 元数据就绪的控制器
- - '###'
  - 支持元数据的协调器
- - '###'
  - 利用元数据进行故障排除
- - '###'
  - 总结
- - '##'
  - 5. 一个简单、自定义、基于文件的 SSIS 框架
- - '###'
  - SSIS 框架的定义与设计
- - '####'
  - 功能性
- - '####'
  - 共情
- - '####'
  - 简洁性
- - '###'
  - 构建基于文件的 SSIS 框架
- - '####'
  - 获取代码
- - '####'
  - 元数据驱动的执行管理
- - '####'
  - '`SSISConfig` 数据库'
- - '####'
  - '`config` 架构'
- - '####'
  - Config.Applications 表
- - '####'
  - Config.Packages 表
- - '#####'
  - 执行属性
- - '#####'
  - 默认约束
- - '#####'
  - 关系
- - '#####'
  - 常见问题
- - '###'
  - 一个示例 SSIS 解决方案
- - '####'
  - 配置 Visual Studio 2019 进行 SSIS 开发
- - '####'
  - 创建示例 SSIS 解决方案
- - '###'
  - SSIS 框架元数据管理
- - '####'
  - 添加 SSIS 应用程序
- - '####'
  - 添加 SSIS 包
- - '####'
  - 分配 SSIS 应用包
- - '###'
  - 总结
- - '##'
  - 6. 框架执行引擎
- - '###'
  - 创建父 SSIS 包
- - '###'
  - 记录执行值
- - '###'
  - 从 SSISConfig 检索 SSIS 应用程序包
- - '###'
  - 配置 SSIS 包以迭代应用程序包
- - '###'
  - 迭代应用程序包
- - '###'
  - 配置 SSIS 变量并映射数据集
- - '###'
  - 记录应用程序包值
- - '###'
  - 执行应用程序包
- - '###'
  - Parent.dtsx 配置与测试
- - '###'
  - 测试执行与结果
- - '###'
  - 记录执行结果
- - '####'
  - 查看 SCR Log Package Execution Failure 脚本任务的 ReadOnlyVariables 属性
- - '####'
  - 结论
- - '##'
  - 7. 框架日志记录
- - '###'
  - 创建日志模式
- - '###'
  - 向 Parent.dtsx 添加应用程序实例日志记录
- - '###'
  - 配置 Execute SQL Task 记录应用程序实例状态
- - '###'
  - 在控制流中添加成功日志任务
- - '####'
  - 配置成功日志任务
- - '###'
  - 在事件处理器中添加失败日志任务
- - '####'
  - 配置失败日志任务
- - '###'
  - 向 Parent.dtsx 添加应用程序包实例日志记录
- - '###'
  - 查看执行报告数据
- - '###'
  - 在 SSIS 框架应用程序元数据中配置容错
- - '###'
  - 结论
- - '##'
  - 8. Azure-SSIS 集成运行时
- - '###'
  - Azure 入门
- - '###'
  - 预配 Azure Data Factory
- - '###'
  - 配置 Azure 存储
- - '###'
  - 为 SSIS 包文件配置 Azure-SSIS 集成运行时
- - '###'
  - 入门
- - '###'
  - 配置常规设置
- - '####'
  - 节点配置
- - '###'
  - 许可与成本管理
- - '###'
  - 配置部署设置
- - '###'
  - 停止 Azure-SSIS 集成运行时
- - '###'
  - 本章总结
- - '##'
  - 9. 部署一个简单的、自定义、基于文件的 Azure-SSIS 框架
- - '###'
  - 配置 SSISConfig 数据库
- - '###'
  - 部署简单、自定义、基于文件的 Azure-SSIS 框架
- - '###'
  - 预配 Azure 文件共享
- - '###'
  - 上传 SSIS 包
- - '###'
  - 更新 `PackageLocation` 值
- - '###'
  - 构建 SSIS 框架 ADF 执行引擎
- - '####'
  - 检索 SSIS 包列表
- - '###'
  - 配置 Azure SQL 连接并解决常见错误
- - '###'
  - 步骤一：配置连接与测试
- - '###'
  - 步骤二：配置查找活动
- - '###'
  - 步骤三：测试与查看结果
- - '###'
  - 执行检索到的 SSIS 包
- - '####'
  - 添加并配置 ForEach 活动
- - '####'
  - 编辑 ForEach 活动的内容
- - '####'
  - 配置 Execute SSIS 包活动
- - '###'
  - 查看测试运行日志
- - '###'
  - 本章小结
- - '##'
  - 10. ADF 中的框架日志记录
- - '##'
  - 11. ADF 框架中的容错
- - '###'
  - 容错简介
- - '###'
  - 将 ADF 托管标识添加到参与者角色
- - '###'
  - 添加应用程序包容错
- - '####'
  - 关于包失败时使应用程序失败
- - '####'
  - 实现应用程序包容错
- - '####'
  - 检查逻辑
- - '####'
  - 实现容错逻辑
- - '#####'
  - ForEach 活动的默认行为
- - '####'
  - ForEach 活动默认行为及其应用
- - '####'
  - 让我们来测试一下！
- - '###'
  - 结论
