name: Expert Oracle Enterprise Manager 12c
name_cn: Oracle Enterprise Manager 12c 专家指南
slug: expert-oracle-enterprise-manager-12c
toc:
- - '#'
  - Oracle Enterprise Manager 12c 专家指南
- - '##'
  - 目录
- - '#'
  - 第 1 章：Enterprise Manager Cloud Control 12c 架构
- - '##'
  - 架构概览
- - '##'
  - Cloud Control 控制台
- - '##'
  - Oracle Management Agent
- - '##'
  - Oracle Management Service
- - '##'
  - Oracle Management Repository
- - '##'
  - 高可用 EM12c 配置
- - '###'
  - Level 1
- - '###'
  - Level 2
- - '###'
  - Level 3
- - '###'
  - Level 4
- - '##'
  - 软件库
- - '##'
  - 管理工具
- - '###'
  - 命令行工具
- - '###'
  - 库用户
- - '###'
  - 库视图
- - '##'
  - 仓库视图与通信流程
- - '###'
  - 通信流程
- - '###'
  - 协议
- - '###'
  - 端口
- - '###'
  - 防火墙
- - '##'
  - EM12c 中的认证
- - '##'
  - 总结
- - '#'
  - 第 2 章：安装与代理部署
- - '##'
  - 硬件要求与安装准备
- - '###'
  - OMS 的硬件要求
- - '###'
  - 管理仓库的硬件要求
- - '###'
  - 管理代理的硬件要求
- - '##'
  - 安装管理仓库
- - '###'
  - 使用 Oracle-validated RPM 包和 YUM
- - '###'
  - 创建 Oracle 用户和组
- - '###'
  - 设置内核参数
- - '###'
  - 创建所需目录
- - '###'
  - 安装 Oracle 数据库软件
- - '##'
  - Oracle 数据库安装与配置
- - '###'
  - 安装准备
- - '###'
  - 软件安装步骤
- - '###'
  - 创建存储库数据库
- - '##'
  - 安装 Oracle Enterprise Manager 12c
- - '###'
  - 1. 选择“创建一个新的 Enterprise Manager 系统”，然后选择“高级”（参见图 2-28）。点击“下一步”。
- - '###'
  - 2. 对于“安装详情”步骤，如图 2-29 所示，输入中间件主目录位置为`/u01/app/Middleware`，代理基本目录为`/u01/app/agent`，以及您的主机名。然后点击“下一步”。
- - '###'
  - 3. 在“插件部署”步骤，如图 2-30 所示，选择您要配置的管理插件。您也可以在安装 Enterprise Manager 后添加或移除管理插件。点击“下一步”。
- - '###'
  - 4. Oracle Management Service 是 Enterprise Manager 的主要应用程序，它需要一个 WebLogic 应用服务器来运行。在下一步中，如图
    2-31 所示，为 WebLogic 服务器选择一个用户名和密码，并为节点管理器设置一个密码。请妥善保管此信息。在排查与 WebLogic 相关的问题时可能需要它。点击“下一步”。
- - '###'
  - 5. 输入仓库数据库的连接信息并选择部署规模（参见图 2-32）。安装程序会根据部署规模检查数据库设置。点击“下一步”。
- - '###'
  - 6. 安装程序将在仓库数据库中创建所需的数据库用户和表空间。对于“仓库配置详情”步骤，如图 2-33 所示，输入`SYSMAN`用户的密码，根据需要修改目录位置，并输入一个注册密码，该密码将用于保护代理通信的安全。点击“下一步”。
- - '###'
  - 7. 检查将分配给 Oracle Enterprise Manager 的端口（参见图 2-34）。您可以修改它们，但请记住端口号必须大于 1024 且小于
    65535。
- - '###'
  - 8. 检查配置（参见图 2-35）。对配置满意后，点击“安装”开始安装。
- - '###'
  - 9. 安装结束时，您需要执行一些配置脚本。以 ROOT 身份登录到服务器（在另一个终端会话中）并运行脚本（参见图 2-36）。然后点击“确定”完成安装。
- - '###'
  - 10. 检查信息，如图 2-37 所示，然后点击“关闭”以完成 Oracle Enterprise Manager Cloud Control 12c 的安装。
- - '###'
  - 11. 现在您可以登录到 Enterprise Manager Cloud Control，如图 2-38 所示。
- - '##'
  - 部署管理代理
- - '###'
  - 使用“添加主机目标”向导
- - '###'
  - 使用 RPM
- - '###'
  - 使用 AgentPull 脚本
- - '###'
  - 使用 `agentDeploy` 脚本
- - '##'
  - 总结
- - '#'
  - 第 3 章：OMS 与资料档案库的管理
- - '##'
  - Oracle Management Agent
- - '###'
  - 通过控制台管理代理
- - '###'
  - 同时控制多个代理
- - '###'
  - 使用代理的主页
- - '###'
  - 使用 EM 代理浏览器
- - '###'
  - 通过命令行管理代理
- - '###'
  - 代理日志和跟踪文件
- - '##'
  - Oracle Management Service
- - '###'
  - 通过控制台管理 OMS
- - '###'
  - 通过命令行管理 OMS
- - '###'
  - OMS 目录结构
- - '###'
  - OMS 日志与跟踪文件
- - '##'
  - Oracle Management Repository
- - '###'
  - 通过控制台管理资料档案库
- - '###'
  - 通过命令行管理资料档案库
- - '###'
  - 资料档案库视图
- - '###'
  - 故障排除
- - '##'
  - 总结
- - '#'
  - 第 4 章：与 EM12c 控制台交互
- - '##'
  - EM 简史
- - '##'
  - 技术栈
- - '##'
  - 界面
- - '##'
  - Cloud Control
- - '###'
  - Cloud Control 菜单栏
- - '###'
  - 安全管理
- - '###'
  - 添加管理员
- - '###'
  - 创建管理员角色与配置支持集成
- - '###'
  - 代理配置
- - '###'
  - 通知
- - '###'
  - 管理包访问
- - '##'
  - 导航菜单栏
- - '###'
  - Enterprise 菜单
- - '###'
  - Targets 菜单
- - '###'
  - Favorites 菜单
- - '###'
  - History 菜单
- - '###'
  - 搜索框
- - '##'
  - 目标管理菜单栏
- - '###'
  - 监控设置
- - '###'
  - 诊断
- - '###'
  - 目标状态与通知控制
- - '###'
  - 日志审查
- - '###'
  - 目标设置
- - '###'
  - 自定义
- - '##'
  - 总结
- - '#'
  - 第 5 章：云生命周期管理
- - '##'
  - 什么是云计算？
- - '##'
  - 基本特征
- - '##'
  - 服务模型
- - '##'
  - 部署模型
- - '##'
  - 企业私有云
- - '##'
  - 完整的云生命周期管理
- - '###'
  - 云规划
- - '###'
  - 云设置
- - '###'
  - 云构建
- - '###'
  - 云中测试
- - '###'
  - 云部署
- - '###'
  - 云监控
- - '###'
  - 云管理
- - '###'
  - 计量与费用分摊
- - '###'
  - 云优化
- - '###'
  - 整合规划器
- - '##'
  - 总结
- - '#'
  - 第 6 章：软件库、修补与配置
- - '##'
  - 软件库
- - '###'
  - 配置软件库
- - '###'
  - 使用软件库实体
- - '###'
  - 通过软件库主页执行任务
- - '###'
  - 维护软件库
- - '##'
  - 补丁管理
- - '###'
  - 配置“我的 Oracle 支持”
- - '###'
  - 补丁计划
- - '###'
  - 创建补丁计划
- - '###'
  - 计划模板
- - '###'
  - 已保存的补丁
- - '###'
  - 其他补丁操作流程
- - '###'
  - 补丁操作所需的角色
- - '##'
  - 配置
- - '###'
  - 数据库配置概述
- - '###'
  - 支持的目标和部署过程
- - '###'
  - 数据库配置设置
- - '###'
  - 创建配置文件
- - '##'
  - 总结
- - '#'
  - 第 7 章：管理与监控最佳实践
- - '##'
  - 指标阈值
- - '##'
  - 监控模板
- - '##'
  - 管理组
- - '###'
  - 规划层级结构
- - '###'
  - 实施层级结构
- - '###'
  - 加入管理组
- - '###'
  - 模板集合
- - '###'
  - 同步计划
- - '##'
  - 事件管理建议
- - '###'
  - 事件、incident 和问题
- - '###'
  - 规则和规则集
- - '###'
  - 指标收集错误
- - '##'
  - 总结
- - '#'
  - 第 8 章：管理工程系统
- - '##'
  - 工程系统类型
- - '##'
  - 工程系统生命周期
- - '##'
  - 支持的硬件和软件
- - '##'
  - 规划与设置阶段
- - '###'
  - 安装管理代理
- - '###'
  - 启动自动发现
- - '###'
  - 指定组件凭据
- - '###'
  - 审查配置并完成设置
- - '##'
  - 测试阶段
- - '###'
  - 确定要迁移的应用程序
- - '###'
  - 创建测试环境
- - '###'
  - 验证应用程序性能
- - '##'
  - 管理阶段
- - '###'
  - I/O 资源管理器
- - '##'
  - 维护阶段
- - '###'
  - 合规框架
- - '###'
  - 配置管理
- - '###'
  - 缺陷诊断
- - '###'
  - 自动化补丁管理
- - '##'
  - 总结
- - '#'
  - 第 9 章：性能页面与 ASH 分析
- - '##'
  - 许可要求
- - '##'
  - 主机性能
- - '###'
  - 性能主页
- - '###'
  - 吞吐量
- - '###'
  - I/O
- - '###'
  - 并行执行
- - '###'
  - 服务
- - '##'
  - 活动排名
- - '###'
  - 顶级 SQL 窗格
- - '###'
  - SQL 详情页面
- - '###'
  - SQL 活动
- - '###'
  - 顶级会话窗格
- - '##'
  - ASH 分析
- - '###'
  - 负载图
- - '##'
  - 相关工具与功能
- - '###'
  - SQL 监控
- - '###'
  - SQL 性能
- - '###'
  - SQL 性能分析器
- - '###'
  - SQL 访问顾问
- - '###'
  - SQL 调优集
- - '###'
  - SQL 计划控制
- - '###'
  - 优化器统计信息
- - '###'
  - Cloud Control SQL 历史记录
- - '###'
  - 顾问中心
- - '###'
  - 应急监控
- - '###'
  - 实时 ADDM
- - '###'
  - ADDM 比较报告
- - '##'
  - 小结
- - '#'
  - 第 10 章：指标扩展与管理插件
- - '##'
  - 指标扩展
- - '###'
  - 你的第一个指标扩展
- - '###'
  - SQL 适配器
- - '###'
  - OS 命令适配器
- - '###'
  - SNMP 适配器
- - '###'
  - JMX 适配器
- - '###'
  - 适配器与目标类型
- - '##'
  - 管理插件
- - '###'
  - 可扩展性框架入门
- - '###'
  - 基本插件目标类型与指标
- - '###'
  - 目标类型元数据
- - '###'
  - 默认收集元数据
- - '###'
  - 打包插件
- - '###'
  - Agentfs 指标浏览器
- - '###'
  - 指标扩展内部机制
- - '##'
  - 小结
- - '#'
  - 第 11 章：Enterprise Manager 作业
- - '##'
  - 为何使用 EM12c 作业
- - '##'
  - Enterprise Manager 作业架构
- - '###'
  - EM 作业系统组件
- - '###'
  - EM 作业服务
- - '##'
  - 监控配置
- - '##'
  - 作业活动页面
- - '##'
  - Enterprise Manager 作业库
- - '##'
  - EM 作业模式
- - '###'
  - 创建作业
- - '###'
  - 作业类型
- - '###'
  - 有效监控与作业状态
- - '###'
  - 权限
- - '##'
  - EM 作业服务图表与指标
- - '###'
  - 性能指标
- - '###'
  - 使用指标
- - '##'
  - 将脚本迁移到 EM 作业系统
- - '##'
  - 管理 EM12c 作业
- - '###'
  - 查看作业结果
- - '###'
  - 从活动视图编辑作业
- - '###'
  - 停止正在运行的作业
- - '###'
  - 暂停作业
- - '###'
  - 复制到库
- - '###'
  - 删除作业
- - '###'
  - 管理管理器
- - '##'
  - 排查 EM12c 作业系统故障
- - '###'
  - 执行安装
- - '###'
  - 在 EM12c 中使用 EMDIAG
- - '###'
  - 停用期与 EM12c 作业影响
- - '###'
  - 通过 EM 作业控制多个管理代理
- - '##'
  - 小结
- - '#'
  - 第 12 章：事件管理
- - '##'
  - 事件管理器术语
- - '###'
  - 事件与意外事件
- - '###'
  - 问题
- - '###'
  - 事件规则集
- - '##'
  - 事件管理器用户界面
- - '###'
  - 创建事件规则
- - '###'
  - 查看事件详情
- - '###'
  - 创建自定义视图
- - '###'
  - 规则与通知的优先级
- - '###'
  - 向后兼容性
- - '##'
  - 事件管理器指南
- - '###'
  - 管理事件与意外事件
- - '###'
  - 规则集建议
- - '##'
  - 小结
- - '#'
  - 第 13 章：高可用性、备份与恢复
- - '##'
  - 高可用性
- - '###'
  - Oracle 管理代理
- - '###'
  - 管理资料库
- - '###'
  - 管理服务
- - '###'
  - 软件库
- - '##'
  - 备份
- - '###'
  - 资料库备份
- - '###'
  - Oracle 管理服务备份
- - '###'
  - 管理代理备份
- - '##'
  - 恢复
- - '###'
  - 资料库恢复
- - '###'
  - Oracle 管理服务恢复
- - '###'
  - 管理代理恢复
- - '##'
  - 切换与故障转移
- - '##'
  - 小结
- - '#'
  - 索引
- - '#'
  - 关于作者
