name: Refactoring Legacy T-SQL for Improved Performance
name_cn: 重构遗留 T-SQL 以提高性能
slug: refactoring-legacy-t-sql-for-improved-performance
toc:
- - '#'
  - 引言
- - '##'
  - 一个令人唏嘘的故事
- - '###'
  - 恭喜你！
- - '##'
  - 本书宗旨
- - '##'
  - 本书不包含什么
- - '##'
  - 工具
- - '##'
  - 无关紧要（多数情况下）的细节
- - '##'
  - 开始吧！
- - '##'
  - 致谢
- - '###'
  - 关于作者与技术评审
- - '###'
  - 关于作者
- - '###'
  - 关于技术评审
- - '#'
  - 第一部分 万物皆慢
- - '##'
  - 1. T-SQL 初步诊断
- - '###'
  - 情况严重性
- - '###'
  - 相对工作量
- - '###'
  - 问题领域
- - '####'
  - STATISTICS IO 和 STATISTICS TIME
- - '####'
  - 查询窗口设置
- - '####'
  - 代码测试
- - '###'
  - 触发器导致的性能问题
- - '####'
  - 执行计划
- - '###'
  - 统计信息
- - '###'
  - 尽可能进行故障排查
- - '####'
  - 是否存在索引？
- - '##'
  - 1. 索引
- - '###'
  - 变更的风险级别
- - '###'
  - 万能答案…？
- - '###'
  - 索引之外的初步评估
- - '####'
  - 如果可能，查询应在键值上连接
- - '####'
  - SARGability（可搜索参数性）
- - '###'
  - 总结
- - '#'
  - 2. 文档
- - '##'
  - 整合现有文档
- - '###'
  - 清单 2-1：DailySummaryReportPerMonth 存储过程代码
- - '###'
  - 功能文档
- - '###'
  - 统计信息与执行计划
- - '###'
  - 编码（反）模式
- - '####'
  - 对每个数据库表的调用次数
- - '####'
  - 数据类型不匹配
- - '#####'
  - 数据截断
- - '#####'
  - 隐式转换
- - '#####'
  - 字段宽度
- - '####'
  - 子查询及其位置
- - '###'
  - 计算
- - '###'
  - 临时表和/或表变量
- - '####'
  - 循环与/或游标
- - '####'
  - 公用表表达式
- - '####'
  - 连接类型
- - '####'
  - LIKE, NOT LIKE, and NOT IN
- - '####'
  - DISTINCT, TOP, and Other Sorting Operations
- - '####'
  - Calls to Other User-Defined SQL Objects
- - '####'
  - WHERE 子句中的原生 SQL Server 函数
- - '###'
  - 索引
- - '####'
  - 回到运行时数据
- - '###'
  - 总结
- - '####'
  - 整理我们的文档
- - '##'
  - 'DailySummaryReportPerMonth: 文档'
- - '###'
  - 截至 2019.06.02 的代码
- - '###'
  - SQL 存储过程文档：每日月度汇总报告
- - '####'
  - 存储过程代码
- - '####'
  - 功能需求
- - '####'
  - 数据调用
- - '####'
  - 编码（反）模式
- - '#####'
  - 数据类型匹配
- - '#####'
  - 子查询
- - '#####'
  - 计算
- - '######'
  - 临时表和/或表变量
- - '######'
  - 循环/游标
- - '######'
  - 公用表表达式 (CTEs)
- - '######'
  - 连接类型
- - '######'
  - LIKE, NOT LIKE 和 NOT IN
- - '######'
  - 排序操作
- - '######'
  - 对其他用户定义 SQL 对象的调用
- - '######'
  - WHERE 子句中的原生 SQL 函数
- - '######'
  - 索引
- - '#'
  - 第二部分：数据库结构
- - '##'
  - 3. 数据库表
- - '###'
  - 计算列
- - '###'
  - 反规范化数据
- - '###'
  - 数据类型与字段大小
- - '###'
  - 已弃用的数据类型
- - '###'
  - 数据量有多少？
- - '###'
  - 数据偏斜/基数
- - '###'
  - 约束
- - '###'
  - 修改表定义
- - '####'
  - 清单 3-6
- - '####'
  - 清单 3-7
- - '####'
  - 清单 3-8
- - '####'
  - 清单 3-9
- - '###'
  - 概要
- - '##'
  - 4. 数据库视图
- - '###'
  - 嵌套
- - '####'
  - 代码清单 4-4
- - '###'
  - 多次表调用
- - '###'
  - 文档编制的附加要点
- - '###'
  - 了解你的数据
- - '###'
  - 功能性检查
- - '####'
  - 代码清单 4-10
- - '#####'
  - 图 4-1
- - '####'
  - 代码清单 4-11
- - '#####'
  - 图 4-2
- - '###'
  - 我们解决了哪些问题？
- - '###'
  - 筛选
- - '###'
  - 通过视图更新数据
- - '###'
  - 其他限制
- - '###'
  - 为什么要使用视图？
- - '###'
  - 总结
- - '#'
  - 第三部分 CRUD 对象
- - '##'
  - 5. 触发器
- - '###'
  - 基于视图的触发器
- - '###'
  - 我们应该在什么时候使用触发器？
- - '###'
  - 触发器的常见问题
- - '###'
  - 触发器递归
- - '###'
  - 触发器与多记录变更
- - '###'
  - 检测值是否发生变化
- - '####'
  - 代码清单 5-17 最终修订版 iu_Users_DownVotes 触发器
- - '###'
  - 限制数据库必须完成的工作
- - '####'
  - 代码清单 5-18 i_LinkTypes_doNothing 的创建语句
- - '####'
  - 代码清单 5-19 u_LinkTypes_doNothing 触发器的创建语句
- - '###'
  - 总结
- - '##'
  - 6. 存储过程
- - '###'
  - 临时表 vs. 表变量
- - '####'
  - 临时表
- - '####'
  - 表变量
- - '###'
  - 循环
- - '###'
  - 功能审查
- - '###'
  - 从最简单的数据开始
- - '###'
  - 以小的、易于测试的增量添加更多数据
- - '###'
  - 窗口函数
- - '###'
  - 避免行或数据重复
- - '####'
  - 清单 6-6
- - '####'
  - 表 6-4
- - '####'
  - 清单 6-7
- - '###'
  - 使用聚合和 ROW_NUMBER() 进行带筛选的查询
- - '####'
  - 表 6-5
- - '#####'
  - 清单 6-7 中查询的输出
- - '###'
  - 我们是如何得到这个结果的？
- - '###'
  - 但是性能如何呢？
- - '####'
  - 清单 6-9
- - '####'
  - 表 6-7
- - '###'
  - SQL 查询分析与结果验证
- - '####'
  - 表 6-8
- - '####'
  - 表 6-9
- - '###'
  - 原始报告包含而我们仍缺失哪些数据？
- - '###'
  - 没有缺失行——计数表！
- - '###'
  - 我们还应该注意什么？
- - '##'
  - 'GetUserInfoByName: 文档'
- - '###'
  - 截至 2019.07.07 的代码
- - '###'
  - 功能要求
- - '###'
  - 数据调用
- - '###'
  - 可能的危险信号
- - '####'
  - 数据类型匹配
- - '####'
  - 子查询
- - '####'
  - 计算
- - '####'
  - 临时表和/或表变量
- - '####'
  - 循环/游标
- - '####'
  - 公共表表达式
- - '####'
  - 连接类型
- - '####'
  - IN/NOT IN/LIKE
- - '####'
  - 排序操作
- - '####'
  - 对其他用户定义 SQL 对象的调用
- - '####'
  - WHERE 子句中的原生 SQL 函数
- - '###'
  - 此次调用的运行统计信息
- - '###'
  - 函数和 STATISTICS IO 输出
- - '###'
  - 制定行动计划
- - '####'
  - 消除子查询吧！
- - '####'
  - 移除函数！
- - '####'
  - 移除 LIKE 语句中开头的 %
- - '###'
  - 总结
- - '##'
  - 7. 函数
- - '###'
  - 标量函数
- - '###'
  - 查看函数引起的 `STATISTICS IO`
- - '###'
  - 性能分析
- - '###'
  - WHERE 子句中的标量值函数
- - '###'
  - SQL Server 原生函数
- - '###'
  - 令人头疼的“庞大业务逻辑”函数
- - '####'
  - 使用 `OUTER APPLY` 来联接聚合数据
- - '####'
  - 随着返回行数增加的指标
- - '###'
  - 表值函数 (TVF)
- - '#'
  - 第四部分：糟粕与败笔
- - '##'
  - 总结
- - '##'
  - 8. 代理作业
- - '###'
  - 代理作业应该做什么
- - '####'
  - 好作业！
- - '####'
  - 我应该在何时运行作业？
- - '#####'
  - 了解你的环境……定期地
- - '#####'
  - 了解你的作业及其背后的需求……定期地
- - '###'
  - 代理作业的常见问题
- - '###'
  - 作业重叠
- - '###'
  - 总结
- - '##'
  - 9. 外部影响
- - '###'
  - 链接服务器
- - '####'
  - 安全性
- - '####'
  - 跨数据库表的查询
- - '####'
  - 网络 I/O
- - '####'
  - 我们如何解决这个问题？
- - '###'
  - 应用程序中的 SQL 代码调用
- - '####'
  - 问题是什么？
- - '####'
  - ORM 在 .NET 端过滤数据
- - '####'
  - ORM RBAR（逐行操作）
- - '####'
  - 似曾相识
- - '####'
  - 猜猜怎么着？使用存储过程！
- - '###'
  - 动态 SQL
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - A, B, C
- - '###'
  - D, E
- - '###'
  - F, G, H, I, J, K
- - '###'
  - L
- - '###'
  - M, N
- - '###'
  - O, P
- - '###'
  - Q, R
- - '###'
  - S
- - '###'
  - T, U
- - '###'
  - V
- - '###'
  - W, X, Y, Z
