name: Pro SQL Server 2012 Practices
name_cn: SQL Server 2012 高级实践
slug: pro-sql-server-2012-practices
toc:
- - '#'
  - 目录
- - '##'
  - 第 1 章：成为开发者的最佳伙伴
- - '###'
  - 我使用 SQL Server 与开发者共事的经验
- - '###'
  - 调和组织内不同的观点
- - '###'
  - 准备与开发者合作实施系统更改
- - '###'
  - 步骤 1：绘制你的环境图
- - '###'
  - 步骤 2：描述新环境
- - '###'
  - 步骤 3：创建清晰的文档
- - '###'
  - 步骤 4：创建系统管理流程
- - '###'
  - 步骤 5：创建良好的报告
- - '###'
  - SQL Server 版本
- - '###'
  - 功能支持
- - '###'
  - 版本
- - '###'
  - 命名标准
- - '###'
  - 补丁
- - '###'
  - 权限
- - '###'
  - 确保版本兼容性
- - '###'
  - 设定限制
- - '##'
  - 第 2 章：正确设计：为性能而设计数据库
- - '###'
  - 需求
- - '###'
  - 表结构
- - '####'
  - 历史速览
- - '####'
  - 为何规范化的数据库优于非规范化的数据库
- - '####'
  - 物理模型选择
- - '###'
  - 一段非常简短的历史渊源
- - '###'
  - 为何普通数据库优于非凡的数据库
- - '###'
  - 数据库规范化指南
- - '####'
  - 引言
- - '####'
  - （半）形式化定义
- - '####'
  - 实际应用
- - '###'
  - 表格与列的设计原则
- - '####'
  - 列
- - '####'
  - 表/行唯一性
- - '####'
  - 列仅依赖于整个键
- - '###'
  - 检测和纠正数据库中的依赖关系
- - '###'
  - 设计良好的表：更新规则
- - '###'
  - 实例：图书信息表
- - '###'
  - 纠正图书信息表的依赖问题
- - '###'
  - 其他依赖关系和总结数据
- - '###'
  - 键始终代表单个表达式
- - '###'
  - 键的单一性测试
- - '###'
  - 三实体依赖关系建模问题
- - '###'
  - 物理模型选择
- - '####'
  - 数据类型
- - '####'
  - 约束
- - '####'
  - 索引
- - '###'
  - 使用域表约束值
- - '###'
  - 索引设计
- - '###'
  - 设计测试
- - '###'
  - 结论
- - '##'
  - 第 3 章：隐藏的性能陷阱
- - '###'
  - 谓词
- - '###'
  - 一个具体的查询示例
- - '###'
  - 比较执行统计信息
- - '###'
  - 索引架构与 Seek 操作
- - '###'
  - 根本原因：索引列顺序
- - '###'
  - 可视化差异
- - '####'
  - 图 3-7. 带有 OrderDate 列谓词的索引扫描
- - '####'
  - 图 3-8. 带有查找和键查找的执行计划
- - '####'
  - 图 3-9. Subtotal 索引上的索引查找，未提及 OrderDate 谓词
- - '####'
  - 图 3-10. 带有谓词的键查找
- - '####'
  - 图 3-11. 带有函数导致谓词的索引查找
- - '###'
  - 为什么索引查找的效率存在差异？
- - '###'
  - 如何发现和解决索引查找效率问题？
- - '###'
  - 索引查找不总是高效的
- - '###'
  - 残差
- - '###'
  - 溢出
- - '###'
  - 内存授权低估与 TempDB 配置
- - '###'
  - 结论
- - '##'
  - 第 4 章：动态管理视图
- - '###'
  - 理解基础
- - '###'
  - 命名约定
- - '###'
  - 相关视图组
- - '###'
  - Varbinary 哈希值
- - '###'
  - 查询 `sql_handle` 的多种方法
- - '###'
  - 常用性能调优查询
- - '####'
  - 检索连接信息
- - '####'
  - 显示当前正在执行的请求
- - '####'
  - 阻塞会话等待资源
- - '###'
  - 锁升级
- - '###'
  - 查找性能不佳的 SQL
- - '###'
  - 利用 DMV 性能脚本的威力
- - '###'
  - 术语差异
- - '###'
  - 优化性能
- - '###'
  - 检查性能统计信息
- - '###'
  - 最高执行次数
- - '###'
  - 物理读取
- - '###'
  - 物理性能查询
- - '####'
  - 定位缺失的索引
- - '###'
  - 索引管理与性能调优
- - '####'
  - 重要建议
- - '####'
  - 缺失索引相关的 DMV 视图
- - '#####'
  - '`dm_db_missing_index_groups`'
- - '#####'
  - '`dm_db_missing_index_group_stats`'
- - '#####'
  - '`dm_db_missing_index_details`'
- - '####'
  - 识别缺失索引以提升性能
- - '####'
  - 索引使用情况分析
- - '####'
  - 识别并删除未使用的索引
- - '###'
  - 分区统计信息
- - '###'
  - 系统性能调优查询
- - '####'
  - 关于系统性能 DMV 你需要知道的
- - '####'
  - 会话和完成百分比
- - '###'
  - 结论
- - '##'
  - 第 5 章：从 SQL 跟踪到扩展事件
- - '###'
  - SQL 跟踪
- - '###'
  - 技术概述
- - '###'
  - 实现细节
- - '###'
  - 管理监控
- - '###'
  - 缓冲机制
- - '###'
  - 行集提供程序
- - '###'
  - SQL Server Profiler
- - '###'
  - .NET SMO 对象
- - '###'
  - SMO 对象模型
- - '###'
  - 跟踪文件提供程序
- - '###'
  - 表 5-1. SQL 跟踪扩展存储过程、函数及其功能描述
- - '###'
  - 事件通知
- - '####'
  - 图 5-6. SQL Server Service Broker 基本架构
- - '###'
  - 事件通知类别
- - '###'
  - 与 SQL Trace 的区别
- - '###'
  - 使用目录视图进行监控
- - '###'
  - 实现与用例
- - '####'
  - 示例 1：即时死锁通知
- - '####'
  - 示例 2：订阅 DDL 事件组
- - '###'
  - 事件
- - '###'
  - 谓词
- - '###'
  - 操作
- - '###'
  - 类型和映射
- - '###'
  - 目标
- - '###'
  - 环形缓冲区
- - '###'
  - 事件文件
- - '###'
  - Windows 事件追踪（ETW）目标
- - '###'
  - 会话
- - '###'
  - 会话配置选项
- - '###'
  - 对象元数据
- - '###'
  - 目标中的数据格式
- - '###'
  - XML 数据规范化与非规范化查询示例
- - '###'
  - 使用扩展事件 (Extended Events) 进行跟踪
- - '###'
  - 内置健康会话 (Built-in Health Session)
- - '###'
  - 问题与扩展事件健康监视
- - '###'
  - 扩展事件 .NET 提供程序
- - '###'
  - 扩展事件 UI
- - '###'
  - 会话创建 UI
- - '###'
  - 会话创建用户界面
- - '####'
  - 图 5-10. 扩展事件会话创建页面：常规
- - '####'
  - 图 5-11. 扩展事件会话创建页面：事件 - 第 1 部分
- - '####'
  - 图 5-12. 扩展事件会话创建页面：事件 - 第 2 部分
- - '####'
  - 图 5-13. 扩展事件会话创建页面：数据存储
- - '###'
  - 扩展事件探查器 UI
- - '###'
  - 结论
- - '##'
  - 第 6 章：实用工具数据库
- - '###'
  - 从清单开始
- - '####'
  - 每日检查清单项目
- - '####'
  - 长期检查清单项目
- - '####'
  - 实用数据库布局
- - '###'
  - 数据分类
- - '####'
  - 组 1：用于分析历史内容的数据
- - '####'
  - 组 2：用于检查当前健康状况的数据
- - '####'
  - 组 3：存档数据
- - '###'
  - 使用模式
- - '###'
  - 使用数据引用完整性
- - '###'
  - 创建实用数据库
- - '###'
  - 表结构
- - '####'
  - 历史数据表
- - '####'
  - 当前健康表
- - '####'
  - 归档表
- - '###'
  - 数据收集
- - '###'
  - 系统表
- - '###'
  - 扩展存储过程
- - '###'
  - CLR
- - '###'
  - DMV
- - '###'
  - 存储
- - '####'
  - 数据库文件大小
- - '####'
  - 寻找空闲空间量
- - '###'
  - 实用程序数据库
- - '####'
  - 跟踪数据库健康状况
- - '###'
  - 处理器
- - '####'
  - 启用处理器利用率收集
- - '###'
  - 错误日志
- - '###'
  - 索引
- - '####'
  - 填充 Index_Fragmentation 表
- - '###'
  - 存储过程性能
- - '###'
  - 失败的作业
- - '###'
  - 信息的可见性
- - '###'
  - Reporting Services
- - '###'
  - SQL Server 高可用性与监控
- - '###'
  - SQL Server Reporting Services
- - '###'
  - 数据库镜像
- - '###'
  - AlwaysOn
- - '###'
  - 管理关键业务指标
- - '###'
  - 数据使用
- - '###'
  - 自动化数据收集
- - '###'
  - 调度数据收集
- - '###'
  - 总结
- - '##'
  - 第 7 章：跳出思维定式进行索引优化
- - '###'
  - 环境的“泡沫”
- - '###'
  - 识别缺失索引
- - '####'
  - 表 7-1. 缺失索引属性
- - '####'
  - 动态管理对象
- - '###'
  - 清单 7-1：用于查询缺失索引 DMO 的语句
- - '###'
  - 表 7-2：缺失索引查询列说明
- - '###'
  - 清单 7-2：查询 sys.dm_db_missing_index_columns 的语句
- - '###'
  - 图 7-1：sys.dm_db_missing_index_columns 的示例输出
- - '###'
  - 清单 7-3：等值列场景
- - '###'
  - 图 7-2：等值列场景的缺失索引建议
- - '###'
  - 清单 7-4：列唯一性检查
- - '###'
  - 不等式列场景分析
- - '####'
  - 清单 7-5. 不等式列场景
- - '###'
  - 计划缓存
- - '####'
  - 清单 7-6. 从计划缓存中查询缺失索引
- - '###'
  - 针对工作负载的索引调优
- - '###'
  - 收集工作负载
- - '####'
  - SQL 跟踪
- - '####'
  - 扩展事件
- - '###'
  - 图 7-12. 扩展事件向导 - 选择模板屏幕
- - '###'
  - 图 7-13. 扩展事件向导 - 选择要捕获的事件屏幕
- - '###'
  - 图 7-14. 扩展事件向导 - 捕获全局字段屏幕
- - '###'
  - 图 7-15. 扩展事件向导 - 设置会话事件筛选器屏幕
- - '###'
  - 图 7-16. 扩展事件向导 - 指定会话数据存储屏幕
- - '###'
  - 清单 7-9. 创建扩展事件会话
- - '###'
  - 清单 7-10. 启动和停止会话
- - '###'
  - 清单 7-11. 将扩展事件会话数据插入 dbo.indexing_workload
- - '###'
  - 示例工作负载
- - '###'
  - 准备数据库
- - '###'
  - 执行分析
- - '###'
  - 业务的“泡沫”
- - '###'
  - 索引的业务用途
- - '###'
  - 数据完整性
- - '###'
  - 总结
- - '##'
  - 第 8 章：版本发布管理
- - '###'
  - 我的版本发布管理流程
- - '###'
  - 收到变更请求
- - '###'
  - 发布流程概览
- - '###'
  - 考虑因素
- - '####'
  - 目标
- - '#####'
  - 降低风险
- - '#####'
  - 控制变更
- - '#####'
  - 成功执行变更
- - '#####'
  - 遵循最佳实践
- - '###'
  - 最佳实践的应用
- - '####'
  - 架构/设计变更
- - '####'
  - 审查变更
- - '###'
  - 环境
- - '####'
  - 图 8-2. 可能的数据库环境
- - '###'
  - 发布流程
- - '###'
  - 参与人员
- - '###'
  - 版本控制
- - '###'
  - 回滚流程
- - '###'
  - 文档
- - '###'
  - 发布说明
- - '####'
  - 发布名称
- - '####'
  - 发布计划
- - '####'
  - 发布到各个环境的日期
- - '####'
  - 初始发布计划请求
- - '####'
  - 接收并审查答案
- - '####'
  - 审查代码
- - '###'
  - 审查发布
- - '###'
  - 交接
- - '###'
  - 发布计划已创建
- - '###'
  - 发布计划审查
- - '###'
  - 回滚程序
- - '###'
  - 发布计划测试
- - '###'
  - 执行发布
- - '###'
  - 发布计划模板与发布计划
- - '###'
  - 通用发布信息
- - '###'
  - 问题与答案
- - '###'
  - 发布步骤
- - '###'
  - 文档仓库
- - '###'
  - 结论
- - '##'
  - 第 9 章：合规性与审计
- - '###'
  - 合规性
- - '####'
  - 萨班斯-奥克斯利法案
- - '####'
  - 健康保险流通与责任法案
- - '###'
  - SQL Server 2012 中的新增审计功能
- - '####'
  - 标准版的服务器级别审计
- - '####'
  - 审计日志失败选项
- - '####'
  - 最大日志文件滚动个数
- - '####'
  - 用户定义的审计
- - '####'
  - 审计筛选
- - '###'
  - 审核
- - '###'
  - 服务器审核
- - '####'
  - 图 9-1
- - '###'
  - 服务器审核规范
- - '####'
  - 注意
- - '####'
  - 图 9-2
- - '###'
  - 数据库审核规范
- - '####'
  - 图 9-3
- - '###'
  - SQL Server 审计配置与日志查询
- - '###'
  - 查询审计文件
- - '###'
  - 专业提示：针对审计事件设置警报
- - '###'
  - 总结
- - '##'
  - 第 10 章：自动化管理
- - '###'
  - 自动化工具
- - '####'
  - 性能监视器
- - '####'
  - 动态管理视图
- - '###'
  - SQL Server 监控与自动化管理
- - '####'
  - 清单 10-2. 查看会话所用 CPU 时间的查询
- - '####'
  - 清单 10-3. 查看按读取次数排序的会话的查询
- - '###'
  - SQL Server Agent
- - '####'
  - 注意
- - '###'
  - 操作员
- - '####'
  - 图 10-2. 配置操作员
- - '###'
  - 作业
- - '####'
  - SQL Server 代理
- - '#####'
  - 清单 10-4. 创建 DBAInfo 数据库
- - '#####'
  - 清单 10-5. 创建用于保存监控信息的表
- - '#####'
  - 图 10-3. SQL Server 代理作业的常规属性
- - '####'
  - 作业步骤
- - '#####'
  - 清单 10-6. 将 DMV 查询结果插入表中的查询
- - '###'
  - DMV 收集作业 SQL 代码
- - '###'
  - 作业步骤选项
- - '###'
  - 计划
- - '###'
  - 通知
- - '###'
  - 警报
- - '####'
  - 错误和严重性级别
- - '####'
  - 性能条件
- - '#####'
  - 图 10-9. SQL Server 性能条件警报
- - '####'
  - WMI 事件
- - '#####'
  - 图 10-10. WMI 事件警报
- - '#####'
  - 图 10-11. 此 WMI 事件警报的响应是执行一个 Agent 作业
- - '###'
  - 响应
- - '####'
  - 图 10-12. 警报的响应选项
- - '###'
  - 选项
- - '####'
  - 图 10-13. 警报的附加选项
- - '###'
  - 维护计划
- - '###'
  - 任务
- - '####'
  - 表 10-1. 可用的维护计划任务
- - '###'
  - 更新统计信息
- - '###'
  - 创建维护计划
- - '####'
  - 其他选项
- - '####'
  - 可能的陷阱
- - '###'
  - SQL Server Integration Services
- - '###'
  - PowerShell
- - '####'
  - 启动 PowerShell
- - '####'
  - 使用 PowerShell
- - '####'
  - 自动化 PowerShell
- - '###'
  - 自动化什么
- - '###'
  - 监控
- - '####'
  - Windows 事件查看器
- - '###'
  - SQL Server 日志管理与自动化运维
- - '###'
  - 日志概述
- - '###'
  - SQL Server 错误日志
- - '###'
  - SQL Server Agent 日志
- - '####'
  - 失败作业
- - '####'
  - 长时间运行的作业
- - '###'
  - 磁盘空间管理
- - '####'
  - 驱动器空间
- - '####'
  - 磁盘空间
- - '####'
  - 数据库文件限制
- - '###'
  - 备份与恢复
- - '####'
  - 备份
- - '###'
  - SQL Server 自动化管理
- - '###'
  - 备份策略
- - '####'
  - 恢复模型
- - '####'
  - 备份类型与计划
- - '####'
  - 备份位置
- - '###'
  - 还原测试
- - '###'
  - 数据库完整性
- - '###'
  - 索引维护
- - '###'
  - 统计维护
- - '###'
  - 结论
- - '##'
  - 第 11 章：SQL Server 数据移动的流体动力学
- - '###'
  - 为什么需要复制数据？
- - '####'
  - 场景 1：全球性组织
- - '####'
  - 场景 2：高容量报告需求
- - '###'
  - SQL Server 解决方案
- - '###'
  - 复制
- - '####'
  - 快照
- - '####'
  - 事务
- - '####'
  - 点对点
- - '####'
  - 合并
- - '###'
  - 合并复制
- - '###'
  - 复制示例
- - '###'
  - 日志传送
- - '###'
  - 场景分析
- - '####'
  - 场景 1：全球化组织
- - '####'
  - 场景 2：高容量报告需求
- - '####'
  - 场景 3：夜间处理作业
- - '####'
  - 场景 4：硬件故障
- - '###'
  - 数据库镜像
- - '###'
  - AlwaysOn
- - '####'
  - 可用性组
- - '####'
  - 辅助副本
- - '####'
  - 将可用性组应用于场景
- - '####'
  - 故障转移群集
- - '###'
  - 使用 SQL Server Integration Services 自定义 ETL
- - '###'
  - 大容量复制过程
- - '###'
  - 选择正确的部署方案
- - '####'
  - 表
- - '####'
  - 高可用性与灾难恢复技术比较
- - '####'
  - 保持数据一致性
- - '###'
  - SQL Server 数据移动的监控与恢复
- - '####'
  - 复制的监控与恢复选项包括：
- - '####'
  - 日志传送的选项如下：
- - '####'
  - 数据库镜像的选项如下：
- - '####'
  - AlwaysOn 可用性组的列表非常短：
- - '####'
  - 使用 SQL Server Integration Services 的自定义 ETL 提供以下监控和恢复选项：
- - '####'
  - 最后，对于大容量复制过程 (`BCP`)，您有以下选项：
- - '###'
  - 结论
- - '##'
  - 第 12 章：面向 DBA 的 Windows Azure SQL Database
- - '###'
  - Windows Azure SQL Database for DBAs
- - '###'
  - SQL Database 架构
- - '####'
  - 基础设施
- - '####'
  - 简化的 SQL Database 基础设施
- - '####'
  - 可用性与故障转移
- - '####'
  - 硬件
- - '###'
  - 与 SQL Server 的区别
- - '####'
  - 数据库组件
- - '####'
  - 管理平台
- - '###'
  - 安全性
- - '###'
  - 其他重要信息
- - '####'
  - 数据库大小
- - '####'
  - 数据库版本
- - '####'
  - 对 T-SQL 的支持
- - '####'
  - 备份和还原
- - '####'
  - 联合
- - '###'
  - 联邦
- - '####'
  - 关键术语
- - '####'
  - 图 12-3. SQL 数据库中的示例联邦
- - '####'
  - 联邦的 T-SQL 变更
- - '#####'
  - 表 12-6. 重要联邦命令和系统视图摘要
- - '####'
  - 修改联邦（ALTER FEDERATION）
- - '####'
  - 使用联邦（USE FEDERATION）
- - '####'
  - 在联邦上创建表（CREATE TABLE FEDERATED ON）
- - '####'
  - sys.federations
- - '####'
  - sys.federation_members
- - '####'
  - 联邦示例
- - '####'
  - 限制
- - '####'
  - 扇出支持
- - '####'
  - 数据库副本
- - '####'
  - 隔离的架构更改
- - '####'
  - 用户界面
- - '####'
  - 其他
- - '###'
  - 性能问题疑难解答
- - '####'
  - 可用的动态管理视图
- - '####'
  - 执行计划
- - '####'
  - 性能仪表板
- - '###'
  - 相关服务
- - '####'
  - Windows Azure SQL Reporting
- - '###'
  - 报表
- - '###'
  - Windows Azure SQL 数据同步
- - '###'
  - 导入/导出功能
- - '###'
  - SQL Database 的成本
- - '###'
  - 结论
- - '##'
  - 第 13 章：I/O：不为人知的故事
- - '###'
  - 基础
- - '###'
  - 监控
- - '###'
  - 注意事项
- - '###'
  - 策略
- - '###'
  - 代码还是磁盘？
- - '###'
  - 时代已变
- - '###'
  - 访问数据
- - '###'
  - 处理查询
- - '###'
  - 环境考量
- - '###'
  - 结论
- - '##'
  - 第 14 章：页和行压缩
- - '###'
  - 开始之前
- - '####'
  - 版本和支持
- - '###'
  - 压缩什么以及如何压缩
- - '###'
  - 行压缩
- - '###'
  - 页压缩
- - '###'
  - 你压缩什么？
- - '####'
  - 分配单元类型数据类型
- - '####'
  - 描述
- - '####'
  - 查询分配单元页计数
- - '####'
  - 在 IN_ROW_DATA 页上压缩数据
- - '####'
  - 跨多个分配单元压缩数据
- - '####'
  - 结论：了解你的数据
- - '###'
  - 碎片和日志操作
- - '####'
  - 重建对象时的压缩选项
- - '####'
  - 对数据库日志的影响
- - '###'
  - 结论
- - '##'
  - 第 15 章：服务器的选择与规模确定
- - '###'
  - 了解你的工作负载
- - '###'
  - SQL Server 2012 企业版考量因素
- - '###'
  - 服务器供应商选择
- - '###'
  - 服务器外形规格选择
- - '####'
  - 机架式服务器
- - '####'
  - 塔式服务器
- - '####'
  - 刀片服务器
- - '###'
  - 服务器处理器数量选择
- - '###'
  - Dell 第 12 代服务器比较
- - '####'
  - Dell PowerEdge R320
- - '####'
  - Dell PowerEdge R420
- - '####'
  - Dell PowerEdge R520
- - '####'
  - Dell PowerEdge R620
- - '####'
  - Dell PowerEdge R720
- - '####'
  - Dell PowerEdge R720xd
- - '####'
  - Dell PowerEdge R820
- - '###'
  - 处理器供应商选择
- - '###'
  - 处理器型号选择
- - '###'
  - 内存选择
- - '###'
  - 结论
- - '##'
  - 第 16 章：使用可用性组进行备份与还原
- - '###'
  - 设置可用性组
- - '####'
  - 配置 Windows 服务器
- - '###'
  - SQL Server 可用性组
- - '###'
  - 在可用性组上启用备份
- - '####'
  - 备份位置
- - '####'
  - 备份优先级
- - '###'
  - 在可用性组上实现自动备份
- - '####'
  - 维护计划
- - '####'
  - T-SQL 脚本
- - '###'
  - 在可用性组上恢复
- - '###'
  - 结论
- - '##'
  - 第 17 章：面向 SQL Server DBA 的大数据
- - '###'
  - 大数据随 Hadoop 而来
- - '####'
  - Hadoop 集群
- - '###'
  - MapReduce：Hadoop 的核心
- - '###'
  - 硬件
- - '###'
  - 数据库管理员作为数据架构师
- - '###'
  - 用于分析的大数据
- - '###'
  - 将 SQL Server 与 Hadoop 结合使用
- - '####'
  - 数据库管理员的角色
- - '####'
  - 实践中的大数据
- - '###'
  - 从 HDFS 导出
- - '###'
  - Hive
- - '###'
  - 在 Hive 中创建表并查询数据
- - '###'
  - 使用 HiveQL 查询 HDFS 数据
- - '###'
  - Hive 和 Excel
- - '###'
  - JavaScript
- - '###'
  - 实践应用代码
- - '####'
  - 映射函数
- - '####'
  - 归约函数
- - '####'
  - 运行代码
- - '###'
  - Pig
- - '###'
  - 面向我们其他人的大数据
- - '####'
  - 商业智能
- - '####'
  - 大数据源
- - '####'
  - 大数据业务案例
- - '####'
  - 适合大数据框架的数据集类型
- - '#####'
  - 非关系型数据集
- - '#####'
  - 传感器流数据
- - '#####'
  - 归档数据
- - '#####'
  - 非结构化数据
- - '#####'
  - 数据发现
- - '#####'
  - 由分析结果驱动的业务规则
- - '####'
  - 微软未来的大数据
- - '###'
  - 结论
- - '##'
  - 第 18 章：为峰值负载进行调优
- - '###'
  - 定义峰值负载
- - '###'
  - 系统性能调优与峰值负载处理
- - '####'
  - 性能 SLA 的重要性
- - '####'
  - 评估当前状态
- - '####'
  - 执行评估
- - '###'
  - 定义要捕获的数据
- - '####'
  - 表 18-2. 需从网络、服务器、应用程序和 SQL Server 收集的配置数据
- - '###'
  - 收集系统性能数据
- - '###'
  - 表 18-3. 创建数据收集器之前需要提出的关键问题
- - '###'
  - 表 18-4. 显示所有推荐捕获的 `Perfmon` 对象计数器
- - '###'
  - SQL Server 性能计数器监控指南
- - '####'
  - 数据库操作计数器
- - '####'
  - 通用统计信息计数器
- - '####'
  - 锁与闩锁计数器
- - '####'
  - 内存管理计数器
- - '####'
  - 执行计划缓存计数器
- - '####'
  - SQL Server：SQL 统计信息\批处理请求数/秒
- - '####'
  - SQL Server：SQL 统计信息\SQL 编译数/秒
- - '####'
  - SQL Server：SQL 统计信息\SQL 重编译数/秒
- - '####'
  - SQL Server：等待统计信息（平均等待时间（毫秒））
- - '####'
  - 存储：逻辑磁盘(*)\% 空闲时间
- - '####'
  - 存储：逻辑磁盘(*) 性能计数器
- - '###'
  - 计划数据收集器
- - '###'
  - 设置停止条件
- - '###'
  - 收集应用程序性能数据
- - '###'
  - 分析数据
- - '###'
  - 分析应用使用情况数据
- - '###'
  - 图 18-8. 三个月内所有应用调用的性能数据（按周汇总）
- - '###'
  - 表 18-8. 与图 18-8 所示数据相关的观察结果
- - '###'
  - 图 18-9. 过去两个月所有应用请求按天的 SLA 合规性
- - '###'
  - 表 18-9. 基于图 18-9 的 SLA 合规性观察结果
- - '###'
  - 分析性能监视器数据
- - '###'
  - 使用 PAL 审查 Perfmon 数据文件
- - '###'
  - 使用性能监视器的报告视图审查 Perfmon 数据文件
- - '###'
  - 使用性能监视器的折线图视图审查 Perfmon 数据文件
- - '###'
  - 分析配置数据
- - '###'
  - 表 18-10. 待验证的 SQL Server 配置示例列表
- - '###'
  - 概述
- - '###'
  - 服务器配置
- - '###'
  - 故障转移群集配置
- - '###'
  - 数据库属性
- - '###'
  - 数据库文件属性
- - '###'
  - 每个数据库的虚拟日志文件 (VLF) 数量
- - '###'
  - 每个数据库中不受信任的约束
- - '###'
  - 作业列表 – 清单和计划
- - '###'
  - 数据库维护过程
- - '###'
  - 最近的错误日志
- - '###'
  - 评估与变更流程
- - '###'
  - 建立性能基线
- - '###'
  - 分析 SQL 性能数据
- - '###'
  - 从活动数据中识别关键问题
- - '###'
  - 索引利用率分析
- - '###'
  - 识别要调优的 SQL 语句的方法
- - '###'
  - 制定计划
- - '###'
  - 结论
- - '##'
  - 索引
