name: Pro SQL Server Internals
name_cn: SQL Server Internals 高级指南
slug: pro-sql-server-internals
toc:
- - '#'
  - SQL专家之声®
- - '##'
  - 深入理解SQL Server内部机制
- - '###'
  - 深入了解内部机制及其对你的影响
- - '####'
  - 第二版
- - '##'
  - 德米特里·科罗特克维奇
- - '#'
  - 目录概览
- - '##'
  - 第一部分：表与索引
- - '###'
  - 第1章：数据存储原理
- - '###'
  - 第2章：表与索引：内部结构与访问方法
- - '###'
  - 第3章：统计信息
- - '###'
  - 第4章：特殊索引与存储功能
- - '###'
  - 第5章：SQL Server 2016新特性
- - '###'
  - 第6章：索引碎片
- - '###'
  - 第7章：索引设计与调优
- - '##'
  - 第二部分：其他重要主题
- - '###'
  - 第8章：约束
- - '###'
  - 第9章：触发器
- - '###'
  - 第10章：视图
- - '###'
  - 第11章：用户定义函数
- - '###'
  - 第12章：XML与JSON
- - '###'
  - 第13章：临时对象与TempDB
- - '###'
  - 第14章：CLR
- - '###'
  - 第15章：CLR类型
- - '###'
  - 第16章：数据分区
- - '##'
  - 第三部分：锁、阻塞与并发
- - '###'
  - 第17章：锁类型与事务隔离级别
- - '###'
  - 第18章：阻塞问题故障排除
- - '###'
  - 第19章：死锁
- - '###'
  - 第20章：锁升级
- - '###'
  - 第21章：乐观隔离级别
- - '###'
  - 第22章：应用程序锁
- - '###'
  - 第23章：架构锁
- - '###'
  - 第24章：事务策略设计
- - '##'
  - 第四部分：查询生命周期
- - '###'
  - 第25章：查询优化与执行
- - '###'
  - 第26章：执行计划缓存
- - '##'
  - 第五部分：实用故障排除
- - '###'
  - 第27章：扩展事件
- - '###'
  - 第28章：系统故障排除
- - '###'
  - 第29章：查询存储
- - '##'
  - 第六部分：事务日志内幕
- - '###'
  - 第30章：事务日志内部机制
- - '###'
  - 第31章：备份与还原
- - '###'
  - 第32章：高可用性技术
- - '##'
  - 第七部分：列存储索引
- - '###'
  - 第33章：基于列的存储与批处理模式执行
- - '###'
  - 第34章：列存储索引
- - '##'
  - 第八部分：内存OLTP引擎
- - '###'
  - 第35章：内存OLTP内部机制
- - '###'
  - 第36章：内存OLTP中的事务处理
- - '###'
  - 第37章：内存OLTP可编程性
- - '##'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审阅者
- - '##'
  - 致谢
- - '##'
  - 引言
- - '##'
  - 第一部分：表与索引
- - '###'
  - 第1章：数据存储内部机制
- - '####'
  - 数据库文件与文件组
- - '####'
  - 数据页与数据行
- - '####'
  - 大对象存储
- - '#####'
  - 行溢出存储
- - '#####'
  - LOB存储
- - '#####'
  - SELECT * 与 I/O
- - '####'
  - 区与区分配映射页
- - '####'
  - 数据修改
- - '####'
  - 关于数据行大小的深入探讨
- - '####'
  - 表的修改
- - '####'
  - 总结
- - '###'
  - 第2章：表与索引：内部结构与访问方法
- - '####'
  - 堆表
- - '####'
  - 聚集索引
- - '####'
  - 非聚集索引
- - '####'
  - 复合索引
- - '####'
  - 总结
- - '###'
  - 第3章：统计信息
- - '####'
  - SQL Server统计信息简介
- - '####'
  - 列级统计信息
- - '####'
  - 统计信息与执行计划
- - '####'
  - 统计信息与查询内存授予
- - '####'
  - 统计信息维护
- - '####'
  - 新基数估算器（SQL Server 2014–2016）
- - '####'
  - 查询优化器修复与跟踪标志T4199
- - '####'
  - 总结
- - '###'
  - 第4章：特殊索引与存储功能
- - '####'
  - 包含列的索引
- - '####'
  - 筛选索引
- - '####'
  - 筛选统计信息
- - '####'
  - 计算列
- - '####'
  - 数据压缩
- - '#####'
  - 行压缩
- - '#####'
  - 页面压缩
- - '#####'
  - 性能考量
- - '####'
  - 稀疏列
- - '####'
  - 总结
- - '###'
  - 第5章：SQL Server 2016新特性
- - '####'
  - 时态表
- - '####'
  - 伸缩数据库
- - '####'
  - 行级安全性
- - '####'
  - 始终加密
- - '####'
  - 动态数据屏蔽
- - '####'
  - 组合安全功能
- - '####'
  - 总结
- - '###'
  - 第6章：索引碎片
- - '####'
  - 碎片类型
- - '####'
  - FILLFACTOR和PAD_INDEX
- - '####'
  - 索引维护
- - '####'
  - 设计索引维护策略
- - '####'
  - 增加碎片的模式
- - '####'
  - 总结
- - '###'
  - 第7章：索引设计与调优
- - '####'
  - 聚集索引设计注意事项
- - '#####'
  - 标识符、序列和唯一标识符
- - '####'
  - 非聚集索引设计注意事项
- - '####'
  - 优化与调整索引
- - '#####'
  - 检测未使用和低效的索引
- - '#####'
  - 索引合并
- - '#####'
  - 检测次优查询
- - '####'
  - 总结
- - '##'
  - 第二部分：其他重要事项
- - '###'
  - 第8章：约束
- - '####'
  - 主键约束
- - '####'
  - 唯一约束
- - '####'
  - 外键约束
- - '####'
  - 检查约束
- - '####'
  - 总结
- - '###'
  - 第9章：触发器
- - '####'
  - DML触发器
- - '####'
  - DDL触发器
- - '####'
  - 登录触发器
- - '####'
  - UPDATE() 和 COLUMNS_UPDATED() 函数
- - '####'
  - 嵌套和递归触发器
- - '####'
  - 首发和末发触发器
- - '####'
  - CONTEXT_INFO 和 SESSION_CONTEXT
- - '####'
  - 总结
- - '###'
  - 第10章：视图
- - '####'
  - 视图
- - '####'
  - 索引（物化）视图
- - '####'
  - 分区视图
- - '####'
  - 可更新视图
- - '####'
  - 总结
- - '###'
  - 第11章：用户定义函数
- - '####'
  - 关于代码重用的诸多讨论
- - '####'
  - 多语句函数
- - '####'
  - 内联表值函数
- - '####'
  - 总结
- - '###'
  - 第12章：XML与JSON
- - '####'
  - 用还是不用XML或JSON？这是个问题！
- - '####'
  - XML数据类型
- - '####'
  - 处理XML数据
- - '####'
  - OPENXML
- - '####'
  - SELECT FOR XML
- - '####'
  - 处理JSON数据 (SQL Server 2016)
- - '####'
  - SELECT FOR JSON
- - '####'
  - 内置函数
- - '####'
  - OPENJSON
- - '####'
  - 总结
- - '###'
  - 第13章：临时对象与TempDB
- - '####'
  - 临时表
- - '####'
  - 表变量
- - '####'
  - 用户定义的表类型与表值参数
- - '####'
  - TempDB中的常规表
- - '####'
  - 优化TempDB性能
- - '####'
  - 总结
- - '###'
  - 第14章：CLR
- - '####'
  - CLR集成概述
- - '####'
  - 安全注意事项
- - '####'
  - 性能注意事项
- - '####'
  - 总结
- - '###'
  - 第15章：CLR类型
- - '####'
  - 用户定义的CLR类型
- - '####'
  - 空间数据类型
- - '####'
  - HierarchyId
- - '####'
  - 总结
- - '###'
  - 第16章：数据分区
- - '####'
  - 数据分区的原因
- - '####'
  - 何时分区？
- - '####'
  - 数据分区技术
- - '#####'
  - 分区表
- - '#####'
  - 分区视图
- - '#####'
  - 比较分区表与分区视图
- - '#####'
  - 结合使用分区表和视图
- - '####'
  - 分层存储
- - '####'
  - 实现滑动窗口场景和数据清除
- - '####'
  - 潜在问题
- - '####'
  - 总结
- - '##'
  - 第三部分：锁、阻塞与并发
- - '###'
  - 第17章：锁类型与事务隔离级别
- - '####'
  - 事务与ACID
- - '####'
  - 主要锁类型
- - '####'
  - 锁的兼容性、行为与生命周期
- - '####'
  - 事务隔离级别与数据一致性
- - '####'
  - 总结
- - '###'
  - 第18章：排查阻塞问题
- - '####'
  - 通用排查方法
- - '####'
  - 实时排查阻塞问题
- - '####'
  - 收集阻塞信息以供进一步分析
- - '####'
  - 总结
- - '###'
  - 第19章：死锁
- - '####'
  - 经典死锁
- - '####'
  - 因非优化查询导致的死锁
- - '####'
  - 总结
- - '###'
  - 第20章：锁升级
- - '####'
  - 锁升级概述
- - '####'
  - 锁升级故障排除
- - '####'
  - 总结
- - '###'
  - 第21章：乐观隔离级别
- - '####'
  - 乐观事务隔离级别
- - '####'
  - 行版本控制概述
- - '####'
  - 乐观事务隔离级别
- - '####'
  - 版本存储行为
- - '####'
  - 总结
- - '###'
  - 第22章：应用程序锁
- - '####'
  - 应用程序锁概述
- - '####'
  - 应用程序锁用法
- - '####'
  - 总结
- - '###'
  - 第23章：架构锁
- - '####'
  - 架构修改锁
- - '####'
  - 多会话与锁兼容性
- - '####'
  - 锁分区
- - '####'
  - 低优先级锁
- - '####'
  - 总结
- - '###'
  - 第24章：设计事务策略
- - '####'
  - 注意事项与代码模式
- - '####'
  - 选择事务隔离级别
- - '####'
  - 总结
- - '##'
  - 第四部分：查询生命周期
- - '###'
  - 第25章：查询优化与执行
- - '####'
  - 查询生命周期
- - '####'
  - 查询优化过程
- - '####'
  - 查询执行
- - '####'
  - 运算符
- - '####'
  - 查询与表提示
- - '####'
  - 总结
- - '###'
  - 第26章：计划缓存
- - '####'
  - 计划缓存概述
- - '####'
  - 参数嗅探
- - '####'
  - 计划重用
- - '####'
  - 即席查询的计划缓存
- - '####'
  - 自动参数化
- - '####'
  - 计划指南
- - '####'
  - 计划缓存内部机制
- - '####'
  - 检查计划缓存
- - '####'
  - 总结
- - '##'
  - 第五部分：实用故障排除
- - '###'
  - 第27章：扩展事件
- - '####'
  - 扩展事件概述
- - '####'
  - 扩展事件对象
- - '####'
  - 创建事件会话
- - '####'
  - 处理事件数据
- - '####'
  - System_health 和 AlwaysOn_Health 会话
- - '####'
  - 使用扩展事件
- - '####'
  - 总结
- - '###'
  - 第28章：系统故障排除
- - '####'
  - 宏观审视
- - '####'
  - 硬件与网络
- - '####'
  - 操作系统配置
- - '####'
  - SQL Server配置
- - '####'
  - 数据库选项
- - '####'
  - 资源调控器概述
- - '####'
  - SQL Server执行模型
- - '####'
  - 等待统计信息分析与故障排除
- - '####'
  - 内存管理与配置
- - '####'
  - 服务器无响应时的处理措施
- - '####'
  - 使用基准线
- - '####'
  - 总结
- - '###'
  - 第29章：查询存储
- - '####'
  - 为何使用查询存储？
- - '####'
  - 查询存储配置
- - '####'
  - 查询存储内部原理
- - '####'
  - 使用场景
- - '####'
  - 管理与监控查询存储
- - '####'
  - 总结
- - '##'
  - 第六部分：事务日志内幕
- - '###'
  - 第30章：事务日志内部原理
- - '####'
  - 数据修改、日志记录与恢复
- - '####'
  - 延迟持久化
- - '####'
  - 虚拟日志文件
- - '####'
  - 数据库恢复模式
- - '####'
  - TempDB日志记录
- - '####'
  - 事务日志过度增长
- - '####'
  - 事务日志管理
- - '####'
  - 总结
- - '###'
  - 第31章：备份与恢复
- - '####'
  - 数据库备份类型
- - '####'
  - 数据库备份
- - '####'
  - 数据库恢复
- - '####'
  - 设计备份策略
- - '####'
  - 部分数据库可用性与分段恢复
- - '####'
  - Microsoft Azure集成
- - '####'
  - 总结
- - '###'
  - 第32章：高可用性技术
- - '####'
  - SQL Server故障转移集群
- - '####'
  - 数据库镜像与AlwaysOn可用性组
- - '####'
  - 日志传送
- - '####'
  - 复制
- - '####'
  - 设计高可用性策略
- - '####'
  - 总结
- - '##'
  - 第七部分：列存储索引
- - '###'
  - 第33章：基于列的存储与批处理模式执行
- - '####'
  - 数据仓库系统概述
- - '####'
  - 列存储索引与批处理模式执行概述
- - '####'
  - 基于列的存储
- - '####'
  - 列存储索引的设计考虑与最佳实践
- - '####'
  - 总结
- - '###'
  - 第34章：列存储索引
- - '####'
  - 列存储索引类型
- - '####'
  - 只读非聚集列存储索引 (SQL Server 2012–2014)
- - '####'
  - 聚集列存储索引 (SQL Server 2014–2016)
- - '####'
  - 可更新的非聚集列存储索引 (SQL Server 2016)
- - '####'
  - 元数据
- - '####'
  - 设计考虑
- - '####'
  - 总结
- - '##'
  - 第八部分：内存OLTP引擎
- - '###'
  - 第35章：内存OLTP内部原理
- - '####'
  - 为何需要内存OLTP？
- - '####'
  - 内存OLTP引擎架构与数据结构
- - '####'
  - 数据持久性与恢复
- - '####'
  - SQL Server 2016功能支持
- - '####'
  - 内存使用注意事项
- - '####'
  - 总结
- - '###'
  - 第36章：内存OLTP中的事务处理
- - '####'
  - 事务隔离级别与数据一致性
- - '####'
  - 内存OLTP中的事务隔离级别
- - '####'
  - 跨容器事务
- - '####'
  - 事务生命周期
- - '####'
  - 引用完整性强制实施 (SQL Server 2016)
- - '####'
  - 事务日志记录
- - '####'
  - 总结
- - '###'
  - 第37章：内存OLTP可编程性
- - '####'
  - 本机编译
- - '####'
  - 本机编译模块
- - '####'
  - 解释型T-SQL与内存优化表
- - '####'
  - 内存优化表类型与变量
- - '####'
  - 内存OLTP：实现考量
- - '####'
  - 总结
- - '##'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 致谢
- - '##'
  - 引言
- - '###'
  - 本书结构
- - '###'
  - 下载代码
