name: The Definitive Guide to MongoDB
name_cn: MongoDB 权威指南
slug: the-definitive-guide-to-mongodb
toc:
- - '##'
  - 第一部分
- - '###'
  - 1. MongoDB 简介
- - '####'
  - 回顾 MongoDB 的理念
- - '#####'
  - 让合适的工具做合适的工作
- - '##'
  - MongoDB 概览
- - '###'
  - 缺乏对事务的原生支持
- - '###'
  - JSON 与 MongoDB
- - '##'
  - XML 与 JSON：数据交换格式的演进
- - '###'
  - 采用非关系型方法
- - '###'
  - 在性能与功能之间做出选择
- - '###'
  - 在任何地方运行数据库
- - '###'
  - 整合所有内容
- - '###'
  - 生成或创建键
- - '###'
  - 使用键与值
- - '###'
  - 实现集合
- - '###'
  - 理解数据库
- - '##'
  - 回顾特性列表
- - '###'
  - 使用面向文档的存储（BSON）
- - '###'
  - 支持动态查询
- - '###'
  - 为你的文档建立索引
- - '###'
  - 利用地理空间索引
- - '###'
  - 分析查询
- - '###'
  - 就地更新信息
- - '###'
  - 存储二进制数据
- - '###'
  - 复制数据
- - '###'
  - 实现分片
- - '###'
  - 使用 Map 和 Reduce 函数
- - '###'
  - 全新的聚合框架
- - '##'
  - 获取帮助
- - '###'
  - 访问网站
- - '###'
  - 与 MongoDB 开发者聊天
- - '###'
  - 剪切和粘贴 MongoDB 代码
- - '###'
  - 在 Google Groups 上寻找解决方案
- - '###'
  - 利用 JIRA 跟踪系统
- - '##'
  - 总结
- - '###'
  - 2. 安装 MongoDB
- - '####'
  - 选择你的版本
- - '#####'
  - 理解版本号
- - '####'
  - 在你的系统上安装 MongoDB
- - '#####'
  - 在 Linux 下安装 MongoDB
- - '######'
  - 通过存储库安装 MongoDB
- - '#####'
  - 手动安装 MongoDB
- - '#####'
  - 在 Windows 下安装 MongoDB
- - '####'
  - 运行 MongoDB
- - '#####'
  - 先决条件
- - '#####'
  - 查看安装布局
- - '#####'
  - 使用 MongoDB Shell
- - '####'
  - 安装额外的驱动程序
- - '#####'
  - 安装 PHP 驱动程序
- - '######'
  - 获取 PHP 的 MongoDB
- - '######'
  - 在基于 Unix 的平台上自动安装 PHP 驱动程序
- - '######'
  - 在基于 Unix 的平台上手动安装 PHP 驱动程序
- - '######'
  - 在 Windows 上安装 PHP 驱动程序
- - '#####'
  - 确认您的 PHP 安装有效
- - '######'
  - 连接与断开 PHP 驱动
- - '#####'
  - 安装 Python 驱动
- - '######'
  - 在 Linux 下安装 PyMongo
- - '#######'
  - 自动安装 PyMongo
- - '#######'
  - 手动安装 PyMongo
- - '######'
  - 在 Windows 下安装 PyMongo
- - '#####'
  - 确认您的 PyMongo 安装是否正常工作
- - '####'
  - 总结
- - '###'
  - 3. 数据模型
- - '####'
  - 摘要
- - '####'
  - 数据库设计
- - '#####'
  - 深入探讨集合
- - '#####'
  - 使用文档
- - '######'
  - 在文档中嵌入与引用信息
- - '#####'
  - 创建 `_id` 字段
- - '####'
  - 构建索引
- - '#####'
  - 通过索引影响性能
- - '####'
  - 实现地理空间索引
- - '#####'
  - 查询地理空间信息
- - '####'
  - 在现实世界中使用 MongoDB
- - '####'
  - 总结
- - '###'
  - 4. 处理数据
- - '####'
  - 浏览你的数据库
- - '#####'
  - 查看可用的数据库和集合
- - '####'
  - 向集合中插入数据
- - '####'
  - 数据查询
- - '#####'
  - 使用点表示法
- - '#####'
  - 使用排序、限制与跳过功能
- - '#####'
  - 处理固定集合、自然顺序与 $natural
- - '#####'
  - 检索单个文档
- - '#####'
  - 使用聚合命令
- - '######'
  - 使用 `count()` 返回文档数量
- - '######'
  - 使用 `distinct()` 检索唯一值
- - '######'
  - 对结果进行分组
- - '#####'
  - 使用条件运算符
- - '####'
  - MongoDB 查询操作符：比较、范围与逻辑匹配
- - '#####'
  - 执行大于与小于比较
- - '#####'
  - 检索除特定条件外的所有文档
- - '#####'
  - 指定一个匹配值数组
- - '#####'
  - 查找值不在数组中的文档
- - '#####'
  - 匹配文档中的所有属性
- - '#####'
  - 在文档中搜索多个表达式
- - '#####'
  - 使用 $slice 检索文档
- - '#####'
  - 搜索奇数/偶数整数
- - '#####'
  - 使用 $size 过滤结果
- - '#####'
  - 返回特定字段对象
- - '#####'
  - 基于 BSON 类型匹配结果
- - '######'
  - 匹配整个数组
- - '######'
  - $not（元操作符）
- - '######'
  - 指定额外的查询表达式
- - '#####'
  - 利用正则表达式
- - '####'
  - 更新数据
- - '#####'
  - 使用 update() 更新
- - '####'
  - 使用 `save()` 命令实现更新插入
- - '####'
  - 自动更新信息
- - '#####'
  - 使用 `$inc` 递增值
- - '#####'
  - 设置字段的值
- - '#####'
  - 删除指定字段
- - '#####'
  - 向指定字段追加值
- - '#####'
  - 在数组中指定多个值
- - '#####'
  - 使用 `$addToSet` 向数组添加数据
- - '####'
  - 从数组中移除元素
- - '#####'
  - 移除指定值的每次出现
- - '#####'
  - 从数组中移除多个元素
- - '####'
  - 指定匹配数组的位置
- - '####'
  - 原子操作
- - '####'
  - 使用当前值更新法
- - '#####'
  - 原子性地修改并返回文档
- - '####'
  - 重命名集合
- - '####'
  - 删除数据
- - '####'
  - 引用数据库
- - '#####'
  - 手动引用数据
- - '#####'
  - 使用 DBRef 引用数据
- - '##'
  - 实现索引相关功能
- - '####'
  - 审视索引相关命令
- - '####'
  - 强制使用指定索引查询数据
- - '###'
  - 5. GridFS
- - '####'
  - 约束查询匹配
- - '####'
  - 总结
- - '####'
  - 摘要
- - '####'
  - 补充一些背景知识
- - '####'
  - 使用 GridFS
- - '####'
  - 开始使用命令行工具
- - '#####'
  - 使用 `_id` 键
- - '#####'
  - 处理文件名
- - '#####'
  - 确定文件长度
- - '#####'
  - 处理分块大小
- - '#####'
  - 跟踪上传日期
- - '#####'
  - 对文件进行哈希处理
- - '####'
  - 深入探究 MongoDB 的内部机制
- - '#####'
  - 使用 `search` 命令
- - '#####'
  - 删除操作
- - '#####'
  - 从 MongoDB 中检索文件
- - '#####'
  - mongofiles 总结
- - '####'
  - 利用 Python 的强大功能
- - '#####'
  - 连接到数据库
- - '#####'
  - 访问单词
- - '##'
  - 第二部分
- - '###'
  - 使用 MongoDB 进行开发
- - '###'
  - 6. PHP 与 MongoDB
- - '####'
  - 将文件存入 MongoDB
- - '####'
  - 从 GridFS 检索文件
- - '####'
  - 删除文件
- - '####'
  - 总结
- - '####'
  - 在 MongoDB 与 PHP 中比较文档
- - '####'
  - MongoDB 类
- - '####'
  - 连接与断开连接
- - '#####'
  - 建立连接
- - '#####'
  - 选择集合
- - '#####'
  - 列出数据库和集合
- - '#####'
  - 断开连接
- - '####'
  - 插入数据
- - '####'
  - 列出你的数据
- - '#####'
  - 返回单个文档
- - '#####'
  - 列出所有文档
- - '#####'
  - 使用查询运算符
- - '#####'
  - 查询特定信息
- - '#####'
  - 排序、限制和跳过项目
- - '#####'
  - 计算匹配结果的数量
- - '#####'
  - 使用聚合框架对数据进行分组
- - '#####'
  - 使用 Hint 指定索引
- - '#####'
  - 使用条件操作符优化查询
- - '####'
  - 使用 `$lt`、`$gt`、`$lte` 和 `$gte` 操作符
- - '#####'
  - 查找与指定值不匹配的文档
- - '#####'
  - 使用 `$in` 匹配多个值中的任意一个
- - '#####'
  - 使用 `$all` 在查询中匹配所有条件
- - '####'
  - 使用 `$or` 搜索多个表达式
- - '####'
  - 使用 `$slice` 检索指定数量的项目
- - '####'
  - 确定字段是否具有值
- - '#####'
  - 正则表达式
- - '####'
  - 使用 PHP 修改数据
- - '#####'
  - 通过 update() 更新
- - '##'
  - 使用更新操作符节省时间
- - '####'
  - 使用 `$inc` 增加特定键的值
- - '####'
  - 使用 `$set` 更改键的值
- - '####'
  - 使用 `$unset` 删除字段
- - '####'
  - 使用 `$rename` 重命名字段
- - '####'
  - 使用 `$setOnInsert` 在更新插入时更改键的值
- - '####'
  - 使用 MongoDB 更新操作符进行数组操作
- - '#####'
  - 赋值到指定字段：使用 `$push`
- - '#####'
  - 向键添加多个值：使用 `$push` 和 `$each`
- - '#####'
  - 向数组添加数据：使用 `$addToSet`
- - '#####'
  - 从数组中移除元素：使用 `$pop`
- - '#####'
  - 移除值的每次出现：使用 `$pull`
- - '#####'
  - 移除多个元素的每次出现
- - '##'
  - MongoDB PHP 驱动高级操作
- - '####'
  - 使用 save() 进行更新插入数据
- - '####'
  - 原子性地修改文档
- - '####'
  - 删除数据
- - '####'
  - DBRef
- - '#####'
  - 检索信息
- - '####'
  - GridFS 与 PHP 驱动程序
- - '#####'
  - 存储文件
- - '#####'
  - 为存储的文件添加更多元数据
- - '#####'
  - 检索文件
- - '#####'
  - 删除数据
- - '##'
  - 总结
- - '###'
  - 7. Python 与 MongoDB
- - '####'
  - 在 Python 中处理文档
- - '####'
  - 使用 PyMongo 模块
- - '####'
  - 连接与断开连接
- - '####'
  - 插入数据
- - '####'
  - 查找你的数据
- - '#####'
  - 查找单个文档
- - '#####'
  - 查找多个文档
- - '#####'
  - 使用点表示法
- - '#####'
  - 返回字段
- - '#####'
  - 使用 sort()、limit() 和 skip() 简化查询
- - '#####'
  - 聚合查询
- - '######'
  - 使用 count() 计数
- - '######'
  - 使用 distinct() 统计唯一项
- - '######'
  - 使用聚合框架对数据进行分组
- - '#####'
  - 使用 hint() 指定索引
- - '#####'
  - 使用条件操作符优化查询
- - '####'
  - 使用 `$lt`、`$gt`、`$lte` 和 `$gte` 操作符
- - '####'
  - 使用 `$ne` 搜索不匹配的值
- - '####'
  - 使用 `$in` 指定匹配数组
- - '####'
  - 使用 `$nin` 针对匹配数组进行排除
- - '####'
  - 查找匹配数组所有值的文档
- - '####'
  - 使用 `$or` 指定多个匹配表达式
- - '####'
  - 使用 `$slice` 从数组中检索项目
- - '#####'
  - 使用正则表达式进行搜索
- - '####'
  - 修改数据
- - '#####'
  - 更新你的数据
- - '##'
  - 定义更新后的数据
- - '##'
  - 现在，执行更新
- - '##'
  - 检查更新的结果
- - '#####'
  - 修改器操作符
- - '######'
  - 使用 $inc 增加整数值
- - '######'
  - 使用 $set 更改现有值
- - '######'
  - 使用 $unset 移除键/值字段
- - '######'
  - 使用 $push 向数组添加值
- - '####'
  - 使用 `$push` 和 `$each` 向数组添加多个值
- - '####'
  - 使用 `$addToSet` 向现有数组添加值
- - '####'
  - 使用 `$pop` 从数组中移除元素
- - '####'
  - 使用 `$pull` 移除特定值
- - '#####'
  - 使用 `save()` 快速保存文档
- - '#####'
  - 原子性地修改文档
- - '#####'
  - 参数实战应用
- - '####'
  - 删除数据
- - '####'
  - 在两个文档之间创建链接
- - '#####'
  - 检索信息
- - '####'
  - 摘要
- - '###'
  - 8. 高级查询
- - '####'
  - 文本搜索
- - '#####'
  - 文本搜索的成本与限制
- - '#####'
  - 启用文本搜索
- - '#####'
  - 使用文本搜索
- - '######'
  - 加载文本数据
- - '######'
  - 创建文本索引
- - '######'
  - 运行文本搜索命令
- - '####'
  - 过滤文本查询
- - '####'
  - 更复杂的文本搜索
- - '#####'
  - 排除术语
- - '#####'
  - 字符串字面量搜索
- - '####'
  - 附加选项
- - '#####'
  - '`limit` 选项'
- - '#####'
  - '`project` 选项'
- - '#####'
  - '`language` 选项'
- - '#####'
  - 支持的语言
- - '#####'
  - 其他语言的文本索引
- - '#####'
  - 文本索引的复合索引
- - '####'
  - 聚合框架
- - '#####'
  - $group
- - '######'
  - $sum
- - '#####'
  - $limit
- - '##'
  - $match
- - '##'
  - $sort
- - '##'
  - $unwind
- - '#####'
  - $project
- - '#####'
  - '`$skip`'
- - '##'
  - MapReduce
- - '#####'
  - MapReduce 如何工作
- - '#####'
  - 设置测试文档
- - '#####'
  - 使用 Map 函数
- - '#####'
  - 高级 MapReduce
- - '#####'
  - 调试 MapReduce
- - '####'
  - 总结
- - '##'
  - 第 3 部分：大数据高级 MongoDB 应用
- - '###'
  - 9. 数据库管理
- - '####'
  - 摘要
- - '####'
  - 使用管理工具
- - '#####'
  - '`mongo`, MongoDB 控制台'
- - '#####'
  - 使用第三方管理工具
- - '####'
  - 备份 MongoDB 服务器
- - '####'
  - 备份入门指南
- - '#####'
  - 备份单个数据库
- - '#####'
  - 备份单个集合
- - '####'
  - 深入探讨备份
- - '####'
  - 恢复单个数据库或集合
- - '#####'
  - 恢复单个数据库
- - '#####'
  - 恢复单个集合
- - '####'
  - 自动化备份
- - '#####'
  - 使用本地数据存储
- - '##'
  - 编辑这些以定义源和目标
- - '##'
  - _do_store_archive <数据库> <转储目录> <目标目录> <目标文件>
- - '##'
  - _do_backup <数据库名称>
- - '##'
  - 检查是否指定了单个数据库，否则备份整个服务器到 "all"
- - '#####'
  - 使用远程（基于云的）数据存储
- - '##'
  - _do_store_archive <数据库> <转储目录> <目标目录> <目标文件>
- - '####'
  - 备份大型数据库
- - '#####'
  - 使用隐藏辅助服务器进行备份
- - '#####'
  - 使用日志文件系统创建快照
- - '#####'
  - 适用于卷管理器的磁盘布局
- - '####'
  - 将数据导入 MongoDB
- - '####'
  - 从 MongoDB 导出数据
- - '####'
  - 通过限制对 MongoDB 服务器的访问来保护数据
- - '####'
  - 通过认证保护你的服务器
- - '#####'
  - 添加管理员用户
- - '##'
  - MongoDB 认证与用户管理
- - '####'
  - 启用认证
- - '####'
  - 在 mongo 控制台中认证
- - '##'
  - MongoDB 用户角色
- - '####'
  - 委托凭证
- - '####'
  - 更改用户凭证
- - '####'
  - 添加只读用户
- - '####'
  - 删除用户
- - '##'
  - 在 PHP 应用程序中使用身份验证连接
- - '##'
  - 管理服务器
- - '####'
  - 启动服务器
- - '####'
  - 重新配置服务器
- - '##'
  - mongodb.conf
- - '####'
  - 获取服务器的版本
- - '##'
  - 获取服务器状态
- - '####'
  - 关闭服务器
- - '####'
  - 使用 MongoDB 日志文件
- - '####'
  - 验证和修复数据
- - '#####'
  - 修复服务器
- - '####'
  - 验证单个集合
- - '####'
  - 修复集合验证错误
- - '#####'
  - 修复集合的索引
- - '#####'
  - 修复集合的数据文件
- - '#####'
  - 压实集合的数据文件
- - '####'
  - 升级 MongoDB
- - '####'
  - MongoDB 的滚动升级
- - '####'
  - 监控 MongoDB
- - '#####'
  - 编写你自己的统计监控工具
- - '####'
  - 使用 MongoDB 管理服务 (MMS)
- - '####'
  - 总结
- - '###'
  - 10. 优化
- - '####'
  - 摘要
- - '####'
  - 为优化性能调整服务器硬件
- - '#####'
  - 理解 MongoDB 如何使用内存
- - '#####'
  - 理解工作集大小
- - '#####'
  - 选择合适的数据库服务器硬件
- - '####'
  - 评估查询性能
- - '#####'
  - MongoDB 分析器
- - '######'
  - 启用和禁用数据库分析器
- - '######'
  - 查找慢查询
- - '######'
  - 增大性能分析集合的大小
- - '#####'
  - 使用 explain() 分析特定查询
- - '##'
  - 使用分析器和 explain() 优化查询
- - '####'
  - 管理索引
- - '#####'
  - 列出索引
- - '#####'
  - 创建简单索引
- - '#####'
  - 创建复合索引
- - '####'
  - 指定索引选项
- - '#####'
  - 使用 `{background:true}` 在后台创建索引
- - '#####'
  - 使用唯一键 `{unique:true}` 创建索引
- - '#####'
  - 使用 `{dropdups:true}` 自动删除重复项
- - '#####'
  - 使用 `{sparse:true}` 创建稀疏索引
- - '##'
  - TTL 索引
- - '##'
  - 文本搜索索引
- - '##'
  - 删除索引
- - '##'
  - 重新索引集合
- - '##'
  - MongoDB 如何选择将使用的索引
- - '####'
  - 使用 `hint()` 强制使用特定索引
- - '####'
  - 优化小对象的存储
- - '####'
  - 总结
- - '###'
  - 11. 复制
- - '####'
  - 阐明 MongoDB 的复制目标
- - '#####'
  - 提升可扩展性
- - '#####'
  - 提升持久性/可靠性
- - '#####'
  - 提供隔离性
- - '####'
  - 复制基础
- - '#####'
  - 什么是主节点？
- - '#####'
  - 什么是从节点？
- - '#####'
  - 什么是仲裁节点？
- - '####'
  - 深入探究操作日志
- - '####'
  - 实现副本集
- - '#####'
  - 创建副本集
- - '####'
  - 启动并运行副本集成员
- - '####'
  - 向副本集添加服务器
- - '#####'
  - 添加仲裁节点
- - '#####'
  - 副本集链式同步
- - '#####'
  - 管理副本集
- - '######'
  - 使用 `rs.status( )` 检查实例状态
- - '######'
  - 使用 `rs.stepDown( )` 强制进行新一轮选举
- - '######'
  - 确定成员是否为主服务器
- - '#####'
  - 配置副本集成员选项
- - '######'
  - members 结构的组织
- - '######'
  - 探索 Settings 结构中的可用选项
- - '#####'
  - 从应用程序连接到副本集
- - '####'
  - 在应用程序中设置读偏好
- - '####'
  - 在应用程序中设置写关注点
- - '####'
  - 使用标签实现读偏好和写关注点
- - '####'
  - 概要
- - '###'
  - 12. 分片
- - '####'
  - 摘要
- - '####'
  - 探索分片的必要性
- - '####'
  - 水平与垂直数据分区
- - '#####'
  - 垂直分区数据
- - '#####'
  - 水平分区数据
- - '####'
  - 分析一个简单的分片场景
- - '####'
  - 使用 MongoDB 实现分片
- - '#####'
  - 分片级别与关键概念
- - '#####'
  - 管理分片和配置
- - '#####'
  - 物理部署考虑
- - '##'
  - 设置分片配置
- - '####'
  - 向集群添加新分片
- - '####'
  - 从集群中移除分片
- - '####'
  - 确定你的连接方式
- - '#####'
  - 列出分片集群的状态
- - '#####'
  - 使用副本集实现分片
- - '#####'
  - 平衡器
- - '##'
  - 设置平衡器窗口
- - '##'
  - 哈希分片键
- - '##'
  - 标签分片
- - '####'
  - 摘要
- - '##'
  - MongoDB 权威指南
- - '###'
  - 聚合与查询
- - '####'
  - 聚合查询
- - '####'
  - 聚合框架
- - '###'
  - 备份与恢复
- - '####'
  - 备份策略
- - '####'
  - '`mongorestore` 命令'
- - '####'
  - GridFS
- - '###'
  - 数据库管理
- - '####'
  - 核心概念
- - '####'
  - 集合类型
- - '####'
  - 连接与命令
- - '####'
  - 数据类型
- - '###'
  - 数据操作
- - '####'
  - 数据库管理工具
- - '####'
  - 数据库操作
- - '###'
  - 数据模型与索引
- - '####'
  - 数据模型构建
- - '####'
  - 数据类型
- - '####'
  - 嵌入信息
- - '####'
  - 字段参数，`findandmodify()`
- - '####'
  - '`Find()` 命令'
- - '####'
  - 前向自然顺序
- - '###'
  - 地理空间索引
- - '####'
  - GridFS
- - '###'
  - 索引与修改器
- - '####'
  - 哈希分片键
- - '####'
  - 索引相关函数
- - '####'
  - '`Insert()` 函数，PHP 驱动'
- - '####'
  - 整数数据类型
- - '####'
  - IRC (Internet Relay Chat)
- - '####'
  - '`$lt`, `$gt`, `$lte`, 和 `$gte` 操作符'
- - '##'
  - J, K
- - '####'
  - '`listCollections()` 函数'
- - '####'
  - MapReduce 函数
- - '####'
  - 最大数据类型
- - '####'
  - 元数据
- - '####'
  - 最小数据类型
- - '###'
  - 修改器函数
- - '####'
  - 修改器操作符
- - '###'
  - MongoDB 服务器与特性
- - '####'
  - Mongod 应用程序 MongoDB
- - '####'
  - PHP 驱动
- - '####'
  - Python 驱动
- - '####'
  - 查询性能（参见查询性能）
- - '####'
  - RAC 架构
- - '####'
  - 关系模型
- - '####'
  - 要求
- - '###'
  - MongoDB 备份与恢复
- - '###'
  - MongoDB 特性
- - '###'
  - MongoDB 管理服务
- - '####'
  - MongoDB 服务器
- - '####'
  - 多版本并发控制方法
- - '##'
  - N
- - '####'
  - '`new` 参数，`findandmodify()`'
- - '####'
  - 非关系型数据库
- - '####'
  - Null 数据类型
- - '##'
  - O
- - '###'
  - 优化
- - '##'
  - P
- - '####'
  - 管道表达式
- - '####'
  - 主节点
- - '####'
  - '`print_r()` 函数（PHP）'
- - '####'
  - '`$pullAll` 操作符、`pullAll` 操作符'
- - '####'
  - '`$pull` 操作符、`pull` 操作符'
- - '####'
  - '`$push` 操作符、`push` 操作符'
- - '####'
  - PyMongo。参见 Python PyMongo 模块
- - '###'
  - Python
- - '##'
  - Q
- - '####'
  - '`query` 参数，`findandmodify()`'
- - '###'
  - 查询性能
- - '####'
  - Quorum
- - '##'
  - R
- - '####'
  - '`remove` 参数，`findandmodify()`'
- - '###'
  - 复制
- - '##'
  - S
- - '###'
  - 分片
- - '####'
  - 分片键
- - '####'
  - '`$slice` 投影操作符'
- - '####'
  - Snowball 字符串处理语言
- - '####'
  - '`sort` 参数，`findandmodify()`'
- - '####'
  - 字符串数据类型
- - '####'
  - 字符串字面量搜索
- - '####'
  - 符号数据类型
- - '##'
  - T
- - '####'
  - 时间戳数据类型
- - '####'
  - 生存时间
- - '##'
  - U, V
- - '####'
  - 当前更新方法
- - '####'
  - '`update` 参数，`findandmodify()`'
- - '###'
  - 更新数据
- - '##'
  - W, X, Y, Z
