name: Pro ASP.Net for SQL server
name_cn: SQL server 的 ASP.Net 高级指南
slug: pro-aspnet-for-sql-server
toc:
- - '#'
  - 高级 ASP.NET SQL Server 开发：面向 Web 开发人员的高性能数据访问技术
- - '##'
  - 目录
- - '###'
  - 第 1 章：入门准备
- - '####'
  - 准备您的环境
- - '####'
  - 项目组织
- - '####'
  - 常用文件夹
- - '####'
  - 数据源配置
- - '####'
  - 代码与数据库分离
- - '####'
  - 管理提供程序服务
- - '####'
  - 使用命令行
- - '####'
  - 混合与匹配提供程序
- - '####'
  - 配置提供程序
- - '####'
  - 成员资格配置
- - '####'
  - 角色配置
- - '####'
  - 配置文件配置
- - '####'
  - 创建用户和角色
- - '####'
  - 保护管理区域
- - '####'
  - 创建管理员用户
- - '####'
  - 总结
- - '###'
  - 第 2 章：数据模型选择
- - '####'
  - 数据访问应用程序块
- - '####'
  - 数据访问代码片段
- - '####'
  - 示例数据库
- - '####'
  - 简单数据示例
- - '####'
  - 复杂数据示例
- - '#####'
  - 类型化 DataSet
- - '#####'
  - 非类型化 DataSet
- - '#####'
  - DataReader
- - '#####'
  - DataObject
- - '####'
  - 有何缺点？
- - '####'
  - 总结
- - '###'
  - 第 3 章：数据库管理
- - '####'
  - 使用数据库项目
- - '#####'
  - Visual Studio
- - '#####'
  - SQL Server Management Studio
- - '####'
  - 管理存储过程
- - '####'
  - 管理索引与约束
- - '####'
  - 性能考量
- - '####'
  - 稳定性考量
- - '####'
  - 数据单元测试
- - '####'
  - 持续集成
- - '####'
  - 总结
- - '###'
  - 第 4 章：数据绑定控件
- - '####'
  - DetailsView
- - '####'
  - FormView
- - '####'
  - GridView
- - '####'
  - 编辑与验证字段
- - '####'
  - 绑定输入参数
- - '#####'
  - 使用控件绑定输入参数
- - '#####'
  - 通过编程绑定输入参数
- - '#####'
  - 绑定用户控件
- - '####'
  - 嵌入数据绑定控件
- - '#####'
  - ViewState 与数据绑定
- - '####'
  - 会话与视图状态
- - '####'
  - 分页
- - '####'
  - 禁用视图状态
- - '####'
  - 控件状态与视图状态
- - '####'
  - 创建数据绑定控件
- - '#####'
  - 获取数据
- - '#####'
  - 获取总行数
- - '#####'
  - 连接分页器事件
- - '#####'
  - 创建 PersonRow 类
- - '#####'
  - 手动持久化视图状态
- - '#####'
  - 在无视图状态下工作
- - '#####'
  - 单步调试
- - '####'
  - 总结
- - '###'
  - 第 5 章：SQL 提供程序
- - '####'
  - SqlMembershipProvider 提供程序
- - '#####'
  - 使用 XML 实现
- - '#####'
  - 设置数据库连接
- - '#####'
  - 创建密码策略
- - '####'
  - SqlRoleProvider 提供程序
- - '#####'
  - 按角色控制访问
- - '#####'
  - 按角色控制行为
- - '####'
  - SqlProfileProvider 提供程序
- - '#####'
  - 为何使用匿名配置文件？
- - '#####'
  - 配置匿名配置文件
- - '#####'
  - 管理匿名配置文件
- - '#####'
  - 匿名与已验证配置文件的差异
- - '#####'
  - 从匿名迁移到已验证
- - '#####'
  - 创建用户
- - '#####'
  - 动态配置文件与作为 BLOB 的配置文件
- - '####'
  - 使用提供程序驱动的 ASP.NET 控件
- - '####'
  - 构建 SQL 相册提供程序
- - '#####'
  - 提供程序要求
- - '#####'
  - 配置节类
- - '#####'
  - 提供程序集合类
- - '#####'
  - 抽象提供程序类
- - '#####'
  - 提供程序实现
- - '#####'
  - 提供程序服务类
- - '#####'
  - 单元测试
- - '#####'
  - 最终产品
- - '####'
  - 构建 SQL 站点地图提供程序
- - '###'
  - 第 6 章：缓存
- - '####'
  - 缓存
- - '#####'
  - 缓存替代方案
- - '######'
  - 应用程序状态
- - '######'
  - 会话
- - '######'
  - 视图状态
- - '######'
  - 当前上下文
- - '####'
  - 缓存选项
- - '#####'
  - 输出缓存
- - '#####'
  - 数据缓存
- - '#####'
  - 使缓存数据失效
- - '######'
  - 绝对过期
- - '######'
  - 滑动过期
- - '######'
  - 缓存依赖
- - '######'
  - 手动移除
- - '#####'
  - SQL 缓存依赖
- - '######'
  - 使用 SqlDependency 和 SqlCacheDependency
- - '######'
  - 轮询
- - '######'
  - 查询通知
- - '######'
  - 查询通知故障排除
- - '#####'
  - 缓存存在的问题
- - '#####'
  - 性能策略
- - '######'
  - 数据仓库
- - '######'
  - 延迟加载
- - '####'
  - 总结
- - '###'
  - 第 7 章：手动数据访问层
- - '####'
  - 使用数据集、内联 SQL 和存储过程
- - '#####'
  - 数据集
- - '#####'
  - 内联 SQL
- - '#####'
  - 存储过程
- - '####'
  - 使用数据对象和对象数据源
- - '#####'
  - 设计约定
- - '#####'
  - 数据约定
- - '#####'
  - 测试设计和数据约定
- - '####'
  - 构建数据库
- - '#####'
  - 创建数据库结构
- - '####'
  - 整合数据
- - '####'
  - 管理关系
- - '####'
  - 创建与修改
- - '####'
  - 空值如何处理？
- - '####'
  - 使用数据库项目
- - '####'
  - 数据访问层
- - '####'
  - 构建网站
- - '#####'
  - 连接数据访问层
- - '#####'
  - 创建用户控件
- - '#####'
  - 创建页面
- - '####'
  - 总结
- - '###'
  - 第 8 章：生成数据访问层
- - '####'
  - 代码生成
- - '####'
  - 构建提供程序
- - '####'
  - CodeDom 命名空间
- - '####'
  - 模板化
- - '####'
  - SubSonic
- - '#####'
  - SubSonic 模板化
- - '####'
  - 分部类
- - '####'
  - 查询工具
- - '####'
  - 脚手架
- - '####'
  - Blinq
- - '####'
  - 总结
- - '###'
  - 第 9 章：部署
- - '####'
  - 使用 MSBuild 实现自动化
- - '####'
  - 部署网站
- - '#####'
  - 网站部署项目
- - '#####'
  - 自动化配置更改
- - '#####'
  - 构建后部署
- - '####'
  - 部署数据库
- - '#####'
  - 生成变更脚本
- - '#####'
  - 自动化数据库更新
- - '#####'
  - 自定义配置节
- - '####'
  - 总结
- - '###'
  - 第 10 章：示例应用
- - '####'
  - 理解性能与可伸缩性
- - '#####'
  - 并发请求
- - '#####'
  - 瓶颈
- - '#####'
  - 流量峰值
- - '#####'
  - 分配流量
- - '#####'
  - 分配内容
- - '#####'
  - 分配服务
- - '#####'
  - 分配后端
- - '#####'
  - 规划可伸缩性
- - '####'
  - 示例应用程序
- - '#####'
  - 创建数据库
- - '#####'
  - 获取、保存与删除
- - '####'
  - 创建数据访问提供程序
- - '#####'
  - EventProvider 对象
- - '#####'
  - 修订后的 DomainObject
- - '####'
  - 管理关系
- - '####'
  - 使用位置
- - '####'
  - 自定义配置
- - '#####'
  - 配置分组
- - '#####'
  - 声明自定义配置
- - '#####'
  - 配置提供程序
- - '####'
  - 创建新的提供程序
- - '#####'
  - 实现 LINQ 提供程序
- - '#####'
  - 实现 WCF 提供程序
- - '######'
  - WCF 服务要求
- - '######'
  - 托管服务
- - '######'
  - 定义数据契约
- - '######'
  - 配置提供程序
- - '####'
  - 使用提供程序
- - '####'
  - 总结
- - '###'
  - 附录
- - '####'
  - 照片相册
- - '#####'
  - 照片相册提供程序
- - '######'
  - 配置
- - '######'
  - 类
- - '######'
  - 表脚本
- - '######'
  - 约束脚本
- - '######'
  - 存储过程脚本
- - '######'
  - 网站类
- - '####'
  - SQL 站点地图提供程序
- - '#####'
  - 类
- - '#####'
  - 表脚本
- - '#####'
  - 存储过程脚本
- - '###'
  - 索引
- - '####'
  - 数字和符号
- - '####'
  - A
- - '####'
  - B
- - '####'
  - C
- - '####'
  - D
- - '####'
  - E
- - '####'
  - F
- - '####'
  - G
- - '####'
  - H
- - '####'
  - I
- - '####'
  - J
- - '####'
  - K
- - '####'
  - L
- - '####'
  - M
- - '####'
  - N
- - '####'
  - O
- - '####'
  - P
- - '####'
  - Q
- - '####'
  - R
- - '####'
  - S
- - '####'
  - T
- - '####'
  - U
- - '####'
  - V
- - '####'
  - W
- - '####'
  - X
- - '####'
  - Z
