name: Azure SQL Revealed
name_cn: Azure SQL 揭秘
slug: azure-sql-revealed
toc:
- - '#'
  - 前言
- - '#'
  - 引言
- - '#'
  - 1. SQL Server 登陆云端
- - '##'
  - CloudDB
- - '##'
  - 红狗项目
- - '##'
  - Azure 服务平台
- - '##'
  - 走向 SQL Azure 之路
- - '###'
  - SQL 数据服务
- - '###'
  - SQL Azure 诞生
- - '###'
  - SAWA 项目
- - '##'
  - 虚拟机计划
- - '#'
  - 演进中的 Azure SQL 数据库
- - '##'
  - Sterling (SAWAv2) 项目
- - '##'
  - Rohan Kumar 与代码库合并
- - '##'
  - Sterling 部署架构
- - '##'
  - Windows Fabric 的优势
- - '##'
  - 新的 Azure 门户
- - '###'
  - 新版本、DTU 与预览版
- - '###'
  - 智能性能与 MDCS
- - '#'
  - Azure SQL：安全演进与工程创新
- - '##'
  - 高级数据安全与 ILDC 团队
- - '##'
  - 一个名为 Ibiza 的未来之窗
- - '##'
  - Azure 的新工程模型
- - '##'
  - 拓展 Azure SQL 数据库的可能性
- - '##'
  - 将客户迁移到云端
- - '##'
  - 苏格拉底项目走向超大规模
- - '##'
  - 当下的 Azure SQL
- - '##'
  - 本章小结
- - '#'
  - 2. 什么是 Azure SQL？
- - '##'
  - Azure 生态系统
- - '###'
  - Azure 账户、租户和订阅
- - '###'
  - Azure 门户
- - '###'
  - Azure 市场
- - '###'
  - Azure API 和 CLI
- - '###'
  - Azure 资源管理器 (ARM)
- - '###'
  - Azure Monitor
- - '##'
  - Azure SQL 是什么？
- - '##'
  - Azure 区域和数据中心
- - '##'
  - Azure 的信任、隐私与合规性
- - '##'
  - Azure 服务级别协议（SLA）
- - '##'
  - IaaS 与 PaaS
- - '##'
  - Azure SQL 产品线
- - '###'
  - SQL 虚拟机
- - '###'
  - 托管实例
- - '###'
  - 数据库
- - '##'
  - Azure SQL 托管实例
- - '###'
  - 托管实例功能
- - '###'
  - 托管实例选项和限制
- - '###'
  - 通用目的
- - '###'
  - 业务关键
- - '####'
  - 托管实例池
- - '####'
  - 托管实例与 Azure 虚拟机上的 SQL Server
- - '####'
  - 使用托管实例的客户
- - '##'
  - Azure SQL Database
- - '###'
  - Azure SQL Database 功能
- - '###'
  - Azure SQL Database 选项与限制
- - '####'
  - 弹性池或单一数据库
- - '####'
  - DTU 与 vCore
- - '####'
  - 常规用途服务层级
- - '####'
  - 无服务器
- - '####'
  - 业务关键型
- - '####'
  - 超大规模
- - '####'
  - 弹性池数据库
- - '###'
  - Azure Database Fleet Manager（数据库舰队管理器）
- - '###'
  - Azure SQL Database 与 Azure SQL Managed Instance
- - '###'
  - 使用 Azure SQL Database 的客户
- - '##'
  - Azure SQL 的接口
- - '###'
  - Azure 门户
- - '###'
  - az CLI
- - '###'
  - PowerShell
- - '###'
  - REST API
- - '###'
  - TDS 和 T-SQL
- - '###'
  - SQL CLI
- - '###'
  - SQL Server Management Studio (SSMS)
- - '###'
  - Visual Studio Tools
- - '##'
  - 超越 RDBMS
- - '##'
  - 摘要
- - '#'
  - 3. Azure 虚拟机上的 SQL Server
- - '##'
  - 部署
- - '###'
  - 定价
- - '###'
  - SQL Server 库映像
- - '###'
  - 资源组、区域和可用性
- - '####'
  - 资源组
- - '####'
  - 虚拟机名称
- - '####'
  - 区域
- - '####'
  - 可用性选项
- - '####'
  - 安全类型
- - '####'
  - 映像
- - '####'
  - VM 架构
- - '###'
  - 竞价实例
- - '###'
  - 虚拟机大小
- - '###'
  - 账户、端口和操作系统许可
- - '###'
  - 作为部署一部分进行配置选择
- - '####'
  - 操作系统磁盘
- - '####'
  - 网络
- - '##'
  - 管理
- - '##'
  - 监控
- - '##'
  - 高级
- - '#'
  - SQL Server 设置
- - '##'
  - 网络
- - '##'
  - SQL 身份验证
- - '##'
  - Azure 密钥保管库集成
- - '##'
  - 存储配置
- - '##'
  - SQL Server 实例设置
- - '##'
  - SQL Server 许可证
- - '##'
  - 标签
- - '##'
  - 部署！
- - '###'
  - 在门户中导航 Azure 虚拟机
- - '###'
  - 连接到你的虚拟机
- - '###'
  - 探索 SQL Server 安装
- - '####'
  - 安装内容
- - '####'
  - 配置内容
- - '###'
  - 自行部署
- - '###'
  - SQL Server IaaS 代理扩展
- - '###'
  - 使用 CLI 与 ARM 模板、Bison 和 Terraform
- - '###'
  - 预留实例、专用主机和容量预留
- - '###'
  - 迁移至 Azure
- - '####'
  - Azure Arc 迁移评估
- - '####'
  - 还原数据库
- - '####'
  - Azure Migrate 和 Azure 数据库迁移服务
- - '####'
  - 使用 Azure Migrate 服务器迁移
- - '##'
  - SQL Server IaaS 代理扩展
- - '###'
  - 部署 SQL Server 容器
- - '###'
  - 设置
- - '####'
  - 配置
- - '####'
  - 存储
- - '####'
  - 更新
- - '####'
  - 备份
- - '####'
  - 高可用性
- - '#'
  - SQL 最佳实践评估
- - '##'
  - 安全性
- - '###'
  - 安全性配置
- - '###'
  - Microsoft Defender for Cloud
- - '#'
  - 配置 Azure 虚拟机
- - '##'
  - 停止与解除分配
- - '##'
  - 调整大小
- - '##'
  - 安全性 (RBAC)
- - '###'
  - 其他配置选项
- - '##'
  - 最大化存储性能
- - '###'
  - 最佳实践
- - '###'
  - 高级 SSD v2
- - '###'
  - 了解更多
- - '##'
  - 性能监控
- - '#'
  - Azure 指标
- - '#'
  - 洞察
- - '#'
  - 网络
- - '#'
  - 高可用性与灾难恢复
- - '##'
  - Azure 存储
- - '###'
  - 备份
- - '###'
  - 提升 Azure 可用性
- - '###'
  - Always On 故障转移群集实例
- - '###'
  - Always On 可用性组
- - '###'
  - SQL Server 与 Linux 高可用性
- - '##'
  - Microsoft 创新与 Azure Boost
- - '##'
  - 本章摘要
- - '#'
  - 4. 部署 Azure SQL
- - '##'
  - 部署前规划
- - '###'
  - 新部署还是迁移
- - '###'
  - 做出部署选择
- - '####'
  - 免费部署
- - '#####'
  - Azure SQL 托管实例免费试用版
- - '#####'
  - Azure SQL 数据库免费优惠
- - '###'
  - 部署方法
- - '###'
  - 部署选项
- - '###'
  - 区域
- - '###'
  - 购买模型
- - '###'
  - 服务层级 (SLO)
- - '###'
  - 硬件
- - '###'
  - vCore 和存储大小
- - '####'
  - 价格
- - '###'
  - 考虑资源限制
- - '##'
  - 部署 Azure SQL 托管实例
- - '###'
  - 部署过程演练
- - '###'
  - 基础配置
- - '###'
  - 网络配置
- - '####'
  - 虚拟网络
- - '###'
  - 连接类型
- - '###'
  - 公共端点
- - '###'
  - 安全性
- - '###'
  - 附加设置
- - '###'
  - 标签
- - '###'
  - 部署！
- - '###'
  - 使用 CLI 部署
- - '###'
  - 实现细节
- - '###'
  - 连接并验证部署
- - '##'
  - 连接到托管实例
- - '###'
  - bwsqlminextgen.b243ea7f888c.database.windows.net
- - '##'
  - 验证部署
- - '###'
  - 检查 ERRORLOG
- - '###'
  - 验证查询
- - '##'
  - 迁移到 Azure SQL 托管实例
- - '##'
  - 部署 Azure SQL 数据库
- - '###'
  - 部署与选项
- - '####'
  - 基本
- - '#####'
  - 服务层级
- - '#####'
  - 计算层级
- - '#####'
  - 硬件配置
- - '#####'
  - vCores
- - '#####'
  - HA 副本和区域冗余
- - '#####'
  - 其他选择
- - '####'
  - 网络
- - '####'
  - 安全
- - '####'
  - 附加设置
- - '####'
  - 标记
- - '####'
  - 开始部署！
- - '###'
  - 部署无服务器版
- - '###'
  - 部署弹性池
- - '###'
  - 使用 CLI 部署
- - '###'
  - 实现细节
- - '####'
  - 专用环与实例
- - '####'
  - 逻辑服务器
- - '##'
  - 存储、计算与网关
- - '##'
  - 无服务器
- - '##'
  - 超大规模
- - '##'
  - 资源治理
- - '###'
  - SQL Server 资源治理器
- - '###'
  - 引擎增强
- - '###'
  - Windows 作业对象
- - '#####'
  - 文件源资源管理器 (FSRM)
- - '###'
  - 连接并验证部署
- - '####'
  - 连接到 Azure SQL 数据库
- - '####'
  - 验证部署
- - '#####'
  - 注意
- - '#####'
  - 注意
- - '#####'
  - 注意
- - '##'
  - 迁移到 Azure SQL Database
- - '##'
  - 总结
- - '#'
  - 5. 配置 Azure SQL
- - '##'
  - 配置 Azure SQL 托管实例
- - '###'
  - sp_configure
- - '###'
  - 跟踪标志
- - '###'
  - Tempdb
- - '###'
  - Master 和 Model
- - '###'
  - 配置版本
- - '###'
  - 计算与存储
- - '###'
  - 网络配置
- - '###'
  - 维护
- - '###'
  - 启动和停止
- - '###'
  - 配置数据库
- - '##'
  - 配置 Azure SQL 数据库
- - '#'
  - Azure SQL 数据库管理
- - '##'
  - 创建新数据库
- - '##'
  - 修改数据库
- - '##'
  - 网络配置
- - '###'
  - 配置无服务器
- - '###'
  - 配置弹性池
- - '##'
  - 配置限制
- - '###'
  - Azure SQL 托管实例限制
- - '####'
  - 启动和停止服务
- - '####'
  - 即时文件初始化
- - '####'
  - 锁定页面
- - '####'
  - FILESTREAM 和可用性组
- - '####'
  - 服务器排序规则
- - '####'
  - 启动参数
- - '####'
  - ERRORLOG 配置
- - '####'
  - 错误报告和客户反馈
- - '####'
  - ALTER SERVER CONFIGURATION
- - '###'
  - “混合模式”安全
- - '###'
  - 登录审核
- - '###'
  - 服务器代理帐户
- - '###'
  - 数据库限制
- - '###'
  - Azure SQL 数据库限制
- - '##'
  - Azure SQL 空间管理
- - '###'
  - Azure SQL 托管实例空间管理
- - '###'
  - Azure SQL 数据库空间管理
- - '##'
  - 加载数据
- - '###'
  - 请牢记这些要点
- - '###'
  - bcp
- - '###'
  - BULK INSERT 与 OPENROWSET
- - '###'
  - SQL Server Integration Services (SSIS)
- - '####'
  - Azure SSIS
- - '##'
  - BACPAC
- - '##'
  - 数据库复制
- - '##'
  - 还原到托管实例
- - '##'
  - Spark 连接器
- - '##'
  - Azure Data Factory (ADF)
- - '##'
  - 更新 Azure SQL
- - '###'
  - Azure SQL 的维护
- - '###'
  - Azure SQL 托管实例的更新策略
- - '###'
  - Azure SQL 中的新功能和特性
- - '####'
  - 总结
- - '#'
  - 6. 保障 Azure SQL 的安全
- - '##'
  - 网络安全
- - '##'
  - 身份验证与访问
- - '##'
  - 数据保护
- - '##'
  - 安全管理
- - '##'
  - 网络安全
- - '###'
  - Azure SQL 托管实例网络安全
- - '###'
  - 公共终结点
- - '###'
  - VNet-本地端点
- - '###'
  - 专用端点
- - '###'
  - 其他注意事项
- - '###'
  - Azure SQL 数据库网络安全
- - '###'
  - 使用公共端点
- - '###'
  - 使用专用链接
- - '##'
  - 身份验证与访问
- - '###'
  - Azure 基于角色的访问控制 (RBAC)
- - '###'
  - SQL DB 参与者
- - '###'
  - SQL Server 参与者
- - '###'
  - SQL 安全管理器
- - '###'
  - SQL 托管实例参与者
- - '###'
  - Azure SQL 托管实例的身份验证
- - '####'
  - Microsoft Entra 身份验证
- - '####'
  - Windows 身份验证
- - '###'
  - Azure SQL 数据库的身份验证
- - '####'
  - 使用包含用户
- - '###'
  - Microsoft Entra 身份验证
- - '###'
  - 托管标识
- - '####'
  - 设置和配置访问
- - '###'
  - Microsoft Purview
- - '##'
  - 数据保护
- - '###'
  - 加密连接
- - '###'
  - 透明数据加密 (TDE)
- - '####'
  - 自带密钥（BYOK）
- - '###'
  - Always Encrypted
- - '###'
  - 动态数据屏蔽（DDM）
- - '#'
  - SQL 账本
- - '##'
  - 安全管理
- - '###'
  - SQL 外部的活动监控
- - '###'
  - 审计 Azure SQL 托管实例
- - '####'
  - 跟踪登录
- - '###'
  - SQL Server 审核
- - '###'
  - 审核 Azure SQL Database
- - '####'
  - 跟踪连接
- - '####'
  - SQL 数据库审核
- - '##'
  - Microsoft Defender for SQL
- - '###'
  - 漏洞评估
- - '#'
  - SQL 威胁防护
- - '#'
  - 数据分类
- - '#'
  - 总结
- - '#'
  - 7. Azure SQL 的性能监控与调优
- - '##'
  - 性能功能
- - '###'
  - 最大容量
- - '###'
  - 索引
- - '###'
  - 内存中 OLTP
- - '##'
  - 分区
- - '##'
  - SQL Server 2022 增强功能
- - '##'
  - 智能性能
- - '##'
  - 性能配置与维护
- - '###'
  - Tempdb
- - '###'
  - 数据库配置
- - '###'
  - 文件与文件组
- - '###'
  - 最大并行度
- - '###'
  - 资源调控器
- - '###'
  - 维护索引
- - '###'
  - 维护统计信息
- - '##'
  - 监控与故障排除性能
- - '###'
  - 监控工具与功能
- - '#'
  - Azure SQL 性能监控与诊断工具
- - '##'
  - Azure Monitor
- - '##'
  - 动态管理视图 (DMVs)
- - '##'
  - 扩展事件 (XEvent)
- - '##'
  - 轻量级查询分析
- - '##'
  - 查询计划调试
- - '##'
  - 查询存储
- - '##'
  - Azure 门户中的性能可视化
- - '##'
  - 数据库监视器
- - '#'
  - Azure SQL 数据库中的 Microsoft Copilot 技能
- - '##'
  - 深入了解 DMV 和扩展事件
- - '###'
  - DMV 深入探讨
- - '####'
  - Azure SQL 托管实例
- - '####'
  - Azure SQL 数据库
- - '##'
  - 你需要了解的 DMVs
- - '##'
  - 用于深度故障排除的 DMVs
- - '##'
  - XEvent 为你服务
- - '###'
  - 适用于 Azure SQL 扩展事件
- - '###'
  - 适用于 Azure SQL 数据库的扩展事件
- - '##'
  - 性能场景
- - '###'
  - 正在运行 vs. 正在等待
- - '####'
  - Azure 门户/PowerShell/警报
- - '###'
  - sys.dm_db_resource_stats
- - '###'
  - sys.server_resource_stats
- - '####'
  - 使用 Copilot 入手
- - '####'
  - 运行中
- - '#####'
  - Query Store
- - '#####'
  - sys.dm_exec_requests
- - '#####'
  - sys.dm_exec_query_stats
- - '#####'
  - sys.dm_exec_procedure_stats
- - '#####'
  - Azure SQL Database 中的 Microsoft Copilot 技能
- - '##'
  - 数据库监视器
- - '##'
  - 等待
- - '###'
  - sys.dm_os_wait_stats
- - '###'
  - sys.dm_exec_requests
- - '###'
  - sys.dm_os_waiting_tasks
- - '###'
  - 查询存储
- - '###'
  - Azure SQL 数据库和数据库监视器中的 Microsoft Copilot 技能
- - '##'
  - 性能示例
- - '###'
  - Azure SQL 特定性能场景
- - '####'
  - 日志治理
- - '####'
  - 工作线程限制
- - '####'
  - 业务关键版 (BC) HADR 等待
- - '####'
  - 超大规模场景
- - '###'
  - 加速与性能调优
- - '#'
  - 扩展 CPU 容量
- - '##'
  - 查看 Azure 门户中的扩展选项
- - '##'
  - 让我们再次运行工作负载
- - '##'
  - 使用 `sys.dm_db_resource_stats` 观察资源使用情况
- - '##'
  - 使用 `sys.dm_exec_requests` 观察活动查询
- - '##'
  - 观察整个工作负载的持续时间
- - '##'
  - 让我们简要看一下 Azure 指标
- - '###'
  - 调优 I/O 性能
- - '###'
  - 增加内存或工作线程数
- - '###'
  - 改善应用程序延迟
- - '###'
  - 像调优 SQL Server 一样调优
- - '###'
  - 智能性能
- - '##'
  - 智能查询处理
- - '##'
  - 自动计划纠正
- - '###'
  - 自动调优
- - '##'
  - 总结
- - '#'
  - 8. Azure SQL 的可用性
- - '##'
  - HADR 功能
- - '###'
  - 自动备份和时间点还原
- - '#'
  - Azure SQL 高可用性与备份
- - '##'
  - 内置可用性
- - '##'
  - 区域冗余用于高可用性
- - '##'
  - 地理复制与故障转移组
- - '##'
  - 数据库可用性与一致性
- - '##'
  - 使用托管实例链接进行灾难恢复
- - '##'
  - 免费被动灾难恢复副本
- - '##'
  - SQL Server 复制
- - '##'
  - 备份与恢复
- - '###'
  - 自动备份
- - '####'
  - 本地冗余存储（`LRS`）
- - '####'
  - 区域冗余存储（`ZRS`）
- - '####'
  - 地理冗余存储（`GRS`）
- - '###'
  - 地理区域冗余存储 (GZRS)
- - '###'
  - 备份保留期
- - '###'
  - 自动备份
- - '###'
  - 备份存储消耗与成本
- - '##'
  - 时间点恢复 (PITR)
- - '###'
  - 删除表
- - '###'
  - 将数据库恢复到删除操作之前的时间点
- - '###'
  - 验证新数据库已恢复被删除的表
- - '#'
  - Azure SQL 的地理恢复与还原操作
- - '###'
  - 数据库的地理恢复
- - '###'
  - 从已删除的数据库还原备份
- - '###'
  - 在 Azure SQL 托管实例中还原
- - '##'
  - 内置可用性
- - '###'
  - 通用型可用性
- - '###'
  - 业务关键型可用性
- - '##'
  - 故障转移测试
- - '##'
  - 超大规模可用性
- - '##'
  - Azure SQL Hyperscale 架构
- - '##'
  - 使用 Azure 扩展 HADR
- - '##'
  - 区域冗余
- - '##'
  - 地理复制
- - '##'
  - 灾难恢复与异地复制
- - '###'
  - 故障转移组
- - '#'
  - Azure SQL 故障转移组与托管实例链接
- - '##'
  - 故障转移组策略
- - '##'
  - 使用托管实例链接进行灾难恢复
- - '###'
  - 离线灾难恢复
- - '###'
  - 在线灾难恢复
- - '###'
  - Azure SQL SLA（服务级别协议）
- - '##'
  - 数据库可用性与一致性
- - '###'
  - 数据库可用性
- - '###'
  - 加速数据库恢复 (ADR)
- - '###'
  - 数据库一致性
- - '##'
  - 监控可用性
- - '###'
  - 实例、服务器和数据库可用性
- - '###'
  - 备份和恢复历史记录
- - '##'
  - 区域、数据中心和服务可用性
- - '##'
  - 可用性指标
- - '##'
  - 副本状态
- - '###'
  - 故障转移原因
- - '###'
  - 小结
- - '#'
  - 9. 扩展 Azure SQL 知识
- - '##'
  - Azure SQL 的功能范围
- - '###'
  - 链接服务器和跨数据库查询
- - '###'
  - 外部表
- - '##'
  - 数据库邮件
- - '#'
  - Service Broker
- - '#'
  - 全文搜索
- - '#'
  - 机器学习服务
- - '#'
  - 分布式事务 (DTC)
- - '#'
  - xp_cmdshell
- - '#'
  - 作业管理
- - '###'
  - SQL Server 代理
- - '###'
  - 弹性作业
- - '###'
  - Azure 自动化
- - '##'
  - 支持 Azure SQL
- - '###'
  - 处理错误
- - '###'
  - 堆栈转储
- - '###'
  - Azure 门户中的故障排除资源
- - '###'
  - UserVoice
- - '##'
  - Azure SQL 最佳实践
- - '###'
  - 安全手册
- - '###'
  - 性能最佳实践
- - '##'
  - Azure Advisor
- - '##'
  - 了解新功能
- - '##'
  - 与我们的团队保持联系
- - '##'
  - 总结
- - '#'
  - 10. 超越关系数据库管理系统
- - '##'
  - “这是‘箱中自带’的功能吗？”
- - '###'
  - JSON
- - '####'
  - JSON_ARRAYAGG
- - '####'
  - JSON_OBJECTAGG
- - '###'
  - 正则表达式
- - '###'
  - 空间与图形
- - '###'
  - 列存储与内存优化
- - '###'
  - 总账本
- - '###'
  - 查询智能
- - '##'
  - REST API 集成
- - '##'
  - 数据 API 生成器与 GraphQL
- - '##'
  - DevOps、GitHub 与容器
- - '###'
  - 数据库项目
- - '###'
  - GitHub Actions
- - '#'
  - 容器
- - '##'
  - SQL 与 AI
- - '###'
  - GenAI 与 SQL
- - '####'
  - 使用 AI 服务
- - '####'
  - 使用 T-SQL 进行混合搜索
- - '##'
  - SQL 与生成式 AI 集成：关键考量
- - '####'
  - 使用框架
- - '####'
  - 聊天历史如何处理？
- - '####'
  - 您的文本数据存储在哪里？
- - '####'
  - 资源
- - '###'
  - 自然语言转 SQL 查询
- - '##'
  - SQL 与 Microsoft Fabric
- - '##'
  - Azure Arc
- - '##'
  - 前景展望
- - '###'
  - 小型语言模型 (SLM) 的使用
- - '###'
  - NL2QL 框架
- - '###'
  - 生成式人工智能从本地到云端
- - '###'
  - 更多且增强的 Copilot 体验
- - '###'
  - JSON 和向量的增强功能
- - '###'
  - 持续投资 Microsoft Fabric
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y
- - '##'
  - Z
