name: MongoDB Recipes
name_cn: MongoDB 秘籍
slug: mongodb-recipes
toc:
- - '#'
  - 引言
- - '##'
  - 为什么选择这本书？
- - '##'
  - 本书适合哪些读者？
- - '##'
  - 本书的组织结构
- - '##'
  - 如何从本书中获得最大收益？
- - '##'
  - 致谢
- - '###'
  - 关于作者与技术审稿人
- - '###'
  - 关于作者
- - '###'
  - 关于技术审稿人
- - '#'
  - 1. MongoDB 特性与安装
- - '##'
  - 对 NoSQL 数据库的需求
- - '##'
  - 什么是 NoSQL 数据库？
- - '###'
  - CAP 定理
- - '####'
  - 注意
- - '###'
  - BASE 方法
- - '###'
  - NoSQL 数据库的类型
- - '##'
  - MongoDB 特性
- - '###'
  - 文档数据库
- - '###'
  - MongoDB 是无模式的
- - '###'
  - MongoDB 使用 BSON
- - '###'
  - 丰富的查询语言
- - '###'
  - 聚合框架
- - '###'
  - 索引
- - '###'
  - GridFS
- - '###'
  - 复制
- - '###'
  - 分片
- - '###'
  - mongo Shell
- - '##'
  - MongoDB 中使用的术语
- - '##'
  - MongoDB 中的数据类型
- - '####'
  - 注意
- - '##'
  - MongoDB 安装
- - '###'
  - 教程 1-1. 在 Windows 上安装 MongoDB
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：安装 `msi` 安装程序
- - '#####'
  - 步骤 2：创建数据目录
- - '#####'
  - 步骤 3：启动 MongoDB 服务器
- - '#####'
  - 步骤 4：启动 MongoDB 客户端
- - '###'
  - 教程 1-2. 在 Ubuntu 上安装 MongoDB
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：解压 tarball
- - '#####'
  - 步骤 2：创建数据目录
- - '#####'
  - 步骤 3：启动 MongoDB 服务器
- - '#####'
  - 步骤 4：启动 MongoDB 客户端
- - '###'
  - 教程 1-3. 在 Windows 上安装 MongoDB Compass
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：安装 MongoDB Compass `msi` 安装程序
- - '#####'
  - 步骤 2：启动 MongoDB 服务器
- - '#####'
  - 注意
- - '#####'
  - 步骤 3：将 MongoDB Compass 连接到 MongoDB 服务器
- - '##'
  - 使用数据库命令
- - '###'
  - 教程 1-4. 创建数据库
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：创建一个数据库
- - '###'
  - 教程 1-5. 删除数据库
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：删除一个数据库
- - '#####'
  - 注意
- - '###'
  - 配方 1-6. 显示数据库列表
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：显示数据库列表
- - '#####'
  - 注意
- - '###'
  - 配方 1-7. 显示 MongoDB 版本
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：显示 MongoDB 版本
- - '###'
  - 配方 1-8. 显示命令列表
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：显示命令列表
- - '#####'
  - 注意
- - '#'
  - 2. MongoDB CRUD 操作
- - '##'
  - 集合
- - '###'
  - 配方 2-1. 创建集合
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：创建集合
- - '###'
  - 配方 2-2. 创建固定集合
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：创建固定集合
- - '#####'
  - 步骤 2：查询固定集合
- - '#####'
  - 步骤 3：向已满的固定集合插入文档
- - '##'
  - 创建操作
- - '###'
  - 配方 2-3. 插入文档
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：插入单个文档
- - '#####'
  - 步骤 2：插入多个文档
- - '##'
  - 读操作
- - '###'
  - 配方 2-4. 查询文档
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：选择集合中的所有文档
- - '#####'
  - 步骤 2：指定相等条件
- - '#####'
  - 步骤 3：使用查询操作符指定条件
- - '#####'
  - 步骤 4：指定 AND 条件
- - '#####'
  - 步骤 5：指定 OR 条件
- - '##'
  - 更新操作
- - '###'
  - 配方 2-5. 更新文档
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：更新单个文档
- - '#####'
  - 注意
- - '#####'
  - 步骤 2：更新多个文档
- - '#####'
  - 步骤 3：替换文档
- - '#####'
  - 注意
- - '##'
  - 删除操作
- - '###'
  - 配方 2-6. 删除文档
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：删除匹配条件的单个文档
- - '#####'
  - 步骤 2：删除所有匹配条件的文档
- - '#####'
  - 步骤 3：删除集合中的所有文档
- - '##'
  - MongoDB 导入与导出
- - '###'
  - 配方 2-7. 使用 Mongo Import
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 注意
- - '####'
  - 工作原理
- - '###'
  - 配方 2-8. 使用 Mongo Export
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 注意
- - '####'
  - 工作原理
- - '##'
  - MongoDB 中的嵌入式文档
- - '###'
  - 配方 2-9. 查询嵌入式文档
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：匹配嵌入式或嵌套文档
- - '#####'
  - 步骤 2：查询嵌套字段
- - '##'
  - 处理数组
- - '###'
  - 配方 2-10. 处理数组
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '###'
  - MongoDB 数组操作指南
- - '####'
  - 步骤 1：匹配数组
- - '####'
  - 步骤 2：查询数组中的元素
- - '####'
  - 步骤 3：指定查询操作符
- - '####'
  - 步骤 4：对数组元素使用复合筛选条件
- - '####'
  - 步骤 5：使用 `$elemMatch` 操作符
- - '####'
  - 步骤 6：按索引位置查询数组元素
- - '####'
  - 步骤 7：使用 `$size` 操作符
- - '####'
  - 步骤 8：使用 `$push` 操作符
- - '####'
  - 步骤 9：使用 `$addToSet` 操作符
- - '####'
  - 步骤 10：使用 `$pop` 操作符
- - '###'
  - 配方 2-11. 查询嵌入文档数组
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：查询数组中的文档
- - '#####'
  - 注意
- - '#####'
  - 步骤 2：查询文档数组中嵌入的字段
- - '#####'
  - 步骤 3：使用数组索引查询嵌入文档中的字段
- - '##'
  - 从查询中投影要返回的字段
- - '###'
  - 配方 2-12. 限制查询返回的字段
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：仅返回指定字段和 `_id` 字段
- - '#####'
  - 步骤 2：抑制 `_id` 字段
- - '#####'
  - 步骤 3：排除多个字段
- - '#####'
  - 步骤 4：返回嵌入文档中的特定字段
- - '##'
  - 查询 Null 或缺失的字段
- - '###'
  - 配方 2-13. 如何查询 Null 或缺失字段
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：相等过滤器
- - '#####'
  - 步骤 2：类型检查
- - '#####'
  - 步骤 3：存在性检查
- - '##'
  - 配方 2-14. 如何迭代游标
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '####'
  - 使用 `limit()` 和 `skip()` 方法
- - '##'
  - 配方 2-15. `limit()` 和 `skip()` 方法
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '##'
  - 使用 `Node.js` 和 MongoDB
- - '###'
  - 配方 2-16. `Node.js` 和 MongoDB
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 注意
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：建立连接并创建集合
- - '#####'
  - 步骤 2：插入文档
- - '#####'
  - 步骤 3：查询文档
- - '#####'
  - 步骤 4：更新文档
- - '#####'
  - 步骤 5：删除文档
- - '#'
  - 3. 数据建模与聚合
- - '##'
  - 数据模型
- - '###'
  - 嵌入式数据模型
- - '###'
  - 规范化数据模型
- - '##'
  - 文档间的数据模型关系
- - '##'
  - 配方 3-1. 使用嵌入式文档的数据模型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1： 一对一关系
- - '####'
  - 步骤 2： 一对多关系
- - '##'
  - 建模树形结构
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 3：使用祖先数组的树形结构
- - '##'
  - 聚合
- - '###'
  - 聚合管道
- - '###'
  - 配方 3-4. 聚合管道
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：聚合管道
- - '###'
  - Map-Reduce
- - '###'
  - 配方 3-5. Map-Reduce
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：Map-Reduce
- - '###'
  - 单用途聚合操作
- - '##'
  - 配方 3-6. 单目的聚合操作
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：单目的聚合操作
- - '##'
  - SQL 聚合术语及对应的 MongoDB 聚合操作符
- - '##'
  - 配方 3-7. 将 SQL 聚合映射到 MongoDB 聚合操作
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：将 SQL 聚合操作转换为 MongoDB
- - '#'
  - 4. 索引
- - '####'
  - 注意
- - '##'
  - 配方 4-1. 使用索引
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：创建索引
- - '####'
  - 注意
- - '##'
  - 配方 4-2. 索引类型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 4-3. 索引属性
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：多键索引
- - '####'
  - 注意
- - '####'
  - 步骤 2：文本索引
- - '####'
  - 步骤 3：哈希索引
- - '####'
  - 步骤 4：2dsphere 索引
- - '####'
  - 步骤 5：TTL 索引
- - '####'
  - 步骤 6：唯一索引
- - '####'
  - 步骤 7：部分索引
- - '##'
  - 配方 4-4. 索引策略
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：创建支持查询的索引
- - '#####'
  - 步骤 2：使用索引对查询结果排序
- - '######'
  - 使用单字段索引排序
- - '######'
  - 对多个字段排序
- - '######'
  - 将最近的值保存在内存中的索引
- - '#####'
  - 步骤 4：稀疏索引
- - '#####'
  - 注意
- - '#####'
  - 创建查询以确保选择性
- - '#'
  - 5. 复制与分片
- - '##'
  - 复制
- - '###'
  - 配方 5-1. 设置副本集
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：三成员副本集
- - '##'
  - 副本集初始化与基本操作
- - '###'
  - 初始化副本集
- - '###'
  - 自动故障转移—高可用
- - '##'
  - 分片
- - '###'
  - 配方 5-2. 创建分片
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 第 1 步：分片集群
- - '#####'
  - 注意
- - '#'
  - 6. 多文档事务
- - '##'
  - MongoDB 中的多文档事务
- - '####'
  - 注意
- - '####'
  - 事务的限制
- - '####'
  - 事务与会话
- - '###'
  - 配方 6-1. 使用多文档事务
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：多文档事务
- - '##'
  - 配方 6-2. 两个并发事务之间的隔离性测试
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：两个并发事务之间的隔离性测试
- - '##'
  - 配方 6-3. 发生写冲突的事务
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：发生写冲突的事务
- - '##'
  - 配方 6-4. 使用 `abortTransaction` 丢弃数据变更
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：丢弃数据变更
- - '#####'
  - 注意
- - '#'
  - 7. MongoDB 监控与备份
- - '##'
  - MongoDB 监控
- - '###'
  - 日志文件
- - '##'
  - 配方 7-1. 使用 MongoDB 日志文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：显示日志文件内容并设置日志级别
- - '#####'
  - 注意
- - '##'
  - MongoDB 性能
- - '###'
  - 数据库分析器
- - '####'
  - 注意
- - '##'
  - 配方 7-2. 使用数据库分析器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：启用并配置数据库分析器
- - '#####'
  - 注意
- - '##'
  - 配方 7-3. 查看数据库分析器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：启用并配置数据库分析器
- - '#####'
  - 注意
- - '##'
  - '`mongostat`'
- - '###'
  - 配方 7-4. 使用 `mongostat`
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1： `mongostat` 命令
- - '#####'
  - 注意
- - '##'
  - '`mongotop`'
- - '###'
  - 配方 7-5. 使用 `mongotop`
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1： `mongotop` 命令
- - '##'
  - '`db.stats()`'
- - '###'
  - 配方 7-6. 使用 `db.stats()`
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1： `db.stats()` 命令
- - '##'
  - '`db.serverStatus()`'
- - '###'
  - 配方 7-7. 使用 `db.serverStatus()`
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1： `db.serverStatus()` 命令
- - '##'
  - 使用 MongoDB 工具进行备份与还原
- - '###'
  - 配方 7-8. 使用 `mongodump`
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '####'
  - 使用 `mongodump` 进行自动和定期备份调度
- - '###'
  - 配方 7-9. 使用 `mongorestore`
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：使用 `mongorestore` 还原数据
- - '#####'
  - 步骤 2：使用 `mongorestore` 还原到远程实例
- - '###'
  - 配方 7-10. 使用 `mongodb` 查询计划
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '#####'
  - 步骤 1：使用 `explain()` 理解查询计划
- - '#####'
  - 步骤 2：理解 `explain()` 中的不同模式
- - '#'
  - 8. MongoDB 安全
- - '##'
  - 身份验证与授权
- - '###'
  - 注意
- - '###'
  - 访问控制
- - '###'
  - 角色
- - '####'
  - MongoDB 用户角色
- - '#####'
  - '`read`'
- - '#####'
  - '`readwrite`'
- - '####'
  - MongoDB 管理员角色
- - '#####'
  - '`dbAdmin`'
- - '#####'
  - '`dbOwner`'
- - '#####'
  - '`userAdmin`'
- - '####'
  - 集群管理员角色
- - '#####'
  - '`clusterAdmin`'
- - '#####'
  - '`clusterManager`'
- - '##'
  - 配方 8-1. 创建超级用户并对用户进行身份验证
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：创建超级用户
- - '####'
  - 步骤 2：对用户进行身份验证
- - '####'
  - 步骤 3：创建一个具有读写访问控制的新用户
- - '##'
  - 配方 8-2. 使用密钥文件对副本集中的服务器进行身份验证
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：使用密钥文件认证副本集中的服务器
- - '#####'
  - 注意
- - '##'
  - 配方 8-3. 为现有用户修改访问权限
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：使用用户 `superUserAdmin` 连接到实例并连接到 `admin` 数据库
- - '####'
  - 步骤 2：识别用户现有角色
- - '#####'
  - 注意
- - '####'
  - 步骤 3：为用户授予一个额外角色
- - '####'
  - 步骤 4：从用户撤销现有角色
- - '##'
  - 配方 8-4. 为现有用户更改密码
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：使用用户 `superUserAdmin` 连接到实例并连接到 `admin` 数据库
- - '####'
  - 步骤 2：更改密码
- - '##'
  - 配方 8-5. 跟踪集群中用户的活动
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 注意
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：启用和配置审计事件
- - '#####'
  - 注意
- - '####'
  - 步骤 2：创建审计过滤器
- - '##'
  - 配方 8-6. 加密
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 注意
- - '###'
  - 工作原理
- - '####'
  - 步骤 1：了解不同的加密选项
- - '#####'
  - 动态数据加密
- - '#####'
  - 静态数据加密
- - '####'
  - 步骤 2：使用本地密钥管理加密静态数据
- - '#####'
  - 注意
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F, G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N, O, P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U
- - '##'
  - V, W
- - '##'
  - X, Y, Z
