name: Pro Oracle database 11g administration
name_cn: Oracle database 11g 高级管理指南
slug: pro-oracle-database-11g-administration
toc:
- - '#'
  - Oracle Database 11g 专业管理指南
- - '##'
  - 目录
- - '#'
  - 第 1 章：安装 Oracle 二进制文件
- - '##'
  - Oracle 清单目录
- - '##'
  - Oracle 基础目录
- - '##'
  - Oracle 家目录
- - '##'
  - Oracle 网络文件目录
- - '##'
  - 自动诊断仓库
- - '##'
  - 安装 Oracle
- - '###'
  - 步骤 1：创建操作系统组和用户
- - '###'
  - 步骤 2：确保操作系统已充分配置
- - '###'
  - 步骤 3：获取 Oracle 安装软件
- - '###'
  - 步骤 4：解压缩文件
- - '###'
  - 步骤 5：配置响应文件并运行安装程序
- - '####'
  - Oracle Database 10g 场景
- - '####'
  - Oracle Database 11g 场景
- - '###'
  - 步骤 6：对任何问题进行故障排除
- - '###'
  - 使用现有安装的副本进行安装
- - '####'
  - 步骤 1：使用操作系统实用程序复制二进制文件
- - '##'
  - 升级 Oracle 软件
- - '##'
  - 安装失败后重新安装
- - '##'
  - 应用临时补丁
- - '##'
  - 应用补丁
- - '##'
  - 使用图形安装程序进行远程安装
- - '###'
  - 步骤 3：将 Oracle 安装介质复制到远程服务器
- - '###'
  - 步骤 4：运行 xhost 命令
- - '###'
  - 步骤 5：从 X 登录到远程计算机
- - '###'
  - 步骤 6：确保远程计算机上的 DISPLAY 变量设置正确
- - '###'
  - 步骤 7：执行 runInstaller 实用程序
- - '###'
  - 步骤 8：故障排除
- - '##'
  - 总结
- - '#'
  - 第 2 章：实施数据库
- - '##'
  - 设置操作系统变量
- - '###'
  - 手动密集型方法
- - '###'
  - Oracle 设置操作系统变量的方法
- - '####'
  - 理解 oratab
- - '####'
  - 使用 oraenv
- - '###'
  - 我设置操作系统变量的方法
- - '##'
  - 创建数据库
- - '###'
  - 步骤 1. 设置操作系统变量
- - '###'
  - 步骤 2：配置初始化文件
- - '###'
  - 步骤 3：创建所需目录
- - '###'
  - 步骤 4：创建数据库
- - '###'
  - 步骤 5. 创建数据字典
- - '##'
  - 配置和实施监听器
- - '##'
  - 创建密码文件
- - '##'
  - 启动和停止数据库
- - '###'
  - 理解身份验证
- - '###'
  - 启动数据库
- - '###'
  - 停止数据库
- - '##'
  - 使用 DBCA 创建数据库
- - '##'
  - 删除数据库
- - '##'
  - 一台服务器上可以有多少个数据库？
- - '##'
  - 总结
- - '#'
  - 第 3 章：配置高效环境
- - '##'
  - 自定义您的操作系统命令提示符
- - '##'
  - 自定义您的 SQL 提示符
- - '##'
  - 为常用命令创建快捷方式
- - '###'
  - 使用别名
- - '###'
  - 使用函数
- - '##'
  - 快速重新运行命令
- - '###'
  - 使用上下方向键滚动
- - '###'
  - 按下 Ctrl+P 和 Ctrl+N
- - '###'
  - 列出命令历史
- - '###'
  - 反向搜索
- - '###'
  - 设置命令编辑器
- - '##'
  - 开发标准脚本
- - '###'
  - dba_setup
- - '###'
  - dba_fcns
- - '###'
  - tbsp_chk.bsh
- - '###'
  - conn.bsh
- - '###'
  - filesp.bsh
- - '###'
  - login.sql
- - '###'
  - top.sql
- - '###'
  - lock.sql
- - '###'
  - users.sql
- - '##'
  - 组织脚本
- - '###'
  - 步骤 1：创建目录
- - '###'
  - 步骤 2：将文件复制到目录
- - '###'
  - 步骤 3：配置启动文件
- - '##'
  - 总结
- - '#'
  - 第 4 章：表空间与数据文件
- - '##'
  - 理解前五个
- - '##'
  - 理解对更多空间的需求
- - '##'
  - 创建表空间
- - '##'
  - 重命名表空间
- - '##'
  - 控制重做日志的生成
- - '##'
  - 更改表空间的写入模式
- - '##'
  - 删除表空间
- - '##'
  - 使用 Oracle 管理的文件
- - '##'
  - 创建大文件表空间
- - '##'
  - 显示表空间大小
- - '##'
  - 更改表空间大小
- - '##'
  - 切换数据文件的离线与在线状态
- - '##'
  - 重命名或重新定位数据文件
- - '##'
  - 总结
- - '#'
  - 第 5 章：管理控制文件与在线重做日志
- - '##'
  - 管理控制文件
- - '###'
  - 查看控制文件名称与位置
- - '###'
  - 添加控制文件
- - '###'
  - 移动控制文件
- - '###'
  - 移除控制文件
- - '##'
  - 管理在线重做日志
- - '###'
  - 显示在线重做日志信息
- - '###'
  - 确定在线重做日志组的最优大小
- - '###'
  - 确定重做日志组的最优数量
- - '###'
  - 添加在线重做日志组
- - '###'
  - 调整在线重做日志组的大小
- - '###'
  - 向组中添加在线重做日志文件
- - '###'
  - 从组中移除在线重做日志文件
- - '###'
  - 移动或重命名重做日志文件
- - '##'
  - 总结
- - '#'
  - 第 6 章：用户与基础安全
- - '##'
  - 理解模式与用户
- - '##'
  - 管理默认用户
- - '##'
  - 创建用户
- - '###'
  - 选择用户名和身份验证方法
- - '###'
  - 分配默认的永久和临时表空间
- - '##'
  - 修改密码
- - '##'
  - 强制实施密码安全
- - '##'
  - 以其他用户身份登录
- - '##'
  - 修改用户
- - '##'
  - 删除用户
- - '##'
  - 强制实施密码安全性与资源限制
- - '###'
  - 实施密码安全性
- - '###'
  - 限制数据库资源使用
- - '##'
  - 管理权限
- - '###'
  - 分配数据库系统权限
- - '###'
  - 分配数据库对象权限
- - '##'
  - 分组与分配权限
- - '##'
  - 本章小结
- - '#'
  - 第 7 章：表与约束
- - '##'
  - 创建表
- - '###'
  - 创建堆组织表
- - '###'
  - 实现虚拟列
- - '###'
  - 创建只读表
- - '###'
  - 理解延迟段创建
- - '###'
  - 允许并行 SQL 执行
- - '###'
  - 压缩表数据
- - '###'
  - 避免重做日志生成
- - '###'
  - 从查询创建表
- - '##'
  - 修改表
- - '###'
  - 获取所需锁
- - '###'
  - 重命名表
- - '###'
  - 添加列
- - '###'
  - 修改列
- - '###'
  - 重命名列
- - '###'
  - 删除列
- - '##'
  - 显示表 DDL 语句
- - '##'
  - 删除表
- - '##'
  - 闪回删除表
- - '##'
  - 从表中移除数据
- - '###'
  - 使用 DELETE
- - '###'
  - 使用 TRUNCATE
- - '##'
  - 查看与调整高水位线
- - '###'
  - 通过跟踪检测高水位线以下的空间
- - '###'
  - 使用 DBMS_SPACE 检测高水位线以下的空间
- - '##'
  - 创建临时表
- - '##'
  - 创建索引组织表
- - '##'
  - 管理约束
- - '###'
  - 创建主键约束
- - '###'
  - 强制唯一键值
- - '###'
  - 创建外键约束
- - '###'
  - 检查特定数据条件
- - '###'
  - 强制非空条件
- - '###'
  - 禁用约束
- - '###'
  - 启用约束
- - '##'
  - 本章小结
- - '#'
  - 第 8 章：索引
- - '##'
  - 决定何时创建索引
- - '##'
  - 需要考虑的因素
- - '##'
  - 索引管理准则
- - '##'
  - 创建索引
- - '###'
  - 创建 B 树索引
- - '###'
  - 创建复合索引
- - '###'
  - 实现基于函数的索引
- - '###'
  - 创建唯一索引
- - '###'
  - 使用位图索引
- - '###'
  - 创建位图连接索引
- - '###'
  - 实现反向键索引
- - '#'
  - 第 9 章：视图、同义词与序列
- - '##'
  - 实现视图
- - '###'
  - 创建视图
- - '###'
  - 检查更新
- - '###'
  - 创建只读视图
- - '###'
  - 可更新的联接视图
- - '###'
  - 创建 INSTEAD OF 触发器
- - '###'
  - 修改视图定义
- - '###'
  - 显示用于创建视图的 SQL
- - '###'
  - 重命名视图
- - '###'
  - 删除视图
- - '##'
  - 管理同义词
- - '###'
  - 创建同义词
- - '###'
  - 创建公共同义词
- - '###'
  - 动态生成同义词
- - '###'
  - 显示同义词元数据
- - '###'
  - 重命名同义词
- - '###'
  - 删除同义词
- - '##'
  - 管理序列
- - '###'
  - 创建序列
- - '###'
  - 使用序列伪列
- - '###'
  - 自增列
- - '###'
  - 使用多个生成唯一值的序列
- - '###'
  - 使用一个序列还是多个序列
- - '###'
  - 查看序列元数据
- - '###'
  - 重命名序列
- - '###'
  - 删除序列
- - '###'
  - 重置序列
- - '##'
  - 总结
- - '#'
  - 第 10 章：数据字典基础
- - '##'
  - 数据字典架构
- - '###'
  - 静态视图
- - '###'
  - 动态性能视图
- - '###'
  - 可派生文档
- - '##'
  - 逻辑与物理数据库结构
- - '##'
  - 显示用户信息
- - '###'
  - 当前连接的用户
- - '###'
  - 当前已登录的用户
- - '###'
  - 当前正在执行的 SQL
- - '###'
  - 数据库中的用户账户
- - '##'
  - 查看表信息
- - '#'
  - 第 11 章：大对象
- - '##'
  - 描述当前 LOB 类型
- - '##'
  - 图解 LOB 定位器、索引和块
- - '##'
  - 区分 BasicFile 与 SecureFile
- - '##'
  - 创建带有 LOB 列的表
- - '##'
  - 维护 LOB 列
- - '##'
  - LOB 管理
- - '###'
  - 添加 LOB 列
- - '###'
  - 删除 LOB 列
- - '###'
  - 缓存 LOB
- - '###'
  - 行内与行外存储 LOB
- - '###'
  - 使用 SecureFile 特性
- - '####'
  - 压缩 LOB
- - '####'
  - 去重 LOB
- - '####'
  - 加密 LOB
- - '####'
  - 从 BasicFiles 迁移到 SecureFiles
- - '###'
  - 查看 LOB 元数据
- - '###'
  - 加载 LOB
- - '####'
  - 加载 CLOB
- - '####'
  - 加载 BLOB
- - '###'
  - 测量 LOB 消耗的空间
- - '####'
  - BasicFile 已用空间
- - '####'
  - SecureFile 已用空间
- - '#'
  - 第 12 章：分区：分而治之
- - '##'
  - 哪些表应该被分区？
- - '##'
  - 创建分区表
- - '###'
  - 按范围分区
- - '###'
  - 按列表分区
- - '###'
  - 按哈希分区
- - '###'
  - 混合使用不同的分区方法
- - '###'
  - 按需创建分区
- - '###'
  - 创建与父表匹配的分区
- - '###'
  - 在虚拟列上分区
- - '###'
  - 让应用程序控制分区
- - '##'
  - 维护分区
- - '###'
  - 查看分区元数据
- - '###'
  - 移动分区
- - '###'
  - 自动移动更新后的行
- - '###'
  - 对现有表进行分区
- - '###'
  - 添加分区
- - '###'
  - 将分区与现有表交换
- - '###'
  - 重命名分区
- - '###'
  - 拆分分区
- - '###'
  - 合并分区
- - '###'
  - 删除分区
- - '###'
  - 为分区生成统计信息
- - '###'
  - 从分区中移除行
- - '###'
  - 操作分区内的数据
- - '##'
  - 分区索引
- - '###'
  - 使索引的分区与其表的分区一致
- - '###'
  - 以不同于其表的方式对索引进行分区
- - '##'
  - 分区修剪
- - '#'
  - 第 13 章：数据泵
- - '##'
  - 数据泵架构
- - '##'
  - 导出数据
- - '###'
  - 创建数据库目录
- - '###'
  - 授予目录访问权限
- - '###'
  - 执行导出操作
- - '##'
  - 导入数据
- - '##'
  - 交互式命令模式
- - '###'
  - 进入交互式命令模式
- - '###'
  - 附加到正在运行的作业
- - '###'
  - 停止和重新启动作业
- - '###'
  - 终止数据泵作业
- - '##'
  - 入门技巧
- - '###'
  - 使用参数文件
- - '###'
  - 估算导出作业的大小
- - '###'
  - 列出转储文件的内容
- - '##'
  - 传输数据
- - '###'
  - 跨网络直接导出和导入
- - '###'
  - 复制数据文件
- - '##'
  - 导出和导入表空间与数据文件
- - '###'
  - 导出表空间元数据
- - '###'
  - 指定不同的数据文件路径和名称
- - '###'
  - 更改段和存储属性
- - '###'
  - 导入到与原始表空间不同的表空间
- - '###'
  - 更改数据文件的大小
- - '##'
  - 过滤数据和对象
- - '###'
  - 指定查询
- - '###'
  - 导出一定百分比的数据
- - '###'
  - 从导出文件中排除对象
- - '###'
  - 排除统计信息
- - '###'
  - 在导出文件中仅包含特定对象
- - '###'
  - 导出表、索引、约束和触发器的 DDL
- - '###'
  - 从导入中排除对象
- - '###'
  - 在导入中包含对象
- - '##'
  - 常见的数据泵任务
- - '###'
  - 创建一致性导出
- - '###'
  - 当对象已存在时进行导入
- - '###'
  - 重命名表
- - '###'
  - 重映射数据
- - '###'
  - 克隆用户
- - '###'
  - 抑制日志文件
- - '###'
  - 使用并行度
- - '###'
  - 指定额外的转储文件
- - '###'
  - 重用输出文件名
- - '###'
  - 创建每日 DDL 文件
- - '###'
  - 压缩输出
- - '###'
  - 加密数据
- - '##'
  - 监控数据泵作业
- - '###'
  - 数据泵日志文件
- - '###'
  - 数据字典视图
- - '###'
  - 数据库警报日志
- - '###'
  - 状态表
- - '###'
  - 交互式命令模式状态
- - '###'
  - 操作系统实用程序
- - '##'
  - 数据泵传统模式
- - '###'
  - 数据泵映射到 exp 实用程序
- - '###'
  - 数据泵映射到 imp 实用程序
- - '##'
  - 总结
- - '#'
  - 第 14 章：外部表
- - '##'
  - SQL*Loader 与外部表
- - '##'
  - 将 CSV 文件加载到数据库
- - '###'
  - 创建目录对象并授权访问
- - '###'
  - 创建外部表
- - '###'
  - 查看外部表元数据
- - '###'
  - 从外部表加载到常规表
- - '##'
  - 执行高级转换
- - '##'
  - 从 SQL 查看文本文件
- - '##'
  - 使用外部表卸载和加载数据
- - '###'
  - 使用并行度减少耗时
- - '##'
  - 总结
- - '#'
  - 第 15 章：物化视图
- - '##'
  - 理解物化视图
- - '##'
  - 物化视图术语
- - '##'
  - 引用有用的视图
- - '##'
  - 创建基本物化视图
- - '###'
  - 创建可完全刷新的物化视图
- - '###'
  - 创建可快速刷新的物化视图
- - '##'
  - 超越基础
- - '###'
  - 创建物化视图并为其及索引指定表空间
- - '###'
  - 在物化视图上创建索引
- - '###'
  - 对物化视图进行分区
- - '###'
  - 压缩物化视图
- - '###'
  - 加密物化视图列
- - '###'
  - 在预建表上构建物化视图
- - '###'
  - 创建未填充的物化视图
- - '###'
  - 创建在提交时刷新的物化视图
- - '###'
  - 创建永不刷新的物化视图
- - '###'
  - 为查询重写创建物化视图
- - '###'
  - 基于复杂查询创建可快速刷新的物化视图
- - '###'
  - 查看物化视图 DDL
- - '###'
  - 删除物化视图
- - '##'
  - 修改物化视图
- - '###'
  - 修改基表 DDL 并传播到物化视图
- - '###'
  - 切换物化视图的重做日志记录
- - '###'
  - 更改并行度
- - '###'
  - 移动物化视图
- - '##'
  - 管理物化视图日志
- - '###'
  - 创建物化视图日志
- - '###'
  - 为物化视图日志列创建索引
- - '###'
  - 查看物化视图日志使用的空间
- - '###'
  - 收缩物化视图日志中的空间
- - '###'
  - 检查物化视图日志的行数
- - '###'
  - 移动物化视图日志
- - '###'
  - 删除物化视图日志
- - '##'
  - 刷新物化视图
- - '###'
  - 从 SQL*Plus 手动刷新物化视图
- - '###'
  - 使用 Shell 脚本和调度工具实现刷新自动化
- - '###'
  - 创建具有刷新间隔的物化视图
- - '###'
  - 高效执行完全刷新
- - '###'
  - 处理 ORA-12034 错误
- - '##'
  - 监控物化视图刷新
- - '###'
  - 查看物化视图上次刷新时间
- - '###'
  - 确定刷新是否正在进行中
- - '###'
  - 监控实时刷新进度
- - '###'
  - 检查物化视图是否在时间段内刷新
- - '##'
  - 创建远程物化视图刷新
- - '###'
  - 理解远程刷新架构
- - '###'
  - 查看物化视图表信息
- - '###'
  - 确定有多少物化视图引用中心物化视图日志
- - '##'
  - 在组中管理物化视图
- - '###'
  - 创建物化视图组
- - '###'
  - 更改物化视图刷新组
- - '###'
  - 刷新物化视图组
- - '###'
  - DBMS_MVIEW 对比 DBMS_REFRESH
- - '###'
  - 确定组中的物化视图
- - '###'
  - 将物化视图添加到刷新组
- - '###'
  - 从刷新组中移除物化视图
- - '###'
  - 删除物化视图刷新组
- - '##'
  - 总结
- - '#'
  - 第 16 章：用户管理的备份与恢复
- - '##'
  - 为非归档模式数据库实施冷备份策略
- - '###'
  - 对非归档模式数据库进行冷备份
- - '###'
  - 在非归档模式下使用在线重做日志恢复冷备份
- - '###'
  - 在非归档模式下无在线重做日志时恢复冷备份
- - '###'
  - 冷备份与恢复的脚本编写
- - '##'
  - 实施归档模式
- - '###'
  - 做出架构决策
- - '###'
  - 设置归档重做文件位置
- - '###'
  - 启用归档模式
- - '###'
  - 禁用归档模式
- - '###'
  - 应对归档日志目标位置磁盘空间不足
- - '###'
  - 备份归档重做日志文件
- - '###'
  - 对归档模式数据库进行冷备份
- - '##'
  - 实施热备份策略
- - '###'
  - 进行热备份
- - '###'
  - 热备份的脚本编写
- - '###'
  - 理解拆分块问题
- - '###'
  - 理解备份期间生成重做的必要性
- - '###'
  - 理解数据文件会被更新
- - '##'
  - 执行归档模式数据库的完全恢复
- - '###'
  - 在数据库离线时进行恢复与还原
- - '###'
  - 在数据库在线时进行恢复与还原
- - '###'
  - 还原控制文件
- - '##'
  - 执行归档模式数据库的不完全恢复
- - '##'
  - 闪回表
- - '###'
  - FLASHBACK TABLE TO BEFORE DROP
- - '###'
  - 将表闪回到之前的某个时间点
- - '##'
  - 闪回数据库
- - '##'
  - 总结
- - '#'
  - 第 17 章：配置 RMAN
- - '##'
  - 理解 RMAN
- - '##'
  - 启动 RMAN
- - '##'
  - RMAN 架构决策
- - '##'
  - 从决策过渡到行动
- - '##'
  - 使用恢复目录
- - '##'
  - 总结
- - '#'
  - 第 18 章：RMAN 备份与报告
- - '###'
  - 准备运行 RMAN 备份命令
- - '####'
  - 设置 NLS_DATE_FORMAT
- - '####'
  - 设置 ECHO
- - '####'
  - 显示变量
- - '###'
  - 运行备份
- - '####'
  - 备份整个数据库
- - '####'
  - 备份表空间
- - '####'
  - 备份数据文件
- - '####'
  - 备份控制文件
- - '####'
  - 备份 Spfile
- - '####'
  - 备份归档重做日志
- - '####'
  - 备份快速恢复区
- - '####'
  - 从备份中排除表空间
- - '####'
  - 备份未备份的数据文件
- - '####'
  - 跳过只读表空间
- - '####'
  - 跳过离线或不可访问的文件
- - '####'
  - 并行备份大型文件
- - '####'
  - 将 RMAN 备份信息添加到仓库
- - '###'
  - 创建增量备份
- - '####'
  - 进行增量级别备份
- - '####'
  - 创建增量更新备份
- - '####'
  - 使用块变化跟踪
- - '###'
  - 检查数据文件和备份中的损坏
- - '####'
  - 使用 VALIDATE
- - '####'
  - 使用 BACKUP...VALIDATE
- - '####'
  - 使用 RESTORE...VALIDATE
- - '###'
  - 记录 RMAN 输出
- - '####'
  - 将输出重定向到文件
- - '####'
  - 使用 Unix/Linux 日志命令捕获输出
- - '####'
  - 将输出记录到文件
- - '####'
  - 在数据字典中查询输出
- - '###'
  - RMAN 报告
- - '####'
  - 使用 LIST
- - '####'
  - 使用 REPORT
- - '####'
  - 使用 SQL
- - '##'
  - 总结
- - '#'
  - 第 19 章：RMAN 还原与恢复
- - '###'
  - 确定需要介质恢复
- - '###'
  - 确定要还原的内容
- - '####'
  - 过程如何工作
- - '####'
  - 使用数据恢复顾问
- - '###'
  - 使用 RMAN 停止/启动 Oracle
- - '####'
  - 关闭
- - '####'
  - 启动
- - '###'
  - 完全恢复
- - '####'
  - 测试还原和恢复
- - '####'
  - 还原整个数据库
- - '####'
  - 还原表空间
- - '####'
  - 还原只读表空间
- - '####'
  - 还原临时表空间
- - '###'
  - 还原数据文件
- - '###'
  - 将数据文件还原到非默认位置
- - '###'
  - 执行块级别恢复
- - '###'
  - 还原归档重做日志文件
- - '###'
  - 还原 Spfile
- - '###'
  - 还原控制文件
- - '###'
  - 使用恢复目录
- - '###'
  - 使用自动备份进行还原
- - '###'
  - 指定文件名
- - '###'
  - 不完全恢复
- - '####'
  - 确定不完全恢复的类型
- - '####'
  - 执行基于时间的恢复
- - '####'
  - 执行基于日志序列的恢复
- - '####'
  - 执行基于变更/SCN 的恢复
- - '####'
  - 还原到恢复点
- - '###'
  - 在不同服务器上还原和恢复
- - '##'
  - 小结
- - '#'
  - 第 20 章：Oracle 安全备份
- - '##'
  - OSB 版本与功能
- - '##'
  - OSB 术语
- - '###'
  - OSB 管理域与服务器
- - '###'
  - OSB 用户与类别
- - '###'
  - OSB 守护进程
- - '##'
  - 下载与安装
- - '##'
  - 命令行访问 OSB
- - '##'
  - OSB 配置
- - '###'
  - 配置用户与类别
- - '###'
  - 配置介质家族
- - '###'
  - 配置数据库备份存储选择器
- - '##'
  - 数据库备份
- - '##'
  - 数据库还原
- - '##'
  - 文件系统备份
- - '###'
  - 创建数据集文件
- - '###'
  - 配置备份窗口
- - '###'
  - 配置备份计划与触发器
- - '###'
  - 执行按需文件系统备份
- - '##'
  - 文件系统还原
- - '###'
  - 执行基于目录的还原
- - '###'
  - 执行原始还原
- - '###'
  - 执行 obtar 还原
- - '##'
  - OSB 作业监控
- - '###'
  - 列出作业
- - '##'
  - 总结
- - '#'
  - 第 21 章：自动化作业
- - '##'
  - 使用 Oracle 调度器自动化作业
- - '##'
  - 通过 cron 自动化作业
- - '##'
  - 自动化 DBA 作业示例
- - '##'
  - 总结
- - '#'
  - 第 22 章：数据库故障排除
- - '##'
  - 快速分流
- - '##'
  - 检查数据库可用性
- - '##'
  - 排查磁盘空间不足
- - '##'
  - 检查告警日志
- - '##'
  - 通过操作系统工具识别瓶颈
- - '###'
  - 识别系统瓶颈
- - '###'
  - 将操作系统进程映射到 SQL 语句
- - '##'
  - 查找资源密集型 SQL 语句
- - '###'
  - 监控实时 SQL 执行统计信息
- - '###'
  - 显示资源密集型 SQL
- - '##'
  - 运行 Oracle 诊断工具
- - '##'
  - 检测与解决锁问题
- - '##'
  - 解决游标未关闭问题
- - '##'
  - 排查 Undo 表空间问题
- - '###'
  - 确认 Undo 表空间大小是否合适
- - '###'
  - 查看消耗 Undo 空间的 SQL
- - '##'
  - 处理临时表空间问题
- - '###'
  - 确认临时表空间大小是否合适
- - '###'
  - 查看消耗临时空间的 SQL
- - '##'
  - 审计
- - '###'
  - 启用 Oracle 标准审计
- - '###'
  - 审计 DML 使用情况
- - '###'
  - 审计登录/注销事件
- - '###'
  - 查看已启用的审计操作
- - '###'
  - 关闭审计
- - '###'
  - 清理审计表和文件
- - '###'
  - 将审计表移动到非系统表空间
- - '###'
  - 细粒度审计
- - '##'
  - 总结
- - '#'
  - 引言
- - '###'
  - 本书使用的约定
- - '###'
  - 评论
- - '###'
  - 联系作者
- - '#'
  - 索引
