name: Pro MongoDBTM Development
name_cn: MongoDB高级开发指南
slug: pro-mongodbtm-development
toc:
- - '#'
  - MongoDB™ 高级开发指南
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '##'
  - 引言
- - '#'
  - 第 1 章：使用 Java 客户端操作 MongoDB
- - '##'
  - 环境设置
- - '##'
  - 创建 Maven 项目
- - '##'
  - 创建 BSON 文档
- - '##'
  - 使用模型创建 BSON 文档
- - '##'
  - 从 MongoDB 获取数据
- - '##'
  - 更新 MongoDB 中的数据
- - '##'
  - 删除 MongoDB 中的数据
- - '##'
  - 小结
- - '#'
  - 第 2 章：使用 Mongo Shell
- - '##'
  - 入门
- - '##'
  - 环境设置
- - '##'
  - 启动 Mongo Shell
- - '##'
  - 在 Mongo Shell 中运行命令或方法
- - '##'
  - 使用数据库
- - '##'
  - 获取数据库信息
- - '##'
  - 创建数据库实例
- - '##'
  - 删除数据库
- - '##'
  - 使用集合
- - '##'
  - 创建集合
- - '##'
  - 删除集合
- - '##'
  - 使用文档
- - '##'
  - 添加文档
- - '##'
  - 批量添加文档
- - '##'
  - 保存文档
- - '##'
  - 更新文档
- - '##'
  - 更新多个文档
- - '##'
  - 查询单个文档
- - '##'
  - 查询所有文档
- - '##'
  - 查询指定字段
- - '##'
  - 使用游标
- - '##'
  - 查找并修改文档
- - '##'
  - 删除文档
- - '##'
  - 小结
- - '#'
  - 第 3 章：使用 PHP 操作 MongoDB
- - '##'
  - 入门
- - '##'
  - PHP MongoDB 数据库驱动概述
- - '##'
  - 环境设置
- - '##'
  - 安装 PHP
- - '##'
  - 安装 PHP 的 MongoDB 驱动
- - '##'
  - 创建连接
- - '##'
  - 获取数据库信息
- - '##'
  - 使用集合
- - '##'
  - 获取集合
- - '##'
  - 删除集合
- - '##'
  - 使用文档
- - '##'
  - 添加文档
- - '##'
  - 添加多个文档
- - '##'
  - 批量添加文档
- - '##'
  - 查询单个文档
- - '##'
  - 查询所有文档
- - '##'
  - 查询部分字段和文档
- - '##'
  - 更新文档
- - '#'
  - 第 4 章：在 Ruby 中使用 MongoDB
- - '##'
  - 入门指南
- - '##'
  - MongoDB Ruby 驱动程序概述
- - '##'
  - 环境设置
- - '###'
  - 安装 Ruby
- - '###'
  - 安装 DevKit
- - '###'
  - 安装 MongoDB 的 Ruby 驱动程序
- - '##'
  - 使用集合
- - '###'
  - 创建与 MongoDB 的连接
- - '###'
  - 连接到数据库
- - '###'
  - 创建集合
- - '##'
  - 使用文档
- - '###'
  - 添加文档
- - '###'
  - 添加多个文档
- - '###'
  - 查找单个文档
- - '###'
  - 查找多个文档
- - '###'
  - 更新文档
- - '###'
  - 删除文档
- - '###'
  - 执行批量操作
- - '##'
  - 本章小结
- - '#'
  - 第 5 章：在 Node.js 中使用 MongoDB
- - '##'
  - 入门指南
- - '##'
  - MongoDB Node.js 驱动程序概述
- - '##'
  - 环境设置
- - '###'
  - 安装 MongoDB 服务器
- - '###'
  - 安装 Node.js
- - '###'
  - 安装 MongoDB 的 Node.js 驱动程序
- - '##'
  - 使用连接
- - '###'
  - 创建一个 MongoDB 连接
- - '##'
  - 使用数据库
- - '##'
  - 使用集合
- - '##'
  - 使用文档
- - '###'
  - 添加单个文档
- - '###'
  - 添加多个文档
- - '###'
  - 查找单个文档
- - '###'
  - 查找所有文档
- - '###'
  - 查找文档子集
- - '###'
  - 使用游标
- - '###'
  - 查找并修改单个文档
- - '###'
  - 查找并移除单个文档
- - '###'
  - 替换单个文档
- - '###'
  - 更新单个文档
- - '###'
  - 更新多个文档
- - '###'
  - 移除单个文档
- - '###'
  - 移除多个文档
- - '###'
  - 执行批量写入操作
- - '##'
  - 本章小结
- - '#'
  - 第 6 章：将 Apache Cassandra 表迁移到 MongoDB
- - '##'
  - 环境设置
- - '###'
  - 在 Eclipse 中创建 Maven 项目
- - '###'
  - 在 Apache Cassandra 中创建文档
- - '###'
  - 将 Cassandra 表迁移到 MongoDB
- - '##'
  - 本章小结
- - '#'
  - 第 7 章：将 Couchbase 迁移到 MongoDB
- - '##'
  - 环境设置
- - '###'
  - 创建 Maven 项目
- - '###'
  - 创建 Java 类
- - '###'
  - 配置 Maven 项目
- - '###'
  - 向 Couchbase 添加文档
- - '###'
  - 创建 Couchbase 视图
- - '###'
  - 将 Couchbase 文档迁移到 MongoDB
- - '##'
  - 本章小结
- - '#'
  - 第 8 章：迁移 Oracle 数据库
- - '##'
  - mongoimport 工具概述
- - '##'
  - 环境设置
- - '###'
  - 创建 Oracle 数据库表
- - '###'
  - 将 Oracle 数据库表导出到 CSV 文件
- - '###'
  - 从 CSV 文件导入数据到 MongoDB
- - '###'
  - 显示 MongoDB 中的 JSON 数据
- - '##'
  - 本章小结
- - '#'
  - 第 9 章：在 MongoDB 中使用 Kundera
- - '##'
  - 环境设置
- - '###'
  - 创建 MongoDB 集合
- - '###'
  - 在 Eclipse 中创建 Maven 项目
- - '###'
  - 创建 JPA 实体类
- - '###'
  - 在 persistence.xml 配置文件中配置 JPA
- - '###'
  - 创建 JPA 客户端类
- - '###'
  - 运行 CRUD 操作
- - '###'
  - 创建目录
- - '###'
  - 使用实体类查找目录条目
- - '###'
  - 使用 JPA 查询查找目录条目
- - '###'
  - 更新目录条目
- - '###'
  - 删除目录条目
- - '###'
  - Kundera-Mongo JPA 客户端类
- - '###'
  - 安装 Maven 项目
- - '###'
  - 运行 Kundera-Mongo JPA 客户端类
- - '###'
  - 调用 KunderaClient 方法
- - '##'
  - 本章小结
- - '#'
  - 第 10 章：在 MongoDB 中使用 Spring Data
- - '##'
  - 环境设置
- - '###'
  - 创建 Maven 项目
- - '###'
  - 安装 Spring Data MongoDB
- - '###'
  - 配置 JavaConfig
- - '###'
  - 创建模型
- - '##'
  - 使用 Spring Data MongoDB Template
- - '###'
  - 创建 MongoDB 集合
- - '###'
  - 创建文档实例
- - '###'
  - 添加文档
- - '###'
  - 批量添加文档
- - '###'
  - 通过 Id 查找文档
- - '###'
  - 查找一个文档
- - '###'
  - 查找所有文档
- - '###'
  - 使用查询查找文档
- - '###'
  - 更新第一个文档
- - '###'
  - 更新多个文档
- - '###'
  - 移除文档
- - '##'
  - 在 MongoDB 中使用 Spring Data
- - '###'
  - 获取文档计数
- - '###'
  - 从仓库查找实体
- - '###'
  - 保存实体
- - '###'
  - 删除实体
- - '###'
  - 通过 Id 删除文档
- - '###'
  - 删除所有文档
- - '##'
  - 本章小结
- - '#'
  - 第 11 章：使用 MongoDB 创建 Apache Hive 表
- - '##'
  - Hive 的 MongoDB 存储处理器概述
- - '##'
  - 环境设置
- - '###'
  - 创建 MongoDB 数据存储
- - '###'
  - 在 Hive 中创建外部表
- - '##'
  - 本章小结
- - '#'
  - 第 12 章：在 Oracle Data Integrator 中将 MongoDB 与 Oracle 数据库集成
- - '##'
  - 环境设置
- - '###'
  - 创建物理架构
- - '###'
  - 创建逻辑架构
- - '###'
  - 创建数据模型
- - '###'
  - 创建集成项目
- - '###'
  - 创建集成接口
- - '###'
  - 运行接口
- - '###'
  - 在 Oracle 数据库表中选择集成的数据
- - '##'
  - 本章小结
- - '#'
  - 索引
- - '##'
  - 关于技术审阅者
- - '##'
  - 引言
