name: Expert Scripting and Automation for SQL Server DBAs
name_cn: SQL Server 数据库管理员专家级脚本与自动化指南
slug: expert-scripting-and-automation-for-sql-server-dbas
toc:
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 1. 面向 DBA 的 T-SQL 技巧
- - '##'
  - 使用 APPLY 运算符
- - '##'
  - 面向 DBA 的 XML
- - '###'
  - 理解 XML
- - '###'
  - 将结果集转换为 XML
- - '####'
  - 使用 FOR XML RAW
- - '####'
  - 使用 FOR XML AUTO
- - '####'
  - 使用 FOR XML PATH
- - '###'
  - 从 XML 文档中提取值
- - '####'
  - query 方法
- - '####'
  - value 和 nodes 方法
- - '####'
  - exist 方法
- - '####'
  - 综合使用方法
- - '####'
  - 高效循环
- - '##'
  - 摘要
- - '#'
  - 2. PowerShell 基础
- - '##'
  - 入门指南
- - '##'
  - 执行策略
- - '##'
  - 标准
- - '##'
  - 别名
- - '##'
  - 语言基础
- - '###'
  - 注释
- - '###'
  - 数据类型
- - '###'
  - 变量
- - '###'
  - 管道与筛选
- - '###'
  - 流程控制
- - '##'
  - 模块
- - '###'
  - SqlServer 模块
- - '####'
  - 表 2-4
- - '##'
  - 总结
- - '#'
  - 3. PowerShell DSC
- - '##'
  - 理解配置管理
- - '##'
  - 理解 DSC
- - '##'
  - 使用 DSC 配置 Windows 服务器
- - '###'
  - 定义文件资源
- - '###'
  - 定义注册表资源
- - '###'
  - 定义服务资源
- - '###'
  - 创建配置文件
- - '###'
  - 运行配置
- - '##'
  - 总结
- - '#'
  - 4. 使用 sqlserver 模块
- - '##'
  - 使用 Invoke-SqlCmd
- - '###'
  - Invoke-SqlCmd 基础用法
- - '###'
  - 将 Invoke-SqlCmd 用于脚本编写
- - '###'
  - 处理参数
- - '###'
  - 输出错误
- - '###'
  - 将结果写入文件
- - '###'
  - 用户执行上下文
- - '##'
  - 管理安全对象
- - '###'
  - 处理登录名
- - '###'
  - 处理服务器角色
- - '###'
  - 处理数据库用户
- - '###'
  - 处理凭据
- - '###'
  - 处理可用性组
- - '##'
  - 处理其他 Cmdlet
- - '##'
  - 小结
- - '#'
  - 5. 使用 DbaTools
- - '##'
  - 安装 DbaTools
- - '##'
  - 列出 DbaTools 模块中的命令
- - '##'
  - 使用 `Invoke-DbaQuery`
- - '###'
  - '`Invoke-DbaQuery` 基础'
- - '###'
  - 使用参数
- - '###'
  - 错误处理
- - '###'
  - 针对多个实例运行查询
- - '####'
  - 将结果写入文件
- - '##'
  - 管理安全对象
- - '###'
  - 创建登录名
- - '###'
  - 管理登录名
- - '####'
  - 将登录名添加到服务器角色
- - '####'
  - 重命名登录名
- - '####'
  - 删除登录名
- - '###'
  - 创建数据库用户
- - '###'
  - 管理数据库用户
- - '####'
  - 将用户添加到数据库角色
- - '####'
  - 删除用户及将其从角色中移除
- - '###'
  - 管理服务器代理
- - '####'
  - 创建凭据
- - '###'
  - 创建代理
- - '###'
  - 创建作业
- - '##'
  - 为作业添加调度
- - '###'
  - 表 5-1：New-DbaAgentSchedule 参数
- - '##'
  - 检索作业信息
- - '###'
  - 从结果看失败任务
- - '##'
  - 总结
- - '#'
  - 6. 自动化安装
- - '##'
  - 安装实例
- - '###'
  - 必需参数
- - '####'
  - IACCEPTSQLSERVERLICENSETERMS 开关
- - '###'
  - ACTION 参数
- - '###'
  - FEATURES 参数
- - '###'
  - Role 参数
- - '###'
  - 基本安装
- - '###'
  - 冒烟测试
- - '###'
  - 可选参数
- - '###'
  - 产品更新
- - '###'
  - 使用配置文件
- - '##'
  - SQL Server 2022 安装配置
- - '##'
  - 通过脚本进行自动化安装
- - '###'
  - 增强安装例程
- - '###'
  - 生产环境就绪
- - '##'
  - 使用 DSC 实现自动化安装
- - '##'
  - 总结
- - '#'
  - 7. 元数据驱动自动化
- - '##'
  - 创建智能例程
- - '###'
  - 移除即席查询计划
- - '####'
  - 处理查询结果的两种方式
- - '##'
  - 失败原因代码与运行时统计信息
- - '###'
  - 强制执行策略
- - '##'
  - 总结
- - '#'
  - 8. 构建库存数据库
- - '##'
  - 库存数据库平台设计
- - '###'
  - 概述
- - '###'
  - 示例拓扑
- - '###'
  - 解决方案
- - '####'
  - IaaS
- - '####'
  - PaaS
- - '##'
  - 库存数据库逻辑设计
- - '###'
  - 规范化
- - '####'
  - 1NF
- - '####'
  - 2NF
- - '####'
  - 3NF
- - '###'
  - 测试规范化
- - '##'
  - 库存数据库物理设计
- - '##'
  - 创建库存数据库
- - '###'
  - 清单 8-1 创建外壳数据库
- - '###'
  - 清单 8-2 为库存数据库创建数据库主密钥
- - '###'
  - 清单 8-3 备份主密钥
- - '###'
  - 创建证书
- - '###'
  - 备份证书
- - '###'
  - 创建对称键
- - '###'
  - 创建表
- - '##'
  - 总结
- - '#'
  - 9. 实现 SQL Server 的配置管理
- - '##'
  - 定义配置需求
- - '###'
  - 安全需求
- - '###'
  - 性能需求
- - '###'
  - 减少持续性操作
- - '##'
  - 实现配置
- - '###'
  - 实施安全资源
- - '###'
  - 实施性能资源
- - '###'
  - 实现操作资源
- - '###'
  - 整合所有资源
- - '##'
  - 清单 9-11 最终配置
- - '##'
  - 总结
- - '#'
  - 10. 集中化维护
- - '##'
  - 设计集中式维护
- - '###'
  - 图 10-1：目标维护例程架构
- - '###'
  - 图 10-2：表和视图的高级设计
- - '###'
  - 表 10-1：`MaintenanceWindows` 列
- - '###'
  - 表 10-2：`MaintenanceTasks` 列
- - '###'
  - 表 10-3：`MaintenanceSchedules` 列
- - '##'
  - 实现集中化维护
- - '###'
  - 创建表和视图
- - '###'
  - 创建 PowerShell 脚本
- - '###'
  - 删除旧备份脚本
- - '##'
  - 维护脚本与作业创建
- - '###'
  - 创建 SQL Server 代理作业
- - '##'
  - 总结
- - '#'
  - 11. 自动化例行维护与故障修复场景
- - '##'
  - 自动化临时例行维护
- - '###'
  - 创建 SSIS 包
- - '####'
  - 创建项目参数
- - '####'
  - 配置连接管理器
- - '####'
  - 创建包变量
- - '####'
  - 备份执行 SQL 任务
- - '##'
  - 自动化故障/修复场景
- - '###'
  - 针对 9002 错误设计响应方案
- - '###'
  - 自动化响应 9002 错误
- - '####'
  - 新建作业步骤 – 常规页
- - '####'
  - 响应页
- - '##'
  - 总结
