name: SQL Primer
name_cn: SQL 入门指南
slug: sql-primer
toc:
- - '##'
  - 第 1 章：SQL 简介
- - '##'
  - 第 2 章：准备好你的数据库
- - '##'
  - 第 3 章：约束的好处
- - '##'
  - 第 4 章：表操作
- - '##'
  - 第 5 章：编写基础查询
- - '##'
  - 第 6 章：操作数据
- - '##'
  - 第 7 章：组织你的数据
- - '##'
  - 第 8 章：用查询做更多事情
- - '##'
  - 第 9 章：计算字段
- - '##'
  - 第 10 章：聚合与分组
- - '##'
  - 第 11 章：理解连接
- - '##'
  - 第 12 章：子查询
- - '##'
  - 第 13 章：集合操作
- - '##'
  - 第 14 章：视图
- - '##'
  - 第 15 章：索引
- - '##'
  - 第 16 章：访问控制语句
- - '##'
  - 附录 A：延伸阅读
- - '##'
  - 附录 B：数据库管理系统与工具
- - '##'
  - 附录 C：SQL 与关系数据库的历史
- - '###'
  - 1. SQL 简介
- - '###'
  - 2. 准备你的数据库
- - '###'
  - 4. 表操作
- - '###'
  - 5. 编写基础查询
- - '###'
  - 6. 操作数据
- - '###'
  - 7. 组织你的数据
- - '###'
  - 8. 用查询做更多事情
- - '###'
  - 10. 聚合与分组
- - '###'
  - 11. 理解连接
- - '###'
  - 13. 集合操作
- - '###'
  - 14. 视图
- - '###'
  - 15. 索引
- - '###'
  - 16. 访问控制语句
- - '###'
  - 延伸阅读
- - '###'
  - 数据库管理系统与工具
- - '###'
  - SQL 与关系数据库的历史
- - '####'
  - 关系模型与 SQL
- - '####'
  - 使用 SQL 的优势
- - '####'
  - SQL 命令分类
- - '####'
  - 解释表
- - '####'
  - SQL 中的数据类型
- - '####'
  - 使用 PostgreSQL
- - '####'
  - 使用 SQLite
- - '####'
  - 创建你自己的数据库
- - '####'
  - 表创建
- - '####'
  - 插入数据
- - '####'
  - 编写你的第一个查询
- - '####'
  - 约束条件的好处
- - '#####'
  - 空值约束
- - '####'
  - 选择字段 INSERT
- - '####'
  - 检查约束
- - '####'
  - 主键约束
- - '####'
  - 唯一键约束
- - '####'
  - 主键与唯一键的区别
- - '####'
  - 删除表
- - '####'
  - 从现有表创建新表
- - '####'
  - 修改表
- - '#####'
  - ALTER TABLE 的多种形式
- - '####'
  - 在 PostgreSQL 中显示表信息
- - '####'
  - 在 SQLite 中显示表信息
- - '####'
  - 在其他 DBMS 中显示表信息
- - '####'
  - 选择有限数量的列
- - '####'
  - 对结果排序
- - '####'
  - 使用字段缩写进行排序
- - '####'
  - 按多列排序
- - '####'
  - 使用 WHERE 设置条件
- - '####'
  - 组合条件
- - '####'
  - 脚注
- - '####'
  - 从另一张表向表中插入数据
- - '####'
  - 更新现有数据
- - '####'
  - 从表中删除数据
- - '####'
  - 规范化
- - '####'
  - 原子性
- - '####'
  - 重复组
- - '####'
  - 拆分表格
- - '####'
  - 统计表中的记录数
- - '####'
  - 在 COUNT 中使用 DISTINCT
- - '####'
  - 列别名
- - '####'
  - SELECT 查询的执行顺序
- - '####'
  - 使用 `LIKE` 操作符
- - '####'
  - 计算字段
- - '#####'
  - 数学计算
- - '####'
  - 字符串操作
- - '####'
  - 字面值
- - '####'
  - 聚合函数
- - '####'
  - 使用极值函数 – MAX 和 MIN
- - '####'
  - 数据分组
- - '####'
  - 分组与聚合函数
- - '####'
  - HAVING 子句
- - '####'
  - 替代连接语法
- - '####'
  - 解决连接列中的歧义
- - '####'
  - 外连接
- - '####'
  - 交叉连接
- - '####'
  - 自连接
- - '####'
  - 非等值连接
- - '####'
  - 子查询
- - '#####'
  - 子查询的类型
- - '#####'
  - 子查询中的存在性测试
- - '####'
  - 在 INSERT 语句中使用子查询
- - '####'
  - 使用 ANY 和 ALL
- - '####'
  - 并集
- - '####'
  - 交集
- - '####'
  - 为什么需要视图？
- - '####'
  - 创建视图
- - '####'
  - 通过视图修改数据
- - '#####'
  - SQLite 中的视图修改
- - '#####'
  - 删除视图
- - '####'
  - 创建索引
- - '####'
  - 使用 EXPLAIN 查看索引如何工作
- - '####'
  - 唯一索引
- - '####'
  - 索引如何工作？
- - '####'
  - 索引开销
- - '#####'
  - SQLite 中的索引大小
- - '####'
  - 删除索引
- - '#####'
  - SQLite 中的访问控制
- - '#####'
  - 在 PostgreSQL 中创建新用户
- - '#####'
  - hunter2 的传说
- - '####'
  - 向用户授予权限
- - '####'
  - 撤销权限
- - '####'
  - 推荐的 SQL 书籍
- - '####'
  - 关系数据库管理系统
- - '####'
  - SQL 开发环境
- - '####'
  - 复杂面向文件系统的兴起
- - '####'
  - 数据库系统的登场
- - '####'
  - 关系模型的起源
- - '####'
  - 查询语言的艰苦奋战
- - '####'
  - 索引和术语表
- - '#####'
  - A
- - '#####'
  - B
- - '#####'
  - C
- - '#####'
  - D
- - '#####'
  - E
- - '#####'
  - G
- - '#####'
  - H
- - '#####'
  - I
- - '#####'
  - J, K
- - '#####'
  - L
- - '#####'
  - M
- - '#####'
  - N
- - '#####'
  - O
- - '#####'
  - P
- - '#####'
  - Q
- - '#####'
  - R
- - '#####'
  - S
- - '#####'
  - T
- - '#####'
  - U
- - '#####'
  - V, W, X, Y, Z
