name: Beginning SQL Queries
name_cn: SQL查询入门指南
slug: beginning-sql-queries
toc:
- - '##'
  - 前言
- - '###'
  - 引言
- - '###'
  - 概述
- - '####'
  - 双管齐下的方法
- - '####'
  - 本书适合谁？
- - '####'
  - 本书目标
- - '####'
  - 第二版新增内容
- - '###'
  - 目录
- - '###'
  - 速览目录
- - '###'
  - 关于作者
- - '###'
  - 关于技术审阅者
- - '###'
  - 致谢
- - '###'
  - 索引
- - '###'
  - 脚注
- - '##'
  - 第1章：关系型数据库概述
- - '###'
  - 介绍数据库表
- - '####'
  - 属性
- - '####'
  - 主键
- - '####'
  - 在表中插入和更新行
- - '####'
  - 设计合适的表
- - '###'
  - 介绍数据模型
- - '###'
  - 从数据库检索信息
- - '####'
  - 过程方法
- - '####'
  - 结果方法
- - '###'
  - 为何考虑两种方法
- - '###'
  - 总结
- - '##'
  - 第2章：单表简单查询
- - '###'
  - 行和列的子集
- - '###'
  - 使用别名
- - '###'
  - 保存查询
- - '###'
  - 指定选择行的条件
- - '####'
  - 比较运算符
- - '####'
  - 逻辑运算符
- - '###'
  - 处理空值
- - '####'
  - 查找空值
- - '####'
  - 涉及空值的比较
- - '###'
  - 管理重复项
- - '###'
  - 排序输出
- - '###'
  - 进行简单计数
- - '###'
  - 避免常见错误
- - '####'
  - 错误地使用 WHERE 子句来回答包含“both（两者都）”的问题
- - '####'
  - 错误地使用 WHERE 子句来回答包含“not（未）”的问题
- - '###'
  - 总结
- - '##'
  - 第3章：初识连接
- - '###'
  - 连接的过程式方法
- - '####'
  - 笛卡尔积
- - '####'
  - 内连接
- - '###'
  - 连接的结果方法
- - '###'
  - 扩展连接查询
- - '####'
  - 过程方法
- - '####'
  - 操作顺序
- - '####'
  - 结果方法
- - '####'
  - 通过图形界面表达连接
- - '###'
  - 其他类型的连接
- - '###'
  - 外连接
- - '###'
  - 概要
- - '##'
  - 第4章：子查询
- - '###'
  - IN 关键字
- - '###'
  - 与子查询一起使用 IN
- - '###'
  - 谨慎使用 `NOT` 和 `<>`
- - '###'
  - EXISTS 关键字
- - '###'
  - 不同类型的子查询
- - '####'
  - 返回单个值的内部查询
- - '####'
  - 返回一组值的内部查询
- - '####'
  - 检查存在性的内部查询
- - '###'
  - 使用子查询进行更新
- - '###'
  - 总结
- - '####'
  - 不同类型子查询的示例
- - '#####'
  - 返回单个值的子查询
- - '#####'
  - 返回一组单值的子查询
- - '#####'
  - 检查存在性的子查询
- - '####'
  - 子查询不同用途的示例
- - '#####'
  - 构造带否定的查询
- - '#####'
  - 与聚合结果比较值
- - '#####'
  - 更新数据
- - '##'
  - 第5章：自连接
- - '###'
  - 自关系
- - '####'
  - 创建自连接
- - '####'
  - 涉及自连接的查询
- - '#####'
  - 教练的名字是什么？
- - '#####'
  - 谁正在由一个差点杆数更高的人教练？
- - '#####'
  - 列出所有成员的名字及其教练的名字
- - '###'
  - 谁指导教练，或者说，谁是我的祖母？
- - '####'
  - 自连接的结果导向方法
- - '###'
  - 涉及“两者”的问题
- - '####'
  - 解决“两者”问题的结果导向法
- - '####'
  - 解决“两者”问题的过程导向法
- - '###'
  - 总结
- - '####'
  - 自关系
- - '####'
  - 涉及“两者”一词的问题
- - '##'
  - 第6章：表间的多重关系
- - '###'
  - 同一表之间的两种关系
- - '####'
  - 从多重关系中提取信息
- - '####'
  - 过程方法
- - '####'
  - 结果方法
- - '###'
  - 业务规则
- - '###'
  - 摘要
- - '##'
  - 第7章：集合运算
- - '###'
  - 基本集合操作概述
- - '###'
  - 联合兼容表
- - '####'
  - 确保并集兼容性
- - '###'
  - Union
- - '####'
  - 选择合适的列
- - '###'
  - 联合的用途
- - '###'
  - 联合与完全外连接
- - '###'
  - 交集
- - '####'
  - 交集的用途
- - '####'
  - 投影适当列的重要性
- - '###'
  - 不使用 INTERSECT 关键字进行管理
- - '###'
  - 差集
- - '####'
  - 差集的用途
- - '####'
  - 在没有 EXCEPT 关键字的情况下进行管理
- - '###'
  - 除法
- - '####'
  - 投影适当的列
- - '####'
  - SQL 中的除法运算
- - '###'
  - 小结
- - '####'
  - 并集
- - '####'
  - 交集
- - '####'
  - 差集
- - '####'
  - 除法
- - '##'
  - 第8章：聚合操作
- - '###'
  - 简单的聚合函数
- - '####'
  - COUNT() 函数
- - '####'
  - 处理空值
- - '####'
  - 处理重复值
- - '###'
  - AVG() 函数
- - '####'
  - 处理空值
- - '####'
  - 处理重复值
- - '####'
  - 处理类型和输出
- - '###'
  - ROUND() 函数
- - '###'
  - 其他聚合函数
- - '###'
  - 分组
- - '####'
  - 在 SELECT 子句中包含分组字段
- - '####'
  - 在分组前连接表
- - '####'
  - SELECT 子句的 GROUP BY 规则
- - '####'
  - 将 GROUP BY 与 WHERE 子句结合
- - '####'
  - 按多个字段分组
- - '####'
  - 与其他聚合函数一起分组
- - '###'
  - 过滤聚合查询的结果
- - '###'
  - 使用聚合执行除法运算
- - '###'
  - 嵌套查询与聚合函数
- - '###'
  - 本章小结
- - '##'
  - 第9章：窗口函数
- - '###'
  - 简单聚合函数
- - '###'
  - 分区
- - '###'
  - ORDER BY 子句
- - '####'
  - 累计聚合
- - '####'
  - 排名
- - '####'
  - 排序与分区结合
- - '###'
  - 帧规范
- - '###'
  - 总结
- - '####'
  - OVER()
- - '####'
  - OVER(PARTITION BY <…>)
- - '####'
  - OVER(ORDER BY <…>)
- - '####'
  - OVER(PARTITION BY <…> ORDER BY <…>)
- - '####'
  - OVER(ROWS BETWEEN <…> AND <…>)
- - '##'
  - 第10章：效率考量
- - '###'
  - 查询的处理过程
- - '###'
  - 查找记录
- - '###'
  - 按顺序存储记录
- - '###'
  - 聚集索引
- - '###'
  - 非聚集索引
- - '####'
  - 复合键上的聚集索引
- - '####'
  - 更新索引
- - '####'
  - 覆盖索引
- - '####'
  - 索引的选择性
- - '###'
  - 连接技术
- - '####'
  - 嵌套循环
- - '####'
  - 合并连接
- - '###'
  - 用于连接的不同 SQL 表达式
- - '###'
  - 总结
- - '####'
  - 主键
- - '####'
  - 外键
- - '####'
  - WHERE 条件
- - '####'
  - ORDER BY、GROUP BY 和 DISTINCT
- - '####'
  - 善用工具
- - '##'
  - 第11章：如何处理查询
- - '###'
  - 理解数据
- - '###'
  - 确定表格之间的关系
- - '###'
  - 现实世界 vs 实现
- - '###'
  - 涉及哪些表？
- - '###'
  - 查看一些数据值
- - '###'
  - 宏观方法
- - '####'
  - 组合表
- - '####'
  - 找出所需的行子集
- - '####'
  - 保留所需的列
- - '####'
  - 考虑使用中间视图
- - '###'
  - 识别问题中的关键词
- - '###'
  - SQL 查询条件分析
- - '####'
  - And, Both, Also
- - '####'
  - Not, Never
- - '####'
  - All, Every
- - '###'
  - 无从下手？
- - '####'
  - 找到一些有用的表
- - '####'
  - 尝试手工回答问题
- - '####'
  - 写下对检索结果的描述
- - '####'
  - 有替代方案吗？
- - '###'
  - 检查查询
- - '####'
  - 检查一条应该被返回的行
- - '####'
  - 检查不应被返回的行
- - '####'
  - 检查边界条件
- - '####'
  - 检查空值
- - '###'
  - 总结
- - '##'
  - 第12章：常见问题
- - '###'
  - 糟糕的数据库设计
- - '####'
  - 未规范化的数据
- - '####'
  - 无主键的表
- - '####'
  - 缺少外键的表
- - '####'
  - 两个表中的相似数据
- - '####'
  - 不恰当的类型
- - '###'
  - 数据值问题
- - '####'
  - 意外的空值
- - '####'
  - 不正确或不一致的拼写
- - '###'
  - 文本字段中的多余字符
- - '###'
  - 文本字段中不一致的大小写
- - '###'
  - 诊断问题
- - '####'
  - 独立检查嵌套查询的部分
- - '####'
  - 理解表是如何组合的
- - '####'
  - 删除额外的 WHERE 子句
- - '####'
  - 保留所有列
- - '####'
  - 检查聚合中的底层查询
- - '###'
  - 常见症状
- - '####'
  - 未返回任何行
- - '####'
  - 缺少行
- - '#####'
  - 是否需要外连接？
- - '#####'
  - 选择条件是否正确处理了空值？
- - '#####'
  - 你是否在查找与文本值的匹配？
- - '#####'
  - 是否误用了 AND 代替 OR？
- - '#####'
  - 集合操作中的列是否正确？
- - '####'
  - 比应有的行数更多
- - '#####'
  - 你是否用了 `NOT` 而不是差集运算符？
- - '#####'
  - 你是否恰当地处理了重复项？
- - '####'
  - 错误的统计信息或聚合
- - '####'
  - 顺序错误
- - '####'
  - 常见的拼写错误和语法问题
- - '###'
  - 总结
- - '##'
  - 附录
- - '###'
  - 附录1：示例数据库
- - '###'
  - 附录2：关系符号
- - '####'
  - 引言
- - '#####'
  - 关系、元组和属性
- - '####'
  - SQL、代数与微积分
- - '####'
  - 关系代数：指定操作
- - '#####'
  - 选择
- - '#####'
  - 投影
- - '#####'
  - 结合选择与投影
- - '#####'
  - 笛卡尔积
- - '#####'
  - 内连接
- - '####'
  - 并集、差集与交集
- - '####'
  - 除法
- - '####'
  - 关系演算：指定结果
- - '#####'
  - 简单演算表达式
- - '#####'
  - 自由变量与绑定变量
- - '#####'
  - 存在量词与 SQL
- - '####'
  - 全称量词和 SQL
- - '####'
  - 示例
- - '#####'
  - 代数
- - '#####'
  - 演算
- - '#####'
  - 结论
- - '####'
  - 脚注
- - '####'
  - 索引
