name: Expert Oracle GoldenGate
name_cn: Oracle GoldenGate 专家指南
slug: expert-oracle-goldengate
toc:
- - '#'
  - 精通 Oracle GoldenGate
- - '##'
  - 目录
- - '##'
  - 第1章：简介
- - '###'
  - 分布式处理与复制
- - '###'
  - Oracle 基础复制
- - '###'
  - Oracle 高级复制
- - '###'
  - Oracle Streams 复制
- - '###'
  - 演进与 Oracle GoldenGate
- - '###'
  - 小结
- - '##'
  - 第2章：安装
- - '###'
  - 下载软件
- - '####'
  - 从 Oracle E-Delivery 下载
- - '####'
  - 从 OTN 下载
- - '###'
  - 了解您的环境
- - '###'
  - 审阅安装说明
- - '###'
  - 安装 GoldenGate
- - '####'
  - 系统要求
- - '#####'
  - 通用系统要求
- - '#####'
  - 数据库服务器版本
- - '#####'
  - 内存要求
- - '#####'
  - 磁盘空间要求
- - '#####'
  - 网络要求
- - '#####'
  - 操作系统要求
- - '#####'
  - Microsoft Windows 集群环境的要求
- - '####'
  - 在 Windows 上安装 GoldenGate
- - '####'
  - 在 Linux 和 UNIX 上安装 GoldenGate 11g
- - '####'
  - 在 Linux 和 UNIX 上设置 Oracle 与 GoldenGate 的环境
- - '####'
  - GoldenGate 与 Oracle RAC 注意事项
- - '####'
  - 在 Windows 上为 Microsoft SQL Server 安装 GoldenGate
- - '####'
  - 在 Windows 和 UNIX 上为 Teradata 安装 GoldenGate
- - '#####'
  - Teradata 与 Oracle GoldenGate 的系统要求
- - '######'
  - Oracle GoldenGate 复制服务器
- - '######'
  - 磁盘要求
- - '####'
  - 在 Windows 和 UNIX 上为 Sybase 安装 GoldenGate
- - '####'
  - 在 Windows 和 UNIX 上为 IBM DB2 UDB 安装 GoldenGate
- - '###'
  - 安装 Oracle GoldenGate Director 11g
- - '####'
  - 系统要求
- - '#####'
  - 受支持的平台
- - '#####'
  - 软件要求
- - '#####'
  - GoldenGate Director 客户端安装要求
- - '#####'
  - GoldenGate Director Web 客户端安装指南
- - '####'
  - 安装 Oracle GoldenGate Director Server
- - '#####'
  - 向 Oracle GoldenGate Director Server 模式授予数据库权限和凭证
- - '####'
  - 安装 Oracle GoldenGate Director
- - '###'
  - 安装 Oracle GoldenGate Veridata
- - '####'
  - GoldenGate Veridata Agent 系统要求
- - '#####'
  - 磁盘要求
- - '#####'
  - 内存要求
- - '#####'
  - 数据库权限
- - '####'
  - GoldenGate Veridata Server 系统要求
- - '#####'
  - 磁盘要求
- - '#####'
  - 内存要求
- - '#####'
  - GoldenGate Veridata 服务器软件要求
- - '#####'
  - GoldenGate Veridata 服务器的数据库权限
- - '#####'
  - GoldenGate Veridata Web 安装要求
- - '#####'
  - 安装 Oracle GoldenGate Veridata
- - '###'
  - 小结
- - '##'
  - 第3章：架构
- - '###'
  - 典型的 GoldenGate 流程
- - '###'
  - GoldenGate 组件
- - '####'
  - 源数据库
- - '####'
  - 捕获（本地提取）进程
- - '####'
  - 源端 Trail 文件
- - '####'
  - 数据泵
- - '####'
  - 网络
- - '####'
  - 收集器
- - '####'
  - 远程 Trail 文件
- - '####'
  - 投递（复制）
- - '####'
  - 目标数据库
- - '####'
  - 管理器
- - '###'
  - 拓扑与用例
- - '####'
  - 单向复制
- - '####'
  - 双向复制
- - '####'
  - 广播复制
- - '####'
  - 集成复制
- - '###'
  - 工具与实用程序
- - '####'
  - '`GGSCI`'
- - '####'
  - '`DEFGEN`'
- - '####'
  - '`Logdump`'
- - '####'
  - '`Reverse`'
- - '####'
  - '`Veridata`'
- - '####'
  - '`Director`'
- - '###'
  - 摘要
- - '##'
  - 第4章：基础复制
- - '###'
  - 概述
- - '###'
  - 设置复制的先决条件
- - '####'
  - 要求
- - '####'
  - 单向复制拓扑
- - '###'
  - 基础复制步骤
- - '####'
  - 启动 `Extract`
- - '####'
  - 验证数据库级补充日志
- - '####'
  - 启用数据库级补充日志
- - '####'
  - 启用表级补充日志
- - '####'
  - 禁用触发器和级联删除约束
- - '####'
  - 验证 `Manager` 状态
- - '####'
  - 配置本地 `Extract`
- - '#####'
  - 添加 `Extract`
- - '#####'
  - 启动和停止 `Extract`
- - '#####'
  - 验证 `Extract`
- - '####'
  - 启动数据泵
- - '#####'
  - 配置数据泵
- - '#####'
  - 添加数据泵
- - '#####'
  - 启动和停止数据泵
- - '#####'
  - 验证数据泵
- - '###'
  - 使用 GoldenGate 进行加载
- - '####'
  - GoldenGate 初始加载的先决条件
- - '####'
  - 配置初始加载 `Extract`
- - '#####'
  - 添加初始加载 `Extract`
- - '####'
  - 配置初始加载 `Replicat`
- - '#####'
  - 添加初始加载 `Replicat`
- - '####'
  - 启动 GoldenGate 初始加载
- - '####'
  - 验证初始加载
- - '###'
  - 使用 `DBMS` 工具加载
- - '####'
  - 使用 `DBMS` 工具加载的先决条件
- - '####'
  - 使用 `DBMS` 工具加载的步骤
- - '###'
  - 启动复制（Replicat）
- - '###'
  - 配置复制（Replicat）
- - '###'
  - 添加复制（Replicat）
- - '###'
  - 启动和停止复制（Replicat）
- - '###'
  - 验证复制（Replicat）
- - '###'
  - 本章小结
- - '##'
  - 第5章：高级功能
- - '###'
  - 增强复制配置
- - '####'
  - 增强提取与复制报告功能
- - '#####'
  - '`REPORTCOUNT`'
- - '#####'
  - '`REPORT`'
- - '#####'
  - 报告滚动
- - '####'
  - 报告丢弃的记录
- - '####'
  - 清理旧的跟踪文件
- - '####'
  - 添加自动进程启动与重启
- - '####'
  - 添加检查点表
- - '###'
  - 提高复制安全性
- - '####'
  - 加密密码
- - '####'
  - 加密跟踪文件
- - '###'
  - 添加数据过滤与映射
- - '####'
  - 过滤表
- - '####'
  - 过滤列
- - '####'
  - 过滤行
- - '####'
  - 映射列
- - '#####'
  - 生成数据定义文件
- - '####'
  - 转换列
- - '###'
  - Oracle 特定的 DBMS 配置选项
- - '####'
  - 为 Oracle RAC 进行配置
- - '#####'
  - 同步节点
- - '#####'
  - 连接到数据库
- - '#####'
  - 定义线程
- - '####'
  - 为 Oracle ASM 进行配置
- - '#####'
  - 指定 ASM 用户
- - '#####'
  - 更新监听器
- - '#####'
  - 更新 TNSNAMES.ORA
- - '###'
  - 添加 Oracle DDL 复制
- - '####'
  - DDL 复制状态
- - '####'
  - 配置角色
- - '####'
  - 启用 DDL 触发器
- - '####'
  - 更新提取参数文件
- - '###'
  - 添加双向复制
- - '####'
  - 为双向复制排除事务
- - '####'
  - 处理双向复制的冲突解决方案
- - '###'
  - 本章小结
- - '##'
  - 第6章：异构复制
- - '###'
  - 从 Microsoft SQL Server 到 Oracle 的复制
- - '####'
  - 准备 Oracle GoldenGate 环境
- - '####'
  - 完成 Oracle GoldenGate 环境的初始数据加载
- - '####'
  - 源 Oracle 数据库配置
- - '#####'
  - 在源 Oracle 数据库系统上配置源定义
- - '#####'
  - 在 Oracle 源系统上执行源定义生成器
- - '#####'
  - 将源定义文件传输到目标 Microsoft SQL Server 系统
- - '####'
  - 目标 Microsoft SQL Server 数据库配置
- - '####'
  - 创建示例 Microsoft SQL Server 数据库
- - '####'
  - 在源端配置变更数据捕获
- - '###'
  - MySQL 到 Oracle 复制
- - '###'
  - Teradata 到 Oracle 复制
- - '###'
  - Sybase 到 Oracle 复制
- - '###'
  - IBM DB2 UDB 到 Oracle 复制
- - '###'
  - 验证操作就绪状态
- - '###'
  - 本章小结
- - '##'
  - 第7章：性能调优
- - '###'
  - 调优方法论
- - '####'
  - 定义性能要求
- - '####'
  - 创建性能基线
- - '####'
  - 评估当前性能
- - '####'
  - 确定问题
- - '####'
  - 设计并实施解决方案
- - '###'
  - 使用并行提取与复制
- - '####'
  - 使用表过滤实现并行提取与复制
- - '####'
  - 使用键范围实现并行提取与复制
- - '###'
  - 使用 `BATCHSQL`
- - '###'
  - 使用 `GROUPTRANSOPS`
- - '###'
  - 调优磁盘存储
- - '###'
  - 调优网络
- - '####'
  - 调优 `RMTHOST` 参数
- - '###'
  - 调优数据库
- - '###'
  - 总结
- - '##'
  - 第8章：监控 Oracle GoldenGate
- - '###'
  - 设计监控策略
- - '####'
  - 为何监控提取进程很重要
- - '####'
  - 获取最大阈值
- - '###'
  - 在 GoldenGate 环境中应监控哪些进程
- - '####'
  - 监控所有正在运行的进程
- - '####'
  - 监控详细提取进程
- - '####'
  - 检查当前的 Oracle 在线重做日志
- - '####'
  - 检查归档日志
- - '####'
  - 监控 GoldenGate 速率与重做日志消耗速率
- - '####'
  - 监控每个组的延迟
- - '###'
  - 查看事件与错误日志
- - '###'
  - 自动化监控
- - '####'
  - 检查 GoldenGate 进程的脚本
- - '####'
  - 监控延迟的脚本
- - '####'
  - 检查内存与 CPU 的脚本
- - '####'
  - 检查磁盘空间
- - '###'
  - 总结
- - '##'
  - 第9章：Oracle GoldenGate Veridata
- - '###'
  - Veridata 组件
- - '####'
  - GoldenGate Veridata 服务器
- - '####'
  - GoldenGate Veridata Web
- - '####'
  - GoldenGate Veridata 仓库
- - '####'
  - GoldenGate Veridata 代理、Java 和 C 代码
- - '####'
  - GoldenGate Veridata 命令行界面 (`Vericom`)
- - '###'
  - Veridata 比对如何工作
- - '###'
  - Veridata 如何为您提供帮助
- - '###'
  - 设置 Veridata 比对
- - '####'
  - 创建数据库连接
- - '####'
  - 设置表与数据脚本
- - '####'
  - 创建一个组
- - '####'
  - 创建比对对
- - '####'
  - 创建一个作业
- - '####'
  - 创建一个配置文件
- - '####'
  - 运行 Veridata 作业
- - '###'
  - 提升性能并降低开销
- - '####'
  - 排除列
- - '####'
  - 调优配置文件设置
- - '####'
  - 禁用“确认不同步”步骤
- - '####'
  - 增加线程数量
- - '###'
  - 比对方法
- - '####'
  - 对字符字段进行右修剪
- - '####'
  - 比较大型表的增量数据
- - '####'
  - 比较 GoldenGate 实时复制数据
- - '####'
  - 比较不同列类型与比较格式
- - '###'
  - 使用性能统计信息
- - '###'
  - 使用 Vericom 命令行
- - '###'
  - 设置基于角色的安全性
- - '###'
  - 总结
- - '##'
  - 第10章：GoldenGate Director
- - '###'
  - Director 组件
- - '####'
  - GoldenGate GGSCI 实例
- - '####'
  - Director 管理员
- - '####'
  - Director 服务器与数据库
- - '####'
  - Director Web
- - '####'
  - Director 客户端
- - '###'
  - 设置数据源
- - '###'
  - 修改管理器参数文件
- - '####'
  - 使用内置编辑器修改参数文件
- - '####'
  - 使用 GUI 修改参数文件
- - '###'
  - 设置初始加载
- - '####'
  - 添加初始加载任务
- - '###'
  - 创建单向复制
- - '####'
  - 添加数据泵进程
- - '###'
  - Director 的其他功能与技巧
- - '####'
  - 更改 Extract 或 Replicat 的运行选项
- - '####'
  - 更改 Trail 文件大小
- - '####'
  - 提取 `Tranlogoptions`
- - '####'
  - 生成定义文件
- - '####'
  - 在 Director 中查找参数或属性
- - '####'
  - 高级映射
- - '####'
  - 警报
- - '###'
  - 总结
- - '##'
  - 第11章：Oracle GoldenGate 故障排除
- - '###'
  - 常见问题与解决方案
- - '###'
  - Oracle GoldenGate 进程故障
- - '####'
  - Oracle GoldenGate Extract 进程故障
- - '####'
  - 无报告诊断的 Oracle GoldenGate 进程故障
- - '###'
  - Oracle GoldenGate Trail 文件问题
- - '####'
  - Trail 文件无法清空
- - '####'
  - Trail 文件不回滚
- - '####'
  - Trail 文件清除问题
- - '####'
  - Trail 文件清除过早
- - '###'
  - Oracle GoldenGate 错误日志分析
- - '###'
  - 理解 Oracle GoldenGate 丢弃文件
- - '####'
  - 未创建丢弃文件
- - '####'
  - 丢弃文件过大
- - '####'
  - 无法打开丢弃文件
- - '###'
  - 在 Oracle GoldenGate 中使用跟踪命令
- - '####'
  - 使用 TLTRACE 跟踪 Oracle GoldenGate 进程
- - '####'
  - 在 Oracle GoldenGate 中使用 TRACE 参数
- - '###'
  - Oracle GoldenGate 故障排除案例研究
- - '####'
  - Oracle GoldenGate 配置问题
- - '#####'
  - Oracle GoldenGate 软件版本不正确
- - '#####'
  - 数据库可用性问题
- - '#####'
  - 缺少 Oracle GoldenGate 进程组
- - '#####'
  - 缺少 Oracle GoldenGate 跟踪文件
- - '#####'
  - Oracle GoldenGate 参数文件配置问题
- - '#####'
  - Oracle GoldenGate 操作系统配置问题
- - '#####'
  - Oracle GoldenGate 网络配置问题
- - '####'
  - 网络数据传输问题
- - '####'
  - 与 GoldenGate 相关的 Oracle 数据库问题
- - '#####'
  - Extract 无法访问 Oracle 数据库归档和重做日志
- - '#####'
  - 由于 Oracle 源数据库问题导致的 Extract 失败条件
- - '####'
  - 数据泵错误
- - '####'
  - Oracle 目标数据库系统上的 Replicat 错误
- - '#####'
  - Replicat 在目标系统上挂起
- - '#####'
  - Replicat 在目标系统上遇到异常中止故障
- - '#####'
  - Replicat 在处理大事务时失败
- - '#####'
  - Replicat 遇到不兼容记录错误
- - '####'
  - 数据同步问题
- - '#####'
  - 表缺少关键约束
- - '#####'
  - 字符集配置问题
- - '#####'
  - 缺少列错误
- - '#####'
  - 提取失败
- - '###'
  - 总结
- - '##'
  - 第12章：灾难恢复复制
- - '###'
  - 先决条件
- - '####'
  - 要求
- - '###'
  - 灾难恢复复制拓扑
- - '###'
  - 设置
- - '###'
  - 配置用于灾难恢复的本地 Extract
- - '###'
  - 配置用于灾难恢复的数据泵
- - '###'
  - 配置用于灾难恢复的 Replicat
- - '###'
  - 配置备用 Extract
- - '###'
  - 配置备用数据泵
- - '###'
  - 配置备用 Replicat
- - '###'
  - 执行计划内的切换
- - '###'
  - 执行计划外的故障转移
- - '###'
  - 总结
- - '##'
  - 第13章：零停机迁移复制
- - '###'
  - 先决条件
- - '####'
  - 要求
- - '###'
  - 零停机迁移拓扑
- - '###'
  - 设置
- - '###'
  - 为零停机迁移配置本地 Extract
- - '###'
  - 配置数据泵以实现零停机迁移
- - '###'
  - 配置 Replicat 以实现零停机迁移
- - '####'
  - 为零停机迁移配置本地备用 Extract
- - '#####'
  - 审查本地 Extract 参数
- - '#####'
  - 添加备用 Extract
- - '####'
  - 为零停机迁移配置备用数据泵
- - '#####'
  - 审查数据泵参数
- - '#####'
  - 添加数据泵 Extract 组
- - '####'
  - 为零停机迁移配置备用 Replicat
- - '#####'
  - 创建 Replicat 参数文件
- - '#####'
  - 添加 Replicat 组
- - '###'
  - 执行迁移切换
- - '###'
  - 执行迁移回退
- - '###'
  - 总结
- - '##'
  - 第14章：技巧与窍门
- - '###'
  - 需求与规划
- - '####'
  - 了解业务目标
- - '####'
  - 理解需求
- - '####'
  - 确定拓扑结构
- - '###'
  - 安装与设置
- - '####'
  - 创建专用用户
- - '####'
  - 加密密码
- - '####'
  - 创建专用安装目录
- - '####'
  - 使用检查点表
- - '####'
  - 验证字符集
- - '####'
  - 制定命名标准
- - '####'
  - 使用数据泵
- - '###'
  - 管理与监控
- - '####'
  - 使用 GGSCI 命令快捷方式
- - '####'
  - 使用 OBEY 文件
- - '####'
  - 生成临时统计数据
- - '####'
  - 使用废弃文件
- - '####'
  - 定期报告进程健康状况
- - '####'
  - 定期清理旧的 Trail 文件
- - '####'
  - 自动启动进程
- - '###'
  - 性能
- - '####'
  - 运行性能测试
- - '####'
  - 限制 Extract 的数量
- - '####'
  - 为数据泵使用 Passthru 模式
- - '####'
  - 使用并行 Replicat
- - '####'
  - 使用最快的可用存储
- - '####'
  - 调优数据库
- - '###'
  - 总结
- - '##'
  - 附录：Oracle GoldenGate 管理员的附加技术资源
- - '###'
  - Oracle GoldenGate 命令快速指南
- - '####'
  - ADD
- - '####'
  - GGSCI
- - '####'
  - HELP
- - '####'
  - INFO
- - '####'
  - SEND
- - '####'
  - STATUS
- - '###'
  - 用于故障排除的 Logdump 命令和语法
- - '####'
  - 访问 Logdump 实用程序
- - '####'
  - 获取 Logdump 语法帮助
- - '####'
  - HISTORY
- - '####'
  - 使用 Logdump 打开 GoldenGate 跟踪文件
- - '##'
  - 索引
- - '###'
  - '![images](img/square.jpg)A'
- - '###'
  - '![images](img/square.jpg)B'
- - '###'
  - '![images](img/square.jpg)C'
- - '###'
  - 对比对
- - '###'
  - 对比
- - '###'
  - 对比对
- - '###'
  - 组件
- - '###'
  - '`COMPRESS` 选项'
- - '###'
  - 压缩的行哈希数据
- - '###'
  - '`compressupdates` 参数'
- - '###'
  - 配置
- - '###'
  - '`config.xml` 文件'
- - '###'
  - '`Confirm Out of Sync` 步骤'
- - '###'
  - 确认对比
- - '###'
  - '`Confirmation Compares` 配置文件设置'
- - '###'
  - '`Confirmed-Out-Of-Sync (COOS)` 报告'
- - '###'
  - 冲突解决
- - '###'
  - 连接配置
- - '###'
  - '`Connection Configuration` 选项'
- - '###'
  - 数据库连接
- - '###'
  - 约束
- - '###'
  - 重做日志的消耗速率
- - '###'
  - '`convchk` 实用程序'
- - '###'
  - '`COOS (Confirmed-Out-Of-Sync)` 报告'
- - '###'
  - 损坏的检查点错误
- - '###'
  - CPU（中央处理器）脚本
- - '###'
  - '`CREATE TABLE AS SELECT` 选项'
- - '###'
  - 数据库权限与凭据
- - '###'
  - 跨数据库对比
- - '###'
  - CSI（客户支持标识符）账户
- - '###'
  - '`CUSTOMER` 表'
- - '###'
  - 迁移割接
- - '###'
  - '![images](img/square.jpg)D'
- - '###'
  - 数据同步问题
- - '###'
  - 数据时效性
- - '###'
  - 数据定义语言（DDL）复制
- - '###'
  - 数据定义文件，生成
- - '###'
  - 数据过滤
- - '###'
  - 数据映射，列
- - '###'
  - 数据迁移项目
- - '###'
  - Data Pump 进程
- - '###'
  - 数据泵
- - '###'
  - 数据需求
- - '###'
  - 数据脚本
- - '###'
  - 数据源，Director 应用程序
- - '###'
  - 数据验证
- - '###'
  - 数据量
- - '###'
  - 数据库组件，Director Server 及
- - '###'
  - 数据库连接
- - '###'
  - 数据库错误消息
- - '###'
  - 数据库管理系统
- - '###'
  - 数据库迁移项目
- - '###'
  - 数据库性能统计信息
- - '###'
  - 数据库权限
- - '###'
  - 数据库服务器版本，Oracle GoldenGate 支持的
- - '###'
  - 数据库排序方法
- - '###'
  - 数据库级补充日志记录
- - '###'
  - 数据库
- - '###'
  - 数据同步与 Oracle GoldenGate 组件
- - '###'
  - 数据同步问题
- - '###'
  - Extract 进程
- - '###'
  - 提取失败
- - '###'
  - 缺少列的错误
- - '###'
  - Replicat 进程
- - '###'
  - 表缺少主键约束
- - '###'
  - 源端
- - '###'
  - 目标端
- - '###'
  - 调优
- - '###'
  - 数据泵 Extract 组
- - '###'
  - 添加
- - '###'
  - 启动
- - '###'
  - 停止
- - '###'
  - '`DBLOGIN`命令'
- - '###'
  - DBMS（数据库管理系统）
- - '###'
  - 配置选项
- - '###'
  - 用于 ASM
- - '###'
  - DDL 复制
- - '###'
  - 用于 RAC
- - '###'
  - 实用程序，用于加载
- - '###'
  - DBMS 厂商加载实用程序
- - '###'
  - '`DBOPTIONS`参数'
- - '###'
  - DDL（数据定义语言）复制
- - '###'
  - '`ddl_setup.sql`'
- - '###'
  - 创建专用安装目录
- - '###'
  - 创建专用用户
- - '###'
  - '`DEFERREFCONST`选项'
- - '###'
  - '`defgen`命令'
- - '###'
  - '`DEFGEN`实用程序'
- - '###'
  - 定义文件
- - '###'
  - 生成
- - '###'
  - 将源传输到目标 Microsoft SQL Server 系统
- - '###'
  - 在 Oracle 源系统上执行定义生成器
- - '###'
  - '`DELETE REPLICAT`命令，GGSCI'
- - '###'
  - 投递
- - '###'
  - 桌面客户端，Director 组件
- - '###'
  - 详细信息，添加和监控
- - '###'
  - '`detail data`命令，Logdump'
- - '###'
  - Detail 特性，Extract
- - '###'
  - '`DETAIL`选项'
- - '###'
  - '`INFO EXTRACT <group>`命令'
- - '###'
  - '`INFO EXTRACT`命令'
- - '###'
  - '`INFO REPLICAT <group>`命令'
- - '###'
  - '`INFO REPLICAT`命令'
- - '###'
  - '`START EXTRACT <extract name>`命令'
- - '###'
  - '`DetailReportView`角色名称，Tomcat Web 服务器管理工具屏幕'
- - '###'
  - 诊断，报告，在没有诊断信息的情况下处理进程失败
- - '###'
  - '`dirdat`目录'
- - '###'
  - '`dirdef`目录'
- - '###'
  - Director 11g，Oracle GoldenGate
- - '###'
  - Director 管理工具
- - '###'
  - Director 管理员组件
- - '###'
  - Director 应用程序
- - '###'
  - 高级映射
- - '###'
  - 警报
- - '###'
  - 更改 Extract 和 Replicat 对象的运行选项
- - '###'
  - 更改跟踪文件大小
- - '###'
  - 目录索引
- - '###'
  - Director 组件
- - '###'
  - Director 相关项
- - '###'
  - Data Pump 与数据源
- - '###'
  - 目录与路径
- - '###'
  - 灾难恢复复制
- - '###'
  - 丢弃文件与参数
- - '###'
  - 磁盘相关
- - '###'
  - 其他术语
- - '###'
  - E
- - '###'
  - F
- - '###'
  - '`G`'
- - '###'
  - '`H`'
- - '###'
  - '![images](img/square.jpg) I'
- - '###'
  - '![images](img/square.jpg) J'
- - '###'
  - '![images](img/square.jpg) K'
- - '###'
  - L
- - '###'
  - 延迟
- - '###'
  - Linux
- - '###'
  - 加载, 70–75
- - '###'
  - 本地 Extract
- - '###'
  - Logdump 实用程序, 用于故障排除的命令和语法, 296–300
- - '###'
  - 日志记录, 补充
- - '###'
  - 日志
- - '###'
  - M
- - '###'
  - N
- - '###'
  - '![images](img/square.jpg)O'
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - RAC（真正应用集群）
- - '###'
  - RANGE 过滤
- - '###'
  - RATE 信息
- - '###'
  - RBA（相对字节地址）
- - '###'
  - 真正应用集群
- - '###'
  - 真正应用集群（Oracle RAC）
- - '###'
  - 记录
- - '###'
  - 重做日志
- - '###'
  - 参考资料
- - '###'
  - 关系数据库管理系统
- - '###'
  - 关系数据库管理系统（MySQL RDBMS）
- - '###'
  - 相对字节地址 (RBA)
- - '###'
  - 远程目录
- - '###'
  - Replicat
- - '###'
  - '`REPLICAT` 关键字'
- - '###'
  - '`Replicat MAP` 参数'
- - '###'
  - '`Replicat` 对象'
- - '###'
  - '`REPLICAT` 参数'
- - '###'
  - Replicat 参数
- - '###'
  - Replicat 进程
- - '###'
  - 复制
- - '###'
  - 高级
- - '###'
  - 基础
- - '###'
  - 双向
- - '###'
  - 广播
- - '###'
  - 数据，实时
- - '###'
  - 数据过滤
- - '###'
  - 列
- - '###'
  - 行
- - '###'
  - 表
- - '###'
  - 数据映射，列
- - '###'
  - 数据泵
- - '###'
  - DBMS 配置选项
- - '###'
  - 增强配置
- - '###'
  - Extract 进程
- - '###'
  - 和 GoldenGate
- - '###'
  - 异构的。*参见* 异构复制
- - '###'
  - 集成
- - '###'
  - 加载
- - '###'
  - 单向
- - '###'
  - 概述
- - '###'
  - Replicat 进程
- - '###'
  - 安全
- - '###'
  - 服务器
- - '###'
  - Streams 复制
- - '###'
  - 拓扑，单向
- - '###'
  - 用于零停机迁移
- - '###'
  - 无报告的进程故障诊断
- - '###'
  - 报告链接
- - '###'
  - REPORT 参数
- - '###'
  - REPORTCOUNT 参数
- - '###'
  - 报告
- - '###'
  - 丢弃的记录
- - '###'
  - 由 Extract 和 Replicat 进程生成
- - '###'
  - REPORTRATE MIN 命令
- - '###'
  - REPORTROLLOVER 参数
- - '###'
  - ReportViewer 角色名称，Tomcat Web 服务器管理工具屏幕
- - '###'
  - 存储库，Veridata
- - '###'
  - 要求
- - '###'
  - 用于灾难恢复复制
- - '###'
  - 和规划
- - '###'
  - RESETREPORTSTATS 选项
- - '###'
  - Reverse 实用工具
- - '###'
  - RHREMD1.defs 文件
- - '###'
  - 右修剪 (RTRIM)，在字符字段上
- - '###'
  - RMTHOST 参数
- - '###'
  - RMTTASK 参数
- - '###'
  - RMTTRAIL 参数
- - '###'
  - 基于角色的安全
- - '###'
  - 行哈希值
- - '###'
  - 行，过滤
- - '###'
  - RTRIM (右修剪)，在字符字段上
- - '###'
  - 运行作业按钮，Veridata 主屏幕
- - '###'
  - 运行选项，更改 Extract 和 Replicat 对象的选项
- - '###'
  - 运行/执行作业选项卡，Veridata 主屏幕
- - '###'
  - 正在运行的作业面板
- - '###'
  - 运行中状态
- - '###'
  - '![images](img/square.jpg) S 部分'
- - '###'
  - '**安全性**'
- - '###'
  - '**服务器**'
- - '###'
  - '**安装设置**, 281–283'
- - '###'
  - SQL 语句和命令
- - '###'
  - 参数和实用程序
- - '###'
  - 进程状态和命令
- - '###'
  - 灾难恢复复制
- - '###'
  - 存储
- - '###'
  - 补充日志记录
- - '###'
  - 数据库系统
- - '###'
  - 系统要求
- - '###'
  - T
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y, Z
