name: Beginning Database Design
name_cn: 数据库设计入门指南
slug: beginning-database-design
toc:
- - '#'
  - 数据库设计入门：从新手到专家
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '##'
  - 前言
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '###'
  - 致谢
- - '###'
  - 引言
- - '###'
  - 可能出现的问题
- - '##'
  - 第1章：可能出现的问题
- - '###'
  - 可能出错的地方
- - '####'
  - 关键词与类别处理不当
- - '#####'
  - 示例 1-1. 植物数据库
- - '#####'
  - 示例 1-2. 研究兴趣
- - '###'
  - 数据类与关系
- - '###'
  - 重复信息
- - '#####'
  - 示例 1-3. 昆虫数据¹
- - '####'
  - 为单一报告而设计
- - '###'
  - 总结
- - '###'
  - 测试你的理解
- - '#####'
  - 练习 1-1
- - '#####'
  - 练习 1-2
- - '##'
  - 第2章：开发过程导览
- - '###'
  - 初始问题陈述
- - '#####'
  - 示例 2-1. 植物数据库的初始用例
- - '###'
  - 分析与简单数据模型
- - '####'
  - 数据建模入门：使用 UML 类图
- - '#####'
  - 类与对象
- - '#####'
  - 关系
- - '###'
  - 进一步分析：重新审视用例
- - '#####'
  - 示例 2-2. 植物数据库的修订用例
- - '###'
  - 设计
- - '####'
  - 数据库设计与实现
- - '#####'
  - 关系数据库设计概述
- - '#####'
  - 实现
- - '#####'
  - 用于输入用例的界面
- - '#####'
  - 用于输出用例的报告
- - '###'
  - 总结
- - '###'
  - 测试你的理解
- - '#####'
  - 练习 2-1
- - '##'
  - 第3章：初始需求与用例
- - '###'
  - 现实与抽象视图
- - '#####'
  - 问题的现实与抽象视图
- - '#####'
  - 数据整理
- - '#####'
  - 任务自动化
- - '######'
  - 用户做什么？
- - '######'
  - 涉及什么数据？
- - '###'
  - 外卖配送系统数据分析
- - '####'
  - 任务与数据记录
- - '#####'
  - 接单
- - '#####'
  - 派单给司机
- - '#####'
  - 取餐
- - '#####'
  - 送餐
- - '#####'
  - 录入工时表
- - '####'
  - 系统目标是什么？
- - '####'
  - 需要哪些数据来实现目标？
- - '#####'
  - 接单
- - '#####'
  - 派单给司机
- - '#####'
  - 取餐
- - '#####'
  - 送达餐品
- - '#####'
  - 录入时间表
- - '#####'
  - 示例 3-2. 餐品配送问题的重新陈述
- - '####'
  - 输入用例是什么？
- - '#####'
  - 表 3-2. 拟议系统的数据录入与交互物理用户任务
- - '#####'
  - 示例 3-3. 餐饮配送的初始用例
- - '######'
  - 图 3-5. 餐饮用例
- - '####'
  - 什么是第一个数据模型？
- - '#####'
  - 图 3-6. 餐饮配送数据库的首次数据模型尝试
- - '####'
  - 什么是输出用例？
- - '####'
  - 数据分析与扩展思考
- - '#####'
  - 示例 3-4. 餐食配送统计报告用例
- - '####'
  - 关于用例的更多内容
- - '#####'
  - 参与者
- - '#####'
  - 异常与扩展
- - '#####'
  - 用于维护数据的用例
- - '###'
  - 用例分析
- - '####'
  - 数据维护用例
- - '####'
  - 报告信息的用例
- - '####'
  - 深入了解问题
- - '####'
  - 我们推迟了哪些内容？
- - '#####'
  - 变动的价格
- - '#####'
  - 停售的膳食
- - '#####'
  - 特定餐点的数量
- - '###'
  - 小结
- - '###'
  - 检验你的理解
- - '##'
  - 第4章：从数据模型中学习
- - '###'
  - 数据模型回顾
- - '###'
  - 可选性：应该是 0 还是 1？
- - '####'
  - 学生选课示例
- - '####'
  - 客户订单示例
- - '####'
  - 昆虫示例
- - '###'
  - 基数为 1：它偶尔会是 2 吗？
- - '####'
  - 昆虫示例
- - '####'
  - 体育俱乐部示例
- - '###'
  - 基数为 1：历史数据怎么办？
- - '####'
  - 体育俱乐部示例
- - '####'
  - 部门示例
- - '####'
  - 昆虫示例
- - '###'
  - 数据模型中的多对多关系：缺失信息与中间类
- - '####'
  - 数据模型的问题：历史记录的重要性
- - '####'
  - 多对多关系：我们是否遗漏了什么？
- - '#####'
  - 运动俱乐部示例
- - '#####'
  - 学生课程示例
- - '#####'
  - 送餐服务示例
- - '##'
  - 第5章：开发数据模型
- - '###'
  - 属性、类还是关系？
- - '#####'
  - 属性、类或关系？
- - '#####'
  - 示例 5-1：体育俱乐部
- - '###'
  - 类之间的两个或更多关系
- - '###'
  - 类之间的不同路径
- - '###'
  - 冗余、陷阱与数据模型
- - '####'
  - 冗余信息
- - '#####'
  - 示例 5-3：创业孵化器
- - '####'
  - 提供不同信息的路径
- - '####'
  - 路径产生的虚假信息（扇形陷阱）
- - '#####'
  - 示例 5-4：更大的组织
- - '####'
  - 类之间路径的缺口（峡谷陷阱）
- - '####'
  - 同类对象之间的关系
- - '####'
  - 涉及两个以上类的关系
- - '###'
  - 总结
- - '##'
  - 第6章：泛化与特化
- - '###'
  - 具有大量共同点的类或对象
- - '###'
  - 数据建模：继承
- - '####'
  - 数据不一致问题
- - '####'
  - 特化
- - '####'
  - 泛化
- - '####'
  - 继承总结
- - '###'
  - 面向对象设计：继承的适用性、误区与权衡
- - '####'
  - 何时考虑继承（子类与超类）
- - '####'
  - 何时继承不是一个好主意
- - '#####'
  - 混淆对象与子类
- - '#####'
  - 混淆关联与子类
- - '####'
  - 何时值得考虑继承
- - '####'
  - 超类应该拥有对象吗？
- - '####'
  - 属于多个子类的对象
- - '###'
  - 数据库设计中的继承与组合模式
- - '####'
  - 使用角色（契约）作为多重继承的替代方案
- - '####'
  - 复合与聚合
- - '####'
  - 这并不容易
- - '###'
  - 总结
- - '###'
  - 继承的使用原则
- - '###'
  - 测试你的理解
- - '#####'
  - 练习 6-1
- - '#####'
  - 练习 6-2
- - '#####'
  - 练习 6-3
- - '##'
  - 第7章：从数据模型到关系数据库设计
- - '###'
  - 表示模型
- - '###'
  - 表示类和属性
- - '###'
  - 设计数据库表
- - '####'
  - 创建表
- - '####'
  - 选择数据类型
- - '####'
  - 域与约束
- - '#####'
  - 检查字符字段
- - '####'
  - 主键
- - '#####'
  - 确定主键
- - '#####'
  - 连接键
- - '###'
  - 表示关系
- - '####'
  - 外键
- - '####'
  - 参照完整性
- - '####'
  - 表示一对多关系
- - '####'
  - 引用完整性
- - '####'
  - 自关系示例
- - '####'
  - 表示多对多关系
- - '####'
  - 表示一对一关系
- - '###'
  - 表示继承
- - '###'
  - 总结
- - '###'
  - 测试你的理解
- - '##'
  - 第8章：规范化
- - '###'
  - 数据库规范化
- - '####'
  - 更新异常
- - '#####'
  - 插入问题
- - '#####'
  - 删除问题
- - '###'
  - 处理更新异常
- - '###'
  - 函数依赖
- - '#####'
  - 函数依赖的定义
- - '###'
  - 函数依赖与规范化
- - '####'
  - 函数依赖与主键
- - '###'
  - 范式
- - '#####'
  - 第一范式
- - '#####'
  - 第二范式
- - '#####'
  - 第三范式
- - '#####'
  - Boyce–Codd 范式
- - '###'
  - 数据模型还是函数依赖？
- - '###'
  - 其他注意事项
- - '#####'
  - 第四和第五范式
- - '###'
  - 总结
- - '###'
  - 测试你的理解
- - '##'
  - 第9章：深入探讨键与约束
- - '###'
  - 选择主键
- - '###'
  - 关于 ID 号码的更多内容
- - '###'
  - 候选键
- - '###'
  - 使用 ID 号码还是连接键？
- - '###'
  - 表结构设计
- - '###'
  - 唯一约束
- - '###'
  - 使用约束替代类别类
- - '###'
  - 删除被引用的记录
- - '###'
  - 总结
- - '###'
  - 测试你的理解
- - '#####'
  - 练习 9-1
- - '#####'
  - 练习 9-2
- - '##'
  - 第10章：查询基础
- - '###'
  - 单表简单查询
- - '###'
  - 投影操作
- - '###'
  - 选择操作
- - '###'
  - 聚合函数
- - '###'
  - SQL 查询、分组与连接
- - '####'
  - 排序
- - '###'
  - 涉及两个或多个表的查询
- - '####'
  - 连接操作
- - '###'
  - 集合操作
- - '###'
  - 索引如何提供帮助
- - '###'
  - 索引与简单查询
- - '####'
  - 索引如何提升查询速度
- - '#####'
  - 清单 10-15. 在 `Enrollment` 表上创建两个索引
- - '#####'
  - 清单 10-16. 在 `Student` 表上创建一个复合索引
- - '####'
  - 索引的缺点
- - '####'
  - 索引类型
- - '###'
  - 视图
- - '###'
  - 创建视图
- - '###'
  - 视图的用途
- - '###'
  - 小结
- - '###'
  - 测试你的理解
- - '#####'
  - 练习 10-1
- - '##'
  - 第11章：用户界面
- - '###'
  - 输入窗体
- - '####'
  - 基于单表的输入窗体
- - '####'
  - 基于多表的输入窗体
- - '###'
  - 表单上的约束
- - '###'
  - 限制对表单的访问
- - '###'
  - 报告
- - '###'
  - 数据库报表基础
- - '####'
  - 基于视图创建报告
- - '####'
  - 报告的主要组成部分
- - '####'
  - 分组与汇总
- - '###'
  - 总结
- - '###'
  - 表单、报告及其他实现方式
- - '###'
  - 测试你的理解
- - '#####'
  - 练习 11-1
- - '##'
  - 第12章：其他实现方式
- - '###'
  - 面向对象实现
- - '####'
  - 类与对象
- - '####'
  - 复杂类型与方法
- - '####'
  - 使用复杂属性类型
- - '####'
  - 对象集合
- - '####'
  - 表示关系
- - '#####'
  - 导航与关系表示
- - '#####'
  - 多对多关系的表示
- - '####'
  - OO 环境
- - '###'
  - 在电子表格中实现数据模型
- - '###'
  - 电子表格在数据管理中的应用
- - '####'
  - 电子表格的优缺点
- - '####'
  - 示例：简单订单模型
- - '####'
  - 优化的数据模型
- - '####'
  - 在电子表格中实现关系
- - '#####'
  - 表示一对多关系
- - '####'
  - 数据验证与参照完整性
- - '####'
  - 多对多关系
- - '#####'
  - 重复列
- - '#####'
  - 类别作为列
- - '#####'
  - 规范化范围
- - '###'
  - 在 XML 中实现
- - '###'
  - 表示关系
- - '###'
  - 定义 XML 类型
- - '###'
  - 查询 XML
- - '###'
  - NoSQL
- - '###'
  - 总结
- - '###'
  - 面向对象数据库
- - '###'
  - 数据存储与表示
- - '####'
  - 面向对象数据库设计注意事项
- - '####'
  - 电子表格
- - '####'
  - XML
- - '##'
  - 附录
- - '###'
  - 测试你的理解
- - '#####'
  - 练习 1-1
- - '#####'
  - 练习 1-2
- - '#####'
  - 练习 2-1
- - '#####'
  - a)  思考不同数据项可能在何时录入。为数据录入绘制一个初始的用例图。
- - '#####'
  - b)  考虑你需要维护哪些不同类型的信息，并绘制一个简单的类图。
- - '#####'
  - c)  你可以向俱乐部建议哪些不同的报告呈现方式？你的类图是否能方便地获取所需信息？
- - '#####'
  - 练习 3-1
- - '####'
  - 学生出勤系统设计过程
- - '#####'
  - 5. 草拟数据输入用例——考虑异常情况——检查现有表单
- - '#####'
  - 6. 考虑异常情况和复杂问题
- - '#####'
  - 7. 草拟第一个数据模型
- - '#####'
  - 8. 根据收集的数据，头脑风暴可能的输出
- - '###'
  - 练习
- - '#####'
  - 练习 4-1
- - '#####'
  - 练习 4-2
- - '#####'
  - 练习 4-3
- - '####'
  - 预订模型的问题与业务规则
- - '#####'
  - 练习 5-1
- - '#####'
  - 练习 5-2
- - '#####'
  - 练习 5-3
- - '#####'
  - 练习 5-4
- - '#####'
  - 练习 6-1
- - '#####'
  - 练习 6-2
- - '#####'
  - 练习 6-3
- - '#####'
  - 练习 7-1
- - '####'
  - 图书馆数据模型与关系数据库设计
- - '#####'
  - 解释数据模型
- - '#####'
  - 转换为关系数据库
- - '#####'
  - 练习 8-3
- - '####'
  - 函数依赖分析
- - '#####'
  - 问题 c)
- - '#####'
  - 问题 d)
- - '#####'
  - 练习 9-1
- - '#####'
  - 练习 9-2
- - '#####'
  - 图 A-38：保存车辆信息的可能模型
- - '#####'
  - 练习 10-1
- - '######'
  - 图 A-39：用于送餐的表
- - '######'
  - 图 A-40：餐品表和订单 _ 餐品表连接的结果
- - '######'
  - 图 A-41：餐品表、订单 _ 餐品表和订单表连接后的部分列
- - '#####'
  - 练习 11-1
- - '######'
  - 图 A-42：记录和报告学校缺勤情况的用例
- - '######'
  - 图 A-43：记录学校缺勤情况的数据模型
- - '######'
  - 图 A-44：学校缺勤情况的一些数据
- - '######'
  - 图 A-45. 录入缺勤情况的表单
- - '######'
  - 代码清单 A-7. 从所有三张表中检索信息的 SQL
- - '######'
  - 图 A-46. 从图 A-8 中视图检索出的数据
- - '######'
  - 图 A-47. 为每位班级教师分组的当前缺勤情况
- - '######'
  - 图 A-48. 通过不同分组和汇总方式可能生成的报告示例
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '####'
  - 异常和扩展
- - '####'
  - 可扩展标记语言 (XML)
- - '#####'
  - 描述
- - '#####'
  - 层次化表示
- - '#####'
  - 查询
- - '#####'
  - 类型
- - '######'
  - DTD
- - '######'
  - XSD
- - '###'
  - F
- - '####'
  - 扇形陷阱，组织模型
- - '####'
  - 第一范式
- - '####'
  - 外键，关系数据库设计
- - '####'
  - 表单。参见 数据录入表单
- - '####'
  - 函数依赖
- - '#####'
  - 数据模型
- - '#####'
  - 定义
- - '#####'
  - 主键
- - '###'
  - G
- - '####'
  - 泛化，数据模型
- - '####'
  - 组，数据模型
- - '###'
  - H
- - '####'
  - 招待所问题
- - '###'
  - I
- - '####'
  - ID 号，主键
- - '####'
  - 索引
- - '#####'
  - 缺点
- - '#####'
  - 注册表
- - '#####'
  - 学生表
- - '#####'
  - 类型
- - '#####'
  - 用途
- - '####'
  - 继承
- - '#####'
  - 适用性
- - '####'
  - 超类
- - '####'
  - 志愿者图书馆
- - '####'
  - 招待所入住的初始模型
- - '####'
  - 多对多关系
- - '#####'
  - 中间类的消除
- - '#####'
  - 中间类的引入
- - '####'
  - 送餐问题
- - '####'
  - 体育俱乐部问题
- - '####'
  - 学生选课问题
- - '####'
  - 婚姻记录
- - '####'
  - 送餐问题
- - '####'
  - 对象和关系实例
- - '####'
  - 可选性
- - '#####'
  - 客户下单问题
- - '#####'
  - 昆虫样本采集问题
- - '#####'
  - 学生选课问题
- - '#####'
  - 管弦乐团音乐会信息
- - '#####'
  - 出版公司
- - '####'
  - 关系
- - '####'
  - 特化
- - '####'
  - 体育俱乐部问题
- - '####'
  - 创业孵化器问题，冗余
- - '####'
  - 大学课程、教学和指导
- - '####'
  - 数据冗余
- - '####'
  - 数据存储问题
- - '####'
  - 数据录入屏幕/报告
- - '####'
  - 数据冗余
- - '####'
  - 关键词和类别的错误处理
- - '####'
  - 特定数据报告
- - '####'
  - 数据类型
- - '####'
  - 删除问题
- - '####'
  - 设计实现
- - '#####'
  - 输入用例的接口
- - '#####'
  - 植物数据库表
- - '#####'
  - 输出用例的报告
- - '####'
  - 用例设计。参见 用例，设计
- - '####'
  - 文档类型定义 (DTD)
- - '####'
  - DTD。参见 文档类型定义 (DTD)
- - '####'
  - 数据重复。参见 数据冗余
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Y
- - '###'
  - Z
