name: Beginning SQL Server R Services
name_cn: SQL Server R 服务入门指南
slug: beginning-sql-server-r-services
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '###'
  - 我们将涵盖的内容
- - '###'
  - 为何选择 R？
- - '##'
  - 致谢
- - '##'
  - 目录
- - '###'
  - 第一部分：设置与安装
- - '####'
  - 第 1 章：SQL Server 2016 的设置与安装
- - '####'
  - 第 2 章：适用于 Visual Studio 的 R 工具的设置与安装
- - '####'
  - 第 3 章：项目场景定义
- - '###'
  - 第二部分：学习基础
- - '####'
  - 第 4 章：使用 RTVS 构建 R 模型
- - '####'
  - 第 5 章：在 RTVS 中绘图
- - '###'
  - 第三部分：创建与查看报告
- - '####'
  - 第 6 章：配置 SQL Server Reporting Services
- - '####'
  - 第 7 章：Report Builder 安装与数据准备
- - '####'
  - 第 8 章：使用 Report Builder 构建报告
- - '####'
  - 第 9 章：在报表服务器中查看报告
- - '###'
  - 第四部分：附录
- - '####'
  - 附录 A：在 SQL Server 2014 安装中安装 SQL Server 2016 实例
- - '####'
  - 附录 B：软件需求文档
- - '####'
  - 附录 C：适用于 Visual Studio 的 R 工具的 R 绘图与表格代码
- - '##'
  - 索引
- - '##'
  - 内容概览
- - '##'
  - 关于作者与关于技术审阅者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审阅者
- - '#'
  - 第一部分：安装与设置
- - '##'
  - 第 1 章：SQL Server 2016 的安装与设置
- - '###'
  - 规划
- - '###'
  - 开始安装
- - '####'
  - 产品密钥
- - '####'
  - 许可条款
- - '###'
  - 安装规则
- - '###'
  - 功能选择
- - '###'
  - 实例配置
- - '###'
  - 服务器配置
- - '###'
  - 数据库引擎配置
- - '####'
  - 服务器配置
- - '####'
  - 数据目录
- - '####'
  - TempDB
- - '####'
  - FILESTREAM
- - '###'
  - Reporting Services 配置
- - '###'
  - 同意安装 Microsoft R Open
- - '###'
  - 准备安装
- - '###'
  - 安装进度
- - '###'
  - 安装完成
- - '###'
  - 服务验证
- - '###'
  - SQL Server 管理工具
- - '###'
  - 小结
- - '##'
  - 第 2 章：Visual Studio R 工具的设置与安装
- - '###'
  - SQL Server Data Tools 与 Visual Studio
- - '###'
  - 下载 Visual Studio 的 R 工具
- - '###'
  - 下载 Microsoft R Open
- - '###'
  - Visual Studio 环境
- - '####'
  - 会话
- - '####'
  - 绘图
- - '####'
  - 数据
- - '####'
  - 工作目录
- - '###'
  - 安装 Microsoft R Client…
- - '###'
  - 将 R 更改为 Microsoft R Client
- - '###'
  - Microsoft R 产品…
- - '###'
  - RTVS 文档和示例
- - '###'
  - R 文档
- - '###'
  - 反馈
- - '###'
  - 检查更新
- - '###'
  - 调查/新闻
- - '###'
  - 编辑器选项
- - '####'
  - 选项
- - '#####'
  - 数据科学设置
- - '###'
  - 探索示例
- - '###'
  - R 入门
- - '##'
  - 第 3 章：项目场景定义
- - '###'
  - 范围蔓延
- - '###'
  - 项目定义阶段
- - '####'
  - 第一阶段：需求收集
- - '####'
  - 螺旋式开发过程
- - '####'
  - 软件变更请求过程
- - '#####'
  - 请求提交
- - '#####'
  - 管理员批准
- - '####'
  - 软件开发工作流程
- - '#####'
  - 设计
- - '#####'
  - 编码
- - '#####'
  - 文档
- - '#####'
  - 单元测试
- - '#####'
  - 回归测试
- - '#####'
  - 验收测试
- - '#####'
  - 安装
- - '#####'
  - 归档
- - '####'
  - 第二阶段：初始界面设计
- - '###'
  - 加载 R 解决方案
- - '###'
  - 总结
- - '#'
  - 第二部分：学习基础
- - '##'
  - 第 4 章：使用 RTVS 构建 R 模型
- - '###'
  - 探索示例
- - '###'
  - 在 Visual Studio 的 R 工具中执行代码与管理包
- - '###'
  - R 包管理器
- - '###'
  - R 中的绘图
- - '###'
  - R 中的线性回归
- - '###'
  - 回归诊断
- - '###'
  - 模型对象
- - '###'
  - 总结
- - '##'
  - 第 5 章：在 RTVS 中绘图
- - '###'
  - 报告 1：按机场 ID 计算平均风速
- - '####'
  - 导入数据集
- - '####'
  - 打开脚本窗格
- - '####'
  - 准备数据集
- - '####'
  - 按机场 ID 的平均风速（表格版）
- - '####'
  - 按机场 ID 的平均风速（图表版）
- - '###'
  - 报告 2：按机场 ID 的平均温度（°F）
- - '####'
  - 按机场 ID 计算平均温度（表格形式）
- - '####'
  - 按机场 ID 计算平均温度（绘图形式）
- - '###'
  - 本章小结
- - '#'
  - 第三部分：创建与查看报告
- - '##'
  - 第 6 章：配置 SQL Server Reporting Services
- - '###'
  - 连接到实例
- - '###'
  - 服务帐户
- - '###'
  - Web 服务 URL
- - '###'
  - 数据库
- - '###'
  - Web 门户 URL
- - '###'
  - 电子邮件设置
- - '###'
  - 执行账户
- - '###'
  - 加密密钥
- - '###'
  - 订阅设置
- - '###'
  - 横向扩展部署
- - '###'
  - Power BI 集成
- - '###'
  - 总结
- - '##'
  - 第 7 章：Report Builder 安装与数据准备
- - '###'
  - 下载 Report Builder
- - '###'
  - 设置新数据库和表
- - '###'
  - 导入天气数据
- - '###'
  - 生成二进制数据
- - '###'
  - 总结
- - '##'
  - 第 8 章：使用 Report Builder 构建报表
- - '###'
  - 报表 1：按机场 ID 的平均风速
- - '####'
  - 设置报表布局
- - '####'
  - 数据配置
- - '####'
  - 添加动态图像
- - '###'
  - 报表 2：按机场 ID 的平均温度
- - '##'
  - 第 9 章：在报表服务器中查看报表
- - '###'
  - 查看报表
- - '###'
  - 管理报表
- - '####'
  - 报表属性
- - '####'
  - 数据源
- - '####'
  - 订阅
- - '####'
  - 依赖项
- - '####'
  - 缓存
- - '####'
  - 历史快照
- - '####'
  - 安全性
- - '###'
  - 运行报表
- - '###'
  - 保存报表
- - '###'
  - 总结
- - '#'
  - 第四部分：附录
- - '##'
  - 附录 A：在 SQL Server 2014 安装中安装 SQL Server 2016 实例
- - '###'
  - 开始
- - '###'
  - 产品密钥
- - '###'
  - 许可条款
- - '###'
  - 安装规则
- - '###'
  - 功能选择
- - '###'
  - 实例配置
- - '###'
  - 服务器配置
- - '###'
  - 数据库引擎配置
- - '####'
  - 服务器配置
- - '###'
  - 数据目录
- - '###'
  - TempDB
- - '###'
  - FILESTREAM
- - '###'
  - Reporting Services 配置
- - '###'
  - 同意安装 Microsoft R Open
- - '###'
  - 准备安装
- - '###'
  - 完成
- - '###'
  - 总结
- - '##'
  - 附录 B：软件需求文档
- - '###'
  - 项目
- - '###'
  - 作者
- - '###'
  - 接受方
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 语言/平台
- - '###'
  - 交付媒介
- - '##'
  - 附录 C：适用于 Visual Studio 的 R 工具的 R 绘图与表格代码
- - '###'
  - 按机场 ID 的平均温度（绘图）
- - '###'
  - 按机场 ID 的平均温度（表格）
- - '###'
  - 按机场 ID 的平均风速（绘图）
- - '###'
  - 按机场 ID 的平均风速（表格）
- - '####'
  - 代码对象与数据框对应表
- - '##'
  - 索引
