name: Oracle SQL recipes
name_cn: Oracle SQL 秘籍
slug: oracle-sql-recipes
toc:
- - '#'
  - Oracle SQL 配方：问题-解决方案方法
- - '##'
  - 作者
- - '##'
  - Apress 路线图
- - '##'
  - 图书详情
- - '##'
  - 版权信息
- - '##'
  - 制作团队
- - '##'
  - 发行
- - '##'
  - 内容概览
- - '###'
  - 第一部分 数据操作基础
- - '####'
  - 第 1 章：基础
- - '####'
  - 第 2 章：数据汇总与聚合
- - '####'
  - 第 3 章：多表查询
- - '####'
  - 第 4 章：创建与派生数据
- - '####'
  - 第 5 章：常见查询模式
- - '###'
  - 第二部分 数据类型及其问题
- - '####'
  - 第 6 章：处理日期时间值
- - '####'
  - 第 7 章：字符串
- - '####'
  - 第 8 章：处理数字
- - '###'
  - 第三部分 您的开发环境
- - '####'
  - 第 9 章：管理事务
- - '####'
  - 第 10 章：数据字典
- - '###'
  - 第四部分 数据字典
- - '####'
  - 第 11 章：常见报表问题
- - '####'
  - 第 12 章：数据清洗
- - '####'
  - 第 13 章：树形结构数据
- - '####'
  - 第 14 章：处理 XML 数据
- - '####'
  - 第 15 章：分区
- - '####'
  - 第 16 章：大对象
- - '###'
  - 第五部分 管理
- - '####'
  - 第 17 章：数据库管理
- - '####'
  - 第 18 章：对象管理
- - '####'
  - 第 19 章：SQL 监控与调优
- - '####'
  - 第 20 章：数据库故障排除
- - '##'
  - 目录
- - '###'
  - 第一部分 数据操作基础
- - '####'
  - 第 1 章：基础
- - '#####'
  - 1-1. 从表中检索数据
- - '#####'
  - 1-2. 从表中选择所有列
- - '#####'
  - 1-3. 对结果进行排序
- - '#####'
  - 1-4. 向表中添加行
- - '#####'
  - 1-5. 将行从一个表复制到另一个表
- - '#####'
  - 1-6. 批量将数据从一个表复制到另一个表
- - '#####'
  - 1-7. 修改行中的值
- - '#####'
  - 1-8. 用单条语句更新多个字段
- - '#####'
  - 1-9. 从表中移除不需要的行
- - '#####'
  - 1-10. 从表中移除所有行
- - '#####'
  - 1-11. 从另一个查询的结果中选择
- - '#####'
  - 1-12. 基于查询设置 Where 条件
- - '#####'
  - 1-13. 查找和消除查询中的 NULL 值
- - '#####'
  - 1-14. 按照人的预期进行排序
- - '#####'
  - 1-15. 启用其他排序和比较选项
- - '#####'
  - 1-16. 基于存在性条件插入或更新
- - '####'
  - 第 2 章：汇总与聚合数据
- - '#####'
  - 2-1. 汇总列中的值
- - '#####'
  - 2-2. 为不同分组汇总数据
- - '#####'
  - 2-3. 按多个字段分组数据
- - '#####'
  - 2-4. 在聚合数据集中忽略分组
- - '#####'
  - 2-5. 在多个层级聚合数据
- - '#####'
  - 2-6. 在其他查询中使用聚合结果
- - '#####'
  - 2-7. 统计组和集合中的成员
- - '#####'
  - 2-8. 查找表中的重复值和唯一值
- - '#####'
  - 2-9. 计算总计和小计
- - '#####'
  - 2-10. 构建你自己的聚合函数
- - '#####'
  - 2-11. 访问后续或先前行中的值
- - '#####'
  - 2-12. 为查询结果中的行分配排名值
- - '#####'
  - 2-13. 在组内查找第一个和最后一个值
- - '#####'
  - 2-14. 在移动窗口上执行聚合
- - '#####'
  - 2-15. 基于列子集删除重复行
- - '#####'
  - 2-16. 查找表中的序列缺口
- - '####'
  - 第 3 章：从多表查询
- - '#####'
  - 3-1. 连接两个或多个表中的对应行
- - '#####'
  - 3-2. 垂直堆叠查询结果
- - '#####'
  - 3-3. 编写可选连接
- - '#####'
  - 3-4. 使连接在两个方向上都成为可选
- - '#####'
  - 3-5. 根据其他表中的数据删除行
- - '#####'
  - 3-6. 跨表查找匹配数据
- - '#####'
  - 3-7. 基于聚合值进行连接
- - '#####'
  - 3-8. 查找缺失行
- - '#####'
  - 3-9. 查找两个表共有的行中不存在的行
- - '#####'
  - 3-10. 生成测试数据
- - '#####'
  - 3-11. 基于其他表中的数据更新行
- - '#####'
  - 3-12. 在连接条件中操作和比较 NULL
- - '####'
  - 第 4 章：创建与派生数据
- - '#####'
  - 4-1. 派生新列
- - '#####'
  - 4-2. 返回不存在的行
- - '#####'
  - 4-3. 将行转换为列
- - '#####'
  - 4-4. 在多个列上进行透视
- - '#####'
  - 4-5. 将列转换为行
- - '#####'
  - 4-6. 为提高可读性拼接数据
- - '#####'
  - 4-7. 将字符串转换为数字等价物
- - '#####'
  - 4-8. 生成随机数据
- - '#####'
  - 4-9. 创建逗号分隔值文件
- - '####'
  - 第 5 章：常见查询模式
- - '#####'
  - 5-1. 将空值转换为实际值
- - '#####'
  - 5-2. 对空值进行排序
- - '#####'
  - 5-3. 对查询结果进行分页
- - '#####'
  - 5-4. 测试数据的存在性
- - '#####'
  - 5-5. 在一条 SQL 语句中进行条件分支
- - '#####'
  - 5-6. 条件排序与按函数排序
- - '#####'
  - 5-7. 解决子查询返回意外多个值时的问题和错误
- - '#####'
  - 5-8. 在不同进制之间转换数字
- - '#####'
  - 5-9. 在不知道列或表的情况下搜索字符串
- - '#####'
  - 5-10. 预测序列结束后的数据值和趋势
- - '#####'
  - 5-11. 显式（悲观地）锁定待更新的行
- - '#####'
  - 5-12. 同步两个表的内容
- - '###'
  - 第二部分 数据类型及其问题
- - '####'
  - 第 6 章：处理日期和时间值
- - '#####'
  - 6-1. 将日期时间值转换为可读字符串
- - '#####'
  - 6-2. 将字符串转换为日期时间值
- - '#####'
  - 6-3. 检测重叠的日期范围
- - '#####'
  - 6-4. 自动跟踪数据变更的日期和时间
- - '#####'
  - 6-5. 从有间隔的数据生成无间隔的时间序列
- - '#####'
  - 6-6. 在时区之间转换日期和时间
- - '#####'
  - 6-7. 检测闰年
- - '#####'
  - 6-8. 计算月份的最后日期
- - '#####'
  - 6-9. 确定月份的第一天或第一个工作日
- - '#####'
  - 6-10. 计算星期几
- - '#####'
  - 6-11. 按时间段分组和聚合
- - '#####'
  - 6-12. 求两个日期或日期部分之间的差值
- - '#####'
  - 6-13. 确定任何年份的复活节日期
- - '#####'
  - 6-14. 计算网站的“X 日活跃用户”
- - '####'
  - 第 7 章：字符串
- - '#####'
  - 7-1. 搜索子字符串
- - '#####'
  - 7-2. 提取子字符串
- - '#####'
  - 7-3. 单字符字符串替换
- - '#####'
  - 7-4. 搜索模式
- - '#####'
  - 7-5. 提取模式
- - '#####'
  - 7-6. 计数模式
- - '#####'
  - 7-7. 替换字符串中的文本
- - '#####'
  - 7-8. 加快字符串搜索
- - '####'
  - 第 8 章：处理数字
- - '#####'
  - 8-1. 在字符串与数值数据类型之间转换
- - '#####'
  - 8-2. 在数值数据类型之间转换
- - '#####'
  - 8-3. 选择数据类型的精度和范围
- - '#####'
  - 8-4. 使用非数字和无限数字正确执行计算
- - '#####'
  - 8-5. 验证字符串中的数字
- - '#####'
  - 8-6. 生成连续数字
- - '#####'
  - 8-7. 按公式或模式生成数字
- - '#####'
  - 8-8. 处理数值计算中的空值
- - '#####'
  - 8-9. 自动对数字进行四舍五入
- - '#####'
  - 8-10. 自动生成数字列表
- - '###'
  - 第三部分 您的开发环境
- - '####'
  - 第 9 章：管理事务
- - '#####'
  - 9-1. 部分回滚事务
- - '#####'
  - 9-2. 识别阻塞事务
- - '#####'
  - 9-3. 优化行锁和表锁
- - '#####'
  - 9-4. 避免死锁场景
- - '#####'
  - 9-5. 延迟约束验证
- - '#####'
  - 9-6. 确保跨事务的读一致性
- - '#####'
  - 9-7. 管理事务隔离级别
- - '####'
  - 第 10 章：数据字典
- - '#####'
  - 10-1. 图形化工具与 SQL
- - '#####'
  - 10-2. 数据字典架构
- - '#####'
  - 10-3. 显示用户信息
- - '#####'
  - 10-4. 确定你可以访问的表
- - '#####'
  - 10-5. 显示表的磁盘空间使用情况
- - '#####'
  - 10-6. 显示表行数
- - '#####'
  - 10-7. 显示表的索引
- - '#####'
  - 10-8. 显示未建立索引的外键列
- - '#####'
  - 10-9. 显示约束
- - '#####'
  - 10-10. 显示主键和外键关系
- - '#####'
  - 10-11. 显示对象依赖关系
- - '#####'
  - 10-12. 显示同义词元数据
- - '#####'
  - 10-13. 显示视图文本
- - '#####'
  - 10-14. 显示数据库代码
- - '#####'
  - 10-15. 显示已授予的角色
- - '#####'
  - 10-16. 显示对象权限
- - '#####'
  - 10-17. 显示系统权限
- - '###'
  - 第四部分 专题
- - '####'
  - 第 11 章：常见的报表问题
- - '#####'
  - 11-1. 避免在报表中重复行
- - '#####'
  - 11-2. 参数化 SQL 报告
- - '#####'
  - 11-3. 在分组结果中返回详细列
- - '#####'
  - 11-4. 将结果排序到等大小的分组中
- - '#####'
  - 11-5. 创建报告直方图
- - '#####'
  - 11-6. 按相对排名过滤结果
- - '#####'
  - 11-7. 在数据集上比较假设
- - '#####'
  - 11-8. 用文本图形化表示数据分布
- - '#####'
  - 11-9. 直接从数据库生成网页报告
- - '####'
  - 第 12 章：数据清洗
- - '#####'
  - 12-1. 检测重复行
- - '#####'
  - 12-2. 删除重复行
- - '#####'
  - 12-3. 判断数据是否可加载为数值型
- - '#####'
  - 12-4. 判断数据是否可加载为日期型
- - '#####'
  - 12-5. 执行不区分大小写的查询
- - '#####'
  - 12-6. 混淆值
- - '#####'
  - 12-7. 删除所有索引
- - '#####'
  - 12-8. 禁用约束
- - '#####'
  - 12-9. 禁用触发器
- - '#####'
  - 12-10. 从表中删除数据
- - '#####'
  - 12-11. 显示模式差异
- - '####'
  - 第 13 章：树形结构数据
- - '#####'
  - 13-1. 从上到下遍历层次数据
- - '#####'
  - 13-2. 在层次级别内对节点排序
- - '#####'
  - 13-3. 从层次表生成路径名
- - '#####'
  - 13-4. 识别层次表中的叶数据
- - '#####'
  - 13-5. 检测层次数据中的循环
- - '#####'
  - 13-6. 生成固定数量的顺序主键
- - '####'
  - 第 14 章：处理 XML 数据
- - '#####'
  - 14-1. 将 SQL 转换为 XML
- - '#####'
  - 14-2. 以原生形式存储 XML
- - '#####'
  - 14-3. 将 XML 拆解为关系型使用
- - '#####'
  - 14-4. 从 XML 文档中提取关键 XML 元素
- - '#####'
  - 14-5. 生成复杂的 XML 文档
- - '#####'
  - 14-6. 验证 XML 模式
- - '#####'
  - 14-7. 就地更改 XML
- - '####'
  - 第 15 章：分区
- - '#####'
  - 15-1. 确定表是否应被分区
- - '#####'
  - 15-2. 按范围分区
- - '#####'
  - 15-3. 按列表分区
- - '#####'
  - 15-4. 按哈希分区
- - '#####'
  - 15-5. 以多种方式对表进行分区
- - '#####'
  - 15-6. 按需创建分区
- - '#####'
  - 15-7. 按引用约束分区
- - '#####'
  - 15-8. 在虚拟列上分区
- - '#####'
  - 15-9. 应用程序控制的分区
- - '#####'
  - 15-10. 使用表空间配置分区
- - '#####'
  - 15-11. 自动移动更新的行
- - '#####'
  - 15-12. 对现有表进行分区
- - '#####'
  - 15-13. 向分区表添加分区
- - '#####'
  - 15-14. 将分区与现有表交换
- - '#####'
  - 15-15. 重命名分区
- - '#####'
  - 15-16. 拆分分区
- - '#####'
  - 15-17. 合并分区
- - '#####'
  - 15-18. 删除分区
- - '#####'
  - 15-19. 从分区中移除行
- - '#####'
  - 15-20. 为分区生成统计信息
- - '#####'
  - 15-21. 创建映射到分区的索引（本地索引）
- - '#####'
  - 15-22. 创建具有自身分区方案的索引（全局索引）
- - '####'
  - 第 16 章：大对象（LOB）
- - '#####'
  - 16-1. 将大型文档加载到 CLOB 列
- - '#####'
  - 16-2. 将图像数据加载到 BLOB 列
- - '#####'
  - 16-3. 使用 SQL*Loader 批量加载大对象
- - '#####'
  - 16-4. 使用 HTTP 访问大对象
- - '#####'
  - 16-5. 使外部大对象（BFILEs）对数据库可用
- - '#####'
  - 16-6. 删除或更新数据库表中的 LOB
- - '###'
  - 第五部分 管理
- - '####'
  - 第 17 章：数据库管理
- - '#####'
  - 17-1. 创建数据库
- - '#####'
  - 17-2. 删除数据库
- - '#####'
  - 17-3. 验证连接信息
- - '#####'
  - 17-4. 创建表空间
- - '#####'
  - 17-5. 删除表空间
- - '#####'
  - 17-6. 调整表空间大小
- - '#####'
  - 17-7. 限制每个会话的数据库资源
- - '#####'
  - 17-8. 关联一组权限
- - '#####'
  - 17-9. 创建用户
- - '#####'
  - 17-10. 删除用户
- - '#####'
  - 17-11. 修改密码
- - '#####'
  - 17-12. 强制密码复杂性
- - '####'
  - 第 18 章：对象管理
- - '#####'
  - 18-1. 创建表
- - '#####'
  - 18-2. 临时存储数据
- - '#####'
  - 18-3. 移动表
- - '#####'
  - 18-4. 重命名对象
- - '#####'
  - 18-5. 删除表
- - '#####'
  - 18-6. 撤消删除表
- - '#####'
  - 18-7. 创建索引
- - '#####'
  - 18-8. 创建基于函数的索引
- - '#####'
  - 18-9. 创建位图索引
- - '#####'
  - 18-10. 创建索引组织表
- - '#####'
  - 18-11. 创建视图
- - '#####'
  - 18-12. 为对象创建别名
- - '#####'
  - 18-13. 在表中强制唯一行
- - '#####'
  - 18-14. 确保查找值存在
- - '#####'
  - 18-15. 按条件检查数据
- - '#####'
  - 18-16. 创建数据库之间的连接
- - '#####'
  - 18-17. 创建自增值
- - '####'
  - 第 19 章：SQL 监控与调优
- - '#####'
  - 19-1. 监控实时 SQL 执行统计信息
- - '#####'
  - 19-2. 在执行计划中显示查询进度
- - '#####'
  - 19-3. 确定剩余的 SQL 工作量
- - '#####'
  - 19-4. 识别资源密集型 SQL 语句
- - '#####'
  - 19-5. 使用 Oracle 性能报告识别资源密集型 SQL
- - '#####'
  - 19-6. 使用操作系统识别资源密集型查询
- - '#####'
  - 19-7. 使用 AUTOTRACE 显示执行计划
- - '#####'
  - 19-8. 使用 DBMS_XPLAN 生成执行计划
- - '#####'
  - 19-9. 追踪会话的所有 SQL 语句
- - '#####'
  - 19-10. 解释执行计划
- - '#####'
  - 19-11. 获取 SQL 调优建议
- - '#####'
  - 19-12. 对查询强制使用自己的执行计划
- - '#####'
  - 19-13. 查看优化器统计信息
- - '#####'
  - 19-14. 生成统计信息
- - '####'
  - 第 20 章：数据库故障排除
- - '#####'
  - 20-1. 确定数据库问题的原因
- - '#####'
  - 20-2. 显示打开的游标
- - '#####'
  - 20-3. 判断联机重做日志大小是否合适
- - '#####'
  - 20-4. 确定撤销表空间大小是否合适
- - '#####'
  - 20-5. 确定临时表空间大小是否正确
- - '#####'
  - 20-6. 显示表空间使用率
- - '#####'
  - 20-7. 显示对象大小
- - '#####'
  - 20-8. 监控索引使用情况
- - '#####'
  - 20-9. 审计对象使用情况
- - '#####'
  - 20-10. 细粒度审计
- - '##'
  - 索引
