name: Introducing RavenDB
name_cn: RavenDB 入门指南
slug: introducing-ravendb
toc:
- - '#'
  - 修复后的目录
- - '##'
  - '*献给 Filip、Olivera 和 Renata。*'
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 关于作者 关于技术审阅者
- - '#'
  - 1. RavenDB 入门
- - '##'
  - 数据库简史
- - '###'
  - 关系型数据库管理系统的问题
- - '###'
  - 阻抗失配
- - '###'
  - 对象关系映射器
- - '###'
  - 规范化
- - '###'
  - 现代 Web 应用程序
- - '##'
  - NoSQL
- - '###'
  - “NoSQL”名称的由来
- - '###'
  - 为何需要 NoSQL？
- - '###'
  - 特征
- - '###'
  - 额外优势
- - '###'
  - 挑战
- - '###'
  - 结论
- - '###'
  - NoSQL 数据库类型
- - '####'
  - 键值存储
- - '####'
  - 文档存储
- - '####'
  - 图数据库
- - '####'
  - 宽列存储
- - '###'
  - 多模型数据库
- - '##'
  - RavenDB
- - '###'
  - 历史
- - '###'
  - RavenDB 的优势
- - '####'
  - 极致性能
- - '####'
  - 完全事务性
- - '####'
  - 自动调优
- - '####'
  - 默认安全
- - '####'
  - 高可用性
- - '####'
  - 拓扑结构
- - '##'
  - 如何开始？
- - '###'
  - 创建你的第一个数据库
- - '###'
  - 填充示例数据
- - '###'
  - Northwind 数据库
- - '##'
  - 文档
- - '##'
  - 本章小结
- - '#'
  - 2. 文档建模
- - '##'
  - 抽象与泛化
- - '##'
  - 关系数据库中的建模
- - '##'
  - 数据封装挑战
- - '##'
  - NoSQL 数据库中的建模
- - '###'
  - JSON 文档
- - '###'
  - 建模良好文档的特性
- - '###'
  - 聚合
- - '##'
  - 变更单元与一致性单元
- - '##'
  - 分布式系统
- - '##'
  - 分布式系统中的聚合
- - '##'
  - 聚合作为事务边界
- - '##'
  - RavenDB 中的建模
- - '###'
  - 文档
- - '###'
  - 标识符
- - '###'
  - 文档关系建模
- - '####'
  - 一对一关系
- - '#####'
  - 嵌入
- - '#####'
  - 引用
- - '##'
  - RavenDB 中的引用完整性
- - '##'
  - 与关系数据库的比较
- - '##'
  - 领域驱动建模
- - '##'
  - 数据库的角色
- - '###'
  - 一对多关系
- - '###'
  - 多对多关系
- - '##'
  - 总结
- - '#'
  - 3. 查询
- - '##'
  - 在 RavenDB Studio 中查询
- - '##'
  - Raven 查询语言基础
- - '###'
  - 过滤
- - '##'
  - 按不存在的属性查询
- - '##'
  - 按非字符串属性查询
- - '##'
  - 按复杂属性筛选
- - '##'
  - 按 Id 筛选
- - '##'
  - 跨集合查询
- - '##'
  - 不等式查询
- - '###'
  - 逻辑运算符
- - '###'
  - 范围查询
- - '###'
  - 大小写
- - '###'
  - 全文搜索
- - '###'
  - 排序
- - '###'
  - 分页
- - '##'
  - 高级查询
- - '##'
  - 投影结果
- - '###'
  - 使用对象字面量进行投影
- - '###'
  - 在查询中声明函数
- - '###'
  - 聚合
- - '###'
  - 处理关系
- - '####'
  - 访问相关文档
- - '##'
  - Include（包含）
- - '##'
  - Summary（总结）
- - '#'
  - 4. Indexes（索引）
- - '##'
  - Queries from the Perspective of a Database（从数据库角度看查询）
- - '###'
  - Unbounded Queries（无界查询）
- - '###'
  - Paging（分页）
- - '###'
  - Filtering（过滤）
- - '##'
  - 索引
- - '###'
  - 索引类型
- - '##'
  - 索引的缺点
- - '##'
  - RavenDB 的索引哲学
- - '##'
  - 图 4-8：基于索引项进行查询
- - '###'
  - 图 4-9：在索引上执行查询的结果
- - '###'
  - 图 4-10：原始索引项
- - '###'
  - 图 4-11：查询执行时间
- - '##'
  - 总结
- - '#'
  - 5. 映射索引
- - '##'
  - 静态索引
- - '###'
  - 静态映射索引
- - '###'
  - 静态索引分析
- - '###'
  - 扩展映射索引
- - '##'
  - 存储字段
- - '##'
  - 计算字段
- - '##'
  - 动态字段
- - '##'
  - 扇出索引
- - '##'
  - 多地图索引
- - '##'
  - 索引层次结构数据
- - '##'
  - 总结
- - '#'
  - 6. MapReduce 索引
- - '##'
  - 分组
- - '##'
  - MapReduce
- - '##'
  - 聚合
- - '##'
  - 静态 MapReduce 索引
- - '##'
  - 静态索引与自动索引
- - '###'
  - 初始索引时刻
- - '###'
  - 聚合的复杂性
- - '###'
  - 多地图归约索引
- - '##'
  - 人工文档
- - '###'
  - 创建人工文档
- - '###'
  - 索引人工文档
- - '##'
  - 概要
- - '#'
  - 7. 全文搜索
- - '##'
  - 全文搜索基础
- - '###'
  - 单一术语
- - '###'
  - 多个术语
- - '###'
  - 对复杂对象进行搜索
- - '###'
  - 通配符
- - '###'
  - 建议
- - '###'
  - 操作符
- - '##'
  - 内部发生了什么？
- - '###'
  - 文本分析
- - '###'
  - 标准分析器
- - '##'
  - 排名
- - '##'
  - 权重提升
- - '##'
  - 静态索引：单字段
- - '##'
  - 静态索引：不同的分析器
- - '##'
  - 静态索引：多字段
- - '##'
  - 索引来自多个集合的属性
- - '##'
  - 索引来自单个集合的多个字段
- - '###'
  - 从多个集合索引多个字段
- - '##'
  - 总结
