name: SQL Server 2017 Query Performance Tuning
name_cn: SQL Server 2017 查询性能调优
slug: sql-server-2017-query-performance-tuning
toc:
- - '###'
  - 关于作者和关于技术评审者
- - '####'
  - 关于作者
- - '####'
  - 关于技术评审者
- - '##'
  - 强化预防性方法
- - '##'
  - 索引不足或不准确
- - '###'
  - 注意
- - '##'
  - 不当的查询设计
- - '##'
  - 生成的执行计划不佳
- - '##'
  - 过度的阻塞和死锁
- - '##'
  - 非基于集合的操作
- - '##'
  - 不恰当的数据库设计
- - '##'
  - 总结
- - '##'
  - 性能监视器工具
- - '##'
  - 硬件资源瓶颈
- - '##'
  - 瓶颈识别
- - '##'
  - 瓶颈解决
- - '##'
  - 内存瓶颈分析
- - '##'
  - SQL Server 内存管理
- - '##'
  - 页面预期寿命
- - '##'
  - 检查点页数/秒
- - '##'
  - 惰性写入次数/秒
- - '##'
  - 内存授予挂起数
- - '##'
  - 目标服务器内存（KB）和服务器总内存（KB）
- - '##'
  - 其他内存监控工具
- - '##'
  - DBCC MEMORYSTATUS
- - '###'
  - 动态管理视图
- - '####'
  - Sys.dm_os_memory_brokers
- - '####'
  - Sys.dm_os_memory_clerks
- - '####'
  - Sys.dm_os_ring_buffers
- - '####'
  - Sys.dm_db_xtp_table_memory_stats
- - '####'
  - Sys.dm_xtp_system_memory_consumers
- - '###'
  - 在 Linux 中监控内存
- - '##'
  - 内存瓶颈解决方案
- - '##'
  - 总结
- - '###'
  - 3. 磁盘性能分析
- - '##'
  - 磁盘瓶颈分析
- - '##'
  - 附加 I/O 监控工具
- - '##'
  - 磁盘瓶颈解决方案
- - '##'
  - 总结
- - '##'
  - 处理器瓶颈分析
- - '##'
  - '% 特权时间'
- - '##'
  - 处理器队列长度
- - '##'
  - 上下文切换/秒
- - '##'
  - 批处理请求/秒
- - '##'
  - SQL 编译/秒
- - '##'
  - SQL 重编译/秒
- - '##'
  - 其他测量 CPU 性能的工具
- - '##'
  - 处理器瓶颈解决方案
- - '##'
  - 网络瓶颈分析
- - '##'
  - 网络瓶颈解决方案
- - '##'
  - 不可重用的执行计划
- - '##'
  - 一般行为
- - '##'
  - 用户连接数
- - '##'
  - 批处理请求/秒
- - '##'
  - 总结
- - '##'
  - 监控虚拟机和托管机器的注意事项
- - '##'
  - 创建基线
- - '##'
  - 使用性能计数器列表创建计数器日志
- - '##'
  - 注意
- - '##'
  - 性能监视器使用注意事项
- - '##'
  - 基于基准线的系统行为分析
- - '##'
  - Azure SQL Database 的基准线
- - '##'
  - 总结
- - '##'
  - 扩展事件
- - '##'
  - 查询性能相关事件
- - '##'
  - 扩展事件自动化
- - '##'
  - 使用因果跟踪
- - '##'
  - 扩展事件建议
- - '##'
  - 其他查询性能指标收集方法
- - '##'
  - 总结
- - '##'
  - 高成本查询
- - '##'
  - 执行计划
- - '##'
  - 识别执行计划中的高开销步骤
- - '##'
  - 分析索引有效性
- - '##'
  - 查询资源成本
- - '##'
  - STATISTICS IO
- - '##'
  - 实际执行计划
- - '##'
  - 本章小结
- - '###'
  - 第 8 章：索引架构与行为
- - '##'
  - 什么是索引？
- - '##'
  - 索引设计建议
- - '##'
  - 聚集索引
- - '##'
  - 堆表
- - '##'
  - 与非聚集索引的关系
- - '##'
  - 聚集索引建议
- - '##'
  - 非聚集索引
- - '##'
  - 非聚集索引维护
- - '##'
  - 定义查找操作
- - '##'
  - 非聚集索引建议
- - '##'
  - 聚集索引与非聚集索引
- - '##'
  - 总结
- - '##'
  - 高级索引技术
- - '##'
  - 索引连接
- - '##'
  - 注意
- - '##'
  - 列存储索引
- - '##'
  - 特殊索引类型
- - '##'
  - 索引的其他特性
- - '##'
  - 小结
- - '##'
  - 数据库引擎优化顾问机制
- - '##'
  - 数据库引擎调优顾问示例
- - '##'
  - 调优查询
- - '##'
  - 从过程缓存调优
- - '##'
  - 从查询存储调优
- - '##'
  - 数据库引擎调优顾问的局限性
- - '##'
  - 总结
- - '##'
  - 查询存储的功能与设计
- - '##'
  - 查询存储报告
- - '##'
  - 计划强制
- - '##'
  - 用于升级的查询存储
- - '##'
  - 键查找与解决方案
- - '##'
  - 摘要
- - '##'
  - 12.1 查找的目的
- - '##'
  - 查找操作的缺点
- - '##'
  - 分析查找操作的原因
- - '##'
  - 解决查找操作
- - '##'
  - 统计信息、数据分布与基数
- - '##'
  - 统计信息在查询优化中的作用
- - '##'
  - 分析统计信息
- - '##'
  - 统计信息维护
- - '##'
  - 分析统计信息对查询的有效性
- - '##'
  - 解决统计信息缺失问题
- - '##'
  - 解决过时的统计信息问题
- - '##'
  - 建议
- - '##'
  - 总结
- - '##'
  - 关于碎片化的讨论
- - '##'
  - 碎片化的原因
- - '##'
  - 分析碎片量
- - '##'
  - 分析小表的碎片
- - '##'
  - 碎片解决方案
- - '##'
  - SQL Server 索引维护技术详解
- - '##'
  - 执行计划生成
- - '##'
  - 执行计划缓存行为
- - '##'
  - 总结
- - '##'
  - 分析执行计划缓存
- - '##'
  - 执行计划重用
- - '##'
  - 即席工作负载
- - '##'
  - 预准备的工作负载
- - '##'
  - 即席工作负载的计划可重用性
- - '##'
  - 针对即席工作负载进行优化
- - '##'
  - 预定义工作负载的计划可重用性
- - '##'
  - 存储过程
- - '##'
  - '`sp_executesql`'
- - '##'
  - Prepare/Execute Model
- - '##'
  - 查询计划哈希与查询哈希
- - '##'
  - 执行计划缓存建议
- - '##'
  - 参数嗅探
- - '##'
  - 摘要
- - '##'
  - 查询重编译
- - '##'
  - 重编译的益处和弊端
- - '##'
  - 识别导致重编译的语句
- - '##'
  - 分析重编译的原因
- - '##'
  - 使用 RECOMPILE 提示来控制单个语句
- - '##'
  - 避免重编译
- - '###'
  - 第 18 章 查询重新编译
- - '##'
  - 查询设计分析
- - '##'
  - 查询设计建议
- - '##'
  - 操作小型结果集
- - '##'
  - 有效使用索引
- - '##'
  - 注意事项
- - '##'
  - 最小化优化器提示
- - '##'
  - 使用域完整性和引用完整性
- - '##'
  - 总结
- - '##'
  - 减少查询资源使用
- - '##'
  - 避免资源密集型查询
- - '##'
  - 减少网络往返次数
- - '##'
  - 降低事务成本
- - '##'
  - 总结
- - '##'
  - 阻塞与被阻塞进程
- - '##'
  - 阻塞基础
- - '##'
  - 理解阻塞
- - '##'
  - 锁
- - '##'
  - 隔离级别
- - '##'
  - 索引对锁定的影响
- - '##'
  - 捕获阻塞信息
- - '##'
  - 阻塞解决方案
- - '##'
  - 减少阻塞的建议
- - '##'
  - 自动化检测与收集阻塞信息
- - '##'
  - 摘要
- - '##'
  - 死锁的原因与解决方案
- - '##'
  - 死锁基础
- - '##'
  - 死锁分析
- - '##'
  - 避免死锁
- - '##'
  - 总结
- - '##'
  - 逐行处理
- - '##'
  - 游标基础
- - '##'
  - 游标成本比较
- - '##'
  - 缺点
- - '##'
  - 游标开销
- - '##'
  - 总结
- - '##'
  - 内存优化 OLTP 表与存储过程
- - '##'
  - 内存 OLTP 基础
- - '##'
  - 系统要求
- - '##'
  - 基本设置
- - '##'
  - 创建表
- - '##'
  - 内存索引
- - '##'
  - 统计信息维护
- - '##'
  - 本地编译存储过程
- - '##'
  - 建议
- - '##'
  - 概要
- - '##'
  - Azure SQL Database 和 SQL Server 中的自动调优
- - '##'
  - 自动计划修正
- - '##'
  - 调优建议
- - '##'
  - 了解 SQL Server 调优建议
- - '##'
  - 查看调优建议
- - '##'
  - 调优建议详情
- - '##'
  - 启用自动调优
- - '##'
  - Azure SQL Database 自动索引管理
- - '##'
  - 自适应查询处理
- - '##'
  - 交错执行
- - '##'
  - 执行计划比较与交错执行优化
- - '##'
  - 总结
- - '##'
  - 数据库性能测试
- - '##'
  - 数据库性能测试
- - '##'
  - 分布式重放
- - '##'
  - 使用服务器端跟踪捕获数据
- - '##'
  - 开始跟踪与保存定义
- - '##'
  - 用于数据库测试的分布式重放
- - '##'
  - 结论
- - '##'
  - 数据库工作负载优化
- - '##'
  - 工作负载优化基础
- - '##'
  - 工作负载优化步骤
- - '##'
  - 示例工作负载
- - '##'
  - 注意
- - '##'
  - 捕获负载
- - '##'
  - 分析负载
- - '##'
  - SQL 查询性能分析与优化
- - '##'
  - 识别代价最高的查询
- - '##'
  - 详细的资源使用分析
- - '##'
  - 分析和优化外部因素
- - '##'
  - 分析代价最高查询的内部行为
- - '##'
  - 分析处理策略
- - '##'
  - 优化成本最高的查询
- - '##'
  - 分析对数据库工作负载的影响
- - '##'
  - 在优化阶段中迭代
- - '##'
  - 总结
- - '##'
  - 数据库设计
- - '##'
  - SQL Server 数据完整性约束的性能优势
- - '##'
  - 维护域和引用完整性约束
- - '##'
  - 配置设置
- - '##'
  - 数据库管理
- - '##'
  - 查询设计
- - '##'
  - 总结
- - '##'
  - 索引
