name: Oracle SQL Revealed
name_cn: Oracle SQL 揭秘
slug: oracle-sql-revealed
toc:
- - '#'
  - 亚历克斯·列普里采夫 《Oracle SQL 揭秘：在数据库引擎中执行业务逻辑》
- - '##'
  - 作者：亚历克斯·列普里采夫
- - '##'
  - 引言
- - '##'
  - 目录
- - '###'
  - 第一部分：特性与原理
- - '####'
  - 第 1 章：连接
- - '#####'
  - ANSI 连接
- - '#####'
  - 其他类型的连接
- - '######'
  - 引言
- - '#####'
  - Oracle 特定语法
- - '######'
  - 1) 预连接与后连接谓词示例
- - '#####'
  - ANSI 与 Oracle 原生语法
- - '#####'
  - Oracle 原生语法的限制
- - '#####'
  - 展开集合与关联查询
- - '######'
  - 展开集合
- - '######'
  - 关联内联视图与子查询
- - '#####'
  - ANSI 转原生语法转换
- - '#####'
  - 关于谓词形式的重要说明
- - '#####'
  - 演示 `PARTITION BY`
- - '#####'
  - SEMI 与 ANTI 连接
- - '#####'
  - SQL 查询优化
- - '######'
  - 引言
- - '######'
  - 清晰度与可读性
- - '######'
  - 混合语法
- - '######'
  - 控制执行计划
- - '######'
  - ANSI 的限制
- - '#####'
  - 总结
- - '####'
  - 第 2 章：查询转换
- - '#####'
  - Oracle 查询转换：CBO、RBO 与启发式转换
- - '#####'
  - 总结
- - '####'
  - 第 3 章：分析函数
- - '#####'
  - 分析函数与连接查询
- - '######'
  - 执行计划对比
- - '######'
  - 性能考虑
- - '######'
  - 函数的差异与互换性
- - '#####'
  - 总结
- - '####'
  - 第 4 章：聚合函数
- - '#####'
  - 透视和逆透视操作符
- - '#####'
  - CUBE, ROLLUP, 分组集
- - '####'
  - 第 5 章：层次查询：CONNECT BY
- - '#####'
  - 概要
- - '#####'
  - CONNECT BY 子句
- - '#####'
  - 代码清单 5-2
- - '#####'
  - 兄弟节点排序
- - '#####'
  - 代码清单 5-3
- - '#####'
  - CONNECT BY 与连接
- - '#####'
  - 有向图
- - '#####'
  - 代码清单 5-4
- - '#####'
  - 使用 CONNECT BY 生成序列
- - '#####'
  - 递归序列生成与循环处理
- - '#####'
  - 伪列生成详解
- - '#####'
  - 总结
- - '####'
  - 第 6 章：递归子查询因子化
- - '#####'
  - 递归子查询因子化
- - '#####'
  - 生成递归序列
- - '#####'
  - 使用前几次迭代的值
- - '#####'
  - 遍历层级结构
- - '#####'
  - 再谈循环
- - '#####'
  - 限制条件
- - '#####'
  - 总结
- - '####'
  - 第 7 章：MODEL 子句
- - '#####'
  - 注意
- - '#####'
  - 在规则左侧指定顺序
- - '#####'
  - 递归度量
- - '#####'
  - 使用自动规则排序的模型
- - '#####'
  - 具有循环规则和自动顺序的模型
- - '#####'
  - 检查收敛性
- - '#####'
  - MODEL 子句中分析函数与聚合函数的局限性
- - '#####'
  - 清单 7-14
- - '#####'
  - 清单 7-15
- - '#####'
  - 使用 MODEL 子句生成递归序列
- - '#####'
  - MODEL 子句的使用场景
- - '#####'
  - 性能简要分析
- - '#####'
  - SQL MODEL 子句性能分析
- - '#####'
  - MODEL 并行执行
- - '#####'
  - 总结
- - '####'
  - 第 8 章：行模式匹配：MATCH_RECOGNIZE
- - '#####'
  - Oracle 模式匹配与分析函数
- - '#####'
  - 清单 8-4：使用模式匹配查找元素 (1, 2, 3) 的组合
- - '#####'
  - 清单 8-5：使用分析函数查找元素 (1, 2, 3) 的组合
- - '#####'
  - 清单 8-6：查找元素 (1, 2, 3) 组合的查询计划
- - '#####'
  - 清单 8-7：带回溯的模式匹配
- - '#####'
  - 总结
- - '####'
  - 第 9 章：查询子句的逻辑执行顺序
- - '#####'
  - 1. 你不能依赖复合条件中谓词的求值顺序
- - '#####'
  - 2. 不保证标量子查询或确定性函数的执行次数
- - '#####'
  - 总结
- - '####'
  - 第 10 章：图灵完备性
- - '#####'
  - 图灵完备性概述
- - '#####'
  - 规则 110 元胞自动机
- - '#####'
  - 使用 SQL 实现 规则 110
- - '#####'
  - 关于算法实现与图灵完备性的讨论
- - '#####'
  - 总结
- - '###'
  - 第二部分：PL/SQL 与 SQL 解决方案
- - '####'
  - 第 11 章：何时 PL/SQL 优于原生 SQL
- - '#####'
  - 分析函数的特殊性
- - '#####'
  - 获取终止
- - '#####'
  - 清单 11-7
- - '#####'
  - 清单 11-8
- - '#####'
  - 清单 11-9
- - '#####'
  - 避免多次排序
- - '#####'
  - 迭代式计算
- - '#####'
  - 当没有有效的内置访问方法时
- - '#####'
  - 组合性质的问题
- - '#####'
  - 联接与子查询的特性
- - '#####'
  - 联接的特性
- - '#####'
  - 初始方法与分析
- - '#####'
  - 使用交叉连接优化为哈希连接
- - '#####'
  - 使用 PL/SQL 函数与关联数组
- - '#####'
  - 子查询的限制
- - '#####'
  - 总结
- - '####'
  - 第 12 章：解决 SQL 趣题
- - '#####'
  - 转换为十进制数字系统
- - '######'
  - 解决方案
- - '#####'
  - 连通分量
- - '######'
  - 解决方案
- - '#####'
  - 排序依赖关系
- - '######'
  - 解决方案
- - '#####'
  - 带偏移的百分位数
- - '######'
  - 解决方案
- - '#####'
  - N 个连续的 1
- - '######'
  - 解决方案
- - '#####'
  - 下一个更大的值
- - '######'
  - 解答
- - '#####'
  - 下一个分支
- - '######'
  - 解答
- - '#####'
  - 随机子集
- - '######'
  - 解决方案
- - '#####'
  - 覆盖范围
- - '######'
  - 解决方案
- - '#####'
  - Zeckendorf 表示法
- - '######'
  - 解法
- - '#####'
  - 顶级路径
- - '######'
  - 解决方案
- - '#####'
  - 相似组
- - '######'
  - 解决方案
- - '#####'
  - 篮子分配
- - '######'
  - 解决方案
- - '#####'
  - 最长递增子序列
- - '######'
  - 解决方案
- - '#####'
  - Quine（自产生程序）
- - '######'
  - 解决方案
- - '#####'
  - 总结
- - '##'
  - 附录 A：实用 Oracle 链接
- - '##'
  - 索引
- - '##'
  - 关于作者
