name: Oracle DBA Mentor
name_cn: Oracle DBA 导师指南
slug: oracle-dba-mentor
toc:
- - '#'
  - 引言
- - '##'
  - 书籍结构
- - '#'
  - 致谢
- - '##'
  - 关于作者和技术审校
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校
- - '#'
  - 第一部分：初始设置
- - '##'
  - 1. 引言
- - '###'
  - 成为一名 DBA
- - '###'
  - 典型的 DBA 一日
- - '###'
  - 数据库守护者
- - '###'
  - 继续前进
- - '#'
  - 2. 作为数据库管理员工作
- - '##'
  - 作为数据库管理员
- - '###'
  - 提示
- - '##'
  - 跨平台工作
- - '###'
  - 小贴士
- - '##'
  - 技巧
- - '##'
  - 数据库管理员的典型回答
- - '##'
  - 了解你的受众
- - '##'
  - 继续前进
- - '#'
  - 3. 创建我们的服务器
- - '##'
  - 下载 VirtualBox
- - '##'
  - 下载 Oracle Linux
- - '###'
  - 创建服务器
- - '##'
  - 安装与配置步骤
- - '##'
  - 继续前进
- - '#'
  - 4. 磁盘布局
- - '###'
  - 提示
- - '##'
  - 最佳灵活架构
- - '###'
  - ORACLE_BASE
- - '###'
  - ORACLE_HOME
- - '###'
  - 数据库管理文件
- - '###'
  - 诊断文件
- - '#'
  - 5. 安装 Oracle
- - '##'
  - 数据库文件
- - '##'
  - 全景概览
- - '##'
  - 继续前进
- - '##'
  - 访问安装指南
- - '###'
  - 提示
- - '##'
  - 下载 Oracle 数据库软件
- - '##'
  - 准备服务器
- - '##'
  - 安装 Oracle
- - '###'
  - 启动 OUI
- - '###'
  - 初始设置步骤
- - '###'
  - 选择安装类型
- - '###'
  - 选择数据库版本
- - '###'
  - 配置安装目录
- - '###'
  - 创建 oraInventory 目录
- - '###'
  - 指定操作系统用户组
- - '###'
  - 先决条件检查与摘要
- - '###'
  - 保存响应文件与安装
- - '###'
  - 执行配置脚本
- - '##'
  - 继续前进
- - '#'
  - 6. 创建我们的数据库
- - '##'
  - 创建数据库
- - '###'
  - 提示
- - '##'
  - 跳过监听器创建
- - '#'
  - 第二部分 使用 Oracle 数据库
- - '##'
  - 7. 恢复与备份
- - '###'
  - 启动 Oracle 监听程序
- - '###'
  - 执行我们的首次查询
- - '###'
  - 继续前进
- - '##'
  - 恢复先于备份
- - '###'
  - 小贴士
- - '##'
  - 恢复要求
- - '###'
  - 建议
- - '##'
  - 备份与恢复文档
- - '##'
  - 备份类型
- - '###'
  - 热备份与冷备份
- - '###'
  - RMAN 与用户管理备份
- - '###'
  - 逻辑备份
- - '##'
  - 还原与恢复
- - '##'
  - 我们的冷备份
- - '##'
  - 归档日志模式
- - '##'
  - 我们的热备份
- - '##'
  - 深入探索
- - '#'
  - 8. 安全性
- - '##'
  - 访问安全指南
- - '###'
  - 提示
- - '##'
  - 默认用户
- - '##'
  - 密码配置文件
- - '##'
  - 安全配置文件
- - '###'
  - 提示
- - '##'
  - 审计
- - '###'
  - 提示
- - '##'
  - 其他安全主题
- - '###'
  - 系统权限
- - '###'
  - 对象权限
- - '###'
  - 角色
- - '###'
  - 透明数据加密
- - '###'
  - DBMS_CRYPTO
- - '###'
  - 虚拟专用数据库
- - '###'
  - 网络加密
- - '###'
  - 更强的身份验证
- - '##'
  - 继续前行
- - '#'
  - 9. 连接到 Oracle
- - '##'
  - 本地连接
- - '###'
  - '此文件被 Oracle 工具程序使用。它由 root.sh 创建，并在使用数据库配置助理（DBCA）创建数据库时，或使用 ASM 配置助理（ASMCA）创建
    ASM 实例时更新。冒号 '':'' 用作字段分隔符。换行符表示条目结束。以井号 ''#'' 开头的行是注释。条目格式如下：$ORACLE_SID:$ORACLE_HOME::
    第一个和第二个字段分别是数据库的系统标识符和主目录。第三个字段指示 dbstart 工具在系统启动时是否应启动该数据库，"Y" 表示是，"N" 表示否。不允许存在具有相同
    $ORACLE_SID 的多个条目。'
- - '##'
  - 进程与继承 (Bequeath)
- - '##'
  - Oracle 监听器
- - '###'
  - 提示
- - '##'
  - Oracle 客户端
- - '##'
  - TNSNAMES
- - '##'
  - 常见 TNS 错误
- - '##'
  - EZ Connect
- - '###'
  - ODBC
- - '###'
  - 提示
- - '##'
  - JDBC
- - '##'
  - 继续前行
- - '#'
  - 10. 测试用例
- - '##'
  - 失败
- - '###'
  - 提示
- - '##'
  - 成功
- - '###'
  - 提示
- - '##'
  - 测试床
- - '###'
  - 提示
- - '##'
  - 快照
- - '#'
  - LiveSQL
- - '##'
  - 测试用例
- - '###'
  - 提示
- - '###'
  - 小贴士
- - '##'
  - 进行“假设”游戏
- - '##'
  - 示例模式
- - '##'
  - 继续前进
- - '#'
  - 第三部分 学习 Oracle 数据库
- - '#'
  - 11. 工具
- - '##'
  - 连接到我们的数据库
- - '###'
  - 配置网络连接
- - '###'
  - 设置静态 IP
- - '###'
  - 修改 Hosts 文件
- - '###'
  - 建立 SSH 连接
- - '##'
  - SQL*Plus
- - '###'
  - 提示
- - '##'
  - SQL 开发人员
- - '##'
  - Oracle Enterprise Manager
- - '##'
  - 显示 SQL
- - '###'
  - 提示
- - '#'
  - 数据库配置助手
- - '#'
  - 网络配置助手
- - '#'
  - 其他工具和实用程序
- - '#'
  - 继续前行
- - '#'
  - 12. 诊断
- - '##'
  - 诊断目标地
- - '##'
  - 告警日志
- - '#'
  - Oracle 数据库警报日志与实例管理
- - '##'
  - 警报日志启动实例
- - '##'
  - 启动失败示例
- - '##'
  - 缺失控制文件
- - '##'
  - 修复控制文件
- - '##'
  - 实例关闭
- - '##'
  - 实例崩溃分析
- - '#'
  - 警报日志
- - '##'
  - 写入警报日志
- - '##'
  - 查询警报日志
- - '#'
  - 监听器日志
- - '##'
  - 监听器日志位置
- - '##'
  - 监听器启动
- - '##'
  - 监听器关闭
- - '##'
  - 后台进程跟踪文件
- - '##'
  - 用户跟踪文件
- - '##'
  - ADRCI
- - '##'
  - 继续前行
- - '#'
  - 13. Oracle 文档
- - '##'
  - RTFM
- - '###'
  - 提示
- - '##'
  - 安装与升级
- - '##'
  - 管理
- - '##'
  - 2 天速成指南
- - '##'
  - 概念指南
- - '###'
  - 提示
- - '##'
  - 管理员指南
- - '###'
  - 提示
- - '##'
  - 性能调优指南
- - '##'
  - 错误消息
- - '##'
  - 备份与恢复
- - '##'
  - SQL 语言参考手册
- - '##'
  - PL/SQL 包与类型参考
- - '##'
  - 书库
- - '##'
  - 其他书籍
- - '##'
  - 继续前进
- - '#'
  - 14. 数据字典
- - '##'
  - 数据字典
- - '##'
  - 基础表
- - '##'
  - 静态字典视图
- - '###'
  - DBA_、ALL_、USER_ 与 CDB_
- - '###'
  - DICT
- - '#'
  - Oracle 数据字典与动态性能视图指南
- - '##'
  - 常用 DBA 视图
- - '##'
  - 有用的视图
- - '##'
  - 动态性能视图
- - '###'
  - 常用 V$ 视图
- - '###'
  - GV$ 视图
- - '##'
  - 实用示例
- - '##'
  - 继续前进
- - '#'
  - 第四部分 维护 Oracle 数据库
- - '#'
  - 15. My Oracle Support
- - '##'
  - 登录 My Oracle Support
- - '##'
  - CSI
- - '##'
  - 仪表板
- - '##'
  - 教程视频
- - '##'
  - 知识库
- - '##'
  - 显示文档与书签功能
- - '##'
  - 知识库使用建议
- - '##'
  - 服务请求
- - '##'
  - 补丁与更新
- - '##'
  - 认证
- - '##'
  - 相对时间
- - '##'
  - 继续前进
- - '#'
  - 16. 社交媒体
- - '##'
  - 社交媒体定义
- - '##'
  - 搜索引擎
- - '##'
  - 博客
- - '###'
  - 博客平台
- - '###'
  - 开设博客的理由
- - '###'
  - 写博客的个人益处
- - '###'
  - 小贴士
- - '##'
  - Twitter
- - '##'
  - 询问 TOM
- - '##'
  - 讨论论坛
- - '##'
  - YouTube
- - '#'
  - 会议和用户组
- - '#'
  - 继续前进
- - '#'
  - 17. 打补丁
- - '##'
  - 补丁概述
- - '##'
  - 补丁管理最佳实践
- - '###'
  - 重要提示
- - '###'
  - 关键规则
- - '##'
  - Oracle 版本解析
- - '###'
  - 提示
- - '##'
  - OPatch
- - '###'
  - 提示
- - '##'
  - 季度补丁
- - '#'
  - Oracle 季度补丁概述
- - '##'
  - 版本更新与 RU/RUR 说明
- - '##'
  - 版本补丁建议
- - '##'
  - 如何获取季度补丁
- - '##'
  - 安装 PSU
- - '##'
  - 17.x 补丁应用过程
- - '##'
  - 继续前行
- - '#'
  - 18. 升级
- - '##'
  - 升级的理由
- - '##'
  - 升级与新功能指南
- - '###'
  - 提示
- - '##'
  - 升级方法论
- - '##'
  - 升级准备与执行
- - '##'
  - 升级方法
- - '###'
  - 数据库升级助手
- - '###'
  - 手动升级
- - '###'
  - 导出/导入
- - '###'
  - 如何选择？
- - '##'
  - 安装 18c
- - '##'
  - 预升级信息工具
- - '##'
  - 升级前修复脚本执行
- - '###'
  - 回到日志文件中，剩下的只有升级后部分。
- - '##'
  - 升级后信息
- - '##'
  - 升级数据库
- - '#'
  - DBUA 升级结果
- - '##'
  - 升级后任务
- - '###'
  - '此文件由 ORACLE 实用程序使用。由 root.sh 创建，并在使用数据库配置助理创建数据库或使用 ASM 配置助理创建 ASM 实例时更新。冒号 '':''
    用作字段分隔符。换行符终止条目。以井号 ''#'' 开头的行是注释。条目格式如下：$ORACLE_SID:$ORACLE_HOME:: 第一个和第二个字段分别是数据库的系统标识符和主目录。第三个字段指示
    dbstart 工具在系统启动时是否应启动该数据库，"Y" 表示是，"N" 表示否。不允许存在具有相同 $ORACLE_SID 的多个条目。'
- - '##'
  - 监听器升级
- - '##'
  - 版本检查
- - '##'
  - 无效对象检查
- - '##'
  - 降级
- - '##'
  - 继续前进
- - '#'
  - 19. 容量规划
- - '##'
  - 复杂性
- - '##'
  - 容量规划
- - '##'
  - 企业管理器
- - '#'
  - 监控与容量规划图表
- - '##'
  - 数据字典
- - '#'
  - 棘手的问题
- - '#'
  - 继续前行
- - '#'
  - 第五部分 附录
- - '#'
  - 20. Oracle 架构
- - '##'
  - 数据库 vs. 实例
- - '##'
  - 文件类型
- - '###'
  - 数据文件
- - '###'
  - 临时文件
- - '###'
  - 联机重做日志
- - '###'
  - 归档重做日志
- - '###'
  - 撤销表空间文件
- - '###'
  - 控制文件
- - '###'
  - 参数文件
- - '###'
  - 口令文件
- - '##'
  - 内存结构
- - '###'
  - PGA
- - '###'
  - SGA
- - '###'
  - 缓冲区缓存
- - '###'
  - 共享池
- - '###'
  - 库缓存
- - '###'
  - 数据字典缓存
- - '###'
  - 结果缓存
- - '###'
  - 重做日志缓冲区
- - '###'
  - 大型池
- - '###'
  - Java 池
- - '###'
  - 固定 SGA
- - '#'
  - 调整 SGA 组件的大小
- - '#'
  - 后台进程
- - '##'
  - 强制性进程
- - '###'
  - 可选后台进程
- - '##'
  - 用户进程
- - '##'
  - 整合说明
- - '##'
  - 交互式快速参考
- - '##'
  - 实例启动
- - '##'
  - 继续前行
- - '#'
  - 21. 高级选项
- - '##'
  - 诊断包
- - '#'
  - 使用 Enterprise Manager 和 Diagnostics Pack 进行性能诊断
- - '##'
  - 调优包
- - '###'
  - 使用 SQL 调优顾问
- - '###'
  - 使用 SQL 访问顾问
- - '###'
  - 总结
- - '##'
  - 分区
- - '##'
  - 真正的应用集群
- - '##'
  - 多租户
- - '#'
  - 数据卫士
- - '##'
  - 概述
- - '##'
  - 与传统方法的对比
- - '##'
  - 数据丢失配置
- - '##'
  - 架构
- - '##'
  - 操作模式：切换与故障转移
- - '##'
  - 许可要求
- - '##'
  - Active Data Guard
- - '##'
  - 兼容性
- - '#'
  - 企业管理器
- - '##'
  - EM DB Express 与 EM Cloud Control
- - '##'
  - EM 界面与导航
- - '##'
  - 监控与告警
- - '##'
  - 管理额外付费包
- - '#'
  - 高级压缩
- - '##'
  - 真实应用测试
- - '##'
  - 后续内容
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W, X
- - '###'
  - Y, Z
