name: Pro SQL Server 2019 Administration
name_cn: SQL Server 2019 高级管理指南
slug: pro-sql-server-2019-administration
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 关于作者和技术评审者
- - '###'
  - 关于作者
- - '###'
  - 关于技术评审者
- - '#'
  - 第一部分 安装与配置
- - '##'
  - 第1章 规划部署
- - '###'
  - 版本与许可模型
- - '###'
  - 硬件考量
- - '####'
  - 指定战略性最低要求
- - '####'
  - 存储
- - '#####'
  - 本地连接存储
- - '######'
  - RAID 0
- - '######'
  - 注意
- - '######'
  - RAID 1
- - '######'
  - 注意
- - '######'
  - RAID 5
- - '######'
  - 注意
- - '######'
  - RAID 10
- - '######'
  - 注意
- - '######'
  - 文件放置
- - '######'
  - 固态硬盘 (SSD)
- - '######'
  - 使用 SAN
- - '#####'
  - 磁盘块大小
- - '#####'
  - 填入你要检查的驱动器盘符
- - '#####'
  - 初始化输出对象
- - '#####'
  - 初始化输出
- - '#####'
  - 将 fsutil 的每一行拆分为单独的数组值
- - '#####'
  - 格式化并显示结果
- - '###'
  - 操作系统考虑因素
- - '###'
  - 配置操作系统
- - '####'
  - 注意
- - '####'
  - 设置电源计划
- - '####'
  - 优化后台服务
- - '####'
  - 分配用户权限
- - '#####'
  - 初始化即时文件
- - '#####'
  - 在内存中锁定页面
- - '####'
  - 注意
- - '#####'
  - SQL 审核到事件日志
- - '####'
  - 注意
- - '###'
  - 选择功能
- - '####'
  - 数据库引擎服务
- - '####'
  - 分析服务
- - '####'
  - 机器学习服务器
- - '####'
  - 数据质量客户端
- - '####'
  - 客户端连接工具
- - '####'
  - 集成服务
- - '####'
  - 客户端工具向后兼容性
- - '####'
  - 客户端工具 SDK
- - '####'
  - 分布式重放控制器
- - '####'
  - 分布式重放客户端
- - '####'
  - SQL 客户端连接 SDK
- - '####'
  - 主数据服务
- - '####'
  - 注意
- - '###'
  - 总结
- - '##'
  - 第2章 GUI 安装
- - '###'
  - 安装中心
- - '####'
  - 规划选项卡
- - '####'
  - 安装选项卡
- - '####'
  - 维护选项卡
- - '####'
  - 提示
- - '####'
  - 工具选项卡
- - '####'
  - 资源选项卡
- - '####'
  - 高级选项卡
- - '####'
  - 选项选项卡
- - '###'
  - 安装独立数据库引擎实例
- - '####'
  - 准备步骤
- - '####'
  - 注意
- - '####'
  - 注意
- - '####'
  - 功能选择页面
- - '###'
  - 实例配置页面
- - '###'
  - 选择服务帐户
- - '####'
  - 注意
- - '###'
  - 选择排序规则
- - '####'
  - 注意
- - '####'
  - 配置实例安全
- - '####'
  - 注意
- - '####'
  - 配置实例
- - '###'
  - SQL Server 安装配置
- - '###'
  - FILESTREAM 配置
- - '###'
  - 配置分布式重放
- - '###'
  - 完成安装
- - '###'
  - 总结
- - '##'
  - 第3章 Server Core 安装
- - '###'
  - 安装实例
- - '####'
  - 必需参数
- - '#####'
  - IACCEPTSQLSERVERLICENSETERMS 开关
- - '#####'
  - ACTION 参数
- - '#####'
  - FEATURES 参数
- - '####'
  - 注意
- - '####'
  - 角色参数
- - '####'
  - 基本安装
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 注意
- - '###'
  - 冒烟测试
- - '####'
  - 提示
- - '####'
  - 注意
- - '###'
  - 故障排除安装
- - '####'
  - Summary.txt
- - '####'
  - Detail.txt
- - '####'
  - SystemConfigurationCheck_Report.htm
- - '#####'
  - 其他日志文件
- - '####'
  - 可选参数
- - '###'
  - 产品更新与配置安装指南
- - '####'
  - 注意事项
- - '####'
  - 功能概述
- - '####'
  - 命令行安装参数
- - '####'
  - 包含 CU 的安装示例
- - '####'
  - 验证实例版本
- - '###'
  - 使用配置文件
- - '####'
  - 提示
- - '###'
  - 自动化安装例程
- - '####'
  - 提示
- - '####'
  - 增强安装例程
- - '#####'
  - 初始化 ConnectionString 变量
- - '#####'
  - 配置操作系统设置
- - '#####'
  - 运行冒烟测试
- - '####'
  - 生产环境就绪
- - '#####'
  - 初始化连接字符串变量
- - '#####'
  - 安装实例
- - '#####'
  - 配置操作系统设置
- - '#####'
  - 运行冒烟测试
- - '###'
  - 总结
- - '##'
  - 第4章 在异构操作系统上安装
- - '###'
  - 提示
- - '###'
  - 在 Linux 上安装 SQL Server
- - '####'
  - 手动安装 SQL Server
- - '#####'
  - 导入公共 GPG 密钥
- - '#####'
  - 注册 SQL Server 软件仓库
- - '#####'
  - 更新软件包列表
- - '#####'
  - 安装 SQL Server 软件包
- - '#####'
  - 配置实例
- - '#####'
  - 连接到实例
- - '###'
  - 配置 SQL Server
- - '####'
  - 注意
- - '###'
  - 无人参与安装
- - '####'
  - 提示
- - '###'
  - 在 Docker 容器中安装 SQL Server
- - '####'
  - 注意
- - '####'
  - 运行 Microsoft 提供的 Docker 镜像
- - '####'
  - 提示
- - '####'
  - 创建用于 SQL Server 的简单 Docker 镜像
- - '###'
  - 提示
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 创建可配置的 SQL Server Docker 镜像
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - Kubernetes 支持
- - '###'
  - 总结
- - '##'
  - 第5章 配置实例
- - '###'
  - 实例配置
- - '####'
  - 使用 sp_configure
- - '####'
  - 处理器和内存配置
- - '#####'
  - 处理器亲和性
- - '####'
  - 注意
- - '###'
  - 注意事项
- - '###'
  - 关于 I/O 掩码的注意事项
- - '###'
  - 提示
- - '###'
  - 最大并行度 (MAXDOP)
- - '###'
  - 最小和最大服务器内存
- - '####'
  - 跟踪标志
- - '####'
  - 注意
- - '#####'
  - 定义初始变量
- - '#####'
  - 配置要插入到注册表路径中的完整服务名称
- - '#####'
  - 创建完整的注册表路径
- - '#####'
  - 从注册表路径收集所有属性
- - '#####'
  - 计算已存在的 SQLArg 属性的数量，以便确定序列中的下一个编号
- - '#####'
  - 根据序列中的下一个参数编号创建新参数的名称
- - '#####'
  - 构造参数的完整值
- - '#####'
  - 设置跟踪标志
- - '####'
  - 注意
- - '#####'
  - 跟踪标志 3042
- - '#####'
  - 跟踪标志 3226
- - '#####'
  - 跟踪标志 3625
- - '###'
  - 端口与防火墙
- - '####'
  - 通信过程
- - '####'
  - SQL Server 所需的端口
- - '####'
  - 注
- - '####'
  - 表 5-5：数据库引擎所需的端口
- - '####'
  - 配置实例将监听的端口
- - '#####'
  - 提示
- - '#####'
  - Initialize variables
- - '#####'
  - Load SMO Wmi.ManagedComputer assembly
- - '#####'
  - Create a new smo object
- - '#####'
  - Set static port
- - '#####'
  - Reconfigure TCP
- - '###'
  - 系统数据库
- - '####'
  - mssqlsystemresource (Resource)
- - '####'
  - MSDB
- - '####'
  - Master
- - '####'
  - 注意
- - '####'
  - 提示
- - '####'
  - Model
- - '####'
  - 提示
- - '####'
  - TempDB
- - '#####'
  - 优化 TempDB
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 缓冲池扩展
- - '###'
  - 混合缓冲池
- - '###'
  - 概要
- - '#'
  - 第二部分 数据库管理
- - '##'
  - 第6章 数据库配置
- - '###'
  - 数据存储
- - '####'
  - 提示
- - '####'
  - 文件组
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 注意
- - '####'
  - FILESTREAM 文件组
- - '####'
  - 注意
- - '####'
  - 提示
- - '####'
  - 内存优化文件组
- - '####'
  - 结构化文件组策略
- - '###'
  - 性能策略
- - '####'
  - 注意
- - '###'
  - 备份和恢复策略
- - '###'
  - 存储分层策略
- - '###'
  - 内存优化文件组策略
- - '###'
  - 文件与文件组维护
- - '####'
  - 添加文件
- - '####'
  - 提示
- - '####'
  - 扩展文件
- - '###'
  - 收缩文件
- - '####'
  - 注意
- - '###'
  - 数据库范围配置
- - '####'
  - 注意
- - '###'
  - 日志维护
- - '####'
  - 恢复模型
- - '####'
  - 注意
- - '####'
  - 日志文件数量
- - '####'
  - 收缩日志
- - '####'
  - 提示
- - '###'
  - 日志碎片化
- - '####'
  - 注意
- - '###'
  - 总结
- - '##'
  - 第7章 表优化
- - '###'
  - 表分区
- - '####'
  - 分区概念
- - '#####'
  - 数据库分区
- - '#####'
  - 分区键
- - '#####'
  - 分区函数
- - '#####'
  - 分区方案
- - '#####'
  - 索引对齐
- - '#####'
  - 分区层次结构
- - '####'
  - 提示
- - '###'
  - 实现分区
- - '####'
  - 创建分区对象
- - '#####'
  - 创建新的分区表
- - '#####'
  - 分区现有表
- - '####'
  - 监视分区表
- - '#####'
  - $PARTITION 函数
- - '#####'
  - 滑动窗口
- - '######'
  - 实现滑动窗口
- - '####'
  - 分区消除
- - '###'
  - 表压缩
- - '####'
  - 行压缩
- - '####'
  - 注意
- - '####'
  - 页压缩
- - '#####'
  - 前缀压缩
- - '#####'
  - 字典压缩
- - '#####'
  - 页压缩结构
- - '####'
  - 列存储压缩
- - '####'
  - 实现行压缩和页压缩
- - '#####'
  - 选择压缩级别
- - '#####'
  - 压缩表和分区
- - '#####'
  - 数据压缩向导
- - '#####'
  - 维护堆上的压缩
- - '#####'
  - 维护压缩分区
- - '###'
  - 内存优化表
- - '####'
  - 持久性
- - '####'
  - 创建和管理内存优化表
- - '####'
  - 性能概况
- - '####'
  - 注意事项
- - '####'
  - 提示
- - '####'
  - 注意事项
- - '####'
  - 表内存优化顾问
- - '####'
  - 注意
- - '####'
  - 本机编译对象
- - '###'
  - 原生编译表
- - '###'
  - 原生编译存储过程
- - '###'
  - 总结
- - '##'
  - 第8章 索引和统计信息
- - '###'
  - 聚集索引
- - '####'
  - 没有聚集索引的表
- - '####'
  - 有聚集索引的表
- - '####'
  - 主键聚簇
- - '####'
  - 注意
- - '####'
  - 提示
- - '####'
  - 管理聚集索引
- - '####'
  - 注意
- - '###'
  - 非聚集索引
- - '####'
  - 覆盖索引
- - '####'
  - 提示
- - '####'
  - 管理非聚集索引
- - '####'
  - 筛选索引
- - '####'
  - 专业应用的索引
- - '####'
  - 列存储索引
- - '#####'
  - 聚集列存储索引
- - '#####'
  - 非聚集列存储索引
- - '###'
  - 内存优化索引
- - '####'
  - 内存中非聚集哈希索引
- - '#####'
  - 提示
- - '#####'
  - 提示
- - '#####'
  - 注意
- - '#####'
  - 从结果看索引性能
- - '####'
  - 内存中非聚集索引
- - '###'
  - 维护索引
- - '####'
  - 缺失索引
- - '####'
  - 索引碎片化
- - '####'
  - 注意
- - '#####'
  - 检测碎片化
- - '###'
  - 移除碎片
- - '####'
  - 提示
- - '####'
  - 可恢复的索引操作
- - '####'
  - 提示
- - '####'
  - 分区索引
- - '###'
  - 统计信息
- - '####'
  - 提示
- - '####'
  - 筛选统计信息
- - '####'
  - 增量统计信息
- - '###'
  - 管理统计信息
- - '####'
  - 注
- - '###'
  - 摘要
- - '##'
  - 第9章 数据库一致性
- - '###'
  - 一致性错误
- - '####'
  - 理解一致性错误
- - '#####'
  - '`605` 错误'
- - '#####'
  - '`823` 错误'
- - '#####'
  - '`824` 错误'
- - '#####'
  - 5180 错误
- - '#####'
  - 7105 错误
- - '###'
  - 检测一致性错误
- - '####'
  - 页面验证选项
- - '####'
  - 注意
- - '####'
  - 提示
- - '####'
  - 可疑页
- - '####'
  - 注意
- - '####'
  - 小心
- - '####'
  - 注意
- - '#####'
  - 内存优化表的一致性问题
- - '####'
  - 系统数据库损坏
- - '#####'
  - 主数据库损坏
- - '#####'
  - 资源数据库或二进制文件损坏
- - '####'
  - DBCC CHECKDB
- - '#####'
  - 检查错误
- - '#####'
  - DBCC CHECKDB 结果所需的 TempDB 空间
- - '###'
  - 修复错误
- - '####'
  - 紧急模式
- - '####'
  - 注意
- - '####'
  - 其他用于处理损坏的 DBCC 命令
- - '#####'
  - DBCC CHECKCATALOG
- - '#####'
  - DBCC CHECKALLOC
- - '#####'
  - DBCC CHECKTABLE
- - '#####'
  - 谨慎
- - '#####'
  - DBCC CHECKFILEGROUP
- - '#####'
  - DBCC CHECKIDENT
- - '#####'
  - DBCC CHECKCONSTRAINTS
- - '####'
  - 提示
- - '####'
  - 超大型数据库的一致性检查
- - '#####'
  - 使用 PHYSICAL_ONLY 选项的 DBCC CHECKDB
- - '#####'
  - 使用 WITH CHECKSUM 备份和 DBCC CHECKALLOC
- - '#####'
  - 分工作业
- - '#####'
  - 卸载到辅助服务器
- - '###'
  - 总结
- - '#'
  - 第三部分 安全、弹性与工作负载扩展
- - '##'
  - 第10章 SQL Server 安全模型
- - '###'
  - 安全层级
- - '####'
  - 创建 Chapter10 数据库
- - '###'
  - 实现实例级安全
- - '###'
  - 服务器角色
- - '###'
  - SQL Server 安全基础
- - '####'
  - 登录名
- - '####'
  - 授予权限
- - '###'
  - 实现数据库级安全性
- - '####'
  - 数据库角色
- - '#####'
  - 提示
- - '####'
  - 架构 (Schemas)
- - '####'
  - 创建和管理包含式用户 (Contained Users)
- - '###'
  - 包含式数据库用户
- - '###'
  - 实现对象级安全性
- - '###'
  - 服务器审计
- - '###'
  - 创建服务器审计
- - '###'
  - 创建服务器审计规范
- - '####'
  - 启用和调用审计
- - '####'
  - 数据库审计规范
- - '####'
  - 提示
- - '####'
  - 审核审计行为
- - '###'
  - 安全报告
- - '####'
  - 提示
- - '####'
  - SQL 数据发现与分类
- - '####'
  - 漏洞评估
- - '##'
  - 第11章 加密
- - '###'
  - 概要
- - '###'
  - 加密层次结构
- - '####'
  - 加密概念
- - '#####'
  - 对称密钥
- - '#####'
  - 非对称密钥
- - '#####'
  - 证书
- - '#####'
  - Windows 数据保护 API
- - '####'
  - SQL Server 加密概念
- - '#####'
  - 主密钥
- - '#####'
  - 提示
- - '#####'
  - 层次结构
- - '####'
  - 注意
- - '###'
  - 透明数据加密
- - '####'
  - 注意
- - '####'
  - 实现透明数据加密
- - '####'
  - 注意
- - '####'
  - 注意
- - '####'
  - 管理透明数据加密
- - '###'
  - 迁移加密数据库
- - '####'
  - 提示
- - '###'
  - 管理单元格级加密
- - '###'
  - SQL Server 加密技术
- - '####'
  - 警告
- - '####'
  - 提示
- - '###'
  - 访问加密数据
- - '###'
  - Always Encrypted
- - '####'
  - 提示
- - '####'
  - 注意
- - '###'
  - 实现 Always Encrypted
- - '####'
  - 提示
- - '####'
  - 注意
- - '#####'
  - 创建一个证书，用于加密列主密钥。它将被存储在 Windows 证书存储的“当前用户”部分。
- - '#####'
  - 导入 SqlServer 模块。
- - '#####'
  - 连接到 Chapter11AlwaysEncrypted 数据库
- - '#####'
  - 创建一个设置对象，指定 -AllowEnclaveComputations 以使密钥支持安全飞地计算
- - '#####'
  - 创建列主密钥。
- - '#####'
  - 创建一个列加密密钥，使用列主密钥进行加密
- - '####'
  - 提示
- - '####'
  - 注意事项
- - '####'
  - 管理密钥
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 概要
- - '##'
  - 第12章 备份与还原
- - '###'
  - 备份基础
- - '####'
  - 恢复模型
- - '#####'
  - SIMPLE 恢复模型
- - '#####'
  - FULL 恢复模型
- - '#####'
  - 提示
- - '#####'
  - BULK LOGGED 恢复模型
- - '####'
  - 注意
- - '####'
  - 更改恢复模型
- - '####'
  - 提示
- - '####'
  - 备份类型
- - '#####'
  - 完整备份
- - '#####'
  - 差异备份
- - '#####'
  - 日志备份
- - '####'
  - 备份介质
- - '#####'
  - 备份设备
- - '#####'
  - 媒体集
- - '#####'
  - 备份集
- - '#####'
  - 备份策略
- - '######'
  - 仅完整备份
- - '######'
  - 完整备份和事务日志备份
- - '###'
  - 数据库备份
- - '####'
  - 完全、差异和事务日志备份
- - '####'
  - 文件组备份
- - '####'
  - 提示
- - '####'
  - 部分备份
- - '####'
  - 在 SQL Server Management Studio 中备份
- - '####'
  - 通过 T-SQL 进行备份
- - '#####'
  - 杂项选项
- - '#####'
  - 日志特定选项
- - '#####'
  - 错误管理选项
- - '#####'
  - 媒体集选项
- - '#####'
  - 备份集选项
- - '#####'
  - WITH 选项
- - '#####'
  - 备份选项
- - '###'
  - 数据库恢复
- - '####'
  - 在 SQL Server Management Studio 中恢复
- - '#####'
  - 提示
- - '#####'
  - 提示
- - '####'
  - 通过 T-SQL 还原
- - '#####'
  - 表 12-8：还原选项
- - '#####'
  - 表 12-14：杂项选项
- - '#####'
  - 表 12-13：错误管理选项
- - '#####'
  - 表 12-12：介质集选项
- - '#####'
  - 表 12-11：备份集选项
- - '#####'
  - 表 12-10：WITH 选项
- - '#####'
  - 表 12-9：还原参数
- - '###'
  - 还原到时间点
- - '###'
  - 还原文件和页面
- - '####'
  - 恢复文件
- - '####'
  - 注意
- - '####'
  - 恢复页面
- - '####'
  - 注意
- - '####'
  - 提示
- - '###'
  - 分段还原
- - '###'
  - 总结
- - '####'
  - 提示
- - '##'
  - 第13章 高可用性与灾难恢复概念
- - '###'
  - 可用性概念
- - '###'
  - 可用性级别
- - '###'
  - 服务级别协议与服务级别目标
- - '###'
  - 主动维护
- - '####'
  - 恢复点目标与恢复时间目标
- - '####'
  - 停机成本
- - '###'
  - 备用服务器的分类
- - '####'
  - 注
- - '###'
  - 高可用性与灾难恢复技术
- - '####'
  - AlwaysOn 故障转移集群
- - '####'
  - 提示
- - '#####'
  - 主动/主动配置
- - '####'
  - 注意
- - '#####'
  - 三节点及以上配置
- - '#####'
  - 仲裁
- - '####'
  - 提示
- - '####'
  - 注意
- - '####'
  - 提示
- - '####'
  - AlwaysOn 可用性组
- - '####'
  - 提示
- - '####'
  - 注
- - '#####'
  - 自动页面修复
- - '####'
  - 注意
- - '####'
  - 日志传送
- - '####'
  - 恢复模式
- - '####'
  - 远程监视服务器
- - '####'
  - 注意
- - '####'
  - 故障转移
- - '####'
  - 注意
- - '###'
  - 技术结合
- - '####'
  - 注意
- - '###'
  - 总结
- - '##'
  - 第14章 实施 AlwaysOn 可用性组
- - '###'
  - 注意
- - '###'
  - 实施 AlwaysOn 可用性组
- - '###'
  - 创建数据库
- - '###'
  - 配置 SQL Server
- - '####'
  - 注意
- - '###'
  - 创建可用性组
- - '###'
  - 使用新建可用性组向导
- - '####'
  - 注意
- - '####'
  - 注意
- - '#####'
  - 备份首选项选项卡
- - '#####'
  - 侦听器选项卡
- - '#####'
  - 提示
- - '#####'
  - 选择初始数据同步
- - '#####'
  - 提示
- - '#####'
  - 验证和完成
- - '###'
  - 使用“新建可用性组”对话框
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - Linux 上的可用性组
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 分布式可用性组
- - '####'
  - 注意
- - '####'
  - 提示
- - '###'
  - 管理 AlwaysOn 可用性组
- - '####'
  - 故障转移
- - '###'
  - 同步故障转移
- - '###'
  - 异步故障转移
- - '###'
  - 同步未包含对象
- - '###'
  - 监控
- - '####'
  - AlwaysOn 仪表板
- - '###'
  - AlwaysOn 可用性组管理注意事项
- - '####'
  - 注意
- - '#####'
  - AlwaysOn 健康跟踪
- - '####'
  - 其他管理注意事项
- - '####'
  - 注意
- - '###'
  - 总结
- - '##'
  - 第15章 实施日志传送
- - '###'
  - 为灾难恢复实施日志传送
- - '####'
  - GUI 配置
- - '###'
  - 新建作业计划屏幕与日志传送配置
- - '###'
  - 初始化辅助数据库选项卡
- - '###'
  - 复制文件选项卡
- - '###'
  - 还原事务日志选项卡
- - '###'
  - 监视服务器配置
- - '####'
  - 提示
- - '###'
  - 完成配置
- - '####'
  - T-SQL 配置
- - '####'
  - 注意
- - '###'
  - 日志传送维护
- - '####'
  - 故障转移日志传送
- - '####'
  - 切换角色
- - '####'
  - 监控
- - '###'
  - 摘要
- - '##'
  - 第16章 扩展工作负载
- - '###'
  - 数据库快照
- - '####'
  - 提示
- - '###'
  - 实现数据库快照
- - '####'
  - 从快照中恢复数据
- - '###'
  - 复制
- - '####'
  - 复制概念
- - '####'
  - 复制类型
- - '#####'
  - 快照
- - '#####'
  - 事务复制
- - '#####'
  - 提示
- - '#####'
  - 合并复制
- - '###'
  - 实现事务复制
- - '####'
  - 注意
- - '#####'
  - 实现分发服务器
- - '###'
  - 实施发布
- - '#####'
  - 实现订阅者
- - '#####'
  - 修改 PAL
- - '###'
  - 添加 AlwaysOn 可读辅助副本
- - '####'
  - 优势与注意事项
- - '####'
  - 实现可读辅助副本
- - '####'
  - 提示
- - '###'
  - 总结
- - '#'
  - 第四部分 性能与维护
- - '##'
  - 第17章 SQL Server 元数据
- - '###'
  - 提示
- - '###'
  - 介绍元数据对象
- - '###'
  - 服务器级和实例级元数据
- - '####'
  - 公开注册表值
- - '####'
  - 公开服务详细信息
- - '###'
  - 分析缓冲区缓存使用情况
- - '####'
  - 注意
- - '###'
  - 用于容量规划的元数据
- - '####'
  - 暴露文件统计信息
- - '####'
  - 提示
- - '####'
  - 使用文件统计信息进行容量分析
- - '####'
  - 注意
- - '###'
  - 用于故障排除和性能调优的元数据
- - '####'
  - 检索性能监视器计数器
- - '####'
  - 分析等待
- - '####'
  - 注意
- - '###'
  - 数据库元数据
- - '####'
  - 注意
- - '###'
  - 页面元数据字段参考
- - '###'
  - 元数据驱动自动化
- - '####'
  - 动态循环数据库快照
- - '####'
  - 仅重建碎片化的索引
- - '###'
  - 概要
- - '##'
  - 第18章 锁与阻塞
- - '###'
  - 理解锁机制
- - '####'
  - 锁粒度
- - '####'
  - 在线维护的锁定行为
- - '####'
  - 提示
- - '###'
  - 锁兼容性
- - '###'
  - 锁分区
- - '###'
  - 理解死锁
- - '####'
  - 死锁如何发生
- - '####'
  - 最小化死锁
- - '###'
  - 理解事务
- - '####'
  - 事务属性
- - '#####'
  - 原子性
- - '#####'
  - 一致性
- - '#####'
  - 隔离性
- - '######'
  - 事务异常
- - '#######'
  - 脏读
- - '#######'
  - 不可重复读
- - '#######'
  - 幻读
- - '######'
  - 隔离级别
- - '#######'
  - 悲观隔离级别
- - '#######'
  - 乐观隔离级别
- - '#####'
  - 持久性
- - '####'
  - 注意事项
- - '###'
  - 使用内存中 OLTP 的事务
- - '####'
  - 隔离级别
- - '#####'
  - 已提交读
- - '#####'
  - 已提交读快照
- - '#####'
  - 快照
- - '#####'
  - 可重复读
- - '#####'
  - 可序列化
- - '####'
  - 跨容器事务
- - '#####'
  - 重试逻辑
- - '###'
  - 观察事务、锁和死锁
- - '####'
  - 观察事务
- - '#####'
  - 注意
- - '#####'
  - 提示
- - '####'
  - 观察锁与争用
- - '#####'
  - 提示
- - '####'
  - 观察死锁
- - '#####'
  - 注意
- - '###'
  - 概述
- - '##'
  - 第19章 扩展事件
- - '###'
  - 扩展事件概念
- - '####'
  - 包
- - '####'
  - 事件
- - '####'
  - 目标
- - '####'
  - 操作
- - '####'
  - 谓词
- - '####'
  - 类型和映射
- - '####'
  - 会话
- - '###'
  - 创建事件会话
- - '###'
  - 使用新建会话对话框
- - '####'
  - 提示
- - '###'
  - 使用 T-SQL
- - '####'
  - 注意
- - '####'
  - 注意
- - '###'
  - 查看收集的数据
- - '####'
  - 使用数据分析器分析数据
- - '####'
  - 提示
- - '###'
  - 使用 T-SQL 分析数据
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 将扩展事件与操作系统数据关联起来
- - '####'
  - 将事件与 Perfmon 数据关联
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 将事件会话与操作系统级事件集成
- - '####'
  - 注意
- - '###'
  - 总结
- - '##'
  - 第20章 查询存储
- - '###'
  - 启用和配置查询存储
- - '###'
  - 使用查询存储数据
- - '###'
  - SSMS 报告
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 查询存储 T-SQL 对象
- - '####'
  - 提示
- - '###'
  - 解决查询存储问题
- - '####'
  - 提示
- - '###'
  - 总结
- - '##'
  - 第21章 分布式重放
- - '###'
  - 注意
- - '###'
  - 分布式重放概念
- - '####'
  - 分布式重放组件
- - '####'
  - 分布式重放架构
- - '###'
  - 配置环境
- - '####'
  - 配置控制器
- - '####'
  - 提示
- - '####'
  - 配置客户端
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 配置重播
- - '###'
  - 使用分布式重播
- - '####'
  - 同步目标
- - '####'
  - 提示
- - '####'
  - 创建跟踪
- - '####'
  - 提示
- - '###'
  - 创建扩展事件会话并启动跟踪
- - '###'
  - 生成要跟踪的活动
- - '###'
  - 重放跟踪
- - '####'
  - 转换跟踪文件
- - '####'
  - 预处理跟踪数据
- - '####'
  - 开始重放
- - '###'
  - 摘要
- - '##'
  - 第22章 自动化维护例程
- - '###'
  - SQL Server 代理
- - '####'
  - SQL Server 代理概念
- - '#####'
  - 计划
- - '#####'
  - 提示
- - '#####'
  - 操作员
- - '#####'
  - 注意
- - '#####'
  - 作业
- - '#####'
  - 警报
- - '####'
  - SQL Server Agent 安全性
- - '#####'
  - SQL Server Agent 数据库角色
- - '#####'
  - SQL Server Agent 代理账户
- - '###'
  - 创建 SQL Server 代理作业
- - '###'
  - 创建简单的 SQL Server 代理作业
- - '####'
  - 创建复杂的 SQL Server Agent 作业
- - '#####'
  - 创建凭据
- - '#####'
  - 创建代理
- - '#####'
  - 提示
- - '#####'
  - 创建计划
- - '#####'
  - 配置数据库邮件
- - '#####'
  - 注意
- - '#####'
  - 注意
- - '#####'
  - 创建操作员
- - '#####'
  - 创建作业
- - '######'
  - 提示
- - '#####'
  - 监控与管理作业
- - '###'
  - 执行作业
- - '###'
  - 查看作业历史记录
- - '###'
  - 创建警报
- - '###'
  - 多服务器作业
- - '####'
  - 配置 MSX 和 TSX 服务器
- - '####'
  - 注意
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 创建主作业
- - '###'
  - 管理目标服务器
- - '###'
  - 概要
- - '##'
  - 第23章 基于策略的管理
- - '###'
  - PBM 概念
- - '####'
  - 方面
- - '####'
  - 条件
- - '####'
  - 目标
- - '####'
  - 策略
- - '####'
  - 评估模式
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 中央管理服务器
- - '####'
  - 提示
- - '###'
  - 创建策略
- - '####'
  - 创建简单策略
- - '#####'
  - 创建可手动评估的策略
- - '#####'
  - 手动评估策略
- - '#####'
  - 提示
- - '#####'
  - 提示
- - '#####'
  - 提示
- - '#####'
  - 创建一个防止不良活动的策略
- - '####'
  - 创建高级策略
- - '####'
  - 注意
- - '###'
  - 策略管理
- - '###'
  - 提示
- - '###'
  - 注意
- - '###'
  - 策略管理
- - '###'
  - 导入和导出策略
- - '###'
  - 使用策略进行企业管理
- - '###'
  - 使用 PowerShell 评估策略
- - '###'
  - 提示
- - '###'
  - 摘要
- - '##'
  - 第24章 资源调控器
- - '###'
  - 资源调控器概念
- - '####'
  - 资源池
- - '####'
  - 工作负荷组
- - '####'
  - 分类器函数
- - '###'
  - 实现资源管理器
- - '####'
  - 创建资源池
- - '####'
  - 提示
- - '####'
  - 提示
- - '####'
  - 创建工作负载组
- - '####'
  - 注意
- - '####'
  - 创建分类器函数
- - '####'
  - 测试分类器函数
- - '###'
  - 监控资源调控器
- - '####'
  - 使用性能监视器进行监控
- - '####'
  - 注意
- - '####'
  - 注意
- - '####'
  - 使用动态管理视图进行监控
- - '#####'
  - 工作负载组的统计列说明
- - '###'
  - 连接 DMV 并生成报告
- - '###'
  - 重置统计信息
- - '###'
  - 资源池处理器关联性 DMV
- - '###'
  - 资源池卷 DMV
- - '####'
  - 提示
- - '####'
  - 提示
- - '###'
  - 总结
- - '###'
  - 索引
- - '####'
  - A
- - '####'
  - B
- - '####'
  - C
- - '####'
  - D
- - '####'
  - E
- - '####'
  - F
- - '####'
  - G
- - '####'
  - H
- - '####'
  - I
- - '####'
  - J
- - '####'
  - K
- - '####'
  - L
- - '####'
  - M
- - '####'
  - N
- - '####'
  - O
- - '####'
  - P
- - '####'
  - Q
- - '####'
  - R
- - '####'
  - S
- - '####'
  - T
- - '####'
  - U
- - '####'
  - V
- - '####'
  - W, X, Y, Z
