name: Pro SQL Server 2012 Reporting Services
name_cn: SQL Server 2012 Reporting Services 高级指南
slug: pro-sql-server-2012-reporting-services
toc:
- - '#'
  - Pro SQL Server 2012 Reporting Services 第三版
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '#'
  - 第 1 章：Reporting Services 架构概述
- - '#'
  - 第 2 章：报表创作：设计高效查询
- - '#'
  - 第 3 章：使用 SQL Server Data Tools 进行 Reporting Services 设计简介
- - '#'
  - 第 4 章：报表布局
- - '##'
  - 设置分页
- - '##'
  - 使用报表对象
- - '##'
  - 实现列表
- - '##'
  - 实现文本框
- - '##'
  - 实现表格
- - '##'
  - 实现矩形
- - '##'
  - 实现矩阵
- - '##'
  - 本章小结
- - '#'
  - 第 5 章：实现仪表板式报表对象
- - '##'
  - 理解图表数据区域
- - '##'
  - 实现图像
- - '##'
  - 实现仪表盘
- - '##'
  - 实现地图
- - '##'
  - 实现数据条
- - '##'
  - 实现迷你图
- - '##'
  - 实现指标
- - '##'
  - 本章小结
- - '#'
  - 第 6 章：构建报表
- - '##'
  - 使用报表向导创建报表
- - '##'
  - 从头开始构建报表
- - '###'
  - 格式化输出
- - '###'
  - 添加小计
- - '###'
  - 添加交互性
- - '####'
  - 文档映射
- - '####'
  - 可见性
- - '####'
  - 交互式排序
- - '####'
  - 超链接操作
- - '#####'
  - 添加书签链接
- - '#####'
  - 添加 URL 链接
- - '#####'
  - 使用报表参数构建 URL 链接
- - '#####'
  - 跳转到报表
- - '#####'
  - 添加超链接格式和工具提示
- - '####'
  - 使用存储过程设置报表参数
- - '####'
  - 使用多值参数
- - '####'
  - 应用筛选器
- - '####'
  - 添加图表
- - '####'
  - 添加 Tablix 元素
- - '####'
  - 配置报表和组变量
- - '####'
  - 添加仪表盘控件
- - '####'
  - 添加收尾工作
- - '##'
  - 本章小结
- - '#'
  - 第 7 章：在报表中使用自定义 .NET 代码
- - '##'
  - 在报表中使用嵌入式代码
- - '###'
  - 使用 ExceedMaxCosts 函数
- - '###'
  - 在报表中使用 ExceedMaxCost 函数
- - '###'
  - 从嵌入式代码访问 .NET 程序集
- - '##'
  - 在报表中使用自定义程序集
- - '###'
  - 向报表解决方案添加类库项目
- - '###'
  - 部署自定义程序集
- - '###'
  - 向报表添加程序集引用
- - '###'
  - 调试自定义程序集
- - '###'
  - 项目故障排除
- - '##'
  - 本章小结
- - '#'
  - 第 8 章：部署报表
- - '##'
  - 使用报表管理器
- - '##'
  - 使用报表生成器 3.0
- - '##'
  - 使用 BIDS 和 Visual Studio 2012
- - '##'
  - 配置报表部署选项
- - '##'
  - 使用配置管理器设置部署
- - '##'
  - 通过解决方案资源管理器部署报表
- - '##'
  - 使用 rs.exe 实用工具
- - '##'
  - 使用报表服务器 Web 服务
- - '###'
  - 访问 Web 服务
- - '###'
  - 布局窗体
- - '###'
  - 为窗体编写代码
- - '###'
  - 允许用户输入服务器名称
- - '###'
  - 使用文件夹列表填充 TreeView 控件
- - '###'
  - 打开 RDL 文件并上传到服务器
- - '###'
  - 运行应用程序
- - '##'
  - 本章小结
- - '#'
  - 第 9 章：从 .NET 应用程序呈现报告
- - '##'
  - 实现 URL 访问
- - '##'
  - URL 报告访问路径格式
- - '##'
  - URL 参数与前缀
- - '##'
  - 报告参数
- - '##'
  - HTML 查看器命令
- - '##'
  - 报告服务器命令参数
- - '##'
  - 凭据参数
- - '##'
  - 报告查看器 Web 部件命令
- - '##'
  - URL 示例
- - '##'
  - 将 SSRS 2012 与 .NET 应用程序集成
- - '##'
  - 使用 WebBrowser 控件构建自定义报告查看器
- - '##'
  - 使用报表查看器控件构建报告查看器
- - '##'
  - 在本地呈现报告
- - '##'
  - 创建报告的数据源
- - '##'
  - 设计报告
- - '##'
  - 使用报表服务器 Web 服务
- - '##'
  - Web 服务方法类别
- - '##'
  - 创建 GetParameters 窗体
- - '##'
  - 编写报告参数窗体的代码
- - '##'
  - GetParameters_Load 事件
- - '##'
  - 调用 Web 服务的 GetItemParameters 方法
- - '##'
  - 呈现最终报告
- - '##'
  - 在 ASP.NET 中构建报告查看器
- - '##'
  - 总结
- - '#'
  - 第 10 章：管理报告
- - '##'
  - 探索 SSRS 部署中的管理角色
- - '##'
  - 管理内容
- - '##'
  - 设置共享计划
- - '##'
  - 创建共享计划
- - '##'
  - 配置报告以使用共享计划
- - '##'
  - 使用报告管理器更新和上传 RDL 文件
- - '##'
  - 为报告设置数据源
- - '##'
  - 更改报告数据源
- - '##'
  - 为报告历史创建快照
- - '##'
  - 处理报告与执行缓存
- - '##'
  - 管理订阅
- - '##'
  - 管理标准订阅
- - '##'
  - 创建标准订阅
- - '##'
  - 配置订阅
- - '##'
  - 管理数据驱动订阅
- - '##'
  - 设计订阅查询
- - '##'
  - 创建数据驱动订阅
- - '##'
  - 执行审核与性能分析
- - '##'
  - 配置 SSRS 日志记录
- - '##'
  - 转换 ExecutionLog 表
- - '##'
  - 设计日志报告
- - '##'
  - 监视性能
- - '##'
  - 以编程方式控制 SSRS
- - '##'
  - 使用 SOAP 控制 SSRS
- - '##'
  - 使用 WMI 控制 SSRS
- - '##'
  - 总结
- - '#'
  - 第 11 章：保护报告安全
- - '##'
  - 加密数据
- - '##'
  - 加密技术简介
- - '##'
  - 使用 SSL 保护网络流量
- - '##'
  - 分析 HTTP 流量
- - '##'
  - 应用 SSL 证书
- - '##'
  - 捕获 HTTPS 流量
- - '##'
  - 保护 SSRS 中的数据存储
- - '##'
  - 设置身份验证和用户数据访问权限
- - '##'
  - SSRS 角色简介
- - '##'
  - 测试 SSRS 角色分配
- - '##'
  - 使用 User!UserID 过滤报告内容
- - '##'
  - 设置数据源安全性
- - '##'
  - 设置 SQL Server 权限
- - '##'
  - 审核报告
- - '##'
  - SSRS 审核
- - '##'
  - 日志文件审核简介
- - '##'
  - 总结
- - '#'
  - 第 12 章：使用 SSRS 交付商业智能
- - '##'
  - 为 SQL Analysis Services 构建 SSRS 报告
- - '##'
  - 在 SSRS 中使用 Analysis Service 多维数据集
- - '##'
  - 设置 Analysis Services 数据源
- - '##'
  - 使用图形化 MDX 查询生成器
- - '##'
  - 将 SSRS 与 Microsoft SharePoint 2010 集成
- - '##'
  - 在独立服务器上安装 SharePoint 2010 和 SQL Server 2012
- - '##'
  - 安装 SharePoint 2010
- - '##'
  - 以 SharePoint 模式安装 SQL Server 2012 Reporting Services
- - '##'
  - 配置 SharePoint 2010
- - '##'
  - 安装并启动 Reporting Services SharePoint 服务
- - '##'
  - 创建新的 Reporting Services 服务应用程序
- - '##'
  - 配置 Reporting Services 与 SharePoint 的集成
- - '##'
  - 在 SharePoint 集成模式的 SSRS 安装中部署报告
- - '##'
  - 创建一个简单的仪表板来显示 SSRS 报告
- - '##'
  - 创建数据警报
- - '##'
  - 总结
- - '#'
  - 第 13 章：使用报表生成器 1.0、2.0 和 3.0 创建报告
- - '##'
  - 获取用户反馈
- - '##'
  - 报告模型简介
- - '##'
  - 使用 BIDS 2008 R2 创建报告模型
- - '##'
  - 添加数据源
- - '##'
  - 创建数据源视图
- - '##'
  - 创建报告模型
- - '##'
  - 使用报表生成器 1.0 创建报告
- - '##'
  - 创建表格报告
- - '##'
  - 创建矩阵报告
- - '##'
  - 创建图表报告
- - '##'
  - 使用报表生成器 2.0 向导创建报告
- - '##'
  - 使用报表生成器 2.0 创建报告
- - '##'
  - 使用报表生成器 3.0 创建报告
- - '##'
  - 报告部件
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 引言
- - '###'
  - 本书面向的读者
- - '##'
  - 前提条件
- - '##'
  - 下载代码
- - '##'
  - 联系作者
