name: DBA Survivor
name_cn: DBA 生存指南
slug: dba-survivor
toc:
- - '#'
  - 修复后的目录
- - '##'
  - 前言
- - '###'
  - 关于作者
- - '###'
  - 关于技术审阅者
- - '###'
  - 致谢
- - '###'
  - 引言
- - '#'
  - 第一章：我是如何走到这里的？
- - '##'
  - 我的旅程
- - '##'
  - 早期的教训
- - '##'
  - 职业生涯早期
- - '##'
  - 运气、准备与机遇
- - '##'
  - 社群
- - '##'
  - 其他旅程
- - '###'
  - 药剂师
- - '###'
  - 酒店经理
- - '###'
  - 估算主管
- - '###'
  - MUMPS 程序员
- - '##'
  - 你被选中了！
- - '##'
  - 你的旅程
- - '###'
  - 积累生活经验
- - '###'
  - 做好准备
- - '###'
  - 做一位负责任的管理者
- - '###'
  - 接受培训
- - '###'
  - 获得认证
- - '###'
  - 现在去争取你的机会吧！
- - '###'
  - 保持专注
- - '#'
  - 第二章：现在我该做什么？
- - '##'
  - 你与总统的共同点
- - '##'
  - 你的初始检查清单
- - '###'
  - 创建服务器列表
- - '###'
  - 检查数据库备份
- - '###'
  - 验证恢复能力
- - '###'
  - 建立客户列表
- - '###'
  - 列出“最重要”的数据库
- - '###'
  - 列出即将进行的项目和可交付成果
- - '###'
  - 建立环境基线
- - '###'
  - 制定你的恢复计划
- - '##'
  - 信息已就绪，接下来呢？
- - '###'
  - 与你的经理会面
- - '###'
  - 与开发人员会面
- - '###'
  - 与服务器管理员会面
- - '###'
  - 与你的客户会面
- - '##'
  - 系统管理员是你的朋友
- - '##'
  - 那个警报严重吗？
- - '##'
  - 我应该调查那个警报吗？
- - '###'
  - 审查警报系统
- - '###'
  - 询问开发人员
- - '###'
  - 询问服务器管理员
- - '###'
  - 询问你的客户
- - '##'
  - 嗨，想一起吃个午饭吗？
- - '###'
  - 以吃会友
- - '###'
  - 政治手腕，或置身事外
- - '###'
  - 应对内向性格
- - '####'
  - 认识到这并无不妥
- - '####'
  - 照顾好自己
- - '####'
  - 开放坦率
- - '####'
  - 加入一些组织
- - '####'
  - 对话开场白与寒暄
- - '##'
  - 追踪你的进展
- - '##'
  - 变被动为主动
- - '#'
  - 第三章：基础知识
- - '##'
  - RAID 简介
- - '###'
  - 为何 RAID 如此重要？
- - '###'
  - 追求性能的 RAID 配置
- - '###'
  - 追求容错能力的 RAID 配置
- - '##'
  - 你想要哪种 RAID 级别？
- - '###'
  - 你的需求
- - '###'
  - 面向 DBA 的 SAN 基础知识
- - '###'
  - 为何 RAID 5 可能适合你
- - '##'
  - 失传的基准测试艺术
- - '##'
  - 核心在于盘片，宝贝
- - '##'
  - 高可用性选项
- - '###'
  - 集群
- - '###'
  - 日志传送
- - '###'
  - 复制
- - '####'
  - 事务复制
- - '####'
  - 合并复制
- - '####'
  - 快照复制
- - '###'
  - 数据库镜像
- - '##'
  - 灾难恢复规划
- - '###'
  - 灾难恢复测试
- - '###'
  - 卡内基音乐厅
- - '##'
  - 网络就像卫生间
- - '###'
  - 叫个水管工来
- - '###'
  - 立即修复！
- - '##'
  - DBA 代表……
- - '###'
  - 人们会抵制变化
- - '###'
  - 拥有标准和流程并非坏事
- - '###'
  - 人们会责备他们不理解的事物
- - '##'
  - 责备与功劳
- - '##'
  - 正确与讨喜的需求
- - '#'
  - 第四章：对开发者而言，开发服务器就是生产服务器
- - '##'
  - 为何开发者如此“需求旺盛”
- - '###'
  - 压力之下
- - '###'
  - 业务需求
- - '###'
  - SQL 知识
- - '##'
  - 服务级别协议
- - '###'
  - 做一个好客户
- - '###'
  - 沟通是关键
- - '##'
  - 管理期望
- - '###'
  - 没人在意付出
- - '###'
  - 我们来谈谈
- - '###'
  - 尽早参与
- - '###'
  - 沟通你的行动
- - '####'
  - 你不够快
- - '####'
  - 你做错了
- - '###'
  - 积极响应并承担责任
- - '##'
  - 时间管理
- - '###'
  - 制定日常工作流程
- - '###'
  - 缓解压力
- - '###'
  - 待办清单
- - '###'
  - 任务分块
- - '###'
  - 学会拒绝
- - '##'
  - 代码评审与克里斯·汉森
- - '#'
  - 第五章：生产支持
- - '##'
  - 服务级别协议
- - '###'
  - 我以为我们已有协议？
- - '###'
  - 了解你的工作内容
- - '###'
  - 友善待人
- - '##'
  - 建立支持流程
- - '###'
  - 定义流程
- - '###'
  - 发布流程
- - '###'
  - 提醒与执行
- - '##'
  - 工作/生活平衡
- - '###'
  - 沟通
- - '###'
  - 保护你的私人时间
- - '###'
  - 欢乐游戏时光
- - '##'
  - 外包
- - '##'
  - 工作质量
- - '##'
  - 语言障碍
- - '##'
  - 安全
- - '##'
  - 工作保障
- - '##'
  - 美好事物
- - '#'
  - 第六章：基础故障排除
- - '##'
  - CSI：SQL
- - '###'
  - 事件
- - '###'
  - 询问盘查
- - '###'
  - 监控
- - '##'
  - 常见瓶颈
- - '###'
  - 磁盘
- - '###'
  - 内存
- - '###'
  - CPU
- - '##'
  - 可用工具
- - '###'
  - 可靠性与性能监视器
- - '###'
  - 活动监视器
- - '###'
  - 动态管理视图 (DMV)
- - '###'
  - 等待统计信息
- - '###'
  - SQL Profiler
- - '###'
  - 网站
- - '####'
  - 搜索引擎
- - '####'
  - 论坛
- - '####'
  - 技术资源
- - '#'
  - 第七章：自助餐在哪里？
- - '##'
  - 食物可以是毒品
- - '###'
  - 情绪化进食
- - '###'
  - 无意识进食
- - '###'
  - 克服坏习惯
- - '##'
  - 社交聚会
- - '###'
  - 早餐
- - '###'
  - 午餐
- - '###'
  - 欢乐时光
- - '##'
  - 出差旅行
- - '##'
  - 锻炼
- - '###'
  - 找到动力与增加步数
- - '###'
  - 定期锻炼的必要性
- - '##'
  - 睡眠
- - '##'
  - 卡路里
- - '#'
  - 第八章：培训，来点这个
- - '##'
  - 培训的理由
- - '###'
  - 职业发展
- - '###'
  - 角色转变
- - '###'
  - 试点新系统
- - '###'
  - 客户满意度
- - '###'
  - 员工福利
- - '###'
  - 工作满意度
- - '###'
  - 员工激励
- - '###'
  - 流程效率
- - '###'
  - 时间管理
- - '###'
  - 沟通技巧
- - '###'
  - 商业效益
- - '###'
  - 士气提升
- - '###'
  - 降低流失率
- - '###'
  - 降低风险
- - '###'
  - 保持竞争力
- - '##'
  - 培训资源
- - '###'
  - 网站
- - '###'
  - 自我培训
- - '###'
  - 志愿服务
- - '###'
  - 在职培训
- - '###'
  - 专业协会
- - '###'
  - 继续教育
- - '###'
  - 课堂培训
- - '###'
  - 认证
- - '##'
  - 构建你的论证
- - '###'
  - 确定你的培训需求
- - '###'
  - 确定需要培训的人数
- - '###'
  - 确定将使用哪些选项
- - '###'
  - 计算相关成本/费用
- - '###'
  - 确定培训的益处
- - '###'
  - 确定成本节约
- - '###'
  - 衡量你的结果！
- - '#'
  - 第九章：连接. 学习. 分享
- - '##'
  - 沟通
- - '###'
  - 开始阅读
- - '###'
  - 开始参与
- - '###'
  - 加入论坛
- - '###'
  - 开始写作
- - '###'
  - 开始演讲
- - '###'
  - 克服恐惧
- - '##'
  - 专业协会
- - '###'
  - 最新行业信息
- - '###'
  - 写作机会
- - '###'
  - 演讲机会
- - '###'
  - 人际网络
- - '###'
  - 人际网络基础
- - '###'
  - 建立您的人际网络
- - '###'
  - 如何感到舒适
- - '###'
  - 如何接近他人
- - '###'
  - 选择正确的房间
- - '###'
  - 让事情变得更简单
- - '#'
  - 第十章：总结
- - '##'
  - 达成目标
- - '##'
  - 身处其位
- - '##'
  - 坚守岗位
- - '#'
  - 索引
- - '##'
  - 条目列表
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
