name: PostgreSQL Query Optimization
name_cn: PostgreSQL 查询优化
slug: postgresql-query-optimization
toc:
- - '#'
  - 引言
- - '##'
  - 我们为何撰写本书
- - '##'
  - 不会涵盖的内容
- - '##'
  - 目标受众
- - '##'
  - 读者将学到什么
- - '##'
  - PostgreSQL 数据库
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '#'
  - 1. 为什么需要优化？
- - '##'
  - 我们所说的优化是什么意思？
- - '##'
  - 为何困难：命令式与声明式
- - '###'
  - 比较相似的查询
- - '###'
  - 命令式思维的自然性
- - '###'
  - 编写声明式查询
- - '##'
  - 优化目标
- - '##'
  - 优化流程
- - '###'
  - 优化 OLTP 与 OLAP
- - '###'
  - 数据库设计与性能
- - '###'
  - 应用程序开发与性能
- - '###'
  - 生命周期的其他阶段
- - '##'
  - PostgreSQL 的特性
- - '##'
  - 总结
- - '#'
  - 2. 理论：是的，我们需要它！
- - '##'
  - 查询处理概述
- - '###'
  - 编译
- - '###'
  - 优化与执行
- - '##'
  - 关系、逻辑与物理操作
- - '###'
  - 关系操作
- - '#'
  - 3. 关系理论与查询优化
- - '##'
  - 关系操作与等价规则
- - '##'
  - 逻辑操作
- - '##'
  - 查询作为表达式：集合式思维
- - '##'
  - 操作与算法
- - '##'
  - 总结
- - '#'
  - 4. 更多理论：算法
- - '##'
  - 算法成本模型
- - '##'
  - 数据访问算法
- - '###'
  - 存储结构
- - '###'
  - 全表扫描
- - '###'
  - 基于索引的表访问
- - '###'
  - 仅索引扫描
- - '###'
  - 比较数据访问算法
- - '##'
  - 索引结构
- - '##'
  - 什么是索引？
- - '##'
  - B 树索引
- - '###'
  - 为什么 B 树如此常用？
- - '###'
  - 其他类型的索引
- - '##'
  - 关系的组合
- - '###'
  - 嵌套循环
- - '###'
  - 基于哈希的算法
- - '###'
  - 排序合并算法
- - '###'
  - 算法比较
- - '##'
  - 总结
- - '#'
  - 5. 理解执行计划
- - '##'
  - 综合运用：优化器如何构建执行计划
- - '##'
  - 阅读执行计划
- - '##'
  - 理解执行计划
- - '###'
  - 优化过程中发生了什么？
- - '###'
  - 为什么有这么多执行计划可供选择？
- - '##'
  - 如何计算执行成本？
- - '##'
  - 优化器如何被误导？
- - '#'
  - 6. 短查询与索引
- - '##'
  - 何为“短”查询？
- - '##'
  - 选择选择标准
- - '###'
  - 索引选择性
- - '###'
  - 唯一索引与约束
- - '##'
  - 嵌套循环连接与索引
- - '##'
  - 是否总是为外键列创建索引？
- - '##'
  - 索引与非等值条件
- - '###'
  - 索引与列转换
- - '##'
  - 索引与 like 操作符
- - '##'
  - 使用多个索引
- - '##'
  - 复合索引
- - '##'
  - 复合索引如何工作？
- - '##'
  - 降低选择性
- - '##'
  - 使用索引进行数据检索
- - '###'
  - 覆盖索引
- - '###'
  - 过度选择条件
- - '##'
  - 回到短查询的定义
- - '##'
  - 如何改进这个查询？
- - '##'
  - 部分索引
- - '##'
  - 索引与连接顺序
- - '##'
  - 何时不使用索引
- - '###'
  - 避免使用索引
- - '###'
  - 为什么 PostgreSQL 会忽略我的索引？
- - '##'
  - 让 PostgreSQL 做它该做的事！
- - '##'
  - 如何构建合适的索引
- - '###'
  - 构建还是不构建
- - '###'
  - 需要哪些索引？
- - '###'
  - 哪些索引是不需要的？
- - '##'
  - 索引与短查询的可扩展性
- - '##'
  - 总结
- - '#'
  - 7. 长查询与全表扫描
- - '##'
  - 哪些查询被视为长查询？
- - '##'
  - 长查询与全表扫描
- - '##'
  - 长查询与哈希连接
- - '##'
  - 长查询与连接顺序
- - '###'
  - 什么是半连接？
- - '##'
  - 半连接与连接顺序
- - '##'
  - 更多关于连接顺序
- - '###'
  - 什么是反连接？
- - '###'
  - 使用 JOIN 操作符的半连接和反连接
- - '###'
  - 何时需要指定连接顺序？
- - '##'
  - 分组：先过滤，后分组
- - '##'
  - 分组：先分组，后选择
- - '##'
  - 使用集合操作
- - '##'
  - 避免多次扫描
- - '#'
  - 8. 长查询：附加技术
- - '##'
  - 构造查询
- - '##'
  - 临时表和 CTE
- - '###'
  - 临时表
- - '###'
  - 公共表表达式（CTE）
- - '##'
  - 视图：用还是不用
- - '##'
  - 为何要使用视图？
- - '##'
  - 物化视图
- - '###'
  - 创建和使用物化视图
- - '###'
  - 刷新物化视图
- - '###'
  - 我应该创建物化视图吗？
- - '##'
  - 物化视图的增长与优化
- - '###'
  - 物化视图是否需要优化？
- - '###'
  - 依赖关系
- - '##'
  - 分区
- - '##'
  - 分区能提升性能吗？
- - '##'
  - 为什么要创建分区表？
- - '##'
  - 并行处理
- - '##'
  - 本章小结
- - '#'
  - 9. 优化数据修改
- - '##'
  - 什么是 DML？
- - '##'
  - 优化数据修改的两种途径
- - '##'
  - DML 是如何工作的？
- - '###'
  - 底层输入/输出
- - '###'
  - 并发控制的影响
- - '##'
  - 数据修改与索引
- - '##'
  - 数据操作语言与清理
- - '###'
  - 批量 UPDATE/DELETE
- - '###'
  - 频繁更新
- - '##'
  - 引用完整性与触发器
- - '##'
  - 总结
- - '#'
  - 10. 设计至关重要
- - '##'
  - 设计的重要性
- - '##'
  - 为何使用关系模型？
- - '###'
  - 数据库的类型
- - '###'
  - 实体-属性-值模型
- - '###'
  - 键值模型
- - '###'
  - 层次模型
- - '###'
  - 融合各家所长
- - '##'
  - 灵活性与效率和正确性之间的权衡
- - '##'
  - 我们必须进行规范化吗？
- - '##'
  - 代理键的使用与误用
- - '###'
  - airport (机场)
- - '###'
  - aircraft (航空器)
- - '###'
  - booking (预订)
- - '###'
  - booking_leg (预订航段)
- - '###'
  - passenger (旅客)
- - '###'
  - account (账户)
- - '###'
  - flight (航班)
- - '###'
  - boarding_pass (登机牌)
- - '##'
  - 本章总结
- - '#'
  - 11. 配置参数怎么办？
- - '##'
  - PostgreSQL 配置参数概述
- - '###'
  - 内存分配
- - '###'
  - 连接与会话
- - '##'
  - 调优参数以获得更好性能
- - '##'
  - 是否有更好的方法？
- - '##'
  - 参数调优的其他局限性
- - '##'
  - 结论
- - '#'
  - 12. 应用程序开发与性能
- - '##'
  - 响应时间至关重要
- - '##'
  - 全局等待
- - '##'
  - 性能指标
- - '##'
  - 阻抗失配
- - '##'
  - 一片好心铺就的道路
- - '###'
  - 应用程序开发模式
- - '###'
  - 购物清单问题
- - '###'
  - 接口
- - '##'
  - 欢迎来到 ORM 的世界
- - '##'
  - 寻求更好的解决方案
- - '##'
  - 总结
- - '#'
  - 13. 函数
- - '##'
  - 函数创建
- - '###'
  - 内部函数
- - '###'
  - 用户自定义函数
- - '###'
  - 过程语言简介
- - '###'
  - 美元引用
- - '###'
  - 函数参数与函数输出：空函数
- - '###'
  - 函数重载
- - '##'
  - 函数执行
- - '##'
  - 函数执行内部原理
- - '##'
  - 函数与性能
- - '###'
  - 使用函数如何降低性能
- - '###'
  - 函数是否有提升性能的机会？
- - '##'
  - 函数与用户定义类型
- - '##'
  - 用户自定义数据类型
- - '##'
  - 返回复合类型的函数
- - '##'
  - 使用具有嵌套结构的复合类型
- - '##'
  - 函数与类型依赖性
- - '##'
  - 使用函数进行数据操作
- - '##'
  - 函数与安全
- - '##'
  - 业务逻辑如何处理？
- - '##'
  - OLAP 系统中的函数
- - '###'
  - 参数化
- - '###'
  - 不显式依赖表和视图
- - '###'
  - 执行动态 SQL 的能力
- - '##'
  - 存储过程
- - '###'
  - 无结果函数
- - '###'
  - 函数与存储过程
- - '###'
  - 事务管理
- - '###'
  - 异常处理
- - '##'
  - 总结
- - '#'
  - 14. 动态 SQL
- - '##'
  - 什么是动态 SQL
- - '###'
  - 为什么动态 SQL 在 Postgres 中效果更好
- - '###'
  - 那么 SQL 注入呢？
- - '##'
  - 如何使用动态 SQL 获得最优执行计划
- - '##'
  - 在 OLAP 系统中使用动态 SQL
- - '##'
  - 使用动态 SQL 实现灵活性
- - '##'
  - 使用动态 SQL 辅助优化器
- - '##'
  - 外部数据包装器与动态 SQL
- - '##'
  - 总结
- - '#'
  - 15. 规避对象关系映射的陷阱
- - '##'
  - 为何应用开发者青睐 NORM
- - '##'
  - ORM vs. NORM
- - '##'
  - NORM 解析
- - '##'
  - 实体关系图
- - '##'
  - 传输对象层次结构
- - '##'
  - JSON Schema 契约
- - '##'
  - 从应用程序视角看 NORM
- - '##'
  - 从数据库视角看 NORM
- - '###'
  - 将 JSON 映射到数据库
- - '###'
  - 生成数据库代码
- - '###'
  - 从数据库获取数据
- - '##'
  - 修改数据库中的数据
- - '##'
  - 为什么不直接存储 JSON？！
- - '##'
  - 性能提升
- - '##'
  - 与应用程序开发人员协同工作
- - '##'
  - 总结
- - '#'
  - 16. 更复杂的过滤与搜索
- - '##'
  - 全文搜索
- - '##'
  - 多维和空间搜索
- - '##'
  - PostgreSQL 中的广义索引类型
- - '###'
  - GIST 索引
- - '###'
  - 全文搜索的索引
- - '###'
  - 索引非常大的表
- - '#'
  - 17. 终极优化算法
- - '##'
  - JSON 与 JSONB 的索引
- - '##'
  - 小结
- - '##'
  - 主要步骤
- - '##'
  - 分步指南
- - '###'
  - 步骤 1：短查询还是长查询？
- - '###'
  - 步骤 2：短查询
- - '####'
  - 步骤 2.1：最具限制性的条件
- - '####'
  - 步骤 2.2：检查索引
- - '####'
  - 步骤 2.3：添加额外的选择条件（如果适用）
- - '####'
  - 步骤 2.4：构建（或重建）查询
- - '###'
  - 步骤 3：长查询
- - '###'
  - 步骤 4：增量更新
- - '###'
  - 步骤 5：非增量长查询
- - '#'
  - 18. 结论
- - '##'
  - 等等——还有更多内容！
- - '##'
  - 总结
- - '#'
  - 数据库技术术语索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
