name: PRACTICAL GRAPH STRUCTURES IN SQL SERVER AND AZURE SQL
name_cn: SQL Server 和 Azure SQL 中的图结构实践指南
slug: practical-graph-structures-in-sql-server-and-azure-sql
toc:
- - '#'
  - 前言
- - '#'
  - 致谢
- - '#'
  - 1. 图论简介
- - '##'
  - 图的基础知识
- - '###'
  - 定义
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 2. 图论核心概念：子图、行走与连通性
- - '##'
  - 子图
- - '##'
  - 行走与路径
- - '##'
  - 欧拉路径
- - '##'
  - 连通图与桥边
- - '#'
  - 3. 计算中的图/有向图
- - '##'
  - 环状图与非环状图
- - '##'
  - 总结
- - '#'
  - 4. 数据结构与算法
- - '##'
  - 基本实现
- - '##'
  - 无环图
- - '###'
  - 图 2-2
- - '###'
  - 图 2-3
- - '###'
  - 图 2-4
- - '###'
  - 树
- - '###'
  - 其他类型的非循环图
- - '##'
  - 循环图
- - '##'
  - 加权边
- - '###'
  - 无向图
- - '##'
  - 本章小结
- - '#'
  - 5. SQL 图表基础
- - '##'
  - 对象创建
- - '##'
  - 创建数据
- - '##'
  - 查询数据
- - '###'
  - 节点到节点查询
- - '####'
  - 过滤输出
- - '###'
  - 多个 MATCH 表达式
- - '###'
  - 遍历变量层级路径
- - '####'
  - 显示路径中的最后一个节点
- - '####'
  - 路径聚合
- - '####'
  - 控制处理深度
- - '####'
  - 过滤特定路径
- - '####'
  - 查找节点间的所有路径
- - '##'
  - 加权图计算
- - '##'
  - 对匹配项检查条件
- - '##'
  - 总结
- - '#'
  - 6. SQL 图形表：高级主题
- - '##'
  - 高级数据创建技术
- - '###'
  - 构建接口层
- - '####'
  - INSERT
- - '####'
  - SQL 查询与图数据库操作
- - '####'
  - UPDATE
- - '####'
  - 删除（DELETE）
- - '###'
  - 使用可组合 JSON 标签加载数据
- - '####'
  - 使用 `NODE_ID_FROM_PARTS` 函数构建图形数据
- - '##'
  - 异构查询
- - '##'
  - 完整性约束与索引
- - '###'
  - 边约束
- - '####'
  - 数据库边约束管理
- - '####'
  - 删除 EC_Follows 约束
- - '####'
  - 删除位置行并检查数据
- - '####'
  - 查询数据发现问题
- - '####'
  - 删除问题行
- - '####'
  - 重新添加约束并使用 CASCADE
- - '####'
  - 将约束改为 NO ACTION
- - '####'
  - 创建新表 LivesAt 并添加数据
- - '####'
  - 恢复数据以匹配模型
- - '###'
  - 唯一性约束（及索引）
- - '###'
  - 附加约束
- - '##'
  - 元数据总结
- - '###'
  - 列出数据库中的图对象
- - '###'
  - 图列的类型
- - '###'
  - 用于获取图信息的工具
- - '##'
  - 总结
- - '#'
  - 7. 树数据结构
- - '##'
  - 创建数据结构
- - '###'
  - 基础表结构
- - '###'
  - 树结构索引与维护
- - '##'
  - 销售结构演示
- - '##'
  - 树维护核心代码
- - '##'
  - 创建新节点的代码
- - '###'
  - 创建新节点至关重要
- - '###'
  - 插入初始数据
- - '###'
  - 查看插入的数据
- - '##'
  - 处理层次结构数据
- - '###'
  - 重新指定父节点
- - '###'
  - 删除节点
- - '###'
  - 测试代码
- - '#'
  - 8. SQL 图数据操作：插入、删除与层级处理示例
- - '##'
  - 数据准备与层级展示
- - '##'
  - 树形输出代码
- - '###'
  - 返回部分树
- - '###'
  - 确定是否存在子节点
- - '###'
  - 聚合每个级别的子节点活动
- - '#'
  - 9. 实现组织树形结构：创建、查询与管理
- - '##'
  - 存储过程定义
- - '##'
  - 执行与结果
- - '##'
  - 代码解析
- - '##'
  - 总结
- - '#'
  - 10. 树结构、算法与性能
- - '##'
  - 替代的树实现
- - '###'
  - 路径技术
- - '###'
  - 添加辅助表
- - '###'
  - 路径技术
- - '###'
  - 代码
- - '####'
  - 表创建脚本
- - '####'
  - 插入新行
- - '###'
  - 层次结构路径方法
- - '####'
  - 返回层次结构
- - '####'
  - 检查子节点
- - '####'
  - 报告销售数据
- - '###'
  - 辅助表
- - '####'
  - Kimball 辅助表
- - '#####'
  - 代码
- - '####'
  - 表创建脚本
- - '####'
  - 检查子节点
- - '####'
  - 层级显示辅助表
- - '#####'
  - 代码
- - '#####'
  - 表创建脚本
- - '####'
  - 使用辅助对象
- - '##'
  - 销售报告
- - '##'
  - 性能比较
- - '#'
  - 11. 其他有向无环图
- - '##'
  - 问题集
- - '##'
  - 示例
- - '###'
  - 图 7-3 虚构的谢尔维货架系统分解图
- - '###'
  - 图 7-4 表示结构中物品重用的有向无环图
- - '###'
  - 图 7-5 谢尔维项目的完整图示
- - '##'
  - 判断某零件是否用于构建
- - '##'
  - 为构建选取物品
- - '##'
  - 打印构建的部件列表
- - '###'
  - 解决方案：递归 CTE
- - '###'
  - 初始结果与解读
- - '###'
  - 调整累计计数
- - '###'
  - 最终聚合查询
- - '##'
  - 总结
- - '#'
  - 12. 一个用于测试的图
- - '##'
  - 示例
- - '###'
  - 创建表
- - '###'
  - 加载数据
- - '###'
  - 查询
- - '####'
  - 查找与特定节点相连的所有节点
- - '###'
  - 检查一个节点是否与另一个节点相连
- - '###'
  - 返回两个节点之间的所有路径
- - '###'
  - 优化查询与递归停止条件
- - '###'
  - 查找用户在任何层级上连接的所有具有共同兴趣的人
- - '####'
  - 查找在任一层级与用户存在特定共同兴趣的连接用户
- - '####'
  - 通过其他节点建立连接
- - '##'
  - 性能调优结果
- - '###'
  - 测试结果
- - '##'
  - 性能调优总结
- - '###'
  - 测试
- - '###'
  - 为内部列创建索引
- - '###'
  - 采用最大并行度为 1
- - '###'
  - 考虑拆分某些查询
- - '##'
  - 结束（还是开始？）
