name: Oracle SQL tuning with Oracle SQLTXPLAIN
name_cn: Oracle SQLTXPLAIN SQL 调优指南
slug: oracle-sql-tuning-with-oracle-sqltxplain
toc:
- - '#'
  - Oracle SQL Tuning with Oracle SQLTXPLAIN
- - '##'
  - 版权声明
- - '##'
  - ISBN 信息
- - '##'
  - 商标说明
- - '##'
  - 免责声明
- - '##'
  - 编辑与制作团队
- - '##'
  - 发行与购买信息
- - '##'
  - 章节概览
- - '##'
  - 目录
- - '##'
  - 第 2 章：基于成本的优化器环境
- - '###'
  - 系统统计信息
- - '###'
  - 基于成本的优化器参数
- - '###'
  - Siebel 环境考量
- - '###'
  - 提示
- - '###'
  - 变更历史
- - '###'
  - 列统计信息
- - '###'
  - 超出范围的值
- - '###'
  - 高估与低估
- - '###'
  - 神秘变化之谜
- - '###'
  - 总结
- - '##'
  - 第 3 章：对象统计信息如何导致您的执行计划出错
- - '###'
  - 什么是统计信息？
- - '###'
  - 对象统计信息
- - '###'
  - 分区
- - '###'
  - 过时的统计信息
- - '###'
  - 采样大小
- - '###'
  - 如何收集统计信息
- - '###'
  - 保存、恢复和锁定统计信息
- - '###'
  - 午夜截断之谜
- - '###'
  - 总结
- - '##'
  - 第 4 章：倾斜度如何导致您的执行时间多变
- - '###'
  - 倾斜度
- - '###'
  - 什么是倾斜度？
- - '###'
  - 如何判断数据是否倾斜
- - '###'
  - 倾斜度如何影响执行计划
- - '###'
  - 直方图
- - '###'
  - 直方图类型
- - '###'
  - 何时使用直方图
- - '###'
  - 如何添加和移除直方图
- - '###'
  - 绑定变量
- - '###'
  - 什么是绑定变量？
- - '###'
  - 什么是绑定变量窥探与绑定捕获？
- - '###'
  - '`Cursor_Sharing` 及其取值'
- - '###'
  - 可变执行时间之谜
- - '###'
  - 总结
- - '##'
  - 第 5 章：查询转换的故障排除
- - '###'
  - 什么是查询转换？
- - '###'
  - '`10053` 跟踪文件'
- - '###'
  - 如何获取 `10053` 跟踪文件？
- - '###'
  - '`10053` 跟踪文件里有什么？'
- - '###'
  - 什么是查询转换？
- - '###'
  - 我们为何要禁用查询转换？
- - '###'
  - 优化器参数
- - '###'
  - 优化器提示
- - '###'
  - 成本计算
- - '###'
  - 总结
- - '##'
  - 第 6 章：通过配置文件强制执行计划
- - '###'
  - 什么是 `SQL Profile`？
- - '###'
  - '`SQLT` 的 `SQL Profile` 从何而来？'
- - '###'
  - 您能用 `SQL Profile` 做什么？
- - '###'
  - 如何确认您正在使用 `SQL Profile`？
- - '###'
  - 如何将 `SQL Profile` 从一个数据库迁移到另一个数据库？
- - '###'
  - 总结
- - '#'
  - 第 7 章：自适应游标共享
- - '##'
  - 绑定变量及其必要性
- - '##'
  - '`CURSOR_SHARING` 参数'
- - '##'
  - 绑定变量窥探
- - '##'
  - 绑定敏感与绑定感知游标
- - '##'
  - 设置绑定敏感游标
- - '##'
  - 使用 SQLTXTRACT 报告检查 ACS
- - '##'
  - ACS 会出错吗？
- - '##'
  - 总结
- - '#'
  - 第 8 章：动态采样与基数反馈
- - '##'
  - 什么是动态采样？
- - '##'
  - 如何控制动态采样
- - '##'
  - 如何查找 `optimizer_dynamic_sampling` 的值
- - '##'
  - 动态采样与并行语句
- - '##'
  - 我应该设置什么动态采样值？
- - '##'
  - 基数反馈
- - '##'
  - 基数反馈如何工作？
- - '##'
  - 如何判断是否使用了基数反馈？
- - '##'
  - 何时使用基数反馈？
- - '##'
  - 基数反馈与动态采样如何协同工作？
- - '##'
  - 双胞胎案例
- - '##'
  - 总结
- - '#'
  - 第 9 章：在 Data Guard 物理备用数据库中使用 SQLTXPLAIN
- - '##'
  - Data Guard 物理备用数据库
- - '##'
  - '`SQLTXTRSBY`'
- - '##'
  - '`SQLTXTRACT` 的局限性'
- - '##'
  - 我们如何使用 `XTRSBY`？
- - '##'
  - '`XTRSBY` 报告是什么样的？'
- - '##'
  - '`roxtract` 工具'
- - '##'
  - 我们如何使用 `roxtract`？
- - '##'
  - '`roxtract` 报告是什么样的？'
- - '##'
  - 总结
- - '#'
  - 第 10 章：比较执行计划
- - '##'
  - 如何使用 `SQLTCOMPARE`？
- - '##'
  - 一个实际例子
- - '##'
  - 收集主方法存储库数据
- - '##'
  - 准备主方法存储库数据
- - '##'
  - 导入存储库数据
- - '##'
  - 运行 `SQLTCOMPARE`
- - '##'
  - 阅读 `SQLTCOMPARE` 报告
- - '##'
  - 总结
- - '#'
  - 第 11 章：构建良好的测试用例
- - '##'
  - 你能用测试用例做什么？
- - '##'
  - 构建测试用例
- - '##'
  - 一步步构建测试用例
- - '##'
  - 测试用例文件
- - '##'
  - SQL 语句
- - '##'
  - 如何快速构建测试用例 (`XPRESS.sql`)
- - '##'
  - 探索执行计划
- - '##'
  - 优化器参数
- - '##'
  - 添加和移除提示
- - '##'
  - 优化器的版本
- - '##'
  - SQL 的结构
- - '##'
  - 索引
- - '#'
  - 第 12 章：使用 XPLORE 排查意外的执行计划变更
- - '##'
  - 何时应使用 XPLORE？
- - '##'
  - XPLORE 如何工作？
- - '##'
  - XPLORE 能改变什么？
- - '##'
  - XPLORE 无法改变什么
- - '##'
  - 什么是 Fix Control？
- - '##'
  - 什么是 SQL Monitor 报告？
- - '##'
  - 一个 XPLORE 会话示例
- - '##'
  - 准备你的测试用例
- - '##'
  - 构建第一个脚本
- - '##'
  - 构建主控脚本
- - '##'
  - 运行脚本
- - '##'
  - 审查结果
- - '##'
  - 寻找最佳执行计划
- - '##'
  - 回顾原始测试用例
- - '##'
  - XPLORE 中的其他信息
- - '##'
  - 总结
- - '#'
  - 第 13 章：跟踪文件、TRCANLZR 与修改 SQLT 行为
- - '##'
  - 10046 跟踪
- - '###'
  - 为何收集 10046 跟踪？
- - '###'
  - 10046 解码
- - '###'
  - 我们如何收集 10046 跟踪
- - '##'
  - TKPROF
- - '##'
  - TRCASPLIT
- - '##'
  - TRCANLZR
- - '##'
  - TRCAXTR
- - '##'
  - 修改 SQLT 行为
- - '##'
  - 总结
- - '#'
  - 第 14 章：运行健康检查
- - '##'
  - 什么是 SQL 健康检查？
- - '##'
  - '`sqlhc.sql` 脚本'
- - '##'
  - '`sqlhc.sql` 产生什么'
- - '##'
  - 运行 SQLHC 脚本
- - '##'
  - 主要健康检查报告
- - '##'
  - 诊断报告
- - '##'
  - 执行计划报告
- - '##'
  - Monitor 报告
- - '##'
  - '`sqldx.sql` 脚本'
- - '##'
  - '`sqlhcxec.sql` 脚本'
- - '##'
  - 总结
- - '#'
  - 第 15 章：最终总结
- - '##'
  - 调优方法论
- - '##'
  - 为何 SQLT 是当之无愧的最佳调优实用工具
- - '##'
  - 关于平台的说明
- - '##'
  - 其他资源
- - '##'
  - 总结
- - '#'
  - 附录 A：安装 SQLTXPLAIN
- - '##'
  - 标准 SQLT 安装
- - '##'
  - SQLT 安装后如何更改许可级别
- - '##'
  - 远程 SQLT 安装
- - '##'
  - 附录与索引
- - '###'
  - 附录 B：CBO 参数 (11.2.0.1)
- - '###'
  - 附录 C：工具配置参数
- - '###'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审阅者
- - '##'
  - 致谢
- - '##'
  - 前言
- - '#'
  - 我与 SQLT 的故事：从被拒绝到广泛采用
- - '##'
  - 与 Abel Macias 的初次碰撞
- - '##'
  - 第三次重写与`SQLT`的独立
- - '##'
  - 工具的本质与社区的认可
- - '##'
  - 致谢杰出贡献者
- - '##'
  - 个人的感言
- - '#'
  - 引言
- - '##'
  - 本书的由来
- - '##'
  - 不要购买本书
- - '##'
  - 请购买本书
- - '#'
  - SQLT 入门指南
- - '##'
  - 什么是 SQLT？
- - '##'
  - SQLT 的由来？
- - '##'
  - 你为何没听说过 SQLT？
- - '##'
  - 我是如何知道 SQLT 的？
- - '##'
  - 开始使用 SQLT
- - '###'
  - 如何获取 SQLT 副本？
- - '###'
  - 如何安装 SQLT？
- - '#'
  - SQLT 报告的安装与运行
- - '##'
  - 安装步骤
- - '##'
  - 运行您的第一个 SQLT 报告
- - '##'
  - 何时使用 SQLTXTRACT 与 SQLTXECUTE
- - '##'
  - 您的第一份 SQLT 报告
- - '##'
  - 一些简单的导航
- - '#'
  - 如何分析 SQLT 报告
- - '##'
  - 如何分析 SQLT 报告
- - '##'
  - 基数与选择性
- - '##'
  - 什么是成本？
- - '#'
  - Oracle SQL 执行计划与成本分析
- - '##'
  - 系统指标与成本计算
- - '##'
  - 执行计划的阅读方法
- - '##'
  - 连接方法
- - '##'
  - 本章小结
- - '#'
  - 附录 B：CBO 参数 (11.2.0.1)
- - '##'
  - 处理隐藏参数的一般方法
- - '##'
  - 一些隐藏参数的更详细描述
- - '###'
  - '`_optimizer_extended_cursor_sharing_rel`'
- - '###'
  - '`_optimizer_cartesian_enabled`'
- - '###'
  - '`_optimizer_cost_model`'
- - '###'
  - '`_optimizer_ignore_hints`'
- - '###'
  - '`_optimizer_max_permutations`'
- - '###'
  - '`_optimizer_use_feedback`'
- - '###'
  - '`_optimizer_search_limit`'
- - '###'
  - 全参数列表
- - '#'
  - 附录 C：工具配置参数
- - '###'
  - SQLT 参数参考
- - '####'
  - 导出控制
- - '####'
  - 健康检查
- - '####'
  - 报告与统计信息
- - '####'
  - SQL 监控与调优
- - '####'
  - 其他工具与功能
- - '#'
  - 索引
