name: Leveling Up with SQL
name_cn: SQL 进阶指南
slug: leveling-up-with-sql
toc:
- - '#'
  - 版权页
- - '#'
  - 引言
- - '##'
  - 示例数据库
- - '##'
  - 说明
- - '##'
  - 源代码
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '#'
  - 1. 准备工作
- - '##'
  - 关于示例数据库
- - '##'
  - 设置
- - '###'
  - 数据库管理软件
- - '###'
  - 数据库客户端
- - '###'
  - 示例数据库
- - '##'
  - 你可能已经知道的内容
- - '###'
  - 一些哲学概念
- - '####'
  - 数据 vs. 信息 vs. 值
- - '####'
  - 数据库表
- - '###'
  - 编写 SQL
- - '###'
  - 基础 SQL
- - '###'
  - 数据类型
- - '###'
  - SQL 子句
- - '####'
  - 使用 WHERE 子句筛选数据
- - '#####'
  - 多重断言
- - '#####'
  - 通配符匹配
- - '####'
  - 使用 ORDER BY 子句排序
- - '#####'
  - 限制结果数量
- - '#####'
  - 排序字符串
- - '###'
  - 计算列
- - '####'
  - 使用 NULL 值进行计算
- - '#####'
  - 别名
- - '#####'
  - 子查询
- - '####'
  - CASE 表达式
- - '###'
  - 类型转换
- - '###'
  - 视图
- - '##'
  - 连接
- - '###'
  - ON 子句
- - '###'
  - 连接类型
- - '##'
  - 聚合
- - '##'
  - 表操作
- - '###'
  - 数据类型
- - '###'
  - 约束
- - '###'
  - 外键
- - '###'
  - 索引
- - '##'
  - 数据操作
- - '##'
  - 集合操作
- - '##'
  - 后续内容
- - '#'
  - 2. 使用表设计
- - '##'
  - 理解规范化表
- - '###'
  - 列应当独立
- - '##'
  - 添加城镇表
- - '##'
  - 添加到城镇的外键
- - '##'
  - 更新客户表
- - '##'
  - 移除旧的地址列
- - '###'
  - 创建客户详情视图
- - '###'
  - 删除地址列
- - '##'
  - 更改城镇
- - '#'
  - 提升数据库完整性
- - '##'
  - 添加国家信息
- - '##'
  - 附加说明
- - '###'
  - 提升数据库完整性
- - '####'
  - 修复可空列的问题
- - '#####'
  - 替换 NULL 数量值
- - '#####'
  - 为数量列设置 NOT NULL 约束
- - '#####'
  - 为数量列设置 DEFAULT 默认值
- - '#####'
  - 为数量列添加正数 CHECK 约束
- - '#####'
  - 合并更改
- - '#####'
  - 在 SQLite 中进行更改
- - '####'
  - 其他调整
- - '#####'
  - 确保价格非负
- - '#####'
  - 确保作者生年早于卒年
- - '##'
  - 添加索引
- - '###'
  - 为 Books 和 Authors 表添加索引
- - '##'
  - 创建唯一索引
- - '##'
  - 回顾
- - '###'
  - 范式
- - '###'
  - 多值处理
- - '###'
  - 修改表
- - '###'
  - 视图
- - '###'
  - 索引
- - '###'
  - 最终成果
- - '##'
  - 总结
- - '##'
  - 后续内容
- - '#'
  - 3. 表关系与连接
- - '##'
  - 关系概述
- - '##'
  - 一对多关系
- - '###'
  - 计算一对多连接的结果数
- - '###'
  - NOT IN 的怪癖
- - '###'
  - 创建书籍与作者视图
- - '###'
  - 一对一关系
- - '###'
  - 一对多可能关系
- - '###'
  - 多值处理
- - '##'
  - 多对多关系
- - '##'
  - 连接多对多表
- - '##'
  - 对多个值进行汇总
- - '##'
  - 组合连接
- - '##'
  - 多对多关系无处不在
- - '##'
  - 另一个多对多示例
- - '##'
  - 向关联表中插入数据
- - '###'
  - 添加一本书和一位作者
- - '####'
  - 添加一位作者
- - '####'
  - 添加一本书
- - '###'
  - 添加一笔新销售
- - '####'
  - 在销售表中添加一笔新销售
- - '####'
  - 添加销售项目并获取价格
- - '####'
  - 完成销售
- - '##'
  - 回顾
- - '###'
  - 关系类型
- - '###'
  - 连接表
- - '###'
  - 视图
- - '###'
  - 向相关表插入数据
- - '#'
  - 总结
- - '#'
  - 后续内容
- - '#'
  - 4. 处理计算数据
- - '##'
  - 计算基础
- - '###'
  - 使用别名
- - '####'
  - 别名名称
- - '####'
  - AS 是可选的
- - '####'
  - 别名在查询后续部分不可用
- - '###'
  - 处理 NULL 值
- - '####'
  - Coalesce
- - '####'
  - 修复作者姓名
- - '###'
  - 在其他子句中使用计算
- - '###'
  - 关于计算的更多细节
- - '###'
  - 类型转换
- - '###'
  - 数值计算
- - '####'
  - 基本算术
- - '##'
  - 数学函数
- - '##'
  - 近似函数
- - '##'
  - 数字格式化
- - '###'
  - 字符串计算
- - '####'
  - 大小写敏感性
- - '####'
  - ASCII 与 Unicode
- - '####'
  - 连接
- - '####'
  - 字符串函数
- - '##'
  - 日期操作
- - '###'
  - 输入和存储日期/时间
- - '###'
  - 获取当前日期/时间
- - '##'
  - 按日期/时间分组和排序
- - '##'
  - 提取日期/时间的部分
- - '###'
  - 在 PostgreSQL、MariaDB/MySQL 和 Oracle 中提取日期
- - '###'
  - 在 Microsoft SQL 中提取日期
- - '##'
  - 格式化日期
- - '##'
  - 日期运算
- - '##'
  - CASE 表达式
- - '###'
  - CASE 的各种用法
- - '###'
  - Coalesce 类似于 CASE 的特殊形式
- - '###'
  - 嵌套的 CASE 表达式
- - '##'
  - 总结
- - '###'
  - 别名
- - '###'
  - NULL 值
- - '###'
  - 类型转换
- - '###'
  - 数字计算
- - '###'
  - 字符串计算
- - '###'
  - 日期计算
- - '###'
  - CASE 表达式
- - '##'
  - 后续内容
- - '#'
  - 5. 汇总数据
- - '##'
  - 基本聚合函数
- - '###'
  - '`NULL`'
- - '##'
  - 理解聚合
- - '##'
  - 聚合部分值
- - '###'
  - 唯一值
- - '###'
  - 聚合筛选器
- - '##'
  - 按计算值分组
- - '###'
  - 使用 CASE 语句进行分组
- - '###'
  - 重新审视配送状态
- - '##'
  - 按任意字符串排序
- - '##'
  - 字符串拼接
- - '##'
  - 使用分组集汇总总计
- - '##'
  - 准备用于汇总的数据
- - '##'
  - 使用 UNION 子句组合汇总结果
- - '###'
  - 使用 GROUPING SETS、CUBE 和 ROLLUP
- - '####'
  - GROUPING SETS 和 CUBE（PostgreSQL、MSSQL 和 Oracle）
- - '####'
  - 使用 ROLLUP（PostgreSQL、MSSQL、Oracle 和 MariaDB/MySQL）
- - '##'
  - 概述
- - '###'
  - 排序结果
- - '###'
  - 在 Oracle 中重命名值
- - '###'
  - 直方图、平均值、众数和中位数
- - '###'
  - 计算均值
- - '###'
  - 生成频率表
- - '###'
  - 计算众数
- - '###'
  - 计算中位数
- - '###'
  - 标准差
- - '##'
  - 总结
- - '###'
  - 基本聚合函数
- - '###'
  - NULL 值
- - '###'
  - 聚合过程
- - '###'
  - 聚合过滤器
- - '###'
  - GROUP BY
- - '###'
  - 混合小计
- - '###'
  - 统计
- - '##'
  - 后续内容
- - '#'
  - 6. 使用视图及其相关对象
- - '##'
  - 处理视图
- - '###'
  - 创建视图
- - '###'
  - 在 MSSQL 中使用 ORDER BY
- - '###'
  - 使用视图的技巧
- - '####'
  - 不要过度级联视图
- - '####'
  - 不要使用 SELECT *
- - '####'
  - 避免使用 ORDER BY
- - '###'
  - 表值函数
- - '####'
  - PostgreSQL 中的 TVF
- - '####'
  - Microsoft SQL 中的 TVF
- - '###'
  - 你能用视图做什么？
- - '####'
  - 便捷性
- - '####'
  - 视图的多种用途
- - '##'
  - 作为接口
- - '##'
  - 与外部应用程序协作
- - '##'
  - 缓存数据与临时表
- - '###'
  - 为何要使用临时表？
- - '##'
  - 计算列
- - '##'
  - 总结
- - '###'
  - 视图
- - '###'
  - 表值函数
- - '###'
  - 临时表
- - '####'
  - 计算列
- - '##'
  - 即将介绍
- - '#'
  - 7. 使用子查询与公共表表达式
- - '##'
  - 关联与非关联子查询
- - '##'
  - SELECT 子句中的子查询
- - '##'
  - WHERE 子句中的子查询
- - '###'
  - 带简单聚合的子查询
- - '####'
  - 大额消费者
- - '####'
  - 最后订单
- - '####'
  - 重复的客户
- - '##'
  - FROM 子句中的子查询
- - '###'
  - 嵌套子查询
- - '##'
  - 使用 WHERE EXISTS (子查询)
- - '####'
  - WHERE EXISTS 与非关联子查询
- - '####'
  - WHERE EXISTS 与关联子查询
- - '####'
  - WHERE EXISTS 与 IN() 表达式的对比
- - '##'
  - LATERAL 连接（又称 CROSS APPLY）及其相关功能
- - '###'
  - 添加列
- - '##'
  - 使用公用表表达式
- - '###'
  - 多列查询
- - '###'
  - 语法
- - '####'
  - 使用公用表表达式（CTE）准备计算
- - '##'
  - 总结
- - '###'
  - 关联与非关联子查询
- - '###'
  - WHERE EXISTS 表达式
- - '###'
  - LATERAL 连接（亦称 CROSS APPLY）
- - '###'
  - 公用表表达式
- - '##'
  - 后续内容
- - '#'
  - 8. 窗口函数
- - '##'
  - 编写窗口函数
- - '###'
  - 简单的聚合窗口
- - '####'
  - 聚合函数
- - '####'
  - 聚合窗口函数和 ORDER BY
- - '##'
  - 帧子句
- - '###'
  - 帧边界
- - '####'
  - 创建每日销售视图
- - '####'
  - 滑动窗口
- - '####'
  - 窗口函数小计
- - '###'
  - 按多列进行 `PARTITION BY`
- - '##'
  - 排名函数
- - '###'
  - 基本排名函数
- - '###'
  - 使用 PARTITION BY 进行排名
- - '####'
  - 分页结果
- - '####'
  - 使用 ntile
- - '####'
  - 针对 `ntile` 的一个变通方案
- - '##'
  - 处理前后行数据
- - '##'
  - 总结
- - '###'
  - 窗口子句
- - '##'
  - 后续内容
- - '#'
  - 9. 关于公共表表达式的更多内容
- - '##'
  - 将 CTE 用作变量
- - '###'
  - 设置硬编码常量
- - '###'
  - 派生常量
- - '###'
  - 在 CTE 中使用聚合
- - '####'
  - 查找每个客户最近的销售记录
- - '####'
  - 查找同名的客户
- - '##'
  - CTE 参数名称
- - '##'
  - 使用多个公用表表达式
- - '###'
  - 使用多个 CTE 汇总重复姓名
- - '##'
  - 递归 CTE
- - '###'
  - 生成序列
- - '###'
  - 连接序列 CTE 以获取缺失值
- - '###'
  - 包含缺失日期的每日对比
- - '###'
  - 遍历层次结构
- - '####'
  - 获取单层层次结构
- - '###'
  - 使用递归 CTE 实现多级层级结构
- - '###'
  - 清理列表末尾的多余字符
- - '##'
  - 处理表字面量
- - '###'
  - 使用表字面量进行测试
- - '###'
  - 使用表字面量进行排序
- - '####'
  - 使用工作日名称重新定义 data CTE
- - '####'
  - 按工作日名称分组
- - '####'
  - 创建用于工作日的表字面量
- - '####'
  - 连接并按序列号排序
- - '###'
  - 使用表字面量作为查找表
- - '####'
  - 创建包含状态名称的 CTE
- - '####'
  - 将 CTE 连接到 customers 和 vip 表
- - '##'
  - 字符串分割技术详解
- - '###'
  - 分割字符串
- - '###'
  - 拆分更复杂的数据
- - '##'
  - 总结
- - '###'
  - 简单的 CTE
- - '###'
  - 参数名称
- - '###'
  - 多个 CTE
- - '###'
  - 递归 CTE
- - '##'
  - 后续内容
- - '#'
  - 10. 更多技术：触发器、数据透视表和变量
- - '##'
  - 理解触发器
- - '###'
  - 触发器的一些基础知识
- - '###'
  - 准备待归档的数据
- - '###'
  - 创建触发器
- - '####'
  - PostgreSQL 触发器
- - '####'
  - MySQL/MariaDB 触发器
- - '####'
  - MSSQL 触发器
- - '####'
  - SQLite 触发器
- - '####'
  - Oracle 触发器
- - '###'
  - 触发器的优缺点
- - '##'
  - 数据透视
- - '###'
  - 透视数据
- - '###'
  - 手动进行数据透视
- - '###'
  - 使用透视功能（MSSQL, Oracle）
- - '###'
  - 反透视功能
- - '##'
  - 使用 SQL 变量
- - '###'
  - 代码块
- - '###'
  - 更新后用于添加销售的代码
- - '###'
  - 在 PostgreSQL 中使用变量
- - '###'
  - 在 MariaDB/MySQL 中使用变量
- - '###'
  - 在 MSSQL 中使用变量
- - '###'
  - 在 Oracle 中使用变量
- - '##'
  - 回顾
- - '###'
  - 触发器
- - '###'
  - 数据透视表
- - '###'
  - SQL 变量
- - '#'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
- - '##'
  - 脚注
