name: Practical Oracle SQL
name_cn: Oracle SQL 实践指南
slug: practical-oracle-sql
toc:
- - '#'
  - 引言
- - '##'
  - 本书内容
- - '###'
  - 第 1 部分：核心 SQL
- - '###'
  - 第 2 部分：分析函数
- - '###'
  - 第 3 部分：行模式匹配
- - '##'
  - 关于代码
- - '###'
  - 源文件
- - '###'
  - 模式
- - '###'
  - 版本与环境
- - '##'
  - 最后的话
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '#'
  - 第一部分：核心 SQL
- - '##'
  - 1. 关联内联视图
- - '###'
  - 啤酒厂产品与销售
- - '###'
  - 标量子查询与多列
- - '###'
  - 分析与使用分析函数
- - '###'
  - 关联内联视图
- - '####'
  - 关联内联视图的外连接
- - '###'
  - 经验教训
- - '##'
  - 2. 集合操作中的陷阱
- - '###'
  - 啤酒集合
- - '###'
  - 集合操作符
- - '###'
  - 集合并置
- - '###'
  - 三种集合操作符
- - '###'
  - 多重集操作符
- - '####'
  - 多重集联合
- - '####'
  - 多重集交集
- - '#####'
  - 多重集差集
- - '###'
  - 减法运算符与多重集差集
- - '###'
  - 经验教训
- - '##'
  - 3. 使用子查询分解进行分而治之
- - '###'
  - 产品和销售数据
- - '###'
  - 低度啤酒的畅销年份
- - '###'
  - 使用 WITH 子句实现模块化
- - '####'
  - 同一子查询的多次使用
- - '####'
  - 图 3-2
- - '####'
  - 列出列名
- - '###'
  - 经验教训
- - '##'
  - 4. 使用递归进行树形计算
- - '###'
  - 托盘上的箱中瓶
- - '####'
  - 清单 4-1
- - '###'
  - 乘法层级数量
- - '####'
  - 递归子查询因子
- - '###'
  - 使用递归子查询实现层次查询
- - '####'
  - 代码清单 4-4
- - '#####'
  - 在递归子查询因子化中查找叶节点
- - '####'
  - 代码清单 4-5
- - '#####'
  - 对包装组合进行分组汇总
- - '#####'
  - PL/SQL 函数中的动态 SQL
- - '###'
  - 经验教训
- - '##'
  - 5. 在 SQL 中定义的函数
- - '###'
  - 包含啤酒酒精数据的表格
- - '###'
  - 啤酒酒精浓度
- - '###'
  - 威德马克公式
- - '###'
  - 使用 PRAGMA UDF 的函数
- - '###'
  - 在 `WITH` 子句中使用函数
- - '####'
  - 封装在视图中
- - '###'
  - 经验教训
- - '##'
  - 6. 使用多维数据进行迭代计算
- - '###'
  - 康威的生命游戏
- - '###'
  - 使用 MODEL 子句计算活跃邻居数
- - '###'
  - 迭代世代
- - '###'
  - 康威生命游戏与 SQL MODEL 子句
- - '###'
  - 经验总结
- - '##'
  - 7. 将列转为行
- - '###'
  - 以列形式接收的数据
- - '###'
  - 逆透视为行
- - '####'
  - 自己动手实现逆透视
- - '####'
  - 多个维度和/或多个度量
- - '###'
  - 维度与度量的组合
- - '####'
  - 单维度多度量
- - '####'
  - 简化维度信息
- - '####'
  - 手动聚合数据
- - '####'
  - 多维度单度量
- - '####'
  - 多维多度量与总结
- - '####'
  - 使用维度表
- - '#####'
  - 动态映射到维度表
- - '###'
  - 经验教训
- - '##'
  - 8. 将行透视为列
- - '###'
  - 用于透视的表
- - '###'
  - 单度量与单维度的行转列操作
- - '####'
  - 基本的行转列操作
- - '####'
  - 手动实现行转列
- - '###'
  - 多度量值
- - '####'
  - 同样使用多维度
- - '###'
  - 经验总结
- - '##'
  - 9. 分割定界符文本
- - '###'
  - 客户偏好与评论
- - '###'
  - 定界符分隔的单个值
- - '####'
  - 管道化表函数
- - '####'
  - 内置 APEX 表函数
- - '####'
  - 使用行生成器进行直接 SQL 查询
- - '####'
  - 将字符串视为 JSON 数组
- - '###'
  - 分隔的多值
- - '####'
  - 自定义 ODCI 表函数
- - '####'
  - 注意
- - '####'
  - 使用 ODCI 表函数
- - '###'
  - 结论
- - '####'
  - 结合使用 `apex_string.split` 与 `substr`
- - '####'
  - 行生成器与 `regexp_substr`
- - '####'
  - 转换为 JSON 格式
- - '###'
  - 经验总结
- - '##'
  - 10. 创建分隔符文本
- - '###'
  - 产品分隔列表
- - '###'
  - 字符串聚合
- - '####'
  - 聚合函数 LISTAGG
- - '####'
  - 聚合函数 COLLECT
- - '###'
  - 自定义聚合函数 STRAGG
- - '####'
  - 注意事项
- - '####'
  - 注意
- - '###'
  - 聚合函数 XMLAGG
- - '###'
  - 当结果不适合 VARCHAR2 时
- - '####'
  - 仅获取结果的第一部分
- - '####'
  - 尝试通过减少数据来使其适应
- - '####'
  - 使用 CLOB 代替 VARCHAR2
- - '###'
  - 经验教训
- - '#'
  - 第二部分：分析函数
- - '##'
  - 第 11 章 分析分区、排序与窗口
- - '###'
  - 数量求和示例
- - '###'
  - 分析函数语法
- - '###'
  - 分区
- - '###'
  - 排序与窗口
- - '###'
  - 窗口子句的灵活性
- - '###'
  - 基于值范围的窗口
- - '###'
  - 默认窗口的危险性
- - '###'
  - 经验教训
- - '##'
  - 12. 回答 Top-N 问题
- - '###'
  - 销售数据的 Top-N
- - '####'
  - 你指的是哪种 Top-3？
- - '###'
  - 啤酒销售数据
- - '###'
  - 传统的 ROWNUM 方法
- - '###'
  - 用于排名的分析函数
- - '###'
  - 仅获取首行
- - '####'
  - 并列情况的处理
- - '####'
  - 行限制子句不能做什么
- - '###'
  - 多分区中的 Top-N 查询
- - '####'
  - 行限制子句的 LATERAL 技巧
- - '###'
  - 经验总结
- - '##'
  - 第 13 章 带滚动求和的有序子集
- - '###'
  - 货物拣选数据
- - '###'
  - 构建拣货 SQL 语句
- - '####'
  - 通过 FIFO 解决拣选一个订单的问题
- - '####'
  - 问题描述
- - '####'
  - 解决方案原理
- - '###'
  - 拣货原则的轻松切换
- - '###'
  - 解决最优拣货路线
- - '###'
  - 解决批量拣货问题
- - '####'
  - 清单 13-10
- - '####'
  - 清单 13-11
- - '####'
  - 清单 13-12
- - '####'
  - 完成完整的拣货 SQL
- - '###'
  - 经验教训
- - '##'
  - 14. 使用 LEAD 分析活动日志
- - '###'
  - 拣货活动日志
- - '###'
  - 分析出发与到达
- - '###'
  - 分析拣货活动
- - '###'
  - SQL 查询优化：识别与分析拣货周期
- - '###'
  - 完整拣货周期分析
- - '##'
  - 第 15 章 使用线性回归进行预测
- - '###'
  - 预热：行模式匹配
- - '###'
  - 经验总结
- - '###'
  - 销售预测
- - '###'
  - 时间序列
- - '###'
  - 计算回归基础
- - '###'
  - 处理零值与避免错误
- - '###'
  - 计算季节性因子
- - '###'
  - 反季节化销售数据
- - '###'
  - 线性回归
- - '###'
  - 最终预测
- - '####'
  - 经验教训
- - '##'
  - 16. 使用滚动求和预测最低库存达到时间
- - '###'
  - 库存、预算与订单
- - '####'
  - 数据
- - '###'
  - 累计至零
- - '###'
  - 达到最低库存时补货
- - '###'
  - 经验教训
- - '#'
  - 第三部分 行模式匹配
- - '##'
  - 17. 升降模式
- - '###'
  - 股票代码示例
- - '###'
  - 分类下降和上升
- - '###'
  - 数据模式匹配与分类优化
- - '###'
  - 初始问题：价格不变行的分类歧义
- - '###'
  - 处理首行：添加 `strt` 分类
- - '###'
  - 分类器顺序的重要性
- - '###'
  - 下跌 + 上涨 = V 形
- - '####'
  - 重新思考是否需要 `SAME` 定义
- - '###'
  - V + V = W 形态
- - '##'
  - 18. 通过模式对数据进行分组
- - '###'
  - 重叠的 W 形状
- - '###'
  - 经验教训
- - '###'
  - 两组用于分组的数据
- - '###'
  - 三种分组条件
- - '####'
  - 对连续数据进行分组
- - '####'
  - 解析式 Tabibitosan 方法与 MATCH_RECOGNIZE 对比
- - '####'
  - 连续日期而非整数
- - '#####'
  - 间隔检测
- - '#####'
  - 按间隔分组直至间隔过大
- - '#####'
  - 按固定时限分组
- - '###'
  - 经验总结
- - '##'
  - 19. 合并日期范围
- - '###'
  - 工作任职周期
- - '####'
  - 时间有效性
- - '###'
  - 合并重叠范围
- - '####'
  - 与上一行进行比较的尝试
- - '####'
  - 更好地与最大结束日期进行比较
- - '###'
  - 理解 MATCH_RECOGNIZE 子句
- - '####'
  - 处理空日期值
- - '###'
  - 经验教训
- - '##'
  - 20. 寻找异常峰值
- - '###'
  - 网页计数器历史
- - '###'
  - 计数器数据
- - '####'
  - 原始计数器数据中的模式
- - '###'
  - 查看每日访问量
- - '###'
  - 日常访问量数据中的模式
- - '##'
  - 第 21 章 装箱匹配
- - '###'
  - 更复杂的模式
- - '###'
  - 经验总结
- - '###'
  - 需要装箱的库存清单
- - '###'
  - 无限数量、容量有限的箱子进行箱装拟合
- - '####'
  - 展示箱柜容量过小的情况
- - '###'
  - 使用容量无限的限定数量箱子进行装箱
- - '####'
  - 使用模式匹配实现
- - '####'
  - 查询解释
- - '####'
  - 查询输出
- - '###'
  - 经验总结
- - '##'
  - 22. 在树中统计子节点数量
- - '###'
  - 员工层级树
- - '###'
  - 统计所有级别的下属
- - '####'
  - 使用行模式匹配进行计数
- - '####'
  - 每次匹配的细节
- - '###'
  - 调整输出
- - '###'
  - 经验总结
- - '#'
  - 附录
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N, O
- - '##'
  - P
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U, V
- - '##'
  - W, X, Y, Z
