name: Pro Oracle SQL Development
name_cn: Oracle SQL 开发高级指南
slug: pro-oracle-sql-development
toc:
- - '#'
  - 引言
- - '##'
  - 为何要更深入地学习 Oracle SQL？
- - '##'
  - 目标读者
- - '##'
  - 书籍结构
- - '##'
  - 示例模式
- - '##'
  - 运行示例
- - '##'
  - 致谢
- - '##'
  - 关于作者 关于技术审校者
- - '#'
  - 第一部分：学会如何学习
- - '#'
  - 第1章 理解关系数据库
- - '##'
  - 关于关系数据库的历史
- - '##'
  - 关系模型及其重要性
- - '###'
  - 历史
- - '###'
  - 术语
- - '###'
  - 关系模型
- - '####'
  - 简洁性
- - '####'
  - 集合与表
- - '####'
  - 实现关系模型的问题
- - '####'
  - 关系模型及其为何无关紧要
- - '####'
  - NULL 问题不是问题
- - '####'
  - 列的顺序至关重要
- - '####'
  - 反规范化
- - '####'
  - 所有行都是唯一的
- - '##'
  - SQL 编程语言
- - '###'
  - 历史与术语
- - '###'
  - SQL 的替代方案
- - '###'
  - SQL 是编程语言吗？
- - '##'
  - 不同的数据库类型
- - '###'
  - 替代性数据库模型
- - '###'
  - 不同的 Oracle 数据库（OLTP 与 DW）
- - '##'
  - 关键概念
- - '###'
  - 'NULL'
- - '###'
  - JOIN
- - '####'
  - 连接可视化
- - '####'
  - 内连接
- - '####'
  - 左外连接与右外连接
- - '####'
  - 全外连接
- - '####'
  - 交叉连接
- - '####'
  - 总结
- - '#'
  - 第2章 创建高效的数据库开发流程
- - '##'
  - 共享数据库与私有数据库
- - '##'
  - 创建无限数量的数据库
- - '###'
  - 私有数据库的优势
- - '##'
  - 性能
- - '##'
  - 许可
- - '##'
  - 初始设置更简单
- - '###'
  - 创建私有数据库：本地安装
- - '###'
  - 创建私有数据库：其他选项
- - '##'
  - 快速删除并重建模式
- - '###'
  - 为何要频繁部署？
- - '###'
  - 如何频繁部署？
- - '###'
  - SQL*Plus 安装脚本
- - '####'
  - 注释
- - '####'
  - SQL*Plus 设置和消息
- - '####'
  - 检查先决条件
- - '####'
  - 删除旧的模式
- - '####'
  - 对象类型的脚本
- - '####'
  - 向角色授权
- - '####'
  - 验证模式
- - '###'
  - SQL*Plus 补丁脚本
- - '##'
  - 用版本控制的文本文件控制模式
- - '###'
  - 唯一可信来源
- - '###'
  - 从仓库和文件系统加载对象
- - '###'
  - 手动创建与保存变更
- - '##'
  - 赋能每个人
- - '###'
  - 权力失衡
- - '###'
  - 透明度
- - '###'
  - 降低入门门槛
- - '##'
  - 总结
- - '#'
  - 第3章 通过测试增强信心与知识
- - '##'
  - 通过自动化测试建立信心
- - '###'
  - 更快地修复错误
- - '###'
  - 获得信心并避免偏见
- - '###'
  - 测试驱动开发
- - '###'
  - 创建有用的测试数据
- - '###'
  - 创建大型测试数据
- - '###'
  - 清理测试数据
- - '###'
  - 如何构建自动化测试
- - '##'
  - 用最小、完整且可验证的示例构建知识
- - '###'
  - 为什么要花这么多时间构建可复现的测试用例？
- - '###'
  - 极简
- - '###'
  - 完整
- - '###'
  - 可验证
- - '##'
  - 共享测试
- - '##'
  - 避免 XY 问题
- - '##'
  - Oracle 性能测试
- - '##'
  - Oracle 侦探工具包
- - '##'
  - 数据字典视图
- - '##'
  - 动态性能视图
- - '###'
  - 用于检查数据库的关系型工具
- - '###'
  - 用于检查数据库的非关系型工具
- - '##'
  - 总结
- - '#'
  - 第4章 寻找可靠的来源
- - '##'
  - 去哪里找
- - '###'
  - 论坛的问题
- - '###'
  - 静态网站的问题
- - '###'
  - 阅读手册
- - '###'
  - 文档的局限性与价值
- - '###'
  - 文档的不足之处
- - '###'
  - 文档详尽性的利与弊
- - '###'
  - My Oracle Support
- - '####'
  - 资源介绍与访问方式
- - '####'
  - 重要工具：错误代码查询
- - '####'
  - 文档质量与服务请求
- - '##'
  - 可咨询的人员
- - '##'
  - 总结
- - '#'
  - 第5章 掌握整个技术栈
- - '##'
  - 不仅仅是更快
- - '##'
  - 输入
- - '##'
  - 操作系统与支持程序
- - '###'
  - 操作系统
- - '###'
  - 文本编辑器
- - '###'
  - 比较工具
- - '###'
  - 报表工具与 Excel
- - '##'
  - SQL 与 PL/SQL
- - '##'
  - SQL*Plus
- - '###'
  - 何时应使用 SQL*Plus
- - '##'
  - 集成开发环境
- - '###'
  - 何时不应使用 SQL*Plus
- - '###'
  - 学习一个 IDE
- - '###'
  - 何时不使用 IDE 功能
- - '##'
  - Oracle IDE 对比
- - '##'
  - 工作表、笔记本、代码片段、脚本和 Gist
- - '###'
  - 保持条理
- - '##'
  - 工作表
- - '##'
  - 总结
- - '#'
  - 第二部分 使用集合和高级功能编写强大的 SQL
- - '#'
  - 第6章 使用内联视图和 ANSI 连接语法构建集合
- - '##'
  - 非标准语法导致的面条代码
- - '##'
  - 难以阅读的旧语法
- - '##'
  - 难以调试的旧语法
- - '##'
  - 旧语法中意外的交叉连接
- - '##'
  - 非标准但仍有用
- - '##'
  - 过多的上下文
- - '###'
  - 减少上下文的重要性
- - '###'
  - 避免关联子查询
- - '###'
  - 避免公用表表达式
- - '##'
  - 集合、分块和函数式编程来救援
- - '###'
  - 集合
- - '###'
  - 分块
- - '###'
  - 函数式编程
- - '###'
  - 内联视图
- - '###'
  - 何为内联视图？
- - '###'
  - 内联视图使代码更庞大但也更简单
- - '###'
  - 一个大型示例中的简单内联视图
- - '###'
  - ANSI 连接
- - '##'
  - 示例
- - '##'
  - 总结
- - '#'
  - 第7章 使用高级 SELECT 功能查询数据库
- - '##'
  - 运算符、函数、表达式和条件
- - '###'
  - 语义
- - '##'
  - 如何发现我们遗漏了什么
- - '##'
  - 优先级规则
- - '##'
  - 简化
- - '##'
  - CASE 和 DECODE
- - '##'
  - 连接
- - '###'
  - 分区外连接
- - '###'
  - LATERAL、CROSS APPLY 和 OUTER APPLY
- - '###'
  - 等值连接或非等值连接
- - '###'
  - 半连接或反连接
- - '###'
  - 自连接
- - '###'
  - 自然连接与 USING 子句之弊端
- - '##'
  - 排序
- - '###'
  - 排序语法
- - '###'
  - 排序性能、资源与隐式排序
- - '##'
  - 集合操作符
- - '###'
  - UNION 和 UNION ALL
- - '###'
  - INTERSECT 和 MINUS
- - '###'
  - 集合操作符的复杂性
- - '##'
  - 高级分组
- - '###'
  - ROLLUP, GROUPING SETS, CUBE
- - '###'
  - LISTAGG
- - '###'
  - 高级聚合函数
- - '##'
  - 分析函数
- - '###'
  - 分析函数语法
- - '###'
  - 分析函数示例
- - '##'
  - 正则表达式
- - '###'
  - 正则表达式语法
- - '###'
  - 正则表达式示例
- - '###'
  - 正则表达式的局限性
- - '##'
  - 行限制
- - '###'
  - 行限制子句
- - '###'
  - ROWNUM
- - '###'
  - 分析函数行限制
- - '##'
  - 透视与逆透视
- - '###'
  - 旧式透视语法
- - '###'
  - 新的 PIVOT 语法
- - '###'
  - UNPIVOT
- - '###'
  - 闪回
- - '###'
  - 抽样
- - '###'
  - 分区扩展子句
- - '##'
  - 公共表表达式
- - '###'
  - 示例
- - '###'
  - PL/SQL 公共表表达式
- - '###'
  - 性能与过度使用
- - '##'
  - 递归查询
- - '###'
  - CONNECT BY 语法
- - '###'
  - 递归公用表表达式
- - '##'
  - XML
- - '###'
  - XMLType
- - '###'
  - DBMS_XMLGEN 与创建 XML
- - '###'
  - XMLTABLE
- - '###'
  - XML 编程语言
- - '##'
  - JSON
- - '###'
  - 在数据库中存储 JSON
- - '###'
  - 创建 JSON 数据
- - '###'
  - 查询 JSON
- - '##'
  - 国家语言支持
- - '###'
  - 字符集
- - '###'
  - 长度语义
- - '###'
  - NLS 比较与排序
- - '###'
  - 显示格式
- - '##'
  - 本章小结
- - '#'
  - 第8章 使用高级 DML 修改数据
- - '##'
  - INSERT
- - '##'
  - 更新（UPDATE）
- - '##'
  - 删除（DELETE）
- - '##'
  - 合并
- - '##'
  - 可更新视图
- - '##'
  - DML 提示
- - '###'
  - 提示概述
- - '###'
  - 特定提示说明
- - '###'
  - 错误日志记录
- - '##'
  - 返回子句
- - '##'
  - TRUNCATE
- - '##'
  - COMMIT、ROLLBACK 与 SAVEPOINT
- - '###'
  - 事务的基本概念
- - '###'
  - 事务的开始与结束
- - '###'
  - COMMIT 的行为与注意事项
- - '###'
  - ROLLBACK 的行为与性能
- - '###'
  - ROLLBACK 进度的估算
- - '###'
  - COMMIT 的选项与风险
- - '##'
  - ALTER SYSTEM（系统级更改）
- - '###'
  - 清理内存结构
- - '###'
  - 使用 PL/SQL 授予精准权限
- - '##'
  - ALTER SESSION（会话级更改）
- - '###'
  - 会话级参数设置
- - '###'
  - 其他会话参数示例
- - '##'
  - 输入与输出
- - '###'
  - 1. 导入/导出数据泵（`impdp`、`expdp`、`DBMS_DATAPUMP`）
- - '###'
  - 2. 传统导入/导出（`imp`、`exp`）
- - '###'
  - 3. 数据库链接
- - '###'
  - 4. SQL*Plus COPY
- - '###'
  - 5. 可传输表空间
- - '###'
  - 1. `UTL_FILE`
- - '###'
  - 2. SQL*Loader
- - '###'
  - 3. 外部表
- - '###'
  - 4. `DBMS_XSLPROCESSOR`
- - '###'
  - 5. SQL*Plus 脚本
- - '###'
  - 6. Oracle SQL Developer、SQL CL 或其他第三方工具
- - '##'
  - 实用的 PL/SQL 包
- - '##'
  - 总结
- - '#'
  - 第9章 使用高级模式对象改进数据库
- - '##'
  - ALTER（更改）
- - '##'
  - Tables（表）
- - '###'
  - Table Types（表类型）
- - '##'
  - 分片表
- - '##'
  - 对象关系表
- - '##'
  - 外部表
- - '##'
  - 索引组织表
- - '##'
  - 不可变表和区块链表
- - '###'
  - 表属性
- - '###'
  - 基本表压缩
- - '###'
  - 并行
- - '###'
  - 延迟段创建
- - '##'
  - 物理属性子句与归档特性
- - '##'
  - 修改与删除表
- - '##'
  - 列类型与属性
- - '##'
  - 约束
- - '###'
  - 约束对性能的影响
- - '###'
  - 修改约束
- - '###'
  - 约束异常
- - '##'
  - NOVALIDATE 与并行约束
- - '##'
  - 其他约束
- - '##'
  - 索引
- - '###'
  - 索引概念
- - '###'
  - 索引特性
- - '###'
  - 重建索引
- - '##'
  - 分区
- - '###'
  - 分区概念
- - '##'
  - 分区特性
- - '##'
  - 视图
- - '###'
  - 创建视图
- - '###'
  - 扩展视图
- - '##'
  - 用户
- - '##'
  - 序列
- - '##'
  - 同义词
- - '##'
  - 物化视图
- - '###'
  - 针对多表约束的物化视图
- - '##'
  - 数据库链接
- - '##'
  - PL/SQL 对象
- - '##'
  - 其他模式对象
- - '##'
  - 全局对象
- - '##'
  - GRANT 和 REVOKE
- - '##'
  - 总结
- - '#'
  - 第10章 使用 Oracle 架构优化数据库
- - '##'
  - 存储结构
- - '###'
  - 列值
- - '###'
  - 行片断
- - '###'
  - 块与行级锁定
- - '###'
  - 区
- - '###'
  - 段
- - '###'
  - 数据文件
- - '###'
  - 表空间
- - '###'
  - 自动存储管理
- - '##'
  - 浪费的空间
- - '##'
  - 重做日志
- - '###'
  - 理论上的重做日志
- - '###'
  - 实践中的重做日志
- - '##'
  - 撤销与多版本读一致性
- - '###'
  - 用于回滚的撤销
- - '###'
  - 用于多版本一致性的撤销
- - '##'
  - 临时表空间
- - '##'
  - 内存
- - '##'
  - 缓存
- - '##'
  - 多租户
- - '##'
  - 数据库类型
- - '##'
  - 总结
- - '#'
  - 第三部分 使用模式和风格编写优雅的 SQL
- - '#'
  - 第11章 停止编码，开始写作
- - '##'
  - 示例的虚伪性
- - '##'
  - 注释
- - '###'
  - 注释风格
- - '###'
  - 注释机制
- - '###'
  - 注释 ASCII 艺术
- - '##'
  - 选择好名称
- - '###'
  - 命名风格
- - '##'
  - 避免使用带引号的标识符
- - '##'
  - 名称长度与变更
- - '##'
  - 空白符
- - '##'
  - 让 Bug 显而易见
- - '###'
  - 快速失败
- - '###'
  - 避免宝可梦式异常处理
- - '###'
  - 使用糟糕的命名和奇怪的数值
- - '###'
  - 使用脆弱的 SQL
- - '##'
  - 编写优秀 SQL 的途径
- - '##'
  - 总结
- - '#'
  - 第12章 编写大型 SQL 语句
- - '##'
  - 命令式编程的规模限制不适用
- - '##'
  - 一个大的 SQL 语句对比多个小的 SQL 语句
- - '##'
  - 大型 SQL 语句的性能风险
- - '###'
  - 大型 SQL 解析问题
- - '###'
  - 大型 SQL 会增加优化器风险
- - '###'
  - 大型 SQL 资源消耗问题
- - '##'
  - 大型 SQL 语句的性能优势
- - '###'
  - 大型 SQL 提高清晰度
- - '##'
  - Oracle 优化：编写大型 SQL 语句的优势
- - '###'
  - 大型 SQL 为优化器提供更多机会
- - '###'
  - 大型 SQL 减少输入/输出
- - '###'
  - 大型 SQL 减少上下文切换
- - '###'
  - 大 SQL 语句提升并行度
- - '##'
  - 阅读和调试大型 SQL 语句
- - '###'
  - 由内向外
- - '###'
  - 浏览内联视图
- - '##'
  - 总结
- - '#'
  - 第13章 编写优美的 SQL 语句
- - '##'
  - 如何衡量代码复杂度
- - '##'
  - 避免不必要的别名
- - '##'
  - 前缀和后缀
- - '###'
  - SQL 对象和列名
- - '###'
  - PL/SQL 变量名
- - '###'
  - 引用表和列
- - '##'
  - 避免使用缩写
- - '##'
  - 使用制表符实现左对齐
- - '##'
  - 避免依赖代码格式化工具
- - '##'
  - 小写字母
- - '##'
  - 总结
- - '#'
  - 第14章 更多地结合基础动态 SQL 使用 SQL
- - '##'
  - 何时使用动态 SQL
- - '###'
  - 运行动态数据定义语言
- - '###'
  - 运行时才确定
- - '####'
  - 动态统计行数
- - '####'
  - 动态 WHERE 子句
- - '###'
  - 简化权限
- - '###'
  - 规则引擎
- - '##'
  - 何时不应使用动态 SQL
- - '##'
  - 基本特性
- - '##'
  - 为性能和安全使用绑定变量
- - '##'
  - 如何简化字符串拼接
- - '###'
  - 多行字符串
- - '##'
  - 替代引号机制
- - '##'
  - 模板化
- - '##'
  - 代码生成，而非通用代码
- - '##'
  - 概要
- - '#'
  - 第15章 避免反模式
- - '##'
  - 避免第二系统综合症和从头重写
- - '##'
  - 避免强类型化实体-属性-值模型
- - '###'
  - EAV 的优缺点
- - '###'
  - 表 15-1
- - '##'
  - 切勿使用错误的类型
- - '###'
  - Oracle SQL 中的隐蔽转换错误
- - '##'
  - 避免软编码
- - '##'
  - 避免对象关系表
- - '##'
  - 避免在数据库中使用 Java
- - '###'
  - Java 并非总是可用
- - '###'
  - Java 并非完美契合
- - '###'
  - SQL 与 PL/SQL 几乎总是更佳选择
- - '##'
  - 避免使用 `TO_DATE`
- - '###'
  - 避免字符串到日期的转换
- - '###'
  - 使用 `DATE`、`TIMESTAMP` 和 `INTERVAL` 字面量
- - '##'
  - 避免使用 `CURSOR`
- - '##'
  - 避免自定义 SQL 解析
- - '##'
  - 避免自动化一切
- - '##'
  - 避免 Cargo Cult 编程语法
- - '##'
  - 避免使用未文档化的功能
- - '##'
  - 避免使用已弃用的功能
- - '##'
  - 避免对通用错误进行简单化解释
- - '###'
  - 已终止进程
- - '###'
  - 死锁
- - '###'
  - 错误堆栈顶部
- - '###'
  - 避免设置过小的参数
- - '##'
  - 避免将规划与过早优化混为一谈
- - '##'
  - 其他章节讨论的反模式
- - '##'
  - 总结
- - '#'
  - 第四部分 提升 SQL 性能
- - '#'
  - 第16章 通过算法分析理解 SQL 性能
- - '##'
  - 算法分析简介
- - '##'
  - O(1/N)：通过批处理减少开销
- - '##'
  - O(1)：哈希与其他操作
- - '###'
  - 哈希的工作原理
- - '##'
  - 哈希分区
- - '##'
  - 哈希集群
- - '###'
  - 哈希连接
- - '###'
  - 其他
- - '##'
  - O(LOG(N))：索引访问
- - '##'
  - 1/((1-P)+P/N)：阿姆达尔定律
- - '##'
  - O(N)：全表扫描及其他操作
- - '###'
  - O(N*LOG(N))：全表扫描 vs. 索引访问、排序、连接、全局 vs. 本地索引、收集统计信息
- - '###'
  - 全表扫描与索引访问
- - '###'
  - 排序
- - '###'
  - 连接操作
- - '###'
  - 全局索引与本地索引
- - '###'
  - 收集优化器统计信息
- - '###'
  - 基数估算的挑战
- - '###'
  - 使用哈希进行近似计数
- - '###'
  - 采样的陷阱
- - '###'
  - 分区的增量统计信息
- - '###'
  - 结论：统计信息是基础
- - '##'
  - O(N²)：交叉连接、嵌套循环及其他操作
- - '##'
  - O(N!)：连接顺序
- - '##'
  - O(∞)：优化器
- - '##'
  - 摘要
- - '#'
  - 第17章 理解 SQL 调优理论
- - '##'
  - 管理用户预期
- - '##'
  - 性能调优的思维方式
- - '###'
  - 性能调优不是调试
- - '###'
  - 有动机的故障排除
- - '###'
  - 不同的方法
- - '###'
  - 为什么不谈数据库调优？
- - '##'
  - 声明式编程（为何执行计划很重要）
- - '###'
  - 声明式编程的怪癖
- - '###'
  - 执行计划
- - '##'
  - 操作（可用的执行计划决策有哪些）
- - '###'
  - 操作详情
- - '###'
  - 执行计划与递归 SQL
- - '###'
  - 操作为何重要
- - '###'
  - 首次操作
- - '###'
  - 连接操作
- - '###'
  - 表访问
- - '###'
  - 索引访问
- - '###'
  - 分组与排序
- - '###'
  - 集合操作符
- - '###'
  - 优化器统计信息
- - '###'
  - 并行
- - '##'
  - 分区（Partition）
- - '##'
  - 过滤（Filter）
- - '###'
  - 其他
- - '##'
  - 基数与优化器统计信息（构建执行计划 I）
- - '###'
  - 基数至关重要
- - '###'
  - 基数差异
- - '###'
  - 成本无关紧要
- - '###'
  - 优化器统计信息
- - '###'
  - 优化器统计信息示例
- - '##'
  - 转换与动态优化（构建执行计划 II）
- - '###'
  - 转换
- - '###'
  - 常见的未命名转换
- - '###'
  - 特定的命名转换
- - '####'
  - 谓词下推
- - '####'
  - 视图合并
- - '####'
  - 子查询反嵌套
- - '####'
  - OR 扩展
- - '###'
  - 查看和补偿转换
- - '####'
  - 自适应游标共享与自适应统计信息
- - '####'
  - 自适应查询计划
- - '##'
  - 总结
- - '#'
  - 第18章 提高 SQL 性能
- - '##'
  - 应用调优：日志记录与分析
- - '##'
  - 日志记录
- - '##'
  - 性能分析：DBMS_PROFILER
- - '##'
  - 性能分析：DBMS_HPROF
- - '##'
  - 通过批处理进行应用调优
- - '###'
  - 安装和补丁脚本
- - '###'
  - OLTP 应用程序
- - '##'
  - 数据仓库
- - '##'
  - 数据库调优
- - '###'
  - 衡量数据库性能
- - '##'
  - 时间模型
- - '##'
  - 等待事件
- - '##'
  - 统计信息
- - '##'
  - 指标
- - '##'
  - 采样
- - '##'
  - 自动工作负载存储库 (AWR)
- - '##'
  - 活动会话历史 (ASH)
- - '###'
  - 自动数据库诊断监视器（ADDM）
- - '###'
  - 指导工具
- - '##'
  - 自动索引
- - '###'
  - 概述
- - '###'
  - 实施步骤
- - '###'
  - 问题与局限
- - '###'
  - 结论
- - '###'
  - 其他工具
- - '##'
  - SQL 调优：寻找慢速 SQL
- - '###'
  - 有条理地组织
- - '###'
  - “慢”是基于数据库时间（DB Time）
- - '###'
  - 查找当前正在运行的慢速 SQL
- - '###'
  - 查找历史慢速 SQL
- - '##'
  - SQL 调优：查找执行计划
- - '###'
  - 图形化执行计划的弊端
- - '###'
  - 文本方式最佳
- - '###'
  - DBMS_XPLAN 函数
- - '##'
  - DBMS_XPLAN FORMAT 参数
- - '##'
  - “Note” 部分
- - '##'
  - 其他获取执行计划的方式
- - '##'
  - SQL 调优：寻找操作的实际执行时间和基数
- - '###'
  - GATHER_PLAN_STATISTICS
- - '####'
  - 使用 GATHER_PLAN_STATISTICS 获取实际执行计划
- - '####'
  - 分析执行计划以定位问题
- - '##'
  - SQL 监控报告
- - '###'
  - 实时 SQL 监控报告（文本格式）
- - '###'
  - 实时 SQL 监控报告（活动格式）
- - '##'
  - 并行度
- - '##'
  - 执行计划中应关注什么
- - '##'
  - SQL 调优：改变执行计划
- - '###'
  - 更改执行计划
- - '###'
  - 提示
- - '##'
  - SQL 调优
- - '###'
  - SQL 配置文件示例
- - '##'
  - SQL 调优：收集优化器统计信息
- - '###'
  - 手动统计信息
- - '###'
  - 自动统计信息收集
- - '###'
  - 其他统计信息
- - '##'
  - 总结
- - '#'
  - 第19章 使用晦涩的 SQL 特性解决难题
- - '##'
  - Oracle 对比 Unix 哲学
- - '##'
  - MODEL 子句
- - '##'
  - 行模式匹配
- - '##'
  - ANY 类型
- - '##'
  - APEX
- - '##'
  - Oracle Text
- - '###'
  - 索引类型
- - '###'
  - 使用示例
- - '###'
  - 索引同步
- - '##'
  - 多语言引擎
- - '###'
  - 基本用法
- - '###'
  - 高精度计算示例
- - '##'
  - Spatial
- - '##'
  - Other Features
- - '###'
  - Machine Learning
- - '###'
  - OLAP
- - '###'
  - Property Graph
- - '###'
  - Virtual Private Database
- - '###'
  - Database In-Memory
- - '###'
  - Advanced Compression
- - '###'
  - 融合数据库与连接性
- - '##'
  - 总结
- - '#'
  - 第20章 更常使用高级动态 SQL
- - '##'
  - 解析
- - '###'
  - PL/Scope
- - '###'
  - PLSQL_LEXER
- - '##'
  - ANTLR
- - '##'
  - DBMS_SQL
- - '##'
  - DBMS_XMLGEN
- - '##'
  - PL/SQL 公共表表达式
- - '##'
  - 方法 4 动态 SQL
- - '##'
  - 多项式表函数
- - '##'
  - SQL 宏
- - '##'
  - 总结
- - '#'
  - 第21章 使用 PL/SQL 提升你的技能
- - '##'
  - 学习 PL/SQL 是否值得？
- - '##'
  - 创建 PL/SQL 练习场
- - '##'
  - PL/SQL 集成特性
- - '###'
  - 代码打包技巧
- - '###'
  - 会话数据
- - '###'
  - 事务 I：COMMIT、ROLLBACK 和 SAVEPOINT
- - '##'
  - 异常处理、事务与锁机制
- - '###'
  - 事务 II：隐式游标属性
- - '###'
  - 事务 III：行级锁
- - '###'
  - 事务 IV：隔离性与一致性
- - '###'
  - 简单变量
- - '###'
  - 游标
- - '###'
  - 记录
- - '###'
  - 集合
- - '##'
  - PL/SQL 集合与函数
- - '###'
  - 函数
- - '####'
  - 表函数
- - '####'
  - 管道函数
- - '####'
  - 并行管道函数
- - '####'
  - 用于 DML 和 DDL 的自主事务
- - '##'
  - 用于日志记录的自治事务
- - '##'
  - 定义者权限与调用者权限
- - '##'
  - 触发器
- - '###'
  - 事件子句
- - '###'
  - 时点
- - '###'
  - WHEN（条件）
- - '###'
  - 简单 DML 触发器
- - '##'
  - 审计触发器与其他 DML 触发器
- - '###'
  - 行级 AFTER 触发器
- - '###'
  - 用于多表约束的 AFTER STATEMENT 触发器
- - '###'
  - Instead-of DML 触发器
- - '###'
  - 复合 DML 触发器
- - '###'
  - 系统触发器
- - '###'
  - 模拟 On-Commit 触发器
- - '##'
  - PL/SQL 高级特性与职业发展
- - '###'
  - 条件编译
- - '###'
  - 其他 PL/SQL 特性
- - '###'
  - 开始教学与创造
- - '####'
  - 教导他人
- - '####'
  - 创建开源项目
- - '##'
  - 附录
- - '#'
  - 附录A SQL 风格指南速查表
- - '#'
  - 附录B 计算机科学主题
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y, Z
