name: Practical Database Auditing for Microsoft SQL Server and Azure SQL
name_cn: Microsoft SQL Server 和 Azure SQL 的数据库审计实用指南
slug: practical-database-auditing-for-microsoft-sql-server-and-azu
toc:
- - '#'
  - 针对 Microsoft SQL Server 和 Azure SQL 的实用数据库审计：故障排除、法规合规性与治理
- - '#'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审阅者
- - '##'
  - 致谢
- - '##'
  - 引言
- - '##'
  - 第一部分：审计入门
- - '###'
  - 第 1 章：审计为何重要
- - '####'
  - 为何需要审计？
- - '####'
  - 审计类型
- - '####'
  - 法规合规性类型
- - '####'
  - 什么是数据库审计？
- - '####'
  - 审计可解决的数据库问题
- - '###'
  - 第 2 章：数据库审计的类型
- - '####'
  - SQL Server 审计
- - '####'
  - 扩展事件
- - '####'
  - 跟踪 SQL Server 配置更改
- - '####'
  - 变更数据捕获
- - '####'
  - 变更跟踪
- - '####'
  - C2 审计与通用准则合规性
- - '####'
  - 时态表
- - '####'
  - 成功与失败的登录审计
- - '####'
  - 审计 Azure SQL 数据库
- - '####'
  - 审计 Azure SQL 托管实例
- - '####'
  - AWS 与 GCP 审计选项
- - '##'
  - 第二部分：实施审计
- - '###'
  - 第 3 章：什么是 SQL Server 审计？
- - '####'
  - SQL Server 审计的可用性
- - '####'
  - SQL Server 审计的要求
- - '####'
  - SQL Server 审计使用案例
- - '####'
  - 审计类别
- - '####'
  - 审计操作组
- - '#####'
  - 服务器审计操作组
- - '#####'
  - 数据库审计操作组
- - '####'
  - SQL Server 审计示例
- - '####'
  - 多重审计设置
- - '###'
  - 第 4 章：通过图形界面实现 SQL Server 审计
- - '####'
  - 设置审计
- - '####'
  - 设置服务器审计规范
- - '####'
  - 设置数据库审计规范
- - '####'
  - 添加多重审计
- - '####'
  - 查询审计日志
- - '#####'
  - SQL Server 审计中的可用列
- - '#####'
  - 筛选 SQL Server 审计
- - '####'
  - 删除审计
- - '####'
  - 禁用审计
- - '####'
  - 修改审计
- - '###'
  - 第 5 章：通过 SQL 脚本实现 SQL Server 审计
- - '####'
  - 编写现有规范的脚本
- - '####'
  - 设置审计
- - '####'
  - 设置服务器审计规范
- - '####'
  - 设置数据库审计规范
- - '####'
  - 查询系统视图
- - '####'
  - 添加多重审计
- - '####'
  - SQL Server 审计中的可用列
- - '####'
  - 查询审计日志
- - '####'
  - 筛选 SQL Server 审计
- - '####'
  - 删除审计
- - '####'
  - 禁用审计
- - '####'
  - 修改审计
- - '###'
  - 第 6 章：什么是扩展事件？
- - '####'
  - 扩展事件默认会话
- - '####'
  - 扩展事件组件
- - '####'
  - 扩展事件模板
- - '####'
  - 扩展事件事件库
- - '####'
  - 扩展事件全局字段和谓词
- - '####'
  - 扩展事件目标
- - '####'
  - 扩展事件高级设置
- - '####'
  - 扩展事件使用案例
- - '###'
  - 第 7 章：通过图形界面实现扩展事件
- - '####'
  - 通过“新建会话向导”选项设置扩展事件
- - '####'
  - 通过“新建会话”选项设置扩展事件
- - '###'
  - 第 8 章：通过 SQL 脚本实现扩展事件
- - '####'
  - 为现有扩展事件编写脚本
- - '####'
  - 设置扩展事件
- - '####'
  - 查询系统表和视图
- - '####'
  - 扩展事件文件
- - '####'
  - 查询扩展事件数据
- - '####'
  - 修改扩展事件
- - '####'
  - 停止和启动扩展事件
- - '####'
  - 删除扩展事件
- - '###'
  - 第 9 章：跟踪 SQL Server 配置更改
- - '####'
  - 在 SSMS 中查看配置变更历史
- - '####'
  - 在 SQL Server 日志中查询配置变更
- - '####'
  - 使用 SQL Server 审计捕获配置变更
- - '###'
  - 第 10 章：其他 SQL Server 审计与跟踪方法
- - '####'
  - 通用准则合规性
- - '####'
  - 变更跟踪
- - '####'
  - 变更数据捕获
- - '####'
  - 时态表
- - '#####'
  - 创建时态表
- - '#####'
  - 修改时态表中的数据
- - '#####'
  - 查询时态表
- - '####'
  - 成功与失败的登录审计
- - '#####'
  - 用于成功和失败登录审计的 SQL Server 审计
- - '#####'
  - 用于成功和失败登录审计的扩展事件
- - '####'
  - DDL 触发器
- - '##'
  - 第三部分：集中化与报告审核数据
- - '###'
  - 第 11 章：集中化审核数据
- - '####'
  - 在多台服务器上设置审计
- - '####'
  - 创建集中审计数据库和用户
- - '####'
  - 创建链接服务器
- - '####'
  - 用于收集和清理审计数据的 SQL Agent 作业
- - '###'
  - 第 12 章：从审核数据创建报告
- - '####'
  - 使用 SQL Server Agent 创建 HTML 报告
- - '####'
  - 使用 PowerShell 生成 HTML 报告
- - '##'
  - 第四部分：云端审核选项
- - '###'
  - 第 13 章：审核 Azure SQL 数据库
- - '####'
  - 通过门户审核 Azure SQL 数据库
- - '####'
  - 修改 Azure SQL 数据库审计设置
- - '####'
  - 获取和设置审计策略
- - '####'
  - 使用扩展事件审计 Azure SQL 数据库
- - '#####'
  - 创建存储账户和容器
- - '#####'
  - 创建数据库凭据
- - '#####'
  - 创建扩展事件
- - '#####'
  - 查询扩展事件
- - '####'
  - 集中与报告 Azure SQL 审核数据
- - '###'
  - 第 14 章：审核 Azure SQL 托管实例
- - '####'
  - 使用诊断设置审核 Azure SQL 托管实例
- - '#####'
  - 启用和配置诊断设置
- - '#####'
  - 创建和配置 SQL Server 审计
- - '#####'
  - 查询审计数据
- - '####'
  - 使用 SQL Server 审计审核 Azure SQL 托管实例
- - '#####'
  - 创建存储帐户和容器
- - '#####'
  - 创建数据库凭据
- - '#####'
  - 创建 SQL Server 审计
- - '#####'
  - 查询 SQL Server 审计文件
- - '####'
  - 使用扩展事件审计 Azure SQL 托管实例
- - '####'
  - 集中和报告 Azure SQL 托管实例审计数据
- - '###'
  - 第 15 章：其他云提供商的审计选项
- - '####'
  - AWS RDS SQL Server 审计
- - '#####'
  - 创建 S3 存储桶
- - '#####'
  - 创建选项组
- - '#####'
  - 向新选项组添加审核选项
- - '#####'
  - 将新选项组添加到 RDS 实例
- - '#####'
  - 设置 SQL Server 审核
- - '#####'
  - 查询 SQL Server 审核数据
- - '####'
  - AWS RDS 扩展事件
- - '####'
  - 审核 Google Cloud SQL 数据库
- - '##'
  - 第五部分：附录
- - '###'
  - 附录 A：数据库审计选项比较
- - '####'
  - 审计选项
- - '####'
  - 审计选择的优缺点
- - '####'
  - SQL Server 审计 vs 扩展事件
- - '####'
  - 使用案例
- - '##'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审阅者
- - '##'
  - 致谢
- - '##'
  - 引言
- - '####'
  - 本书内容
- - '####'
  - 目标读者
- - '####'
  - 联系作者
