name: Oracle RMAN for Absolute Beginners
name_cn: 绝对初学者的 Oracle RMAN
slug: oracle-rman-for-absolute-beginners
toc:
- - '#'
  - Oracle RMAN 完全初学者指南
- - '##'
  - 版权声明
- - '##'
  - 致谢
- - '##'
  - 发行
- - '##'
  - 献词
- - '##'
  - 目录速览
- - '##'
  - 关于作者
- - '##'
  - 前言
- - '##'
  - 第1章：入门指南
- - '###'
  - 连接到你的数据库
- - '###'
  - 设置操作系统变量
- - '###'
  - 使用操作系统认证
- - '###'
  - 使用密码文件
- - '###'
  - 启动数据库
- - '###'
  - 停止数据库
- - '###'
  - 小结
- - '##'
  - 第2章：支持备份与恢复操作的文件
- - '###'
  - 管理控制文件
- - '####'
  - 查看控制文件名称与位置
- - '####'
  - 添加控制文件
- - '####'
  - 移动控制文件
- - '####'
  - 移除控制文件
- - '###'
  - 管理在线重做日志
- - '####'
  - 显示在线重做日志信息
- - '####'
  - 确定在线重做日志组的最佳大小
- - '####'
  - 确定重做日志组的最佳数量
- - '####'
  - 添加在线重做日志组
- - '####'
  - 调整大小和删除在线重做日志组
- - '####'
  - 向组中添加在线重做日志文件
- - '####'
  - 从组中移除在线重做日志文件
- - '####'
  - 移动或重命名重做日志文件
- - '###'
  - 实施归档日志模式
- - '####'
  - 做出架构决策
- - '####'
  - 设置归档重做文件位置
- - '####'
  - 启用归档日志模式
- - '####'
  - 禁用归档日志模式
- - '####'
  - 应对归档日志目标磁盘空间不足
- - '####'
  - 备份归档重做日志文件
- - '###'
  - 管理表空间和数据文件
- - '####'
  - 理解前五个
- - '####'
  - 理解为何需要更多
- - '####'
  - 创建表空间
- - '####'
  - 重命名表空间
- - '####'
  - 控制重做的生成
- - '####'
  - 更改表空间的写入模式
- - '####'
  - 删除表空间
- - '####'
  - 使用 Oracle 托管文件
- - '####'
  - 创建大文件表空间
- - '####'
  - 在表空间内启用默认表压缩
- - '####'
  - 显示表空间大小
- - '####'
  - 更改表空间大小
- - '##'
  - 第3章：用户管理的备份与恢复
- - '###'
  - 为非归档日志模式数据库实施冷备份策略
- - '###'
  - 对非归档日志模式数据库进行冷备份
- - '###'
  - 在非归档日志模式下使用联机重做日志恢复冷备份
- - '###'
  - 在非归档日志模式下无联机重做日志时恢复冷备份
- - '###'
  - 编写冷备份与恢复脚本
- - '###'
  - 对归档日志模式数据库进行冷备份
- - '###'
  - 实施热备份策略
- - '###'
  - 进行热备份
- - '###'
  - 编写热备份脚本
- - '###'
  - 理解分块问题
- - '###'
  - 理解备份期间产生重做日志的必要性
- - '###'
  - 理解数据文件会被更新
- - '###'
  - 对归档日志模式数据库执行完全恢复
- - '###'
  - 在数据库离线时进行恢复
- - '###'
  - 在数据库在线时进行恢复
- - '###'
  - 恢复控制文件
- - '###'
  - 对归档日志模式数据库执行不完全恢复
- - '###'
  - 小结
- - '##'
  - 第4章：配置RMAN
- - '###'
  - 理解RMAN
- - '###'
  - 启动RMAN
- - '###'
  - RMAN架构决策
- - '####'
  - 1. 远程或本地运行RMAN客户端
- - '####'
  - 2. 指定备份用户
- - '####'
  - 3. 使用联机或脱机备份
- - '####'
  - 4. 设置归档重做日志的目标位置和文件格式
- - '####'
  - 5. 配置RMAN备份位置和文件格式
- - '####'
  - 6. 设置控制文件的自动备份
- - '####'
  - 7. 指定控制文件自动备份的位置
- - '####'
  - 8. 备份归档重做日志
- - '####'
  - 9. 确定快照控制文件的位置
- - '####'
  - 10. 使用恢复目录
- - '####'
  - 11. 使用介质管理器
- - '####'
  - 12. 设置`CONTROL_FILE_RECORD_KEEP_TIME`初始化参数
- - '####'
  - 13. 配置RMAN的备份保留策略
- - '####'
  - 14. 配置归档重做日志的删除策略
- - '####'
  - 15. 设置并行度
- - '####'
  - 16. 使用备份集或映像副本
- - '####'
  - 17. 使用增量备份
- - '####'
  - 18. 使用增量更新的备份
- - '####'
  - 19. 使用块变化跟踪
- - '####'
  - 20. 配置二进制压缩
- - '####'
  - 21. 配置加密
- - '####'
  - 22. 配置其他设置
- - '####'
  - 23. 配置信息输出
- - '###'
  - 从决策到行动的过渡
- - '###'
  - 小结
- - '##'
  - 第5章：RMAN备份与报告
- - '###'
  - 准备运行RMAN备份命令
- - '###'
  - 设置NLS_DATE_FORMAT
- - '###'
  - 设置ECHO
- - '###'
  - 显示变量
- - '###'
  - 执行备份
- - '####'
  - 备份整个数据库
- - '####'
  - 备份表空间
- - '####'
  - 备份数据文件
- - '####'
  - 备份控制文件
- - '####'
  - 备份SPFILE
- - '####'
  - 备份归档重做日志
- - '####'
  - 备份FRA
- - '####'
  - 从备份中排除表空间
- - '####'
  - 备份未备份的数据文件
- - '####'
  - 跳过只读表空间
- - '####'
  - 跳过离线或不可访问的文件
- - '####'
  - 并行备份大文件
- - '####'
  - 将RMAN备份信息添加到存储库
- - '####'
  - 备份可插播数据库
- - '####'
  - 创建增量备份
- - '####'
  - 执行增量级别备份
- - '####'
  - 创建增量更新备份
- - '####'
  - 使用块变更跟踪
- - '####'
  - 检查数据文件和备份中的损坏
- - '###'
  - 使用恢复目录
- - '####'
  - 创建恢复目录
- - '####'
  - 注册目标数据库
- - '####'
  - 备份恢复目录
- - '####'
  - 同步恢复目录
- - '####'
  - 恢复目录版本
- - '####'
  - 删除恢复目录
- - '###'
  - 记录RMAN输出
- - '####'
  - 将输出重定向到文件
- - '####'
  - 使用Linux/Unix日志命令捕获输出
- - '####'
  - 将输出记录到文件
- - '####'
  - 在数据字典中查询输出
- - '###'
  - RMAN报告
- - '####'
  - 使用LIST命令
- - '####'
  - 使用REPORT命令
- - '####'
  - 使用SQL命令
- - '###'
  - 总结
- - '##'
  - 第6章：RMAN恢复
- - '###'
  - 确定是否需要介质恢复
- - '###'
  - 确定要恢复的内容
- - '###'
  - 过程如何工作
- - '###'
  - 使用数据恢复顾问
- - '###'
  - 使用RMAN停止/启动Oracle
- - '####'
  - 关闭数据库
- - '####'
  - 启动数据库
- - '###'
  - 完全恢复
- - '###'
  - 测试恢复
- - '###'
  - 恢复整个数据库
- - '###'
  - 恢复表空间
- - '###'
  - 恢复只读表空间
- - '###'
  - 恢复临时表空间
- - '###'
  - 恢复数据文件
- - '###'
  - 将数据文件恢复到非默认位置
- - '###'
  - 执行块级别恢复
- - '###'
  - 小结
- - '##'
  - 第7章：处理在线重做日志故障
- - '###'
  - 确定行动方案
- - '###'
  - 恢复多路复用日志成员丢失
- - '###'
  - 恢复非活动日志组所有成员丢失
- - '###'
  - 恢复活动/当前日志组所有成员丢失
- - '###'
  - 小结
- - '##'
  - 第8章：数据泵
- - '###'
  - Data Pump架构
- - '###'
  - 开始使用
- - '####'
  - 执行导出
- - '####'
  - 导入表
- - '####'
  - 使用参数文件
- - '###'
  - 以精细度进行导出和导入
- - '####'
  - 导出和导入整个数据库
- - '####'
  - 模式级别
- - '####'
  - 表级别
- - '####'
  - 表空间级别
- - '###'
  - 传输数据
- - '####'
  - 直接通过网络导出和导入
- - '####'
  - 复制数据文件
- - '###'
  - 操作存储的特性
- - '###'
  - 过滤数据和对象
- - '###'
  - 常见数据泵任务
- - '###'
  - 交互式命令模式
- - '###'
  - 监控Data Pump作业
- - '###'
  - 数据泵传统模式
- - '###'
  - 总结
- - '##'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 致谢
- - '##'
  - 本书概述
- - '###'
  - 简介
- - '###'
  - 本书涵盖内容
- - '###'
  - 排版约定
- - '###'
  - 源代码
- - '###'
  - 勘误
- - '###'
  - 联系作者
- - '##'
  - 附录
- - '###'
  - 离线与在线切换数据文件
- - '###'
  - 重命名或重新定位数据文件
- - '###'
  - 小结
