name: Analytics Optimization with Columnstore Indexes in Microsoft SQL Server
name_cn: Microsoft SQL Server 列存储索引分析性能优化
slug: analytics-optimization-with-columnstore-indexes-in-microsoft
toc:
- - '#'
  - 引言
- - '##'
  - 本书简介
- - '##'
  - 目标读者
- - '##'
  - 为何选择列存储索引？
- - '##'
  - 联系作者
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 第1章 事务数据库中的分析数据介绍
- - '##'
  - 1.1 分析数据应存放在何处？
- - '##'
  - 1.2 分析数据规模
- - '##'
  - 1.3 分析数据结构
- - '##'
  - 1.4 分析数据源
- - '###'
  - 1.4.1 数据仓库
- - '###'
  - 1.4.2 非结构化数据
- - '###'
  - 1.4.3 第三方分析软件
- - '###'
  - 1.4.4 在事务型数据库的 **OLTP** 表中存储 **OLAP** 数据
- - '###'
  - 1.4.5 在事务型数据库的分析表中存储 **OLAP** 数据
- - '#'
  - 第2章 事务型与分析型工作负载
- - '##'
  - 2.1 事务型数据
- - '##'
  - 2.2 分析型数据
- - '##'
  - 2.3 对两套系统的必要性
- - '##'
  - 2.4 构建更好的分析型数据结构
- - '#'
  - 第3章 什么是列存储索引？
- - '##'
  - 3.1 事务型数据存储的限制
- - '##'
  - 3.2 SQL Server 中的列存储索引技术
- - '###'
  - 3.2.1 行存储索引下的查询性能分析
- - '###'
  - 3.2.2 介绍列存储索引
- - '###'
  - 3.2.3 SQL Server 中列存储索引的优势
- - '####'
  - 3.2.3.1 SQL Server 中的原生分析型数据
- - '####'
  - 3.2.3.2 可扩展性
- - '####'
  - 3.2.3.3 卓越的压缩能力
- - '####'
  - 3.2.3.4 更快的分析读取
- - '####'
  - 3.2.3.5 更快的数据加载
- - '#'
  - 第4章 列存储索引架构
- - '##'
  - 4.1 示例数据
- - '##'
  - 4.2 行组与段
- - '##'
  - 4.3 增量存储
- - '##'
  - 4.4 删除位图
- - '##'
  - 4.5 非聚集列存储索引架构
- - '##'
  - 4.6 页面上的物理数据
- - '##'
  - 4.7 差异总结
- - '#'
  - 第5章 列存储压缩
- - '##'
  - 5.1 列存储压缩基础
- - '##'
  - 5.2 列存储压缩算法
- - '###'
  - 5.2.1 值编码
- - '###'
  - 5.2.2 字典编码
- - '####'
  - 表 5-6
- - '####'
  - 表 5-7
- - '##'
  - 5.3 查询字典元数据
- - '##'
  - 5.4 字符串数据是否应该规范化？
- - '###'
  - 5.4.1 行组（Vertipaq）优化
- - '##'
  - 5.5 其他压缩算法
- - '##'
  - 5.6 列存储索引压缩与元数据
- - '###'
  - 5.6.1 列存储归档压缩
- - '###'
  - 5.6.2 压缩生命周期
- - '#'
  - 第6章 列存储元数据
- - '##'
  - 6.1 可用的列存储元数据
- - '###'
  - 6.1.1 行组元数据
- - '####'
  - '`partition_number`'
- - '####'
  - '`delta_store_hobt_id`'
- - '####'
  - '`state` 和 `state_description`'
- - '###'
  - 6.1.2 列存储索引元数据
- - '####'
  - Total_rows
- - '####'
  - Deleted_rows
- - '####'
  - Size_in_bytes
- - '###'
  - 6.1.3 段元数据
- - '####'
  - Encoding_type
- - '####'
  - Row_Count
- - '####'
  - Has_nulls
- - '####'
  - Base_id and Magnitude
- - '####'
  - Min_data_id and Max_data_id
- - '####'
  - Null_value
- - '####'
  - On_disk_size
- - '###'
  - 6.1.4 行组物理元数据
- - '####'
  - State_desc
- - '####'
  - Total_rows, Deleted_rows, Size_in_bytes
- - '####'
  - Trim_reason_desc
- - '####'
  - Transition_to_compressed_state_desc
- - '##'
  - 6.2 行组统计
- - '###'
  - Has_vertipaq_optimization
- - '###'
  - Created_time
- - '###'
  - 6.2.1 行组操作统计
- - '####'
  - Index_scan_count
- - '####'
  - Scan_count
- - '####'
  - Delete_buffer_scan_count
- - '####'
  - Row_group_lock_count、Row_group_lock_wait_count 和 Row_group_lock_wait_in_ms
- - '####'
  - Returned_row_count
- - '###'
  - 6.2.2 列存储索引内存使用情况
- - '####'
  - Object_type_desc
- - '####'
  - Access_count
- - '####'
  - Object_load_time
- - '###'
  - 6.2.3 Internal Columnstore Index Objects
- - '####'
  - Internal_object_type_desc
- - '#'
  - 第7章 批处理执行
- - '##'
  - 7.1 行模式执行
- - '##'
  - 7.2 批处理模式执行
- - '##'
  - 7.3 批处理模式如何工作？
- - '##'
  - 7.4 批处理模式与行模式性能对比
- - '#'
  - 第8章 大容量加载数据
- - '##'
  - 8.1 大容量加载过程详解
- - '##'
  - 8.2 向列存储索引进行大容量加载
- - '##'
  - 8.3 批量加载到列存储索引的性能
- - '###'
  - 8.3.1 涓流插入 vs. 分阶段插入
- - '###'
  - 8.3.2 其他数据加载注意事项
- - '####'
  - 8.3.2.1 在数据加载期间删除非聚集索引
- - '####'
  - 8.3.2.2 每次数据加载时的列存储重新组织操作
- - '##'
  - 8.4 总结
- - '#'
  - 第9章 删除和更新操作
- - '##'
  - 9.1 修改数据的代价
- - '##'
  - 9.2 删除操作
- - '##'
  - 9.3 更新操作
- - '#'
  - 第10章 段与行组消除
- - '##'
  - 10.1 段消除
- - '##'
  - 10.2 列存储索引的查询优化
- - '###'
  - 10.2.1 行组消除
- - '###'
  - 10.2.2 无序数据的问题
- - '###'
  - 10.2.3 行组消除
- - '###'
  - 10.2.4 通过有序数据优化
- - '###'
  - 10.2.5 验证优化效果
- - '##'
  - 10.3 有序列存储索引的性能优势
- - '###'
  - 10.3.1 空间节省与压缩优势
- - '###'
  - 10.3.2 更新和删除操作的性能改进
- - '#'
  - 第11章 分区
- - '##'
  - 11.1 结合段消除与行组消除
- - '##'
  - 11.2 维护热/温/冷数据
- - '##'
  - 11.3 更快的数据移动/迁移
- - '##'
  - 11.4 分区消除
- - '##'
  - 11.5 数据库维护
- - '##'
  - 11.6 分区实战
- - '##'
  - 11.7 分区与非分区列存储索引的比较
- - '##'
  - 11.8 分区指南
- - '###'
  - 11.8.1 分区和行组大小调整
- - '###'
  - 11.8.2 分区列选择
- - '###'
  - 11.8.3 存储选择
- - '###'
  - 11.8.4 额外优势
- - '#'
  - 第12章 表上的非聚集列存储索引
- - '##'
  - 12.1 使用行存储索引
- - '##'
  - 12.2 数据库性能优化：分离 OLAP 与 OLTP
- - '###'
  - 12.2.1 分离 OLAP 与 OLTP 进程
- - '###'
  - 12.2.2 非聚集列存储索引
- - '###'
  - 12.2.3 管理热、温、冷事务数据
- - '##'
  - 12.3 压缩延迟
- - '##'
  - 12.4 压缩延迟的配置与调整
- - '###'
  - 12.4.1 过滤非聚集列存储索引：概念与优势
- - '###'
  - 12.4.2 使用过滤索引进行查询
- - '###'
  - 12.4.3 重要注意事项和陷阱
- - '###'
  - 12.4.4 与压缩延迟结合使用
- - '##'
  - 12.5 代码变更
- - '###'
  - 12.5.1 非聚集列存储索引的 Vertipaq 优化
- - '###'
  - 12.5.2 测试非聚集列存储索引
- - '###'
  - 12.5.3 不要忘记删除不需要的索引！
- - '#'
  - 第13章 列存储表上的非聚集行存储索引
- - '##'
  - 13.1 使用非聚集行存储索引
- - '##'
  - 13.2 非聚集行存储索引的大小考量
- - '##'
  - 13.3 强制实施约束
- - '##'
  - 13.4 筛选非聚集行存储索引
- - '##'
  - 13.5 启用 Vertipaq 优化
- - '###'
  - 13.5.1 向非聚集行存储索引添加筛选器
- - '###'
  - 13.5.2 执行周期性索引维护
- - '##'
  - 13.6 索引视图
- - '##'
  - 13.7 非聚集行存储索引的压缩
- - '#'
  - 第14章 列存储索引维护
- - '##'
  - 14.1 非聚集行存储索引指南
- - '##'
  - 14.2 碎片产生的原因是什么？
- - '##'
  - 14.3 碎片化到什么程度才算过多？
- - '###'
  - 14.3.1 量化已删除行
- - '###'
  - 14.3.2 详述无序数据
- - '##'
  - 14.4 无需维护的列存储索引
- - '##'
  - 14.5 列存储索引重组
- - '###'
  - 14.5.1 重组以移除增量行组
- - '##'
  - 14.6 列存储索引维护
- - '##'
  - 14.7 列存储索引重建
- - '###'
  - 14.7.1 列存储索引的重新排序与重建
- - '###'
  - 14.7.2 按分区进行列存储索引维护
- - '###'
  - 14.7.3 非聚集列存储索引的索引维护
- - '#'
  - 第15章 列存储索引性能
- - '##'
  - 15.1 列存储元数据读取
- - '###'
  - 15.1.1 分区与元数据查阅
- - '###'
  - 15.1.2 查询字典元数据
- - '###'
  - 15.1.3 最小化元数据读取的重要性
- - '##'
  - 15.2 列存储数据读取
- - '##'
  - 15.3 内存容量规划
- - '###'
  - 15.3.1 字典大小与字典压力
- - '####'
  - 规范化宽列
- - '####'
  - 添加或更改列存储排序列
- - '####'
  - 分区
- - '####'
  - 临时表上的列存储索引
- - '##'
  - 15.3.2 在临时表和内存优化表上使用列存储索引
- - '###'
  - 在临时表上使用列存储索引
- - '###'
  - 内存优化列存储索引
- - '####'
  - 演示内存优化列存储索引
- - '##'
  - 15.4 内存优化列存储索引：创建、比较与测试
- - '###'
  - 图 15-10
- - '###'
  - 图 15-11
- - '###'
  - 图 15-12
- - '##'
  - 15.5 内存优化列存储索引的权衡与优化策略
- - '###'
  - 优化策略
- - '#'
  - 附录
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y, Z
