name: DATABASE BENCHMARKING AND STRESS TESTING
name_cn: 数据库基准测试与压力测试
slug: database-benchmarking-and-stress-testing
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 关于作者和关于技术审校者
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '#'
  - 1. 基准测试基础
- - '##'
  - 什么是数据库压力测试？
- - '##'
  - 什么是数据库基准测试？
- - '##'
  - 什么是工作负载捕获/回放？
- - '##'
  - 为什么这些技术有用
- - '##'
  - 这些技术何时具有价值
- - '##'
  - 如何在这些选项中做选择
- - '##'
  - 后续内容
- - '#'
  - 2. 行业标准基准测试
- - '##'
  - 最流行的基准测试
- - '###'
  - TPC-C
- - '###'
  - TPC-C 与 TPC-E 基准测试对比分析
- - '##'
  - TPC-C 的数据库设计与问题
- - '##'
  - TPC-C 允许的高级特性
- - '##'
  - TPC-E 基准概述
- - '###'
  - 数据库基准测试：TPC-E 与 TPC-H
- - '####'
  - TPC-E
- - '####'
  - TPC-H
- - '#####'
  - TPC-DS
- - '##'
  - 注意
- - '##'
  - 较不流行的基准测试
- - '###'
  - TPC-DI
- - '###'
  - TPC-VMS
- - '###'
  - 威斯康星基准
- - '###'
  - AS³AP 基准
- - '##'
  - 已过时的基准测试
- - '###'
  - TPC-A 基准
- - '###'
  - TPC-B 基准
- - '###'
  - TPC-D 基准
- - '###'
  - TPC-R 基准
- - '###'
  - TPC-W 基准
- - '###'
  - 总结
- - '#'
  - 3. 基准测试工具
- - '##'
  - 存储基准测试
- - '###'
  - WINSAT
- - '###'
  - HDPARM
- - '###'
  - SQLIO
- - '###'
  - DISKSPD
- - '##'
  - 数据库模拟
- - '###'
  - SQLIOSTRESS
- - '###'
  - SQLIOSIM
- - '###'
  - Orion
- - '###'
  - 注意
- - '###'
  - Calibrate IO
- - '##'
  - 数据库基准测试
- - '###'
  - HammerDB
- - '####'
  - 简介与资源
- - '####'
  - 安装与启动
- - '####'
  - 执行基准测试的流程
- - '#####'
  - 步骤一：构建数据库对象
- - '######'
  - 步骤二：加载驱动脚本
- - '#####'
  - 步骤三：创建虚拟用户
- - '#####'
  - 步骤四：执行基准测试
- - '####'
  - 监控性能
- - '####'
  - 系列执行
- - '###'
  - Benchmark Factory
- - '###'
  - Swingbench
- - '###'
  - SLOB
- - '##'
  - 总结
- - '#'
  - 4. 基准测试准备
- - '##'
  - 基准测试准备
- - '##'
  - 项目使命陈述
- - '##'
  - 数据库准备
- - '##'
  - 基准测试时间规划
- - '##'
  - 基准测试规模设定
- - '#'
  - 5. 基准测试常见错误
- - '##'
  - 工作负载捕获
- - '##'
  - 扭曲因素
- - '##'
  - 总结
- - '###'
  - 注意
- - '##'
  - 所有必备工具
- - '##'
  - 没有“大红简单”按钮
- - '##'
  - 正确的工具部署方式
- - '##'
  - 意想不到的人为因素
- - '###'
  - 验证我们的方向
- - '###'
  - 自我应验的预言
- - '##'
  - 十大数据库基准测试误解
- - '###'
  - '#1：我使用的是像 Quest 的 `Benchmark Factory` 这样的工具，所以这就是我所需要的一切'
- - '###'
  - '#2：我拥有昂贵的 SAN，因此无需为 IO 配置任何特殊设置'
- - '###'
  - '#3：我可以直接使用开箱即用的默认操作系统配置'
- - '###'
  - '#4：我可以直接使用开箱即用的默认数据库设置/配置'
- - '###'
  - '#5：像 Benchmark Factory 这样的工具会为我的硬件创建最优设计的数据库对象'
- - '###'
  - '#6：像 Benchmark Factory 这样的工具会自动监控、调整和优化我的所有硬件、操作系统和数据库配置参数'
- - '###'
  - '#7：我不需要 DBA 来执行基准测试——任何技术人员都可以做'
- - '###'
  - '#8：我可以在相同的硬件平台上非常容易地比较数据库供应商'
- - '###'
  - '#9：每秒事务数（即 TPS）是基准测试中最关键的指标'
- - '###'
  - '#10：我们只需花几天时间就能基准测试所有我们感兴趣的内容'
- - '#'
  - 6. 基准测试硬件选项
- - '##'
  - 概要
- - '##'
  - 绘制架构图
- - '##'
  - CPU 与内存
- - '##'
  - 旋转磁盘
- - '##'
  - 新存储技术
- - '##'
  - 专用设备
- - '##'
  - 总结
- - '#'
  - 7. 基准测试软件选项
- - '###'
  - 注意
- - '##'
  - 绘制图表
- - '###'
  - 注意
- - '##'
  - 对大型对象进行分区
- - '##'
  - 高级数据压缩
- - '##'
  - 使用 SSD 扩展内存
- - '##'
  - 在内存中固定表
- - '##'
  - 列存存储与行存存储
- - '##'
  - 新的“内存中”表
- - '##'
  - 总结
- - '#'
  - 8. 整合基准测试
- - '##'
  - 整合方法
- - '##'
  - 数据库共存
- - '##'
  - 意外问题
- - '##'
  - 服务器分配
- - '##'
  - 混合基准测试
- - '##'
  - 总结
- - '#'
  - 9. 面向虚拟化的基准测试
- - '###'
  - 注意
- - '##'
  - 服务器 BIOS
- - '###'
  - 注意事项
- - '##'
  - 虚拟机配置
- - '###'
  - CPU
- - '###'
  - 内存
- - '###'
  - 网络
- - '###'
  - 磁盘 IO
- - '##'
  - 监控问题
- - '##'
  - 总结
- - '#'
  - 10. 公有云基准测试
- - '###'
  - 注意
- - '##'
  - 镜像规格选择
- - '##'
  - 部署架构
- - '##'
  - 摘要
- - '#'
  - 11. 工作负载捕获与回放
- - '##'
  - 万事俱备
- - '##'
  - 捕获/回放工具
- - '##'
  - 捕获时长
- - '##'
  - 重放架构
- - '##'
  - 结果解读
- - '##'
  - 捕获/回放示例
- - '##'
  - 总结
- - '#'
  - 12. 数据库压力测试
- - '##'
  - 原始压力测试
- - '###'
  - 注意
- - '##'
  - DBBENCHMARK 工具
- - '###'
  - DBBENCHMARK 运行与结果分析
- - '####'
  - 执行与输出
- - '####'
  - 输出文件结构
- - '####'
  - 性能图表分析
- - '#####'
  - CPU 使用率
- - '#####'
  - 运行队列长度
- - '#####'
  - RAM 使用率
- - '#####'
  - IO 事务率
- - '##'
  - 总结
- - '#'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E, F, G
- - '##'
  - H
- - '##'
  - I, J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q, R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
