name: Pro SQL server relational database design and implementation
name_cn: SQL Server 关系型数据库设计与实现高级指南
slug: pro-sql-server-relational-database-design-and-implementation
toc:
- - '#'
  - 专业级 SQL Server 关系数据库设计与实现
- - '##'
  - 第五版
- - '##'
  - 前言
- - '##'
  - 引言
- - '##'
  - 数据库设计的目的
- - '##'
  - 本书目标读者
- - '##'
  - 本书结构
- - '##'
  - 先决条件
- - '##'
  - 下载代码
- - '##'
  - 联系作者
- - '##'
  - 致谢
- - '#'
  - 目录
- - '##'
  - 第1章 基础知识
- - '##'
  - 第2章 需求简介
- - '##'
  - 第3章 数据建模的语言
- - '##'
  - 第4章 概念与逻辑数据模型制作
- - '##'
  - 第5章 规范化
- - '##'
  - 第6章 物理模型实现案例研究
- - '##'
  - 第7章 使用检查约束和触发器扩展数据保护
- - '##'
  - 第8章 模式与反模式
- - '##'
  - 第9章 数据库安全与安全模式
- - '##'
  - 第10章 索引结构与应用
- - '##'
  - 第11章 并发性问题
- - '##'
  - 第12章 可复用的标准数据库组件
- - '##'
  - 第13章 架构你的系统
- - '##'
  - 第14章 报表设计
- - '##'
  - 附录 A 标量数据类型参考
- - '##'
  - 索引
- - '#'
  - 第1章 基础知识
- - '##'
  - 历史
- - '##'
  - 关系数据结构
- - '##'
  - 实体间的关系
- - '##'
  - 依赖关系
- - '##'
  - 关系编程
- - '##'
  - 数据库设计阶段
- - '##'
  - 简要回顾历史
- - '###'
  - 介绍科德的关系数据库管理系统规则
- - '####'
  - 规则1：信息原则
- - '####'
  - 规则2：保证访问
- - '####'
  - 规则3：NULL值的系统化处理
- - '####'
  - 规则4：基于关系模型的动态在线目录
- - '####'
  - 规则5：综合性数据子语言规则
- - '####'
  - 规则6：视图更新规则
- - '####'
  - 规则7：高级插入、更新和删除
- - '####'
  - 规则8：物理数据独立性
- - '####'
  - 规则9：逻辑数据独立性
- - '####'
  - 规则10：完整性独立性
- - '####'
  - 规则11：分布独立性
- - '####'
  - 规则12：非篡改规则
- - '###'
  - 认可SQL标准
- - '##'
  - 识别关系型数据结构
- - '###'
  - 关系型数据结构
- - '###'
  - 隶属关系与关系模型
- - '##'
  - 介绍数据库与架构
- - '##'
  - 理解表、行与列
- - '##'
  - 表格、行和列的术语
- - '###'
  - 表1-1：基本数据表示术语细分
- - '###'
  - 表1-2：列术语细分
- - '##'
  - 数据库术语的不同视角定义
- - '###'
  - 注意
- - '###'
  - 行术语解析
- - '###'
  - 处理缺失值（NULL）
- - '###'
  - 定义域
- - '###'
  - 存储元数据
- - '###'
  - 定义唯一性约束（键）
- - '####'
  - 键的类型
- - '##'
  - 选择键
- - '###'
  - 自然键
- - '###'
  - 智能键
- - '###'
  - 代理键
- - '##'
  - 理解关系
- - '###'
  - 处理二元关系
- - '####'
  - 一对多关系
- - '####'
  - 一对多（一般情况）
- - '####'
  - 一对多关系
- - '####'
  - 多对多关系
- - '###'
  - 处理非二元关系
- - '##'
  - 理解函数依赖
- - '###'
  - 函数依赖与决定因素
- - '###'
  - 理解函数依赖
- - '###'
  - 寻找决定因素
- - '##'
  - 关系编程
- - '##'
  - 概述数据库项目的特定阶段
- - '###'
  - 概念阶段
- - '###'
  - 逻辑阶段
- - '###'
  - 物理阶段
- - '###'
  - 引擎调整阶段
- - '##'
  - 本章小结
- - '#'
  - 第2章 需求简介
- - '##'
  - 记录需求
- - '##'
  - 收集需求
- - '###'
  - 收集需求的方法
- - '###'
  - 详细规格说明的重要性
- - '###'
  - 数据库架构师的活动
- - '###'
  - 客户访谈
- - '###'
  - 提出正确的问题
- - '####'
  - 需要什么数据？
- - '####'
  - 数据如何使用？
- - '####'
  - 哪些规则管理数据的使用？
- - '##'
  - 报告涵盖哪些数据？
- - '##'
  - 数据目前在哪里？
- - '##'
  - 数据是否需要与其他系统集成？
- - '##'
  - 这些数据价值几何？
- - '##'
  - 谁会使用这些数据？
- - '##'
  - 是否在替换现有系统？
- - '##'
  - 利用其他类型的文档
- - '###'
  - 早期项目文档
- - '###'
  - 合同或客户工单
- - '###'
  - 服务等级协议
- - '###'
  - 审计计划
- - '###'
  - 原型
- - '###'
  - 遵循最佳实践
- - '###'
  - 总结
- - '#'
  - 第3章 数据建模的语言
- - '##'
  - 数据建模简介
- - '##'
  - 实体
- - '##'
  - 缩写的使用
- - '##'
  - 匈牙利表示法的使用
- - '##'
  - 属性
- - '##'
  - 主键
- - '##'
  - 备用键
- - '###'
  - 外键
- - '###'
  - 域
- - '##'
  - 域作为实现无关的数据类型描述
- - '##'
  - 物理建模与域的重用价值
- - '##'
  - 域层次结构示例
- - '##'
  - 逻辑建模中的域展示
- - '##'
  - 实现阶段与域的映射
- - '##'
  - 关系
- - '###'
  - 标识关系
- - '###'
  - 非标识关系
- - '##'
  - 非标识关系中的属性迁移
- - '##'
  - 核心概念差异
- - '##'
  - 说明性示例
- - '##'
  - 域实体
- - '##'
  - 强制关系与可选关系
- - '##'
  - 实际实现场景
- - '###'
  - 角色名称
- - '###'
  - 关系基数
- - '##'
  - 递归关系
- - '##'
  - 子类型
- - '##'
  - 多对多关系
- - '###'
  - 动词短语（关系名称）
- - '##'
  - 描述信息
- - '##'
  - 替代建模方法
- - '###'
  - 信息工程
- - '###'
  - 陈氏实体关系图
- - '##'
  - 最佳实践
- - '###'
  - 建模语言
- - '###'
  - 实体名称
- - '###'
  - 属性名称
- - '###'
  - 关系
- - '###'
  - 域
- - '##'
  - 总结
- - '#'
  - 第4章 概念与逻辑数据模型制作
- - '##'
  - 示例场景
- - '##'
  - 构建概念模型
- - '###'
  - 识别实体
- - '####'
  - 人物
- - '####'
  - 地点
- - '####'
  - 物品
- - '####'
  - 概念
- - '#####'
  - 文档
- - '#####'
  - 组
- - '#####'
  - 其他实体
- - '######'
  - 审计跟踪
- - '######'
  - 事件
- - '######'
  - 记录与日志
- - '####'
  - 实体回顾
- - '###'
  - 识别实体间的关系
- - '####'
  - 一对多关系
- - '#####'
  - 简单关系
- - '######'
  - 连接关系
- - '######'
  - 事务关系
- - '##'
  - 多值属性与领域
- - '##'
  - Is-A关系
- - '##'
  - 多对多关系
- - '####'
  - 列出关系
- - '###'
  - 测试概念模型
- - '##'
  - 构建逻辑模型
- - '###'
  - 识别属性与域
- - '####'
  - 标识符
- - '##'
  - 标识属性
- - '###'
  - 描述性信息
- - '####'
  - 定位器
- - '####'
  - 值
- - '####'
  - 关系属性
- - '#####'
  - 提示
- - '####'
  - 实体、属性与域列表
- - '#####'
  - 提示
- - '###'
  - 识别业务规则
- - '###'
  - 识别基本过程
- - '###'
  - 完成逻辑模型
- - '##'
  - 识别明显的新增数据需求
- - '###'
  - 测试逻辑模型
- - '###'
  - 与客户评审
- - '###'
  - 重复此过程直到客户同意你的模型
- - '##'
  - 最佳实践
- - '###'
  - 注意
- - '##'
  - 总结
- - '#'
  - 第5章 规范化
- - '##'
  - 规范化的过程
- - '##'
  - 表与列的形状
- - '###'
  - 所有列必须是原子性的
- - '####'
  - 电子邮件地址
- - '####'
  - 电子邮件地址和姓名的存储设计
- - '#####'
  - 电子邮件地址
- - '#####'
  - 姓名
- - '##'
  - 姓名处理与存储
- - '###'
  - 电话号码
- - '##'
  - 数据库设计
- - '###'
  - 关于第一范式
- - '####'
  - 重复组与一对多关系
- - '###'
  - 注意事项
- - '###'
  - 所有行必须互不相同
- - '###'
  - 注意
- - '###'
  - 判断现有设计是否符合第一范式的线索
- - '####'
  - 包含分隔符类型字符的字符串数据
- - '####'
  - 列名末尾带有数字
- - '####'
  - 没有键或键定义不佳的表
- - '##'
  - 列之间的关系
- - '###'
  - BCNF（鲍依斯-科得范式）定义
- - '###'
  - 部分键依赖
- - '###'
  - 完全键依赖
- - '###'
  - 代理键对依赖关系的影响
- - '###'
  - 行之间的依赖关系
- - '###'
  - 数据库未达到BCNF的迹象
- - '####'
  - 具有相同前缀的多列
- - '####'
  - 重复数据组
- - '##'
  - 汇总数据
- - '###'
  - 位置含义
- - '##'
  - 具有多重含义的表
- - '###'
  - 第四范式：独立的多值依赖
- - '###'
  - 第五范式
- - '##'
  - 反规范化
- - '##'
  - 最佳实践
- - '##'
  - 总结
- - '##'
  - 本书进程回顾至此
- - '#'
  - 第6章 物理模型实现案例研究
- - '##'
  - 本章内容概述
- - '###'
  - 注意事项
- - '##'
  - 为你的表选择物理模型
- - '###'
  - 引擎选项
- - '###'
  - 优势与考虑因素
- - '###'
  - 推荐场景
- - '###'
  - 实用建议与工具
- - '###'
  - 章节上下文与示例
- - '##'
  - 选择名称
- - '###'
  - 表命名
- - '###'
  - 列命名
- - '###'
  - 模型名称调整
- - '##'
  - 选择键的实现方式
- - '###'
  - 主键
- - '####'
  - 基于现有列构建主键
- - '##'
  - 基于新的代理值设置主键
- - '###'
  - 使用代理键
- - '###'
  - 替代键
- - '##'
  - 确定域的实现
- - '###'
  - 域定义示例
- - '###'
  - 实现主题
- - '###'
  - 在列中强制执行域，还是使用表？
- - '###'
  - 选择数据类型
- - '##'
  - 精确数值数据
- - '###'
  - '`bit`'
- - '###'
  - '`tinyint`'
- - '###'
  - '`smallint`'
- - '###'
  - '`int`'
- - '###'
  - '`bigint`'
- - '###'
  - '`decimal` (或 `numeric`)'
- - '##'
  - 近似数值数据
- - '###'
  - '`float(N)`'
- - '###'
  - '`real`'
- - '##'
  - 日期和时间
- - '###'
  - '`date`'
- - '###'
  - '`time`'
- - '###'
  - '`datetime2(N)`'
- - '###'
  - '`datetimeoffset`'
- - '###'
  - '`smalldatetime`'
- - '###'
  - '`datetime`'
- - '##'
  - 二进制数据
- - '###'
  - '`binary(N)`'
- - '###'
  - '`varbinary(N)`'
- - '###'
  - '`varbinary(max)`'
- - '##'
  - 字符（或字符串）数据
- - '###'
  - '`char(N)`'
- - '###'
  - '`varchar(N)`'
- - '###'
  - '`varchar(max)`'
- - '###'
  - '`nchar`、`nvarchar`、`nvarchar(max)`'
- - '##'
  - 其他数据类型
- - '###'
  - '`sql_variant`'
- - '###'
  - '`rowversion` (`timestamp` 是其同义词)'
- - '###'
  - '`uniqueidentifier`'
- - '###'
  - '`XML`'
- - '###'
  - 空间类型 (`geometry`、`geography`、`circularString`、`compoundCurve`、`curvePolygon`)
- - '###'
  - '`hierarchyId`'
- - '####'
  - 已弃用或不良选择的数据类型
- - '####'
  - 常见的数据类型配置
- - '#####'
  - 布尔/逻辑值
- - '###'
  - 大值数据类型列
- - '###'
  - 用户定义类型/别名
- - '###'
  - 复杂CLR数据类型
- - '##'
  - 选择合适的数据类型
- - '###'
  - 设置可空性
- - '###'
  - 选择排序规则
- - '##'
  - 排序规则、模式与实现列
- - '###'
  - 设置模式
- - '###'
  - 添加实现列
- - '##'
  - 使用DDL创建数据库
- - '###'
  - 创建基本表结构
- - '####'
  - 模式
- - '####'
  - 列与基本数据类型
- - '####'
  - 可空性
- - '###'
  - 管理非自然主键
- - '####'
  - 手动管理
- - '#####'
  - 使用IDENTITY属性生成
- - '#####'
  - 使用默认约束生成
- - '###'
  - 用于构建表的实际DDL
- - '###'
  - 添加唯一性约束
- - '####'
  - 添加主键约束
- - '####'
  - 添加替代键约束
- - '###'
  - 索引该如何考虑？
- - '###'
  - 构建DEFAULT约束
- - '###'
  - 添加关系（外键）
- - '###'
  - 关于级联操作的限制与思考
- - '###'
  - 关于`MessagingUser`与`Message`的关系处理
- - '###'
  - 关于`Topic`相关关系的处理
- - '###'
  - 关于跨数据库关系的讨论
- - '###'
  - 添加基本`CHECK`约束
- - '###'
  - 维护自动值的触发器
- - '##'
  - 编写数据库文档
- - '###'
  - 扩展属性的使用与查看
- - '###'
  - 查看基本系统元数据
- - '##'
  - 查看数据库对象元数据
- - '##'
  - 查看约束信息
- - '##'
  - 查看触发器信息
- - '##'
  - 查看CHECK约束
- - '##'
  - 为你的结构进行单元测试
- - '###'
  - 注意
- - '###'
  - 提示
- - '###'
  - 测试唯一约束与错误处理
- - '##'
  - 总结与经验
- - '##'
  - 最佳实践
- - '###'
  - 理解关系引擎并明智选择
- - '###'
  - 投资于数据库生成工具
- - '###'
  - 保持规范化
- - '###'
  - 制定真正的对象命名策略
- - '###'
  - 开发模板域
- - '###'
  - 仔细为每列选择数据类型和可空性
- - '###'
  - 确保每个表至少有一个不包含人工值的`唯一性`约束
- - '###'
  - 使用外键约束实施外键
- - '###'
  - 记录并编写脚本
- - '###'
  - 开发测试脚本
- - '##'
  - 部署生命周期
- - '###'
  - 全新的数据库
- - '###'
  - 随后的数据库构建
- - '##'
  - 总结
- - '#'
  - 第7章 使用检查约束和触发器扩展数据保护
- - '##'
  - 检查约束
- - '###'
  - 检查约束冲突示例
- - '##'
  - 使用`WITH NOCHECK`添加约束
- - '###'
  - 提示
- - '##'
  - 约束的可信度与优化器
- - '###'
  - 注意
- - '###'
  - 使约束可信
- - '###'
  - 基于简单表达式的CHECK约束
- - '##'
  - 空字符串
- - '##'
  - 日期范围检查
- - '##'
  - 值合理性
- - '###'
  - 使用函数的CHECK约束
- - '###'
  - 增强由约束引发的错误
- - '##'
  - DML触发器
- - '###'
  - AFTER触发器
- - '##'
  - 对多行的范围检查
- - '###'
  - 维护汇总值
- - '##'
  - 查看触发事件
- - '##'
  - 注意事项
- - '###'
  - 级联插入
- - '##'
  - 概念介绍
- - '##'
  - 示例代码
- - '###'
  - 建表与初始数据
- - '###'
  - 创建触发器
- - '###'
  - 测试触发器
- - '####'
  - 从子级到父级的级联
- - '###'
  - 跨数据库的关系
- - '##'
  - 父表更新
- - '###'
  - 阻止更新存在子行的父行
- - '##'
  - 父表删除
- - '###'
  - 级联删除
- - '###'
  - 阻止删除存在关联子行的父行
- - '##'
  - 子表插入与子表更新
- - '###'
  - INSTEAD OF触发器
- - '####'
  - 将无效数据重定向到异常表
- - '##'
  - INSTEAD OF触发器示例
- - '##'
  - 强制不执行对表的任何操作
- - '###'
  - 处理触发器与约束错误
- - '##'
  - 最佳实践
- - '##'
  - 总结
- - '#'
  - 第8章 模式与反模式
- - '##'
  - 理想模式
- - '###'
  - 唯一性
- - '##'
  - 选择性唯一性
- - '##'
  - 批量唯一性
- - '##'
  - 范围唯一性
- - '###'
  - 测试预约重叠
- - '###'
  - 总结讨论
- - '###'
  - 近似唯一性
- - '###'
  - 数据库设计模式
- - '##'
  - 数据驱动设计
- - '##'
  - 历史/时态数据
- - '###'
  - 使用触发器捕获历史记录
- - '####'
  - 创建历史架构
- - '####'
  - 创建历史表
- - '####'
  - 创建触发器
- - '####'
  - 测试触发器
- - '##'
  - 使用时间扩展来管理历史记录
- - '###'
  - 配置时间扩展
- - '####'
  - 一次处理一行时态数据
- - '###'
  - 版本化表中的数据时态与历史记录
- - '##'
  - 版本控制的注意事项
- - '##'
  - 历史查询与数据一致性
- - '####'
  - 处理一张或多张表中的多行数据
- - '####'
  - 设置/重写历史
- - '###'
  - 层级结构
- - '####'
  - 自引用/递归关系/邻接表
- - '##'
  - 树（单父级层次结构）
- - '##'
  - 图（多父级层次结构）
- - '##'
  - 使用`hierarchyId`类型实现层次结构
- - '##'
  - 获取节点的子节点和父节点
- - '##'
  - 替代方法/查询优化
- - '###'
  - 路径技术
- - '###'
  - 嵌套集
- - '###'
  - Kimball辅助表
- - '###'
  - 图像、文档及其他文件，哦天哪！
- - '##'
  - 配置服务器以进行文件流访问
- - '###'
  - 提示
- - '##'
  - 文件存储与数据库设计
- - '###'
  - 泛化
- - '###'
  - 家庭库存系统数据库设计示例
- - '##'
  - 背景介绍
- - '##'
  - 初始数据库设计
- - '##'
  - 添加子类以扩展信息
- - '##'
  - 更新数据与创建视图
- - '##'
  - 查询结果示例
- - '###'
  - 泛化与缺失数据
- - '###'
  - 存储用户指定数据
- - '##'
  - 实体-属性-值(EAV)
- - '##'
  - 设备数据查询
- - '####'
  - 向表添加列
- - '##'
  - 更新稀疏列与列集
- - '##'
  - 查看列的元数据
- - '##'
  - 使用列集
- - '##'
  - 索引稀疏列
- - '##'
  - 反模式
- - '###'
  - 不可解码的数据
- - '###'
  - 一刀切的通用领域表
- - '###'
  - 过度使用非结构化数据
- - '##'
  - 总结
- - '#'
  - 第9章 数据库安全与安全模式
- - '##'
  - SQL Server数据库安全指南
- - '##'
  - 数据库访问
- - '###'
  - 主机服务器安全配置指南
- - '###'
  - 主体与安全对象
- - '###'
  - 连接到服务器
- - '####'
  - 使用登录名和数据库用户连接到服务器
- - '##'
  - 使用包含数据库模型
- - '###'
  - SQL Server中的包含用户
- - '##'
  - 创建用户时遇到的错误
- - '##'
  - 连接到包含用户
- - '##'
  - 在对象资源管理器中查看
- - '##'
  - 在包含数据库中创建链接到登录的用户
- - '##'
  - 切换包含模式
- - '##'
  - 身份模拟
- - '##'
  - 演示
- - '##'
  - 测试身份模拟
- - '##'
  - 恢复上下文
- - '##'
  - 总结
- - '##'
  - 数据库对象安全对象
- - '###'
  - 可授予的权限
- - '####'
  - 表安全
- - '####'
  - 列级安全
- - '###'
  - 角色
- - '####'
  - 内置数据库角色
- - '###'
  - 用户定义的数据库角色
- - '##'
  - 用于职位描述的角色示例
- - '##'
  - 用于确定安全信息的函数
- - '##'
  - 实际示例
- - '##'
  - 关于基于角色安全的总结
- - '##'
  - 数据库权限管理示例
- - '###'
  - 应用程序角色
- - '##'
  - 架构
- - '##'
  - 行级安全
- - '###'
  - 使用专用视图提供行级安全
- - '###'
  - 视图与行级安全
- - '##'
  - 使用行级安全功能
- - '###'
  - 行级安全策略配置与测试
- - '###'
  - 使用数据驱动的行级安全
- - '###'
  - 通过T-SQL编码对象控制数据访问
- - '###'
  - 存储过程与标量函数
- - '###'
  - 提示
- - '###'
  - 对象内的模拟
- - '###'
  - EXECUTE AS功能详解与安全注意事项
- - '##'
  - 功能概述
- - '##'
  - 安全注意事项
- - '##'
  - 使用示例
- - '##'
  - 与行级安全性的交互
- - '###'
  - 视图与表值函数
- - '##'
  - 跨越数据库边界
- - '###'
  - 使用跨数据库链
- - '###'
  - 通过模拟跨越数据库边界
- - '###'
  - 使用基于证书的信任
- - '##'
  - 不同服务器（分布式查询）
- - '##'
  - 数据混淆
- - '###'
  - 加密数据
- - '###'
  - 使用动态数据遮蔽向用户隐藏数据
- - '##'
  - 审核SQL Server使用情况
- - '###'
  - 定义审核规范
- - '####'
  - 启用审核规范
- - '###'
  - 查看审计跟踪
- - '###'
  - 查看审计配置
- - '##'
  - 最佳实践
- - '##'
  - 总结
- - '#'
  - 第10章 索引结构与应用
- - '##'
  - 索引概述与性能平衡
- - '##'
  - 索引概述
- - '##'
  - 基本索引结构
- - '###'
  - 图10-1
- - '###'
  - 小结
- - '###'
  - 磁盘索引
- - '###'
  - 聚簇索引
- - '##'
  - 结构
- - '####'
  - 使用聚簇索引
- - '##'
  - 非聚集索引
- - '###'
  - 结构
- - '####'
  - 聚集表上的非聚集索引
- - '####'
  - 堆表上的非聚集索引
- - '###'
  - 使用非聚集索引
- - '###'
  - 一般性考虑
- - '####'
  - 确定索引的有用性
- - '###'
  - SQL Server索引与查询优化：直方图与多列索引
- - '###'
  - 索引与多列
- - '###'
  - 复合索引
- - '##'
  - 覆盖索引
- - '###'
  - 多索引使用与索引键排序
- - '##'
  - 多索引
- - '##'
  - 索引键的排序顺序
- - '##'
  - 堆表上的非聚集索引
- - '###'
  - 使用唯一索引
- - '##'
  - 内存优化索引
- - '###'
  - 内存中OLTP表
- - '###'
  - 通用表结构
- - '###'
  - 索引结构
- - '##'
  - Bw-Tree索引
- - '#####'
  - 哈希索引
- - '#####'
  - 索引内存优化OLTP表
- - '###'
  - 列存储索引
- - '##'
  - 索引使用的常见OLTP模式
- - '###'
  - 何时在非主键上进行聚簇索引
- - '###'
  - 为外键建立索引
- - '##'
  - 域表
- - '##'
  - 所有权关系
- - '##'
  - 多对多关系表关系
- - '##'
  - 一对一关系
- - '###'
  - 索引视图
- - '###'
  - 压缩
- - '##'
  - SQL Server分区与索引
- - '##'
  - 分区
- - '##'
  - 索引与动态管理视图查询
- - '###'
  - 缺失索引
- - '###'
  - 磁盘索引利用率统计
- - '###'
  - 碎片
- - '###'
  - 内存OLTP索引统计
- - '##'
  - 最佳实践
- - '##'
  - 总结
- - '#'
  - 第11章 并发性问题
- - '##'
  - 资源调控器
- - '##'
  - 操作系统与硬件考量
- - '##'
  - 事务
- - '###'
  - 事务概述
- - '###'
  - 事务语法
- - '###'
  - 事务基础
- - '##'
  - 命名事务
- - '##'
  - 带MARK的事务
- - '####'
  - 嵌套事务
- - '####'
  - 自主事务
- - '###'
  - 保存点
- - '###'
  - 分布式事务
- - '##'
  - 事务状态
- - '##'
  - 显式事务与隐式事务
- - '##'
  - SQL Server并发方法
- - '###'
  - 隔离级别
- - '###'
  - 悲观并发性强制
- - '####'
  - 锁类型
- - '#####'
  - 表11-1. 锁类型
- - '####'
  - 锁模式
- - '#####'
  - 表11-2. 锁模式
- - '#####'
  - 表11-3. 锁兼容性模式
- - '###'
  - SQL Server中的锁与并发控制
- - '##'
  - 使用表提示覆盖锁
- - '##'
  - 死锁
- - '##'
  - 隔离级别与锁机制
- - '###'
  - READ UNCOMMITTED
- - '###'
  - READ COMMITTED
- - '###'
  - REPEATABLE READ
- - '###'
  - 可序列化 (`SERIALIZABLE`)
- - '###'
  - 有趣的案例
- - '####'
  - 锁定与外键
- - '##'
  - 应用程序锁
- - '###'
  - 乐观并发强制机制
- - '####'
  - 磁盘上表的乐观并发强制机制
- - '###'
  - SNAPSHOT隔离级别
- - '##'
  - 已提交读快照（数据库设置）
- - '###'
  - 注意
- - '###'
  - 内存OLTP表中的乐观并发性强制实施
- - '###'
  - 错误信息与隔离级别限制
- - '###'
  - SNAPSHOT隔离级别
- - '###'
  - REPEATABLE READ隔离级别
- - '#####'
  - '`SERIALIZABLE`隔离级别'
- - '#####'
  - 写入争用
- - '#####'
  - 外键
- - '##'
  - 为异步争用进行编码
- - '###'
  - 基于行的更改检测
- - '####'
  - 添加验证列
- - '###'
  - 使用RowVersion列实现乐观锁
- - '###'
  - 行级变更检测的编码实践
- - '###'
  - 为逻辑工作单元变更检测编写代码
- - '##'
  - 最佳实践
- - '##'
  - 摘要
- - '#'
  - 第12章 可复用的标准数据库组件
- - '##'
  - 数字表
- - '###'
  - 生成数字表
- - '###'
  - 算法分解
- - '###'
  - 创建和使用持久化数字表
- - '###'
  - 示例查询
- - '###'
  - 确定字符串的内容
- - '###'
  - 在数字序列中查找间隙
- - '###'
  - 分隔逗号分隔的项目
- - '###'
  - SQL数据拆分与日历表设计
- - '##'
  - 日历表
- - '###'
  - 使用日历表进行高级日期操作
- - '###'
  - 日历表的常见用法
- - '####'
  - 分组查询示例
- - '###'
  - 构建复杂日期条件
- - '###'
  - 实际应用与扩展列
- - '###'
  - 标准日历表中的常见列
- - '###'
  - 浮动时间窗口
- - '##'
  - 实用工具对象
- - '###'
  - 监控对象
- - '##'
  - 创建监控架构与表
- - '##'
  - 创建捕获行数的存储过程
- - '##'
  - 执行示例与查看结果
- - '##'
  - 后续监控建议
- - '###'
  - 扩展DDL工具
- - '###'
  - 日志记录对象
- - '###'
  - 其他可能性…
- - '##'
  - 总结
- - '#'
  - 第13章 架构你的系统
- - '##'
  - 根据需求选择引擎
- - '###'
  - 指南：选择使用内存引擎的时机
- - '###'
  - 即席SQL
- - '####'
  - 优势
- - '###'
  - 查询的运行时控制
- - '##'
  - 动态SQL的优势
- - '##'
  - 实际示例
- - '###'
  - 基础表与查询
- - '###'
  - 通过连接和聚合进行扩展
- - '###'
  - 资源优化
- - '###'
  - 灵活性优于共享计划和参数化
- - '##'
  - 共享执行计划
- - '##'
  - 参数化
- - '###'
  - 缺陷
- - '##'
  - 高内聚，低耦合
- - '##'
  - 多于一条语句的批处理
- - '###'
  - 安全问题
- - '###'
  - 警告
- - '####'
  - SQL注入
- - '####'
  - 性能调优的难度
- - '##'
  - 存储过程
- - '###'
  - 优点
- - '####'
  - 封装
- - '####'
  - 动态过程
- - '###'
  - 安全性
- - '###'
  - 性能
- - '##'
  - 参数化复杂计划
- - '##'
  - 无需修改程序进行微调
- - '####'
  - 充分利用内存引擎的能力
- - '#####'
  - 原生编译对象的强大之处
- - '#####'
  - 原生编译对象的局限性
- - '#####'
  - 示例与演示
- - '###'
  - 存储过程的错误处理与事务管理
- - '##'
  - 缺陷
- - '###'
  - 高昂的初始投入
- - '###'
  - 搜索中支持可选参数的困难
- - '###'
  - 操作中仅影响某些列的困难
- - '###'
  - 存储过程还是即席SQL？
- - '##'
  - T-SQL与CLR
- - '###'
  - 为何要将SQL Server与CLR集成？
- - '###'
  - 架构选项：SQLCLR
- - '###'
  - 认知与现实
- - '###'
  - 托管CLR的关键动机
- - '###'
  - 在CLR和T-SQL之间选择
- - '###'
  - 深入学习资源
- - '##'
  - 最佳实践
- - '##'
  - 总结
- - '#'
  - 第14章 报表设计
- - '##'
  - 报告风格
- - '###'
  - 分析型报告
- - '####'
  - 拉尔夫·金博尔
- - '####'
  - 比尔·英蒙
- - '###'
  - 聚合型报告
- - '###'
  - 操作型报表
- - '##'
  - 需求收集过程
- - '##'
  - 用于分析报表的维度建模
- - '##'
  - 维度
- - '###'
  - 日期维度
- - '##'
  - 缓慢变化维度
- - '##'
  - 雪花维度
- - '###'
  - 类型维度
- - '##'
  - 事实
- - '###'
  - 事务事实
- - '##'
  - 业务度量值的设计考量
- - '##'
  - 创建事实表示例数据
- - '##'
  - 退化维度
- - '##'
  - 快照事实
- - '##'
  - 分析查询
- - '###'
  - 查询
- - '###'
  - 查询示例
- - '##'
  - 索引
- - '##'
  - 用于聚合报表的汇总建模
- - '###'
  - 初始汇总表
- - '###'
  - 其他汇总表
- - '###'
  - 聚合查询
- - '###'
  - 查询
- - '###'
  - 索引
- - '##'
  - 操作型报表的建模（或无需建模）
- - '###'
  - 示例操作型数据模型
- - '###'
  - 内存中OLTP
- - '##'
  - 操作查询
- - '###'
  - 查询
- - '###'
  - 索引
- - '##'
  - 总结
- - '##'
  - 标量数据类型参考
- - '##'
  - 精确数值数据
- - '###'
  - 整数值
- - '####'
  - tinyint
- - '####'
  - smallint
- - '####'
  - int
- - '##'
  - bigint
- - '###'
  - 十进制数值
- - '####'
  - decimal和numeric
- - '####'
  - 货币类型
- - '##'
  - 近似数值数据
- - '####'
  - 日期和时间数据
- - '###'
  - SQL Server日期时间数据类型参考
- - '##'
  - date
- - '###'
  - 范围
- - '###'
  - 存储
- - '###'
  - 精度
- - '###'
  - 讨论
- - '###'
  - 行压缩效果
- - '##'
  - time [(precision)]
- - '###'
  - 范围
- - '###'
  - 存储
- - '###'
  - 精度
- - '###'
  - 讨论
- - '###'
  - 行压缩效果
- - '##'
  - datetime2 [(precision)]
- - '###'
  - 范围
- - '###'
  - 存储
- - '###'
  - 精度
- - '###'
  - 讨论
- - '###'
  - 行压缩效果
- - '##'
  - datetimeoffset [(precision)]
- - '###'
  - 范围
- - '###'
  - 存储
- - '###'
  - 精度
- - '###'
  - 讨论
- - '###'
  - 行压缩效果
- - '##'
  - smalldatetime
- - '###'
  - 范围
- - '###'
  - 存储
- - '###'
  - 精度
- - '###'
  - 讨论
- - '###'
  - 行压缩效果
- - '##'
  - datetime
- - '###'
  - 范围
- - '###'
  - 存储
- - '###'
  - 精度
- - '###'
  - 讨论
- - '###'
  - 行压缩效果
- - '##'
  - 所有日期类型的讨论
- - '###'
  - 日期函数
- - '###'
  - 日期范围
- - '###'
  - 在文本格式中表示日期
- - '###'
  - 字符串
- - '###'
  - char[(长度)]
- - '###'
  - varchar[(长度)]
- - '###'
  - varchar(max)
- - '###'
  - text
- - '###'
  - Unicode字符串：`nchar`、`nvarchar`、`nvarchar(max)`、`ntext`
- - '##'
  - 二进制数据
- - '###'
  - '`binary[(length)]`'
- - '###'
  - '`varbinary[(length)]`'
- - '###'
  - '`varbinary(max)`'
- - '###'
  - '`image`'
- - '##'
  - 其他数据类型
- - '###'
  - '`bit`'
- - '##'
  - rowversion（又称timestamp）
- - '##'
  - uniqueidentifier
- - '##'
  - 游标
- - '##'
  - 表
- - '###'
  - 表变量
- - '####'
  - 表值参数
- - '###'
  - sql_variant
- - '##'
  - 并非简单的标量数据类型
- - '###'
  - 数据库与SQL技术术语汇编
- - '##'
  - A
- - '###'
  - 数据库命令与语句
- - '###'
  - 安全问题
- - '###'
  - 触发器(Triggers)
- - '###'
  - 汇总与维护
- - '###'
  - 报告风格(Reporting styles)
- - '###'
  - 键(Keys)
- - '###'
  - 建模方法
- - '##'
  - B
- - '##'
  - C
- - '###'
  - 约束(Constraints)
- - '###'
  - 概念与模型
- - '##'
  - D
- - '###'
  - 数据访问策略(Data access strategies)
- - '###'
  - 数据库组件与对象
- - '###'
  - 日期维度与函数
- - '###'
  - 域实现(Domain implementation)
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '###'
  - 标量数据类型(Scalar datatype)
- - '###'
  - 其他术语
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
