name: XML and JSON Recipes for SQL Server
name_cn: SQL Server 的 XML 和 JSON 秘籍
slug: xml-and-json-recipes-for-sql-server
toc:
- - '##'
  - 目录
- - '##'
  - 致谢
- - '##'
  - 目录
- - '##'
  - 第一部分：SQL Server 中的 XML
- - '###'
  - 第 1 章：XML 简介 3
- - '####'
  - 步入 XML 3
- - '####'
  - 示例数据库 4
- - '####'
  - 理解 XML 4
- - '####'
  - XML 字符实体化 6
- - '####'
  - 探索 XML 数据类型 7
- - '####'
  - 1-1. 创建未类型化的 XML 列 8
- - '#####'
  - 问题 8
- - '#####'
  - 解决方案 8
- - '#####'
  - 工作原理 10
- - '####'
  - 1-2. 在 Visual Studio 中创建 XML 架构 11
- - '#####'
  - 问题 11
- - '#####'
  - 解决方案 11
- - '#####'
  - 工作原理 13
- - '####'
  - 1-3. 从 SSMS 创建 XML 架构 14
- - '#####'
  - 问题 14
- - '#####'
  - 解决方案 15
- - '#####'
  - 工作原理 16
- - '####'
  - 1-4. 将 XML 绑定到架构集合 18
- - '#####'
  - 问题 18
- - '#####'
  - 解决方案 18
- - '#####'
  - 工作原理 19
- - '####'
  - 1-5. 创建类型化的 XML 列 20
- - '#####'
  - 问题 20
- - '#####'
  - 解决方案 21
- - '#####'
  - 工作原理 21
- - '####'
  - 总结 22
- - '###'
  - 第 2 章：构建 XML 23
- - '####'
  - 修复“无法显示 XML”错误 24
- - '####'
  - 2-1. 将关系数据转换为简单的 XML 格式 26
- - '#####'
  - 问题 26
- - '#####'
  - 解决方案 26
- - '#####'
  - 工作原理 26
- - '####'
  - 2-2. 生成以表名为元素名的 XML 数据 28
- - '#####'
  - 问题 28
- - '#####'
  - 解决方案 28
- - '#####'
  - 工作原理 30
- - '####'
  - 2-3. 生成以元素为中心的 XML 30
- - '#####'
  - 问题 30
- - '#####'
  - 解决方案 31
- - '#####'
  - 工作原理 31
- - '####'
  - 2-4. 添加根元素 32
- - '#####'
  - 问题 32
- - '#####'
  - 解决方案 32
- - '#####'
  - 工作原理 33
- - '####'
  - 2-5. 在 XML 数据中包含具有 NULL 值的元素 33
- - '#####'
  - 问题 33
- - '#####'
  - 解决方案 33
- - '#####'
  - 工作原理 34
- - '####'
  - 2-6. 在 XML 中包含二进制数据 34
- - '#####'
  - 问题 34
- - '#####'
  - 解决方案 34
- - '#####'
  - 工作原理 35
- - '####'
  - 2-7. 生成嵌套的层次结构 XML 数据 36
- - '#####'
  - 问题 36
- - '#####'
  - 解决方案 36
- - '#####'
  - 工作原理 38
- - '####'
  - 2-8. 构建自定义 XML 38
- - '#####'
  - 问题 38
- - '#####'
  - 解决方案 38
- - '#####'
  - 工作原理 40
- - '####'
  - 2-9. 简化自定义 XML 生成 45
- - '#####'
  - 问题 45
- - '#####'
  - 解决方案 45
- - '#####'
  - 工作原理 46
- - '####'
  - 2-10. 向 XML 添加特殊节点 48
- - '#####'
  - 问题 48
- - '#####'
  - 解决方案 48
- - '#####'
  - 工作原理 49
- - '####'
  - 总结 51
- - '###'
  - 第 3 章：操作 XML 文件 53
- - '####'
  - 3-1. 从 SQL 将 XML 结果存储到文件 53
- - '#####'
  - 问题 53
- - '#####'
  - 解决方案 53
- - '#####'
  - 工作原理 55
- - '####'
  - 3-2. 从 SSIS 包创建 XML 59
- - '#####'
  - 问题 59
- - '#####'
  - 解决方案 59
- - '#####'
  - 工作原理 72
- - '####'
  - 3-3. 从存储过程加载 XML 72
- - '#####'
  - 问题 72
- - '#####'
  - 解决方案 72
- - '#####'
  - 工作原理 75
- - '####'
  - 3-4. 从 SSIS 包加载 XML 78
- - '#####'
  - 问题 78
- - '#####'
  - 解决方案 78
- - '#####'
  - 工作原理 90
- - '####'
  - 3-5. 实现 CLR 解决方案 92
- - '#####'
  - 问题 92
- - '#####'
  - 解决方案 92
- - '#####'
  - 工作原理 96
- - '####'
  - 总结 99
- - '###'
  - 第 4 章：分解 XML 101
- - '####'
  - 4-1. 使用内部 ENTITY 声明分解 XML 101
- - '#####'
  - 问题 101
- - '#####'
  - 解决方案 101
- - '#####'
  - 工作原理 102
- - '####'
  - 4-2. 将 OPENXML 迁移到 XQuery 108
- - '#####'
  - 问题 108
- - '#####'
  - 解决方案 108
- - '#####'
  - 工作原理 109
- - '####'
  - 4-3. 分解列中的 XML 113
- - '#####'
  - 问题 113
- - '#####'
  - 解决方案 113
- - '#####'
  - 工作原理 114
- - '####'
  - 4-4. 处理遗留的 XML 存储 116
- - '#####'
  - 问题 116
- - '#####'
  - 解决方案 117
- - '#####'
  - 工作原理 118
- - '####'
  - 4-5. 导航类型化的 XML 列 120
- - '#####'
  - 问题 120
- - '#####'
  - 解决方案 120
- - '#####'
  - 工作原理 122
- - '####'
  - 4-6. 检索 XML 数据的子集 123
- - '#####'
  - 问题 123
- - '#####'
  - 解决方案 123
- - '#####'
  - 工作原理 124
- - '####'
  - 4-7. 查找表中的所有 XML 列 127
- - '#####'
  - 问题 127
- - '#####'
  - 解决方案 127
- - '#####'
  - 工作原理 129
- - '####'
  - 4-8. 使用多个 CROSS APPLY 运算符 132
- - '#####'
  - 问题 132
- - '#####'
  - 解决方案 132
- - '#####'
  - 工作原理 133
- - '####'
  - 总结 134
- - '###'
  - 第 5 章：修改 XML 135
- - '####'
  - 5-1. 向 XML 插入子元素 135
- - '#####'
  - 问题 135
- - '#####'
  - 解决方案 135
- - '#####'
  - 工作原理 136
- - '####'
  - 5-2. 向具有命名空间的现有 XML 实例插入子元素 137
- - '#####'
  - 问题 137
- - '#####'
  - 解决方案 137
- - '#####'
  - 工作原理 138
- - '####'
  - 5-3. 插入 XML 属性 140
- - '#####'
  - 问题 140
- - '#####'
  - 解决方案 140
- - '#####'
  - 工作原理 141
- - '####'
  - 5-4. 有条件地插入 XML 属性 143
- - '#####'
  - 问题 143
- - '#####'
  - 解决方案 143
- - '#####'
  - 工作原理 144
- - '####'
  - 5-5. 插入指定了位置的子元素 144
- - '#####'
  - 问题 144
- - '#####'
  - 解决方案 144
- - '#####'
  - 工作原理 146
- - '####'
  - 5-6. 插入多个元素 146
- - '#####'
  - 问题 146
- - '#####'
  - 解决方案 146
- - '#####'
  - 工作原理 147
- - '####'
  - 5-7. 更新 XML 元素值 148
- - '#####'
  - 问题 148
- - '#####'
  - 解决方案 148
- - '#####'
  - 工作原理 149
- - '####'
  - 5-8. 更新 XML 属性值 150
- - '#####'
  - 问题 150
- - '#####'
  - 解决方案 150
- - '#####'
  - 工作原理 151
- - '####'
  - 5-9. 删除 XML 属性 151
- - '#####'
  - 问题 151
- - '#####'
  - 解决方案 151
- - '#####'
  - 工作原理 152
- - '####'
  - 5-10. 删除 XML 元素 153
- - '#####'
  - 问题 153
- - '#####'
  - 解决方案 153
- - '#####'
  - 工作原理 154
- - '####'
  - 总结 156
- - '###'
  - 第 6 章：过滤 XML 157
- - '####'
  - 6-1. 实现 exist( ) 方法 157
- - '#####'
  - 问题 157
- - '#####'
  - 解决方案 157
- - '#####'
  - 工作原理 158
- - '####'
  - 6-2. 使用 exist( ) 方法过滤 XML 值 160
- - '#####'
  - 问题 160
- - '#####'
  - 解决方案 160
- - '#####'
  - 工作原理 161
- - '####'
  - 6-3. 查找 XML 实例中任意位置的所有 XML 元素 164
- - '#####'
  - 问题 164
- - '#####'
  - 解决方案 164
- - '#####'
  - 工作原理 166
- - '####'
  - 6-4. 按单个值过滤 167
- - '#####'
  - 问题 167
- - '#####'
  - 解决方案 167
- - '#####'
  - 工作原理 168
- - '####'
  - 6-5. 通过 T-SQL 变量过滤 XML 168
- - '#####'
  - 问题 168
- - '#####'
  - 解决方案 168
- - '#####'
  - 工作原理 169
- - '####'
  - 6-6. 与值序列进行比较 170
- - '#####'
  - 问题 170
- - '#####'
  - 解决方案 170
- - '#####'
  - 工作原理 171
- - '####'
  - 6-7. 匹配指定的字符串模式 171
- - '#####'
  - 问题 171
- - '#####'
  - 解决方案 172
- - '#####'
  - 工作原理 172
- - '####'
  - 6-8. 过滤值的范围 174
- - '#####'
  - 问题 174
- - '#####'
  - 解决方案 174
- - '#####'
  - 工作原理 175
- - '####'
  - 6-9. 按多个条件过滤 175
- - '#####'
  - 问题 175
- - '#####'
  - 解决方案 175
- - '#####'
  - 工作原理 176
- - '####'
  - 6-10. 设置否定谓词 177
- - '#####'
  - 问题 177
- - '#####'
  - 解决方案 177
- - '#####'
  - 工作原理 178
- - '####'
  - 6-11. 过滤空值 178
- - '#####'
  - 问题 178
- - '#####'
  - 解决方案 179
- - '#####'
  - 工作原理 180
- - '####'
  - 总结 182
- - '###'
  - 第 7 章：提高 XML 性能 185
- - '####'
  - 7-1. 创建主 XML 索引 185
- - '#####'
  - 问题 185
- - '#####'
  - 解决方案 185
- - '#####'
  - 工作原理 187
- - '####'
  - 7-2. 创建辅助 PATH 类型索引 193
- - '#####'
  - 问题 193
- - '#####'
  - 解决方案 193
- - '#####'
  - 工作原理 195
- - '####'
  - 7-3. 创建辅助 VALUE 类型索引 196
- - '#####'
  - 问题 196
- - '#####'
  - 解决方案 196
- - '#####'
  - 工作原理 198
- - '####'
  - 7-4. 创建辅助 PROPERTY 类型索引 200
- - '#####'
  - 问题 200
- - '#####'
  - 解决方案 200
- - '#####'
  - 工作原理 202
- - '####'
  - 7-5. 创建选择性 XML 索引 202
- - '#####'
  - 问题 202
- - '#####'
  - 解决方案 203
- - '#####'
  - 工作原理 205
- - '####'
  - 7-6. 优化选择性 XML 索引 210
- - '#####'
  - 问题 210
- - '#####'
  - 解决方案 210
- - '#####'
  - 工作原理 211
- - '####'
  - 7-7. 创建辅助选择性 XML 索引 213
- - '#####'
  - 问题 213
- - '#####'
  - 解决方案 213
- - '#####'
  - 工作原理 214
- - '####'
  - 7-8. 修改选择性 XML 索引 215
- - '#####'
  - 问题 215
- - '#####'
  - 解决方案 215
- - '#####'
  - 工作原理 217
- - '####'
  - 总结 218
- - '##'
  - 第二部分：SQL Server 中的 JSON
- - '###'
  - 第 8 章：构造 JSON 221
- - '####'
  - JSON 简介 221
- - '####'
  - 8-1. 使用 AUTO 模式构建 JSON 225
- - '#####'
  - 问题 225
- - '#####'
  - 解决方案 225
- - '#####'
  - 工作原理 226
- - '####'
  - 8-2. 在构建 JSON 时处理 NULL 230
- - '#####'
  - 问题 230
- - '#####'
  - 解决方案 230
- - '#####'
  - 工作原理 231
- - '####'
  - 8-3. 转义 JSON 输出的括号 232
- - '#####'
  - 问题 232
- - '#####'
  - 解决方案 232
- - '#####'
  - 工作原理 232
- - '####'
  - 8-4. 向 JSON 添加 ROOT 键元素 233
- - '#####'
  - 问题 233
- - '#####'
  - 解决方案 233
- - '#####'
  - 工作原理 233
- - '####'
  - 8-5. 获得对 JSON 输出的控制权 234
- - '#####'
  - 问题 234
- - '#####'
  - 解决方案 234
- - '#####'
  - 工作原理 235
- - '####'
  - 8-6. 处理转义字符 239
- - '#####'
  - 问题 239
- - '#####'
  - 解决方案 239
- - '#####'
  - 工作原理 240
- - '####'
  - 8-7. 处理 CLR 数据类型 241
- - '#####'
  - 问题 241
- - '#####'
  - 解决方案 242
- - '#####'
  - 工作原理 243
- - '####'
  - 总结 244
- - '###'
  - 第 9 章：将 JSON 转换为行集 245
- - '####'
  - 9-1. 使用 JSON 检测列 245
- - '#####'
  - 问题 245
- - '#####'
  - 解决方案 245
- - '#####'
  - 工作原理 247
- - '####'
  - 9-2. 返回 JSON 文档的子集 249
- - '#####'
  - 问题 249
- - '#####'
  - 解决方案 249
- - '#####'
  - 工作原理 250
- - '####'
  - 9-3. 从 JSON 返回标量值 251
- - '#####'
  - 问题 251
- - '#####'
  - 解决方案 251
- - '#####'
  - 工作原理 252
- - '####'
  - 9-4. 对返回的 NULL 进行故障排除 254
- - '#####'
  - 问题 254
- - '#####'
  - 解决方案 254
- - '#####'
  - 工作原理 254
- - '####'
  - 9-5. 将 JSON 转换为表 255
- - '#####'
  - 问题 255
- - '#####'
  - 解决方案 255
- - '#####'
  - 工作原理 256
- - '####'
  - 9-6. 处理 JSON 嵌套子对象 259
- - '#####'
  - 问题 259
- - '#####'
  - 解决方案 259
- - '#####'
  - 工作原理 262
- - '####'
  - 9-7. 索引 JSON 263
- - '#####'
  - 问题 263
- - '#####'
  - 解决方案 263
- - '#####'
  - 工作原理 264
- - '####'
  - 总结 267
- - '###'
  - 第 10 章：修改 JSON 269
- - '####'
  - 10-1. 向 JSON 添加新的键值对 269
- - '#####'
  - 问题 269
- - '#####'
  - 解决方案 269
- - '#####'
  - 工作原理 270
- - '####'
  - 10-2. 更新现有 JSON 270
- - '#####'
  - 问题 270
- - '#####'
  - 解决方案 270
- - '#####'
  - 工作原理 271
- - '####'
  - 10-3. 从 JSON 中删除 271
- - '#####'
  - 问题 271
- - '#####'
  - 解决方案 271
- - '#####'
  - 工作原理 271
- - '####'
  - 10-4. 追加 JSON 属性 273
- - '#####'
  - 问题 273
- - '#####'
  - 解决方案 273
- - '#####'
  - 工作原理 274
- - '####'
  - 10-5. 使用多个操作进行修改 274
- - '#####'
  - 问题 274
- - '#####'
  - 解决方案 274
- - '#####'
  - 工作原理 275
- - '####'
  - 10-6. 重命名 JSON 键 275
- - '#####'
  - 问题 275
- - '#####'
  - 解决方案 275
- - '#####'
  - 工作原理 276
- - '####'
  - 10-7. 修改 JSON 对象 277
- - '#####'
  - 问题 277
- - '#####'
  - 解决方案 277
- - '#####'
  - 工作原理 277
- - '####'
  - 10-8. 比较 XML 与 JSON 279
- - '#####'
  - 问题 279
- - '#####'
  - 解决方案 279
- - '#####'
  - 工作原理 283
- - '####'
  - 总结 285
- - '##'
  - 索引 287
- - '##'
  - 关于作者和关于技术审校者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '#'
  - 第一部分
- - '##'
  - 1. XML 简介
- - '###'
  - 踏入 XML 之门
- - '###'
  - 示例数据库
- - '###'
  - 理解 XML
- - '###'
  - XML 字符实体化
- - '#'
  - 探索 XML 数据类型
- - '##'
  - 1-1. 创建非类型化 XML 列
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 1-2. 在 Visual Studio 中创建 XML 架构
- - '###'
  - 问题
- - '#'
  - 使用 Visual Studio 和 SSMS 生成 XML 架构
- - '##'
  - 解决方案
- - '##'
  - 工作原理
- - '##'
  - 1-3. 从 SSMS 创建 XML 架构
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 工作原理
- - '##'
  - 1-4. 将 XML 绑定到架构集合
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 1-5. 创建类型化 XML 列
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 总结
- - '#'
  - 2. 构建 XML
- - '##'
  - 修复“无法显示 XML”错误
- - '##'
  - 2-1. 将关系数据转换为简单 XML 格式
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '#'
  - 工作原理
- - '#'
  - 2-2\. 使用表名作为元素名称生成 XML 数据
- - '##'
  - 问题
- - '##'
  - 解决方案
- - '##'
  - 工作原理
- - '#'
  - 2-3\. 生成以元素为中心的 XML
- - '##'
  - 问题
- - '##'
  - 解决方案
- - '##'
  - 工作原理
- - '#'
  - 2-4\. 添加根元素
- - '##'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 2-5. 在 XML 数据中包含值为 NULL 的元素
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 2-6. 在 XML 中包含二进制数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 2-7. 生成嵌套的层次结构 XML 数据
- - '###'
  - 问题
- - '##'
  - 2-8. 构建自定义 XML
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 解决方案（续）
- - '###'
  - 工作原理
- - '###'
  - 工作原理
- - '#'
  - 2-9. 简化自定义 XML 生成
- - '##'
  - 问题
- - '##'
  - 解决方案
- - '##'
  - 工作原理
- - '#'
  - 2-10. 向 XML 添加特殊节点
- - '##'
  - 问题
- - '##'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 总结
- - '#'
  - 3. 操作 XML 文件
- - '##'
  - 3-1. 从 SQL 将 XML 结果存储到文件中
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3-2. 从 SSIS 包创建 XML
- - '###'
  - 问题
- - '#'
  - 解决方案
- - '##'
  - SSIS 包创建
- - '##'
  - 配置执行 SQL 任务
- - '##'
  - 配置 SQL 语句
- - '#'
  - 显示常规菜单配置
- - '##'
  - 显示如何为变量设置表达式
- - '##'
  - 显示脚本任务管理器属性
- - '##'
  - 测试 SSIS 包
- - '###'
  - 工作原理
- - '##'
  - 3-3. 从存储过程加载 XML
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3-4. 从 SSIS 包加载 XML
- - '###'
  - 问题
- - '##'
  - 解决方案
- - '#'
  - 显示参数映射菜单设置
- - '##'
  - 7. 文件系统任务 “归档文件”：打开文件系统任务编辑器。
- - '###'
  - 它是如何工作的
- - '##'
  - 3-5. 实现 CLR 解决方案
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '####'
  - 注册 C# 代码文件
- - '####'
  - 使用 T-SQL 进行配置
- - '###'
  - 工作原理
- - '##'
  - 本章小结
- - '#'
  - 4. 分解 XML
- - '##'
  - 4-1. 使用内部实体声明分解 XML
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '#'
  - 工作原理
- - '##'
  - 数据准备
- - '##'
  - OPENXML 函数
- - '##'
  - 内存释放
- - '##'
  - 4-2. 将 OPENXML 迁移到 XQuery
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4-3. 从列中分解 XML
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4-4. 处理遗留的 XML 存储
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4-5. 导航类型化 XML 列
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4-6. 检索 XML 数据的子集
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 工作原理
- - '##'
  - 4-7. 查找表中的所有 XML 列
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '#'
  - 工作原理
- - '##'
  - 数据类型过滤与验证
- - '##'
  - 代码执行过程
- - '##'
  - CTE 外部 SELECT 块分析
- - '##'
  - 4-8. 使用多个 CROSS APPLY 运算符
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 摘要
- - '##'
  - 5. 修改 XML
- - '###'
  - 5-1. 在 XML 中插入一个子元素
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '###'
  - 5-2. 在包含命名空间的现有 XML 实例中插入子元素
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '##'
  - 工作原理
- - '##'
  - 5-3. 插入 XML 属性
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5-4. 条件性地插入 XML 属性
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 5-5. 在指定位置插入子元素
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '###'
  - 5-6. 插入多个元素
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '###'
  - 5-7. 更新 XML 元素值
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5-8. 更新 XML 属性值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5-9. 删除 XML 属性
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5-10. 删除 XML 元素
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 总结
- - '#'
  - 6. 过滤 XML
- - '##'
  - 6-1. 使用 exist( ) 方法
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 6-2. 使用 exist( ) 方法过滤 XML 值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '#'
  - 工作原理
- - '#'
  - 6-3. 在 XML 实例中任何位置查找所有 XML 元素的出现
- - '##'
  - 问题
- - '##'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 6-4. 通过单值过滤
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 6-5. 通过 T-SQL 变量过滤 XML
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 6-6. 与值序列进行比较
- - '###'
  - 问题
- - '##'
  - 解决方案
- - '##'
  - 工作原理
- - '##'
  - 6-7. 匹配指定的字符串模式
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 6-8. 筛选值范围
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 6-9. 按多个条件筛选
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '###'
  - 6-10. 设置否定谓词
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '###'
  - 6-11. 过滤空值
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '##'
  - 摘要
- - '##'
  - 7. 提升 XML 性能
- - '###'
  - 7-1 创建主 XML 索引
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '##'
  - 工作原理
- - '##'
  - 7-2 创建辅助 PATH 类型索引
- - '###'
  - 问题
- - '#'
  - 7-3 创建二级 VALUE 类型索引
- - '##'
  - 问题
- - '##'
  - 解决方案
- - '##'
  - 工作原理
- - '###'
  - 工作原理
- - '##'
  - 7-4 创建次级属性类型索引
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 7-5 创建选择性 XML 索引
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 工作原理
- - '###'
  - 7-6 优化选择性 XML 索引
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 7-7 创建辅助选择性 XML 索引
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 7-8 修改选择性 XML 索引
- - '###'
  - 问题
- - '#'
  - 第二部分
- - '#'
  - 8. 构造 JSON
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 总结
- - '#'
  - JSON 简介
- - '##'
  - 8-1. 使用 AUTO 模式构建 JSON
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 8-2\. 处理 JSON 构建时的 NULL 值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 8-3\. 转义 JSON 输出的方括号
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 8-4. 向 JSON 添加 ROOT 键元素
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 8-5. 获取对 JSON 输出的控制权
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 工作原理
- - '##'
  - 8-6. 处理转义字符
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '#'
  - 工作原理
- - '#'
  - 8-7. 处理 CLR 数据类型
- - '##'
  - 问题
- - '##'
  - 解决方案
- - '##'
  - 工作原理
- - '#'
  - 总结
- - '#'
  - 9. 将 JSON 转换为行集
- - '##'
  - 9-1. 检测包含 JSON 的列
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9-2. 返回 JSON 文档的子集
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9-3. 从 JSON 返回标量值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9-4. 对返回的 NULL 进行故障排除
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 9-4. 为 JSON 路径实现严格模式
- - '###'
  - 工作原理
- - '##'
  - 9-5. 将 JSON 转换为表
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9-6. 处理 JSON 嵌套子对象
- - '###'
  - 问题
- - '##'
  - 9-6. 处理多级 JSON
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9-7. JSON 索引
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 总结
- - '#'
  - 10. 修改 JSON
- - '##'
  - 10-1. 向 JSON 添加新的键值对
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10-2. 更新现有的 JSON
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10-3. 从 JSON 中删除
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10-4. 追加 JSON 属性
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10-5. 使用多重操作进行修改
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10-6. 重命名 JSON 键
- - '###'
  - 问题
- - '##'
  - 10-7\. 修改 JSON 对象
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10-8\. 比较 XML 与 JSON
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - XML 插入
- - '##'
  - JSON 插入
- - '##'
  - 切分 XML
- - '##'
  - 切分 JSON
- - '###'
  - 工作原理
- - '##'
  - 总结
- - '##'
  - 索引
