name: Azure Arc-enabled Data Services Revealed
name_cn: Azure Arc 启用的数据服务揭秘
slug: azure-arc-enabled-data-services-revealed
toc:
- - '#'
  - 献词
- - '##'
  - 献给 Franzie 和 Gwendolyn
- - '##'
  - 献给我的家人
- - '#'
  - 前言
- - '#'
  - 引言
- - '#'
  - 书籍结构
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 1. Kubernetes 入门
- - '##'
  - 介绍 Kubernetes
- - '###'
  - Kubernetes 的优势
- - '##'
  - Kubernetes API
- - '###'
  - API 对象
- - '###'
  - API 服务器
- - '###'
  - 核心 Kubernetes `API` 原语
- - '####'
  - '`Pod`'
- - '####'
  - '`控制器`'
- - '####'
  - StatefulSet 概述
- - '####'
  - Services
- - '####'
  - Storage
- - '##'
  - 存储供应
- - '##'
  - Kubernetes 集群组件
- - '###'
  - 探索 Kubernetes 集群架构
- - '####'
  - 控制平面节点
- - '####'
  - 工作节点
- - '###'
  - 理解调度与资源分配
- - '####'
  - Kubernetes 中的调度
- - '##'
  - Pod 调度技术
- - '###'
  - 资源消耗
- - '###'
  - 网络基础
- - '##'
  - Kubernetes 网络模型规则
- - '##'
  - 通信模式
- - '##'
  - Kubernetes 在 Azure Arc 启用的数据服务中的作用
- - '##'
  - 总结与关键要点
- - '#'
  - 2. Azure Arc 启用的数据服务
- - '##'
  - 挑战
- - '##'
  - Azure Arc 简介
- - '###'
  - Azure Arc 支持的资源
- - '####'
  - Azure Arc 支持的服务器
- - '####'
  - Azure Arc 支持的 Kubernetes
- - '####'
  - Azure Arc 支持的 SQL Server
- - '####'
  - Azure Arc 启用的数据服务
- - '###'
  - 工具
- - '####'
  - Azure 工具
- - '####'
  - 原生工具
- - '##'
  - 介绍 Azure Arc 启用的数据服务
- - '###'
  - Azure Arc 启用的数据服务架构
- - '####'
  - 硬件层
- - '####'
  - Kubernetes 层
- - '####'
  - Azure Arc 管理控制平面层
- - '####'
  - 数据服务层
- - '##'
  - Azure Arc 管理控制平面层：深入解析
- - '###'
  - 间接连接模式
- - '###'
  - 直接连接模式
- - '##'
  - Azure Arc 支持的数据服务管理功能
- - '###'
  - 数据服务层：深入探讨
- - '####'
  - Azure Arc-enabled SQL Managed Instance
- - '##'
  - Azure Arc 支持的 PostgreSQL 超大规模版
- - '###'
  - 部署规模考虑
- - '####'
  - 计算
- - '###'
  - 高可用性
- - '####'
  - 存储
- - '##'
  - 总结与要点
- - '#'
  - 3. 部署准备
- - '##'
  - 先决条件
- - '###'
  - Chocolatey
- - '###'
  - Windows 上的工具
- - '###'
  - Ubuntu 上的工具
- - '##'
  - 准备 Azure Data Studio
- - '###'
  - azure-cli 扩展和提供程序
- - '###'
  - 在 Azure 中拥有一个资源组
- - '##'
  - 总结与要点回顾
- - '#'
  - 4. 安装 Kubernetes
- - '##'
  - 安装考虑因素与方法
- - '###'
  - 部署位置？
- - '###'
  - 进一步考虑事项
- - '###'
  - 安装方法
- - '###'
  - 附加选项
- - '##'
  - 安装要求
- - '###'
  - 网络要求
- - '###'
  - 获取 Kubernetes
- - '##'
  - 构建自管理集群
- - '###'
  - 基于虚拟机的 Kubernetes 集群要求
- - '###'
  - 准备虚拟机
- - '###'
  - 虚拟机网络配置
- - '###'
  - 系统交换空间设置
- - '###'
  - 软件包安装
- - '##'
  - 安装与配置 containerd
- - '##'
  - 安装与配置 Kubernetes 软件包
- - '###'
  - 创建控制平面
- - '###'
  - Pod 网络
- - '###'
  - 引导你的控制平面
- - '###'
  - 部署 Pod 网络
- - '###'
  - 将节点添加到集群
- - '##'
  - 在集群中配置存储
- - '##'
  - 使用 kubectl 访问集群
- - '###'
  - 重命名 kubeconfig 上下文
- - '###'
  - 从 Windows 工作站操作
- - '###'
  - 从 Linux 工作站操作
- - '##'
  - 本章总结
- - '#'
  - 5. 以间接模式部署数据控制器
- - '##'
  - 决定 Kubernetes 存储类
- - '##'
  - 通过命令行部署
- - '##'
  - 通过 Azure Data Studio 部署
- - '##'
  - 总结与要点
- - '#'
  - 6. 以直接模式部署数据控制器
- - '##'
  - Azure Arc-enabled Data Services 准备工作
- - '###'
  - 让你的 Kubernetes 集群启用 Azure Arc
- - '###'
  - 准备你的 Azure 订阅
- - '##'
  - 部署直接模式数据控制器
- - '##'
  - 总结与要点
- - '#'
  - 7. 部署 Azure Arc 启用的 SQL 托管实例
- - '##'
  - 通过 azure-cli 进行部署
- - '##'
  - 通过 Azure Data Studio 进行部署
- - '###'
  - 通过 Kubernetes 工具部署
- - '###'
  - 通过 Azure 门户部署
- - '##'
  - Active Directory 身份验证
- - '##'
  - 将数据导入实例
- - '###'
  - 将备份文件复制到实例中
- - '###'
  - 在实例中还原备份文件
- - '###'
  - 托管备份与还原
- - '##'
  - 删除已部署的托管实例
- - '##'
  - 总结与要点回顾
- - '#'
  - 8. 部署 Azure Arc 启用的 PostgreSQL 超大规模实例
- - '##'
  - 通过命令行部署
- - '##'
  - 通过 Azure Data Studio 部署
- - '##'
  - 服务器组的横向扩展
- - '##'
  - 移除已部署的服务器组
- - '##'
  - 总结与关键要点
- - '#'
  - 9. 监控与管理
- - '##'
  - 通过数据控制器进行监控
- - '###'
  - 获取端点
- - '###'
  - 指标（Grafana 仪表板）
- - '###'
  - 日志搜索分析（Kibana）
- - '##'
  - 通过 Azure 门户进行监控
- - '###'
  - 直接连接模式
- - '###'
  - 间接连接模式
- - '###'
  - 准备上传
- - '###'
  - 上传日志、使用情况和指标
- - '###'
  - 在 Azure 门户中监控你的资源
- - '##'
  - 升级启用 Azure Arc 的数据服务
- - '##'
  - 总结与要点
