name: Pro SQL Server on Microsoft Azure
name_cn: Microsoft Azure 上的 SQL Server 高级指南
slug: pro-sql-server-on-microsoft-azure
toc:
- - '#'
  - 微软 Azure 上的 Pro SQL Server
- - '##'
  - 关于技术审稿人
- - '##'
  - 致谢
- - '##'
  - 目录
- - '###'
  - 云计算概述
- - '###'
  - 云计算的特征
- - '###'
  - 服务模型
- - '####'
  - 平台即服务
- - '####'
  - 基础设施即服务
- - '####'
  - 软件即服务
- - '###'
  - Microsoft Azure
- - '###'
  - Azure 服务
- - '###'
  - 计算服务
- - '###'
  - 数据管理服务
- - '###'
  - 网络
- - '###'
  - 开发者服务
- - '###'
  - 身份与访问
- - '###'
  - 备份
- - '###'
  - 总结
- - '###'
  - Azure 服务
- - '###'
  - 计算
- - '###'
  - 存储
- - '###'
  - 网络
- - '###'
  - 如何协同工作
- - '###'
  - 更新/升级域
- - '###'
  - 容错域
- - '###'
  - 部署
- - '####'
  - 经典部署模型
- - '####'
  - 资源管理器部署模型
- - '###'
  - 部署自动化
- - '###'
  - 总结
- - '###'
  - Azure 存储服务
- - '###'
  - Blob 存储
- - '###'
  - 表存储
- - '###'
  - 队列存储
- - '###'
  - 文件存储
- - '###'
  - 设计决策
- - '###'
  - Azure 存储架构内幕
- - '###'
  - 复制引擎
- - '###'
  - 存储戳内的层级
- - '###'
  - 为读取请求保持可用性/一致性
- - '###'
  - 分区层的负载均衡
- - '###'
  - DFS 层的负载均衡
- - '###'
  - DFS 容量的负载均衡
- - '###'
  - Azure 存储提供的持久性
- - '###'
  - Azure 高级存储
- - '###'
  - 高级存储内部机制
- - '###'
  - Azure 存储最佳实践
- - '###'
  - 使用 Blob 提升性能
- - '###'
  - 使用表提升性能
- - '###'
  - 数据查询最佳实践
- - '###'
  - 总结
- - '###'
  - 网络基础知识
- - '###'
  - 站点到站点连接
- - '###'
  - 点到站点连接
- - '###'
  - ExpressRoute
- - '###'
  - Azure AD Connect
- - '###'
  - 流量管理器
- - '###'
  - 虚拟专用网络
- - '###'
  - 负载均衡器
- - '###'
  - Azure DNS
- - '###'
  - 总结
- - '###'
  - 补充参考
- - '###'
  - 部署独立的 SQL Server 实例
- - '###'
  - 配置设置
- - '###'
  - 自动化
- - '###'
  - 部署后工作
- - '###'
  - Azure 资源管理器
- - '###'
  - Azure CLI
- - '###'
  - 总结
- - '###'
  - 混合模型概览
- - '###'
  - 备份到 Azure 存储
- - '###'
  - Microsoft Azure 存储中的 SQL Server 文件
- - '###'
  - 智能备份
- - '###'
  - Azure VM 上的 AlwaysOn 配置
- - '###'
  - 总结
- - '###'
  - 补充参考
- - '###'
  - 理解虚拟机性能
- - '####'
  - 计算
- - '####'
  - 网络
- - '####'
  - 存储
- - '####'
  - 数据磁盘
- - '####'
  - 存储空间
- - '####'
  - Tempdb
- - '####'
  - 数据库设置
- - '####'
  - 服务账户权限
- - '####'
  - 备份
- - '####'
  - 位于 Azure Blob 上的数据文件
- - '####'
  - 监控
- - '####'
  - 操作见解
- - '###'
  - 速查表
- - '###'
  - 总结
- - '###'
  - SQL Database 架构
- - '####'
  - 租户环
- - '####'
  - 控制环
- - '###'
  - Azure SQL Database 服务层级
- - '###'
  - 弹性数据库池
- - '###'
  - 服务层级：限制与能力
- - '###'
  - 管理工具
- - '####'
  - Azure 门户
- - '####'
  - SQL Server Management Studio
- - '####'
  - SQL Server 数据工具 (SSDT)
- - '####'
  - 命令行实用工具和 REST API
- - '###'
  - Azure SQL Database 与 Azure VM 上的 SQL Server 对比
- - '###'
  - 迁移到 Azure SQL Database
- - '####'
  - SQLPackage.exe
- - '####'
  - SQL Server Management Studio
- - '####'
  - 执行数据库迁移
- - '###'
  - 总结
- - '###'
  - Azure SQL Database：业务连续性与灾难恢复
- - '###'
  - 本地冗余
- - '###'
  - 时间点还原
- - '###'
  - 异地还原
- - '###'
  - 异地复制
- - '###'
  - SQL Server 复制
- - '###'
  - Azure SQL Database：安全与审核
- - '###'
  - 防火墙管理
- - '###'
  - 身份验证与授权
- - '###'
  - SQL Database 审核
- - '###'
  - SQL Database 威胁检测
- - '###'
  - 加密
- - '###'
  - 总结
- - '###'
  - 什么是 DTU？
- - '###'
  - 选择性能级别
- - '###'
  - 更改性能级别
- - '####'
  - 使用 PowerShell 更改服务层级或性能级别
- - '####'
  - 使用 Azure 门户更改服务层级或性能级别
- - '###'
  - Azure SQL 性能优化功能
- - '####'
  - 内存中优化
- - '####'
  - SQL Database 索引顾问
- - '####'
  - SQL Database 查询性能洞察
- - '###'
  - 监控 SQL Database
- - '####'
  - 使用 Azure 门户
- - '####'
  - 使用 DMV 和目录视图
- - '####'
  - 使用扩展事件
- - '###'
  - 总结
- - '#'
  - 1. 微软 Azure 简介
- - '##'
  - 云计算概述
- - '##'
  - 云计算的特征
- - '##'
  - 服务模型
- - '###'
  - 平台即服务
- - '###'
  - 基础设施即服务
- - '###'
  - 软件即服务
- - '##'
  - Microsoft Azure
- - '##'
  - Azure 服务
- - '###'
  - 计算产品
- - '####'
  - 虚拟机
- - '####'
  - Azure WebApps（前身为 Azure 网站）
- - '####'
  - 云服务
- - '###'
  - 数据管理产品
- - '#'
  - 在 Azure 虚拟机上运行的 SQL/Oracle
- - '#'
  - Azure SQL 数据库
- - '#'
  - Azure Blob 存储
- - '#'
  - Azure 表存储
- - '#'
  - 网络
- - '##'
  - 虚拟网络
- - '##'
  - VPN 连接选项
- - '###'
  - 点到站点 VPN 连接
- - '###'
  - 站点到站点 VPN 连接
- - '###'
  - ExpressRoute 连接
- - '#'
  - 开发者服务
- - '##'
  - Visual Studio Team Services
- - '##'
  - Application Insights
- - '#'
  - 身份与访问管理
- - '##'
  - Active Directory
- - '#'
  - 备份
- - '##'
  - Azure Site Recovery
- - '##'
  - 小结
- - '#'
  - 2. Azure 架构
- - '##'
  - Azure 服务
- - '##'
  - 计算资源
- - '##'
  - 存储
- - '##'
  - 网络
- - '##'
  - 协同工作原理
- - '##'
  - 更新/升级域
- - '##'
  - 故障域
- - '##'
  - 部署
- - '###'
  - 经典部署模型
- - '###'
  - 资源管理器部署模型
- - '###'
  - 部署自动化
- - '##'
  - 摘要
- - '#'
  - 3. Microsoft Azure 存储
- - '##'
  - Azure 存储服务
- - '###'
  - Blob 存储
- - '###'
  - 表存储
- - '###'
  - 队列存储
- - '###'
  - 文件存储
- - '###'
  - 设计决策
- - '##'
  - Azure 存储架构内部原理
- - '###'
  - 复制引擎
- - '###'
  - 存储戳内的层次结构
- - '###'
  - 维护读取请求的可用性/一致性
- - '###'
  - 分区层的负载均衡
- - '###'
  - DFS 层的负载均衡
- - '###'
  - DFS 容量的负载均衡
- - '##'
  - Azure 存储提供的持久性
- - '###'
  - Azure 高级存储
- - '##'
  - 使用高级存储和 PowerShell 创建 Azure 虚拟机
- - '##'
  - 高级存储内部机制
- - '##'
  - Azure 存储最佳实践
- - '###'
  - 使用 Blob 提升性能
- - '####'
  - 复制/移动 Blob
- - '####'
  - AzCopy
- - '####'
  - 选择合适的 Blob 类型
- - '###'
  - 使用表进行性能提升
- - '##'
  - 查询数据最佳实践
- - '##'
  - 总结
- - '#'
  - 4. Microsoft Azure 网络
- - '##'
  - 网络入门
- - '###'
  - 站点到站点连接
- - '###'
  - 点到站点连接
- - '###'
  - ExpressRoute
- - '##'
  - Azure AD Connect
- - '##'
  - 流量管理器
- - '##'
  - 虚拟专用网络
- - '###'
  - 负载均衡器
- - '###'
  - Azure DNS
- - '##'
  - 总结
- - '#'
  - 5. 在 Azure VM 上部署 SQL Server
- - '##'
  - 部署独立的 SQL Server 实例
- - '###'
  - 配置设置
- - '####'
  - 虚拟机区域
- - '####'
  - 虚拟机硬件
- - '####'
  - 监控与可用性集
- - '####'
  - SQL Server 设置
- - '##'
  - 自动化
- - '###'
  - 用于 Azure 自动化的 PowerShell
- - '####'
  - 安装 Azure PowerShell 模块
- - '####'
  - 将部署过程脚本化
- - '####'
  - 登录 Azure 订阅
- - '####'
  - 创建资源组和存储帐户
- - '####'
  - 选择虚拟机映像和大小
- - '####'
  - 配置可用性集和网络
- - '####'
  - 置备虚拟机
- - '##'
  - Azure 虚拟机部署与监控
- - '###'
  - 在 Azure 中创建虚拟机
- - '###'
  - 部署后
- - '###'
  - Azure Resource Explorer
- - '###'
  - Azure CLI
- - '##'
  - 总结
- - '#'
  - 6. SQL 混合解决方案
- - '##'
  - 混合模型概览
- - '##'
  - 备份到 Azure 存储
- - '###'
  - 步骤 1：为备份到 Azure 创建凭据
- - '###'
  - 步骤 2：发出备份数据库命令以备份到 Azure
- - '##'
  - Microsoft Azure 存储中的 SQL Server 文件
- - '###'
  - 创建数据文件和凭据
- - '###'
  - 优势与架构
- - '###'
  - 实施示例
- - '##'
  - 智能备份
- - '##'
  - 在 Azure 虚拟机上配置 AlwaysOn
- - '###'
  - 添加副本向导：指定副本
- - '##'
  - 总结
- - '#'
  - 7. 性能全解析
- - '##'
  - 理解虚拟机性能
- - '###'
  - 计算
- - '###'
  - 网络
- - '###'
  - 存储
- - '###'
  - 数据磁盘
- - '###'
  - 存储空间
- - '###'
  - Tempdb
- - '###'
  - 数据库设置
- - '###'
  - 服务账户权限
- - '###'
  - 备份
- - '###'
  - Azure Blobs 上的数据文件
- - '###'
  - 监控
- - '###'
  - 操作见解
- - '###'
  - 速查表
- - '###'
  - 本章小结
- - '#'
  - 8. Azure SQL Database
- - '##'
  - SQL Database 架构
- - '###'
  - 租户环
- - '###'
  - 控制环
- - '####'
  - 控制管理节点
- - '####'
  - 管理服务节点
- - '####'
  - 重定向器服务节点
- - '##'
  - Azure SQL Database 服务层级
- - '###'
  - 弹性数据库池
- - '###'
  - 服务层级：限制与功能
- - '##'
  - 管理工具
- - '###'
  - Azure 门户
- - '####'
  - 创建数据库
- - '####'
  - 管理数据库属性
- - '###'
  - SQL Server Management Studio
- - '###'
  - SQL Server Data Tools (SSDT)
- - '###'
  - 命令行实用程序和 REST API
- - '##'
  - Azure SQL Database 与 Azure VM 上的 SQL Server
- - '##'
  - 迁移到 Azure SQL Database
- - '###'
  - SQLPackage.exe
- - '###'
  - SQL Server Management Studio
- - '###'
  - 执行数据库迁移
- - '###'
  - 导出/导入 Bacpac 文件
- - '###'
  - SSMS “部署到 Azure SQL 数据库”向导
- - '###'
  - 使用事务复制
- - '##'
  - 小结
- - '#'
  - 9. Azure SQL 数据库的业务连续性与安全性
- - '##'
  - Azure SQL 数据库：业务连续性与灾难恢复
- - '###'
  - 本地冗余
- - '###'
  - 时间点还原
- - '###'
  - 地理还原
- - '###'
  - 地理复制
- - '####'
  - 标准地理复制
- - '####'
  - 执行数据库故障转移
- - '####'
  - 活动地理复制
- - '###'
  - SQL Server 复制
- - '##'
  - Azure SQL 数据库：安全性与审核
- - '###'
  - 防火墙管理
- - '###'
  - 身份验证与授权
- - '####'
  - 行级安全
- - '####'
  - 动态数据屏蔽
- - '###'
  - SQL 数据库审核
- - '###'
  - SQL 数据库威胁检测
- - '###'
  - 加密
- - '####'
  - 连接加密
- - '####'
  - 透明数据加密
- - '####'
  - 单元级（或列数据）加密
- - '####'
  - 始终加密
- - '##'
  - 总结
- - '#'
  - 10. Azure SQL 数据库：性能与监控
- - '##'
  - 什么是 DTU？
- - '##'
  - 选择性能级别
- - '##'
  - 更改性能级别
- - '###'
  - 使用 PowerShell 更改服务层级或性能级别
- - '###'
  - 使用 Azure 门户更改服务层级或性能级别
- - '##'
  - Azure SQL 性能优化功能
- - '###'
  - 内存中优化
- - '###'
  - SQL 数据库索引顾问
- - '###'
  - SQL 数据库查询性能见解
- - '##'
  - 监控 SQL 数据库
- - '###'
  - 使用 Azure 门户
- - '###'
  - 使用动态管理视图和目录视图
- - '####'
  - 资源利用率
- - '####'
  - 数据库相关信息
- - '####'
  - 执行相关信息
- - '###'
  - 使用扩展事件
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - Microsoft Azure
- - '##'
  - 计算产品
- - '##'
  - 数据管理产品
- - '##'
  - 开发人员服务
- - '##'
  - 网络
- - '##'
  - 存储
- - '##'
  - 安全与审核
- - '##'
  - 工具和实用程序
- - '##'
  - 概念和术语
