name: Oracle Enterprise Manager 12c Command-Line Interface
name_cn: Oracle Enterprise Manager 12c 命令行界面
slug: oracle-enterprise-manager-12c-command-line-interface
toc:
- - '#'
  - Oracle Enterprise Manager 12c 命令行界面
- - '##'
  - 作者
- - '##'
  - 版权信息
- - '##'
  - 出版团队
- - '##'
  - 发行信息
- - '##'
  - 献辞
- - '##'
  - 目录概览
- - '##'
  - 详细目录
- - '#'
  - 第二章：命令与任务
- - '#'
  - 第三章：术语与基础
- - '##'
  - 术语：动词
- - '##'
  - 模式
- - '##'
  - 帮助！
- - '##'
  - 理解错误代码
- - '##'
  - 语法
- - '##'
  - 设置
- - '##'
  - 通信
- - '##'
  - '`EMCLI`'
- - '##'
  - '`EMCTL`'
- - '##'
  - '`EMCTL` 与 `EMCLI`'
- - '##'
  - 任务：建立登录
- - '##'
  - 任务：获取目标列表
- - '##'
  - 任务：使用 `Blackouts`
- - '##'
  - 任务：创建目标
- - '##'
  - 任务：操作 `Jobs`
- - '##'
  - 小结
- - '#'
  - 第四章：命令行操作
- - '##'
  - 启动 `EMCLI` 会话
- - '##'
  - '`CLI` 参考'
- - '##'
  - '`get_targets` 动词'
- - '##'
  - 输出格式
- - '##'
  - '`Agent` 管理'
- - '##'
  - 使用 `EMCLI` 删除 `EM` 目标
- - '###'
  - 查找精确的目标名称
- - '###'
  - 删除目标
- - '##'
  - 如何用一条命令移除 `Enterprise Manager Agent`
- - '##'
  - 将目标传输到另一个 `EM Agent`
- - '###'
  - 工作原理
- - '###'
  - '`OMS` 介导的目标'
- - '##'
  - 管理 `OEM` 管理员
- - '###'
  - 角色管理
- - '###'
  - 跟踪管理服务器登录
- - '##'
  - 小结
- - '#'
  - 第五章：通过 `Shell` 脚本实现自动化
- - '##'
  - '`Shell` 脚本编写最佳实践'
- - '###'
  - 日志记录
- - '###'
  - 重定向
- - '###'
  - 错误处理
- - '##'
  - 密码与 `Shell` 脚本
- - '##'
  - 从 `Shell` 脚本调用 `EMCLI`
- - '##'
  - '`Shell` 脚本函数'
- - '###'
  - '`GetTargetName` 函数'
- - '###'
  - '`Name` 参数'
- - '###'
  - '`Add Targets` 参数'
- - '###'
  - '`Schedule` 参数'
- - '###'
  - 定时 `Blackouts` 的稳健解决方案
- - '##'
  - 小结
- - '#'
  - 第六章：高级脚本
- - '##'
  - '`Python` 的历史'
- - '##'
  - '`Jython`'
- - '##'
  - '`JSON`'
- - '##'
  - 入门
- - '###'
  - '`Hello World!`'
- - '#'
  - 关于作者
- - '#'
  - 关于技术评审者
- - '#'
  - 第一章
- - '##'
  - 架构
- - '###'
  - 企业管理器框架
- - '###'
  - '`EMCLI` 动词'
- - '#'
  - '`EMCLI` 使用指南与示例'
- - '##'
  - 输出列
- - '##'
  - 示例
- - '##'
  - '`EMCLI` 客户端软件'
- - '##'
  - '`EMCLI` 与 `EMCTL`'
- - '##'
  - 代理启动与停止
- - '##'
  - 集中管理
- - '##'
  - 访问控制
- - '##'
  - 安全保护
- - '#'
  - 第二章
- - '##'
  - 安全框架、安装与 `EM12c` 第 4 版
- - '##'
  - '`EMCLI` 与 `WebLogic` 安装'
- - '#'
  - '`WebLogic` 服务器配置要求与概览'
- - '##'
  - 要求
- - '##'
  - 创建 `WebLogic` 域配置文件
- - '##'
  - 图 2-12. 通过作为作业一部分创建的工作文件，从命令行查看作业状态
- - '##'
  - 过滤掉 `Fusion Middleware`
- - '###'
  - 获取 `GUID` 并创建属性文件
- - '##'
  - 图 2-13. 用于通过 `EMCLI` 满足进程调用请求的已填写属性文件示例
- - '###'
  - 扩展中间件部署
- - '##'
  - '`Jython`'
- - '##'
  - 支持的 `Java` 版本
- - '##'
  - 路径和环境变量
- - '#'
  - 客户端或远程目标安装
- - '##'
  - 考虑原因
- - '##'
  - 安装概述
- - '##'
  - 先决条件
- - '##'
  - 下载套件
- - '##'
  - 设置环境
- - '##'
  - 安装命令
- - '###'
  - '`EMCLI` 高级工具包'
- - '###'
  - 通过 `OMS` 安装 `EMCLI`
- - '###'
  - 安装后配置
- - '###'
  - 补丁与升级
- - '####'
  - 使用 `EMCLI` 客户端打补丁
- - '###'
  - '`EM` 安全框架'
- - '###'
  - '`EMCLI` 中的安全性'
- - '##'
  - '`EMCLI` 安全架构与关键功能'
- - '###'
  - '`EMCLI` 设置的安全模式'
- - '###'
  - '`HTTPS` 受信证书'
- - '###'
  - 第 4 版中的重要动词
- - '####'
  - 金质代理更新动词
- - '####'
  - '`BI` 发布报表动词'
- - '####'
  - 云服务动词
- - '####'
  - 其他动词
- - '####'
  - '`Fusion Middleware` 配置动词'
- - '####'
  - 作业动词
- - '####'
  - 目标数据动词
- - '#'
  - 第三章
- - '##'
  - 概要
- - '##'
  - 术语与基础
- - '###'
  - 术语：动词
- - '###'
  - 模式
- - '####'
  - 命令行模式
- - '####'
  - 交互模式
- - '####'
  - 脚本模式
- - '###'
  - 帮助！
- - '##'
  - 理解错误代码
- - '##'
  - 语法
- - '##'
  - 设置
- - '#'
  - '`EMCLI` 和 `EMCTL` 使用指南'
- - '##'
  - 通信方式
- - '###'
  - '`EMCLI`'
- - '###'
  - '`EMCTL`'
- - '###'
  - '`EMCTL` 与 `EMCLI` 的比较'
- - '##'
  - 任务：建立登录
- - '###'
  - 创建登录脚本
- - '###'
  - 在交互模式下建立登录
- - '###'
  - 在脚本模式下建立登录
- - '##'
  - 任务：获取目标列表
- - '###'
  - 检索所有目标信息
- - '###'
  - 筛选检索到的目标
- - '###'
  - 在筛选器中使用通配符
- - '###'
  - 在交互和脚本模式下使用 `get_targets`
- - '##'
  - 任务：使用停机维护
- - '##'
  - 任务：创建目标
- - '#'
  - 添加数据库集群目标与 `EMCLI` 作业管理
- - '##'
  - 添加数据库集群目标
- - '##'
  - 使用 `EMCLI` 添加目标
- - '##'
  - 任务：操作作业
- - '##'
  - 通过属性文件创建作业
- - '##'
  - 创建库作业
- - '##'
  - 总结
- - '#'
  - 第四章
- - '##'
  - 在命令行工作
- - '###'
  - 启动一个 `EMCLI` 会话
- - '###'
  - '`CLI` 参考'
- - '###'
  - '`get_targets` 动词'
- - '###'
  - 输出格式
- - '##'
  - 代理管理
- - '##'
  - 使用 `EMCLI` 删除 `EM` 目标
- - '###'
  - 查找确切的目标名称
- - '###'
  - 删除目标
- - '##'
  - 如何用一条命令移除 `Enterprise Manager` 代理
- - '##'
  - 监视目标的删除与代理管理
- - '##'
  - 将目标转移到另一个 `EM` 代理
- - '###'
  - 工作原理
- - '###'
  - '`OMS` 介导的目标'
- - '##'
  - 管理 `OEM` 管理员
- - '###'
  - 角色管理
- - '###'
  - 跟踪管理服务器登录
- - '##'
  - 总结
- - '#'
  - 第五章
- - '##'
  - 通过 `Shell` 脚本实现自动化
- - '###'
  - '`Shell` 脚本编写最佳实践'
- - '####'
  - 日志记录
- - '####'
  - 重定向
- - '####'
  - 错误处理
- - '###'
  - 密码与 `Shell` 脚本
- - '##'
  - 从 `Shell` 脚本调用 `EMCLI`
- - '##'
  - '`Shell` 脚本函数'
- - '###'
  - '`GetTargetName` 函数'
- - '##'
  - 使用 `EMCLI` 管理停机维护 (`Blackouts`)
- - '###'
  - '`Name` 参数'
- - '##'
  - 添加目标参数
- - '##'
  - 计划参数
- - '##'
  - 计划停用的一个健壮解决方案
- - '##'
  - 使用 `Shell` 脚本创建和停止停用
- - '##'
  - 创建和使用函数库
- - '##'
  - '`EMCTL` 或 `EMCLI`'
- - '##'
  - 使用 `EMCLI` 管理 `OEM` 管理员
- - '###'
  - 角色管理
- - '###'
  - 使用 `Argfile` 进行批处理
- - '###'
  - 从文本文件填充 `Argfile`
- - '#'
  - 使用 `EMCLI` 进行高级管理
- - '##'
  - 准备参数文件
- - '##'
  - 在 `OMS` 实例间克隆 `OEM` 角色和用户
- - '##'
  - 更改 `EM` 管理员引用
- - '##'
  - '`Shell Getopts` 命令'
- - '#'
  - 第六章 高级脚本编写
- - '##'
  - 概述
- - '##'
  - 命令行输入的处理
- - '##'
  - 使用参数文件更新目标属性
- - '##'
  - 总结
- - '##'
  - '`Python` 的历史'
- - '#'
  - '`Python`、`Jython` 与 `EMCLI` 入门指南'
- - '##'
  - '`Jython`'
- - '##'
  - '`JSON`'
- - '##'
  - 入门
- - '##'
  - '`Hello World!`'
- - '##'
  - 查找帮助
- - '#'
  - '`Python` 帮助系统与基础对象'
- - '##'
  - 使用 `Python` 帮助系统
- - '##'
  - '`EMCLI` 中的 `help` 函数'
- - '##'
  - '`Python` 对象'
- - '###'
  - 数字和字符串
- - '###'
  - 列表
- - '####'
  - 简单列表
- - '#'
  - '`EMCLI` 中的列表'
- - '#'
  - 字符串与列表
- - '##'
  - 清单 6-1. 在 `Linux` 中查找 `Oracle` 数据库监听器进程
- - '##'
  - 清单 6-2. 使用 `awk` 解析进程详细信息
- - '##'
  - 清单 6-3. 使用 `Python` 解析进程详细信息
- - '##'
  - 清单 6-4. 将清单 6-3 中的命令合并为单条命令
- - '##'
  - 清单 6-3a. 使用 `Python subprocess` 模块捕获 `ps` 命令输出
- - '#'
  - 字典
- - '##'
  - 清单 6-5. 通过指定所属键来从字典调用值
- - '##'
  - 清单 6-6. 在 `EMCLI` 中使用 `list()` 函数展示 `JSON` 字典
- - '##'
  - 登录脚本
- - '##'
  - 使用 `EMCLI` 的 `Python` 脚本设置目标属性
- - '##'
  - 使用 `EMCLI` 设置目标属性的 `Python` 类
- - '##'
  - 使用 `updateProps` 类更新目标属性
- - '###'
  - 使用 `updateProps()` 类
- - '###'
  - 理解代码
- - '#'
  - '`__init__()` 函数'
- - '#'
  - '`__loadtargobjects()` 函数'
- - '#'
  - '`props()` 函数'
- - '#'
  - '`filt()` 函数'
- - '##'
  - 总结
- - '#'
  - 第七章
- - '##'
  - 使用软件库和 `Oracle` 可扩展性交换中心
- - '###'
  - '`OEM` 软件库'
- - '##'
  - 设置软件库存储
- - '#'
  - 使用 `EMCLI` 管理 `Oracle Enterprise Manager 12c` 软件库
- - '##'
  - 创建软件库位置
- - '##'
  - 在软件库中创建文件夹
- - '##'
  - 将脚本添加到软件库
- - '#'
  - '`Enterprise Manager 12c Cloud Control` 中的软件库与 `CLI` 作业操作'
- - '##'
  - 构建报告定义库
- - '##'
  - 使用 `CLI` 调用的 `OEM` 作业
- - '###'
  - 创建作业
- - '###'
  - 步骤 1：升级代理
- - '#'
  - 扩展性交换平台概述
- - '##'
  - 搜索与最近更新
- - '##'
  - 标签化搜索
- - '##'
  - 执行搜索
- - '##'
  - 插件详情页面
- - '##'
  - 经典视图
- - '##'
  - 开发资源
- - '##'
  - 贡献
- - '##'
  - 概览
- - '##'
  - 总结
- - '#'
  - 第八章：`EMCLI` 脚本示例
- - '##'
  - 第 1 节：函数库和 `Shell` 脚本
- - '###'
  - 命令行输入
- - '##'
  - 存活性证据
- - '##'
  - 示例函数库
- - '##'
  - '`EMCLI` 函数库与示例脚本'
- - '##'
  - 创建停机维护 (`Blackout`)
- - '##'
  - 停止停机维护 (`Blackout`)
- - '##'
  - 代理同步
- - '###'
  - 重新同步不可达的代理
- - '###'
  - 保护所有代理
- - '##'
  - 用户账户凭据
- - '###'
  - 设置数据库用户凭据
- - '###'
  - 设置用户凭据
- - '##'
  - 与函数相关的 `Shell` 脚本
- - '###'
  - 示例脚本：`emcli_start_blackout.ksh`
- - '###'
  - 示例脚本：`emcli_stop_blackout.ksh`
- - '##'
  - 第 2 节：`EMCLI` 与 `Veritas Cluster Server`
- - '###'
  - 程序逻辑
- - '###'
  - '`Veritas Cluster Server`'
- - '###'
  - '`Oracle Enterprise Manager`'
- - '###'
  - 实现
- - '#'
  - '示例脚本: `emcli_relocate_target_vcs.ksh`'
- - '##'
  - 函数
- - '###'
  - '`CleanUpFiles`'
- - '###'
  - '`ExitCleanly`'
- - '###'
  - '`ExitDirty`'
- - '###'
  - '`ListNicely`'
- - '##'
  - 运行时过程
- - '##'
  - 第 3 节：必要的服务器管理脚本
- - '##'
  - 配置备份脚本
- - '##'
  - 临时文件清理脚本
- - '##'
  - 第 4 节：`EMCLI` 脚本与交互式脚本
- - '###'
  - 简单登录脚本 (`start.py`)
- - '###'
  - 安全登录脚本 (`secureStart.py`)
- - '###'
  - 更新目标属性命令 (`updatePropsFunc.py`)
- - '##'
  - 更新目标属性类 (`updateProps.py`)
- - '##'
  - 索引
- - '#'
  - 企业管理器命令行界面 (`EMCLI`)
- - '##'
  - 动词
- - '##'
  - 模式
- - '##'
  - 脚本
- - '##'
  - 其他概念
- - '##'
  - 组件与相关工具
- - '#'
  - L, M, N
- - '##'
  - '`Jython`'
- - '##'
  - 监听器进程
- - '##'
  - 登录脚本
- - '#'
  - O
- - '##'
  - '`OEM` 作业, `EMCLI`'
- - '###'
  - '`create_job` 动词'
- - '###'
  - 创建和升级作业
- - '###'
  - 移除代理
- - '###'
  - 升级代理
- - '##'
  - '`OEM` 软件库。参见软件库'
- - '##'
  - '`Oracle` 可扩展性交换中心'
- - '###'
  - 优势
- - '###'
  - “概览”选项卡
- - '###'
  - 经典视图
- - '###'
  - '`EMC` 插件对比'
- - '###'
  - “贡献”选项卡
- - '###'
  - '`Fusion ION Accelerator` 插件'
- - '###'
  - 全局访问
- - '###'
  - 标题页
- - '###'
  - 主页
- - '###'
  - 链接
- - '###'
  - 卸载和导出功能
- - '###'
  - 搜索栏视图
- - '###'
  - 二级搜索页面
- - '###'
  - 标签搜索
- - '#'
  - P, Q
- - '##'
  - 打补丁过程
- - '###'
  - 远程客户端安装
- - '###'
  - 模板
- - '###'
  - 使用 `EMCLI` 客户端
- - '##'
  - '`Python`'
- - '###'
  - 你好，世界
- - '###'
  - '`help()` 函数'
- - '###'
  - 登录脚本
- - '###'
  - 对象
- - '####'
  - 字典
- - '####'
  - '`EMCLI` 列表'
- - '####'
  - '`len()` 函数'
- - '####'
  - 监听器进程
- - '####'
  - 列表
- - '####'
  - 数字和字符串
- - '###'
  - 概述
- - '###'
  - 目标属性
- - '###'
  - '`updateProps()` 类'
- - '###'
  - '`EMCLI` 目标'
- - '####'
  - '`filt()` 函数'
- - '####'
  - '`__init__()` 函数'
- - '####'
  - '`__loadtargobjects()` 函数'
- - '####'
  - '`props()` 函数'
- - '####'
  - '`setprops()` 函数'
- - '####'
  - '`show()` 函数'
- - '####'
  - '`showprops()` 函数'
- - '#'
  - R
- - '##'
  - 远程目标安装
- - '###'
  - 关联目录
- - '###'
  - 下载和部署
- - '###'
  - 效率
- - '###'
  - '`emclikit.jar` 文件'
- - '###'
  - '`Java` 路径'
- - '###'
  - 要求
- - '###'
  - 安全性
- - '##'
  - 报表定义库
- - '#'
  - S, T, U
- - '##'
  - 计划中断 (`Blackouts`)
- - '###'
  - 管理员参考
- - '###'
  - 参数文件创建
- - '###'
  - 批处理
