name: Visual Design of GraphQL Data
name_cn: GraphQL 数据的视觉设计
slug: visual-design-of-graphql-data
toc:
- - '###'
  - 关于作者
- - '###'
  - 关于技术评审者
- - '##'
  - 邮件图数据模型
- - '##'
  - GraphQL 模式
- - '##'
  - 基于互联网消息格式 RFC5322，但有所简化
- - '##'
  - Copyright Thomas Frisendal, 2017
- - '#'
  - 5. 业务含义
- - '#'
  - 6. 呈现业务流程
- - '#'
  - 9. 从图到树
- - '#'
  - 12. 将 `GraphQL` 与新的图数据库结合使用
- - '##'
  - '`Neo4j-GraphQL` 集成的设计目标'
- - '###'
  - 问题 1：模式重复
- - '###'
  - 问题 2：服务器/客户端数据不匹配
- - '###'
  - 问题 3：多余的数据库调用
- - '###'
  - 问题 4：性能不佳
- - '###'
  - 问题 5：样板代码泛滥
- - '####'
  - A, B
- - '####'
  - C
- - '####'
  - D
- - '####'
  - E, F
- - '####'
  - G, H, I, J, K, L, M
- - '####'
  - N
- - '####'
  - O
- - '####'
  - P, Q, R
- - '####'
  - S
- - '####'
  - T, U, V, W, X, Y, Z
