name: Expert Apache Cassandra Administration
name_cn: Apache Cassandra 高级管理指南
slug: expert-apache-cassandra-administration
toc:
- - '#'
  - Sam R. Alapati 精通 Apache Cassandra 管理
- - '##'
  - 补充材料
- - '##'
  - 出版信息
- - '##'
  - 版权声明
- - '##'
  - 献词
- - '##'
  - 致谢
- - '#'
  - 第一部分：简介、安装与配置
- - '##'
  - 第 1 章：Apache Cassandra 简介
- - '###'
  - 什么是 Cassandra？
- - '###'
  - 开源数据库
- - '###'
  - 容错性
- - '###'
  - 高性能
- - '###'
  - 分布式配置与高韧性
- - '###'
  - 灵活性
- - '###'
  - 使用廉价服务器
- - '###'
  - 易于管理
- - '###'
  - 高度可扩展
- - '###'
  - 这还是熟悉的 SQL！
- - '###'
  - 关系型数据库带来的问题
- - '###'
  - 关系数据库管理系统与大数据
- - '###'
  - NoSQL 数据库的兴起
- - '###'
  - 键值数据库
- - '###'
  - 文档数据库
- - '###'
  - 列族数据库
- - '###'
  - 图数据库
- - '###'
  - Cassandra 的特殊能力
- - '###'
  - 分布式与去中心化数据库
- - '###'
  - 日志结构存储引擎
- - '###'
  - 本地管理存储
- - '###'
  - 处理多种类型数据的能力
- - '###'
  - 面向行
- - '###'
  - 一致性、ACID 要求、CAP 定理与 BASE
- - '###'
  - ACID 要求
- - '###'
  - CAP 定理
- - '###'
  - Cassandra 的缺点
- - '###'
  - 查询数据的问题
- - '###'
  - 写入数据的问题
- - '###'
  - 谁应该使用 Cassandra？
- - '###'
  - Cassandra 优化
- - '###'
  - 数据缓存
- - '###'
  - 压缩
- - '###'
  - 布隆过滤器
- - '###'
  - 压实
- - '###'
  - Cassandra 适合您吗？
- - '###'
  - Cassandra 数据建模基础
- - '###'
  - 根据查询构建数据结构
- - '###'
  - 避免更新和删除
- - '###'
  - 均匀分布数据
- - '###'
  - 避免跨分区查询
- - '###'
  - Cassandra 管理员应知事项
- - '###'
  - Cassandra 工具
- - '###'
  - 获取并行远程工具
- - '###'
  - 理解 Cassandra 数据库中的故障场景
- - '###'
  - 监控与告警
- - '###'
  - 调优 Java 虚拟机
- - '###'
  - Cassandra 架构快速导览
- - '###'
  - 理解 Cassandra 特定概念
- - '###'
  - Cassandra 如何存储数据
- - '###'
  - Cassandra 数据模型概览
- - '###'
  - DataStax 与 Cassandra
- - '###'
  - DataStax 企业版
- - '###'
  - DataStax 开发工具
- - '###'
  - 本章小结
- - '##'
  - 第 2 章：安装 Cassandra 并开始使用 CQL Shell
- - '###'
  - 安装 Apache Cassandra
- - '###'
  - 安装规划
- - '###'
  - 安装 Cassandra 的先决条件
- - '###'
  - 安装 Cassandra
- - '###'
  - 配置 Cassandra
- - '###'
  - '`cassandra.yaml` 文件的位置'
- - '###'
  - 必须设置的最小配置属性
- - '###'
  - 配置防火墙
- - '###'
  - 探索 CQL Shell
- - '###'
  - 启动 CQL Shell
- - '###'
  - '`cqlsh` 中的时区'
- - '###'
  - 在 CQL Shell 中获取帮助
- - '###'
  - 命令行 CQL Shell 选项
- - '###'
  - Cassandra 安装目录
- - '###'
  - '`bin` 目录'
- - '###'
  - '`tools` 目录'
- - '###'
  - '`lib` 目录'
- - '###'
  - '`conf` 目录'
- - '###'
  - Javadoc 目录
- - '###'
  - 启动和停止 Cassandra
- - '###'
  - 启动 Cassandra
- - '###'
  - 检查 Cassandra 的状态
- - '###'
  - 使用 `service` 命令启动和停止
- - '###'
  - 清除 Cassandra 数据
- - '###'
  - 验证 Cassandra 版本
- - '###'
  - 配置 `cqlsh`
- - '###'
  - 通过 `cqlshrc` 配置文件配置
- - '###'
  - 通过在命令行指定选项配置
- - '###'
  - 查找版本
- - '###'
  - '`Cqlsh` 选项'
- - '###'
  - 实践 Cassandra
- - '###'
  - 连接到 CQL Shell
- - '###'
  - 创建键空间
- - '###'
  - 创建表
- - '###'
  - 插入测试数据
- - '###'
  - 查询表
- - '###'
  - 获取命令历史记录
- - '###'
  - 本章小结
- - '##'
  - 第 3 章：部署 Cassandra 集群
- - '###'
  - 规划集群部署
- - '###'
  - 使用 `cassandra-stress` 规划生产部署
- - '###'
  - 选择内存
- - '###'
  - 选择 CPU
- - '###'
  - 网络考虑
- - '###'
  - 选择存储
- - '###'
  - 为 Linux 服务器选择生产设置
- - '###'
  - 安装 PDSH
- - '###'
  - 初始化 Cassandra 多节点集群（单数据中心与多数据中心）
- - '###'
  - 先决条件
- - '###'
  - 配置集群
- - '###'
  - 初始化多数据中心集群
- - '###'
  - 启动和停止多节点集群
- - '###'
  - 集群中节点的启动过程
- - '###'
  - 初期常见错误
- - '###'
  - 在 Amazon EC2 上运行 Cassandra
- - '###'
  - 使用可信 AMI
- - '###'
  - 为 Cassandra 设置 AWS 实例
- - '###'
  - 安装 Cassandra
- - '###'
  - 配置 Cassandra 集群
- - '###'
  - 本章小结
- - '#'
  - 第二部分：数据模型、集群架构与 Cassandra 查询语言
- - '##'
  - 第 4 章：Cassandra 数据建模以及数据的读写
- - '###'
  - Cassandra 与关系型数据库：主要区别
- - '###'
  - 数据驱动 vs. 查询驱动的数据建模
- - '###'
  - 表连接与参照完整性
- - '###'
  - 排序差异
- - '###'
  - 数据重复
- - '###'
  - 什么是数据建模？
- - '###'
  - 分析需求
- - '###'
  - 概念建模：识别实体及其关系
- - '###'
  - 审视您想使用的查询
- - '###'
  - 逻辑建模
- - '###'
  - 物理数据建模
- - '###'
  - Cassandra 数据建模规则
- - '###'
  - 两条基本规则
- - '###'
  - 围绕查询而非关系建模
- - '###'
  - Cassandra 的性能限制
- - '###'
  - 写入限制
- - '###'
  - 读取限制
- - '###'
  - 最终一致性概念
- - '###'
  - 一致性冲突解决
- - '###'
  - 修复数据
- - '###'
  - Cassandra 如何写入数据
- - '###'
  - 写入提交日志以保护更改
- - '###'
  - 写入 Memtable 以实现持久性
- - '###'
  - 写入 SSTable 以实现持久存储
- - '###'
  - 写入请求流程
- - '###'
  - 读取数据
- - '###'
  - Cassandra 读取路径
- - '###'
  - 写入模式如何影响读取
- - '###'
  - Cassandra 事务与 ACID 属性
- - '###'
  - 原子性
- - '###'
  - 隔离性
- - '###'
  - 持久性
- - '###'
  - 处理一致性
- - '###'
  - 写入一致性
- - '###'
  - 计算仲裁
- - '###'
  - 读取一致性
- - '###'
  - 配置一致性级别
- - '###'
  - 三种读取请求类型
- - '###'
  - 测试一致性级别的性能
- - '###'
  - 使用批处理操作确保原子性
- - '###'
  - 配置批处理操作
- - '###'
  - 单分区和多分区批处理操作
- - '###'
  - 何时使用批处理操作是好的
- - '###'
  - 轻量级事务
- - '###'
  - 执行轻量级事务
- - '###'
  - 轻量级事务如何工作
- - '###'
  - 使用轻量级事务时的注意事项
- - '###'
  - 本章小结
- - '##'
  - 第 5 章：Cassandra 架构
- - '###'
  - 基本集群术语
- - '###'
  - 副本放置策略
- - '###'
  - Cassandra 如何存储数据
- - '###'
  - Gossip 协议及其如何帮助节点通信
- - '###'
  - 配置 Gossip 设置
- - '###'
  - 种子节点与 Gossip
- - '###'
  - 故障检测与恢复
- - '###'
  - 修复节点
- - '###'
  - Hinted Handoff
- - '###'
  - 读取修复
- - '###'
  - 快速读取保护
- - '###'
  - 反熵修复
- - '###'
  - 执行手动（反熵）修复
- - '###'
  - 数据分布与复制
- - '###'
  - 虚拟节点与数据所有权
- - '###'
  - 数据如何在集群中分布
- - '###'
  - 如何分发令牌范围
- - '###'
  - 选择复制策略
- - '###'
  - 分区器与分区策略
- - '###'
  - Snitch
- - '###'
  - 本章小结
- - '##'
  - 第 6 章：Cassandra 查询语言入门
- - '###'
  - 使用键空间
- - '###'
  - 管理键空间
- - '###'
  - 创建键空间
- - '###'
  - 在具有多个数据中心的集群中创建键空间
- - '###'
  - 运行 `nodetool repair` 命令的必要性
- - '###'
  - 防止键空间向某些数据中心发送副本
- - '###'
  - 修复键空间
- - '###'
  - 使用键空间限定符
- - '###'
  - 移除键空间
- - '###'
  - 系统键空间
- - '###'
  - 创建表
- - '###'
  - 列定义
- - '###'
  - 主键、分区键与聚簇列
- - '###'
  - 分区键
- - '###'
  - 创建具有简单主键的表
- - '###'
  - 查看表的配置选项
- - '###'
  - 删除和截断表
- - '###'
  - 从表中删除行和列
- - '###'
  - Cassandra 数据库中的索引
- - '###'
  - 何时使用索引
- - '###'
  - 何时不使用二级索引
- - '###'
  - 创建二级索引
- - '###'
  - Cassandra 中的物化视图
- - '###'
  - 创建物化视图
- - '###'
  - 删除物化视图
- - '###'
  - 使用物化视图进行反规范化
- - '###'
  - 更新物化视图
- - '###'
  - 使用 SELECT 语句查询数据
- - '###'
  - 选择子句
- - '###'
  - WHERE 子句
- - '###'
  - 创建二级索引
- - '###'
  - 二级索引的缺点
- - '###'
  - SASI：二级索引的新实现
- - '###'
  - 编写条件语句
- - '###'
  - 使用 INSERT 语句插入数据
- - '###'
  - 使用 UPDATE 语句修改数据
- - '###'
  - 使用高级数据类型
- - '###'
  - 集合
- - '###'
  - 元组
- - '###'
  - 用户定义类型
- - '###'
  - 用户定义函数与用户定义聚合
- - '###'
  - 用户定义聚合函数
- - '###'
  - 内置函数和聚合
- - '###'
  - 本章小结
- - '##'
  - 第 7 章：Docker 上的 Cassandra、Apache Spark 与 Cassandra 集群管理器
- - '###'
  - Cassandra 与 Docker
- - '###'
  - Docker 快速导览
- - '###'
  - 在 Docker 上运行 Cassandra 集群
- - '###'
  - 为 Docker 设置 Cassandra 环境变量
- - '###'
  - 使用 Docker-Compose 和行为驱动开发创建 Cassandra 集群
- - '###'
  - 使用 Cassandra 集群管理器启动集群
- - '###'
  - 安装 CCM
- - '###'
  - 使用 CCM 创建 Cassandra 集群
- - '###'
  - 使用 CCM 工作
- - '###'
  - 将 Apache Spark 与 Cassandra 一起运行
- - '###'
  - 安装先决条件
- - '###'
  - 安装 Apache Spark
- - '###'
  - 配置 Spark 集群
- - '###'
  - 启动 Spark 集群
- - '###'
  - 从 Spark 集群连接到 Cassandra
- - '###'
  - 从 Spark 使用 Cassandra
- - '###'
  - Cassandra 与 SMACK 技术栈：日益增长的趋势
- - '###'
  - 本章小结
- - '##'
  - 第 8 章：备份、恢复与数据迁移
- - '###'
  - 备份数据
- - '###'
  - 管理快照
- - '###'
  - 执行增量备份
- - '###'
  - 使用各种恢复方法恢复数据
- - '###'
  - 从快照恢复数据
- - '###'
  - 使用 `sstableloader` 恢复快照
- - '###'
  - 节点重启方法步骤
- - '###'
  - 提交日志归档与时间点恢复
- - '###'
  - 将批量数据加载到 Cassandra
- - '###'
  - 使用 COPY 命令导入和导出数据
- - '###'
  - 从 Cassandra 表复制数据
- - '###'
  - 将数据复制到 Cassandra 表
- - '###'
  - 运行 `sstableloader` 执行批量加载
- - '###'
  - 本章小结
- - '#'
  - 第三部分：维护、监控、调优与保障 Apache Cassandra 安全
- - '##'
  - 第 9 章：维护 Cassandra
- - '###'
  - 常见集群维护任务
- - '###'
  - 修复数据 (`nodetool repair`)
- - '###'
  - 重建索引
- - '###'
  - 刷新表的大小估计
- - '###'
  - 关键的 Nodetool 维护命令
- - '###'
  - 退役节点 (`nodetool decommission`)
- - '###'
  - 清除节点 (`nodetool assassinate`)
- - '###'
  - 节点管理
- - '###'
  - 防止节点加入集群
- - '###'
  - 向数据中心添加节点
- - '###'
  - 替换正在运行的节点
- - '###'
  - 从集群中移除节点
- - '###'
  - 替换故障节点
- - '###'
  - 将节点移动到不同的机架
- - '###'
  - 退役整个数据中心
- - '###'
  - 切换 Snitch
- - '###'
  - 无拓扑变更
- - '###'
  - 有拓扑变更
- - '###'
  - 管理 Gossip
- - '###'
  - 获取 Gossip 信息
- - '###'
  - 刷新与清空数据：区别
- - '###'
  - 清空节点
- - '###'
  - 从 Memtable 刷新数据
- - '###'
  - 维护数据中心
- - '###'
  - 向集群添加数据中心
- - '###'
  - 退役数据中心
- - '###'
  - 处理数据损坏
- - '###'
  - 检查数据损坏
- - '###'
  - 修复损坏的数据
- - '###'
  - 管理 Handoff 和 Hints
- - '###'
  - 清除节点上的 Gossip 状态
- - '###'
  - 本章小结
- - '##'
  - 第 10 章：监控、日志与指标
- - '###'
  - '`nodetool proxyhistograms` 命令'
- - '###'
  - 获取表级统计信息
- - '###'
  - 从主机获取网络信息
- - '###'
  - '`nodetool tablehistograms` 命令'
- - '###'
  - 检查集群健康状态
- - '###'
  - '`nodetool status` 命令'
- - '###'
  - '`nodetool info` 命令'
- - '###'
  - 使用线程池统计信息 (`nodetool tpstats`)
- - '###'
  - 使用 JMX 客户端
- - '###'
  - JConsole
- - '###'
  - 日志记录
- - '###'
  - 设置日志记录位置
- - '###'
  - 通过 Logback 配置日志记录
- - '###'
  - Logback 日志框架
- - '###'
  - 使用 Nodetool 设置服务的日志级别
- - '###'
  - 使用 Nagios 监控 Cassandra
- - '###'
  - 安装 LAMP 技术栈并解决其他先决条件
- - '###'
  - 安装 Nagios
- - '###'
  - 安装 Nagios 插件
- - '###'
  - 安装 NRPE
- - '###'
  - 配置 Nagios 和 Apache
- - '###'
  - 配置 Apache
- - '###'
  - 添加要监控的 Cassandra 集群主机
- - '###'
  - 本章小结
- - '##'
  - 第 11 章：调优 Cassandra 性能
- - '###'
  - 使用追踪分析性能
- - '###'
  - 管理追踪
- - '###'
  - 如何追踪写入和读取请求
- - '###'
  - 调优布隆过滤器
- - '###'
  - 配置布隆过滤器
- - '###'
  - 重新生成布隆过滤器
- - '###'
  - 缓存数据
- - '###'
  - 数据缓存类型
- - '###'
  - Cassandra 在何处存储缓存数据
- - '###'
  - 配置缓存
- - '###'
  - 全局缓存参数
- - '###'
  - 使用计数器缓存
- - '###'
  - 监控缓存
- - '###'
  - 追踪数据库操作以优化缓存
- - '###'
  - 使用 `cassandra-stress` 对 Cassandra 进行压力测试
- - '###'
  - 运行 `cassandra-stress`
- - '###'
  - '`cassandra-stress` 示例'
- - '###'
  - 设置复制、压实和压缩选项
- - '###'
  - 使用基于 YAML 的配置文件运行 `cassandra-stress`
- - '###'
  - 配置压实策略
- - '###'
  - 压实策略
- - '###'
  - 启用和禁用压实
- - '###'
  - 配置全局压实属性
- - '###'
  - 设置压实策略
- - '###'
  - 记录压实活动
- - '###'
  - 测试压实策略的效果
- - '###'
  - 压缩数据以节省存储空间
- - '###'
  - 配置压缩
- - '###'
  - Cassandra 何时压缩数据
- - '###'
  - 修改压缩算法
- - '###'
  - 测试压缩的效果
- - '###'
  - 关闭压缩
- - '###'
  - 通过 Memtable 阈值提高写入性能
- - '###'
  - 调优 JVM
- - '###'
  - Java 垃圾回收
- - '###'
  - 选择正确的垃圾收集器
- - '###'
  - 使用 `nodetool proxyhistograms` 和 `tablehistograms` 命令
- - '###'
  - 本章小结
- - '##'
  - 第 12 章：保障 Cassandra 安全
- - '###'
  - 配置认证
- - '###'
  - 创建角色
- - '###'
  - 配置认证
- - '###'
  - 创建角色
- - '###'
  - 处理超级用户账户
- - '###'
  - 配置授权：授予资源权限
- - '###'
  - Cassandra 的访问控制矩阵
- - '###'
  - 配置基于角色的访问控制
- - '###'
  - 为登录账户创建角色
- - '###'
  - 向角色授予权限
- - '###'
  - Cassandra 中的对象权限
- - '###'
  - 向角色授予对象权限
- - '###'
  - 配置访问的防火墙端口
- - '###'
  - 使用 SSL 加密 Cassandra
- - '###'
  - 安装 Java 加密扩展文件
- - '###'
  - 准备服务器证书
- - '###'
  - 启用节点间加密
- - '###'
  - 启用客户端加密
- - '###'
  - JMX 认证与授权
- - '###'
  - 启用 JMX 认证与授权
- - '###'
  - 使用带认证的 `cqlsh`
- - '###'
  - 本章小结
