name: Query Store for SQL Server 2019
name_cn: SQL Server 2019 的 查询存储
slug: query-store-for-sql-server-2019
toc:
- - '##'
  - 引言
- - '###'
  - 关于作者与关于技术审校者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '##'
  - 1. 什么是查询存储？
- - '###'
  - 查询存储的实用性
- - '####'
  - 建立性能基线
- - '###'
  - 查询存储与性能基线
- - '####'
  - 什么是基线？
- - '####'
  - 查询存储如何提供基线
- - '####'
  - 目录视图
- - '####'
  - 稳定性能
- - '###'
  - 提示
- - '###'
  - 不使用查询存储的故障排除技术
- - '####'
  - SQL Server Profiler
- - '####'
  - 注意
- - '####'
  - 注意
- - '####'
  - SQL Server Profiler 概念
- - '####'
  - 与性能相关的 SQL Server Profiler 事件类
- - '#####'
  - 服务器端跟踪
- - '######'
  - 与查询存储相比，SQL Server Profiler 或服务器端跟踪的缺点
- - '#####'
  - 扩展事件
- - '######'
  - 扩展事件概念
- - '######'
  - 与查询存储相比，扩展事件的缺点
- - '######'
  - 与扩展事件相比，SQL Server Profiler 和服务器端跟踪的缺点
- - '#####'
  - 轻量级显示计划跟踪标志
- - '#####'
  - 注意
- - '#####'
  - sys.dm_exec_query_plan_stats
- - '#####'
  - DMV
- - '######'
  - DMV 的缺点
- - '###'
  - sp_whoisactive
- - '###'
  - 等待统计信息
- - '###'
  - 提示
- - '###'
  - 在查询存储技术之前稳定性能
- - '####'
  - 计划指南/USE PLAN 提示
- - '####'
  - 更新统计信息
- - '#####'
  - 重新编译存储过程
- - '#####'
  - 从计划缓存中移除计划
- - '###'
  - 查询存储：改变游戏规则者
- - '####'
  - 收集哪些信息
- - '####'
  - 查询存储为我们提供哪些信息：用例
- - '####'
  - 自动计划修正
- - '####'
  - 等待统计信息
- - '###'
  - 结论
- - '##'
  - 2. 查询存储概述与架构
- - '###'
  - 查询存储如何工作
- - '####'
  - 收集查询与计划信息
- - '####'
  - 收集查询运行时信息和等待统计信息
- - '####'
  - 数据收集通用说明
- - '###'
  - 查询存储收集的数据
- - '####'
  - 查询与查询计划信息
- - '####'
  - 运行时信息
- - '##'
  - 3. 配置查询存储
- - '###'
  - 等待统计
- - '###'
  - 关于查询存储的信息
- - '###'
  - 总结
- - '###'
  - 查询存储默认设置
- - '###'
  - 配置选项
- - '####'
  - OPERATION_MODE
- - '####'
  - CLEANUP_POLICY (STALE_QUERY_THRESHOLD_DAYS)
- - '####'
  - DATA_FLUSH_INTERVAL_SECONDS
- - '####'
  - MAX_STORAGE_SIZE_MB
- - '####'
  - INTERVAL_LENGTH_MINUTES
- - '####'
  - SIZE_BASED_CLEANUP_MODE
- - '####'
  - QUERY_STORE_CAPTURE_MODE
- - '####'
  - MAX_PLANS_PER_QUERY
- - '####'
  - WAIT_STATISTICS_CAPTURE_MODE
- - '####'
  - 使用 GUI 更改配置
- - '####'
  - 注意
- - '###'
  - 查询存储配置目录视图
- - '###'
  - 查询存储配置最佳实践
- - '####'
  - 参数化与查询存储
- - '####'
  - “删除并创建”与“更改”的影响
- - '####'
  - 数据库重命名的影响
- - '####'
  - 使用跟踪标志减少恢复时间
- - '###'
  - 查询存储与内存优化表
- - '###'
  - 为原生编译存储过程配置查询存储
- - '####'
  - 注意
- - '###'
  - 启用与禁用自动计划回归纠正（APRC）
- - '###'
  - 维护查询存储
- - '####'
  - 监控期望状态与实际状态
- - '#####'
  - 查询存储的只读状态
- - '#####'
  - 如何修复处于错误状态的查询存储
- - '#####'
  - 提示
- - '#####'
  - 监控空间使用情况
- - '#####'
  - 提示
- - '#####'
  - 如何清除查询存储
- - '#####'
  - 计划强制失败
- - '#####'
  - 移除计划和查询
- - '#####'
  - 重置计划的统计信息
- - '###'
  - 结论
- - '##'
  - 4. 标准查询存储报告
- - '###'
  - 性能回退查询报告
- - '####'
  - 注意
- - '###'
  - 总体资源消耗报告
- - '####'
  - 提示
- - '###'
  - 资源消耗最大的查询报告
- - '###'
  - 顶级资源消耗报告
- - '###'
  - 常规网格视图与图表视图
- - '###'
  - 更改坐标轴选项
- - '###'
  - 查询与计划交互
- - '###'
  - 左侧窗格分组依据选项
- - '###'
  - 左侧窗格控件（纵向模式）
- - '###'
  - 右侧窗格交互与图标
- - '###'
  - 强制计划查询报告
- - '###'
  - 报告概述
- - '###'
  - 报告按钮
- - '###'
  - 底部窗格选项
- - '###'
  - 高变化率查询报告
- - '###'
  - 查询等待统计信息报告
- - '###'
  - 跟踪查询报告
- - '###'
  - 结论
- - '##'
  - 5. 查询存储目录视图
- - '###'
  - sys.database_query_store_options
- - '###'
  - Query Store 配置与状态
- - '###'
  - sys.query_context_settings
- - '###'
  - sys.query_store_plan
- - '####'
  - 注意事项
- - '###'
  - sys.query_store_query
- - '###'
  - sys.query_store_query_text
- - '###'
  - sys.query_store_wait_stats
- - '###'
  - sys.query_store_runtime_stats
- - '###'
  - 查询存储运行时统计信息
- - '##'
  - 6. Query Store 使用案例
- - '###'
  - sys.query_store_runtime_stats_interval
- - '###'
  - 结论
- - '###'
  - 确定什么是正常工作负载
- - '###'
  - 为查询建立基线
- - '####'
  - 什么是基线？
- - '####'
  - 如何使用 Query Store 创建基线
- - '###'
  - 如何将工作负载与基线进行比较
- - '###'
  - 查看昨晚发生了什么
- - '###'
  - 故障排除回归查询
- - '####'
  - 什么是回归查询？
- - '####'
  - 查看计划变更
- - '###'
  - 识别资源消耗最多的查询
- - '###'
  - 稳定 SQL Server 升级
- - '####'
  - 更改兼容性模式的影响
- - '####'
  - 基数估算变更解析
- - '####'
  - 使用查询存储测试和完成升级的过程
- - '###'
  - 查找和改进即席工作负载
- - '###'
  - 结论
- - '##'
  - 7. 强制执行计划
- - '###'
  - 识别行为不佳的执行计划
- - '####'
  - 识别性能回退的查询
- - '#####'
  - 从查询存储数据中识别回退查询
- - '###'
  - 回归查询报告
- - '####'
  - 执行计划中的警示信号
- - '#####'
  - First Operator
- - '#####'
  - Most Costly Operator
- - '#####'
  - Warnings and Errors
- - '#####'
  - Fat Pipes
- - '#####'
  - Scans
- - '#####'
  - Extra Operators
- - '####'
  - 估计值与实际值
- - '###'
  - 比较执行计划
- - '###'
  - 强制与解除强制执行计划
- - '####'
  - 通过报告强制计划
- - '####'
  - 使用 T-SQL 强制计划
- - '####'
  - 确定哪些计划已被强制
- - '###'
  - 结论
- - '##'
  - 8. 自动计划修正与等待统计信息
- - '###'
  - 自动计划修正
- - '####'
  - 识别查询回归
- - '###'
  - 调优推荐详情
- - '###'
  - 启用自动调优
- - '####'
  - 在 Azure SQL Database 中启用自动调优
- - '####'
  - 使用 T-SQL 启用自动调优
- - '####'
  - 自动调优的工作原理
- - '###'
  - 查询存储等待统计信息
- - '####'
  - 等待统计信息类别
- - '###'
  - 查看查询存储等待统计信息
- - '####'
  - 查询等待统计信息
- - '#####'
  - 等待统计信息报告
- - '###'
  - 结论
- - '##'
  - 9. 使用查询存储进行故障排除
- - '###'
  - Query Store Waits
- - '###'
  - Extended Events and Query Store
- - '####'
  - 跟踪查询存储行为
- - '###'
  - 结论
- - '##'
  - 10. 社区工具
- - '###'
  - dbatools
- - '###'
  - Get-DbaDbQueryStoreOption
- - '###'
  - Set-DbaDbQueryStoreOption
- - '###'
  - Copy-DbaQueryStoreConfig
- - '###'
  - dbatools 总结
- - '###'
  - sp_BlitzQueryStore
- - '####'
  - 注意
- - '###'
  - 结论
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G, H
- - '###'
  - I, J, K, L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U, V
- - '###'
  - W, X, Y, Z
