name: Pro SQL Database for Windows Azure
name_cn: Windows Azure 的 SQL 数据库高级指南
slug: pro-sql-database-for-windows-azure
toc:
- - '#'
  - 内容概览
- - '#'
  - 引言
- - '##'
  - 本书面向的读者
- - '##'
  - 本书的组织结构
- - '###'
  - 引言
- - '#'
  - 第 1 章：SQL 数据库入门
- - '##'
  - 云计算简介
- - '###'
  - 谁在云中做什么？
- - '###'
  - 典型的云服务
- - '##'
  - 探索 Microsoft Azure 平台
- - '###'
  - 为什么选择 Microsoft Azure？
- - '###'
  - 关于地理位置
- - '###'
  - 在 Azure 中存储数据
- - '##'
  - SQL 数据库入门
- - '###'
  - 注册 Azure
- - '###'
  - 创建 SQL 数据库实例
- - '####'
  - 使用 Windows Azure 管理门户
- - '####'
  - 使用 T-SQL 命令
- - '###'
  - 配置防火墙
- - '###'
  - 使用 SQL Server Management Studio 连接
- - '###'
  - 创建登录名和用户
- - '####'
  - 创建新登录名
- - '####'
  - 创建新用户
- - '###'
  - 分配访问权限
- - '###'
  - 了解 SQL 数据库的计费方式
- - '###'
  - SQL 数据库的限制
- - '####'
  - 安全性
- - '####'
  - 备份
- - '####'
  - 对象
- - '####'
  - 其他
- - '####'
  - 驱动程序和协议
- - '#'
  - 小结
- - '#'
  - 第 2 章：设计考量
- - '##'
  - 设计因素
- - '###'
  - 异地存储
- - '###'
  - 高可用性
- - '###'
  - 性能
- - '####'
  - 节流
- - '####'
  - 应用程序设计考量
- - '###'
  - 数据同步
- - '###'
  - 直接连接与服务化连接
- - '###'
  - 定价
- - '###'
  - 安全性
- - '###'
  - 设计因素回顾
- - '##'
  - 设计模式
- - '###'
  - 直接连接
- - '###'
  - 智能分支
- - '###'
  - 透明分支
- - '###'
  - 分片
- - '####'
  - 分片概念与方法
- - '####'
  - 只读分片
- - '####'
  - 读写分片
- - '###'
  - 卸载
- - '###'
  - 聚合
- - '###'
  - 镜像
- - '##'
  - 组合模式
- - '###'
  - 透明分支 + 读写分片
- - '###'
  - 级联聚合
- - '##'
  - 示例设计：应用程序 SLA 监控
- - '###'
  - Azure 部署前的应用架构
- - '###'
  - Azure 实现方案
- - '##'
  - 其他考量
- - '###'
  - Blob 数据存储
- - '###'
  - 边缘数据缓存
- - '###'
  - 数据加密
- - '###'
  - SaaS 应用程序与联合
- - '#'
  - 小结
- - '#'
  - 第 3 章：安全性
- - '##'
  - 概述
- - '###'
  - 保密性
- - '###'
  - 完整性
- - '###'
  - 可用性
- - '##'
  - 保护你的数据
- - '###'
  - 加密
- - '####'
  - 加密实现
- - '####'
  - 加密算法描述
- - '####'
  - 加密代码实现
- - '###'
  - 哈希
- - '####'
  - 哈希工具方法
- - '####'
  - 使用哈希
- - '###'
  - 证书
- - '##'
  - 访问控制
- - '###'
  - 身份验证 (AUTHN)
- - '###'
  - 授权 (AUTHZ)
- - '####'
  - 创建登录和用户
- - '####'
  - 架构
- - '####'
  - 架构分离
- - '##'
  - SQL 数据库防火墙
- - '##'
  - 内部防火墙
- - '##'
  - 合规性
- - '#'
  - 小结
- - '#'
  - 第 4 章：数据迁移与备份策略
- - '##'
  - 将数据库和数据迁移到 SQL Azure
- - '###'
  - 导入/导出服务
- - '####'
  - 数据层应用程序框架
- - '####'
  - 使用 SQL Server 2012 通过 BACPAC 部署到 SQL Azure
- - '#####'
  - 直接部署到 SQL Azure
- - '#####'
  - 使用 SQL Server 2012 通过 BACPAC 导出和导入到 SQL Azure
- - '######'
  - DAC 导出
- - '######'
  - DAC 导入
- - '##'
  - 生成和发布脚本向导
- - '###'
  - 启动向导
- - '###'
  - 选择目标对象
- - '###'
  - 设置高级选项
- - '###'
  - 审查生成的脚本
- - '###'
  - 修复脚本
- - '###'
  - 针对 Azure 数据库执行脚本
- - '##'
  - bcp 实用程序
- - '###'
  - 调用 bcp
- - '###'
  - 导出数据
- - '###'
  - 导入数据
- - '##'
  - SQL Azure 备份策略
- - '###'
  - 复制数据库
- - '####'
  - 了解复制何时完成
- - '####'
  - 自动化数据库复制
- - '####'
  - 维护备份历史记录
- - '###'
  - 使用导入/导出功能进行备份
- - '###'
  - 第三方备份产品
- - '####'
  - Enzo 备份
- - '####'
  - 云服务
- - '#'
  - 小结
- - '#'
  - 第 5 章：使用 SQL 数据库编程
- - '##'
  - 应用程序部署因素
- - '###'
  - 本地托管应用程序
- - '###'
  - Azure 托管应用程序
- - '###'
  - 如何选择？
- - '##'
  - 连接到 SQL Database
- - '###'
  - ADO.NET
- - '####'
  - 建立连接
- - '####'
  - 使用数据读取器
- - '####'
  - 使用数据集
- - '###'
  - ODBC
- - '###'
  - sqlcmd
- - '###'
  - WCF 数据服务
- - '####'
  - 创建数据服务
- - '####'
  - 将服务连接到模型
- - '####'
  - 创建客户端应用程序
- - '##'
  - 最佳实践
- - '###'
  - 瞬态故障处理应用程序块
- - '####'
  - 将瞬态故障处理应用程序块添加到你的项目中
- - '###'
  - 使用瞬态故障处理应用程序块
- - '#'
  - 小结
- - '#'
  - 第 6 章：SQL 报告
- - '##'
  - SQL 报告概述
- - '###'
  - 架构
- - '####'
  - 网关
- - '####'
  - 节点
- - '###'
  - 功能比较
- - '##'
  - 配置您的 SQL Reporting 服务器
- - '##'
  - 创建报告
- - '###'
  - 创建 SQL Database 数据源
- - '###'
  - 创建报告设计
- - '##'
  - 部署报告
- - '##'
  - 安全性
- - '###'
  - 角色
- - '##'
  - 使用管理门户
- - '##'
  - 定价
- - '#'
  - 小结
- - '#'
  - 第 7 章：SQL 数据同步
- - '##'
  - 理解 SQL Data Sync
- - '###'
  - 为何需要？
- - '##'
  - 基本场景
- - '##'
  - 常见数据同步场景
- - '##'
  - 架构
- - '##'
  - 配置同步
- - '###'
  - 配置 SQL 数据同步服务器
- - '###'
  - 创建同步组
- - '###'
  - 定义中心和成员数据库
- - '###'
  - 选择要同步的表
- - '###'
  - 应用筛选器
- - '###'
  - 应用冲突解决策略
- - '###'
  - 设置同步计划
- - '###'
  - 部署同步组
- - '###'
  - 调试和日志查看器
- - '###'
  - 查看同步的数据
- - '###'
  - 编辑数据和重新同步
- - '###'
  - 测试冲突解决
- - '##'
  - 数据同步限制
- - '##'
  - 数据同步最佳实践
- - '###'
  - 设计考虑因素
- - '###'
  - 初始同步
- - '###'
  - 安全性
- - '###'
  - 同步计划
- - '#'
  - 小结
- - '#'
  - 第 8 章：Windows Azure 与 ASP.NET
- - '##'
  - 创建云服务
- - '##'
  - 创建 Windows Azure 项目
- - '###'
  - 配置开发环境
- - '###'
  - 创建你的第一个 Visual Studio 云项目
- - '###'
  - 将 GridView 连接到 SQL 数据库
- - '###'
  - 部署和配置文件
- - '##'
  - 在 Windows Azure 中部署 ASP.NET 应用程序
- - '#'
  - 小结
- - '#'
  - 第 9 章：高性能设计
- - '##'
  - 通用性能概念
- - '###'
  - 频繁交互 vs. 大块交互
- - '###'
  - 延迟加载
- - '###'
  - 缓存
- - '###'
  - 异步用户界面
- - '###'
  - 并行处理
- - '###'
  - 分片
- - '####'
  - 编码策略总结
- - '##'
  - 构建分片
- - '###'
  - 设计分片库对象
- - '###'
  - 管理数据库连接
- - '###'
  - 读取分片
- - '###'
  - 缓存
- - '###'
  - 缓存优化技术
- - '###'
  - 在分片中更新和删除记录
- - '###'
  - 向分片中添加记录
- - '##'
  - 管理分片
- - '###'
  - 异常管理
- - '###'
  - 性能管理
- - '###'
  - 处理部分分片
- - '###'
  - 管理事务一致性
- - '###'
  - 管理外键约束
- - '##'
  - 设计多租户系统
- - '###'
  - 基于模式的安全与数据隔离
- - '###'
  - 设计此系统时必须考虑以下几点
- - '####'
  - 处理客户请求的工作流程
- - '####'
  - 连接池碎片化问题
- - '###'
  - 对客户模式的维护操作
- - '##'
  - 创建垂直分区分片
- - '##'
  - 用于 Windows Azure 的大数据与 Hadoop
- - '#'
  - 小结
- - '#'
  - 第 10 章：联合
- - '##'
  - 联合介绍
- - '###'
  - 联合与分片
- - '###'
  - 为何使用联邦？
- - '###'
  - 联邦概述
- - '##'
  - 联合组件
- - '##'
  - 创建联合
- - '###'
  - 步骤 1：创建数据库
- - '###'
  - 步骤 2：创建联合
- - '###'
  - 创建更多联合
- - '##'
  - 管理联邦
- - '##'
  - 高级考虑因素
- - '###'
  - 限制
- - '###'
  - 分片库
- - '#'
  - 小结
- - '#'
  - 第 11 章：性能调优
- - '##'
  - SQL Database 的不同之处
- - '##'
  - 方法与工具
- - '##'
  - 编码影响
- - '##'
  - 调优技术
- - '##'
  - 动态管理视图
- - '##'
  - 连接池
- - '###'
  - 使用相同的连接字符串
- - '###'
  - 使用 SSMS 执行计划
- - '###'
  - 使用管理门户查看执行计划
- - '##'
  - 通过管理门户查看查询性能
- - '##'
  - 索引
- - '###'
  - 索引视图
- - '##'
  - 存储过程
- - '##'
  - 提供程序统计信息
- - '###'
  - 应用程序设计
- - '#'
  - 小结
- - '#'
  - 第 12 章：Windows Azure 移动服务
- - '##'
  - 入门
- - '##'
  - 选择数据库
- - '###'
  - 指定数据库设置
- - '###'
  - 预配移动服务
- - '##'
  - 开始使用服务
- - '###'
  - 连接现有应用程序
- - '###'
  - 创建新应用程序
- - '##'
  - 创建表
- - '###'
  - 下载示例应用程序
- - '##'
  - 高级设置
- - '###'
  - 推送
- - '###'
  - 标识
- - '###'
  - 缩放
- - '#'
  - 小结
- - '#'
  - 附录 A：SQL 数据库管理门户
- - '##'
  - 启动管理门户
- - '##'
  - 管理功能
- - '###'
  - 运行 T-SQL 语句
- - '###'
  - 查看执行计划
- - '###'
  - 监控当前查询性能
- - '##'
  - 设计功能
- - '###'
  - 设计表
- - '###'
  - 设计视图
- - '###'
  - 设计存储过程
- - '#'
  - 小结
- - '#'
  - 附录 B：Windows Azure SQL 数据库快速参考
- - '##'
  - 支持的 T-SQL 语句
- - '##'
  - 部分支持的 T-SQL 语句
- - '##'
  - 不支持的 T-SQL 语句
- - '##'
  - 支持的数据类型
- - '##'
  - 索引
- - '#'
  - 索引
