name: Expert T-SQL Window Functions in SQL Server 2019
name_cn: SQL Server 2019 T-SQL 窗口函数高级指南
slug: expert-t-sql-window-functions-in-sql-server-2019
toc:
- - '#'
  - 前言
- - '#'
  - 引言
- - '##'
  - 本书内容
- - '##'
  - 目标读者
- - '##'
  - 联系作者
- - '##'
  - 致谢
- - '###'
  - 关于作者与技术审校者
- - '####'
  - 关于作者
- - '####'
  - 关于技术审校者
- - '#'
  - 1. 初识窗口函数
- - '##'
  - 探索窗口函数
- - '###'
  - 注意
- - '##'
  - 理解窗口
- - '##'
  - 理解 OVER 子句
- - '###'
  - 注意
- - '##'
  - 使用随机 ORDER BY 的行号
- - '##'
  - 使用分区划分窗口
- - '##'
  - 揭示特殊案例窗口
- - '##'
  - 总结
- - '#'
  - 2. 探索排名函数
- - '##'
  - 使用 ROW_NUMBER
- - '##'
  - 理解 RANK 与 DENSE_RANK
- - '##'
  - 使用 NTILE 划分数据
- - '##'
  - 使用排名函数解决查询
- - '###'
  - 数据去重
- - '###'
  - 查找每组的前 N 行
- - '###'
  - 创建计数表
- - '###'
  - 解决奖金问题
- - '##'
  - 总结
- - '#'
  - 3. 使用窗口聚合进行汇总
- - '##'
  - 使用窗口聚合
- - '##'
  - 将窗口聚合添加到聚合查询中
- - '##'
  - 使用窗口聚合解决常见查询
- - '###'
  - 销售额占比问题
- - '###'
  - 分区表问题
- - '##'
  - 创建自定义窗口聚合函数
- - '##'
  - 概述
- - '#'
  - 4. 计算累积和移动聚合
- - '##'
  - 向窗口聚合添加 ORDER BY
- - '##'
  - 计算移动总计和平均值
- - '##'
  - 使用累积聚合解决查询
- - '###'
  - 上一个有效值问题
- - '####'
  - 清单 4-4：创建并填充表
- - '####'
  - 图 4-6：上一个有效值问题的原始数据
- - '####'
  - 清单 4-5：解决方案步骤 1
- - '####'
  - 图 4-7：步骤 1 的结果
- - '####'
  - 清单 4-6：完整解决方案
- - '####'
  - 图 4-8：上一个有效值问题的完整结果
- - '###'
  - 订阅问题
- - '##'
  - 总结
- - '#'
  - 5. 向窗口添加帧
- - '##'
  - 理解 Framing
- - '##'
  - 将框架应用于累计聚合和移动聚合
- - '##'
  - 理解 ROWS 与 RANGE 的逻辑差异
- - '##'
  - 总结
- - '#'
  - 6. 瞥见另一行
- - '##'
  - 理解 LAG 和 LEAD
- - '##'
  - 理解 FIRST_VALUE 和 LAST_VALUE
- - '##'
  - 使用偏移函数解决查询
- - '###'
  - 同比增长率计算
- - '###'
  - 考勤卡问题
- - '##'
  - 小结
- - '#'
  - 7. 理解统计函数
- - '##'
  - 使用 PERCENT_RANK 和 CUME_DIST
- - '##'
  - 使用 PERCENTILE_CONT 和 PERCENTILE_DISC
- - '##'
  - 比较统计函数与旧方法
- - '##'
  - 小结
- - '#'
  - 8. 为获得更佳性能进行调优
- - '##'
  - 使用执行计划
- - '##'
  - 使用 STATISTICS IO
- - '##'
  - 通过索引提升窗口函数性能
- - '##'
  - 为性能而设计框架
- - '##'
  - 利用行存储上的批处理模式
- - '###'
  - 图 8-17：窗口聚合函数和统计函数的逻辑读取
- - '###'
  - 图 8-18：显示表假脱机运算符的执行计划
- - '###'
  - 图 8-19：使用批处理模式时的逻辑读取
- - '###'
  - 图 8-20：带有窗口聚合运算符的执行计划
- - '###'
  - 图 8-21：批执行模式
- - '##'
  - 时间对比测量
- - '###'
  - 注意
- - '##'
  - 清理数据库
- - '##'
  - 总结
- - '#'
  - 9. 利用间隙、岛屿和连续期打出全垒打
- - '##'
  - 经典的间隔/岛屿问题
- - '###'
  - 查找岛屿
- - '###'
  - 查找间隔
- - '##'
  - 限制与注意事项
- - '##'
  - 数据聚类
- - '###'
  - 使用 CTE 查询进行邻近性分析
- - '##'
  - 追踪连续记录
- - '##'
  - 连胜与连败
- - '##'
  - 跨分区数据集的连胜/连败
- - '###'
  - 清单 9-8：计算一支球队对阵每个对手的所有连胜记录的 T-SQL
- - '####'
  - 图 9-10：红袜队对阵每个对手的连胜记录
- - '###'
  - 清单 9-9：计算所有球队对阵所有其他球队的连胜记录的查询
- - '##'
  - 数据质量
- - '###'
  - 空值
- - '###'
  - 意外或无效值
- - '###'
  - 重复数据
- - '##'
  - 性能
- - '##'
  - 总结
- - '#'
  - 10. 时间范围计算
- - '##'
  - 父级百分比
- - '##'
  - 使用 CTE 简化计算
- - '##'
  - 期间至今计算
- - '##'
  - 平均值和移动平均值
- - '###'
  - 处理日期范围中的间隙
- - '###'
  - 同一时期上一年
- - '###'
  - 增长与增长率计算
- - '###'
  - 总结
- - '#'
  - 11. 时间趋势计算
- - '##'
  - 移动总量与移动平均值
- - '###'
  - 确保数据集完整
- - '##'
  - 月度级别，无产品维度：处理数据空隙，全产品，三步操作查询
- - '###'
  - 月度移动总计与平均值
- - '##'
  - 计算同期上年累计至今值
- - '##'
  - 可视化趋势
- - '##'
  - 月环比 vs. 同期上年
- - '##'
  - 变化率
- - '##'
  - 帕累托原则
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H, I, J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U, V
- - '##'
  - W, X
- - '##'
  - Y, Z
