name: Hacking MySQL
name_cn: MySQL 深入指南
slug: hacking-mysql
toc:
- - '#'
  - 第一部分 MySQL 基础
- - '##'
  - 1. MySQL 的世界
- - '###'
  - 本书中的示例
- - '###'
  - 评论、问题与关切
- - '###'
  - 致谢
- - '###'
  - 关于作者
- - '###'
  - '`MySQL`的历史'
- - '###'
  - '`MySQL`的架构'
- - '###'
  - 基本用例和初始考虑因素
- - '###'
  - 存储引擎
- - '####'
  - 其他存储引擎
- - '###'
  - 总结
- - '##'
  - 2. 各个存储引擎
- - '###'
  - 存储引擎的现代王者
- - '####'
  - MySQL 和 MariaDB 中的 InnoDB
- - '###'
  - InnoDB 参数
- - '###'
  - Percona Server
- - '####'
  - Percona Server 中的存储引擎
- - '####'
  - Percona MyRocks 和 TokuDB
- - '###'
  - MyRocks
- - '###'
  - TokuDB
- - '###'
  - InnoDB 的主要竞争对手
- - '####'
  - MyISAM 的早期
- - '####'
  - MyISAM 的现状
- - '####'
  - 存储引擎使用场景
- - '####'
  - MEMORY 和 TempTable 存储引擎
- - '####'
  - CSV 存储引擎
- - '####'
  - ARCHIVE 与 BLACKHOLE 存储引擎
- - '####'
  - MERGE 存储引擎
- - '#####'
  - 优点
- - '#####'
  - 缺点
- - '####'
  - 高可用性存储引擎
- - '###'
  - 安装与使用 NDB
- - '####'
  - 影响所有数据节点上 ndbd 进程的选项
- - '####'
  - NDB 管理节点
- - '####'
  - 第一个数据节点
- - '####'
  - 第二个数据节点
- - '###'
  - FEDERATED 和 EXAMPLE 存储引擎
- - '####'
  - MariaDB 专属存储引擎
- - '###'
  - 总结
- - '#'
  - 第二部分 破坏 MySQL
- - '##'
  - 3. 什么会破坏 MySQL？
- - '###'
  - MySQL 使用案例
- - '###'
  - 问题使用场景
- - '####'
  - 性能小故障
- - '####'
  - 可用性问题
- - '####'
  - 安全问题
- - '###'
  - 理解你的数据
- - '###'
  - 选择适当的模式与数据类型
- - '####'
  - 用于 `数值` 数据的数据类型
- - '####'
  - 用于存储 `日期` 和 `时间` 值的数据类型
- - '####'
  - 用于存储 `字符串` 值的数据类型
- - '####'
  - 用于存储 `地理` 数据的空间（地理空间）数据类型
- - '####'
  - '`JSON` 数据类型'
- - '###'
  - 提示
- - '####'
  - 字符集与排序规则
- - '###'
  - 你的架构一团糟
- - '###'
  - 通过软件与 MySQL 通信
- - '####'
  - 导致查询性能缓慢的主要原因
- - '###'
  - 总结
- - '##'
  - 4. 你如何破坏了你的查询
- - '###'
  - 好的、坏的和丑陋的：理解 MySQL 中的查询
- - '###'
  - 你如何在 MySQL 中破坏了查询
- - '###'
  - MySQL 中的查询类型
- - '####'
  - 破坏 MySQL 中 DML 查询的因素
- - '####'
  - MySQL 查询常见错误与优化
- - '####'
  - 教训
- - '###'
  - 破坏 MySQL 中 DDL 查询的因素
- - '###'
  - 导致 MySQL 中 DCL 和 TCL 查询失败的因素
- - '###'
  - 为什么查询速度慢？
- - '###'
  - SQL 查询性能分析
- - '###'
  - 设计完美的模式设计
- - '###'
  - 精心设计数据库模式
- - '###'
  - 理解数据类型
- - '###'
  - 理解字符集和校对规则
- - '###'
  - 理解索引
- - '###'
  - 理解分区
- - '####'
  - 分区与大数据
- - '####'
  - NULL 值处理与分区修剪
- - '###'
  - 在 MySQL 中优化查询时应避免的事项
- - '####'
  - 不要盲目信任文档
- - '###'
  - 总结
- - '##'
  - 5. 理解查询组件
- - '###'
  - SQL 查询与存储过程
- - '###'
  - 解析器与优化器
- - '####'
  - MySQL 查询解析与优化
- - '###'
  - 查询与错误消息
- - '####'
  - 理解 MySQL 错误
- - '#####'
  - 常见的 MySQL 错误代码
- - '###'
  - 查询所厌恶的因素
- - '####'
  - 隔离你的列！
- - '####'
  - 消除重复索引
- - '####'
  - 使用 EXISTS 而不是 IN
- - '###'
  - 善用存储过程和触发器
- - '###'
  - '`SHOW STATUS` 和 `EXPLAIN`'
- - '###'
  - 总结
- - '##'
  - 6. 理解你的服务器
- - '###'
  - 高效使用服务器资源
- - '###'
  - 理解和模拟错误
- - '####'
  - SQLSTATE 码、MySQL 错误码与服务器配置
- - '#####'
  - SQLSTATE 码
- - '#####'
  - MySQL 错误码
- - '###'
  - 服务器组件及其与 MySQL 的交互
- - '###'
  - 为 MySQL 选择服务器
- - '###'
  - InnoDB 刷新方法与压力测试
- - '###'
  - 为 MySQL 性能与安全而编码
- - '#'
  - 第三部分 MySQL 优化
- - '##'
  - 7. 为 MySQL 优化你的服务器
- - '###'
  - 不该做的事
- - '###'
  - 总结
- - '###'
  - 为何要为 MySQL 优化你的服务器？
- - '###'
  - 影响 MySQL 的常见网络服务器问题
- - '####'
  - MySQL 性能陷阱与基础设施规划
- - '###'
  - 什么限制了 MySQL 的性能？
- - '###'
  - 选择服务器和硬盘
- - '###'
  - 配置 MySQL 参数
- - '###'
  - 为您的操作系统配置 MySQL I/O
- - '###'
  - 测试您的硬件
- - '####'
  - MySQL 数据库优化与 ACID 特性详解
- - '#####'
  - 实践中的数据库优化
- - '#####'
  - 数据库性能测试工具
- - '#####'
  - 充分利用 ACID 特性
- - '##'
  - 8. 优化存储引擎、模式与数据类型
- - '###'
  - 概要
- - '###'
  - 为什么要优化存储引擎和数据类型？
- - '###'
  - 优化存储引擎
- - '####'
  - 针对包含大量表的应用程序的注意事项
- - '####'
  - 针对只读操作和事务的优化
- - '###'
  - 优化 MySQL 性能的注意事项
- - '####'
  - 按需分区数据
- - '####'
  - 检查 InnoDB 的缓冲池和日志文件
- - '####'
  - 利用 `START TRANSACTION READ ONLY` 语句
- - '####'
  - 帮助 InnoDB 检测只读事务
- - '####'
  - 插入大量数据时关闭 `autocommit`，待所有数据插入完成后再启用
- - '###'
  - 数据类型
- - '####'
  - MySQL 中的数据类型
- - '####'
  - 字符串数据类型
- - '####'
  - 数值数据类型
- - '####'
  - MariaDB 中的数值数据类型
- - '###'
  - 日期、时间、空间和 JSON 数据类型
- - '###'
  - 数据类型的存储要求
- - '###'
  - 选择合适的数据类型
- - '####'
  - 为大数据优化模式和数据类型
- - '###'
  - 总结
- - '##'
  - 9. 优化查询
- - '###'
  - 为什么要优化 SQL 查询？
- - '####'
  - MySQL 查询优化指南
- - '###'
  - 优化准则
- - '###'
  - 优化特定类型的查询
- - '####'
  - 查询缓存
- - '####'
  - 优化 INSERT 查询
- - '####'
  - 在 MySQL/MariaDB 中插入与优化数据
- - '###'
  - 优化 SELECT 查询
- - '####'
  - 优化 SQL 查询性能
- - '###'
  - 诊断查询状态与数据
- - '###'
  - 分步检查与优化
- - '###'
  - 优化索引与约束
- - '###'
  - B-树索引与性能
- - '###'
  - 优化 UPDATE 查询
- - '###'
  - 优化 DELETE 查询
- - '###'
  - 为大数据优化查询、避免死锁及其他查询优化技巧
- - '####'
  - 总结
- - '##'
  - 10. 为大数据优化 MySQL
- - '####'
  - MySQL 能应对大数据吗？
- - '###'
  - MariaDB 与大数据：处理大数据集
- - '####'
  - 将大数据插入 MariaDB
- - '###'
  - 使用 MariaDB 读取大数据
- - '###'
  - 在 MariaDB 中更新大数据
- - '####'
  - 使用 WHERE、OFFSET 和 LIMIT 子句
- - '####'
  - 保持对数据库负载的警惕
- - '###'
  - 从 MariaDB 中删除大数据
- - '###'
  - 存储引擎与大数据
- - '###'
  - ACID 与大数据
- - '###'
  - 大数据陷阱与已知问题
- - '###'
  - 总结
- - '##'
  - 11. MySQL 索引技术
- - '####'
  - 索引是任何数据库的关键部分
- - '###'
  - 为什么需要索引？MariaDB 中可用的索引类型
- - '###'
  - 引言
- - '###'
  - 什么以及何时索引？
- - '###'
  - 索引的迷思、误解与碎片化问题
- - '###'
  - 硬件、数据库与索引
- - '###'
  - 索引类型
- - '####'
  - B-树索引
- - '####'
  - B 树索引：结构、用法与优化
- - '#####'
  - B 树索引简介
- - '#####'
  - 在 MySQL 中定义 B 树索引
- - '#####'
  - 实践演示
- - '#####'
  - 测试索引性能
- - '#####'
  - 关键注意事项与优化
- - '###'
  - 覆盖索引
- - '###'
  - 多列（复合）索引
- - '####'
  - 复合索引、覆盖索引及其他索引类型
- - '#####'
  - 前缀索引
- - '#####'
  - 空间（R-Tree）、哈希和聚簇索引
- - '###'
  - 设计完美的索引方案
- - '####'
  - 索引基础与初步设计
- - '####'
  - 索引设计与大数据考量
- - '####'
  - 索引与查询优化
- - '###'
  - 总结
- - '##'
  - 12. 优化分区
- - '###'
  - 为什么要分区数据？
- - '###'
  - 何时分区数据？
- - '###'
  - 数据库分区内部原理
- - '###'
  - MySQL 中的分区类型
- - '###'
  - 创建分区表示例
- - '###'
  - 范围分区
- - '###'
  - 列表分区
- - '###'
  - 哈希分区
- - '###'
  - 键分区
- - '###'
  - 分区的好处与数据修剪
- - '###'
  - 分区技巧：子分区、限制、NULL 值等
- - '####'
  - MySQL 分区：关键概念与操作
- - '#####'
  - 不同分区类型对 NULL 值的处理
- - '#####'
  - 理解子分区
- - '#####'
  - 定义分区的关键规则
- - '#####'
  - 索引与分区的结合
- - '#####'
  - 分区与表的相互转换
- - '#####'
  - 分区的维护操作
- - '#####'
  - 分区的重组
- - '#####'
  - 分区的限制
- - '###'
  - 总结
- - '##'
  - 13. 优化备份与恢复
- - '###'
  - 为何、何时以及如何备份 MariaDB？
- - '###'
  - 备份类型与工具
- - '####'
  - MariaDB 备份工具详解
- - '###'
  - 备份选项
- - '###'
  - 使用示例
- - '###'
  - 增量备份
- - '###'
  - 备份压缩与安全
- - '####'
  - 备份压缩与加密
- - '###'
  - 备份大数据集
- - '###'
  - 恢复 MariaDB
- - '####'
  - 恢复大数据
- - '###'
  - 备份与恢复的陷阱
- - '####'
  - 大数据的陷阱
- - '###'
  - 摘要
- - '##'
  - 14. 优化复制
- - '###'
  - 理解复制
- - '###'
  - 术语与背景
- - '###'
  - 配置与实施复制
- - '###'
  - 复制类型
- - '####'
  - MariaDB 复制技术概述
- - '###'
  - 复制注意事项与技巧
- - '###'
  - 保护复制安全
- - '###'
  - 总结
- - '##'
  - 15. 安全优化
- - '###'
  - 理解 MariaDB 中的安全
- - '###'
  - 在安装时保护 MariaDB
- - '###'
  - 通用安全措施
- - '###'
  - 总结
- - '#'
  - 第四部分 保障 MySQL 安全
- - '##'
  - 16. MySQL 的安全世界
- - '###'
  - 通用安全指南与措施回顾
- - '####'
  - 安全框架指南
- - '#####'
  - NIST 网络安全框架
- - '#####'
  - OWASP Top 10 (2021)
- - '###'
  - 访问控制
- - '####'
  - MariaDB 用户与权限管理
- - '#####'
  - 创建用户
- - '#####'
  - 分配权限
- - '#####'
  - 访问控制
- - '###'
  - 用户安全
- - '####'
  - 数据库安全：保护您的数据免受攻击
- - '###'
  - 保持数据安全的 MariaDB 组件和插件
- - '###'
  - 防火墙保护 MariaDB
- - '###'
  - 总结
- - '##'
  - 17. 加固您的数据库实例
- - '###'
  - 针对特定用例的安全准则与纵深防御
- - '###'
  - 账户类别与预留账户
- - '####'
  - 17. 安全与数据库
- - '#####'
  - SQL 注入的边界情况
- - '###'
  - 针对数据库的其他攻击
- - '###'
  - 总结
- - '##'
  - 18. 安全与大数据
- - '###'
  - 在 SDLC 初始阶段保障大数据与代码的安全
- - '###'
  - 数据、“脚本小子”及其他
- - '###'
  - 如果发生……怎么办？
- - '###'
  - 安全日志分析
- - '###'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X
- - '##'
  - Y, Z
