name: Practical MonogoDB
name_cn: MongoDB 实践指南
slug: practical-monogodb
toc:
- - '#'
  - 目录
- - '##'
  - 前言
- - '###'
  - 关于本书
- - '###'
  - 本书所需环境
- - '###'
  - 本书读者对象
- - '##'
  - 致谢
- - '##'
  - 第 1 章：大数据入门介绍
- - '###'
  - 大数据的事实概述
- - '###'
  - 大数据来源
- - '###'
  - 大数据的三个 V 特征
- - '####'
  - 容量
- - '####'
  - 多样性
- - '####'
  - 速度
- - '###'
  - 大数据的用途
- - '####'
  - 可见性
- - '####'
  - 发现与分析信息
- - '####'
  - 细分与定制化
- - '####'
  - 辅助决策
- - '####'
  - 创新
- - '###'
  - 大数据挑战
- - '####'
  - 策略与流程
- - '####'
  - 数据访问
- - '####'
  - 技术与技巧
- - '###'
  - 遗留系统与大数据
- - '####'
  - 大数据结构
- - '####'
  - 数据存储
- - '####'
  - 数据处理
- - '###'
  - 大数据技术
- - '###'
  - 小结
- - '##'
  - 第 2 章：NoSQL
- - '###'
  - SQL
- - '###'
  - NoSQL
- - '####'
  - 定义
- - '####'
  - NoSQL 简史
- - '####'
  - ACID 与 BASE
- - '####'
  - CAP 定理（布鲁尔定理）
- - '####'
  - BASE 模型
- - '###'
  - NoSQL 的优势与劣势
- - '####'
  - NoSQL 的优势
- - '####'
  - NoSQL 的劣势
- - '###'
  - SQL 与 NoSQL 数据库对比
- - '###'
  - NoSQL 数据库分类
- - '###'
  - 小结
- - '##'
  - 第 3 章：MongoDB 入门
- - '###'
  - 历史
- - '###'
  - MongoDB 设计哲学
- - '####'
  - 速度、可扩展性与敏捷性
- - '####'
  - 非关系型方法
- - '####'
  - 基于 JSON 的文档存储
- - '####'
  - 性能与功能的权衡
- - '####'
  - 任意位置运行数据库
- - '###'
  - SQL 对比
- - '###'
  - 小结
- - '##'
  - 第 4 章：MongoDB 数据模型
- - '###'
  - 数据模型
- - '###'
  - JSON 与 BSON
- - '###'
  - 标识符 (`_id`)
- - '###'
  - 固定集合
- - '###'
  - 多态模式
- - '###'
  - 面向对象编程
- - '###'
  - 模式演进
- - '###'
  - 小结
- - '##'
  - 第 5 章：MongoDB 安装与配置
- - '###'
  - 选择版本
- - '###'
  - 在 Linux 上安装 MongoDB
- - '####'
  - 使用软件仓库安装
- - '####'
  - 手动安装
- - '###'
  - 在 Windows 上安装 MongoDB
- - '###'
  - 运行 MongoDB
- - '####'
  - 前提条件
- - '####'
  - 启动服务
- - '###'
  - 验证安装
- - '###'
  - MongoDB Shell
- - '###'
  - 部署安全防护
- - '####'
  - 使用认证与授权
- - '####'
  - 控制网络访问
- - '###'
  - 使用 MongoDB Cloud Manager 进行配置
- - '###'
  - 小结
- - '##'
  - 第 6 章：使用 MongoDB Shell
- - '###'
  - 基本查询
- - '###'
  - 创建与插入
- - '####'
  - 显式创建集合
- - '####'
  - 使用循环插入文档
- - '####'
  - 通过显式指定 `_id` 插入
- - '###'
  - 更新
- - '###'
  - 删除
- - '###'
  - 读取
- - '###'
  - 使用索引
- - '###'
  - 进阶技巧
- - '####'
  - 使用条件操作符
- - '####'
  - 正则表达式
- - '####'
  - MapReduce
- - '####'
  - '`aggregate( )`'
- - '###'
  - 设计应用数据模型
- - '####'
  - 关系数据建模与规范化
- - '####'
  - MongoDB 文档数据模型方法
- - '###'
  - 小结
- - '##'
  - 第 7 章：MongoDB 架构
- - '###'
  - 核心进程
- - '####'
  - '`mongod`'
- - '####'
  - '`mongo`'
- - '####'
  - '`mongos`'
- - '###'
  - MongoDB 工具
- - '###'
  - 独立部署
- - '###'
  - 复制
- - '####'
  - 主/从复制
- - '####'
  - 副本集
- - '###'
  - 使用副本集实现高级集群
- - '###'
  - 分片
- - '####'
  - 分片组件
- - '####'
  - 数据分发过程
- - '####'
  - 数据均衡过程
- - '###'
  - 运维操作
- - '###'
  - 实现分片
- - '###'
  - 控制集合分布（基于标签的分片）
- - '###'
  - 在分片环境中导入数据的注意事项
- - '###'
  - 分片监控
- - '####'
  - 监控配置服务器
- - '###'
  - 生产集群架构
- - '####'
  - 场景 1
- - '####'
  - 场景 2
- - '####'
  - 场景 3
- - '####'
  - 场景 4
- - '###'
  - 小结
- - '##'
  - 第 8 章：MongoDB 原理详解
- - '###'
  - 数据存储引擎
- - '###'
  - 数据文件（与 MMAPv1 相关）
- - '####'
  - 命名空间（`.ns` 文件）
- - '###'
  - 数据文件（与 WiredTiger 相关）
- - '###'
  - 读取与写入
- - '###'
  - 使用日志进行数据写入的原理
- - '###'
  - GridFS – MongoDB 文件系统
- - '####'
  - GridFS 的基本原理
- - '####'
  - GridFS 内部机制
- - '####'
  - 使用 GridFS
- - '###'
  - 索引
- - '####'
  - 索引类型
- - '####'
  - 行为与限制
- - '###'
  - 小结
- - '##'
  - 第 9 章：MongoDB 管理
- - '###'
  - 管理工具
- - '####'
  - '`mongo`'
- - '####'
  - 第三方管理工具
- - '###'
  - 备份与恢复
- - '####'
  - 数据文件备份
- - '####'
  - '`mongodump` 和 `mongorestore`'
- - '####'
  - '`fsync` 与 `锁`'
- - '####'
  - 从节点备份
- - '###'
  - 导入与导出
- - '####'
  - '`mongoimport`'
- - '####'
  - '`mongoexport`'
- - '###'
  - 管理服务器
- - '####'
  - 启动服务器
- - '####'
  - 停止服务器
- - '####'
  - 查看日志文件
- - '####'
  - 服务器状态
- - '###'
  - 识别与修复 MongoDB
- - '####'
  - 识别与修复集合级数据
- - '###'
  - 监控 MongoDB
- - '####'
  - '`mongostat`'
- - '####'
  - '`mongod` Web 界面'
- - '####'
  - 第三方插件
- - '####'
  - MongoDB Cloud Manager
- - '###'
  - 小结
- - '##'
  - 第 10 章：MongoDB 应用案例
- - '###'
  - 案例 1 - 性能监控
- - '####'
  - 模式设计
- - '####'
  - 运维操作
- - '####'
  - 分片
- - '####'
  - 数据管理
- - '###'
  - 案例 2 – 社交网络
- - '####'
  - 模式设计
- - '####'
  - 运维操作
- - '####'
  - 分片
- - '###'
  - 小结
- - '##'
  - 第 11 章：MongoDB 限制
- - '###'
  - MongoDB 空间占用过大（适用于 MMAPv1）
- - '###'
  - 内存问题（适用于 MMAPv1 存储引擎）
- - '###'
  - 32 位与 64 位系统
- - '###'
  - BSON 文档限制
- - '###'
  - 命名空间限制
- - '###'
  - 索引限制
- - '###'
  - 固定集合限制 - 固定集合中文档的最大数量
- - '###'
  - 分片限制
- - '####'
  - 尽早分片以避免问题
- - '####'
  - 分片键无法更新
- - '####'
  - 分片集合限制
- - '####'
  - 选择正确的分片键
- - '###'
  - 安全限制
- - '####'
  - 默认无认证
- - '####'
  - MongoDB 的进出流量未加密
- - '###'
  - 写入与读取限制
- - '####'
  - 区分大小写的查询
- - '####'
  - 字段类型敏感
- - '####'
  - 无 `JOIN` 操作
- - '####'
  - 事务支持
- - '###'
  - MongoDB 不适用的范围
- - '###'
  - 小结
- - '##'
  - 第 12 章：MongoDB 最佳实践
- - '###'
  - 部署
- - '####'
  - MongoDB 官方硬件建议
- - '####'
  - 几点注意事项
- - '###'
  - 编码
- - '###'
  - 应用响应时间优化
- - '###'
  - 数据安全
- - '###'
  - 管理
- - '###'
  - 复制延迟
- - '###'
  - 分片
- - '###'
  - 监控
- - '###'
  - 小结
- - '##'
  - 内容概览
- - '#'
  - 1. 大数据
- - '##'
  - 1.1 入门介绍
- - '##'
  - 1.2 大数据
- - '###'
  - 1.2.1 关于大数据的事实
- - '####'
  - 1.2.1.1 大数据规模因行业而异
- - '####'
  - 1.2.1.2 大数据类型因行业而异
- - '##'
  - 1.3 大数据来源
- - '##'
  - 1.4 大数据的三个 V
- - '###'
  - 1.4.1 容量
- - '###'
  - 1.4.2 多样性
- - '###'
  - 1.4.3 速度
- - '##'
  - 1.5 大数据的使用
- - '###'
  - 1.5.1 可见性
- - '###'
  - 1.5.2 发现与分析信息
- - '###'
  - 1.5.3 细分与定制
- - '###'
  - 1.5.4 辅助决策制定
- - '###'
  - 1.5.5 创新
- - '##'
  - 1.6 大数据挑战
- - '###'
  - 1.6.1 政策与程序
- - '###'
  - 1.6.2 数据访问
- - '###'
  - 1.6.3 技术与技巧
- - '##'
  - 1.7 遗留系统与大数据
- - '###'
  - 1.7.1 大数据的结构
- - '###'
  - 1.7.2 数据存储
- - '###'
  - 1.7.3 数据处理
- - '##'
  - 1.8 大数据技术
- - '##'
  - 1.9 小结
- - '#'
  - 2. NoSQL
- - '##'
  - 2.1 SQL
- - '##'
  - 2.2 NoSQL
- - '###'
  - 2.2.1 定义
- - '###'
  - 2.2.2 NoSQL 简史
- - '##'
  - 2.3 ACID 与 BASE
- - '###'
  - 2.3.1 CAP 定理（布鲁尔定理）
- - '###'
  - 2.3.2 BASE 模型
- - '##'
  - 2.4 NoSQL 的优势与劣势
- - '###'
  - 2.4.1 NoSQL 的优势
- - '###'
  - 2.4.2 NoSQL 的劣势
- - '##'
  - 2.5 SQL 与 NoSQL 数据库对比
- - '##'
  - 2.6 NoSQL 数据库分类
- - '##'
  - 2.7 小结
- - '#'
  - 3. MongoDB 入门
- - '##'
  - 3.1 历史
- - '##'
  - 3.2 MongoDB 设计哲学
- - '###'
  - 3.2.1 速度、可扩展性与敏捷性
- - '###'
  - 3.2.2 非关系型方法
- - '###'
  - 3.2.3 基于 JSON 的文档存储
- - '###'
  - 3.2.4 性能与功能的权衡
- - '###'
  - 3.2.5 任意位置运行数据库
- - '##'
  - 3.3 SQL 对比
- - '##'
  - 3.4 小结
- - '#'
  - 4. MongoDB 数据模型
- - '##'
  - 4.1 数据模型
- - '###'
  - 4.1.1 JSON 与 BSON
- - '####'
  - 4.1.1.1 二进制 JSON (BSON)
- - '###'
  - 4.1.2 标识符 (`_id`)
- - '###'
  - 4.1.3 固定集合
- - '###'
  - 4.1.4 多态模式
- - '###'
  - 4.1.5 面向对象编程
- - '###'
  - 4.1.6 模式演进
- - '##'
  - 4.2 小结
- - '#'
  - 5. MongoDB 安装与配置
- - '##'
  - 5.1 选择版本
- - '##'
  - 5.2 在 Linux 上安装 MongoDB
- - '###'
  - 5.2.1 使用软件仓库安装
- - '###'
  - 5.2.2 手动安装
- - '##'
  - 5.3 在 Windows 上安装 MongoDB
- - '##'
  - 5.4 运行 MongoDB
- - '###'
  - 5.4.1 前提条件
- - '###'
  - 5.4.2 启动服务
- - '##'
  - 5.5 验证安装
- - '##'
  - 5.6 MongoDB Shell
- - '##'
  - 5.7 部署安全防护
- - '###'
  - 5.7.1 使用认证与授权
- - '####'
  - 5.7.1.1 启用认证
- - '####'
  - 5.7.1.2 创建管理员用户
- - '####'
  - 5.7.1.3 创建用户并启用授权
- - '###'
  - 5.7.2 控制网络访问
- - '####'
  - 5.7.2.1 使用防火墙
- - '####'
  - 5.7.2.2 加密数据
- - '####'
  - 5.7.2.3 加密通信
- - '##'
  - 5.8 使用 MongoDB Cloud Manager 进行配置
- - '##'
  - 5.9 小结
- - '#'
  - 6. 使用 MongoDB Shell
- - '##'
  - 6.1 基本查询
- - '###'
  - 6.1.1 创建与插入
- - '####'
  - 6.1.1.1 显式创建集合
- - '####'
  - 6.1.1.2 使用循环插入文档
- - '####'
  - 6.1.1.3 通过显式指定 `_id` 插入
- - '###'
  - 6.1.2 更新
- - '###'
  - 6.1.3 删除
- - '###'
  - 6.1.4 读取
- - '####'
  - 6.1.4.1 查询文档
- - '####'
  - 6.1.4.2 选择器
- - '####'
  - 6.1.4.3 投影器
- - '####'
  - 6.1.4.4 sort()
- - '####'
  - 6.1.4.5 limit()
- - '####'
  - 6.1.4.6 skip()
- - '####'
  - 6.1.4.7 findOne()
- - '####'
  - 6.1.4.8 使用游标
- - '####'
  - 6.1.4.9 explain()
- - '###'
  - 6.1.5 使用索引
- - '####'
  - 6.1.5.1 单键索引
- - '####'
  - 6.1.5.2 复合索引
- - '####'
  - 6.1.5.3 支持排序操作
- - '####'
  - 6.1.5.4 唯一索引
- - '####'
  - 6.1.5.5 system.indexes
- - '####'
  - 6.1.5.6 dropIndex
- - '####'
  - 6.1.5.7 reIndex
- - '####'
  - 6.1.5.8 索引如何工作
- - '##'
  - 6.2 进阶技巧
- - '###'
  - 6.2.1 使用条件操作符
- - '####'
  - 6.2.1.1 `$lt` 和 `$lte`
- - '####'
  - 6.2.1.2 `$gt` 和 `$gte`
- - '####'
  - 6.2.1.3 `$in` 和 `$nin`
- - '###'
  - 6.2.2 正则表达式
- - '###'
  - 6.2.3 MapReduce
- - '###'
  - 6.2.4 `aggregate( )`
- - '##'
  - 6.3 设计应用数据模型
- - '###'
  - 6.3.1 关系数据建模与规范化
- - '####'
  - 6.3.1.1 什么是范式形式？
- - '####'
  - 6.3.1.2 范式形式的问题
- - '###'
  - 6.3.2 MongoDB 文档数据模型方法
- - '####'
  - 6.3.2.1 嵌入
- - '####'
  - 6.3.2.2 引用
- - '####'
  - 6.3.2.3 数据建模的决策
- - '####'
  - 6.3.2.4 操作考虑因素
- - '####'
  - 数据生命周期管理
- - '####'
  - 索引
- - '####'
  - 分片
- - '####'
  - 大量集合
- - '####'
  - 文档增长
- - '##'
  - 6.4 小结
- - '#'
  - 7. MongoDB 架构
- - '##'
  - 7.1 核心进程
- - '###'
  - 7.1.1 `mongod`
- - '###'
  - 7.1.2 `mongo`
- - '###'
  - 7.1.3 `mongos`
- - '##'
  - 7.2 MongoDB 工具
- - '##'
  - 7.3 独立部署
- - '##'
  - 7.4 复制
- - '###'
  - 7.4.1 主/从复制
- - '###'
  - 7.4.2 副本集
- - '####'
  - 7.4.2.1 主节点与副节点
- - '####'
  - 7.4.2.2 副节点的类型
- - '####'
  - 7.4.2.3 选举
- - '####'
  - 7.4.2.4 数据复制过程
- - '####'
  - Oplog
- - '####'
  - 初始同步与复制
- - '####'
  - 副本集中的同步与故障转移
- - '####'
  - 同步 – 正常操作
- - '####'
  - 启动过程
- - '####'
  - 从谁同步？
- - '####'
  - 使写入操作与链式从节点协同工作
- - '####'
  - 故障转移
- - '####'
  - 如果节点是 Secondary 节点
- - '####'
  - 如果节点是 Primary 节点
- - '####'
  - 7.4.2.6 回滚
- - '####'
  - 7.4.2.7 一致性
- - '####'
  - 7.4.2.8 可能的复制部署架构
- - '####'
  - 7.4.2.9 扩展读取操作
- - '####'
  - 7.4.2.10 应用程序写关注点
- - '####'
  - 写关注点下写入如何发生
- - '###'
  - 7.4.3 实现高级副本集集群
- - '####'
  - 7.4.3.1 设置副本集
- - '####'
  - 7.4.3.2 移除服务器
- - '####'
  - 7.4.3.3 添加服务器
- - '####'
  - 7.4.3.4 向副本集添加仲裁器
- - '####'
  - 7.4.3.5 使用 `rs.status()` 检查状态
- - '####'
  - 7.4.3.6 强制新选举
- - '####'
  - 7.4.3.7 使用 Web 界面检查副本集状态
- - '##'
  - 7.5 分片
- - '###'
  - 7.5.1 分片组件
- - '###'
  - 7.5.2 数据分发过程
- - '####'
  - 7.5.2.1 分片键
- - '####'
  - 基于范围的分区
- - '####'
  - 基于哈希的分区
- - '####'
  - 块
- - '####'
  - 配置服务器在上述场景中的作用
- - '###'
  - 7.5.3 数据均衡过程
- - '####'
  - 7.5.3.1 块拆分
- - '####'
  - 7.5.3.2 平衡器
- - '###'
  - 7.5.4 运维操作
- - '###'
  - 7.5.5 实现分片
- - '####'
  - 7.5.5.1 设置分片集群
- - '####'
  - 7.5.5.2 创建数据库和分片集合
- - '####'
  - 7.5.5.3 添加新分片
- - '####'
  - 7.5.5.4 移除分片
- - '####'
  - 7.5.5.5 列出分片集群状态
- - '###'
  - 7.5.6 控制集合分布（基于标签的分片）
- - '####'
  - 7.5.6.1 先决条件
- - '####'
  - 7.5.6.2 标记
- - '####'
  - 无标签的分布
- - '####'
  - 通过标签扩展
- - '####'
  - 多重标签
- - '###'
  - 7.5.7 在分片环境中导入数据的注意事项
- - '####'
  - 7.5.7.1 准备工作
- - '####'
  - 7.5.7.2 预分裂数据
- - '####'
  - 7.5.7.3 决定分片块大小
- - '####'
  - 7.5.7.4 选择一个好的分片键
- - '###'
  - 7.5.8 分片监控
- - '###'
  - 7.5.9 监控配置服务器
- - '####'
  - 7.5.9.1 监控分片状态、平衡与分片块分布
- - '####'
  - 7.5.9.2 监控锁状态
- - '##'
  - 7.6 生产集群架构
- - '###'
  - 7.6.1 场景 1
- - '###'
  - 7.6.2 场景 2
- - '###'
  - 7.6.3 场景 3
- - '###'
  - 7.6.4 场景 4
- - '##'
  - 7.7 小结
- - '#'
  - 8. MongoDB 原理详解
- - '##'
  - 8.1 数据存储引擎
- - '####'
  - MMAPv1
- - '####'
  - 可插拔存储引擎 API
- - '####'
  - WiredTiger
- - '####'
  - 压缩算法
- - '##'
  - 8.2 数据文件（与 MMAPv1 相关）
- - '###'
  - 8.2.1 命名空间（`.ns` 文件）
- - '####'
  - 8.2.1.1 集合命名空间
- - '#####'
  - Extent (范围)
- - '#####'
  - 数据记录 (Data Record)
- - '#####'
  - 删除列表 (Deleted List)
- - '#####'
  - 总结
- - '####'
  - 8.2.1.2 `$freelist` (空闲列表)
- - '####'
  - 8.2.1.3 索引结构：B 树
- - '#####'
  - 键节点
- - '##'
  - 8.3 数据文件（与 WiredTiger 相关）
- - '##'
  - 8.4 读取与写入
- - '###'
  - WiredTiger 与 MongoDB 存储机制
- - '##'
  - 8.5 使用日志进行数据写入的原理
- - '##'
  - 8.6 GridFS – MongoDB 文件系统
- - '###'
  - 8.6.1 GridFS 的设计原理
- - '###'
  - 8.6.2 GridFS 的内部机制
- - '###'
  - 8.6.3 使用 GridFS
- - '####'
  - 添加对文件系统的引用
- - '####'
  - write( )
- - '####'
  - find( )
- - '####'
  - 强制分割文件
- - '####'
  - read( )
- - '####'
  - 将 GridFS 更像文件系统一样对待
- - '##'
  - 8.7 索引
- - '###'
  - 8.7.1 索引类型
- - '####'
  - '`_id` 索引'
- - '####'
  - 二级索引
- - '####'
  - 带键排序的索引
- - '####'
  - 唯一索引
- - '####'
  - dropDups
- - '####'
  - 稀疏索引
- - '####'
  - TTL 索引（生存时间）
- - '####'
  - 地理空间索引
- - '####'
  - 干草堆索引
- - '####'
  - 索引交叉
- - '###'
  - 8.7.2 行为与限制
- - '##'
  - 8.8 小结
- - '#'
  - 9. MongoDB 管理
- - '##'
  - 9.1 管理工具
- - '###'
  - 9.1.1 `mongo`
- - '###'
  - 9.1.2 第三方管理工具
- - '##'
  - 9.2 备份与恢复
- - '###'
  - 9.2.1 数据文件备份
- - '###'
  - 9.2.2 `mongodump` 和 `mongorestore`
- - '####'
  - 9.2.2.1 单数据库备份
- - '####'
  - 9.2.2.2 集合级别备份
- - '####'
  - 9.2.2.3 `mongodump` –帮助
- - '####'
  - 9.2.2.4 `mongorestore`
- - '####'
  - 9.2.2.5 还原单个数据库
- - '####'
  - 9.2.2.6 还原单个集合
- - '####'
  - 9.2.2.7 `mongorestore` –Help
- - '###'
  - 9.2.3 `fsync` 与 `锁`
- - '###'
  - 9.2.4 从节点备份
- - '##'
  - 9.3 导入与导出
- - '###'
  - 9.3.1 `mongoimport`
- - '###'
  - 9.3.2 `mongoexport`
- - '##'
  - 9.4 管理服务器
- - '###'
  - 9.4.1 启动服务器
- - '###'
  - 9.4.2 停止服务器
- - '###'
  - 9.4.3 查看日志文件
- - '###'
  - 9.4.4 服务器状态
- - '###'
  - 9.4.5 识别与修复 MongoDB
- - '###'
  - 9.4.6 识别与修复集合级数据
- - '##'
  - 9.5 监控 MongoDB
- - '###'
  - 9.5.1 `mongostat`
- - '###'
  - 9.5.2 `mongod` Web 界面
- - '###'
  - 9.5.3 第三方插件
- - '###'
  - 9.5.4 MongoDB Cloud Manager
- - '####'
  - 9.5.4.1 指标
- - '##'
  - 9.6 小结
- - '#'
  - 10. MongoDB 应用案例
- - '##'
  - 10.1 案例 1 - 性能监控
- - '###'
  - 10.1.1 模式设计
- - '###'
  - 10.1.2 运维操作
- - '####'
  - 10.1.2.1 插入数据
- - '####'
  - 10.1.2.2 批量插入
- - '####'
  - 10.1.2.3 查询性能数据
- - '####'
  - 查询 1：获取特定主机的性能数据
- - '####'
  - 查询 2：获取日期范围内的数据
- - '####'
  - 查询 3：获取特定主机在日期范围内的数据
- - '####'
  - 查询 4：按主机和日期获取性能数据的数量
- - '###'
  - 10.1.3 分片
- - '###'
  - 10.1.4 数据管理
- - '##'
  - 10.2 案例 2 – 社交网络
- - '###'
  - 10.2.1 模式设计
- - '###'
  - 10.2.2 运维操作
- - '####'
  - 10.2.2.1 查看帖子
- - '####'
  - 10.2.2.2 创建评论
- - '####'
  - 创建新帖
- - '###'
  - 10.2.3 分片
- - '##'
  - 10.3 小结
- - '#'
  - 11. MongoDB 限制
- - '##'
  - 11.1 MongoDB 空间占用过大（适用于 MMAPv1）
- - '##'
  - 11.2 内存问题（适用于 MMAPv1 存储引擎）
- - '##'
  - 11.3 32 位与 64 位系统
- - '##'
  - 11.4 BSON 文档限制
- - '##'
  - 11.5 命名空间限制
- - '##'
  - 11.6 索引限制
- - '##'
  - 11.7 固定集合限制 - 固定集合中文档的最大数量
- - '##'
  - 11.8 分片限制
- - '###'
  - 11.8.1 尽早分片以避免问题
- - '###'
  - 11.8.2 分片键无法更新
- - '###'
  - 11.8.3 分片集合限制
- - '###'
  - 11.8.4 选择正确的分片键
- - '##'
  - 11.9 安全限制
- - '###'
  - 11.9.1 默认无认证
- - '###'
  - 11.9.2 MongoDB 的进出流量未加密
- - '##'
  - 11.10 写入与读取限制
- - '###'
  - 11.10.1 区分大小写的查询
- - '###'
  - 11.10.2 字段类型敏感
- - '###'
  - 11.10.3 无 `JOIN` 操作
- - '###'
  - 11.10.4 事务支持
- - '##'
  - 11.11 MongoDB 不适用的范围
- - '##'
  - 11.12 小结
- - '#'
  - 12. MongoDB 最佳实践
- - '##'
  - 12.1 部署
- - '###'
  - 12.1.1 MongoDB 官方硬件建议
- - '###'
  - 12.1.2 几点注意事项
- - '##'
  - 12.2 编码
- - '###'
  - 数据模型选择
- - '###'
  - 避免文档无限增长
- - '###'
  - 为未来设计文档
- - '###'
  - 预设文档大小
- - '###'
  - 子文档 vs 数组
- - '###'
  - 存储计算结果
- - '###'
  - 避免使用 `$Where`
- - '###'
  - 使用正确的数据类型
- - '###'
  - 字符串大小写敏感性
- - '###'
  - 自定义 _id 主键
- - '###'
  - 只返回需要的字段
- - '###'
  - 使用 GridFS
- - '###'
  - 使用 TTL 自动删除文档
- - '###'
  - 使用固定集合
- - '###'
  - 注意数据一致性
- - '###'
  - 处理异常与故障转移
- - '##'
  - 12.3 应用响应时间优化
- - '##'
  - 12.4 数据安全
- - '##'
  - 12.5 管理
- - '##'
  - 12.6 复制延迟
- - '##'
  - 12.7 分片
- - '##'
  - 12.8 监控
- - '##'
  - 12.9 小结
- - '#'
  - MongoDB 技术概念参考
- - '##'
  - 核心概念
- - '###'
  - ACID 事务
- - '###'
  - CAP 定理
- - '###'
  - 大数据
- - '##'
  - 数据存储与建模
- - '###'
  - BSON
- - '###'
  - 数据文件
- - '###'
  - 数据模型
- - '###'
  - 数据库对象
- - '###'
  - 存储引擎
- - '###'
  - 标识符
- - '###'
  - 命名空间
- - '##'
  - CRUD 操作
- - '###'
  - 查询操作符
- - '###'
  - 查询方法
- - '###'
  - 数据操作
- - '###'
  - 查询处理
- - '##'
  - 索引
- - '###'
  - 索引类型
- - '###'
  - 索引管理
- - '###'
  - 索引行为
- - '##'
  - 复制与分片
- - '###'
  - 复制
- - '###'
  - 分片
- - '##'
  - 部署与管理
- - '###'
  - 部署
- - '###'
  - 云管理与监控
- - '###'
  - 性能与维护
- - '###'
  - 命令与工具
- - '##'
  - 编程接口与工具
- - '###'
  - 驱动与 API
- - '###'
  - 数据导入导出
- - '###'
  - 应用示例
- - '##'
  - 数据安全与一致性
- - '###'
  - 数据安全
- - '###'
  - SQL 对比
- - '##'
  - 概念与理论
- - '###'
  - NoSQL
- - '###'
  - 其他概念
