name: MySQL Database Service Revealed
name_cn: MySQL 数据库服务揭秘
slug: mysql-database-service-revealed
toc:
- - '#'
  - 引言
- - '##'
  - 目标读者
- - '##'
  - 本书结构
- - '##'
  - 如何使用本书
- - '#'
  - 第1章 云端 MySQL 入门
- - '##'
  - 联系作者
- - '##'
  - 致谢
- - '##'
  - 关于作者与技术审校者
- - '##'
  - 概述
- - '###'
  - 什么是云计算？
- - '###'
  - 为什么要迁移到云？
- - '####'
  - 提高敏捷性
- - '####'
  - 自动化
- - '##'
  - 什么是 Oracle 云基础设施？
- - '##'
  - 什么是 MySQL 数据库服务？
- - '###'
  - OCI 中的 MDS
- - '####'
  - 区域可用性
- - '####'
  - 所需的身份和访问管理策略
- - '##'
  - 数据安全
- - '##'
  - MDS 与审计服务
- - '##'
  - MDS 版本与存储引擎
- - '##'
  - 计算形状
- - '##'
  - DB 系统
- - '##'
  - MySQL HeatWave
- - '###'
  - 用例
- - '###'
  - 限制
- - '#'
  - 第2章 Oracle Cloud Infrastructure
- - '##'
  - 云服务成本预期
- - '##'
  - 小结
- - '##'
  - 服务简介
- - '###'
  - 术语
- - '####'
  - 虚拟化
- - '####'
  - 租户
- - '####'
  - 隔离区
- - '####'
  - 安全区
- - '####'
  - OCI 资源分配
- - '####'
  - 虚拟云网络
- - '####'
  - 甲骨文云标识符 (OCID)
- - '####'
  - 计算实例
- - '#####'
  - 虚拟机
- - '#####'
  - 裸机主机
- - '#####'
  - 配置方案
- - '#####'
  - 镜像
- - '#####'
  - 关于“实例”一词的说明
- - '####'
  - 配置
- - '##'
  - OCI 用户界面
- - '##'
  - 核心服务
- - '####'
  - 网络服务
- - '####'
  - 计算服务
- - '####'
  - 存储服务
- - '#####'
  - 块卷
- - '#####'
  - 本地 NVMe
- - '#####'
  - 文件存储
- - '#####'
  - 对象存储
- - '##'
  - 身份和访问管理服务
- - '##'
  - 设置您的账户
- - '###'
  - 始终免费资源
- - '###'
  - 服务使用情况和限制
- - '###'
  - OCI 教程
- - '####'
  - 创建新的 compartment
- - '####'
  - 创建虚拟云网络
- - '##'
  - 创建计算实例
- - '##'
  - 为计算实例添加块存储
- - '##'
  - 持久化挂载
- - '###'
  - 终止资源
- - '##'
  - 概要
- - '#'
  - 第3章 MySQL 简明教程
- - '##'
  - 入门指南
- - '###'
  - 连接 MySQL Shell
- - '####'
  - 功能特性
- - '##'
  - 模式支持
- - '##'
  - 建立连接
- - '###'
  - 使用 URI
- - '###'
  - 使用单独选项
- - '###'
  - 使用 SSL 连接
- - '###'
  - 连接 MySQL 客户端
- - '####'
  - 新的默认认证方式
- - '###'
  - 基本 SQL 命令
- - '###'
  - 如何获取与安装 MySQL
- - '###'
  - 配置与管理 MySQL 访问权限
- - '####'
  - 配置文件
- - '####'
  - 小型系统的 MySQL 配置文件示例
- - '####'
  - 创建用户与授予访问权限
- - '##'
  - 关于安全性的说明
- - '##'
  - 基本 SQL 命令
- - '###'
  - 创建数据库和表
- - '###'
  - 数据搜索
- - '##'
  - 查询数据
- - '###'
  - 创建数据
- - '###'
  - 更新数据
- - '###'
  - 删除数据
- - '###'
  - 使用索引
- - '###'
  - 视图
- - '###'
  - 触发器
- - '###'
  - 简单连接
- - '####'
  - 注意
- - '####'
  - 提示
- - '##'
  - 存储例程
- - '###'
  - 如何修改对象？
- - '##'
  - 连接应用程序
- - '###'
  - MySQL 数据库连接器
- - '###'
  - 示例数据库
- - '###'
  - 示例连接器：Connector/Python
- - '####'
  - 安装 Connector/Python
- - '####'
  - 检查安装
- - '##'
  - 连接到 MySQL 服务器
- - '###'
  - 示例连接器：Connector/J
- - '####'
  - 安装 Connector/J
- - '####'
  - 检查安装
- - '##'
  - 总结
- - '#'
  - 第4章 MySQL 数据库服务
- - '##'
  - 托管式 MySQL 的职责
- - '##'
  - 入门指南
- - '###'
  - 步骤 1：创建虚拟云网络
- - '###'
  - 步骤 2：创建用户组
- - '####'
  - 创建用户组
- - '##'
  - 创建用户并将其添加到组
- - '###'
  - 步骤 3：创建策略
- - '##'
  - MDS 概览
- - '##'
  - 创建你的第一个 DB 系统
- - '###'
  - 打开 DB 系统资源页面
- - '###'
  - 数据库系统详情页面
- - '####'
  - 状态与按钮
- - '####'
  - 资源菜单
- - '#####'
  - 指标
- - '##'
  - 端点
- - '##'
  - HeatWave
- - '##'
  - 备份
- - '##'
  - 通道
- - '##'
  - 工作请求
- - '##'
  - MySQL 数据库系统信息和标签
- - '###'
  - DB 系统信息标签页
- - '###'
  - 标签标签页
- - '###'
  - 停止和启动 DB 系统
- - '##'
  - 连接到您的 DB 系统
- - '###'
  - 连接机制
- - '###'
  - 通过计算实例连接
- - '####'
  - 创建计算实例
- - '###'
  - 修改 VCN – 为私有子网创建入站规则
- - '###'
  - 连接到计算实例
- - '##'
  - 连接到数据库系统
- - '###'
  - 等等，它不工作！
- - '###'
  - 使用堡垒机会话进行连接
- - '####'
  - 堡垒服务术语
- - '####'
  - 会话类型
- - '####'
  - 先决条件
- - '####'
  - 创建堡垒服务
- - '####'
  - 创建 SSH 密钥对
- - '####'
  - 创建端口转发会话
- - '####'
  - 从您的 PC 连接
- - '###'
  - 养成良好的云资源管理习惯
- - '##'
  - 总结
- - '#'
  - 第5章 备份与恢复
- - '##'
  - 可能出现什么问题？
- - '##'
  - 备份
- - '###'
  - 备份类型
- - '####'
  - 手动备份
- - '####'
  - 自动备份
- - '####'
  - 最终备份
- - '####'
  - 操作员备份
- - '###'
  - 备份详情与管理
- - '####'
  - 备份详情页面
- - '####'
  - 管理自动备份
- - '#####'
  - 启用或禁用自动备份
- - '####'
  - 创建手动备份
- - '####'
  - 编辑备份
- - '####'
  - 管理标签
- - '####'
  - 删除备份
- - '###'
  - 移动备份
- - '####'
  - 注意
- - '##'
  - 恢复
- - '###'
  - 从备份还原数据库系统
- - '####'
  - 配置源
- - '####'
  - 提供数据库系统信息
- - '####'
  - 配置网络与放置位置
- - '####'
  - 配置硬件
- - '####'
  - 配置备份计划
- - '####'
  - 摘要与最终配置
- - '####'
  - 执行还原
- - '##'
  - 总结
- - '#'
  - 第6章 时间点恢复
- - '##'
  - 概述
- - '##'
  - 设置
- - '###'
  - 注意
- - '##'
  - 恢复
- - '##'
  - 总结
- - '#'
  - 第7章 数据导入与导出
- - '##'
  - 概述
- - '###'
  - 将数据迁移到 MDS
- - '###'
  - 数据传输策略
- - '###'
  - 其他物理备份工具怎么办？
- - '###'
  - 兼容性问题
- - '####'
  - 安全性
- - '###'
  - 检查兼容性问题（发现）
- - '###'
  - 较旧的 MySQL 版本
- - '###'
  - 将数据迁移到 MDS
- - '###'
  - 使用对象存储桶
- - '####'
  - 为 OCI CLI 访问配置您的 PC
- - '####'
  - 安装并测试 OCI CLI
- - '####'
  - 创建 ObjectStore 存储桶
- - '####'
  - 导出到 ObjectStore 存储桶
- - '##'
  - 从本地 MySQL 服务器导出数据
- - '###'
  - 配置计算实例
- - '####'
  - 创建预认证请求（PAR）
- - '####'
  - 从对象存储存储桶导入到数据库系统
- - '##'
  - 使用计算实例
- - '###'
  - 使用 MySQL Shell 导出数据
- - '####'
  - 将导出的数据复制到计算实例
- - '####'
  - 在 DB 系统上导入数据
- - '###'
  - 使用堡垒网关
- - '####'
  - 设置堡垒服务
- - '####'
  - 使用 MySQL Shell 导出数据
- - '####'
  - 启动 Bastion 服务的 SSH 会话
- - '####'
  - 在 DB 系统上导入数据
- - '##'
  - 从 MDS 迁移数据
- - '###'
  - 使用 ObjectStore 存储桶
- - '####'
  - 准备你的 PC
- - '####'
  - 创建 ObjectStore 存储桶
- - '##'
  - 导出到对象存储桶
- - '##'
  - 从对象存储桶导入到本地 MySQL 服务器
- - '###'
  - 使用计算实例
- - '####'
  - 使用 MySQL Shell 导出数据
- - '####'
  - 将导出的数据复制到本地 MySQL 服务器
- - '####'
  - 在数据库系统上导入数据
- - '###'
  - 使用堡垒主机网关
- - '####'
  - 使用 MySQL Shell 导出数据
- - '####'
  - 在本地 MySQL 服务器上导入数据
- - '####'
  - 小结
- - '#'
  - 第8章 高可用性
- - '##'
  - 概述
- - '###'
  - MDS 中的高可用性
- - '####'
  - 故障转移和切换如何工作？
- - '####'
  - 故障转移的条件是什么？
- - '###'
  - 前提条件
- - '##'
  - 查找无主键的表
- - '##'
  - 添加代理主键
- - '##'
  - 如何设置 HA
- - '###'
  - 设置 HA（创建 DB 系统）
- - '##'
  - 启用高可用性（现有数据库系统）
- - '##'
  - 禁用高可用性（现有高可用性数据库系统）
- - '##'
  - 如何使用 MDS 高可用性
- - '##'
  - 限制
- - '##'
  - 高级主题
- - '##'
  - 总结
- - '#'
  - 第9章 OCI 命令行与应用程序编程界面
- - '##'
  - 入门指南
- - '###'
  - 命令行界面（CLI）
- - '####'
  - 安装 CLI
- - '####'
  - 功能
- - '####'
  - 示例用法
- - '##'
  - 管理 DB 系统
- - '###'
  - 列出 DB 系统的备份
- - '###'
  - 停止/启动 DB 系统
- - '####'
  - 创建数据库系统
- - '####'
  - 列出可用域
- - '####'
  - 更多信息
- - '##'
  - OCI API
- - '###'
  - MDS API
- - '###'
  - 示例使用
- - '##'
  - 安装 Python SDK
- - '##'
  - 入门指南
- - '###'
  - 列出 MySQL 规格
- - '###'
  - 停止/启动数据库系统
- - '###'
  - 创建数据库系统
- - '####'
  - 删除数据库系统
- - '##'
  - 摘要
- - '#'
  - 第10章 迁移至 MDS
- - '##'
  - 在使用 OCI 和 MDS 时获取帮助
- - '###'
  - 与 Oracle 的沟通
- - '##'
  - 文档
- - '###'
  - 故障排除
- - '##'
  - 检查您的数据库系统需求
- - '###'
  - 形态
- - '###'
  - 数据存储
- - '###'
  - 网络
- - '##'
  - 规划你的数据库系统
- - '##'
  - 安全最佳实践
- - '##'
  - 总结
- - '#'
  - 附录A 术语表
- - '##'
  - Application Express (APEX)
- - '#'
  - 附录B
- - '##'
  - DB 系统中的备份
- - '##'
  - 裸金属主机
- - '##'
  - 堡垒机网关
- - '###'
  - 堡垒机服务
- - '###'
  - 会话
- - '##'
  - 计费使用情况（OCI 控制台）
- - '##'
  - 块卷，OCI
- - '###'
  - 附加到 AD 的块卷
- - '##'
  - 启动卷，OCI
- - '#'
  - 附录C
- - '##'
  - 无类域间路由 (CIDR)
- - '##'
  - 云计算
- - '##'
  - 云计算规范
- - '##'
  - 云服务
- - '##'
  - 云系统
- - '##'
  - 命令行界面 (CLI)
- - '###'
  - DevOps 工具
- - '##'
  - 逗号分隔值 (CSV) 文件
- - '##'
  - 隔离区
- - '##'
  - 兼容性
- - '##'
  - 计算实例
- - '##'
  - 计算资源
- - '##'
  - Connector/J
- - '##'
  - Connector/Python
- - '##'
  - 连接器
- - '##'
  - 传统计算
- - '##'
  - 核心服务，OCI
- - '#'
  - 附录D, E
- - '##'
  - 数据库 (DB) 系统
- - '##'
  - 数据库系统
- - '##'
  - 数据定义语言 (DDL)
- - '##'
  - 数据操作语言 (DML)
- - '##'
  - 数据脱敏
- - '##'
  - 数据迁移过程
- - '##'
  - 数据迁移到 MDS
- - '##'
  - 数据对象
- - '##'
  - DB 系统备份
- - '##'
  - DB 系统恢复
- - '##'
  - DB 系统存储
- - '##'
  - 删除计划
- - '##'
  - 开发运营 (DevOps)
- - '##'
  - 文档
- - '##'
  - 域名服务 (DNS)
- - '##'
  - 转储实用程序
- - '#'
  - 附录F
- - '##'
  - 故障域 (FD)
- - '##'
  - 最终备份
- - '##'
  - 全量备份
- - '#'
  - 附录G
- - '##'
  - '`get_db_system()` 方法'
- - '##'
  - GNU 公共许可证 (GPL)
- - '##'
  - 组复制
- - '#'
  - 附录H
- - '##'
  - 硬件故障
- - '##'
  - HeatWave
- - '##'
  - 高可用性
- - '##'
  - 人为错误
- - '#'
  - 附录I
- - '##'
  - IAM 策略
- - '##'
  - 身份和访问管理 (IAM)
- - '##'
  - 增量备份
- - '##'
  - 基础设施即服务 (IaaS)
- - '##'
  - 每秒输入/输出操作数 (IOPS)
- - '##'
  - 集成开发环境 (IDE)
- - '##'
  - 互联网
- - '##'
  - 物联网 (IoT)
- - '##'
  - 互联网协议 (IP)
- - '##'
  - 传输中加密
- - '#'
  - 附录J, K
- - '##'
  - Java 数据库连接 (JDBC)
- - '##'
  - Java 开发工具包 (JDK)
- - '##'
  - Java 运行时环境 (JRE)
- - '##'
  - JavaScript 方法
- - '##'
  - JavaScript 对象表示法 (JSON)
- - '#'
  - 附录L
- - '##'
  - '`list_db_systems()` 方法'
- - '##'
  - '`list_mysql_shapes.py`'
- - '##'
  - '`list_shapes()` 方法'
- - '#'
  - 附录M
- - '##'
  - 手动备份
- - '##'
  - 主详细关系
- - '##'
  - MDS API
- - '##'
  - MDS 自动化机制
- - '##'
  - MDS 备份列表
- - '##'
  - MDS 高可用性
- - '##'
  - MDS 故障排除页面
- - '##'
  - 从 MDS 迁移数据
- - '##'
  - 数据迁移到 MDS
- - '##'
  - MySQL
- - '#'
  - 附录N
- - '##'
  - 网络差距
- - '##'
  - 网络负载均衡器
- - '##'
  - 网络接口卡 (NIC)
- - '#'
  - 附录O
- - '##'
  - 对象存储
- - '##'
  - 本地服务器数据库
- - '##'
  - 开源促进会 (OSI)
- - '##'
  - 开源软件
- - '##'
  - 操作员备份
- - '##'
  - Oracle
- - '##'
  - Oracle 云基础设施 (OCI)
- - '##'
  - Oracle 公司
- - '##'
  - Oracle FastConnect
- - '##'
  - Oracle 的自动化层
- - '#'
  - 附录P, Q
- - '##'
  - 物理备份
- - '##'
  - 平台即服务 (PaaS)
- - '##'
  - 可插拔认证模块 (PAM)
- - '##'
  - 时间点恢复 (PITR)
- - '##'
  - 策略
- - '##'
  - 预认证请求 (PAR)
- - '##'
  - 主键
- - '##'
  - 编程语言
- - '##'
  - 配置
- - '##'
  - PyCharm
- - '##'
  - Python API
- - '##'
  - Python OCI API
- - '##'
  - Python 编程语言
- - '##'
  - Python 编程风格
- - '##'
  - Python SDK
- - '##'
  - Python SDK API 参考
- - '#'
  - 附录R
- - '##'
  - 领域
- - '##'
  - 区域
- - '##'
  - 定期备份
- - '##'
  - 关系数据库管理系统 (RDBMS)
- - '##'
  - 可靠性
- - '##'
  - RemoteSigned 执行策略
- - '##'
  - 恢复 DB 系统
- - '##'
  - 恢复到新的 DB 系统
- - '#'
  - 附录S
- - '##'
  - sakila 数据库
- - '##'
  - 安全性
- - '##'
  - ShapeSummary 类
- - '##'
  - 软件即服务 (SaaS)
- - '##'
  - 软件定义网络 (SDN)
- - '##'
  - 软件开发工具包 (SDK)
- - '##'
  - SSH 密钥对
- - '##'
  - 结构化查询语言 (SQL)
- - '##'
  - Sun Microsystems
- - '##'
  - 代理键
- - '#'
  - 附录T
- - '##'
  - 标签
- - '##'
  - 租户
- - '##'
  - Thonny
- - '##'
  - 透明数据加密 (TDE)
- - '##'
  - 传输层安全 (TLS)
- - '#'
  - 附录U
- - '##'
  - 统一资源定位符 (URL)
- - '#'
  - 附录V
- - '##'
  - 虚拟云网络 (VCN)
- - '##'
  - 虚拟化
- - '##'
  - 虚拟机 (VM)
- - '##'
  - 虚拟网络
- - '##'
  - 虚拟专用网络 (VPN)
- - '##'
  - 虚拟资源
- - '#'
  - 附录W, X, Y, Z
- - '##'
  - Web 应用程序防火墙 (WAF)
